import React,{useEffect,useMemo,useRef,useState}from'react';
import{ArrowLeft,PackageSearch}from'lucide-react';
import{publicCatalogUrl,searchCatalog,type CatalogItem,type CatalogSearchResponse}from'./api';
import{getProducerStoreMetrics,type ProducerStoreMetric}from'./producerMetricsApi';
import{getProductHandlingProfiles,type ProductHandlingProfile}from'./productHandlingApi';
import CatalogProductCard from'./CatalogProductCard';
import{buildSearchUrl}from'../navigation/appUrl';

const PAGE_SIZE=20;
type Props={query:string;categorySlug?:string|null;producerId?:string|null;onBack:()=>void;onOpenProduct:(slug:string)=>void;onAddToCart:(item:CatalogItem,quantity:number)=>Promise<void>|void;};
function safeText(value:unknown,max=300){return typeof value==='string'?value.trim().slice(0,max):'';}
function safeInteger(value:unknown){return typeof value==='number'&&Number.isSafeInteger(value)&&value>=0?value:null;}
function safeRating(value:unknown){return typeof value==='number'&&Number.isFinite(value)&&value>=0&&value<=5?value:null;}
function safeCurrency(value:unknown){const currency=safeText(value,3).toUpperCase();return/^[A-Z]{3}$/.test(currency)?currency:null;}
function renderableItem(value:unknown):value is CatalogItem{const item=value as any;return Boolean(item&&typeof item==='object'&&!Array.isArray(item)&&safeText(item.id,160)&&safeText(item.slug,220)&&safeText(item.name,300)&&item.variant&&typeof item.variant==='object'&&!Array.isArray(item.variant)&&safeText(item.variant.id,160)&&safeText(item.variant.name,240)&&item.producer&&typeof item.producer==='object'&&!Array.isArray(item.producer)&&safeText(item.producer.id,160)&&safeText(item.producer.name,240)&&item.category&&typeof item.category==='object'&&!Array.isArray(item.category)&&safeText(item.category.name,160));}
function mergeCatalogItems(previous:CatalogItem[],incoming:CatalogItem[]){const unique=new Map<string,CatalogItem>();[...previous,...incoming].filter(renderableItem).forEach(item=>unique.set(`${item.id}:${item.variant.id}`,item));return Array.from(unique.values());}

export default function CatalogSearchResults({query,categorySlug=null,producerId=null,onBack,onOpenProduct,onAddToCart}:Props){
 const[sort,setSort]=useState<'relevance'|'newest'|'price_asc'|'price_desc'|'rating'>('relevance');
 const[inStock,setInStock]=useState(false);
 const[result,setResult]=useState<CatalogSearchResponse|null>(null);
 const[producerMetrics,setProducerMetrics]=useState<Record<string,ProducerStoreMetric>>({});
 const[handlingProfiles,setHandlingProfiles]=useState<Record<string,ProductHandlingProfile>>({});
 const[offset,setOffset]=useState(0);
 const[loading,setLoading]=useState(true);
 const[error,setError]=useState('');
 const requestId=useRef(0);
 async function load(nextOffset=0,append=false){const current=++requestId.current;try{setLoading(true);setError('');const next=await searchCatalog({query:query.trim()||null,categorySlug,producerId,inStock,sort,limit:PAGE_SIZE,offset:nextOffset});if(requestId.current!==current)return;if(!Array.isArray(next.items))throw new Error('Arama sonucu ürünleri doğrulanamadı.');const validItems=next.items.filter(renderableItem);if(validItems.length!==next.items.length)throw new Error('Arama sonuçlarından biri doğrulanamadı. Liste güvenli şekilde gösterilemedi.');const total=safeInteger(next.total);if(total===null||total<validItems.length)throw new Error('Arama sonucu toplamı doğrulanamadı.');const safeNext:CatalogSearchResponse={...next,total,items:validItems};const[metrics,profiles]=await Promise.all([getProducerStoreMetrics(validItems.map(item=>item.producer.id)).catch(metricsError=>{console.warn('Producer metrics unavailable for catalog search.',metricsError);return[];}),getProductHandlingProfiles(validItems.map(item=>item.id)).catch(profileError=>{console.warn('Product handling profiles unavailable for catalog search.',profileError);return[];})]);if(requestId.current!==current)return;const nextMetrics=Object.fromEntries(metrics.map(metric=>[metric.producerId,metric]));const nextProfiles=Object.fromEntries(profiles.map(row=>[row.productId,row.profile]));setProducerMetrics(previous=>append?{...previous,...nextMetrics}:nextMetrics);setHandlingProfiles(previous=>append?{...previous,...nextProfiles}:nextProfiles);setOffset(nextOffset);setResult(previous=>append&&previous?{...safeNext,items:mergeCatalogItems(previous.items,safeNext.items),offset:0,limit:previous.items.length+safeNext.items.length}:safeNext);}catch(err:any){if(requestId.current===current)setError(err?.message||'Katalog sonuçları yüklenemedi.');}finally{if(requestId.current===current)setLoading(false);}}
 useEffect(()=>{try{const canonical=buildSearchUrl({query,categorySlug,producerId});if(window.location.href!==canonical)window.history.replaceState({...window.history.state,tab:'search-results'},'',canonical);}catch(urlError){console.warn('Search route URL could not be canonicalized.',urlError);}},[query,categorySlug,producerId]);
 useEffect(()=>{void load(0,false);},[query,categorySlug,producerId,sort,inStock]);
 const items=useMemo(()=>Array.isArray(result?.items)?result!.items.filter(renderableItem):[],[result]);const total=result?safeInteger(result.total):null;const canLoadMore=total!==null&&items.length<total;const resultLabel=result&&total!==null?`${total} gerçek katalog sonucu`:result?'Sonuç sayısı doğrulanamadı':'Katalog aranıyor';
 return <section className="mx-auto max-w-7xl px-4 py-6 sm:py-8" aria-labelledby="catalog-results-title" aria-busy={loading}>
  <div className="mb-5 flex items-center gap-3"><button type="button" onClick={onBack} aria-label="Arama sonuçlarından geri dön" className="min-h-11 min-w-11 rounded-xl border p-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><ArrowLeft aria-hidden="true" className="mx-auto h-5 w-5"/></button><div className="min-w-0"><h1 id="catalog-results-title" className="truncate text-2xl font-bold text-brand-green dark:text-brand-gold">{query.trim()?`“${query.trim().slice(0,160)}” sonuçları`:'Katalog'}</h1><p className="text-sm text-gray-500" aria-live="polite">{resultLabel}</p></div></div>
  <div className="mb-5 grid gap-3 rounded-2xl border border-gray-200 bg-white p-4 dark:border-gray-800 dark:bg-gray-900 sm:grid-cols-[1fr_auto]" aria-label="Katalog sonuç kontrolleri"><label className="block"><span className="text-sm font-semibold">Sırala</span><select value={sort} onChange={e=>setSort(e.target.value as typeof sort)} className="mt-1 min-h-11 w-full rounded-xl border bg-transparent px-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><option value="relevance">En ilgili</option><option value="newest">En yeni</option><option value="price_asc">Fiyat: düşükten yükseğe</option><option value="price_desc">Fiyat: yüksekten düşüğe</option><option value="rating">Değerlendirme</option></select></label><label className="flex min-h-11 items-center gap-3 self-end rounded-xl border px-4 focus-within:ring-2 focus-within:ring-brand-gold"><input type="checkbox" checked={inStock} onChange={e=>setInStock(e.target.checked)} className="h-5 w-5"/><span className="font-semibold">Sadece stokta</span></label></div>
  <div className="sr-only" aria-live="polite" aria-atomic="true">{loading?(offset>0?'Daha fazla katalog sonucu yükleniyor':'Katalog sonuçları yükleniyor'):error?error:total===null?'Sonuç sayısı doğrulanamadı':`${total} sonuç bulundu, ${items.length} sonuç gösteriliyor`}</div>
  {error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200"><p>{error}</p><button type="button" onClick={()=>void load(0,false)} className="mt-3 min-h-11 rounded-lg border border-red-300 px-4 font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500">Tekrar dene</button></div>:null}
  {!loading&&!error&&items.length===0?<div className="rounded-2xl border border-dashed p-10 text-center"><PackageSearch aria-hidden="true" className="mx-auto h-10 w-10 text-gray-300"/><h2 className="mt-3 font-bold">Sonuç bulunamadı</h2><p className="mt-1 text-sm text-gray-500">Yazımı değiştirerek veya stok filtresini kapatarak tekrar deneyin.</p></div>:null}
  <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{items.map(item=>{const metric=producerMetrics[item.producer.id];const priceMinor=safeInteger(item.variant.priceMinor);const compareAtMinor=safeInteger(item.variant.compareAtPriceMinor);const currency=safeCurrency(item.currency);const rating=safeRating(item.averageRating);const reviewCount=safeInteger(item.reviewCount);const stock=item.availableQuantity==null?null:safeInteger(item.availableQuantity);const cardProduct={id:item.id,legacyId:item.legacyId??null,slug:item.slug,name:item.name,description:safeText(item.shortDescription,1000),shortDescription:safeText(item.shortDescription,1000),category:item.category.name,price:priceMinor===null?null:priceMinor/100,originalPrice:compareAtMinor===null?null:compareAtMinor/100,currency,image:publicCatalogUrl(item.imagePath),origin:safeText(item.origin,240)||null,unit:safeText(item.unitLabel,120)||safeText(item.variant.name,120)||null,rating,reviewCount,stock,stockMode:safeText(item.stockMode,80),is_featured:item.featured===true,preOrder:item.stockMode==='preorder',variantId:item.variant.id,variantName:item.variant.name,vendor_id:item.producer.id,producerName:item.producer.name,producerFollowerCount:metric?.followerCount??null,producerVerified:metric?.verified===true,producerOriginVerified:metric?.originVerified===true,producerStoreKind:metric?.storeKind??null,producerBadgeTone:metric?.badgeTone??null,producerStorefrontTier:metric?.storefrontTier??null,handlingProfile:handlingProfiles[item.id]??null};return<CatalogProductCard key={`${item.id}:${item.variant.id}`} product={cardProduct} onClick={()=>onOpenProduct(item.slug)} onAddToCart={(_,quantity)=>onAddToCart(item,quantity)}/>;})}</div>
  {loading?<div role="status" className="py-6 text-center text-gray-500">{offset>0?'Daha fazla ürün yükleniyor…':'Yükleniyor…'}</div>:null}
  {!loading&&canLoadMore?<button type="button" onClick={()=>void load(offset+PAGE_SIZE,true)} className="mt-6 min-h-12 w-full rounded-xl border border-brand-gold/30 font-bold text-brand-gold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">Daha fazla ürün göster</button>:null}
 </section>;
}
