import React,{useEffect,useMemo,useRef,useState}from'react';
import{ArrowLeft,Filter,PackageSearch,RotateCcw,X}from'lucide-react';
import{publicCatalogUrl,searchCatalog,type CatalogItem,type CatalogSearchResponse}from'./api';
import{catalogSearchFacets,type CatalogSearchFacets}from'./catalogSearchExperienceApi';
import CatalogProductCard from'./CatalogProductCard';
import{buildSearchUrl}from'../navigation/appUrl';

const PAGE_SIZE=20;
type Props={query:string;categorySlug?:string|null;producerId?:string|null;onBack:()=>void;onOpenProduct:(slug:string)=>void;onAddToCart:(item:CatalogItem,quantity:number)=>Promise<void>|void;};
function safeText(value:unknown,max=300){return typeof value==='string'?value.trim().slice(0,max):'';}
function safeInteger(value:unknown){return typeof value==='number'&&Number.isSafeInteger(value)&&value>=0?value:null;}
function safeRating(value:unknown){return typeof value==='number'&&Number.isFinite(value)&&value>=0&&value<=5?value:null;}
function safeCurrency(value:unknown){const currency=safeText(value,3).toUpperCase();return/^[A-Z]{3}$/.test(currency)?currency:null;}
function renderableItem(value:unknown):value is CatalogItem{const item=value as any;return Boolean(item&&typeof item==='object'&&!Array.isArray(item)&&safeText(item.id,160)&&safeText(item.slug,220)&&safeText(item.name,300)&&item.handlingProfile&&typeof item.handlingProfile==='object'&&item.variant&&typeof item.variant==='object'&&!Array.isArray(item.variant)&&safeText(item.variant.id,160)&&safeText(item.variant.name,240)&&item.producer&&typeof item.producer==='object'&&!Array.isArray(item.producer)&&safeText(item.producer.id,160)&&safeText(item.producer.name,240)&&item.category&&typeof item.category==='object'&&!Array.isArray(item.category)&&safeText(item.category.name,160));}
function mergeCatalogItems(previous:CatalogItem[],incoming:CatalogItem[]){const unique=new Map<string,CatalogItem>();[...previous,...incoming].filter(renderableItem).forEach(item=>unique.set(`${item.id}:${item.variant.id}`,item));return Array.from(unique.values());}
function priceInputToMinor(value:string){const clean=value.trim();if(!clean)return null;if(!/^\d{1,9}([,.]\d{0,2})?$/.test(clean))return Number.NaN;const amount=Number(clean.replace(',','.'));if(!Number.isFinite(amount)||amount<0)return Number.NaN;const minor=Math.round(amount*100);return Number.isSafeInteger(minor)?minor:Number.NaN;}
function formatFacetMoney(minor:number|null){if(minor==null)return'Belirsiz';try{return(minor/100).toLocaleString('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:2});}catch{return`${minor/100} TL`;}}

export default function CatalogSearchResults({query,categorySlug=null,producerId=null,onBack,onOpenProduct,onAddToCart}:Props){
 const[sort,setSort]=useState<'relevance'|'newest'|'price_asc'|'price_desc'|'rating'>('relevance');
 const[category,setCategory]=useState(categorySlug||'');const[producer,setProducer]=useState(producerId||'');const[province,setProvince]=useState('');const[district,setDistrict]=useState('');const[village,setVillage]=useState('');
 const[minPrice,setMinPrice]=useState('');const[maxPrice,setMaxPrice]=useState('');const[inStock,setInStock]=useState(false);const[featured,setFeatured]=useState(false);
 const[result,setResult]=useState<CatalogSearchResponse|null>(null);const[facets,setFacets]=useState<CatalogSearchFacets|null>(null);const[offset,setOffset]=useState(0);const[loading,setLoading]=useState(true);const[facetLoading,setFacetLoading]=useState(true);const[error,setError]=useState('');const[facetError,setFacetError]=useState('');const requestId=useRef(0);
 useEffect(()=>{setCategory(categorySlug||'');},[categorySlug]);useEffect(()=>{setProducer(producerId||'');},[producerId]);
 const minPriceMinor=useMemo(()=>priceInputToMinor(minPrice),[minPrice]);const maxPriceMinor=useMemo(()=>priceInputToMinor(maxPrice),[maxPrice]);
 const filterError=Number.isNaN(minPriceMinor)||Number.isNaN(maxPriceMinor)?'Fiyat alanlarına geçerli bir tutar girin.':minPriceMinor!=null&&maxPriceMinor!=null&&maxPriceMinor<minPriceMinor?'Maksimum fiyat minimum fiyattan düşük olamaz.':'';
 const filterKey=[query,category,producer,province,district,village,minPriceMinor,maxPriceMinor,inStock,featured,sort].join('|');
 async function load(nextOffset=0,append=false){if(filterError)return;const current=++requestId.current;try{setLoading(true);setError('');const next=await searchCatalog({query:query.trim()||null,categorySlug:category||null,producerId:producer||null,province:province||null,district:district||null,village:village||null,minPriceMinor:minPriceMinor as number|null,maxPriceMinor:maxPriceMinor as number|null,inStock,featured:featured?true:null,sort,limit:PAGE_SIZE,offset:nextOffset});if(requestId.current!==current)return;if(!Array.isArray(next.items))throw new Error('Arama sonucu ürünleri doğrulanamadı.');const validItems=next.items.filter(renderableItem);if(validItems.length!==next.items.length)throw new Error('Arama sonuçlarından biri doğrulanamadı. Liste güvenli şekilde gösterilemedi.');const total=safeInteger(next.total);if(total===null||total<validItems.length)throw new Error('Arama sonucu toplamı doğrulanamadı.');const safeNext:CatalogSearchResponse={...next,total,items:validItems};setOffset(nextOffset);setResult(previous=>append&&previous?{...safeNext,items:mergeCatalogItems(previous.items,safeNext.items),offset:0,limit:previous.items.length+safeNext.items.length}:safeNext);}catch(err:any){if(requestId.current===current)setError(err?.message||'Katalog sonuçları yüklenemedi.');}finally{if(requestId.current===current)setLoading(false);}}
 useEffect(()=>{let active=true;setFacetLoading(true);setFacetError('');catalogSearchFacets({query:query.trim().slice(0,100)||null}).then(next=>{if(active)setFacets(next);}).catch(err=>{if(active){setFacets(null);setFacetError(String(err?.message||'Katalog filtreleri yüklenemedi.'));}}).finally(()=>{if(active)setFacetLoading(false);});return()=>{active=false;};},[query]);
 useEffect(()=>{try{const canonical=buildSearchUrl({query,categorySlug:category||null,producerId:producer||null});if(window.location.href!==canonical)window.history.replaceState({...window.history.state,tab:'search-results'},'',canonical);}catch(urlError){console.warn('Search route URL could not be canonicalized.',urlError);}},[query,category,producer]);
 useEffect(()=>{if(filterError){setLoading(false);return;}void load(0,false);},[filterKey,filterError]);
 const items=useMemo(()=>Array.isArray(result?.items)?result!.items.filter(renderableItem):[],[result]);const total=result?safeInteger(result.total):null;const canLoadMore=total!==null&&items.length<total;const resultLabel=result&&total!==null?`${total} gerçek katalog sonucu`:result?'Sonuç sayısı doğrulanamadı':'Katalog aranıyor';
 const activeFilters=useMemo(()=>{const rows:{key:string;label:string;clear:()=>void}[]=[];const categoryName=facets?.categories.find(item=>item.slug===category)?.name;const producerName=facets?.producers.find(item=>item.id===producer)?.name;if(category)rows.push({key:'category',label:`Kategori: ${categoryName||category}`,clear:()=>setCategory('')});if(producer)rows.push({key:'producer',label:`Üretici: ${producerName||producer}`,clear:()=>setProducer('')});if(province)rows.push({key:'province',label:`İl: ${province}`,clear:()=>setProvince('')});if(district)rows.push({key:'district',label:`İlçe: ${district}`,clear:()=>setDistrict('')});if(village)rows.push({key:'village',label:`Köy: ${village}`,clear:()=>setVillage('')});if(minPrice)rows.push({key:'min',label:`Min ${minPrice} TL`,clear:()=>setMinPrice('')});if(maxPrice)rows.push({key:'max',label:`Maks ${maxPrice} TL`,clear:()=>setMaxPrice('')});if(inStock)rows.push({key:'stock',label:'Stokta',clear:()=>setInStock(false)});if(featured)rows.push({key:'featured',label:'Öne çıkan',clear:()=>setFeatured(false)});return rows;},[category,producer,province,district,village,minPrice,maxPrice,inStock,featured,facets]);
 function resetFilters(){setCategory('');setProducer('');setProvince('');setDistrict('');setVillage('');setMinPrice('');setMaxPrice('');setInStock(false);setFeatured(false);setSort('relevance');}
 return <section className="mx-auto max-w-7xl px-4 py-6 sm:py-8" aria-labelledby="catalog-results-title" aria-busy={loading}>
  <div className="mb-5 flex items-center gap-3"><button type="button" onClick={onBack} aria-label="Arama sonuçlarından geri dön" className="min-h-11 min-w-11 rounded-xl border p-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><ArrowLeft aria-hidden="true" className="mx-auto h-5 w-5"/></button><div className="min-w-0"><h1 id="catalog-results-title" className="truncate text-2xl font-bold text-brand-green dark:text-brand-gold">{query.trim()?`“${query.trim().slice(0,160)}” sonuçları`:'Katalog'}</h1><p className="text-sm text-gray-500" aria-live="polite">{resultLabel}</p></div></div>
  <details className="mb-4 rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-gray-900" open><summary className="flex min-h-12 cursor-pointer list-none items-center justify-between gap-3 px-4 py-3 font-bold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><span className="flex items-center gap-2"><Filter aria-hidden="true" className="h-5 w-5"/>Filtreler{activeFilters.length?<span className="rounded-full bg-brand-gold/15 px-2 py-0.5 text-xs text-brand-gold">{activeFilters.length}</span>:null}</span>{activeFilters.length?<button type="button" onClick={event=>{event.preventDefault();resetFilters();}} className="inline-flex min-h-9 items-center gap-1 rounded-lg px-2 text-xs text-gray-500 hover:bg-gray-100 dark:hover:bg-gray-800"><RotateCcw aria-hidden="true" className="h-3.5 w-3.5"/>Temizle</button>:null}</summary><div className="grid gap-3 border-t p-4 sm:grid-cols-2 lg:grid-cols-4">
   <label className="block"><span className="text-xs font-semibold text-gray-500">Kategori</span><select value={category} onChange={e=>setCategory(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border bg-transparent px-3"><option value="">Tüm kategoriler</option>{facets?.categories.map(item=><option key={item.slug} value={item.slug}>{item.name} ({item.count})</option>)}</select></label>
   <label className="block"><span className="text-xs font-semibold text-gray-500">Üretici</span><select value={producer} onChange={e=>setProducer(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border bg-transparent px-3"><option value="">Tüm üreticiler</option>{facets?.producers.map(item=><option key={item.id} value={item.id}>{item.name} ({item.count})</option>)}</select></label>
   <label className="block"><span className="text-xs font-semibold text-gray-500">İl</span><select value={province} onChange={e=>{setProvince(e.target.value);setDistrict('');setVillage('');}} className="mt-1 min-h-11 w-full rounded-xl border bg-transparent px-3"><option value="">Tüm iller</option>{facets?.provinces.map(item=><option key={item.value} value={item.value}>{item.value} ({item.count})</option>)}</select></label>
   <label className="block"><span className="text-xs font-semibold text-gray-500">İlçe</span><select value={district} onChange={e=>{setDistrict(e.target.value);setVillage('');}} className="mt-1 min-h-11 w-full rounded-xl border bg-transparent px-3"><option value="">Tüm ilçeler</option>{facets?.districts.map(item=><option key={item.value} value={item.value}>{item.value} ({item.count})</option>)}</select></label>
   <label className="block"><span className="text-xs font-semibold text-gray-500">Köy / mahalle</span><select value={village} onChange={e=>setVillage(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border bg-transparent px-3"><option value="">Tüm yerleşimler</option>{facets?.villages.map(item=><option key={item.value} value={item.value}>{item.value} ({item.count})</option>)}</select></label>
   <label className="block"><span className="text-xs font-semibold text-gray-500">Minimum fiyat (TL)</span><input inputMode="decimal" value={minPrice} onChange={e=>setMinPrice(e.target.value.slice(0,12))} placeholder={facets?.price.minMinor!=null?formatFacetMoney(facets.price.minMinor):'0'} className="mt-1 min-h-11 w-full rounded-xl border bg-transparent px-3"/></label>
   <label className="block"><span className="text-xs font-semibold text-gray-500">Maksimum fiyat (TL)</span><input inputMode="decimal" value={maxPrice} onChange={e=>setMaxPrice(e.target.value.slice(0,12))} placeholder={facets?.price.maxMinor!=null?formatFacetMoney(facets.price.maxMinor):'Sınır yok'} className="mt-1 min-h-11 w-full rounded-xl border bg-transparent px-3"/></label>
   <label className="block"><span className="text-xs font-semibold text-gray-500">Sırala</span><select value={sort} onChange={e=>setSort(e.target.value as typeof sort)} className="mt-1 min-h-11 w-full rounded-xl border bg-transparent px-3"><option value="relevance">En ilgili</option><option value="newest">En yeni</option><option value="price_asc">Fiyat: düşükten yükseğe</option><option value="price_desc">Fiyat: yüksekten düşüğe</option><option value="rating">Değerlendirme</option></select></label>
   <label className="flex min-h-11 items-center gap-3 rounded-xl border px-4"><input type="checkbox" checked={inStock} onChange={e=>setInStock(e.target.checked)} className="h-5 w-5"/><span className="font-semibold">Sadece stokta {facets?`(${facets.inStockCount})`:''}</span></label><label className="flex min-h-11 items-center gap-3 rounded-xl border px-4"><input type="checkbox" checked={featured} onChange={e=>setFeatured(e.target.checked)} className="h-5 w-5"/><span className="font-semibold">Öne çıkan ürünler</span></label>
  </div>{facetLoading?<div role="status" className="border-t px-4 py-2 text-xs text-gray-500">Filtre seçenekleri güncelleniyor…</div>:null}{facetError?<div role="alert" className="border-t px-4 py-2 text-xs text-amber-700 dark:text-amber-300">{facetError}</div>:null}{filterError?<div role="alert" className="border-t px-4 py-2 text-sm font-semibold text-red-700 dark:text-red-300">{filterError}</div>:null}</details>
  {activeFilters.length?<div className="mb-5 flex flex-wrap gap-2" aria-label="Aktif katalog filtreleri">{activeFilters.map(item=><button key={item.key} type="button" onClick={item.clear} className="inline-flex min-h-9 items-center gap-1 rounded-full bg-brand-gold/10 px-3 text-xs font-bold text-brand-green focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold dark:text-brand-gold">{item.label}<X aria-hidden="true" className="h-3.5 w-3.5"/></button>)}</div>:null}
  <div className="sr-only" aria-live="polite" aria-atomic="true">{loading?(offset>0?'Daha fazla katalog sonucu yükleniyor':'Katalog sonuçları yükleniyor'):error?error:total===null?'Sonuç sayısı doğrulanamadı':`${total} sonuç bulundu, ${items.length} sonuç gösteriliyor`}</div>
  {error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200"><p>{error}</p><button type="button" onClick={()=>void load(0,false)} className="mt-3 min-h-11 rounded-lg border border-red-300 px-4 font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500">Tekrar dene</button></div>:null}
  {!loading&&!error&&!filterError&&items.length===0?<div className="rounded-2xl border border-dashed p-10 text-center"><PackageSearch aria-hidden="true" className="mx-auto h-10 w-10 text-gray-300"/><h2 className="mt-3 font-bold">Sonuç bulunamadı</h2><p className="mt-1 text-sm text-gray-500">Arama ifadesini veya filtreleri değiştirerek tekrar deneyin.</p>{activeFilters.length?<button type="button" onClick={resetFilters} className="mt-4 min-h-11 rounded-xl border px-4 font-bold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">Tüm filtreleri temizle</button>:null}</div>:null}
  <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{items.map(item=>{const priceMinor=safeInteger(item.variant.priceMinor);const compareAtMinor=safeInteger(item.variant.compareAtPriceMinor);const currency=safeCurrency(item.currency);const rating=safeRating(item.averageRating);const reviewCount=safeInteger(item.reviewCount);const stock=item.availableQuantity==null?null:safeInteger(item.availableQuantity);const cardProduct={id:item.id,legacyId:item.legacyId??null,slug:item.slug,name:item.name,description:safeText(item.shortDescription,1000),shortDescription:safeText(item.shortDescription,1000),category:item.category.name,price:priceMinor===null?null:priceMinor/100,originalPrice:compareAtMinor===null?null:compareAtMinor/100,currency,image:publicCatalogUrl(item.imagePath),origin:safeText(item.origin,240)||null,unit:safeText(item.unitLabel,120)||safeText(item.variant.name,120)||null,rating,reviewCount,stock,stockMode:safeText(item.stockMode,80),is_featured:item.featured===true,preOrder:item.stockMode==='preorder',variantId:item.variant.id,variantName:item.variant.name,vendor_id:item.producer.id,producerName:item.producer.name,producerFollowerCount:item.producer.followerCount,producerVerified:item.producer.verified,producerOriginVerified:item.producer.originVerified,producerStoreKind:item.producer.storeKind,producerBadgeTone:item.producer.badgeTone,producerStorefrontTier:item.producer.storefrontTier,handlingProfile:item.handlingProfile};return<CatalogProductCard key={`${item.id}:${item.variant.id}`} product={cardProduct} onClick={()=>onOpenProduct(item.slug)} onAddToCart={(_,quantity)=>onAddToCart(item,quantity)}/>;})}</div>
  {loading?<div role="status" className="py-6 text-center text-gray-500">{offset>0?'Daha fazla ürün yükleniyor…':'Yükleniyor…'}</div>:null}
  {!loading&&canLoadMore?<button type="button" onClick={()=>void load(offset+PAGE_SIZE,true)} className="mt-6 min-h-12 w-full rounded-xl border border-brand-gold/30 font-bold text-brand-gold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">Daha fazla ürün göster</button>:null}
 </section>;
}
