import React,{useEffect,useMemo,useState}from'react';
import{Calendar,CheckCircle2,Gift,Heart,Minus,Plus,Share2,ShoppingCart,Star,ThumbsUp,Users}from'lucide-react';
import{buildProductUrl,shareOrCopy}from'../navigation/appUrl';

type Props={product:any;onClick:()=>void;onAddToCart:(product:any,quantity:number)=>Promise<void>|void;onToggleFavorite?:(product:any)=>Promise<void>|void;isFavorite?:boolean;onShare?:(product:any)=>Promise<void>|void;onGift?:(product:any)=>Promise<void>|void;onLike?:(product:any)=>Promise<void>|void;isLiked?:boolean;};
type SecondaryAction='favorite'|'share'|'gift'|'like'|null;
function safeNonNegativeNumber(value:unknown){return typeof value==='number'&&Number.isFinite(value)&&value>=0?value:null;}
function safeNonNegativeInteger(value:unknown){return typeof value==='number'&&Number.isSafeInteger(value)&&value>=0?value:null;}
function safeRating(value:unknown){return typeof value==='number'&&Number.isFinite(value)&&value>=0&&value<=5?value:null;}
function safeCurrency(value:unknown){const currency=typeof value==='string'?value.trim().toUpperCase():'';return/^[A-Z]{3}$/.test(currency)?currency:null;}
function safeReference(value:unknown){const reference=typeof value==='string'?value.trim():'';return reference&&reference.length<=220?reference:null;}
function messageOf(error:unknown,fallback:string){return error instanceof Error&&error.message.trim()?error.message:fallback;}

export default function CatalogProductCard({product,onClick,onAddToCart,onToggleFavorite,isFavorite=false,onShare,onGift,onLike,isLiked=false}:Props){
 const[quantity,setQuantity]=useState(1),[busy,setBusy]=useState(false),[actionBusy,setActionBusy]=useState<SecondaryAction>(null),[actionFeedback,setActionFeedback]=useState('');
 const tracked=product?.stockMode==='tracked'||product?.stockMode==='seasonal',numericStock=safeNonNegativeInteger(product?.stock),stockReady=!tracked||numericStock!==null,soldOut=tracked&&numericStock!==null&&numericStock<=0,maxQuantity=tracked&&numericStock!==null?Math.max(1,Math.min(99,numericStock)):99,preorder=product?.preOrder===true||product?.stockMode==='preorder',price=safeNonNegativeNumber(product?.price),currency=safeCurrency(product?.currency),description=typeof product?.shortDescription==='string'?product.shortDescription.trim():typeof product?.description==='string'?product.description.trim():'',productName=typeof product?.name==='string'&&product.name.trim()?product.name.trim():'Ürün',followerCount=safeNonNegativeInteger(product?.producerFollowerCount),reviewCount=safeNonNegativeInteger(product?.reviewCount),rating=safeRating(product?.rating),producerVerified=product?.producerVerified===true,producerOriginVerified=product?.producerOriginVerified===true,producerStoreKind=product?.producerStoreKind==='official'?'official':product?.producerStoreKind==='independent'?'independent':null,producerBadgeTone=product?.producerBadgeTone==='ruby'?'ruby':product?.producerBadgeTone==='blue'?'blue':producerStoreKind==='official'?'ruby':'blue',variantReference=safeReference(product?.variantId),priceReady=price!==null&&currency!==null,purchaseReady=priceReady&&stockReady&&variantReference!==null&&!soldOut,cardBusy=busy||actionBusy!==null,focusClass='focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold focus-visible:ring-offset-2 dark:focus-visible:ring-offset-gray-900';
 const trustColor=producerBadgeTone==='ruby'?'text-rose-700 dark:text-rose-300':'text-blue-600 dark:text-blue-400';
 useEffect(()=>{setQuantity(current=>Math.min(Math.max(1,current),maxQuantity));},[maxQuantity]);
 const badges=useMemo(()=>{const list:Array<{key:string;label:string;className:string}>=[];if(preorder)list.push({key:'preorder',label:'Öncelikli Erişim',className:'bg-brand-green text-brand-on-green'});if(product?.is_featured===true||product?.featured===true)list.push({key:'featured',label:'Seçkin Ürün',className:'bg-brand-gold text-brand-on-gold'});if(tracked&&numericStock!==null&&numericStock>0&&numericStock<=5)list.push({key:'low-stock',label:'Sınırlı Stok',className:'bg-white/95 text-brand-green shadow-sm dark:bg-gray-900/95 dark:text-brand-gold'});if(soldOut)list.push({key:'sold-out',label:'Tükendi',className:'bg-gray-800 text-white'});return list;},[numericStock,preorder,product?.is_featured,product?.featured,soldOut,tracked]);
 async function add(){if(cardBusy||!purchaseReady)return;try{setBusy(true);setActionFeedback('');await onAddToCart(product,quantity);}catch(error:unknown){setActionFeedback(messageOf(error,'Ürün sepete eklenemedi.'));}finally{setBusy(false);}}
 async function runAction(kind:Exclude<SecondaryAction,null>,action:(product:any)=>Promise<void>|void){if(cardBusy)return;try{setActionBusy(kind);setActionFeedback('');await action(product);}catch(error:unknown){setActionFeedback(messageOf(error,kind==='favorite'?'Favori işlemi tamamlanamadı.':kind==='gift'?'Hediye işlemi başlatılamadı.':kind==='like'?'Beğeni işlemi tamamlanamadı.':'İşlem tamamlanamadı.'));}finally{setActionBusy(null);}}
 async function shareProduct(){if(cardBusy)return;try{setActionBusy('share');setActionFeedback('');if(onShare){await onShare(product);return;}const reference=safeReference(product?.slug)||safeReference(product?.legacyId)||safeReference(product?.id);if(!reference)throw new Error('invalid_product_reference');const result=await shareOrCopy({title:productName,text:description,url:buildProductUrl(reference)});setActionFeedback(result==='copied'?'Ürün bağlantısı kopyalandı.':result==='shared'?'Paylaşım menüsü açıldı.':'Paylaşım iptal edildi.');}catch{setActionFeedback('Ürün bağlantısı paylaşılamadı. Ürün detayını açıp tekrar deneyebilirsiniz.');}finally{setActionBusy(null);}}
 function decrease(){setQuantity(current=>Math.max(1,current-1));}function increase(){setQuantity(current=>Math.min(maxQuantity,current+1));}
 const purchaseIssue=!priceReady?'Fiyat doğrulanamadı':!stockReady?'Stok doğrulanamadı':!variantReference?'Ürün seçeneği doğrulanamadı':soldOut?'Stokta yok':'';
 return <article aria-busy={cardBusy} className="flex h-full flex-col overflow-hidden rounded-[1.75rem] border border-brand-gold/10 bg-brand-card shadow-sm transition duration-300 hover:-translate-y-0.5 hover:shadow-lg">
  <div className="relative aspect-[4/3] overflow-hidden bg-gray-100 dark:bg-gray-800"><button type="button" onClick={onClick} className={`block h-full w-full ${focusClass} focus-visible:ring-inset focus-visible:ring-offset-0`} aria-label={`${productName} detayını aç`}>{product?.image?<img src={product.image} alt={`${productName} ürün görseli`} loading="lazy" decoding="async" className="h-full w-full object-cover transition-transform duration-300 motion-safe:hover:scale-[1.025]"/>:<div role="img" aria-label={`${productName} için doğrulanmış görsel henüz yayınlanmadı`} className="grid h-full place-items-center px-4 text-center text-sm text-gray-500">Doğrulanmış görsel henüz yayınlanmadı</div>}</button>{badges.length?<div className="pointer-events-none absolute left-3 top-3 flex max-w-[78%] flex-wrap gap-2">{badges.map(badge=><span key={badge.key} className={`rounded-full px-3 py-1.5 text-xs font-bold ${badge.className}`}>{badge.label}</span>)}</div>:null}<div className="absolute right-3 top-3 flex gap-2">{onToggleFavorite?<button type="button" disabled={cardBusy} onClick={event=>{event.stopPropagation();void runAction('favorite',onToggleFavorite);}} aria-label={isFavorite?`${productName} ürününü favorilerden çıkar`:`${productName} ürününü favorilere ekle`} aria-pressed={isFavorite} className={`grid min-h-11 min-w-11 place-items-center rounded-full bg-white/95 shadow-sm disabled:cursor-not-allowed disabled:opacity-60 dark:bg-gray-900/95 ${focusClass}`}><Heart aria-hidden="true" className={`h-5 w-5 ${isFavorite?'fill-red-500 text-red-500':'text-gray-700 dark:text-gray-200'}`}/></button>:null}<button type="button" disabled={cardBusy} onClick={event=>{event.stopPropagation();void shareProduct();}} aria-label={`${productName} ürününü paylaş`} className={`grid min-h-11 min-w-11 place-items-center rounded-full bg-white/95 shadow-sm disabled:cursor-not-allowed disabled:opacity-60 dark:bg-gray-900/95 ${focusClass}`}><Share2 aria-hidden="true" className="h-5 w-5"/></button></div></div>
  <div className="flex flex-1 flex-col p-5"><div className="text-[11px] font-bold uppercase tracking-[0.16em] text-brand-gold">{typeof product?.category==='string'&&product.category.trim()?product.category:'Golden Oremar'}</div><button type="button" onClick={onClick} className={`mt-1 min-h-11 text-left focus-visible:rounded-lg ${focusClass}`}><h3 className="line-clamp-2 text-lg font-black tracking-tight text-brand-text">{productName}</h3></button>{description?<p className="mt-1 line-clamp-2 text-sm leading-6 text-gray-600 dark:text-gray-300">{description}</p>:null}
   {product?.producerName?<div className="mt-3 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-gray-500"><span className="inline-flex items-center gap-1 font-semibold text-gray-700 dark:text-gray-200">{product.producerName}{producerVerified?<><CheckCircle2 aria-hidden="true" className={`h-4 w-4 ${trustColor}`}/><span className="sr-only">{producerStoreKind==='official'?'Resmi Golden Oremar mağazası':'Satıcı doğrulandı'}</span></>:null}</span>{followerCount!==null?<span className="inline-flex items-center gap-1" aria-label={`${formatNumber(followerCount)} takipçi`}><Users aria-hidden="true" className="h-4 w-4"/>{formatNumber(followerCount)}</span>:null}</div>:null}
   {product?.origin?<p className="mt-1 flex flex-wrap items-center gap-1 text-xs text-gray-500"><span className="line-clamp-1">Menşe: {product.origin}</span>{producerOriginVerified?<span className={`inline-flex items-center gap-1 font-semibold ${trustColor}`}><CheckCircle2 aria-hidden="true" className="h-3.5 w-3.5"/>Doğrulandı</span>:null}</p>:null}
   {reviewCount===null?<div className="mt-3 text-xs text-amber-700 dark:text-amber-300">Değerlendirme sayısı doğrulanamadı</div>:reviewCount>0?<div className="mt-3 flex items-center gap-1 text-sm">{rating!==null?<><Star aria-hidden="true" className="h-4 w-4 fill-brand-gold text-brand-gold"/><span className="font-semibold">{rating.toFixed(1)}</span></>:<span className="font-semibold text-amber-700 dark:text-amber-300">Puan doğrulanamadı</span>}<span className="text-gray-500">({formatNumber(reviewCount)})</span></div>:<div className="mt-3 text-xs text-gray-500">Henüz yayınlanmış değerlendirme yok</div>}
   <div className="mt-4 flex items-end justify-between gap-3"><div>{priceReady?<div className="text-xl font-black text-brand-green dark:text-brand-gold">{formatMoney(price,currency)}</div>:<div role="status" className="text-sm font-semibold text-red-700 dark:text-red-300">Fiyat doğrulanamadı</div>}{product?.unit?<div className="mt-0.5 text-xs text-gray-500">{product.unit}</div>:null}</div>{tracked?<div className={`text-xs font-semibold ${!stockReady||soldOut?'text-red-700 dark:text-red-300':'text-gray-500'}`}>{!stockReady?'Stok doğrulanamadı':soldOut?'Stokta yok':numericStock!==null&&numericStock<=5?`${formatNumber(numericStock)} adet mevcut`:'Stokta'}</div>:preorder?<div className="text-xs font-semibold text-brand-green">Öncelikli erişime açık</div>:null}</div>
   {purchaseReady?<div className="mt-4 flex items-center justify-between gap-3 rounded-2xl bg-gray-50 p-2 dark:bg-gray-800"><span className="pl-1 text-xs font-semibold text-gray-500">Adet</span><div className="flex items-center gap-1" role="group" aria-label={`${productName} adet seçimi`}><button type="button" onClick={decrease} disabled={quantity<=1||cardBusy} aria-label={`${productName} miktarını azalt`} className={`grid min-h-11 min-w-11 place-items-center rounded-full border disabled:opacity-40 ${focusClass}`}><Minus aria-hidden="true" className="h-4 w-4"/></button><span aria-live="polite" aria-label={`${quantity} adet`} className="min-w-10 text-center font-bold">{quantity}</span><button type="button" onClick={increase} disabled={quantity>=maxQuantity||cardBusy} aria-label={`${productName} miktarını artır`} className={`grid min-h-11 min-w-11 place-items-center rounded-full border disabled:opacity-40 ${focusClass}`}><Plus aria-hidden="true" className="h-4 w-4"/></button></div></div>:purchaseIssue?<div role="status" className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs font-semibold text-amber-900 dark:border-amber-900/60 dark:bg-amber-950/30 dark:text-amber-100">{purchaseIssue}. Satın alma doğrulama tamamlanana kadar kapalıdır.</div>:null}
   <div className="mt-4 grid grid-cols-[1fr_auto_auto] gap-2"><button type="button" onClick={()=>void add()} disabled={cardBusy||!purchaseReady} aria-label={!purchaseReady?`${productName} ${purchaseIssue.toLocaleLowerCase('tr-TR')} olduğu için sepete eklenemez`:preorder?`${productName} ürününü ${quantity} adet ön siparişe ekle`:`${productName} ürününü ${quantity} adet sepete ekle`} className={`min-h-12 rounded-full bg-brand-green px-4 font-bold text-brand-on-green disabled:cursor-not-allowed disabled:opacity-50 ${focusClass}`}>{preorder?<Calendar aria-hidden="true" className="mr-2 inline h-4 w-4"/>:<ShoppingCart aria-hidden="true" className="mr-2 inline h-4 w-4"/>}{busy?'Ekleniyor...':!purchaseReady?purchaseIssue:preorder?'Öncelikli Sipariş':'Sepete Ekle'}</button>{onGift?<button type="button" disabled={cardBusy||!purchaseReady} onClick={()=>void runAction('gift',onGift)} aria-label={`${productName} ürününü hediye et`} className={`grid min-h-12 min-w-12 place-items-center rounded-full border disabled:cursor-not-allowed disabled:opacity-60 ${focusClass}`}><Gift aria-hidden="true" className="h-5 w-5 text-brand-gold"/></button>:null}{onLike?<button type="button" disabled={cardBusy} onClick={()=>void runAction('like',onLike)} aria-label={isLiked?`${productName} beğenisini kaldır`:`${productName} ürününü beğen`} aria-pressed={isLiked} className={`grid min-h-12 min-w-12 place-items-center rounded-full border disabled:cursor-not-allowed disabled:opacity-60 ${focusClass}`}><ThumbsUp aria-hidden="true" className={`h-5 w-5 ${isLiked?'fill-brand-gold text-brand-gold':''}`}/></button>:null}</div>{actionFeedback?<div role="status" aria-live="polite" className="mt-2 text-xs text-gray-600 dark:text-gray-300">{actionFeedback}</div>:null}<div className="sr-only" aria-live="polite">{actionBusy==='favorite'?'Favori işlemi yapılıyor.':actionBusy==='share'?'Paylaşım hazırlanıyor.':actionBusy==='gift'?'Hediye akışı hazırlanıyor.':actionBusy==='like'?'Beğeni işlemi yapılıyor.':busy?'Sepete ekleniyor.':''}</div>
  </div>
 </article>;
}
function formatMoney(value:number,currency:string){try{return new Intl.NumberFormat('tr-TR',{style:'currency',currency}).format(value);}catch{return`${value.toFixed(2)} ${currency}`;}}
function formatNumber(value:number){if(!Number.isFinite(value)||value<0)return'Doğrulanamadı';try{return new Intl.NumberFormat('tr-TR').format(value);}catch{return String(Math.floor(value));}}