import React,{useCallback,useEffect,useMemo,useRef,useState}from'react';
import{ArrowLeft,Filter,PackageSearch,RefreshCw,RotateCcw,SlidersHorizontal,X}from'lucide-react';
import{publicCatalogUrl,searchCatalog,toggleProductFavorite,listFavoriteReferences,type CatalogItem,type CatalogSearchResponse}from'./api';
import{getCatalogSearchFacets,type CatalogSearchFacets}from'./catalogSearchFacetsApi';
import CatalogProductCard from'./CatalogProductCard';
import CatalogSearchInput from'./CatalogSearchInput';
import{useAccessibleDialog}from'../accessibility/useAccessibleDialog';
import{CUSTOMER_COPY}from'../customer-experience/customerCopy';
import{buildSearchUrl}from'../navigation/appUrl';

const PAGE_SIZE=20;
type SortMode='relevance'|'newest'|'price_asc'|'price_desc';
type Filters={categorySlug:string|null;producerId:string|null;province:string|null;district:string|null;village:string|null;minPriceMinor:number|null;maxPriceMinor:number|null;inStock:boolean;};
type Props={query:string;categorySlug?:string|null;producerId?:string|null;authenticated:boolean;onBack:()=>void;onSearch:(query:string)=>void;onVoice:()=>void;isListening?:boolean;onOpenProduct:(slug:string)=>void;onAddToCart:(item:CatalogItem,quantity:number)=>Promise<void>|void;onLoginRequired:()=>void;};
const EMPTY_FILTERS:Filters={categorySlug:null,producerId:null,province:null,district:null,village:null,minPriceMinor:null,maxPriceMinor:null,inStock:false};
function safeText(value:unknown,max=300){return typeof value==='string'?value.trim().slice(0,max):'';}
function safeInteger(value:unknown){return typeof value==='number'&&Number.isSafeInteger(value)&&value>=0?value:null;}
function safeRating(value:unknown){return typeof value==='number'&&Number.isFinite(value)&&value>=0&&value<=5?value:null;}
function safeCurrency(value:unknown){const currency=safeText(value,3).toUpperCase();return/^[A-Z]{3}$/.test(currency)?currency:null;}
function renderableItem(value:unknown):value is CatalogItem{const item=value as any;return Boolean(item&&typeof item==='object'&&!Array.isArray(item)&&safeText(item.id,160)&&safeText(item.slug,220)&&safeText(item.name,300)&&item.handlingProfile&&typeof item.handlingProfile==='object'&&item.variant&&typeof item.variant==='object'&&!Array.isArray(item.variant)&&safeText(item.variant.id,160)&&safeText(item.variant.name,240)&&item.producer&&typeof item.producer==='object'&&!Array.isArray(item.producer)&&safeText(item.producer.id,160)&&safeText(item.producer.name,240)&&item.category&&typeof item.category==='object'&&!Array.isArray(item.category)&&safeText(item.category.name,160));}
function mergeCatalogItems(previous:CatalogItem[],incoming:CatalogItem[]){const unique=new Map<string,CatalogItem>();for(const item of [...previous,...incoming])if(renderableItem(item))unique.set(`${item.id}:${item.variant.id}`,item);return Array.from(unique.values());}
function minorParam(value:string|null){if(!value||!/^\d{1,12}$/.test(value))return null;const number=Number(value);return Number.isSafeInteger(number)&&number>=0?number:null;}
function sortParam(value:string|null):SortMode{return value==='newest'||value==='price_asc'||value==='price_desc'?value:'relevance';}
function readRouteFilters(fallbackCategory:string|null,fallbackProducer:string|null){const url=new URL(window.location.href);return{filters:{categorySlug:safeText(url.searchParams.get('category'),220)||fallbackCategory,producerId:safeText(url.searchParams.get('producerId'),80)||fallbackProducer,province:safeText(url.searchParams.get('province'),160)||null,district:safeText(url.searchParams.get('district'),160)||null,village:safeText(url.searchParams.get('village'),160)||null,minPriceMinor:minorParam(url.searchParams.get('minPriceMinor')),maxPriceMinor:minorParam(url.searchParams.get('maxPriceMinor')),inStock:url.searchParams.get('inStock')==='1'} satisfies Filters,sort:sortParam(url.searchParams.get('sort'))};}
function formatPriceMinor(value:number){return new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:2}).format(value/100);}
function toInputPrice(value:number|null){return value==null?'':String(value/100);}
function fromInputPrice(value:string){const normalized=value.trim().replace(',','.');if(!normalized)return null;const number=Number(normalized);if(!Number.isFinite(number)||number<0||number>10_000_000)return null;return Math.round(number*100);}
function filterCount(filters:Filters){return Number(Boolean(filters.categorySlug))+Number(Boolean(filters.producerId))+Number(Boolean(filters.province))+Number(Boolean(filters.district))+Number(Boolean(filters.village))+Number(filters.minPriceMinor!==null||filters.maxPriceMinor!==null)+Number(filters.inStock);}

export default function CatalogSearchResults({query,categorySlug=null,producerId=null,authenticated,onBack,onSearch,onVoice,isListening=false,onOpenProduct,onAddToCart,onLoginRequired}:Props){
 const initial=useRef(readRouteFilters(categorySlug,producerId)).current;
 const[sort,setSort]=useState<SortMode>(initial.sort);
 const[filters,setFilters]=useState<Filters>(initial.filters);
 const[draftFilters,setDraftFilters]=useState<Filters>(initial.filters);
 const[result,setResult]=useState<CatalogSearchResponse|null>(null);
 const[facets,setFacets]=useState<CatalogSearchFacets|null>(null);
 const[draftFacets,setDraftFacets]=useState<CatalogSearchFacets|null>(null);
 const[offset,setOffset]=useState(0);
 const[loading,setLoading]=useState(true);
 const[previewLoading,setPreviewLoading]=useState(false);
 const[error,setError]=useState('');
 const[favoriteReferences,setFavoriteReferences]=useState<string[]>([]);
 const[favoriteOverrides,setFavoriteOverrides]=useState<Record<string,boolean>>({});
 const[favoriteStatus,setFavoriteStatus]=useState('');
 const[filterOpen,setFilterOpen]=useState(false);
 
 useEffect(()=>{if(!favoriteStatus)return;const timer=setTimeout(()=>setFavoriteStatus(''),4000);return()=>clearTimeout(timer);},[favoriteStatus]);
 const[queryDraft,setQueryDraft]=useState(query.slice(0,100));
 const requestId=useRef(0);
 const previewRequestId=useRef(0);

 useEffect(()=>{setQueryDraft(query.slice(0,100));const next=readRouteFilters(categorySlug,producerId);setFilters(next.filters);setDraftFilters(next.filters);setSort(next.sort);},[query,categorySlug,producerId]);

 const queryInput=useCallback((targetFilters:Filters,sortMode:SortMode,nextOffset:number)=>({query:query.trim()||null,categorySlug:targetFilters.categorySlug,producerId:targetFilters.producerId,province:targetFilters.province,district:targetFilters.district,village:targetFilters.village,minPriceMinor:targetFilters.minPriceMinor,maxPriceMinor:targetFilters.maxPriceMinor,inStock:targetFilters.inStock,sort:sortMode,limit:PAGE_SIZE,offset:nextOffset}),[query]);
 const facetInput=useCallback((targetFilters:Filters)=>({query:query.trim()||null,categorySlug:targetFilters.categorySlug,producerId:targetFilters.producerId,province:targetFilters.province,district:targetFilters.district,village:targetFilters.village,minPriceMinor:targetFilters.minPriceMinor,maxPriceMinor:targetFilters.maxPriceMinor,inStock:targetFilters.inStock}),[query]);

 const load=useCallback(async(nextOffset=0,append=false)=>{const current=++requestId.current;try{setLoading(true);setError('');if(append){const next=await searchCatalog(queryInput(filters,sort,nextOffset));if(requestId.current!==current)return;const validItems=next.items.filter(renderableItem);if(validItems.length!==next.items.length)throw new Error('Arama sonuçlarından biri doğrulanamadı.');const total=safeInteger(next.total);if(total===null||total<validItems.length)throw new Error('Arama sonucu toplamı doğrulanamadı.');const safeNext:CatalogSearchResponse={...next,total,items:validItems};setOffset(nextOffset);setResult(previous=>previous?{...safeNext,items:mergeCatalogItems(previous.items,safeNext.items),offset:0,limit:previous.items.length+safeNext.items.length}:safeNext);return;}const[next,nextFacets]=await Promise.all([searchCatalog(queryInput(filters,sort,0)),getCatalogSearchFacets(facetInput(filters))]);if(requestId.current!==current)return;const validItems=next.items.filter(renderableItem);if(validItems.length!==next.items.length)throw new Error('Arama sonuçlarından biri doğrulanamadı.');const total=safeInteger(next.total);if(total===null||total<validItems.length||total!==nextFacets.total)throw new Error('Arama sonucu ve filtre sayıları tutarsız.');setOffset(0);setResult({...next,total,items:validItems});setFacets(nextFacets);setDraftFacets(nextFacets);}catch{if(requestId.current===current)setError('Arama sonuçları şu anda gösterilemiyor. Lütfen yeniden deneyin.');}finally{if(requestId.current===current)setLoading(false);}},[facetInput,filters,queryInput,sort]);

 useEffect(()=>{void load(0,false);},[load]);
 useEffect(()=>{let active=true;if(authenticated){listFavoriteReferences().then(refs=>{if(active)setFavoriteReferences(refs);}).catch(()=>{if(active)setFavoriteReferences([]);});}else{setFavoriteReferences([]);}return()=>{active=false;};},[authenticated]);
 useEffect(()=>{try{const url=new URL(buildSearchUrl({query,categorySlug:filters.categorySlug,producerId:filters.producerId}));if(filters.province)url.searchParams.set('province',filters.province);if(filters.district)url.searchParams.set('district',filters.district);if(filters.village)url.searchParams.set('village',filters.village);if(filters.minPriceMinor!==null)url.searchParams.set('minPriceMinor',String(filters.minPriceMinor));if(filters.maxPriceMinor!==null)url.searchParams.set('maxPriceMinor',String(filters.maxPriceMinor));if(filters.inStock)url.searchParams.set('inStock','1');if(sort!=='relevance')url.searchParams.set('sort',sort);if(window.location.href!==url.toString())window.history.replaceState({...window.history.state,tab:'search-results'},'',url.toString());}catch(urlError){console.warn('Search route URL could not be canonicalized.',urlError);}},[query,filters,sort]);
 useEffect(()=>{if(!filterOpen)return;const current=++previewRequestId.current;setPreviewLoading(true);const timer=window.setTimeout(()=>{void getCatalogSearchFacets(facetInput(draftFilters)).then(next=>{if(previewRequestId.current===current)setDraftFacets(next);}).catch(()=>{if(previewRequestId.current===current)setDraftFacets(null);}).finally(()=>{if(previewRequestId.current===current)setPreviewLoading(false);});},180);return()=>window.clearTimeout(timer);},[filterOpen,draftFilters,facetInput]);

 const items=useMemo(()=>Array.isArray(result?.items)?result!.items.filter(renderableItem):[],[result]);
 const total=result?safeInteger(result.total):null;
 const canLoadMore=total!==null&&items.length<total;
 const activeCount=filterCount(filters);
 const resultLabel=total===null?(loading?CUSTOMER_COPY.search.searching:'Aramanız için sonuç sayısını gösteremiyoruz'):CUSTOMER_COPY.search.resultCount(total);
 const categoryName=facets?.categories.find(item=>item.slug===filters.categorySlug)?.name||filters.categorySlug;
 const producerName=facets?.producers.find(item=>item.id===filters.producerId)?.name||filters.producerId;
 const chips=useMemo(()=>{const rows:Array<{key:string;label:string;clear:()=>void}>=[];if(filters.categorySlug)rows.push({key:'category',label:categoryName||'Kategori',clear:()=>setFilters(previous=>({...previous,categorySlug:null}))});if(filters.producerId)rows.push({key:'producer',label:producerName||'Üretici',clear:()=>setFilters(previous=>({...previous,producerId:null}))});if(filters.province)rows.push({key:'province',label:filters.province,clear:()=>setFilters(previous=>({...previous,province:null,district:null,village:null}))});if(filters.district)rows.push({key:'district',label:filters.district,clear:()=>setFilters(previous=>({...previous,district:null,village:null}))});if(filters.village)rows.push({key:'village',label:filters.village,clear:()=>setFilters(previous=>({...previous,village:null}))});if(filters.minPriceMinor!==null||filters.maxPriceMinor!==null){const label=filters.minPriceMinor!==null&&filters.maxPriceMinor!==null?`${formatPriceMinor(filters.minPriceMinor)} - ${formatPriceMinor(filters.maxPriceMinor)}`:filters.minPriceMinor!==null?`${formatPriceMinor(filters.minPriceMinor)} ve üzeri`:`${formatPriceMinor(filters.maxPriceMinor!)} ve altı`;rows.push({key:'price',label,clear:()=>setFilters(previous=>({...previous,minPriceMinor:null,maxPriceMinor:null}))});}if(filters.inStock)rows.push({key:'stock',label:'Stokta',clear:()=>setFilters(previous=>({...previous,inStock:false}))});return rows;},[filters,categoryName,producerName]);
 function openFilters(){setDraftFilters(filters);setDraftFacets(facets);setFilterOpen(true);}
 function clearAll(){setFilters({...EMPTY_FILTERS});}
 function applyFilters(){setFilters({...draftFilters});setFilterOpen(false);}
 async function toggleFavorite(product:any){if(!authenticated){onLoginRequired();return;}const reference=String(product?.legacyId||product?.id||'');if(!reference)return;try{setFavoriteStatus('');const result=await toggleProductFavorite(reference);const isFavorite=result?.isFavorite===true;const ref=String(result?.productReference||reference);setFavoriteOverrides(prev=>({...prev,[ref]:isFavorite}));setFavoriteReferences(prev=>isFavorite?[...prev.filter(r=>r!==ref),ref]:prev.filter(r=>r!==ref));setFavoriteStatus(isFavorite?`✓ ${product?.name||'Ürün'} favorilerinize eklendi.`:`✓ ${product?.name||'Ürün'} favorilerinizden çıkarıldı.`);}catch{setFavoriteStatus('Favori işlemi tamamlanamadı. Lütfen tekrar deneyin.');}}

 return<section className="mx-auto max-w-7xl px-4 py-4 sm:px-6 sm:py-6" aria-labelledby="catalog-results-title" aria-busy={loading}>
  <h1 id="catalog-results-title" className="sr-only">Katalog arama sonuçları</h1>
  <div className="flex items-center gap-2"><div className="min-w-0 flex-1"><CatalogSearchInput value={queryDraft} onChange={setQueryDraft} onSubmit={onSearch} onVoice={onVoice} listening={isListening}/></div><button type="button" onClick={onBack} aria-label="Arama sonuçlarından geri dön" className="grid min-h-11 min-w-11 place-items-center rounded-xl border border-gray-200 bg-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold dark:border-gray-700 dark:bg-gray-900"><ArrowLeft aria-hidden="true" className="h-5 w-5"/></button></div>

  <p className="mt-4 text-sm font-semibold text-gray-600 dark:text-gray-300" aria-live="polite" aria-atomic="true">{resultLabel}</p>
  {favoriteStatus?<div role="status" aria-live="polite" className="mt-3 rounded-2xl border-2 border-green-200 bg-green-50 p-3 text-sm font-semibold text-green-800 dark:bg-green-950/30 dark:text-green-200">{favoriteStatus}</div>:null}
  <div className="mt-3 grid grid-cols-2 gap-2" aria-label="Arama sonucu kontrolleri"><button type="button" onClick={openFilters} className="flex min-h-11 items-center justify-center gap-2 rounded-xl border border-gray-200 bg-white px-3 font-bold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold dark:border-gray-700 dark:bg-gray-900"><Filter aria-hidden="true" className="h-4 w-4"/>Filtre{activeCount?` (${activeCount})`:''}</button><label className="relative"><span className="sr-only">Sonuçları sırala</span><SlidersHorizontal aria-hidden="true" className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2"/><select value={sort} onChange={event=>setSort(event.target.value as SortMode)} aria-label="Sırala" className="min-h-11 w-full appearance-none rounded-xl border border-gray-200 bg-white pl-9 pr-3 font-bold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold dark:border-gray-700 dark:bg-gray-900"><option value="relevance">Önerilen</option><option value="newest">En yeni</option><option value="price_asc">Fiyat: düşükten yükseğe</option><option value="price_desc">Fiyat: yüksekten düşüğe</option></select></label></div>

  {chips.length?<div className="mt-3 flex flex-wrap items-center gap-2" aria-label="Aktif filtreler">{chips.map(chip=><button type="button" key={chip.key} onClick={chip.clear} className="inline-flex min-h-11 items-center gap-2 rounded-full border-2 border-brand-gold/30 bg-brand-gold/5 px-3.5 text-sm font-semibold transition hover:bg-brand-gold/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><span>{chip.label}</span><X aria-hidden="true" className="h-3.5 w-3.5"/></button>)}<button type="button" onClick={clearAll} className="min-h-11 px-3 text-sm font-bold text-brand-green underline-offset-4 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><RotateCcw aria-hidden="true" className="mr-1.5 inline h-3.5 w-3.5"/>Tümünü temizle</button></div>:null}

  <div className="sr-only" aria-live="polite" aria-atomic="true">{loading?(offset>0?'Daha fazla ürün yükleniyor':CUSTOMER_COPY.search.searching):error?error:total===null?'Sonuç sayısını gösteremiyoruz':`${total} sonuç bulundu, ${items.length} sonuç gösteriliyor`}</div>
  {error?<div role="alert" className="mt-5 rounded-2xl border-2 border-red-200 bg-red-50 p-4 text-red-800 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200"><p className="font-semibold">{error}</p><button type="button" onClick={()=>void load(0,false)} className="mt-3 inline-flex min-h-11 items-center gap-2 rounded-xl border-2 border-red-300 bg-white px-4 font-bold dark:bg-red-950/20"><RefreshCw aria-hidden="true" className="h-4 w-4"/>Tekrar dene</button></div>:null}
  {!loading&&!error&&items.length===0?<div className="mt-5 flex min-h-60 flex-col items-center justify-center gap-4 rounded-2xl border-2 border-dashed border-gray-200 py-10 dark:border-gray-800"><div className="grid h-24 w-24 place-items-center rounded-3xl bg-gradient-to-br from-gray-100 to-gray-200 dark:from-gray-800 dark:to-gray-900"><PackageSearch aria-hidden="true" className="h-12 w-12 text-gray-400"/></div><div className="text-center"><div className="text-lg font-bold text-brand-text">{CUSTOMER_COPY.search.emptyTitle}</div><div className="mt-2 max-w-md px-4 text-sm leading-6 text-brand-muted">{CUSTOMER_COPY.search.emptyBody}</div></div>{activeCount?<button type="button" onClick={clearAll} className="mt-2 inline-flex min-h-11 items-center gap-2 rounded-xl border-2 border-gray-300 px-4 font-bold dark:border-gray-700"><RotateCcw aria-hidden="true" className="h-4 w-4"/>{CUSTOMER_COPY.search.clearFilters}</button>:null}</div>:null}

  <section className="mt-5" aria-labelledby="catalog-product-list-title"><h2 id="catalog-product-list-title" className="sr-only">Ürünler</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{items.map(item=>{const priceMinor=safeInteger(item.variant.priceMinor);const compareAtMinor=safeInteger(item.variant.compareAtPriceMinor);const currency=safeCurrency(item.currency);const rating=safeRating(item.averageRating);const reviewCount=safeInteger(item.reviewCount);const stock=item.availableQuantity==null?null:safeInteger(item.availableQuantity);const reference=String(item.legacyId||item.id);const isFavorite=favoriteOverrides[reference]??favoriteReferences.includes(reference);const cardProduct={id:item.id,legacyId:item.legacyId??null,slug:item.slug,name:item.name,description:safeText(item.shortDescription,1000),shortDescription:safeText(item.shortDescription,1000),category:item.category.name,price:priceMinor===null?null:priceMinor/100,originalPrice:compareAtMinor===null?null:compareAtMinor/100,currency,image:publicCatalogUrl(item.imagePath),origin:safeText(item.origin,240)||null,unit:safeText(item.unitLabel,120)||safeText(item.variant.name,120)||null,rating,reviewCount,stock,stockMode:safeText(item.stockMode,80),is_featured:item.featured===true,preOrder:item.stockMode==='preorder',variantId:item.variant.id,variantName:item.variant.name,vendor_id:item.producer.id,producerName:item.producer.name,producerFollowerCount:item.producer.followerCount,producerVerified:item.producer.verified,producerOriginVerified:item.producer.originVerified,producerStoreKind:item.producer.storeKind,producerBadgeTone:item.producer.badgeTone,producerStorefrontTier:item.producer.storefrontTier,handlingProfile:item.handlingProfile};return<CatalogProductCard key={`${item.id}:${item.variant.id}`} product={cardProduct} onClick={()=>onOpenProduct(item.slug)} onAddToCart={(_,quantity)=>onAddToCart(item,quantity)} onToggleFavorite={()=>void toggleFavorite(cardProduct)} isFavorite={isFavorite}/>;})}</div></section>
  {loading?<div role="status" className="py-6 text-center text-gray-500">{offset>0?'Daha fazla ürün yükleniyor…':CUSTOMER_COPY.search.searching}</div>:null}
  {!loading&&canLoadMore?<button type="button" onClick={()=>void load(offset+PAGE_SIZE,true)} className="mt-6 min-h-12 w-full rounded-xl border border-brand-gold/30 font-bold text-brand-gold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">{CUSTOMER_COPY.search.loadMore}</button>:null}

  <FilterSheet open={filterOpen} filters={draftFilters} onChange={setDraftFilters} facets={draftFacets} loading={previewLoading} onClose={()=>setFilterOpen(false)} onClear={()=>setDraftFilters({...EMPTY_FILTERS})} onApply={applyFilters}/>
 </section>;
}

function FilterSheet({open,filters,onChange,facets,loading,onClose,onClear,onApply}:{open:boolean;filters:Filters;onChange:(filters:Filters)=>void;facets:CatalogSearchFacets|null;loading:boolean;onClose:()=>void;onClear:()=>void;onApply:()=>void}){
 const dialogRef=useAccessibleDialog<HTMLDivElement>(open,onClose);
 if(!open)return null;
 const count=facets?.total;
 const activeCount=filterCount(filters);
 return<div className="fixed inset-0 z-[115] bg-black/60 backdrop-blur-sm" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="catalog-filter-title" tabIndex={-1} className="absolute inset-x-0 bottom-0 flex max-h-[88dvh] flex-col overflow-hidden rounded-t-3xl border-t-2 border-gray-200 bg-white shadow-2xl outline-none dark:border-gray-700 dark:bg-gray-950 sm:inset-y-6 sm:left-auto sm:right-6 sm:w-[28rem] sm:rounded-3xl sm:border-2"><div className="flex shrink-0 items-center justify-between gap-3 border-b-2 border-gray-200 p-5 dark:border-gray-700"><div><h2 id="catalog-filter-title" className="text-xl font-black">Filtre</h2>{activeCount>0?<p className="mt-0.5 text-xs text-gray-500">{activeCount} filtre aktif</p>:null}</div><button type="button" onClick={onClose} aria-label="Filtreleri kapat" className="grid min-h-11 min-w-11 place-items-center rounded-xl border-2 border-gray-200 transition hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold dark:border-gray-700 dark:hover:bg-gray-800"><X aria-hidden="true" className="h-5 w-5"/></button></div>
  <div className="min-h-0 flex-1 overflow-y-auto p-5">
   {loading?<div className="flex items-center justify-center gap-2 py-8 text-sm text-gray-500"><RefreshCw aria-hidden="true" className="h-4 w-4 animate-spin"/>Filtre sonuçları hesaplanıyor…</div>:<div className="space-y-5">
    {facets?.categories.length?<FilterSelect label="Kategori" value={filters.categorySlug||''} onChange={value=>onChange({...filters,categorySlug:value||null})} options={facets.categories.map(item=>({value:item.slug,label:`${item.name} (${item.count.toLocaleString('tr-TR')})`}))}/>:null}
    <fieldset><legend className="font-bold">Fiyat aralığı</legend><div className="mt-2 grid grid-cols-2 gap-2"><label className="block text-sm"><span className="block text-gray-500">En düşük</span><input type="number" min="0" step="0.01" inputMode="decimal" value={toInputPrice(filters.minPriceMinor)} onChange={event=>onChange({...filters,minPriceMinor:fromInputPrice(event.target.value)})} placeholder={facets?.price.minMinor==null?'Min':String(facets.price.minMinor/100)} className="mt-1 min-h-11 w-full rounded-xl border-2 bg-transparent px-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"/></label><label className="block text-sm"><span className="block text-gray-500">En yüksek</span><input type="number" min="0" step="0.01" inputMode="decimal" value={toInputPrice(filters.maxPriceMinor)} onChange={event=>onChange({...filters,maxPriceMinor:fromInputPrice(event.target.value)})} placeholder={facets?.price.maxMinor==null?'Max':String(facets.price.maxMinor/100)} className="mt-1 min-h-11 w-full rounded-xl border-2 bg-transparent px-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"/></label></div></fieldset>
    {facets?.producers.length?<FilterSelect label="Üretici" value={filters.producerId||''} onChange={value=>onChange({...filters,producerId:value||null})} options={facets.producers.map(item=>({value:item.id,label:`${item.name} (${item.count.toLocaleString('tr-TR')})`}))}/>:null}
    {facets?.provinces.length?<FilterSelect label="Bölge / İl" value={filters.province||''} onChange={value=>onChange({...filters,province:value||null,district:null,village:null})} options={facets.provinces.map(item=>({value:item.value,label:`${item.value} (${item.count.toLocaleString('tr-TR')})`}))}/>:null}
    {facets?.districts.length?<FilterSelect label="İlçe" value={filters.district||''} onChange={value=>onChange({...filters,district:value||null,village:null})} options={facets.districts.map(item=>({value:item.value,label:`${item.value} (${item.count.toLocaleString('tr-TR')})`}))}/>:null}
    {facets?.villages.length?<FilterSelect label="Köy" value={filters.village||''} onChange={value=>onChange({...filters,village:value||null})} options={facets.villages.map(item=>({value:item.value,label:`${item.value} (${item.count.toLocaleString('tr-TR')})`}))}/>:null}
    <label className="flex min-h-14 cursor-pointer items-center justify-between gap-3 rounded-xl border-2 border-gray-200 px-4 transition hover:bg-gray-50 dark:border-gray-700 dark:hover:bg-gray-800"><span><span className="block font-bold">Stokta olan ürünler</span><span className="block text-xs text-gray-500">Yalnızca satın alınabilir ürünleri göster</span></span><input type="checkbox" checked={filters.inStock} onChange={event=>onChange({...filters,inStock:event.target.checked})} className="h-5 w-5"/></label>
   </div>}
  </div>
  <div className="shrink-0 border-t-2 border-gray-200 bg-white p-4 pb-[calc(1rem+env(safe-area-inset-bottom,0px))] dark:border-gray-700 dark:bg-gray-950"><div className="grid grid-cols-[auto_1fr] gap-2"><button type="button" onClick={onClear} disabled={activeCount===0} title={activeCount===0 ? 'Temizlenecek filtre yok' : undefined} className="inline-flex min-h-12 items-center gap-2 rounded-xl border-2 border-gray-300 px-4 font-bold transition hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold dark:border-gray-700 dark:hover:bg-gray-800"><RotateCcw aria-hidden="true" className="h-4 w-4"/>Temizle</button><button type="button" onClick={onApply} disabled={loading||count==null} className="min-h-12 rounded-xl border-2 border-brand-green bg-brand-green px-4 font-black text-white shadow-lg transition hover:bg-green-700 disabled:cursor-not-allowed disabled:opacity-60 disabled:hover:bg-brand-green focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">{loading?'Hesaplanıyor…':count==null?'Sonuç yok':`${count.toLocaleString('tr-TR')} ürünü göster`}</button></div></div>
 </div></div>;
}
function FilterSelect({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:Array<{value:string;label:string}>}){return<label className="block"><span className="font-bold">{label}</span><select value={value} onChange={event=>onChange(event.target.value)} className="mt-2 min-h-11 w-full rounded-xl border-2 bg-transparent px-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><option value="">Tümü</option>{options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>;}
