import{userFacingError}from'../../lib/userFacingError';
import React,{useEffect,useMemo,useRef,useState}from'react';
import{ArrowLeft,ChevronRight,LayoutGrid,PackageSearch}from'lucide-react';
import{listPublicCategories,publicCatalogUrl,searchCatalog,type CatalogItem,type PublicCategory}from'./api';
import CatalogProductCard from'./CatalogProductCard';
import{categoryIcon}from'../home/components/CategoryCard';
import'./categoryDirectory.css';
import{categoryTheme}from'./ProductArtwork';
import{buildTabUrl}from'../navigation/appUrl';
import{CUSTOMER_COPY}from'../customer-experience/customerCopy';
import{NETWORK_RESTORED_EVENT}from'../resilience/useConnectivity';

const PAGE_SIZE=24;
// "?category=tumu" lists every product; no category in the address is the directory itself.
const ALL='tumu';
function categoryFromAddress():string|null{try{return safeText(new URL(window.location.href).searchParams.get('category'),220)||null;}catch{return null;}}
function goTo(category:string|null){const url=buildTabUrl('categories',{category});const depth=Number(window.history.state?.goldenOremarDepth);const nextDepth=Number.isSafeInteger(depth)&&depth>=0?depth+1:1;const state={...window.history.state,goldenOremar:true,goldenOremarDepth:nextDepth,tab:'categories'};window.history.pushState(state,'',url);window.dispatchEvent(new PopStateEvent('popstate',{state}));window.scrollTo({top:0,behavior:'auto'});}
type Props={onOpenProduct:(slug:string)=>void;onAddToCart:(item:CatalogItem,quantity:number)=>Promise<void>|void;};
function safeText(value:unknown,max=300){return typeof value==='string'?value.trim().slice(0,max):'';}
function safeInteger(value:unknown){return typeof value==='number'&&Number.isSafeInteger(value)&&value>=0?value:null;}
function safeRating(value:unknown){return typeof value==='number'&&Number.isFinite(value)&&value>=0&&value<=5?value:null;}
function safeCurrency(value:unknown){const currency=safeText(value,3).toUpperCase();return/^[A-Z]{3}$/.test(currency)?currency:null;}
function renderableCatalogItem(value:unknown):value is CatalogItem{const item=value as any;return Boolean(item&&typeof item==='object'&&!Array.isArray(item)&&safeText(item.id,160)&&safeText(item.slug,220)&&safeText(item.name,300)&&item.handlingProfile&&typeof item.handlingProfile==='object'&&item.variant&&typeof item.variant==='object'&&!Array.isArray(item.variant)&&safeText(item.variant.id,160)&&safeText(item.variant.name,240)&&item.producer&&typeof item.producer==='object'&&!Array.isArray(item.producer)&&safeText(item.producer.id,160)&&safeText(item.producer.name,240)&&item.category&&typeof item.category==='object'&&!Array.isArray(item.category)&&safeText(item.category.name,160));}
function renderableCategory(value:unknown):value is PublicCategory{const category=value as any;return Boolean(category&&typeof category==='object'&&!Array.isArray(category)&&safeText(category.id,160)&&safeText(category.slug,220)&&safeText(category.name,160)&&safeInteger(category.sortOrder)!==null&&safeInteger(category.productCount)!==null);}

export default function CategoryDirectoryScreen({onOpenProduct,onAddToCart}:Props){
 const[categories,setCategories]=useState<PublicCategory[]>([]);
 const[selected,setSelected]=useState<string|null>(categoryFromAddress);
 const[items,setItems]=useState<CatalogItem[]>([]);
 const[total,setTotal]=useState<number|null>(null);
 const[sort,setSort]=useState<'relevance'|'newest'|'price_asc'|'price_desc'|'rating'>('relevance');
 const[inStock,setInStock]=useState(false);
 const[categoryLoading,setCategoryLoading]=useState(true);
 const[productLoading,setProductLoading]=useState(true);
 const[loadingMore,setLoadingMore]=useState(false);
 const[categoryError,setCategoryError]=useState('');
 const[productError,setProductError]=useState('');
 const[loadMoreError,setLoadMoreError]=useState('');
 const requestId=useRef(0);
 async function loadCategories(){try{setCategoryLoading(true);setCategoryError('');const rows=await listPublicCategories();if(!Array.isArray(rows)||rows.some(row=>!renderableCategory(row)))throw new Error('Kategoriler şu anda gösterilemiyor. Lütfen yeniden deneyin.');setCategories(rows);setSelected(current=>current&&current!==ALL&&!rows.some(row=>row.slug===current)?null:current);}catch(err:any){setCategoryError(userFacingError(err,'Kategoriler yüklenemedi.'));}finally{setCategoryLoading(false);}}
 async function loadProducts(append=false){if(selected===null){requestId.current++;setItems([]);setTotal(null);setProductLoading(false);return;}const current=++requestId.current;const nextOffset=append?items.length:0;try{if(append)setLoadingMore(true);else setProductLoading(true);if(append)setLoadMoreError('');else setProductError('');const result=await searchCatalog({categorySlug:selected===ALL?null:selected,sort,inStock,limit:PAGE_SIZE,offset:nextOffset});if(requestId.current!==current)return;if(!Array.isArray(result.items)||result.items.some(row=>!renderableCatalogItem(row)))throw new Error('Ürünler şu anda gösterilemiyor. Lütfen yeniden deneyin.');const verifiedTotal=safeInteger(result.total);if(verifiedTotal===null||verifiedTotal<result.items.length)throw new Error('Ürünler şu anda gösterilemiyor. Lütfen yeniden deneyin.');setItems(previous=>{if(!append)return result.items;const unique=new Map<string,CatalogItem>();[...previous,...result.items].forEach(item=>unique.set(`${item.id}:${item.variant.id}`,item));return Array.from(unique.values());});setTotal(verifiedTotal);}catch(err:any){if(requestId.current===current){const message=userFacingError(err,'Kategori ürünleri yüklenemedi.');if(append)setLoadMoreError(message);else{setItems([]);setTotal(null);setProductError(message);}}}finally{if(requestId.current===current){setProductLoading(false);setLoadingMore(false);}}}
 useEffect(()=>{void loadCategories();},[]);
 // The address decides what is open, so the back button and shared links work.
 useEffect(()=>{const sync=()=>setSelected(categoryFromAddress());window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync);},[]);
 useEffect(()=>{setLoadMoreError('');void loadProducts(false);},[selected,sort,inStock]);
 useEffect(()=>{const restore=()=>{setLoadMoreError('');void Promise.all([loadCategories(),loadProducts(false)]);};window.addEventListener(NETWORK_RESTORED_EVENT,restore);return()=>window.removeEventListener(NETWORK_RESTORED_EVENT,restore);},[selected,sort,inStock]);
 const selectedCategory=categories.find(item=>item.slug===selected);const safeItems=useMemo(()=>items.filter(renderableCatalogItem),[items]);const hasMore=!productLoading&&!productError&&total!==null&&safeItems.length<total;const productSummary=CUSTOMER_COPY.category.productSummary(safeItems.length,total,productLoading);
 const totalProducts=categories.reduce((sum,category)=>sum+category.productCount,0);
 function back(){const depth=Number(window.history.state?.goldenOremarDepth);if(Number.isSafeInteger(depth)&&depth>0)window.history.back();else goTo(null);}

 // The directory: every category once, as a calm list. No products here;
 // a category opens its own page.
 if(selected===null)return <section className="mx-auto max-w-3xl px-4 py-6 sm:px-6 sm:py-10" aria-labelledby="category-directory-title">
  <div className="go-cat-head"><h1 id="category-directory-title">{CUSTOMER_COPY.category.title}</h1><p>{CUSTOMER_COPY.category.intro}</p></div>
  <div className="sr-only" aria-live="polite">{categoryLoading?'Kategoriler yükleniyor.':categoryError?categoryError:`${categories.length} kategori yüklendi.`}</div>
  {categoryError?<div role="alert" className="mt-6 rounded-2xl border-2 border-red-200 bg-red-50 p-4 font-semibold leading-relaxed text-red-800 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200"><p>{categoryError}</p><button type="button" onClick={()=>void loadCategories()} className="mt-3 min-h-11 rounded-xl border-2 border-red-300 bg-white px-4 font-bold transition-all hover:border-red-400 hover:bg-red-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500 dark:border-red-800 dark:bg-red-950/20 dark:hover:bg-red-900/30">{CUSTOMER_COPY.category.retry}</button></div>:null}
  {categoryLoading&&!categories.length?<div role="status" className="py-9 text-center text-sm font-black text-gray-500">{CUSTOMER_COPY.category.loadingCategories}</div>:null}
  <ul className="go-cat-list">{categories.map(category=>{const Icon=categoryIcon(category.icon);const theme=categoryTheme(category.slug);return<li key={category.id}><button type="button" onClick={()=>goTo(category.slug)} className="go-cat-row" style={{'--cat-from':theme.from,'--cat-ink':theme.ink} as React.CSSProperties} aria-label={`${category.name}, ${category.productCount} ürün`}><span className="go-cat-row__seal" aria-hidden="true"><Icon/></span><span className="go-cat-row__copy" aria-hidden="true"><strong>{category.name}</strong>{safeText(category.description,200)?<span>{safeText(category.description,200)}</span>:null}</span><span className="go-cat-row__count" aria-hidden="true">{category.productCount}</span><ChevronRight className="go-cat-row__go" aria-hidden="true"/></button></li>;})}</ul>
  {categories.length?<button type="button" onClick={()=>goTo(ALL)} className="go-cat-all"><LayoutGrid aria-hidden="true"/><span>{CUSTOMER_COPY.category.allProductsTitle}</span><span className="go-cat-all__count">{totalProducts}</span></button>:null}
 </section>;

 return <section className="mx-auto max-w-7xl px-4 py-6 sm:px-6 sm:py-10" aria-labelledby="category-directory-title">
  <button type="button" onClick={back} className="go-cat-back"><ArrowLeft aria-hidden="true"/>Kategoriler</button>
  <div className="sr-only" aria-live="polite">{productLoading?'Ürünler yükleniyor.':productError?productError:total===null?`${safeItems.length} ürün gösteriliyor.`:`${safeItems.length} ürün gösteriliyor. Toplam ${total} ürün var.`} {loadingMore?'Daha fazla ürün yükleniyor.':loadMoreError||''}</div>
  <div className="go-cat-toolbar"><div className="min-w-0"><h1 id="category-directory-title" className="go-cat-toolbar__title">{selectedCategory?.name||CUSTOMER_COPY.category.allProductsTitle}</h1><p className="go-cat-toolbar__summary">{[selectedCategory?.description,productSummary].filter(Boolean).join(' ')}</p></div><div className="go-cat-toolbar__controls"><label className="block min-w-0"><span className="sr-only">Ürünleri sırala</span><select value={sort} onChange={event=>setSort(event.target.value as typeof sort)} className="go-cat-toolbar__select"><option value="relevance">En ilgili</option><option value="newest">En yeni</option><option value="price_asc">Fiyat: düşükten yükseğe</option><option value="price_desc">Fiyat: yüksekten düşüğe</option><option value="rating">En yüksek puan</option></select></label><label className="go-cat-toolbar__check"><input type="checkbox" checked={inStock} onChange={event=>setInStock(event.target.checked)}/><span>Sadece stokta</span></label></div></div>
  {productError?<div role="alert" className="mt-6 rounded-2xl border-2 border-red-200 bg-red-50 p-4 font-semibold leading-relaxed text-red-800 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200"><p>{productError}</p><button type="button" onClick={()=>void loadProducts(false)} className="mt-3 min-h-11 rounded-xl border-2 border-red-300 bg-white px-4 font-bold transition-all hover:border-red-400 hover:bg-red-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500 dark:border-red-800 dark:bg-red-950/20 dark:hover:bg-red-900/30">{CUSTOMER_COPY.category.retry}</button></div>:null}
  {productLoading?<div role="status" className="py-9 text-center text-sm font-black text-gray-500">{CUSTOMER_COPY.category.loadingProducts}</div>:null}
  {!productLoading&&!productError&&!safeItems.length?<div className="mt-7 rounded-2xl border-2 border-dashed border-gray-300 p-10 text-center dark:border-gray-700"><PackageSearch aria-hidden="true" className="mx-auto h-10 w-10 text-gray-300 dark:text-gray-600"/><h3 className="mt-4 font-black text-brand-text">{CUSTOMER_COPY.category.emptyTitle}</h3><p className="mt-2 text-sm leading-relaxed text-gray-500">{CUSTOMER_COPY.category.emptyBody}</p></div>:null}
  <div id="category-products" className="mt-5 grid gap-3 sm:grid-cols-2 sm:gap-4 xl:grid-cols-3">{safeItems.map(item=>{const priceMinor=safeInteger(item.variant.priceMinor);const compareAtMinor=safeInteger(item.variant.compareAtPriceMinor);const currency=safeCurrency(item.currency);const cardProduct={id:item.id,legacyId:item.legacyId??null,slug:item.slug,makerName:item.makerName,name:item.name,description:safeText(item.shortDescription,1000),shortDescription:safeText(item.shortDescription,1000),category:item.category.name,price:priceMinor===null?null:priceMinor/100,originalPrice:compareAtMinor===null?null:compareAtMinor/100,currency,image:publicCatalogUrl(item.imagePath),origin:safeText(item.origin,240)||null,unit:safeText(item.unitLabel,120)||safeText(item.variant.name,120)||null,rating:safeRating(item.averageRating),reviewCount:safeInteger(item.reviewCount),stock:item.availableQuantity==null?null:safeInteger(item.availableQuantity),stockMode:safeText(item.stockMode,80),is_featured:item.featured===true,preOrder:item.stockMode==='preorder',variantId:item.variant.id,variantName:item.variant.name,vendor_id:item.producer.id,producerName:item.producer.name,producerFollowerCount:item.producer.followerCount,producerVerified:item.producer.verified,producerOriginVerified:item.producer.originVerified,producerStoreKind:item.producer.storeKind,producerBadgeTone:item.producer.badgeTone,producerStorefrontTier:item.producer.storefrontTier,handlingProfile:item.handlingProfile};return<CatalogProductCard key={`${item.id}:${item.variant.id}`} product={cardProduct} onClick={()=>onOpenProduct(item.slug)} onAddToCart={(_,quantity)=>onAddToCart(item,quantity)} compact/>;})}</div>
  {loadMoreError?<div role="alert" className="mt-6 rounded-2xl border-2 border-amber-200 bg-amber-50 p-4 font-semibold leading-relaxed text-amber-900 dark:border-amber-900/60 dark:bg-amber-950/30 dark:text-amber-100"><p>Daha fazla ürün yüklenemedi. Mevcut ürünler korunuyor.</p><button type="button" disabled={loadingMore} onClick={()=>void loadProducts(true)} className="mt-3 min-h-11 rounded-xl border-2 border-amber-300 bg-white px-4 font-bold transition-all hover:border-amber-400 hover:bg-amber-50 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none dark:bg-amber-950/20">Yüklemeyi tekrar dene</button></div>:null}
  {hasMore?<div className="mt-8 flex justify-center"><button type="button" disabled={loadingMore} onClick={()=>void loadProducts(true)} aria-controls="category-products" className="min-h-12 min-w-48 rounded-xl border-2 border-brand-green bg-white px-5 font-bold text-brand-green shadow-sm transition-all hover:bg-brand-green/5 disabled:cursor-not-allowed disabled:opacity-50 dark:border-brand-gold dark:bg-gray-900 dark:text-brand-gold">{loadingMore?CUSTOMER_COPY.category.loadingProducts:`${CUSTOMER_COPY.category.loadMore} (${safeItems.length}/${total})`}</button></div>:null}
 </section>;
}
