import React,{useEffect,useMemo,useRef,useState}from'react';
import{Grid2X2,PackageSearch}from'lucide-react';
import{listPublicCategories,publicCatalogUrl,searchCatalog,type CatalogItem,type PublicCategory}from'./api';
import{getProducerStoreMetrics,type ProducerStoreMetric}from'./producerMetricsApi';
import CatalogProductCard from'./CatalogProductCard';
import{NETWORK_RESTORED_EVENT}from'../resilience/useConnectivity';

const PAGE_SIZE=24;
type Props={onOpenProduct:(slug:string)=>void;onAddToCart:(item:CatalogItem,quantity:number)=>Promise<void>|void;};
function safeText(value:unknown,max=300){return typeof value==='string'?value.trim().slice(0,max):'';}
function safeInteger(value:unknown){return typeof value==='number'&&Number.isSafeInteger(value)&&value>=0?value:null;}
function safeRating(value:unknown){return typeof value==='number'&&Number.isFinite(value)&&value>=0&&value<=5?value:null;}
function safeCurrency(value:unknown){const currency=safeText(value,3).toUpperCase();return/^[A-Z]{3}$/.test(currency)?currency:null;}
function renderableCatalogItem(value:unknown):value is CatalogItem{const item=value as any;return Boolean(item&&typeof item==='object'&&!Array.isArray(item)&&safeText(item.id,160)&&safeText(item.slug,220)&&safeText(item.name,300)&&item.handlingProfile&&typeof item.handlingProfile==='object'&&item.variant&&typeof item.variant==='object'&&!Array.isArray(item.variant)&&safeText(item.variant.id,160)&&safeText(item.variant.name,240)&&item.producer&&typeof item.producer==='object'&&!Array.isArray(item.producer)&&safeText(item.producer.id,160)&&safeText(item.producer.name,240)&&item.category&&typeof item.category==='object'&&!Array.isArray(item.category)&&safeText(item.category.name,160));}
function renderableCategory(value:unknown):value is PublicCategory{const category=value as any;return Boolean(category&&typeof category==='object'&&!Array.isArray(category)&&safeText(category.id,160)&&safeText(category.slug,220)&&safeText(category.name,160)&&safeInteger(category.sortOrder)!==null&&safeInteger(category.productCount)!==null);}

export default function CategoryDirectoryScreen({onOpenProduct,onAddToCart}:Props){
 const[categories,setCategories]=useState<PublicCategory[]>([]);
 const[selected,setSelected]=useState<string|null>(null);
 const[items,setItems]=useState<CatalogItem[]>([]);
 const[producerMetrics,setProducerMetrics]=useState<Record<string,ProducerStoreMetric>>({});
 const[total,setTotal]=useState<number|null>(null);
 const[sort,setSort]=useState<'relevance'|'newest'|'price_asc'|'price_desc'|'rating'>('relevance');
 const[inStock,setInStock]=useState(false);
 const[categoryLoading,setCategoryLoading]=useState(true);
 const[productLoading,setProductLoading]=useState(true);
 const[loadingMore,setLoadingMore]=useState(false);
 const[categoryError,setCategoryError]=useState('');
 const[productError,setProductError]=useState('');
 const[loadMoreError,setLoadMoreError]=useState('');
 const requestId=useRef(0);
 async function loadCategories(){try{setCategoryLoading(true);setCategoryError('');const rows=await listPublicCategories();if(!Array.isArray(rows)||rows.some(row=>!renderableCategory(row)))throw new Error('Kategori listesi sunucudan doğrulanamadı.');setCategories(rows);setSelected(current=>current&&!rows.some(row=>row.slug===current)?null:current);}catch(err:any){setCategoryError(err?.message||'Kategoriler yüklenemedi.');}finally{setCategoryLoading(false);}}
 async function loadProducts(append=false){const current=++requestId.current;const nextOffset=append?items.length:0;try{if(append)setLoadingMore(true);else setProductLoading(true);if(append)setLoadMoreError('');else setProductError('');const result=await searchCatalog({categorySlug:selected,sort,inStock,limit:PAGE_SIZE,offset:nextOffset});if(requestId.current!==current)return;if(!Array.isArray(result.items)||result.items.some(row=>!renderableCatalogItem(row)))throw new Error('Kategori ürünlerinden biri doğrulanamadı.');const verifiedTotal=safeInteger(result.total);if(verifiedTotal===null||verifiedTotal<result.items.length)throw new Error('Kategori ürün toplamı doğrulanamadı.');const metrics=await getProducerStoreMetrics(result.items.map(item=>item.producer.id)).catch(error=>{console.warn('Producer metrics unavailable for category directory.',error);return[];});if(requestId.current!==current)return;const nextMetrics=Object.fromEntries(metrics.map(metric=>[metric.producerId,metric]));setProducerMetrics(previous=>append?{...previous,...nextMetrics}:nextMetrics);setItems(previous=>{if(!append)return result.items;const unique=new Map<string,CatalogItem>();[...previous,...result.items].forEach(item=>unique.set(`${item.id}:${item.variant.id}`,item));return Array.from(unique.values());});setTotal(verifiedTotal);}catch(err:any){if(requestId.current===current){const message=err?.message||'Kategori ürünleri yüklenemedi.';if(append)setLoadMoreError(message);else{setItems([]);setProducerMetrics({});setTotal(null);setProductError(message);}}}finally{if(requestId.current===current){setProductLoading(false);setLoadingMore(false);}}}
 useEffect(()=>{void loadCategories();},[]);
 useEffect(()=>{setLoadMoreError('');void loadProducts(false);},[selected,sort,inStock]);
 useEffect(()=>{const restore=()=>{setLoadMoreError('');void Promise.all([loadCategories(),loadProducts(false)]);};window.addEventListener(NETWORK_RESTORED_EVENT,restore);return()=>window.removeEventListener(NETWORK_RESTORED_EVENT,restore);},[selected,sort,inStock]);
 const selectedCategory=categories.find(item=>item.slug===selected);const safeItems=useMemo(()=>items.filter(renderableCatalogItem),[items]);const hasMore=!productLoading&&!productError&&total!==null&&safeItems.length<total;const productSummary=productLoading?'Ürünler güncelleniyor…':total===null?`${safeItems.length} ürün gösteriliyor, toplam doğrulanamadı`:`${safeItems.length} / ${total} ürün gösteriliyor`;
 return <section className="mx-auto max-w-7xl px-4 py-6 sm:px-6 sm:py-8" aria-labelledby="category-directory-title">
  <div className="mx-auto max-w-2xl text-center"><h1 id="category-directory-title" className="text-2xl font-bold tracking-tight text-brand-green dark:text-brand-gold sm:text-3xl">Kategoriler</h1><p className="mt-2 text-sm leading-6 text-gray-500">Yalnız aktif kategoriler ve doğrulanmış üreticilerin yayındaki ürünleri gösterilir.</p></div>
  <div className="sr-only" aria-live="polite">{categoryLoading?'Kategoriler yükleniyor.':categoryError?categoryError:`${categories.length} kategori yüklendi.`} {productLoading?'Ürünler yükleniyor.':productError?productError:total===null?`${safeItems.length} ürün gösteriliyor. Toplam sayı doğrulanamadı.`:`${safeItems.length} ürün gösteriliyor. Toplam ${total} ürün var.`} {loadingMore?'Daha fazla ürün yükleniyor.':loadMoreError||''}</div>
  {categoryError?<div role="alert" className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-red-800 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200"><p>{categoryError}</p><button type="button" onClick={()=>void loadCategories()} className="mt-3 min-h-11 rounded-xl border border-red-300 px-4 font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500 dark:border-red-800">Tekrar dene</button></div>:null}
  <div className="mt-6 overflow-x-auto pb-3 [scrollbar-width:thin]" aria-label="Ürün kategorileri"><div className="flex min-w-max gap-3" role="list"><div role="listitem"><button type="button" onClick={()=>setSelected(null)} aria-pressed={selected===null} aria-controls="category-products" className={`group min-h-24 min-w-[180px] rounded-2xl border p-3 text-left shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold ${selected===null?'border-brand-gold bg-brand-gold/10 shadow-brand-gold/10':'border-gray-200 bg-white dark:border-gray-800 dark:bg-gray-900'}`}><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-green/10 text-brand-green dark:bg-brand-gold/10 dark:text-brand-gold"><Grid2X2 aria-hidden="true" className="h-5 w-5"/></span><span className="mt-3 block font-bold">Tüm Ürünler</span><span className="mt-1 block text-xs text-gray-500">Canlı katalogdaki tüm seçki</span></button></div>{categoryLoading?<div role="status" className="flex min-h-24 min-w-[210px] items-center rounded-2xl border border-dashed px-4 text-sm text-gray-500">Kategoriler yükleniyor…</div>:null}{categories.map(category=>{const categoryImage=publicCatalogUrl(category.imagePath);return<div key={category.id} role="listitem"><button type="button" onClick={()=>setSelected(category.slug)} aria-pressed={selected===category.slug} aria-controls="category-products" className={`group relative min-h-24 min-w-[220px] max-w-[260px] overflow-hidden rounded-2xl border p-3 text-left shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold ${selected===category.slug?'border-brand-gold bg-brand-gold/10 shadow-brand-gold/10':'border-gray-200 bg-white dark:border-gray-800 dark:bg-gray-900'}`}><span className="flex items-start gap-3">{categoryImage?<img src={categoryImage} alt="" loading="lazy" decoding="async" className="h-14 w-14 shrink-0 rounded-xl object-cover ring-1 ring-black/5 dark:ring-white/10"/>:<span aria-hidden="true" className="flex h-14 w-14 shrink-0 items-center justify-center rounded-xl bg-brand-green/10 text-lg font-bold text-brand-green dark:bg-brand-gold/10 dark:text-brand-gold">{category.name.charAt(0).toLocaleUpperCase('tr-TR')}</span>}<span className="min-w-0 flex-1"><span className="line-clamp-1 font-bold text-brand-text">{category.name}</span><span className="mt-1 block text-xs font-semibold text-brand-green dark:text-brand-gold">{category.productCount} ürün</span>{category.description?<span className="mt-1 line-clamp-2 block text-xs leading-4 text-gray-500">{category.description}</span>:null}</span></span></button></div>;})}</div></div>
  <div className="mt-5 rounded-2xl border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-900 sm:flex sm:items-end sm:justify-between sm:gap-4"><div className="min-w-0"><h2 className="text-xl font-bold text-brand-text">{selectedCategory?.name||'Tüm Ürünler'}</h2>{selectedCategory?.description?<p className="mt-1 max-w-2xl text-sm leading-5 text-gray-500">{selectedCategory.description}</p>:null}<p className="mt-1 text-sm text-gray-500">{productSummary}</p></div><div className="mt-4 grid gap-3 sm:mt-0 sm:grid-cols-[minmax(190px,1fr)_auto]"><label className="block"><span className="sr-only">Ürünleri sırala</span><select value={sort} onChange={event=>setSort(event.target.value as typeof sort)} className="min-h-12 w-full rounded-xl border border-gray-200 bg-transparent px-3 font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold dark:border-gray-700"><option value="relevance">En ilgili</option><option value="newest">En yeni</option><option value="price_asc">Fiyat: düşükten yükseğe</option><option value="price_desc">Fiyat: yüksekten düşüğe</option><option value="rating">En yüksek puan</option></select></label><label className="flex min-h-12 items-center gap-3 rounded-xl border border-gray-200 px-4 focus-within:ring-2 focus-within:ring-brand-gold dark:border-gray-700"><input type="checkbox" checked={inStock} onChange={event=>setInStock(event.target.checked)} className="h-5 w-5"/><span className="font-semibold">Sadece stokta</span></label></div></div>
  {productError?<div role="alert" className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-red-800 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200"><p>{productError}</p><button type="button" onClick={()=>void loadProducts(false)} className="mt-3 min-h-11 rounded-xl border border-red-300 px-4 font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500">Tekrar dene</button></div>:null}
  {productLoading?<div role="status" className="py-8 text-center text-sm font-medium text-gray-500">Ürünler yükleniyor…</div>:null}
  {!productLoading&&!productError&&!safeItems.length?<div className="mt-5 rounded-2xl border border-dashed border-gray-300 p-9 text-center dark:border-gray-700"><PackageSearch aria-hidden="true" className="mx-auto h-10 w-10 text-gray-300 dark:text-gray-600"/><h3 className="mt-3 font-bold text-brand-text">Bu seçimde ürün bulunamadı</h3><p className="mt-1 text-sm text-gray-500">Başka bir kategori seçin veya stok filtresini kapatın.</p></div>:null}
  <div id="category-products" className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{safeItems.map(item=>{const metric=producerMetrics[item.producer.id];const priceMinor=safeInteger(item.variant.priceMinor);const compareAtMinor=safeInteger(item.variant.compareAtPriceMinor);const currency=safeCurrency(item.currency);const cardProduct={id:item.id,legacyId:item.legacyId??null,slug:item.slug,name:item.name,description:safeText(item.shortDescription,1000),shortDescription:safeText(item.shortDescription,1000),category:item.category.name,price:priceMinor===null?null:priceMinor/100,originalPrice:compareAtMinor===null?null:compareAtMinor/100,currency,image:publicCatalogUrl(item.imagePath),origin:safeText(item.origin,240)||null,unit:safeText(item.unitLabel,120)||safeText(item.variant.name,120)||null,rating:safeRating(item.averageRating),reviewCount:safeInteger(item.reviewCount),stock:item.availableQuantity==null?null:safeInteger(item.availableQuantity),stockMode:safeText(item.stockMode,80),is_featured:item.featured===true,preOrder:item.stockMode==='preorder',variantId:item.variant.id,variantName:item.variant.name,vendor_id:item.producer.id,producerName:item.producer.name,producerFollowerCount:metric?.followerCount??null,producerVerified:metric?.verified===true,producerOriginVerified:metric?.originVerified===true,producerStoreKind:metric?.storeKind??null,producerBadgeTone:metric?.badgeTone??null,producerStorefrontTier:metric?.storefrontTier??null,handlingProfile:item.handlingProfile};return<CatalogProductCard key={`${item.id}:${item.variant.id}`} product={cardProduct} onClick={()=>onOpenProduct(item.slug)} onAddToCart={(_,quantity)=>onAddToCart(item,quantity)}/>;})}</div>
  {loadMoreError?<div role="alert" className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-900 dark:border-amber-900/60 dark:bg-amber-950/30 dark:text-amber-100"><p>Daha fazla ürün yüklenemedi. Mevcut ürünler korunuyor.</p><p className="mt-1 text-xs opacity-80">{loadMoreError}</p><button type="button" disabled={loadingMore} onClick={()=>void loadProducts(true)} className="mt-3 min-h-11 rounded-xl border border-amber-300 px-4 font-semibold disabled:opacity-50">Yüklemeyi tekrar dene</button></div>:null}
  {hasMore?<div className="mt-7 flex justify-center"><button type="button" disabled={loadingMore} onClick={()=>void loadProducts(true)} aria-controls="category-products" className="min-h-12 min-w-48 rounded-xl border border-brand-green px-5 font-bold text-brand-green disabled:cursor-not-allowed disabled:opacity-50 dark:border-brand-gold dark:text-brand-gold">{loadingMore?'Daha fazla ürün yükleniyor…':`Daha fazla ürün göster (${safeItems.length}/${total})`}</button></div>:null}
 </section>;
}
