import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,CheckCircle2,Copy,ExternalLink,Gift,Heart,MapPin,Minus,PackageCheck,Plus,QrCode,ShoppingCart,Star,Store,Truck}from'lucide-react';
import{getProductDetail,listProductReviews,publicCatalogUrl,toggleProductFavorite}from'./api';
import{setCartItem}from'../cart/api';

type Props={
 reference:string;
 authenticated:boolean;
 favoriteReferences?:string[];
 onFavoriteChanged?:(reference:string,isFavorite:boolean)=>void;
 onBack:()=>void;
 onLoginRequired:()=>void;
 onCartChanged?:()=>Promise<void>|void;
 onGift:(reference:string)=>void;
 onProducer:(id:string,slug:string,name:string)=>void;
};

const exportText:Record<string,string>={
 not_configured:'Bu ürün için otomatik yurtdışı gönderim henüz yapılandırılmadı. Uluslararası sipariş için manuel teklif ve uygunluk kontrolü gerekir.',
 domestic_only:'Bu ürün şu anda Türkiye içi otomatik siparişe açık; yurtdışı gönderim otomatik olarak sunulmuyor.',
 manual_review:'Yurtdışı sipariş ürün ve hedef ülkeye göre manuel inceleme gerektirir.',
 eligible:'Ürün ihracat uygunluk kontrolünden geçmiş. Nihai teslimat ücreti ve ülke koşulları ödeme öncesinde ayrıca doğrulanmalıdır.',
};

export default function ProductDetailScreen({reference,authenticated,favoriteReferences=[],onFavoriteChanged,onBack,onLoginRequired,onCartChanged,onGift,onProducer}:Props){
 const[detail,setDetail]=useState<any>(null);const[reviews,setReviews]=useState<any>(null);const[variantId,setVariantId]=useState('');const[quantity,setQuantity]=useState(1);const[selectedImagePath,setSelectedImagePath]=useState('');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[status,setStatus]=useState('');const[favoriteOverride,setFavoriteOverride]=useState<boolean|null>(null);
 async function load(){try{setLoading(true);setError('');setStatus('');setFavoriteOverride(null);const product=await getProductDetail(reference);setDetail(product);const defaultVariant=product?.variants?.find((v:any)=>v.default&&v.available!==false)||product?.variants?.find((v:any)=>v.available!==false)||product?.variants?.[0];setVariantId(defaultVariant?.id||'');setQuantity(1);const firstImage=product?.images?.find((i:any)=>i.primary)||product?.images?.[0];setSelectedImagePath(firstImage?.path||'');if(product?.id){try{setReviews(await listProductReviews(product.id,20,0));}catch{setReviews(null);}}else setReviews(null);}catch(err:any){setError(err?.message||'Ürün bilgileri yüklenemedi.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[reference]);
 const variant=useMemo(()=>detail?.variants?.find((item:any)=>item.id===variantId)||null,[detail,variantId]);
 const images=Array.isArray(detail?.images)?detail.images:[];const selectedImage=images.find((item:any)=>item.path===selectedImagePath)||images.find((item:any)=>item.primary)||images[0]||null;
 const activeBadges=Array.isArray(detail?.trustBadges)?detail.trustBadges.filter((badge:any)=>badge.active):[];const hasTraceability=!!detail?.traceability?.hasReleasedBatches;
 const tracked=detail?.stockMode==='tracked'||detail?.stockMode==='seasonal';const variantStock=typeof variant?.availableQuantity==='number'?Math.max(0,Number(variant.availableQuantity)):null;const soldOut=variant?.available===false||(tracked&&variantStock!==null&&variantStock<=0);const maxQuantity=tracked&&variantStock!==null?Math.max(1,Math.min(99,variantStock)):99;const preorder=detail?.stockMode==='preorder';
 useEffect(()=>{setQuantity(current=>Math.max(1,Math.min(current,maxQuantity)));},[variantId,maxQuantity]);
 const favoriteReference=String(detail?.legacyId||detail?.id||'');const isFavorite=favoriteOverride??favoriteReferences.includes(favoriteReference);const featureItems=normalizeFeatures(detail?.features);const tags=Array.isArray(detail?.tags)?detail.tags.filter((tag:any)=>typeof tag==='string'&&tag.trim()).slice(0,12):[];
 async function addToCart(){if(!authenticated){onLoginRequired();return;}if(!variant?.id||soldOut)return;try{setBusy(true);setError('');setStatus('');await setCartItem({variantId:variant.id,quantity});await onCartChanged?.();setStatus(`${quantity} adet ürün sepetinize eklendi.`);}catch(err:any){setError(err?.message||'Ürün sepete eklenemedi.');}finally{setBusy(false);}}
 async function favorite(){if(!authenticated){onLoginRequired();return;}try{setBusy(true);setError('');const result=await toggleProductFavorite(detail.slug||detail.id);const next=!!result?.isFavorite;const ref=String(result?.productReference||favoriteReference);setFavoriteOverride(next);onFavoriteChanged?.(ref,next);setStatus(next?'Ürün favorilerinize eklendi.':'Ürün favorilerinizden çıkarıldı.');}catch(err:any){setError(err?.message||'Favori işlemi tamamlanamadı.');}finally{setBusy(false);}}
 async function copyTrace(code:string){try{await navigator.clipboard.writeText(code);setStatus(`Takip kodu kopyalandı: ${code}`);}catch{setError('Takip kodu kopyalanamadı.');}}
 if(loading)return<div role="status" className="mx-auto max-w-5xl p-8 text-center">Ürün yükleniyor…</div>;
 if(error&&!detail)return<div className="mx-auto max-w-5xl p-6"><div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{error}</div><button onClick={onBack} className="mt-4 min-h-11 rounded-xl border px-4">Geri dön</button></div>;
 if(!detail)return null;
 return<article className="mx-auto max-w-6xl px-4 py-6 sm:py-8">
  <button onClick={onBack} className="mb-5 min-h-11 rounded-xl border px-4 font-semibold"><ArrowLeft className="mr-2 inline h-4 w-4"/>Geri</button>
  {error?<div role="alert" className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>:null}{status?<div role="status" aria-live="polite" className="mb-4 rounded-xl bg-green-50 p-3 text-sm text-green-800">{status}</div>:null}
  <div className="grid gap-7 lg:grid-cols-2">
   <section aria-label="Ürün görselleri">
    <div className="overflow-hidden rounded-3xl border bg-gray-100 dark:bg-gray-800">{selectedImage?.path?<img src={publicCatalogUrl(selectedImage.path)} alt={selectedImage.alt||detail.name} className="aspect-square h-full w-full object-cover"/>:<div className="grid aspect-square place-items-center text-gray-400">Görsel henüz eklenmedi</div>}</div>
    {images.length>1?<div className="mt-3 grid grid-cols-4 gap-2 sm:grid-cols-6">{images.slice(0,12).map((img:any,index:number)=><button key={`${img.path}:${index}`} onClick={()=>setSelectedImagePath(img.path)} aria-label={`${detail.name} görseli ${index+1} görüntüle`} aria-pressed={selectedImage?.path===img.path} className={`overflow-hidden rounded-xl border focus-visible:ring-2 focus-visible:ring-brand-gold ${selectedImage?.path===img.path?'border-brand-gold ring-2 ring-brand-gold/30':''}`}><img src={publicCatalogUrl(img.path)} alt={img.alt||`${detail.name} küçük görsel ${index+1}`} className="aspect-square h-full w-full object-cover"/></button>)}</div>:null}
   </section>
   <section>
    <div className="text-sm font-semibold text-brand-gold">{detail.category?.name}</div><h1 className="mt-1 text-3xl font-bold text-brand-green dark:text-brand-gold">{detail.name}</h1>{detail.shortDescription?<p className="mt-3 leading-7 text-gray-600 dark:text-gray-300">{detail.shortDescription}</p>:null}
    {detail.producer?.id?<button onClick={()=>onProducer(detail.producer.id,detail.producer.slug,detail.producer.name)} className="mt-4 flex min-h-12 w-full items-center gap-3 rounded-2xl border p-3 text-left"><Store className="h-5 w-5 text-brand-gold"/><span className="min-w-0 flex-1"><span className="block font-bold">{detail.producer.name}</span><span className="block text-sm text-gray-500">{detail.producer.locationLabel||detail.origin||'Türkiye'}</span></span></button>:null}
    {activeBadges.length?<div className="mt-4 flex flex-wrap gap-2">{activeBadges.map((badge:any)=><span key={badge.key} className="inline-flex items-center gap-1 rounded-full bg-green-50 px-3 py-1.5 text-xs font-bold text-green-800"><CheckCircle2 className="h-3.5 w-3.5"/>{badge.label}</span>)}</div>:null}
    {tags.length?<div className="mt-3 flex flex-wrap gap-2">{tags.map((tag:string)=><span key={tag} className="rounded-full border px-3 py-1 text-xs text-gray-600 dark:text-gray-300">{tag}</span>)}</div>:null}
    {variant?<div className="mt-6 rounded-2xl bg-gray-50 p-4 dark:bg-gray-800"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-2xl font-bold text-brand-green dark:text-brand-gold">{money(variant.priceMinor,detail.currency)}</div>{Number(variant.compareAtPriceMinor||0)>Number(variant.priceMinor||0)?<div className="text-sm text-gray-400 line-through">{money(variant.compareAtPriceMinor,detail.currency)}</div>:null}</div><div className={`text-sm font-semibold ${soldOut?'text-red-700':'text-green-700'}`}>{soldOut?'Stokta yok':tracked&&variantStock!==null?`${variantStock} adet stokta`:preorder?'Ön siparişe açık':'Satışa açık'}</div></div>{preorder&&detail.preorderLeadDays?<div className="mt-2 text-sm text-gray-500">Tahmini hazırlık: {detail.preorderLeadDays} gün</div>:null}</div>:null}
    <fieldset className="mt-5"><legend className="font-bold">Seçenek</legend><div className="mt-2 space-y-2">{detail.variants?.map((item:any)=>{const itemStock=typeof item.availableQuantity==='number'?Math.max(0,Number(item.availableQuantity)):null;return<label key={item.id} className={`flex min-h-12 items-center justify-between gap-3 rounded-xl border p-3 ${variantId===item.id?'border-brand-gold bg-brand-gold/5':''}`}><span className="flex items-center gap-3"><input type="radio" name="variant" value={item.id} checked={variantId===item.id} disabled={item.available===false} onChange={()=>setVariantId(item.id)}/><span><span className="block font-semibold">{item.name}</span><span className="block text-xs text-gray-500">{item.available===false?'Satışta değil':tracked&&itemStock!==null?`${itemStock} adet mevcut`:'Satışta'}{Number(item.weightGrams||0)>0?` • ${formatWeight(item.weightGrams)}`:''}</span></span></span><span className="text-right font-bold">{money(item.priceMinor,detail.currency)}{Number(item.compareAtPriceMinor||0)>Number(item.priceMinor||0)?<span className="block text-xs font-normal text-gray-400 line-through">{money(item.compareAtPriceMinor,detail.currency)}</span>:null}</span></label>;})}</div></fieldset>
    <div className="mt-4" role="group" aria-labelledby="product-quantity-label"><span id="product-quantity-label" className="text-sm font-semibold">Adet</span><div className="mt-2 flex flex-wrap items-center gap-3"><div className="inline-flex items-center rounded-xl border bg-white dark:bg-gray-900" aria-label={`${detail.name} adet seçimi`}><button type="button" onClick={()=>setQuantity(current=>Math.max(1,current-1))} disabled={soldOut||busy||quantity<=1} aria-label={`${detail.name} miktarını azalt`} className="grid min-h-11 min-w-11 place-items-center rounded-l-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold disabled:cursor-not-allowed disabled:opacity-40"><Minus aria-hidden="true" className="h-4 w-4"/></button><output aria-live="polite" aria-atomic="true" aria-label={`${quantity} adet`} className="min-w-12 px-2 text-center font-bold tabular-nums">{quantity}</output><button type="button" onClick={()=>setQuantity(current=>Math.min(maxQuantity,current+1))} disabled={soldOut||busy||quantity>=maxQuantity} aria-label={`${detail.name} miktarını artır`} className="grid min-h-11 min-w-11 place-items-center rounded-r-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold disabled:cursor-not-allowed disabled:opacity-40"><Plus aria-hidden="true" className="h-4 w-4"/></button></div><span className="text-xs text-gray-500">En fazla {maxQuantity} adet</span></div></div>
    <div className="mt-5 grid grid-cols-[1fr_auto_auto] gap-2"><button onClick={()=>void addToCart()} disabled={busy||!variant||soldOut} className="min-h-12 rounded-xl bg-brand-green px-4 font-bold text-white disabled:opacity-50"><ShoppingCart className="mr-2 inline h-5 w-5"/>{busy?'İşleniyor…':soldOut?'Tükendi':preorder?'Ön Siparişe Ekle':'Sepete Ekle'}</button><button onClick={()=>void favorite()} disabled={busy} aria-label={isFavorite?'Favorilerden çıkar':'Favorilere ekle'} aria-pressed={isFavorite} className="min-h-12 min-w-12 rounded-xl border px-3"><Heart className={`mx-auto h-5 w-5 ${isFavorite?'fill-red-500 text-red-500':''}`}/></button><button onClick={()=>authenticated?onGift(detail.slug||detail.id):onLoginRequired()} aria-label="Hediye et" className="min-h-12 min-w-12 rounded-xl border px-3"><Gift className="mx-auto h-5 w-5 text-brand-gold"/></button></div>
   </section>
  </div>
  <div className="mt-8 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border p-5"><h2 className="text-xl font-bold">Ürün Hikâyesi</h2><p className="mt-3 whitespace-pre-wrap leading-7 text-gray-600 dark:text-gray-300">{detail.story||detail.description||'Ürün hikâyesi henüz eklenmedi.'}</p>{detail.origin?<div className="mt-4 flex items-center gap-2 text-sm font-semibold"><MapPin className="h-4 w-4 text-brand-gold"/>{detail.origin}</div>:null}</section><ShippingReadiness detail={detail} variant={variant}/></div>
  {featureItems.length?<section className="mt-5 rounded-2xl border p-5"><h2 className="text-xl font-bold">Ürün Özellikleri</h2><ul className="mt-3 grid gap-2 sm:grid-cols-2">{featureItems.map((item,index)=><li key={`${item}-${index}`} className="rounded-xl bg-gray-50 p-3 text-sm dark:bg-gray-800">{item}</li>)}</ul></section>:null}
  <section className="mt-5 rounded-2xl border p-5"><h2 className="flex items-center gap-2 text-xl font-bold"><QrCode className="h-5 w-5 text-brand-gold"/>Lot / İzlenebilirlik</h2>{hasTraceability?<div className="mt-3 space-y-3">{detail.traceability.batches.map((batch:any)=><article key={batch.traceCode} className="rounded-xl bg-gray-50 p-4 dark:bg-gray-800"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-bold">{batch.batchCode||'Yayınlanmış lot'}</div><div className="mt-1 text-sm text-gray-500">Takip kodu: {batch.traceCode}</div></div><button onClick={()=>void copyTrace(batch.traceCode)} className="min-h-11 rounded-lg border px-3 text-sm font-semibold"><Copy className="mr-2 inline h-4 w-4"/>Kodu kopyala</button></div><div className="mt-3 grid gap-2 text-sm sm:grid-cols-2">{batch.harvestDate?<div>Hasat: {dateOnly(batch.harvestDate)}</div>:null}{batch.productionDate?<div>Üretim: {dateOnly(batch.productionDate)}</div>:null}{batch.packagingDate?<div>Paketleme: {dateOnly(batch.packagingDate)}</div>:null}{batch.bestBeforeDate?<div>Tavsiye edilen tüketim: {dateOnly(batch.bestBeforeDate)}</div>:null}{batch.origin?<div>Menşe: {joinLocation(batch.origin)}</div>:null}{batch.productionMethod?<div>Üretim yöntemi: {batch.productionMethod}</div>:null}</div>{batch.publicNotes?<p className="mt-3 text-sm text-gray-600 dark:text-gray-300">{batch.publicNotes}</p>:null}</article>)}</div>:<p className="mt-3 text-sm text-gray-500">Bu ürün için henüz müşteriye yayınlanmış lot bulunmuyor. İncelemedeki veya doğrulanmamış lot bilgileri gösterilmez.</p>}</section>
  {Array.isArray(detail.certifications)&&detail.certifications.length?<section className="mt-5 rounded-2xl border p-5"><h2 className="flex items-center gap-2 text-xl font-bold"><PackageCheck className="h-5 w-5 text-brand-gold"/>Doğrulanmış Sertifikalar</h2><div className="mt-3 space-y-2">{detail.certifications.map((cert:any,index:number)=><div key={`${cert.type}:${index}`} className="rounded-xl bg-gray-50 p-3 text-sm dark:bg-gray-800"><div><strong>{cert.type}</strong>{cert.issuer?` • ${cert.issuer}`:''}</div>{cert.certificateNumber?<div className="mt-1 text-gray-500">Belge no: {cert.certificateNumber}</div>:null}{cert.expiresAt?<div className="mt-1 text-gray-500">Geçerlilik: {dateOnly(cert.expiresAt)}</div>:null}{safeUrl(cert.verificationUrl)?<a href={safeUrl(cert.verificationUrl)} target="_blank" rel="noopener noreferrer" className="mt-2 inline-flex min-h-11 items-center font-semibold text-brand-green">Belgeyi doğrula<ExternalLink className="ml-2 h-4 w-4"/></a>:null}</div>)}</div></section>:null}
  <section className="mt-5 rounded-2xl border p-5"><h2 className="text-xl font-bold">Müşteri Yorumları</h2><div className="mt-2 flex items-center gap-2"><Star className="h-5 w-5 fill-brand-gold text-brand-gold"/><strong>{Number(reviews?.summary?.averageRating||detail.reviewSummary?.averageRating||0).toFixed(1)}</strong><span className="text-sm text-gray-500">({reviews?.summary?.count||detail.reviewSummary?.count||0} yorum)</span></div>{reviews?.items?.length?<div className="mt-4 space-y-3">{reviews.items.map((review:any)=><article key={review.id} className="rounded-xl bg-gray-50 p-4 dark:bg-gray-800"><div className="flex items-center justify-between gap-3"><strong>{review.reviewerName}</strong><span className="text-sm">{review.rating}/5</span></div>{review.verifiedPurchase?<div className="mt-1 text-xs font-bold text-green-700">Doğrulanmış satın alma</div>:null}{review.title?<h3 className="mt-2 font-semibold">{review.title}</h3>:null}<p className="mt-1 text-sm leading-6 text-gray-600 dark:text-gray-300">{review.body}</p>{review.merchantReply?<div className="mt-3 rounded-lg border-l-4 border-brand-gold bg-white p-3 text-sm dark:bg-gray-900"><strong>Üretici yanıtı:</strong> {review.merchantReply}</div>:null}</article>)}</div>:<p className="mt-4 text-sm text-gray-500">Henüz yayınlanmış müşteri yorumu yok.</p>}</section>
 </article>;
}

function ShippingReadiness({detail,variant}:{detail:any;variant:any}){const exp=detail?.export||{};const status=String(exp.status||'not_configured');const missingWeight=!Number(variant?.weightGrams||0);return<section className="rounded-2xl border p-5"><h2 className="flex items-center gap-2 text-xl font-bold"><Truck className="h-5 w-5 text-brand-gold"/>Teslimat / Yurtdışı Hazırlığı</h2><p className="mt-3 text-sm leading-6 text-gray-600 dark:text-gray-300">{exportText[status]||'Yurtdışı gönderim durumu ürün bazında doğrulanmalıdır.'}</p>{status==='eligible'&&missingWeight?<div role="status" className="mt-3 rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">Seçili varyantın sevkiyat ağırlığı henüz kayıtlı değil; otomatik uluslararası kargo fiyatı hesaplanamaz.</div>:null}<dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-gray-50 p-3 dark:bg-gray-800"><dt className="text-gray-500">Bozulabilir ürün</dt><dd className="font-semibold">{exp.perishable?'Evet':'Hayır'}</dd></div><div className="rounded-xl bg-gray-50 p-3 dark:bg-gray-800"><dt className="text-gray-500">Soğuk zincir</dt><dd className="font-semibold">{exp.requiresColdChain?'Gerekli':'Gerekli değil'}</dd></div>{Number(exp.shelfLifeDays||0)>0?<div className="rounded-xl bg-gray-50 p-3 dark:bg-gray-800"><dt className="text-gray-500">Raf ömrü</dt><dd className="font-semibold">{exp.shelfLifeDays} gün</dd></div>:null}{Number(variant?.weightGrams||0)>0?<div className="rounded-xl bg-gray-50 p-3 dark:bg-gray-800"><dt className="text-gray-500">Sevkiyat ağırlığı</dt><dd className="font-semibold">{formatWeight(variant.weightGrams)}</dd></div>:null}</dl></section>;}
function normalizeFeatures(value:any):string[]{if(Array.isArray(value))return value.flatMap(item=>typeof item==='string'&&item.trim()?[item.trim()]:item&&typeof item==='object'?Object.entries(item).map(([k,v])=>`${labelKey(k)}: ${formatValue(v)}`):[]).slice(0,24);if(value&&typeof value==='object')return Object.entries(value).map(([k,v])=>`${labelKey(k)}: ${formatValue(v)}`).filter(item=>!item.endsWith(': ')).slice(0,24);return[];}
function labelKey(value:string){return value.replace(/[_-]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}
function formatValue(value:any){if(Array.isArray(value))return value.map(String).join(', ');if(value===true)return'Evet';if(value===false)return'Hayır';if(value==null)return'';if(typeof value==='object')return JSON.stringify(value);return String(value);}
function money(minor:any,currency:string){try{return new Intl.NumberFormat('tr-TR',{style:'currency',currency:String(currency||'TRY').toUpperCase()}).format(Number(minor||0)/100);}catch{return`${(Number(minor||0)/100).toFixed(2)} ${currency||'TRY'}`;}}
function formatWeight(grams:any){const value=Number(grams||0);return value>=1000?`${(value/1000).toLocaleString('tr-TR',{maximumFractionDigits:2})} kg`:`${value.toLocaleString('tr-TR')} g`;}
function dateOnly(value?:string|null){if(!value)return'—';try{return new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium'}).format(new Date(`${value}T12:00:00`));}catch{return value;}}
function safeUrl(value?:string|null){if(!value)return'';try{const url=new URL(value);return url.protocol==='https:'?url.toString():'';}catch{return'';}}
function joinLocation(origin:any){return[origin?.village,origin?.district,origin?.province,origin?.countryCode].filter(Boolean).join(', ')||'Belirtilmedi';}
