import React,{useEffect,useMemo,useRef,useState}from'react';
import{ArrowLeft,CheckCircle2,Copy,ExternalLink,Gift,Heart,MapPin,Minus,PackageCheck,Plus,QrCode,Share2,ShoppingCart,Star,Store,Truck}from'lucide-react';
import{getProductDetail,listProductReviews,publicCatalogUrl,toggleProductFavorite}from'./api';import ProductSafetyPanel from'../content/ProductSafetyPanel';import{getProductSafety}from'../content/productSafetyApi';
import{setCartItem}from'../cart/api';
import{buildProductUrl,copyText,shareOrCopy}from'../navigation/appUrl';

type Props={
 reference:string;
 authenticated:boolean;
 favoriteReferences?:string[];
 onFavoriteChanged?:(reference:string,isFavorite:boolean)=>void;
 onBack:()=>void;
 onLoginRequired:()=>void;
 onCartChanged?:()=>Promise<void>|void;
 onGift:(reference:string)=>void;
 onProducer:(id:string,slug:string,name:string)=>void;
};

const exportText:Record<string,string>={
 not_configured:'Bu ürün için otomatik yurtdışı gönderim henüz yapılandırılmadı. Uluslararası sipariş için manuel teklif ve uygunluk kontrolü gerekir.',
 domestic_only:'Bu ürün şu anda Türkiye içi otomatik siparişe açık; yurtdışı gönderim otomatik olarak sunulmuyor.',
 manual_review:'Yurtdışı sipariş ürün ve hedef ülkeye göre manuel inceleme gerektirir.',
 eligible:'Ürün ihracat uygunluk kontrolünden geçmiş. Nihai teslimat ücreti ve ülke koşulları ödeme öncesinde ayrıca doğrulanmalıdır.',
};

function safeText(value:unknown,max=1000){return typeof value==='string'?value.trim().slice(0,max):'';}
function safeNonNegativeInteger(value:unknown){return typeof value==='number'&&Number.isSafeInteger(value)&&value>=0?value:null;}
function safeRating(value:unknown){return typeof value==='number'&&Number.isFinite(value)&&value>=0&&value<=5?value:null;}
function safeCurrency(value:unknown){const currency=safeText(value,3).toUpperCase();return/^[A-Z]{3}$/.test(currency)?currency:null;}
function safeReference(value:unknown,max=220){const reference=safeText(value,max);return reference||null;}
function firstInteger(...values:unknown[]){for(const value of values){const parsed=safeNonNegativeInteger(value);if(parsed!==null)return parsed;}return null;}
function firstRating(...values:unknown[]){for(const value of values){const parsed=safeRating(value);if(parsed!==null)return parsed;}return null;}

export default function ProductDetailScreen({reference,authenticated,favoriteReferences=[],onFavoriteChanged,onBack,onLoginRequired,onCartChanged,onGift,onProducer}:Props){
 const[detail,setDetail]=useState<any>(null);const[safetyContent,setSafetyContent]=useState<any>(null);const[reviews,setReviews]=useState<any>(null);const[variantId,setVariantId]=useState('');const[quantity,setQuantity]=useState(1);const[selectedImagePath,setSelectedImagePath]=useState('');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[shareBusy,setShareBusy]=useState(false);const[error,setError]=useState('');const[status,setStatus]=useState('');const[favoriteOverride,setFavoriteOverride]=useState<boolean|null>(null);
 const requestId=useRef(0);
 async function load(){
  const current=++requestId.current;
  try{
   setLoading(true);setError('');setStatus('');setFavoriteOverride(null);setDetail(null);setReviews(null);
   const product=await getProductDetail(reference);
   if(requestId.current!==current)return;
   setDetail(product);
   const variants=Array.isArray(product?.variants)?product.variants:[];
   const defaultVariant=variants.find((v:any)=>v?.default===true&&v?.available===true)||variants.find((v:any)=>v?.available===true)||variants[0];
   setVariantId(safeReference(defaultVariant?.id,160)||'');setQuantity(1);
   const productImages=Array.isArray(product?.images)?product.images:[];const firstImage=productImages.find((i:any)=>i?.primary===true)||productImages[0];setSelectedImagePath(safeText(firstImage?.path,1200));
   if(product?.id){
    try{const nextReviews=await listProductReviews(product.id,20,0);if(requestId.current===current)setReviews(nextReviews);}
    catch{if(requestId.current===current)setReviews(null);}
   }
  }catch(err:any){if(requestId.current===current)setError(err?.message||'Ürün bilgileri yüklenemedi.');}
  finally{if(requestId.current===current)setLoading(false);}
 }
 useEffect(()=>{void load();return()=>{requestId.current+=1;};},[reference]);
 useEffect(()=>{let active=true;setSafetyContent(null);getProductSafety(reference,'tr').then(data=>{if(active)setSafetyContent(data);}).catch(error=>{console.warn('Structured product safety content unavailable.',error);if(active)setSafetyContent(null);});return()=>{active=false;};},[reference]);
 const variant=useMemo(()=>Array.isArray(detail?.variants)?detail.variants.find((item:any)=>item?.id===variantId)||null:null,[detail,variantId]);
 const images=Array.isArray(detail?.images)?detail.images:[];const selectedImage=images.find((item:any)=>item?.path===selectedImagePath)||images.find((item:any)=>item?.primary===true)||images[0]||null;
 const activeBadges=Array.isArray(detail?.trustBadges)?detail.trustBadges.filter((badge:any)=>badge&&typeof badge==='object'&&badge.active===true&&safeText(badge.label,120)):[];const hasTraceability=detail?.traceability?.hasReleasedBatches===true;
 const tracked=detail?.stockMode==='tracked'||detail?.stockMode==='seasonal';const variantStock=safeNonNegativeInteger(variant?.availableQuantity);const stockReady=!tracked||variantStock!==null;const soldOut=variant?.available===false||(tracked&&variantStock!==null&&variantStock<=0);const maxQuantity=tracked&&variantStock!==null?Math.max(1,Math.min(99,variantStock)):99;const preorder=detail?.stockMode==='preorder';
 const currency=safeCurrency(detail?.currency);const priceMinor=safeNonNegativeInteger(variant?.priceMinor);const priceReady=currency!==null&&priceMinor!==null;const variantReference=safeReference(variant?.id,160);const purchaseReady=variant?.available===true&&variantReference!==null&&priceReady&&stockReady&&!soldOut;
 useEffect(()=>{setQuantity(current=>Math.max(1,Math.min(current,maxQuantity)));},[variantId,maxQuantity]);
 const favoriteReference=String(detail?.legacyId||detail?.id||'');const isFavorite=favoriteOverride??favoriteReferences.includes(favoriteReference);const featureItems=normalizeFeatures(detail?.features);const tags=Array.isArray(detail?.tags)?detail.tags.filter((tag:any)=>typeof tag==='string'&&tag.trim()).map((tag:string)=>tag.trim().slice(0,120)).slice(0,12):[];
 const reviewCount=firstInteger(reviews?.summary?.count,detail?.reviewSummary?.count);const averageRating=firstRating(reviews?.summary?.averageRating,detail?.reviewSummary?.averageRating);
 async function addToCart(){if(!authenticated){onLoginRequired();return;}if(!purchaseReady||!variantReference){setError(!priceReady?'Fiyat doğrulanamadığı için ürün sepete eklenemiyor.':!stockReady?'Stok doğrulanamadığı için ürün sepete eklenemiyor.':soldOut?'Ürün stokta olmadığı için sepete eklenemiyor.':'Ürün seçeneği doğrulanamadığı için sepete eklenemiyor.');return;}try{setBusy(true);setError('');setStatus('');await setCartItem({variantId:variantReference,quantity});await onCartChanged?.();setStatus(`${quantity} adet ürün sepetinize eklendi.`);}catch(err:any){setError(err?.message||'Ürün sepete eklenemedi.');}finally{setBusy(false);}}
 async function favorite(){if(!authenticated){onLoginRequired();return;}const favoriteTarget=safeReference(detail?.slug)||safeReference(detail?.id,160);if(!favoriteTarget){setError('Ürün favori referansı doğrulanamadı.');return;}try{setBusy(true);setError('');setStatus('');const result=await toggleProductFavorite(favoriteTarget);const next=result?.isFavorite===true;const ref=String(result?.productReference||favoriteReference);setFavoriteOverride(next);onFavoriteChanged?.(ref,next);setStatus(next?'Ürün favorilerinize eklendi.':'Ürün favorilerinizden çıkarıldı.');}catch(err:any){setError(err?.message||'Favori işlemi tamamlanamadı.');}finally{setBusy(false);}}
 async function shareProduct(){if(shareBusy)return;try{setShareBusy(true);setError('');setStatus('');const productReference=safeReference(detail?.slug)||safeReference(reference)||safeReference(detail?.legacyId)||safeReference(detail?.id,160);if(!productReference)throw new Error('invalid_product_reference');const url=buildProductUrl(productReference);const result=await shareOrCopy({title:safeText(detail?.name,300)||'Golden Oremar ürünü',text:safeText(detail?.shortDescription||detail?.description,2000),url});if(result==='copied')setStatus('Ürün bağlantısı panoya kopyalandı.');else if(result==='shared')setStatus('Ürün paylaşımı tamamlandı.');else setStatus('Paylaşım iptal edildi.');}catch(err:any){setError(err?.message==='invalid_product_reference'?'Ürün paylaşım bağlantısı oluşturulamadı.':'Ürün bağlantısı paylaşılamadı.');}finally{setShareBusy(false);}}
 async function copyTrace(code:string){const safeCode=safeText(code,200);if(!safeCode){setError('Takip kodu doğrulanamadı.');return;}try{await copyText(safeCode);setStatus(`Takip kodu kopyalandı: ${safeCode}`);}catch{setError('Takip kodu kopyalanamadı.');}}
 if(loading)return<div role="status" aria-live="polite" className="mx-auto max-w-5xl p-8 text-center">Ürün yükleniyor…</div>;
 if(error&&!detail)return<div className="mx-auto max-w-5xl p-6"><div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200">{error}</div><button type="button" onClick={onBack} className="mt-4 min-h-11 rounded-xl border px-4 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">Geri dön</button></div>;
 if(!detail)return null;
 const detailName=safeText(detail.name,300)||'Ürün';const producerLocation=safeText(detail?.producer?.locationLabel,240)||safeText(detail?.origin,240);const purchaseIssue=!priceReady?'Fiyat doğrulanamadı':!stockReady?'Stok doğrulanamadı':!variantReference?'Ürün seçeneği doğrulanamadı':soldOut?'Stokta yok':variant?.available!==true?'Satış durumu uygun değil':'';
 return<article className="mx-auto max-w-6xl px-4 py-6 sm:py-8">
  <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><button type="button" onClick={onBack} className="min-h-11 rounded-xl border px-4 font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><ArrowLeft aria-hidden="true" className="mr-2 inline h-4 w-4"/>Geri</button><button type="button" onClick={()=>void shareProduct()} disabled={shareBusy} className="min-h-11 rounded-xl border px-4 font-semibold disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold" aria-label={`${detailName} ürününü paylaş`}><Share2 aria-hidden="true" className="mr-2 inline h-4 w-4"/>{shareBusy?'Hazırlanıyor…':'Paylaş'}</button></div>
  {error?<div role="alert" className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200">{error}</div>:null}{status?<div role="status" aria-live="polite" className="mb-4 rounded-xl bg-green-50 p-3 text-sm text-green-800 dark:bg-green-950/30 dark:text-green-200">{status}</div>:null}
  <div className="grid gap-7 lg:grid-cols-2">
   <section aria-label="Ürün görselleri">
    <div className="overflow-hidden rounded-3xl border bg-gray-100 dark:bg-gray-800">{selectedImage?.path&&publicCatalogUrl(selectedImage.path)?<img src={publicCatalogUrl(selectedImage.path)} alt={safeText(selectedImage.alt,300)||detailName} loading="eager" decoding="async" fetchPriority="high" className="aspect-square h-full w-full object-cover"/>:<div role="img" aria-label={`${detailName} için görsel henüz eklenmedi`} className="grid aspect-square place-items-center text-gray-400">Görsel henüz eklenmedi</div>}</div>
    {images.length>1?<div className="mt-3 grid grid-cols-4 gap-2 sm:grid-cols-6">{images.slice(0,12).map((img:any,index:number)=>{const src=publicCatalogUrl(img?.path);return src?<button type="button" key={`${safeText(img.path,1200)}:${index}`} onClick={()=>setSelectedImagePath(safeText(img.path,1200))} aria-label={`${detailName} görseli ${index+1} görüntüle`} aria-pressed={selectedImage?.path===img.path} className={`overflow-hidden rounded-xl border focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold ${selectedImage?.path===img.path?'border-brand-gold ring-2 ring-brand-gold/30':''}`}><img src={src} alt={safeText(img.alt,300)||`${detailName} küçük görsel ${index+1}`} loading="lazy" decoding="async" className="aspect-square h-full w-full object-cover"/></button>:null;})}</div>:null}
   </section>
   <section>
    {safeText(detail.category?.name,160)?<div className="text-sm font-semibold text-brand-gold">{safeText(detail.category?.name,160)}</div>:null}<h1 className="mt-1 text-3xl font-bold text-brand-green dark:text-brand-gold">{detailName}</h1>{safeText(detail.shortDescription,2000)?<p className="mt-3 leading-7 text-gray-600 dark:text-gray-300">{safeText(detail.shortDescription,2000)}</p>:null}
    {detail.producer?.id?<button type="button" onClick={()=>onProducer(detail.producer.id,detail.producer.slug,detail.producer.name)} className="mt-4 flex min-h-12 w-full items-center gap-3 rounded-2xl border p-3 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><Store aria-hidden="true" className="h-5 w-5 text-brand-gold"/><span className="min-w-0 flex-1"><span className="block font-bold">{safeText(detail.producer.name,240)||'Üretici'}</span><span className="block text-sm text-gray-500">{producerLocation||'Konum doğrulanamadı'}</span></span></button>:null}
    {activeBadges.length?<div className="mt-4 flex flex-wrap gap-2">{activeBadges.map((badge:any)=><span key={safeText(badge.key,80)||safeText(badge.label,120)} className="inline-flex items-center gap-1 rounded-full bg-green-50 px-3 py-1.5 text-xs font-bold text-green-800 dark:bg-green-950/30 dark:text-green-200"><CheckCircle2 aria-hidden="true" className="h-3.5 w-3.5"/>{safeText(badge.label,120)}</span>)}</div>:null}
    {tags.length?<div className="mt-3 flex flex-wrap gap-2">{tags.map((tag:string)=><span key={tag} className="rounded-full border px-3 py-1 text-xs text-gray-600 dark:text-gray-300">{tag}</span>)}</div>:null}
    {variant?<div className="mt-6 rounded-2xl bg-gray-50 p-4 dark:bg-gray-800"><div className="flex flex-wrap items-end justify-between gap-3"><div>{priceReady?<><div className="text-2xl font-bold text-brand-green dark:text-brand-gold">{money(priceMinor,currency)}</div>{safeNonNegativeInteger(variant.compareAtPriceMinor)!==null&&safeNonNegativeInteger(variant.compareAtPriceMinor)!>(priceMinor as number)?<div className="text-sm text-gray-400 line-through">{money(safeNonNegativeInteger(variant.compareAtPriceMinor),currency)}</div>:null}</>:<div className="font-bold text-red-700 dark:text-red-300">Fiyat doğrulanamadı</div>}</div><div className={`text-sm font-semibold ${!stockReady||soldOut?'text-red-700 dark:text-red-300':'text-green-700 dark:text-green-300'}`}>{!stockReady?'Stok doğrulanamadı':soldOut?'Stokta yok':tracked&&variantStock!==null?`${variantStock} adet stokta`:preorder?'Ön siparişe açık':variant?.available===true?'Satışa açık':'Satış durumu doğrulanamadı'}</div></div>{preorder&&safeNonNegativeInteger(detail.preorderLeadDays)!==null&&safeNonNegativeInteger(detail.preorderLeadDays)!>0?<div className="mt-2 text-sm text-gray-500">Tahmini hazırlık: {safeNonNegativeInteger(detail.preorderLeadDays)} gün</div>:null}</div>:<div role="alert" className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900/60 dark:bg-amber-950/30 dark:text-amber-100">Satın alınabilir ürün seçeneği doğrulanamadı.</div>}
    <fieldset className="mt-5"><legend className="font-bold">Seçenek</legend><div className="mt-2 space-y-2">{Array.isArray(detail.variants)?detail.variants.map((item:any)=>{const itemStock=safeNonNegativeInteger(item?.availableQuantity);const itemPrice=safeNonNegativeInteger(item?.priceMinor);const itemCompare=safeNonNegativeInteger(item?.compareAtPriceMinor);const itemStockReady=!tracked||itemStock!==null;return<label key={safeReference(item?.id,160)||safeText(item?.name,240)} className={`flex min-h-12 items-center justify-between gap-3 rounded-xl border p-3 ${variantId===item.id?'border-brand-gold bg-brand-gold/5':''}`}><span className="flex items-center gap-3"><input type="radio" name="variant" value={safeReference(item.id,160)||''} checked={variantId===item.id} disabled={item.available===false} onChange={()=>setVariantId(safeReference(item.id,160)||'')}/><span><span className="block font-semibold">{safeText(item.name,240)||'Seçenek'}</span><span className="block text-xs text-gray-500">{item.available===false?'Satışta değil':!itemStockReady?'Stok doğrulanamadı':tracked&&itemStock!==null?`${itemStock} adet mevcut`:'Satışta'}{safeNonNegativeInteger(item.weightGrams)!==null&&safeNonNegativeInteger(item.weightGrams)!>0?` • ${formatWeight(safeNonNegativeInteger(item.weightGrams))}`:''}</span></span></span><span className="text-right font-bold">{itemPrice!==null&&currency?money(itemPrice,currency):'Fiyat doğrulanamadı'}{itemCompare!==null&&itemPrice!==null&&itemCompare>itemPrice&&currency?<span className="block text-xs font-normal text-gray-400 line-through">{money(itemCompare,currency)}</span>:null}</span></label>; }):null}</div></fieldset>
    <div className="mt-4" role="group" aria-labelledby="product-quantity-label"><span id="product-quantity-label" className="text-sm font-semibold">Adet</span><div className="mt-2 flex flex-wrap items-center gap-3"><div className="inline-flex items-center rounded-xl border bg-white dark:bg-gray-900" aria-label={`${detailName} adet seçimi`}><button type="button" onClick={()=>setQuantity(current=>Math.max(1,current-1))} disabled={!purchaseReady||busy||quantity<=1} aria-label={`${detailName} miktarını azalt`} className="grid min-h-11 min-w-11 place-items-center rounded-l-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold disabled:cursor-not-allowed disabled:opacity-40"><Minus aria-hidden="true" className="h-4 w-4"/></button><output aria-live="polite" aria-atomic="true" aria-label={`${quantity} adet`} className="min-w-12 px-2 text-center font-bold tabular-nums">{quantity}</output><button type="button" onClick={()=>setQuantity(current=>Math.min(maxQuantity,current+1))} disabled={!purchaseReady||busy||quantity>=maxQuantity} aria-label={`${detailName} miktarını artır`} className="grid min-h-11 min-w-11 place-items-center rounded-r-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold disabled:cursor-not-allowed disabled:opacity-40"><Plus aria-hidden="true" className="h-4 w-4"/></button></div>{purchaseReady?<span className="text-xs text-gray-500">En fazla {maxQuantity} adet</span>:<span className="text-xs font-semibold text-amber-700 dark:text-amber-300">{purchaseIssue||'Satın alma doğrulanamadı'}</span>}</div></div>
    <div className="mt-5 grid grid-cols-[1fr_auto_auto] gap-2"><button type="button" onClick={()=>void addToCart()} disabled={busy||!purchaseReady} className="min-h-12 rounded-xl bg-brand-green px-4 font-bold text-white disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><ShoppingCart aria-hidden="true" className="mr-2 inline h-5 w-5"/>{busy?'İşleniyor…':purchaseReady?(preorder?'Ön Siparişe Ekle':'Sepete Ekle'):(purchaseIssue||'Satın Alma Kapalı')}</button><button type="button" onClick={()=>void favorite()} disabled={busy} aria-label={isFavorite?'Favorilerden çıkar':'Favorilere ekle'} aria-pressed={isFavorite} className="min-h-12 min-w-12 rounded-xl border px-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><Heart aria-hidden="true" className={`mx-auto h-5 w-5 ${isFavorite?'fill-red-500 text-red-500':''}`}/></button><button type="button" onClick={()=>authenticated?onGift(detail.slug||detail.id):onLoginRequired()} disabled={busy||!purchaseReady} aria-label="Hediye et" className="min-h-12 min-w-12 rounded-xl border px-3 disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><Gift aria-hidden="true" className="mx-auto h-5 w-5 text-brand-gold"/></button></div>
   </section>
  </div>
  <div className="mt-8 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border p-5"><h2 className="text-xl font-bold">Ürün Hikâyesi</h2><p className="mt-3 whitespace-pre-wrap leading-7 text-gray-600 dark:text-gray-300">{safeText(detail.story,12000)||safeText(detail.description,12000)||'Ürün hikâyesi henüz eklenmedi.'}</p>{safeText(detail.origin,240)?<div className="mt-4 flex items-center gap-2 text-sm font-semibold"><MapPin aria-hidden="true" className="h-4 w-4 text-brand-gold"/>{safeText(detail.origin,240)}</div>:null}</section><ShippingReadiness detail={detail} variant={variant}/></div>
  {featureItems.length?<section className="mt-5 rounded-2xl border p-5"><h2 className="text-xl font-bold">Ürün Özellikleri</h2><ul className="mt-3 grid gap-2 sm:grid-cols-2">{featureItems.map((item,index)=><li key={`${item}-${index}`} className="rounded-xl bg-gray-50 p-3 text-sm dark:bg-gray-800">{item}</li>)}</ul></section>:null}
  <ProductSafetyPanel safety={safetyContent?.safety} summary={safetyContent?.summary} heading="Gıda güvenliği & kullanım" className="mt-5"/>
  <section className="mt-5 rounded-2xl border p-5"><h2 className="flex items-center gap-2 text-xl font-bold"><QrCode aria-hidden="true" className="h-5 w-5 text-brand-gold"/>Lot / İzlenebilirlik</h2>{hasTraceability&&Array.isArray(detail.traceability?.batches)?<div className="mt-3 space-y-3">{detail.traceability.batches.map((batch:any,index:number)=>{const traceCode=safeText(batch?.traceCode,200);if(!traceCode)return null;return<article key={`${traceCode}:${index}`} className="rounded-xl bg-gray-50 p-4 dark:bg-gray-800"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-bold">{safeText(batch.batchCode,200)||'Yayınlanmış lot'}</div><div className="mt-1 text-sm text-gray-500">Takip kodu: {traceCode}</div></div><button type="button" onClick={()=>void copyTrace(traceCode)} className="min-h-11 rounded-lg border px-3 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><Copy aria-hidden="true" className="mr-2 inline h-4 w-4"/>Kodu kopyala</button></div><div className="mt-3 grid gap-2 text-sm sm:grid-cols-2">{batch.harvestDate?<div>Hasat: {dateOnly(batch.harvestDate)}</div>:null}{batch.productionDate?<div>Üretim: {dateOnly(batch.productionDate)}</div>:null}{batch.packagingDate?<div>Paketleme: {dateOnly(batch.packagingDate)}</div>:null}{batch.bestBeforeDate?<div>Tavsiye edilen tüketim: {dateOnly(batch.bestBeforeDate)}</div>:null}{batch.origin?<div>Menşe: {joinLocation(batch.origin)}</div>:null}{safeText(batch.productionMethod,500)?<div>Üretim yöntemi: {safeText(batch.productionMethod,500)}</div>:null}</div>{safeText(batch.publicNotes,3000)?<p className="mt-3 text-sm text-gray-600 dark:text-gray-300">{safeText(batch.publicNotes,3000)}</p>:null}</article>;})}</div>:<p className="mt-3 text-sm text-gray-500">Bu ürün için henüz müşteriye yayınlanmış lot bulunmuyor. İncelemedeki veya doğrulanmamış lot bilgileri gösterilmez.</p>}</section>
  {Array.isArray(detail.certifications)&&detail.certifications.length?<section className="mt-5 rounded-2xl border p-5"><h2 className="flex items-center gap-2 text-xl font-bold"><PackageCheck aria-hidden="true" className="h-5 w-5 text-brand-gold"/>Doğrulanmış Sertifikalar</h2><div className="mt-3 space-y-2">{detail.certifications.slice(0,50).map((cert:any,index:number)=><div key={`${safeText(cert?.type,160)}:${index}`} className="rounded-xl bg-gray-50 p-3 text-sm dark:bg-gray-800"><div><strong>{safeText(cert?.type,160)||'Sertifika'}</strong>{safeText(cert?.issuer,240)?` • ${safeText(cert.issuer,240)}`:''}</div>{safeText(cert?.certificateNumber,240)?<div className="mt-1 text-gray-500">Belge no: {safeText(cert.certificateNumber,240)}</div>:null}{cert?.expiresAt?<div className="mt-1 text-gray-500">Geçerlilik: {dateOnly(cert.expiresAt)}</div>:null}{safeUrl(cert?.verificationUrl)?<a href={safeUrl(cert.verificationUrl)} target="_blank" rel="noopener noreferrer" className="mt-2 inline-flex min-h-11 items-center font-semibold text-brand-green focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">Belgeyi doğrula<ExternalLink aria-hidden="true" className="ml-2 h-4 w-4"/></a>:null}</div>)}</div></section>:null}
  <section className="mt-5 rounded-2xl border p-5"><h2 className="text-xl font-bold">Müşteri Yorumları</h2>{reviewCount===null?<div className="mt-2 text-sm font-semibold text-amber-700 dark:text-amber-300">Değerlendirme özeti doğrulanamadı</div>:reviewCount>0?<div className="mt-2 flex items-center gap-2">{averageRating!==null?<><Star aria-hidden="true" className="h-5 w-5 fill-brand-gold text-brand-gold"/><strong>{averageRating.toFixed(1)}</strong></>:<strong className="text-amber-700 dark:text-amber-300">Puan doğrulanamadı</strong>}<span className="text-sm text-gray-500">({reviewCount} yorum)</span></div>:<div className="mt-2 text-sm text-gray-500">Henüz yayınlanmış müşteri yorumu yok.</div>}{Array.isArray(reviews?.items)&&reviews.items.length?<div className="mt-4 space-y-3">{reviews.items.slice(0,20).map((review:any,index:number)=>{const rating=safeRating(review?.rating);return<article key={safeReference(review?.id,160)||`review-${index}`} className="rounded-xl bg-gray-50 p-4 dark:bg-gray-800"><div className="flex items-center justify-between gap-3"><strong>{safeText(review?.reviewerName,160)||'Müşteri'}</strong><span className="text-sm">{rating!==null?`${rating}/5`:'Puan doğrulanamadı'}</span></div>{review?.verifiedPurchase===true?<div className="mt-1 text-xs font-bold text-green-700 dark:text-green-300">Doğrulanmış satın alma</div>:null}{safeText(review?.title,240)?<h3 className="mt-2 font-semibold">{safeText(review.title,240)}</h3>:null}{safeText(review?.body,5000)?<p className="mt-1 text-sm leading-6 text-gray-600 dark:text-gray-300">{safeText(review.body,5000)}</p>:null}{safeText(review?.merchantReply,5000)?<div className="mt-3 rounded-lg border-l-4 border-brand-gold bg-white p-3 text-sm dark:bg-gray-900"><strong>Üretici yanıtı:</strong> {safeText(review.merchantReply,5000)}</div>:null}</article>;})}</div>:reviewCount!==null&&reviewCount>0?<p className="mt-4 text-sm text-gray-500">Yorum listesi şu anda yüklenemedi veya doğrulanamadı.</p>:null}</section>
 </article>;
}

function ShippingReadiness({detail,variant}:{detail:any;variant:any}){const exp=detail?.export&&typeof detail.export==='object'&&!Array.isArray(detail.export)?detail.export:{};const status=safeText(exp.status,80);const statusText=exportText[status]||'Yurtdışı gönderim durumu doğrulanamadı. Hedef ülke ve ürün uygunluğu ödeme öncesinde ayrıca kontrol edilmelidir.';const weight=safeNonNegativeInteger(variant?.weightGrams);const shelfLife=safeNonNegativeInteger(exp.shelfLifeDays);const perishable=typeof exp.perishable==='boolean'?exp.perishable:null;const coldChain=typeof exp.requiresColdChain==='boolean'?exp.requiresColdChain:null;const missingWeight=weight===null||weight<=0;return<section className="rounded-2xl border p-5"><h2 className="flex items-center gap-2 text-xl font-bold"><Truck aria-hidden="true" className="h-5 w-5 text-brand-gold"/>Teslimat / Yurtdışı Hazırlığı</h2><p className="mt-3 text-sm leading-6 text-gray-600 dark:text-gray-300">{statusText}</p>{status==='eligible'&&missingWeight?<div role="status" className="mt-3 rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900 dark:border-amber-800 dark:bg-amber-950/30 dark:text-amber-100">Seçili varyantın sevkiyat ağırlığı henüz doğrulanmadı; otomatik uluslararası kargo fiyatı hesaplanamaz.</div>:null}<dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-gray-50 p-3 dark:bg-gray-800"><dt className="text-gray-500">Bozulabilir ürün</dt><dd className="font-semibold">{perishable===null?'Doğrulanamadı':perishable?'Evet':'Hayır'}</dd></div><div className="rounded-xl bg-gray-50 p-3 dark:bg-gray-800"><dt className="text-gray-500">Soğuk zincir</dt><dd className="font-semibold">{coldChain===null?'Doğrulanamadı':coldChain?'Gerekli':'Gerekli değil'}</dd></div>{shelfLife!==null&&shelfLife>0?<div className="rounded-xl bg-gray-50 p-3 dark:bg-gray-800"><dt className="text-gray-500">Raf ömrü</dt><dd className="font-semibold">{shelfLife} gün</dd></div>:null}{weight!==null&&weight>0?<div className="rounded-xl bg-gray-50 p-3 dark:bg-gray-800"><dt className="text-gray-500">Sevkiyat ağırlığı</dt><dd className="font-semibold">{formatWeight(weight)}</dd></div>:null}</dl></section>;}
function normalizeFeatures(value:any):string[]{if(Array.isArray(value))return value.flatMap(item=>typeof item==='string'&&item.trim()?[item.trim().slice(0,500)]:item&&typeof item==='object'&&!Array.isArray(item)?Object.entries(item).map(([k,v])=>`${labelKey(k)}: ${formatValue(v)}`):[]).filter(Boolean).slice(0,24);if(value&&typeof value==='object'&&!Array.isArray(value))return Object.entries(value).map(([k,v])=>`${labelKey(k)}: ${formatValue(v)}`).filter(item=>!item.endsWith(': ')).slice(0,24);return[];}
function labelKey(value:string){return value.replace(/[_-]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase()).slice(0,120);}
function formatValue(value:any){if(Array.isArray(value))return value.slice(0,20).map(item=>safeText(String(item),120)).filter(Boolean).join(', ');if(value===true)return'Evet';if(value===false)return'Hayır';if(value==null)return'';if(typeof value==='object')return'Yapılandırılmış bilgi';return safeText(String(value),500);}
function money(minor:number|null,currency:string|null){if(minor===null||currency===null)return'Fiyat doğrulanamadı';try{return new Intl.NumberFormat('tr-TR',{style:'currency',currency}).format(minor/100);}catch{return'Fiyat doğrulanamadı';}}
function formatWeight(grams:number|null){if(grams===null||!Number.isFinite(grams)||grams<=0)return'Ağırlık doğrulanamadı';return grams>=1000?`${(grams/1000).toLocaleString('tr-TR',{maximumFractionDigits:2})} kg`:`${grams.toLocaleString('tr-TR')} g`;}
function dateOnly(value?:string|null){const raw=safeText(value,80);if(!raw)return'Tarih doğrulanamadı';const date=/^\d{4}-\d{2}-\d{2}$/.test(raw)?new Date(`${raw}T12:00:00`):new Date(raw);if(Number.isNaN(date.getTime()))return'Tarih doğrulanamadı';try{return new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium'}).format(date);}catch{return'Tarih doğrulanamadı';}}
function safeUrl(value?:string|null){const raw=safeText(value,1200);if(!raw)return'';try{const url=new URL(raw);return url.protocol==='https:'?url.toString():'';}catch{return'';}}
function joinLocation(origin:any){if(!origin||typeof origin!=='object'||Array.isArray(origin))return'Menşe doğrulanamadı';return[origin?.village,origin?.district,origin?.province,origin?.countryCode].map((item:any)=>safeText(item,120)).filter(Boolean).join(', ')||'Menşe doğrulanamadı';}
