import React,{useEffect,useRef,useState}from'react';
import{ArrowLeft,CheckCircle2,Heart,MapPin,MessageCircle,Package,Send,Star,Store,Users,X}from'lucide-react';
import{getPublicProducerProfile,publicCatalogUrl,startProducerProductConversation,toggleProducerFollow}from'./api';
import CatalogProductCard from'./CatalogProductCard';

type Props={
 reference:string;
 authenticated:boolean;
 onBack:()=>void;
 onLoginRequired:()=>void;
 onOpenProduct:(slug:string)=>void;
 onAddToCart:(product:{id:string;slug:string;name:string;variantId:string},quantity:number)=>Promise<void>|void;
 onOpenConversation?:(conversationId:string)=>void;
};

function safeText(value:unknown,max=300){return typeof value==='string'?value.trim().slice(0,max):'';}
function safeNonNegativeInteger(value:unknown){return typeof value==='number'&&Number.isSafeInteger(value)&&value>=0?value:null;}
function safeNonNegativeNumber(value:unknown){return typeof value==='number'&&Number.isFinite(value)&&value>=0?value:null;}
function safeRating(value:unknown){return typeof value==='number'&&Number.isFinite(value)&&value>=0&&value<=5?value:null;}
function safeCurrency(value:unknown){const currency=safeText(value,3).toUpperCase();return/^[A-Z]{3}$/.test(currency)?currency:null;}
function safeReference(value:unknown,max=220){const reference=safeText(value,max);return reference||null;}

export default function PublicProducerScreen({reference,authenticated,onBack,onLoginRequired,onOpenProduct,onAddToCart,onOpenConversation}:Props){
 const[profile,setProfile]=useState<any>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[status,setStatus]=useState('');const[following,setFollowing]=useState(false);const[questionProduct,setQuestionProduct]=useState<any>(null);const[question,setQuestion]=useState('');const[messageBusy,setMessageBusy]=useState(false);const questionRef=useRef<HTMLTextAreaElement>(null);
 const requestId=useRef(0);
 async function load(){
  const current=++requestId.current;
  try{
   setLoading(true);setError('');setProfile(null);
   const producer=await getPublicProducerProfile(reference);
   if(requestId.current!==current)return;
   setProfile(producer);setFollowing(authenticated&&producer?.following===true);
  }catch(err:any){if(requestId.current===current)setError(err?.message||'Üretici profili yüklenemedi.');}
  finally{if(requestId.current===current)setLoading(false);}
 }
 useEffect(()=>{setStatus('');void load();return()=>{requestId.current+=1;};},[reference,authenticated]);
 useEffect(()=>{if(questionProduct)setTimeout(()=>questionRef.current?.focus(),30);},[questionProduct?.id]);
 async function follow(){if(!authenticated){onLoginRequired();return;}const producerId=safeReference(profile?.id,160);if(!producerId){setError('Üretici kimliği doğrulanamadığı için takip işlemi yapılamıyor.');return;}try{setBusy(true);setError('');setStatus('');const result=await toggleProducerFollow(producerId);const refreshed=await getPublicProducerProfile(reference);setProfile(refreshed);setFollowing(refreshed?.following===true);setStatus(result?.following===true?'Üreticiyi takip etmeye başladınız.':result?.following===false?'Üretici takibi bırakıldı.':'Takip durumu sunucudan doğrulanamadı.');}catch(err:any){setError(err?.message||'Takip işlemi tamamlanamadı.');}finally{setBusy(false);}}
 function ask(product:any){if(!authenticated){onLoginRequired();return;}if(!safeReference(product?.id,160)){setError('Ürün kimliği doğrulanamadığı için mesaj başlatılamıyor.');return;}setError('');setStatus('');setQuestionProduct(product);setQuestion('');}
 async function sendQuestion(){const producerId=safeReference(profile?.id,160);const productId=safeReference(questionProduct?.id,160);const productName=safeText(questionProduct?.name,240);if(!producerId||!productId||!productName){setError('Üretici veya ürün bilgisi doğrulanamadığı için mesaj gönderilemiyor.');return;}const body=question.trim();if(!body){setError('Üreticiye göndermek istediğiniz mesajı yazın.');return;}try{setMessageBusy(true);setError('');setStatus('');const result=await startProducerProductConversation({producerId,productId,productName,message:body});setQuestion('');setQuestionProduct(null);setStatus('Mesajınız üreticiye güvenli konuşma üzerinden gönderildi.');const conversationId=safeReference(result?.conversationId,160);if(conversationId)onOpenConversation?.(conversationId);}catch(err:any){setError(err?.message||'Üreticiye mesaj gönderilemedi.');}finally{setMessageBusy(false);}}
 if(loading)return<div role="status" aria-live="polite" className="mx-auto max-w-6xl p-8 text-center">Üretici profili yükleniyor…</div>;
 if(!profile)return<div className="mx-auto max-w-6xl p-6"><div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200">{error||'Üretici bulunamadı.'}</div><button type="button" onClick={onBack} className="mt-4 min-h-11 rounded-xl border px-4 font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">Geri</button></div>;
 const activeBadges=Array.isArray(profile.badges)?profile.badges.filter((item:any)=>item&&typeof item==='object'&&item.active===true&&safeText(item.label,120)):[];
 const structuredLocation=[profile.location?.village,profile.location?.district,profile.location?.province].map((item:any)=>safeText(item,120)).filter(Boolean).join(', ');const locationText=structuredLocation||safeText(profile.location_label,240);
 const followerCount=safeNonNegativeInteger(profile.follower_count);const productCount=safeNonNegativeInteger(profile.product_count);const ratingCount=safeNonNegativeInteger(profile.rating_count);const ratingAverage=safeRating(profile.rating_average);
 const producerVerified=activeBadges.some((badge:any)=>badge.key==='verified_producer');const producerOriginVerified=activeBadges.some((badge:any)=>badge.key==='verified_origin');
 const displayName=safeText(profile.display_name,240)||'Üretici';
 return<article className="mx-auto max-w-6xl px-4 py-6 sm:py-8">
  <button type="button" onClick={onBack} className="mb-5 min-h-11 rounded-xl border px-4 font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><ArrowLeft aria-hidden="true" className="mr-2 inline h-4 w-4"/>Geri</button>
  {error?<div role="alert" className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200">{error}</div>:null}{status?<div role="status" aria-live="polite" className="mb-4 rounded-xl bg-green-50 p-3 text-sm text-green-800 dark:bg-green-950/30 dark:text-green-200">{status}</div>:null}
  <section className="overflow-hidden rounded-3xl border bg-white shadow-sm dark:border-gray-800 dark:bg-gray-900">
   <div className="h-44 bg-gradient-to-br from-brand-green/70 to-brand-gold/30 sm:h-60">{profile.cover_path?<img src={publicCatalogUrl(profile.cover_path)} alt={`${displayName} kapak görseli`} loading="eager" decoding="async" fetchPriority="high" className="h-full w-full object-cover"/>:null}</div>
   <div className="p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-start"><div className="-mt-16 grid h-28 w-28 shrink-0 place-items-center overflow-hidden rounded-full border-4 border-white bg-gray-100 shadow-lg dark:border-gray-900 dark:bg-gray-800">{profile.logo_path?<img src={publicCatalogUrl(profile.logo_path)} alt={`${displayName} logosu`} loading="eager" decoding="async" className="h-full w-full object-cover"/>:<Store aria-hidden="true" className="h-10 w-10 text-brand-gold"/>}</div><div className="min-w-0 flex-1"><h1 className="text-3xl font-bold text-brand-green dark:text-brand-gold">{displayName}</h1><div className="mt-2 flex flex-wrap gap-2">{activeBadges.map((badge:any)=><span key={safeText(badge.key,80)||safeText(badge.label,120)} className="inline-flex items-center gap-1 rounded-full bg-green-50 px-3 py-1.5 text-xs font-bold text-green-800 dark:bg-green-950/30 dark:text-green-200"><CheckCircle2 aria-hidden="true" className="h-3.5 w-3.5"/>{safeText(badge.label,120)}</span>)}</div><div className="mt-3 flex flex-wrap items-center gap-4 text-sm text-gray-500">{locationText?<span className="inline-flex items-center gap-1"><MapPin aria-hidden="true" className="h-4 w-4 text-brand-gold"/>{locationText}</span>:<span className="text-amber-700 dark:text-amber-300">Konum doğrulanamadı</span>}<span className="inline-flex items-center gap-1"><Package aria-hidden="true" className="h-4 w-4 text-brand-gold"/>{productCount===null?'Ürün sayısı doğrulanamadı':`${formatNumber(productCount)} ürün`}</span><span className="inline-flex items-center gap-1"><Users aria-hidden="true" className="h-4 w-4 text-brand-gold"/>{followerCount===null?'Takipçi sayısı doğrulanamadı':`${formatNumber(followerCount)} takipçi`}</span>{ratingCount===null?<span className="text-amber-700 dark:text-amber-300">Değerlendirme sayısı doğrulanamadı</span>:ratingCount>0?<span className="inline-flex items-center gap-1"><Star aria-hidden="true" className="h-4 w-4 fill-brand-gold text-brand-gold"/>{ratingAverage!==null?ratingAverage.toFixed(1):'Puan doğrulanamadı'} ({formatNumber(ratingCount)})</span>:<span>Henüz değerlendirme yok</span>}</div></div><button type="button" onClick={()=>void follow()} disabled={busy||!safeReference(profile.id,160)} aria-pressed={following} className="min-h-11 rounded-xl border border-brand-gold/40 px-5 font-bold text-brand-gold disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><Heart aria-hidden="true" className={`mr-2 inline h-4 w-4 ${following?'fill-brand-gold':''}`}/>{busy?'Güncelleniyor…':following?'Takibi bırak':'Takip et'}</button></div>
   {safeText(profile.description,5000)?<p className="mt-6 leading-7 text-gray-600 dark:text-gray-300">{safeText(profile.description,5000)}</p>:null}{safeText(profile.story,10000)?<div className="mt-5 rounded-2xl bg-gray-50 p-4 dark:bg-gray-800"><h2 className="font-bold">Üretici Hikâyesi</h2><p className="mt-2 whitespace-pre-wrap leading-7 text-gray-600 dark:text-gray-300">{safeText(profile.story,10000)}</p></div>:null}<p className="mt-4 text-xs text-gray-500">Gizlilik nedeniyle üreticinin ev adresi, telefon, e-posta, banka/KYC bilgileri ve kesin koordinatları public profilde gösterilmez.</p></div>
  </section>
  {questionProduct?<section aria-labelledby="producer-question-title" className="mt-6 rounded-2xl border border-brand-green/30 bg-brand-green/5 p-4"><div className="flex items-start justify-between gap-3"><div><h2 id="producer-question-title" className="font-bold">{safeText(questionProduct.name,240)||'Ürün'} hakkında üreticiye sor</h2><p className="mt-1 text-sm text-gray-500">Konuşma bu ürüne bağlanır; üretici ürün bağlamını görür.</p></div><button type="button" onClick={()=>{setQuestionProduct(null);setQuestion('');}} className="min-h-11 rounded-lg border px-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold" aria-label="Mesaj formunu kapat"><X aria-hidden="true" className="h-4 w-4"/></button></div><label className="mt-3 block"><span className="text-sm font-semibold">Mesajınız</span><textarea ref={questionRef} value={question} onChange={e=>setQuestion(e.target.value.slice(0,5000))} maxLength={5000} rows={4} className="mt-1 w-full rounded-xl border bg-white p-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold dark:bg-gray-900" placeholder="Ürün, üretim yöntemi, teslimat veya kullanım hakkında sorunuzu yazın."/><span className="mt-1 block text-xs text-gray-500">{question.length}/5000</span></label><button type="button" onClick={()=>void sendQuestion()} disabled={messageBusy||!question.trim()} className="mt-3 min-h-12 w-full rounded-xl bg-brand-green px-4 font-bold text-white disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><Send aria-hidden="true" className="mr-2 inline h-4 w-4"/>{messageBusy?'Gönderiliyor…':'Üreticiye güvenli mesaj gönder'}</button></section>:null}
  <section className="mt-7" aria-labelledby="producer-products-title"><h2 id="producer-products-title" className="text-2xl font-bold text-brand-green dark:text-brand-gold">Ürünleri</h2>{!Array.isArray(profile.products)?<div role="alert" className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-900 dark:border-amber-900/60 dark:bg-amber-950/30 dark:text-amber-100">Ürün listesi sunucudan doğrulanamadı.</div>:!profile.products.length?<div className="mt-4 rounded-2xl border border-dashed p-8 text-center text-gray-500">Bu üreticinin yayında ürünü bulunmuyor.</div>:<div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{profile.products.map((product:any,index:number)=>{const id=safeReference(product?.id,160);const slug=safeReference(product?.slug,220);const name=safeText(product?.name,300)||'Ürün';const variantId=safeReference(product?.variant_id,160);const priceMinor=safeNonNegativeInteger(product?.price_minor);const compareMinor=safeNonNegativeInteger(product?.compare_at_price_minor);const currency=safeCurrency(product?.currency);const stock=safeNonNegativeInteger(product?.available_quantity);const reviewCount=safeNonNegativeInteger(product?.review_count);const rating=safeRating(product?.average_rating);const productReference=id||slug||`producer-product-${index}`;const cardProduct={id:id||'',slug:slug||'',name,description:safeText(product?.short_description,1000),shortDescription:safeText(product?.short_description,1000),category:'Üretici ürünü',price:priceMinor===null?null:priceMinor/100,originalPrice:compareMinor===null?null:compareMinor/100,currency:currency||null,image:publicCatalogUrl(product?.image_path),origin:safeText(product?.origin,240)||null,unit:safeText(product?.unit_label,120)||safeText(product?.variant_name,120)||null,stock,stockMode:safeText(product?.stock_mode,80),is_featured:product?.featured===true,preOrder:product?.stock_mode==='preorder',variantId:variantId||'',variantName:safeText(product?.variant_name,240),producerName:displayName,producerFollowerCount:followerCount,producerVerified,producerOriginVerified,reviewCount,rating};return<div key={productReference} className="flex flex-col gap-2"><CatalogProductCard product={cardProduct} onClick={()=>{if(slug)onOpenProduct(slug);else setError('Ürün bağlantısı doğrulanamadı.');}} onAddToCart={(_,quantity)=>{if(!id||!slug||!variantId)throw new Error('Ürün satın alma referansları doğrulanamadı.');return onAddToCart({id,slug,name,variantId},quantity);}}/><button type="button" onClick={()=>ask(product)} disabled={!id} className="min-h-11 rounded-xl border border-brand-green/40 px-3 font-semibold text-brand-green disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><MessageCircle aria-hidden="true" className="mr-2 inline h-4 w-4"/>Bu ürün hakkında sor</button></div>;})}</div>}</section>
 </article>;
}

function formatNumber(value:number){if(!Number.isFinite(value)||value<0)return'Doğrulanamadı';try{return new Intl.NumberFormat('tr-TR').format(value);}catch{return String(Math.floor(value));}}
