import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "@supabase/supabase-js";

const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function json(status:number,body:Record<string,unknown>){return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});}
function isRecord(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==="object"&&!Array.isArray(value);}
function text(value:unknown,max:number){const next=typeof value==="string"?value.trim():value==null?"":String(value).trim();if(!next||next.length>max||/[\u0000-\u001F\u007F]/.test(next))return"";return next;}
function uuid(value:unknown){const next=text(value,80);return UUID_RE.test(next)?next:"";}
function safeBaseUrl(raw:string){const value=raw.replace(/\/$/,"");if(value!=="https://api.iyzipay.com"&&value!=="https://sandbox-api.iyzipay.com")throw new Error("invalid_iyzico_base_url");return value;}
async function hmacHex(secret:string,value:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const signature=new Uint8Array(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(value)));return Array.from(signature).map(byte=>byte.toString(16).padStart(2,"0")).join("");}
function sameHex(a:string,b:string){const left=a.toLowerCase(),right=b.toLowerCase();if(!left||left.length!==right.length)return false;let diff=0;for(let i=0;i<left.length;i++)diff|=left.charCodeAt(i)^right.charCodeAt(i);return diff===0;}
async function signedProviderRequest(path:"/payment/detail",payload:Record<string,unknown>){const apiKey=Deno.env.get("IYZICO_API_KEY")?.trim()||"",secretKey=Deno.env.get("IYZICO_SECRET_KEY")?.trim()||"",baseRaw=Deno.env.get("IYZICO_BASE_URL")?.trim()||"";if(!apiKey||!secretKey||!baseRaw)throw new Error("payment_provider_credentials_missing");const base=safeBaseUrl(baseRaw),body=JSON.stringify(payload),randomKey=`${Date.now()}${crypto.randomUUID().replaceAll("-","")}`,requestSignature=await hmacHex(secretKey,randomKey+path+body),authorizationString=`apiKey:${apiKey}&randomKey:${randomKey}&signature:${requestSignature}`;const response=await fetch(`${base}${path}`,{method:"POST",headers:{Authorization:`IYZWSv2 ${btoa(authorizationString)}`,"x-iyzi-rnd":randomKey,"Content-Type":"application/json",Accept:"application/json"},body,signal:AbortSignal.timeout(15000)});const parsed=await response.json().catch(()=>null);if(!response.ok||!isRecord(parsed)||parsed.status!=="success")throw new Error("payment_detail_unavailable");return{data:parsed,secretKey};}
async function verifyResponse(data:Record<string,unknown>,secretKey:string){const signature=text(data.signature,256);if(!signature)return false;const values=[data.paymentId,data.currency,data.basketId,data.conversationId,data.paidPrice,data.price].map(value=>String(value??""));if(values.some(value=>!value))return false;return sameHex(await hmacHex(secretKey,values.join(":")),signature);}
function classify(data:Record<string,unknown>):"captured"|"authorized"|"failed"{const fraud=Number(data.fraudStatus);if(fraud===1)return"captured";if(fraud===0)return"authorized";return"failed";}
function safeDetail(data:Record<string,unknown>){const keys=["status","systemTime","conversationId","paymentId","price","paidPrice","installment","fraudStatus","iyziCommissionRateAmount","iyziCommissionFee","cardType","cardAssociation","cardFamily","lastFourDigits","basketId","currency","paymentStatus"];const out:Record<string,unknown>={signatureVerified:true,source:"webhook_reconciliation"};for(const key of keys)if(data[key]!=null)out[key]=data[key];return out;}
async function complete(service:any,intentId:string,providerReference:string,status:"captured"|"authorized"|"failed"|"cancelled",payload:Record<string,unknown>,failureCode?:string|null,failureMessage?:string|null){const{data,error}=await service.rpc("complete_order_payment_for_service_v1",{p_intent_id:intentId,p_provider_reference:providerReference,p_status:status,p_provider_payload:payload,p_failure_code:failureCode||null,p_failure_message:failureMessage||null});if(error)throw error;return data;}

Deno.serve(async(req:Request)=>{
  if(req.method!=="POST")return json(405,{ok:false,error:"method_not_allowed"});
  try{
    const secretKey=Deno.env.get("IYZICO_SECRET_KEY")?.trim()||"";const serviceUrl=Deno.env.get("SUPABASE_URL")||"",serviceRoleKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!secretKey||!serviceUrl||!serviceRoleKey)return json(503,{ok:false,error:"webhook_configuration_missing"});
    const raw=await req.json().catch(()=>null);if(!isRecord(raw))return json(400,{ok:false,error:"invalid_webhook_payload"});
    const eventType=text(raw.iyziEventType,80),paymentId=text(raw.paymentId,220)||text(raw.iyziPaymentId,220),conversationId=uuid(raw.paymentConversationId),status=text(raw.status,40).toUpperCase(),signature=text(req.headers.get("X-IYZ-SIGNATURE-V3"),256);
    if(!eventType||!paymentId||!conversationId||!status||!signature)return json(400,{ok:false,error:"invalid_webhook_payload"});
    const expected=await hmacHex(secretKey,secretKey+eventType+paymentId+conversationId+status);if(!sameHex(expected,signature))return json(401,{ok:false,error:"invalid_webhook_signature"});
    const service=createClient(serviceUrl,serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false}});const{data:intent,error:intentError}=await service.rpc("get_payment_intent_for_service_v1",{p_intent_id:conversationId});if(intentError)throw intentError;if(!isRecord(intent)||text(intent.provider,40)!=="iyzico")return json(404,{ok:false,error:"payment_intent_not_found"});
    if(text(intent.providerReference,220)&&text(intent.providerReference,220)!==paymentId&&text(intent.status,40)==="captured")return json(409,{ok:false,error:"payment_reference_mismatch"});
    if(status==="FAILURE"){
      const result=await complete(service,conversationId,paymentId,"failed",{signatureVerified:true,source:"iyzico_webhook",iyziEventType:eventType,paymentId,paymentConversationId:conversationId,status},"provider_webhook_failure","Ödeme sağlayıcısı işlemin başarısız olduğunu bildirdi.");return json(200,{ok:true,state:"failed",result});
    }
    if(status!=="SUCCESS")return json(200,{ok:true,state:"ignored",status});
    const{data:detail,secretKey:detailSecret}=await signedProviderRequest("/payment/detail",{locale:"tr",conversationId:crypto.randomUUID(),paymentId,paymentConversationId:conversationId});if(!await verifyResponse(detail,detailSecret))return json(502,{ok:false,error:"payment_detail_signature_invalid"});
    if(text(detail.paymentId,220)!==paymentId)return json(409,{ok:false,error:"payment_detail_reference_mismatch"});
    if(text(detail.currency,3).toUpperCase()!==text(intent.currency,3).toUpperCase())return json(409,{ok:false,error:"payment_detail_currency_mismatch"});
    const amountMinor=typeof intent.amountMinor==="number"&&Number.isSafeInteger(intent.amountMinor)?intent.amountMinor:null;if(amountMinor==null||Math.round(Number(detail.paidPrice)*100)!==amountMinor)return json(409,{ok:false,error:"payment_detail_amount_mismatch"});
    const state=classify(detail);const result=await complete(service,conversationId,paymentId,state,safeDetail(detail),state==="failed"?"fraud_rejected":null,state==="failed"?"Ödeme sağlayıcısı işlemi reddetti.":null);return json(200,{ok:true,state,result});
  }catch(error){const message=error instanceof Error?error.message:"payment_webhook_failed";const safe=message.length<=300&&!/[\u0000-\u001F\u007F]/.test(message)?message:"payment_webhook_failed";return json(503,{ok:false,error:safe});}
});
