import { supabase } from '../../lib/supabase';

export type ProducerEventSubmissionStatus='pending'|'needs_changes'|'approved'|'rejected'|'withdrawn';
export type ProducerEventSubmission={id:string;title:string;description:string;imagePath:string|null;locationName:string;locationDetails:Record<string,unknown>;startsAt:string;endsAt:string;capacity:number|null;reservationDeadline:string|null;ticketPriceMinor:number;currency:string;status:ProducerEventSubmissionStatus;reviewReason:string|null;eventId:string|null;createdAt:string;updatedAt:string;};
export type ProducerEventSaveResult={id:string;status:'pending';ticketPriceMinor:number;currency:string;};
const STATUSES=new Set<ProducerEventSubmissionStatus>(['pending','needs_changes','approved','rejected','withdrawn']);
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function unwrap<T>(data:T|null,error:unknown):T{if(error)throw error;return data as T;}
function record(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function text(value:unknown,label:string,max:number,required=true){if(value==null||value===''){if(required)throw new Error(`${label} doğrulanamadı.`);return null;}if(typeof value!=='string')throw new Error(`${label} doğrulanamadı.`);const next=value.trim();if((required&&!next)||next.length>max||/[\u0000-\u001F\u007F]/.test(next))throw new Error(`${label} doğrulanamadı.`);return next||null;}
function uuid(value:unknown,label:string,required=true){const next=text(value,label,36,required);if(next==null)return null;if(!UUID_RE.test(next))throw new Error(`${label} doğrulanamadı.`);return next;}
function integer(value:unknown,label:string,min:number,max:number,required=true){if(value==null){if(required)throw new Error(`${label} doğrulanamadı.`);return null;}if(typeof value!=='number'||!Number.isSafeInteger(value)||value<min||value>max)throw new Error(`${label} doğrulanamadı.`);return value;}
function date(value:unknown,label:string,required=true){const next=text(value,label,80,required);if(next==null)return null;if(Number.isNaN(Date.parse(next)))throw new Error(`${label} doğrulanamadı.`);return next;}
function currency(value:unknown){const next=(text(value,'Etkinlik para birimi',3,true) as string).toUpperCase();if(!/^[A-Z]{3}$/.test(next))throw new Error('Etkinlik para birimi doğrulanamadı.');return next;}
function normalize(value:unknown,index:number):ProducerEventSubmission{if(!record(value)||!record(value.locationDetails))throw new Error(`${index+1}. etkinlik başvurusu doğrulanamadı.`);const status=text(value.status,'Etkinlik başvuru durumu',40,true) as ProducerEventSubmissionStatus;if(!STATUSES.has(status))throw new Error('Etkinlik başvuru durumu doğrulanamadı.');const startsAt=date(value.startsAt,'Etkinlik başlangıcı',true) as string,endsAt=date(value.endsAt,'Etkinlik bitişi',true) as string;if(new Date(endsAt).getTime()<=new Date(startsAt).getTime())throw new Error('Etkinlik tarih aralığı doğrulanamadı.');const deadline=date(value.reservationDeadline,'Kayıt son tarihi',false);if(deadline&&new Date(deadline).getTime()>new Date(startsAt).getTime())throw new Error('Kayıt son tarihi doğrulanamadı.');return{id:uuid(value.id,'Etkinlik başvuru kimliği',true) as string,title:text(value.title,'Etkinlik adı',180,true) as string,description:text(value.description,'Etkinlik açıklaması',20000,true) as string,imagePath:text(value.imagePath,'Etkinlik görseli',1200,false),locationName:text(value.locationName,'Etkinlik konumu',500,true) as string,locationDetails:value.locationDetails,startsAt,endsAt,capacity:integer(value.capacity,'Etkinlik kapasitesi',1,1000000,false),reservationDeadline:deadline,ticketPriceMinor:integer(value.ticketPriceMinor,'Etkinlik bilet fiyatı',0,100000000000,true) as number,currency:currency(value.currency),status,reviewReason:text(value.reviewReason,'İnceleme gerekçesi',2000,false),eventId:uuid(value.eventId,'Yayınlanan etkinlik kimliği',false),createdAt:date(value.createdAt,'Oluşturma tarihi',true) as string,updatedAt:date(value.updatedAt,'Güncelleme tarihi',true) as string};}
export async function listMyProducerEventSubmissions(){const{data,error}=await supabase.rpc('list_my_producer_event_submissions_v1');const rows=unwrap<unknown>(data,error);if(!Array.isArray(rows)||rows.length>1000)throw new Error('Etkinlik başvuruları doğrulanamadı.');return rows.map(normalize);}
export async function saveProducerEventSubmission(submissionId:string|null,payload:Record<string,unknown>):Promise<ProducerEventSaveResult>{if(submissionId&&!UUID_RE.test(submissionId))throw new Error('Etkinlik başvuru kimliği doğrulanamadı.');if(!record(payload))throw new Error('Etkinlik başvuru paketi doğrulanamadı.');const{data,error}=await supabase.rpc('producer_upsert_event_submission_v1',{p_submission_id:submissionId||null,p_payload:payload});const result=unwrap<unknown>(data,error);if(!record(result))throw new Error('Etkinlik kayıt sonucu doğrulanamadı.');const status=text(result.status,'Etkinlik kayıt durumu',40,true);if(status!=='pending')throw new Error('Etkinlik kayıt durumu doğrulanamadı.');return{id:uuid(result.id,'Etkinlik başvuru kimliği',true) as string,status:'pending',ticketPriceMinor:integer(result.ticketPriceMinor,'Etkinlik bilet fiyatı',0,100000000000,true) as number,currency:currency(result.currency)};}
export async function uploadProducerEventImage(producerId:string,file:File){if(!UUID_RE.test(producerId))throw new Error('Satıcı kimliği doğrulanamadı.');if(!(file instanceof File))throw new Error('Etkinlik görseli doğrulanamadı.');const allowed=['image/jpeg','image/png','image/webp','image/avif'];if(!allowed.includes(file.type))throw new Error('Etkinlik görseli JPEG, PNG, WebP veya AVIF olmalıdır.');if(file.size<=0||file.size>10*1024*1024)throw new Error('Etkinlik görseli en fazla 10 MB olabilir.');const ext=file.type==='image/jpeg'?'jpg':file.type==='image/png'?'png':file.type==='image/avif'?'avif':'webp';const path=`${producerId}/events/${crypto.randomUUID()}.${ext}`;const{error}=await supabase.storage.from('event-public').upload(path,file,{contentType:file.type,upsert:false,cacheControl:'31536000'});if(error)throw error;return path;}
export async function removeProducerEventImage(path:string){const normalized=text(path,'Etkinlik görsel yolu',1200,true) as string;const{error}=await supabase.storage.from('event-public').remove([normalized]);if(error)throw error;}
export function publicEventImageUrl(path?:string|null){if(!path)return'';return supabase.storage.from('event-public').getPublicUrl(path).data.publicUrl;}
export function producerEventErrorMessage(error:unknown,fallback='Etkinlik işlemi tamamlanamadı.'){const message=String((error as{message?:unknown}|null)?.message||'').trim();const map:Array<[string,string]>=[['verified_active_producer_required','Etkinlik göndermek için aktif, menşei doğrulanmış ve Doğrulanmış Üretici rozetine sahip satıcı hesabı gerekir.'],['platform_access_blocked','Hesap güvenlik politikası nedeniyle etkinlik gönderemezsiniz.'],['producer_portal_separate_from_admin','Super Admin hesabı satıcı etkinlik başvuru yolunu kullanamaz.'],['stored_event_image_required','Seçtiğiniz etkinlik görseli güvenli depolamada doğrulanamadı.'],['invalid_event_date_range','Etkinliğin başlangıcı gelecekte olmalı ve bitiş başlangıçtan sonra olmalıdır.'],['invalid_event_reservation_deadline','Kayıt son tarihi etkinlik başlangıcından sonra olamaz.'],['event_submission_not_editable','Bu etkinlik başvurusu artık düzenlenemez.'],['event_submission_not_found','Etkinlik başvurusu bulunamadı.']];for(const[key,textValue]of map)if(message.includes(key))return textValue;return message||fallback;}
