import React,{useMemo,useState}from'react';
import{CheckCircle2,Save,ShieldCheck,XCircle}from'lucide-react';
import{emptyProductHealthPayload,normalizeProductHealthPayload,productHealthErrorMessage,publishAdminProductHealth,rejectAdminProductHealthChange,saveSellerProductHealthChange,type ProductHealthPayload,type ProductHealthWarning}from'./productHealthEditorApi';

type Props={mode:'seller'|'super_admin';productId:string;productName:string;initial?:ProductHealthPayload|null;requestId?:string|null;onDone?:()=>void|Promise<void>;onBack?:()=>void};
type NutritionKey='energyKcal'|'proteinG'|'carbohydrateG'|'sugarsG'|'fatG'|'saturatedFatG'|'fiberG'|'saltG';
const nutritionLabels:Record<NutritionKey,string>={energyKcal:'Enerji (kcal)',proteinG:'Protein (g)',carbohydrateG:'Karbonhidrat (g)',sugarsG:'Şeker (g)',fatG:'Yağ (g)',saturatedFatG:'Doymuş yağ (g)',fiberG:'Lif (g)',saltG:'Tuz (g)'};
function lines(value:string[]){return value.join('\n');}function parseLines(value:string,max=60){return value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean).slice(0,max);}function warningLines(rows:ProductHealthWarning[]){return rows.map(row=>`[${row.severity}] ${row.text}`).join('\n');}
function parseWarnings(value:string):ProductHealthWarning[]{return parseLines(value,20).map(line=>{const match=line.match(/^\[(info|low|medium|high)\]\s*(.+)$/i);return{severity:(match?.[1]?.toLowerCase()||'info')as ProductHealthWarning['severity'],text:(match?.[2]||line).trim()};});}

export default function ProductHealthEditorForm({mode,productId,productName,initial,requestId,onDone,onBack}:Props){
 const seed=useMemo(()=>normalizeProductHealthPayload(initial||emptyProductHealthPayload()),[initial]);
 const[summary,setSummary]=useState(seed.summary);const[ingredients,setIngredients]=useState(lines(seed.productInfo.ingredients));const[usage,setUsage]=useState(lines(seed.productInfo.usageNotes));const[storage,setStorage]=useState(lines(seed.safety.storage));const[preparation,setPreparation]=useState(lines(seed.safety.preparation));const[allergens,setAllergens]=useState(lines(seed.safety.allergens));const[allergenNote,setAllergenNote]=useState(seed.safety.allergenNote);const[verification,setVerification]=useState(lines(seed.safety.verificationNeeded));const[claimPolicy,setClaimPolicy]=useState(seed.safety.claimPolicy);const[warnings,setWarnings]=useState(warningLines(seed.safety.warnings));const[serving,setServing]=useState(seed.productInfo.nutrition.servingSize||'');
 const[nutrition,setNutrition]=useState<Record<NutritionKey,string>>(()=>Object.fromEntries((Object.keys(nutritionLabels)as NutritionKey[]).map(key=>[key,seed.productInfo.nutrition[key]?.toString()||'']))as Record<NutritionKey,string>);
 const[recipeEnabled,setRecipeEnabled]=useState(seed.recipe.enabled);const[recipeTitle,setRecipeTitle]=useState(seed.recipe.title);const[recipeIngredients,setRecipeIngredients]=useState(lines(seed.recipe.ingredients));const[recipeSteps,setRecipeSteps]=useState(lines(seed.recipe.steps));const[servings,setServings]=useState(seed.recipe.servings?.toString()||'');const[prepMinutes,setPrepMinutes]=useState(seed.recipe.prepMinutes?.toString()||'');const[cookMinutes,setCookMinutes]=useState(seed.recipe.cookMinutes?.toString()||'');
 const[reviewNote,setReviewNote]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[status,setStatus]=useState('');
 function numeric(value:string){if(!value.trim())return undefined;const n=Number(value);if(!Number.isFinite(n)||n<0)throw new Error('Besin ve süre değerleri negatif olamaz.');return n;}
 function payload():ProductHealthPayload{const n:Record<string,unknown>={};if(serving.trim())n.servingSize=serving.trim();for(const key of Object.keys(nutritionLabels)as NutritionKey[]){const value=numeric(nutrition[key]);if(value!=null)n[key]=value;}return normalizeProductHealthPayload({summary,productInfo:{ingredients:parseLines(ingredients),usageNotes:parseLines(usage,30),nutrition:n},safety:{storage:parseLines(storage,30),preparation:parseLines(preparation,30),warnings:parseWarnings(warnings),allergens:parseLines(allergens,30),allergenNote,verificationNeeded:parseLines(verification,30),claimPolicy},recipe:{enabled:recipeEnabled,title:recipeTitle,servings:numeric(servings),prepMinutes:numeric(prepMinutes),cookMinutes:numeric(cookMinutes),ingredients:parseLines(recipeIngredients),steps:parseLines(recipeSteps,40)}});}
 async function save(){if(busy)return;try{setBusy(true);setError('');setStatus('');const next=payload();if(mode==='seller'){await saveSellerProductHealthChange(productId,next);setStatus('Ürün bilgileri Super Admin incelemesine gönderildi. Mevcut yayın değiştirilmedi.');}else{await publishAdminProductHealth(productId,next,reviewNote,requestId);setStatus('Onaylanmış ürün bilgileri müşterilere yayınlandı.');}await onDone?.();}catch(err){setError(productHealthErrorMessage(err));}finally{setBusy(false);}}
 async function reject(){if(mode!=='super_admin'||!requestId||busy)return;try{setBusy(true);setError('');setStatus('');await rejectAdminProductHealthChange(requestId,reviewNote);setStatus('Ürün bilgisi talebi reddedildi.');await onDone?.();}catch(err){setError(productHealthErrorMessage(err));}finally{setBusy(false);}}
 return<div className="space-y-5"><header className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-black">{productName}</h2><p className="mt-1 text-sm text-gray-500">İçerik, besin, alerjen, saklama ve kullanım bilgileri. Hasat, üretim, paketleme ve tavsiye edilen tüketim tarihleri Lot ve İzlenebilirlik bölümünde yönetilir.</p></div>{onBack?<button type="button" onClick={onBack} disabled={busy} className="min-h-11 rounded-xl border px-4 font-semibold">Geri</button>:null}</header>
 {error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>:null}{status?<div role="status" className="rounded-xl border border-green-200 bg-green-50 p-3 text-sm text-green-800">{status}</div>:null}
 <section className="rounded-2xl border p-4"><h3 className="font-black">Temel ürün bilgisi</h3><Field label="Müşteriye gösterilecek kısa açıklama"><textarea rows={3} maxLength={2000} value={summary} onChange={e=>setSummary(e.target.value)} className="w-full rounded-xl border p-3"/></Field><Field label="İçindekiler - her satıra bir öğe"><textarea rows={5} value={ingredients} onChange={e=>setIngredients(e.target.value)} className="w-full rounded-xl border p-3"/></Field><Field label="Kullanım notları - her satıra bir öğe"><textarea rows={4} value={usage} onChange={e=>setUsage(e.target.value)} className="w-full rounded-xl border p-3"/></Field></section>
 <section className="rounded-2xl border p-4"><h3 className="font-black">Besin değerleri</h3><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label><span className="text-sm font-semibold">Porsiyon</span><input value={serving} maxLength={120} onChange={e=>setServing(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label>{(Object.keys(nutritionLabels)as NutritionKey[]).map(key=><label key={key}><span className="text-sm font-semibold">{nutritionLabels[key]}</span><input type="number" min="0" step="any" value={nutrition[key]} onChange={e=>setNutrition(v=>({...v,[key]:e.target.value}))} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label>)}</div></section>
 <section className="rounded-2xl border p-4"><h3 className="font-black">Güvenli kullanım</h3><div className="mt-3 grid gap-4 lg:grid-cols-2"><Field label="Saklama - her satıra bir madde"><textarea rows={5} value={storage} onChange={e=>setStorage(e.target.value)} className="w-full rounded-xl border p-3"/></Field><Field label="Hazırlama / kullanım - her satıra bir madde"><textarea rows={5} value={preparation} onChange={e=>setPreparation(e.target.value)} className="w-full rounded-xl border p-3"/></Field><Field label="Alerjenler - her satıra bir öğe"><textarea rows={4} value={allergens} onChange={e=>setAllergens(e.target.value)} className="w-full rounded-xl border p-3"/></Field><Field label="Alerjen açıklaması"><textarea rows={4} maxLength={1000} value={allergenNote} onChange={e=>setAllergenNote(e.target.value)} className="w-full rounded-xl border p-3"/></Field><Field label="Uyarılar - [high], [medium], [low] veya [info] ile başlayabilir"><textarea rows={5} value={warnings} onChange={e=>setWarnings(e.target.value)} className="w-full rounded-xl border p-3"/></Field><Field label="Ürüne özel doğrulanması gerekenler"><textarea rows={5} value={verification} onChange={e=>setVerification(e.target.value)} className="w-full rounded-xl border p-3"/></Field></div><Field label="Beyan politikası"><textarea rows={3} maxLength={1000} value={claimPolicy} onChange={e=>setClaimPolicy(e.target.value)} className="w-full rounded-xl border p-3"/></Field><div className="mt-3 flex gap-2 rounded-xl bg-amber-50 p-3 text-sm text-amber-950"><ShieldCheck aria-hidden="true" className="mt-0.5 h-5 w-5 shrink-0"/><p>Tedavi, mucize, hastalık önleme veya doğrulanmamış sağlık iddiaları sunucu tarafından reddedilir.</p></div></section>
 <section className="rounded-2xl border p-4"><label className="flex min-h-11 items-center gap-3 font-bold"><input type="checkbox" checked={recipeEnabled} onChange={e=>setRecipeEnabled(e.target.checked)} className="h-5 w-5"/>Tarif bilgisini yayın paketine ekle</label>{recipeEnabled?<div className="mt-3 space-y-3"><label><span className="text-sm font-semibold">Tarif başlığı</span><input value={recipeTitle} maxLength={240} onChange={e=>setRecipeTitle(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label><div className="grid gap-3 sm:grid-cols-3"><NumberField label="Porsiyon" value={servings} setValue={setServings}/><NumberField label="Hazırlık (dk)" value={prepMinutes} setValue={setPrepMinutes}/><NumberField label="Pişirme (dk)" value={cookMinutes} setValue={setCookMinutes}/></div><Field label="Tarif malzemeleri"><textarea rows={5} value={recipeIngredients} onChange={e=>setRecipeIngredients(e.target.value)} className="w-full rounded-xl border p-3"/></Field><Field label="Tarif adımları"><textarea rows={6} value={recipeSteps} onChange={e=>setRecipeSteps(e.target.value)} className="w-full rounded-xl border p-3"/></Field></div>:null}</section>
 {mode==='super_admin'?<section className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><h3 className="font-black">Super Admin kararı</h3><textarea rows={3} maxLength={2000} value={reviewNote} onChange={e=>setReviewNote(e.target.value)} placeholder="İnceleme / ret notu" className="mt-3 w-full rounded-xl border bg-white p-3"/><div className="mt-3 grid gap-3 sm:grid-cols-2"><button type="button" disabled={busy} onClick={()=>void save()} className="min-h-11 rounded-xl bg-brand-green px-4 font-bold text-brand-on-green"><CheckCircle2 aria-hidden="true" className="mr-2 inline h-4 w-4"/>{busy?'İşleniyor...':'Onayla ve yayınla'}</button>{requestId?<button type="button" disabled={busy||reviewNote.trim().length<10} onClick={()=>void reject()} className="min-h-11 rounded-xl bg-red-700 px-4 font-bold text-white disabled:opacity-50"><XCircle aria-hidden="true" className="mr-2 inline h-4 w-4"/>Talebi reddet</button>:null}</div></section>:<button type="button" disabled={busy} onClick={()=>void save()} className="min-h-12 w-full rounded-xl bg-brand-green px-5 font-black text-brand-on-green"><Save aria-hidden="true" className="mr-2 inline h-5 w-5"/>{busy?'Gönderiliyor...':'Super Admin incelemesine gönder'}</button>}
 </div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return<label className="mt-3 block"><span className="mb-1 block text-sm font-semibold">{label}</span>{children}</label>;}
function NumberField({label,value,setValue}:{label:string;value:string;setValue:(value:string)=>void}){return<label><span className="text-sm font-semibold">{label}</span><input type="number" min="0" step="1" value={value} onChange={e=>setValue(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label>;}
