export type RecordValue=Record<string,unknown>;
export type BuyerIdentityType='tc_identity'|'passport';
export const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export const PAYMENT_CURRENCIES=new Set(['TRY','USD','EUR','GBP','NOK','CHF']);

export function isRecord(value:unknown):value is RecordValue{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
export function text(value:unknown,max:number){if(typeof value!=='string')return'';const normalized=value.trim();if(!normalized||normalized.length>max||/[\u0000-\u001F\u007F]/.test(normalized))return'';return normalized;}
export function uuid(value:unknown){const normalized=text(value,80);return UUID_RE.test(normalized)?normalized:'';}
export function integer(value:unknown,min=0){return typeof value==='number'&&Number.isSafeInteger(value)&&value>=min?value:null;}
export function minorToMajor(value:number){if(!Number.isSafeInteger(value)||value<0)throw new Error('invalid_money');return(value/100).toFixed(2);}
export function decimalToMinor(value:unknown){const raw=typeof value==='number'&&Number.isFinite(value)?String(value):text(value,80);if(!raw||!/^[0-9]+(?:\.[0-9]+)?$/.test(raw))return null;const amount=Number(raw);if(!Number.isFinite(amount)||amount<0)return null;const minor=Math.round(amount*100);return Number.isSafeInteger(minor)?minor:null;}
export function validEmail(value:unknown){const email=text(value,254).toLowerCase();return/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)?email:'';}
export function validPhone(value:unknown){const phone=text(value,40),digits=phone.replace(/\D/g,'');return digits.length>=7&&digits.length<=20?phone:'';}
export function requestIp(req:Request){const candidates=[req.headers.get('cf-connecting-ip'),req.headers.get('x-real-ip'),req.headers.get('x-forwarded-for')?.split(',')[0]||null];for(const candidate of candidates){const normalized=(candidate||'').trim();if(normalized&&normalized.length<=64&&/^[0-9a-fA-F:.]+$/.test(normalized))return normalized;}throw new Error('payment_request_ip_required');}
export function fullNameParts(...candidates:unknown[]){for(const candidate of candidates){const normalized=text(candidate,240),parts=normalized.split(/\s+/).filter(Boolean);if(parts.length>=2)return{fullName:normalized,name:parts.slice(0,-1).join(' '),surname:parts[parts.length-1]};}throw new Error('payment_profile_full_name_required');}
function validTurkishIdentity(value:string){if(!/^[1-9][0-9]{10}$/.test(value))return false;const digits=value.split('').map(Number),odd=digits[0]+digits[2]+digits[4]+digits[6]+digits[8],even=digits[1]+digits[3]+digits[5]+digits[7];return((odd*7-even)%10)===digits[9]&&digits.slice(0,10).reduce((sum,digit)=>sum+digit,0)%10===digits[10];}
export function identityType(value:unknown):BuyerIdentityType{const normalized=text(value,30).toLowerCase();if(normalized==='tc_identity'||normalized==='passport')return normalized;throw new Error('buyer_identity_type_required');}
export function buyerIdentity(value:unknown,type:BuyerIdentityType){const normalized=text(value,40).replace(/\s+/g,'').toUpperCase();if(type==='tc_identity'){if(!validTurkishIdentity(normalized))throw new Error('payment_turkish_identity_invalid');return normalized;}if(!/^[A-Z0-9-]{5,30}$/.test(normalized))throw new Error('payment_passport_invalid');return normalized;}
export function addressContext(raw:unknown){if(!isRecord(raw))throw new Error('payment_address_invalid');const countryCode=text(raw.country_code??raw.countryCode,2).toUpperCase();if(!/^[A-Z]{2}$/.test(countryCode))throw new Error('payment_country_invalid');const city=text(raw.city??raw.district??raw.administrative_area??raw.province,160);if(!city)throw new Error('payment_city_required');const address=[text(raw.address_line1??raw.address_line,1000),text(raw.address_line2,500),text(raw.locality??raw.neighborhood,160)].filter(Boolean).join(' ').trim();if(address.length<5||address.length>1000)throw new Error('payment_address_invalid');const postalCode=text(raw.postal_code??raw.postalCode,30);if(!postalCode)throw new Error('payment_postal_code_required');const recipientName=text(raw.recipient_name??raw.recipientName,240);return{countryCode,city,address,postalCode,recipientName};}
export function marketplaceBasket(context:RecordValue){const priceMinor=integer(context.priceMinor,1),splitTotalMinor=integer(context.splitTotalMinor,1);if(priceMinor==null||splitTotalMinor==null||splitTotalMinor>priceMinor)throw new Error('payment_marketplace_totals_invalid');if(!Array.isArray(context.items)||context.items.length<1||context.items.length>100)throw new Error('payment_items_invalid');let priceSum=0,splitSum=0;const items=context.items.map(raw=>{if(!isRecord(raw))throw new Error('payment_item_invalid');const id=uuid(raw.id),name=text(raw.name,300),lineTotalMinor=integer(raw.lineTotalMinor,1),subMerchantKey=text(raw.subMerchantKey,500),subMerchantPriceMinor=integer(raw.subMerchantPriceMinor,1);if(!id||!name||lineTotalMinor==null||!subMerchantKey||subMerchantPriceMinor==null||subMerchantPriceMinor>lineTotalMinor)throw new Error('payment_marketplace_item_invalid');priceSum+=lineTotalMinor;splitSum+=subMerchantPriceMinor;if(!Number.isSafeInteger(priceSum)||!Number.isSafeInteger(splitSum))throw new Error('payment_marketplace_totals_invalid');return{id,name,category1:'Köy Ürünleri',itemType:'PHYSICAL',price:minorToMajor(lineTotalMinor),subMerchantKey,subMerchantPrice:minorToMajor(subMerchantPriceMinor)};});if(priceSum!==priceMinor||splitSum!==splitTotalMinor)throw new Error('payment_marketplace_totals_mismatch');return items;}
export function providerPaymentId(value:unknown){if(typeof value==='number'&&Number.isFinite(value))return String(value);return text(value,220);}
export function paymentMethodTypeFromProvider(data:RecordValue):'card'|'bank_transfer'|'wallet'|'other'{const event=text(data.iyziEventType,120).toUpperCase();if(event==='BANK_TRANSFER_AUTH'||event.includes('BANK_TRANSFER'))return'bank_transfer';if(event.startsWith('PWI_')||data.memberEmail||data.memberGsmNumber)return'wallet';if(text(data.cardAssociation,40)||text(data.cardType,40)||text(data.lastFourDigits,8))return'card';return'other';}
