import { iyzicoRequest, verifyIyzicoCheckoutRetrieveSignature, verifyIyzicoNon3dResponseSignature, type IyzicoJson } from './iyzico.ts';
import { decimalToMinor, integer, isRecord, paymentMethodTypeFromProvider, providerPaymentId, text, uuid, type RecordValue } from './commerce.ts';

function safeProviderPayload(data:IyzicoJson,signatureVerified:boolean){const allowed=['status','locale','systemTime','conversationId','paymentId','price','paidPrice','installment','fraudStatus','merchantCommissionRate','merchantCommissionRateAmount','iyziCommissionRateAmount','iyziCommissionFee','cardType','cardAssociation','cardFamily','lastFourDigits','basketId','currency','authCode','phase','hostReference','paymentStatus','token','callbackUrl','memberEmail','memberGsmNumber'];const result:RecordValue={signatureVerified};for(const key of allowed)if(data[key]!=null)result[key]=data[key];if(Array.isArray(data.itemTransactions))result.itemTransactions=data.itemTransactions.slice(0,100).map(item=>isRecord(item)?{itemId:item.itemId,paymentTransactionId:item.paymentTransactionId,transactionStatus:item.transactionStatus,price:item.price,paidPrice:item.paidPrice,subMerchantPrice:item.subMerchantPrice,iyziCommissionRateAmount:item.iyziCommissionRateAmount,iyziCommissionFee:item.iyziCommissionFee,merchantPayoutAmount:item.merchantPayoutAmount,subMerchantPayoutAmount:item.subMerchantPayoutAmount}:{});return result;}
function classify(data:IyzicoJson){const paymentStatus=text(data.paymentStatus,40).toUpperCase(),fraud=Number(data.fraudStatus);if(paymentStatus==='FAILURE')return'failed' as const;if(paymentStatus==='SUCCESS'){if(fraud===1||Number.isNaN(fraud))return'captured' as const;if(fraud===0)return'authorized' as const;if(fraud===-1)return'failed' as const;}if(fraud===1)return'captured' as const;if(fraud===0)return'authorized' as const;if(fraud===-1)return'failed' as const;throw new Error('payment_provider_status_invalid');}
function verifyContext(data:IyzicoJson,context:RecordValue,intentId:string,expectedToken?:string){const orderNumber=text(context.orderNumber,180),currency=text(context.currency,3).toUpperCase(),priceMinor=integer(context.priceMinor,1),amountMinor=integer(context.amountMinor,1);if(!orderNumber||priceMinor==null||amountMinor==null)throw new Error('payment_context_invalid');if(text(data.conversationId,180)!==intentId)throw new Error('payment_conversation_mismatch');if(text(data.basketId,180)!==orderNumber)throw new Error('payment_basket_mismatch');if(text(data.currency,3).toUpperCase()!==currency)throw new Error('payment_currency_mismatch');if(decimalToMinor(data.price)!==priceMinor||decimalToMinor(data.paidPrice)!==amountMinor)throw new Error('payment_amount_mismatch');if(expectedToken&&text(data.token,500)!==expectedToken)throw new Error('payment_token_mismatch');const paymentId=providerPaymentId(data.paymentId);if(!paymentId)throw new Error('payment_provider_reference_missing');return paymentId;}
async function complete(service:any,context:RecordValue,data:IyzicoJson,signatureVerified:boolean){const intentId=uuid(context.intentId);if(!intentId)throw new Error('payment_intent_invalid');const state=classify(data),providerReference=verifyContext(data,context,intentId,context.providerSessionToken?text(context.providerSessionToken,500):undefined),method=paymentMethodTypeFromProvider(data),providerPayload=safeProviderPayload(data,signatureVerified);const{data:result,error}=await service.rpc('complete_order_payment_for_service_v2',{p_intent_id:intentId,p_provider_reference:providerReference,p_payment_method_type:method,p_status:state,p_provider_payload:providerPayload,p_failure_code:state==='failed'?'provider_rejected':null,p_failure_message:state==='failed'?'Ödeme sağlayıcısı işlemi reddetti.':null});if(error)throw error;if(!isRecord(result)||result.ok!==true)throw new Error('payment_completion_invalid');return{ok:state!=='failed',state,intentId,orderId:uuid(context.orderId),orderNumber:text(context.orderNumber,180),result};}

export async function settleCheckoutToken(service:any,token:string,context?:RecordValue){const normalized=text(token,500);if(!normalized)throw new Error('hosted_payment_token_required');let ctx=context;if(!ctx){const{data,error}=await service.rpc('get_hosted_payment_intent_for_service_v1',{p_token:normalized});if(error)throw error;if(!isRecord(data))throw new Error('hosted_payment_context_invalid');ctx=data;}const intentId=uuid(ctx.intentId);if(!intentId||text(ctx.providerSessionToken,500)!==normalized)throw new Error('hosted_payment_context_invalid');const{response,data}=await iyzicoRequest('/payment/iyzipos/checkoutform/auth/ecom/detail','POST',{locale:'tr',conversationId:intentId,token:normalized});if(!response.ok||data.status!=='success')throw new Error('hosted_payment_retrieve_failed');const signatureVerified=await verifyIyzicoCheckoutRetrieveSignature(data);if(!signatureVerified)throw new Error('payment_provider_signature_invalid');return complete(service,ctx,data,true);}

export async function settleDirectIntent(service:any,context:RecordValue,paymentId?:string|null){const intentId=uuid(context.intentId);if(!intentId)throw new Error('payment_intent_invalid');const payload:RecordValue={locale:'tr',paymentConversationId:intentId};if(paymentId)payload.paymentId=paymentId;const{response,data}=await iyzicoRequest('/payment/detail','POST',payload);if(!response.ok||data.status!=='success')throw new Error('payment_retrieve_failed');const signatureVerified=await verifyIyzicoNon3dResponseSignature(data);if(!signatureVerified)throw new Error('payment_provider_signature_invalid');return complete(service,context,data,true);}
