import React,{useMemo,useState}from'react';
import{ArrowDownUp,Clock3,Droplets,Fish,Leaf,Mountain,Sparkles,Star,Wheat}from'lucide-react';
import CatalogProductCard from'../catalog/CatalogProductCard';
import{useLiveHomeCatalog,type LegacyHomeProduct}from'../catalog/useLiveHomeCatalog';
import{usePublicStorefrontConfig}from'../storefront/usePublicStorefrontConfig';
import HomeEventsSpotlight from'./HomeEventsSpotlight';

type Props={searchQuery:string;setSearchQuery:(value:string)=>void;onProductClick:(product:LegacyHomeProduct)=>void;onAddToCart:(product:LegacyHomeProduct,quantity:number)=>Promise<void>|void;onToggleFavorite:(product:LegacyHomeProduct)=>Promise<void>|void;favorites:string[];onShare:(product:LegacyHomeProduct)=>Promise<void>|void;onGift:(product:LegacyHomeProduct)=>Promise<void>|void;};
type SortOption='featured'|'rating'|'price-asc'|'price-desc';
function safeText(value:unknown,max=300){return typeof value==='string'?value.trim().slice(0,max):'';}
function safePrice(value:unknown){return typeof value==='number'&&Number.isFinite(value)&&value>=0?value:null;}
function safeRating(value:unknown){return typeof value==='number'&&Number.isFinite(value)&&value>=0&&value<=5?value:null;}
function prefersReducedMotion(){return typeof window!=='undefined'&&window.matchMedia?.('(prefers-reduced-motion: reduce)').matches===true;}
function CategoryGlyph({name}:{name:string}){const value=name.toLocaleLowerCase('tr-TR');if(value.includes('balık')||value.includes('et')||value.includes('yumurta'))return<Fish aria-hidden="true"/>;if(value.includes('süt')||value.includes('şarküteri'))return<Droplets aria-hidden="true"/>;if(value.includes('tahıl')||value.includes('un')||value.includes('buğday'))return<Wheat aria-hidden="true"/>;if(value.includes('dağ')||value.includes('yayla'))return<Mountain aria-hidden="true"/>;return<Leaf aria-hidden="true"/>;}
function SectionGlyph({id}:{id:string}){if(id==='featured'||id==='best_sellers')return<Star aria-hidden="true"/>;if(id==='pre_order')return<Clock3 aria-hidden="true"/>;if(id==='seasonal')return<Leaf aria-hidden="true"/>;return<Sparkles aria-hidden="true"/>;}
function navigateToCategories(){const url=new URL(window.location.href);url.search='';url.hash='';url.searchParams.set('tab','categories');const depth=Number(window.history.state?.goldenOremarDepth);const nextDepth=Number.isSafeInteger(depth)&&depth>=0?depth+1:1;const state={...window.history.state,goldenOremar:true,goldenOremarDepth:nextDepth,tab:'categories'};window.history.pushState(state,'',url.toString());window.dispatchEvent(new PopStateEvent('popstate',{state}));window.scrollTo({top:0,behavior:'auto'});}

export default function HomeSection({searchQuery,setSearchQuery,onProductClick,onAddToCart,onToggleFavorite,favorites,onShare,onGift}:Props){
 const{staticContent,heroCategories,homeSections,eventSpotlight,salesReadiness,loading:storefrontLoading,error:storefrontError}=usePublicStorefrontConfig('tr');
 const{products,categories,loading:catalogLoading,error:catalogError}=useLiveHomeCatalog();
 const[sort,setSort]=useState<SortOption>('featured');
 const interfaceContent=staticContent?.interface??null;
 const categoriesTitle=interfaceContent?safeText(interfaceContent.categoriesTitle,200):'Kategoriler';
 const loading=storefrontLoading||catalogLoading,hasLoadError=Boolean(storefrontError||catalogError),salesPaused=salesReadiness?.status==='blocked_pending_business_identity';
 const quickCategories=useMemo(()=>{const liveById=new Map(categories.filter(category=>category.productCount>0).map(category=>[category.id,category]));const managed=heroCategories.map(config=>liveById.get(config.targetCategory)).filter((category):category is NonNullable<typeof category>=>Boolean(category));const managedIds=new Set(managed.map(category=>category.id));const fallback=categories.filter(category=>category.productCount>0&&!managedIds.has(category.id));return[...managed,...fallback].slice(0,10);},[categories,heroCategories]);
 const categoryPreviewImages=useMemo(()=>{const result=new Map<string,string[]>();for(const category of quickCategories){result.set(category.id,products.filter(product=>product.categorySlug===category.id&&Boolean(product.image)).map(product=>product.image).filter(Boolean).slice(0,3));}return result;},[products,quickCategories]);
 const sortedProducts=useMemo(()=>{const result=[...products];if(sort==='price-asc'||sort==='price-desc')return result.sort((a,b)=>{const ap=safePrice(a.price),bp=safePrice(b.price);if(ap===null&&bp===null)return 0;if(ap===null)return 1;if(bp===null)return-1;return sort==='price-asc'?ap-bp:bp-ap;});if(sort==='rating')return result.sort((a,b)=>(safeRating(b.rating)??-1)-(safeRating(a.rating)??-1));return result.sort((a,b)=>Number(b.is_featured)-Number(a.is_featured)||(b.reviewCount??0)-(a.reviewCount??0));},[products,sort]);
 function sectionProducts(id:string){let source:LegacyHomeProduct[]=[];if(id==='featured')source=products.filter(product=>product.is_featured||product.homeSection==='featured');else if(id==='pre_order')source=products.filter(product=>product.preOrder||product.homeSection==='pre_order');else if(id==='seasonal')source=products.filter(product=>product.stockMode==='seasonal'||product.homeSection==='seasonal');else if(id==='best_sellers'){const assigned=products.filter(product=>product.homeSection==='best_sellers');source=assigned.length?assigned:[...products].filter(product=>(product.reviewCount??0)>0).sort((a,b)=>(b.reviewCount??0)-(a.reviewCount??0)||(b.rating??0)-(a.rating??0));}else if(id==='offers')source=products.filter(product=>product.homeSection==='offers'||(safePrice(product.originalPrice)!==null&&safePrice(product.price)!==null&&(product.originalPrice as number)>(product.price as number)));else source=products.filter(product=>product.homeSection===id);return Array.from(new Map(source.map(product=>[product.id,product])).values()).slice(0,10);}
 const offerProducts=sectionProducts('offers');
 const showCampaign=!searchQuery&&Boolean(interfaceContent)&&offerProducts.length>0;
 function isFavorite(product:LegacyHomeProduct){return favorites.includes(String(product.legacyId||product.id));}
 function chooseCategory(slug:string){const url=new URL(window.location.href);url.search='';url.hash='';url.searchParams.set('tab','categories');url.searchParams.set('category',slug);const depth=Number(window.history.state?.goldenOremarDepth);const nextDepth=Number.isSafeInteger(depth)&&depth>=0?depth+1:1;const state={...window.history.state,goldenOremar:true,goldenOremarDepth:nextDepth,tab:'categories'};window.history.pushState(state,'',url.toString());window.dispatchEvent(new PopStateEvent('popstate',{state}));window.scrollTo({top:0,behavior:'auto'});}
 function renderEvents(placement:'after_hero'|'after_categories'|'before_products'){return!searchQuery&&eventSpotlight?.enabled&&eventSpotlight.placement===placement?<HomeEventsSpotlight settings={eventSpotlight}/>:null;}
 const visibleSections=homeSections.filter(section=>section.active).map(section=>({...section,items:sectionProducts(section.id)})).filter(section=>section.items.length>0);
 const showcaseProducts=sortedProducts.slice(0,10);

 return<div className="go-premium-home go-reference-home" data-video-reference-home="true" data-reference-layout="approved-recording-marketplace">
  <section className="mx-auto max-w-7xl px-4 pt-4 sm:px-6 sm:pt-6" aria-labelledby="home-title">
   <h1 id="home-title" className="sr-only">Golden Oremar ürünleri</h1>
   {loading?<div role="status" aria-live="polite" className="mb-4 rounded-2xl border border-brand-border bg-brand-card px-4 py-3 text-center text-sm font-semibold text-brand-muted">Seçkiler hazırlanıyor…</div>:null}
   {hasLoadError?<CustomerNotice>Mağazanın bir bölümü şu anda yenilenemiyor. Mevcut içerikleri incelemeye devam edebilirsiniz.</CustomerNotice>:null}
   {salesPaused&&salesReadiness?<CustomerNotice>{safeText(salesReadiness.message,500)}</CustomerNotice>:null}

   {!searchQuery&&quickCategories.length?<section className="go-reference-category-section" aria-labelledby="home-categories-title"><h2 id="home-categories-title" className="sr-only">{categoriesTitle}</h2><div className="go-reference-category-rail hide-scrollbar" role="list">{quickCategories.map(category=>{const previews=categoryPreviewImages.get(category.id)||[];return<button type="button" role="listitem" key={category.id} onClick={()=>chooseCategory(category.id)} className="go-reference-category-card focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><span className="go-reference-category-card__top"><span className="go-reference-category-card__glyph"><CategoryGlyph name={category.name}/></span><span className="go-reference-category-card__previews" aria-hidden="true">{previews.map((image,index)=><span className="go-reference-category-card__preview" key={`${category.id}-${index}`}><img src={image} alt="" loading="lazy" decoding="async"/></span>)}</span></span><span className="go-reference-category-card__title">{category.name}</span><span className="go-reference-category-card__description">{safeText(category.description,220)||`${category.productCount} ürün`}</span></button>;})}</div></section>:null}
   {renderEvents('after_categories')}
  </section>

  {showCampaign&&interfaceContent?<section className="go-reference-campaign mx-auto mt-7 max-w-7xl px-4 sm:px-6" aria-label="Günün fırsatı"><button type="button" onClick={()=>document.getElementById('home-section-offers')?.scrollIntoView({behavior:prefersReducedMotion()?'auto':'smooth',block:'start'})} className="go-reference-campaign__surface"><span className="go-reference-campaign__eyebrow">Günün fırsatı</span><span className="go-reference-campaign__title">{safeText(interfaceContent.heroTitle,300)}</span><span className="go-reference-campaign__subtitle">{safeText(interfaceContent.heroSubtitle,600)}</span></button></section>:null}

  <section className="mx-auto mt-8 max-w-7xl space-y-9 px-4 sm:px-6">{visibleSections.map(section=><section id={`home-section-${section.id}`} key={section.id} className={`go-reference-product-section go-reference-product-section--${section.id}`} aria-labelledby={`home-section-title-${section.id}`}><div className="go-reference-section-heading"><span className="go-reference-section-heading__icon"><SectionGlyph id={section.id}/></span><h2 id={`home-section-title-${section.id}`}>{section.title}</h2></div>{section.id==='seasonal'?<p className="go-reference-section-copy">Mevsiminde üretilen, sınırlı dönemde sunulan seçkiler.</p>:null}<div className="go-reference-product-rail hide-scrollbar">{section.items.map(product=><CatalogProductCard homeRail key={product.id} product={product} onClick={()=>onProductClick(product)} onAddToCart={onAddToCart} onToggleFavorite={()=>onToggleFavorite(product)} isFavorite={isFavorite(product)} onShare={()=>onShare(product)} onGift={()=>onGift(product)}/>)}</div></section>)}</section>

  <div className="mx-auto mt-8 max-w-7xl px-4 sm:px-6">{renderEvents('after_hero')}{renderEvents('before_products')}</div>

  {!searchQuery?<section className="go-reference-discover mx-auto mt-10 max-w-7xl px-4 sm:px-6"><button type="button" onClick={navigateToCategories} className="go-reference-discover__button">Tüm Ürünleri Keşfet <span aria-hidden="true">→</span></button></section>:null}

  <section id="products" className="go-reference-showcase mx-auto mb-28 mt-10 max-w-7xl px-4 sm:px-6" aria-labelledby="showcase-title"><div className="go-reference-showcase__head"><h2 id="showcase-title">Öne Çıkan Koleksiyon</h2><label className="go-reference-sort"><span className="sr-only">Sırala</span><ArrowDownUp aria-hidden="true"/><select value={sort} onChange={event=>setSort(event.target.value as SortOption)}><option value="featured">Önerilen</option><option value="rating">En yüksek puan</option><option value="price-asc">Fiyat artan</option><option value="price-desc">Fiyat azalan</option></select></label></div>{catalogLoading?<ProductSkeleton/>:showcaseProducts.length?<div className="go-reference-product-rail go-reference-product-rail--showcase hide-scrollbar">{showcaseProducts.map(product=><CatalogProductCard homeRail key={product.id} product={product} onClick={()=>onProductClick(product)} onAddToCart={onAddToCart} onToggleFavorite={()=>onToggleFavorite(product)} isFavorite={isFavorite(product)} onShare={()=>onShare(product)} onGift={()=>onGift(product)}/>)}</div>:<div className="rounded-2xl border border-brand-border bg-brand-card p-5 text-center text-sm text-brand-muted">Canlı katalogda gösterilecek ürün bulunamadı.</div>}</section>
 </div>;
}
function CustomerNotice({children}:{children:React.ReactNode}){return<div role="status" className="mb-4 rounded-2xl border border-amber-300/50 bg-amber-950/30 px-4 py-3 text-sm font-semibold text-amber-100">{children}</div>;}
function ProductSkeleton(){return<div aria-hidden="true" className="go-reference-product-rail">{Array.from({length:3}).map((_,index)=><div key={index} className="go-product-card go-product-card--home-rail"><div className="aspect-[4/3] animate-pulse bg-brand-green/10"/><div className="space-y-3 p-4"><div className="h-3 w-24 animate-pulse rounded bg-brand-border"/><div className="h-6 w-4/5 animate-pulse rounded bg-brand-border"/><div className="h-4 w-3/5 animate-pulse rounded bg-brand-border"/></div></div>)}</div>;}
