import React,{useMemo,useState}from'react';
import{ArrowDownUp,Clock3,Droplets,Filter,Fish,Leaf,Mountain,SlidersHorizontal,Sparkles,Star,Wheat}from'lucide-react';
import CatalogProductCard from'../catalog/CatalogProductCard';
import{useCatalogFilterOptions}from'../catalog/useCatalogFilterOptions';
import{useLiveHomeCatalog,type LegacyHomeProduct}from'../catalog/useLiveHomeCatalog';
import{usePublicStorefrontConfig}from'../storefront/usePublicStorefrontConfig';
import HomeEventsSpotlight from'./HomeEventsSpotlight';

type Props={searchQuery:string;setSearchQuery:(value:string)=>void;onProductClick:(product:LegacyHomeProduct)=>void;onAddToCart:(product:LegacyHomeProduct,quantity:number)=>Promise<void>|void;onToggleFavorite:(product:LegacyHomeProduct)=>Promise<void>|void;favorites:string[];onShare:(product:LegacyHomeProduct)=>Promise<void>|void;onGift:(product:LegacyHomeProduct)=>Promise<void>|void;};
type SortOption='featured'|'rating'|'price-asc'|'price-desc';
function safeText(value:unknown,max=300){return typeof value==='string'?value.trim().slice(0,max):'';}
function safePrice(value:unknown){return typeof value==='number'&&Number.isFinite(value)&&value>=0?value:null;}
function safeRating(value:unknown){return typeof value==='number'&&Number.isFinite(value)&&value>=0&&value<=5?value:null;}
function prefersReducedMotion(){return typeof window!=='undefined'&&window.matchMedia?.('(prefers-reduced-motion: reduce)').matches===true;}
function CategoryGlyph({name}:{name:string}){const value=name.toLocaleLowerCase('tr-TR');if(value.includes('balık')||value.includes('et')||value.includes('yumurta'))return<Fish aria-hidden="true"/>;if(value.includes('süt')||value.includes('şarküteri'))return<Droplets aria-hidden="true"/>;if(value.includes('tahıl')||value.includes('un')||value.includes('buğday'))return<Wheat aria-hidden="true"/>;if(value.includes('dağ')||value.includes('yayla'))return<Mountain aria-hidden="true"/>;return<Leaf aria-hidden="true"/>;}
function SectionGlyph({id}:{id:string}){if(id==='featured')return<Star aria-hidden="true"/>;if(id==='pre_order')return<Clock3 aria-hidden="true"/>;if(id==='seasonal')return<Leaf aria-hidden="true"/>;return<Sparkles aria-hidden="true"/>;}

export default function HomeSection({searchQuery,setSearchQuery,onProductClick,onAddToCart,onToggleFavorite,favorites,onShare,onGift}:Props){
 const{staticContent,heroCategories,homeSections,eventSpotlight,salesReadiness,loading:storefrontLoading,error:storefrontError}=usePublicStorefrontConfig('tr');
 const{products,categories,loading:catalogLoading,error:catalogError}=useLiveHomeCatalog();
 const{categories:filterCategories,origins,loading:filtersLoading,error:filtersError}=useCatalogFilterOptions();
 const[activeCategory,setActiveCategory]=useState<string|null>(null),[activeOrigin,setActiveOrigin]=useState<string|null>(null),[sort,setSort]=useState<SortOption>('featured'),[filtersOpen,setFiltersOpen]=useState(false);
 const interfaceContent=staticContent?.interface??null;
 const categoriesTitle=interfaceContent?safeText(interfaceContent.categoriesTitle,200):'Kategoriler';
 const loading=storefrontLoading||catalogLoading||filtersLoading,hasLoadError=Boolean(storefrontError||catalogError||filtersError),salesPaused=salesReadiness?.status==='blocked_pending_business_identity';

 const quickCategories=useMemo(()=>{const liveById=new Map(categories.filter(category=>category.productCount>0).map(category=>[category.id,category]));const managed=heroCategories.map(config=>liveById.get(config.targetCategory)).filter((category):category is NonNullable<typeof category>=>Boolean(category));const managedIds=new Set(managed.map(category=>category.id));const fallback=categories.filter(category=>category.productCount>0&&!managedIds.has(category.id));return[...managed,...fallback].slice(0,12);},[categories,heroCategories]);
 const categoryPreviewImages=useMemo(()=>{const result=new Map<string,string[]>();for(const category of quickCategories){const images=products.filter(product=>product.categorySlug===category.id&&Boolean(product.image)).map(product=>product.image).filter(Boolean).slice(0,3);result.set(category.id,images);}return result;},[products,quickCategories]);
 const filteredProducts=useMemo(()=>{const query=searchQuery.trim().toLocaleLowerCase('tr-TR');return[...products].filter(product=>{const matchesQuery=!query||[product.name,product.category,product.producerName,product.origin,...product.tags].filter(Boolean).some(value=>String(value).toLocaleLowerCase('tr-TR').includes(query));const matchesCategory=!activeCategory||product.categorySlug===activeCategory;const matchesOrigin=!activeOrigin||safeText(product.origin,240).toLocaleLowerCase('tr-TR').includes(activeOrigin.toLocaleLowerCase('tr-TR'));return matchesQuery&&matchesCategory&&matchesOrigin;}).sort((a,b)=>{if(sort==='price-asc'||sort==='price-desc'){const ap=safePrice(a.price),bp=safePrice(b.price);if(ap===null&&bp===null)return 0;if(ap===null)return 1;if(bp===null)return-1;return sort==='price-asc'?ap-bp:bp-ap;}if(sort==='rating'){const ar=safeRating(a.rating),br=safeRating(b.rating);if(ar===null&&br===null)return 0;if(ar===null)return 1;if(br===null)return-1;return br-ar;}return Number(b.is_featured)-Number(a.is_featured);});},[products,searchQuery,activeCategory,activeOrigin,sort]);
 function sectionProducts(id:string){const source=id==='featured'?products.filter(product=>product.is_featured||product.homeSection==='featured'):id==='pre_order'?products.filter(product=>product.preOrder):id==='seasonal'?products.filter(product=>product.stockMode==='seasonal'||product.homeSection==='seasonal'):products.filter(product=>product.homeSection===id);return Array.from(new Map(source.map(product=>[product.id,product])).values()).slice(0,12);}
 const offerProducts=sectionProducts('offers');
 const showCampaignHero=!searchQuery&&Boolean(interfaceContent)&&offerProducts.length>0;
 function isFavorite(product:LegacyHomeProduct){return favorites.includes(String(product.legacyId||product.id));}
 function chooseCategory(slug:string){setActiveCategory(slug);requestAnimationFrame(()=>document.getElementById('products')?.scrollIntoView({behavior:prefersReducedMotion()?'auto':'smooth',block:'start'}));}
 function clearFilters(){setSearchQuery('');setActiveCategory(null);setActiveOrigin(null);setSort('featured');}
 function renderEvents(placement:'after_hero'|'after_categories'|'before_products'){return!searchQuery&&eventSpotlight?.enabled&&eventSpotlight.placement===placement?<HomeEventsSpotlight settings={eventSpotlight}/>:null;}
 const activeCategoryName=filterCategories.find(item=>item.id===activeCategory)?.name||categories.find(item=>item.id===activeCategory)?.name||'';

 return<div className="go-premium-home go-reference-home" data-video-reference-home="true" data-reference-layout="approved-dark-marketplace">
  <section className="mx-auto max-w-7xl px-4 pt-5 sm:px-6 sm:pt-7" aria-labelledby="home-title">
   <h1 id="home-title" className="sr-only">Golden Oremar ürünleri</h1>
   {loading?<div role="status" aria-live="polite" className="mb-4 rounded-2xl border border-brand-border bg-brand-card px-4 py-3 text-center text-sm font-semibold text-brand-muted">Seçkiler hazırlanıyor…</div>:null}
   {hasLoadError?<CustomerNotice>Mağazanın bir bölümü şu anda yenilenemiyor. Mevcut içerikleri incelemeye devam edebilirsiniz.</CustomerNotice>:null}
   {salesPaused&&salesReadiness?<CustomerNotice>{safeText(salesReadiness.message,500)}</CustomerNotice>:null}

   {!searchQuery&&quickCategories.length?<section className="go-reference-category-section mb-10" aria-labelledby="home-categories-title"><div className="sr-only"><h2 id="home-categories-title">{categoriesTitle}</h2></div><div className="go-reference-category-rail hide-scrollbar" role="list">{quickCategories.map(category=>{const previews=categoryPreviewImages.get(category.id)||[];return<button type="button" role="listitem" key={category.id} onClick={()=>chooseCategory(category.id)} aria-pressed={activeCategory===category.id} className="go-reference-category-card focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><span className="go-reference-category-card__top"><span className="go-reference-category-card__glyph"><CategoryGlyph name={category.name}/></span><span className="go-reference-category-card__previews" aria-hidden="true">{previews.map((image,index)=><span className="go-reference-category-card__preview" key={`${category.id}-${index}`}><img src={image} alt="" loading="lazy" decoding="async"/></span>)}</span></span><span className="go-reference-category-card__title">{category.name}</span><span className="go-reference-category-card__description">{safeText(category.description,220)||`${category.productCount} ürün`}</span></button>;})}</div></section>:null}

   {renderEvents('after_categories')}
  </section>

  {!searchQuery&&!activeCategory?<section className="mx-auto max-w-7xl space-y-11 px-4 sm:px-6">{homeSections.filter(section=>section.active).map(section=>{const items=sectionProducts(section.id);if(!items.length)return null;return<section id={`home-section-${section.id}`} key={section.id} className="go-premium-section go-reference-product-section" aria-labelledby={`home-section-title-${section.id}`}><div className="go-reference-section-heading"><span className="go-reference-section-heading__icon"><SectionGlyph id={section.id}/></span><h2 id={`home-section-title-${section.id}`}>{section.title}</h2><span className="go-reference-section-heading__count">{items.length}</span></div><div className="go-premium-product-rail go-reference-product-rail hide-scrollbar">{items.map(product=><CatalogProductCard key={product.id} product={product} onClick={()=>onProductClick(product)} onAddToCart={onAddToCart} onToggleFavorite={()=>onToggleFavorite(product)} isFavorite={isFavorite(product)} onShare={()=>onShare(product)} onGift={()=>onGift(product)}/>)}</div></section>;})}</section>:null}

  {showCampaignHero&&interfaceContent?<section className="go-reference-campaign mx-auto mt-10 max-w-7xl px-4 sm:px-6" aria-label="Güncel fırsatlar"><button type="button" onClick={()=>document.getElementById('home-section-offers')?.scrollIntoView({behavior:prefersReducedMotion()?'auto':'smooth',block:'start'})} className="go-reference-campaign__surface"><span className="go-reference-campaign__eyebrow"><Sparkles aria-hidden="true"/>Güncel fırsat</span><span className="go-reference-campaign__title">{safeText(interfaceContent.heroTitle,300)}</span><span className="go-reference-campaign__subtitle">{safeText(interfaceContent.heroSubtitle,600)}</span><span className="go-reference-campaign__action">{safeText(interfaceContent.heroButtonText,120)}</span></button></section>:null}

  <div className="mx-auto mt-10 max-w-7xl px-4 sm:px-6">{renderEvents('after_hero')}{renderEvents('before_products')}</div>

  <section id="products" className="go-premium-section go-reference-catalog mx-auto mb-28 mt-12 max-w-7xl scroll-mt-24 px-4 sm:px-6" aria-labelledby="products-title">
   <div className="mb-4 flex items-end justify-between gap-3"><div className="min-w-0"><div className="go-premium-section__eyebrow">Canlı katalog</div><h2 id="products-title" className="mt-1 truncate text-2xl font-black text-brand-text">{searchQuery?`“${searchQuery.trim().slice(0,80)}”`:activeCategoryName||'Tüm Ürünler'}</h2><p className="mt-1 text-xs font-semibold text-brand-muted">{filteredProducts.length} ürün listeleniyor</p></div><button type="button" onClick={()=>setFiltersOpen(value=>!value)} aria-expanded={filtersOpen} aria-controls="home-filters" className="inline-flex min-h-11 shrink-0 items-center rounded-full border border-brand-border bg-brand-card px-4 text-sm font-bold"><Filter aria-hidden="true" className="mr-2 h-4 w-4"/>{filtersOpen?'Kapat':'Filtrele'}</button></div>
   <div className="mb-4 flex items-center gap-2 overflow-x-auto pb-1 hide-scrollbar"><button type="button" onClick={()=>setActiveCategory(null)} aria-pressed={!activeCategory} className={`min-h-10 shrink-0 rounded-full border px-3.5 text-xs font-black ${!activeCategory?'border-brand-gold bg-brand-gold text-brand-on-gold':'border-brand-border bg-brand-card text-brand-text'}`}>Tüm Ürünler <span className="ml-1 opacity-80">{products.length}</span></button>{quickCategories.slice(0,8).map(category=><button type="button" key={`filter-${category.id}`} onClick={()=>setActiveCategory(category.id)} aria-pressed={activeCategory===category.id} className={`min-h-10 shrink-0 rounded-full border px-3.5 text-xs font-black ${activeCategory===category.id?'border-brand-gold bg-brand-gold text-brand-on-gold':'border-brand-border bg-brand-card text-brand-text'}`}>{category.name}</button>)}</div>
   <div className="go-filter-panel mb-4 flex flex-wrap items-center justify-between gap-3 p-3"><span className="text-sm font-bold text-brand-muted">{activeOrigin?`Üretim yeri: ${activeOrigin}`:'Önerilen sıralama ve canlı stok'}</span><label className="relative inline-flex min-h-11 items-center rounded-xl border border-brand-border bg-brand-card px-3 text-sm font-bold"><ArrowDownUp aria-hidden="true" className="mr-2 h-4 w-4 text-brand-gold"/><span className="sr-only">Sıralama</span><select value={sort} onChange={event=>setSort(event.target.value as SortOption)} className="min-h-10 bg-transparent pr-2 outline-none"><option value="featured">Önerilen</option><option value="rating">En yüksek puan</option><option value="price-asc">Fiyat artan</option><option value="price-desc">Fiyat azalan</option></select></label></div>
   {filtersOpen?<div id="home-filters" className="go-filter-panel mb-5 p-4"><div className="mb-3 flex items-center gap-2 font-black"><SlidersHorizontal aria-hidden="true" className="h-4 w-4 text-brand-gold"/>Seçiminizi daraltın</div><div className="grid gap-3 md:grid-cols-2"><label className="text-sm font-semibold">Üretim yeri<select value={activeOrigin||''} onChange={event=>setActiveOrigin(event.target.value||null)} className="mt-1 min-h-11 w-full rounded-xl border border-brand-border bg-transparent px-3"><option value="">Tüm bölgeler</option>{origins.map(origin=><option key={origin} value={origin}>{origin}</option>)}</select></label><label className="text-sm font-semibold">Kategori<select value={activeCategory||''} onChange={event=>setActiveCategory(event.target.value||null)} className="mt-1 min-h-11 w-full rounded-xl border border-brand-border bg-transparent px-3"><option value="">Tüm kategoriler</option>{filterCategories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label></div><div className="mt-3 flex justify-end border-t border-brand-border pt-3"><button type="button" onClick={clearFilters} className="min-h-11 rounded-full border border-brand-border px-4 text-sm font-black">Filtreleri temizle</button></div></div>:null}
   {catalogLoading?<ProductSkeleton/>:filteredProducts.length?<div className="go-reference-catalog-grid">{filteredProducts.map(product=><CatalogProductCard key={product.id} product={product} onClick={()=>onProductClick(product)} onAddToCart={onAddToCart} onToggleFavorite={()=>onToggleFavorite(product)} isFavorite={isFavorite(product)} onShare={()=>onShare(product)} onGift={()=>onGift(product)}/>)}</div>:<div className="rounded-3xl border border-dashed border-brand-border bg-brand-card p-7 text-center"><Sparkles aria-hidden="true" className="mx-auto h-7 w-7 text-brand-gold"/><h3 className="mt-3 text-lg font-black">Aradığınız ürün şu anda görünmüyor</h3><p className="mt-1 text-sm text-brand-muted">Filtreleri temizleyerek tüm canlı kataloğa dönebilirsiniz.</p><button type="button" onClick={clearFilters} className="mt-4 min-h-11 rounded-full bg-brand-gold px-5 font-black text-brand-on-gold">Tüm ürünleri göster</button></div>}
  </section>
 </div>;
}
function CustomerNotice({children}:{children:React.ReactNode}){return<div role="status" className="mb-4 rounded-2xl border border-amber-300/50 bg-amber-950/30 px-4 py-3 text-sm font-semibold text-amber-100">{children}</div>;}
function ProductSkeleton(){return<div aria-hidden="true" className="go-reference-catalog-grid">{Array.from({length:6}).map((_,index)=><div key={index} className="overflow-hidden rounded-3xl border border-brand-border bg-brand-card"><div className="aspect-square animate-pulse bg-brand-green/10"/><div className="space-y-3 p-4"><div className="h-3 w-24 animate-pulse rounded bg-brand-border"/><div className="h-6 w-4/5 animate-pulse rounded bg-brand-border"/><div className="h-4 w-3/5 animate-pulse rounded bg-brand-border"/><div className="h-9 w-32 animate-pulse rounded bg-brand-border"/></div></div>)}</div>;}
