import React,{useEffect,useMemo,useState}from'react';
import{Ban,Flag,ShieldCheck,X}from'lucide-react';
import{supabase}from'../../lib/supabase';
import{getProductDetail,listProductReviews}from'../catalog/api';
import{listMyConversations,type ConversationSummary}from'../account/messagesApi';
import{acceptCurrentTerms,getConversationSafetyContext,getMyTermsAcceptance,reportConversation,reportPublishedReview,setConversationUserBlock,type ConversationSafety,type ReportReason,type TermsAcceptance}from'./storeComplianceApi';

const reasonLabels:Record<ReportReason,string>={harassment:'Taciz veya zorbalık',hate:'Nefret söylemi',sexual:'Uygunsuz cinsel içerik',violence:'Şiddet veya tehdit',spam:'Spam',fraud:'Dolandırıcılık',privacy:'Kişisel veri / gizlilik ihlali',illegal:'Yasa dışı içerik',other:'Diğer'};
function productReferenceFromUrl(){try{const url=new URL(window.location.href);const tab=url.searchParams.get('tab');if(tab==='product-detail')return(url.searchParams.get('product')||url.searchParams.get('id')||'').trim();const parts=url.pathname.split('/').filter(Boolean);if(parts[0]==='products'&&parts[1])return decodeURIComponent(parts[1]).trim();return'';}catch{return'';}}
function safeText(value:unknown,max=300){return typeof value==='string'?value.trim().slice(0,max):'';}

export default function StoreComplianceControls(){
 const[userId,setUserId]=useState('');const[open,setOpen]=useState(false);const[terms,setTerms]=useState<TermsAcceptance|null>(null);const[termsChecked,setTermsChecked]=useState(false);const[conversations,setConversations]=useState<ConversationSummary[]>([]);const[safety,setSafety]=useState<Record<string,ConversationSafety>>({});const[reviews,setReviews]=useState<any[]>([]);const[reason,setReason]=useState<ReportReason>('other');const[details,setDetails]=useState('');const[busy,setBusy]=useState('');const[error,setError]=useState('');const[status,setStatus]=useState('');const[routeKey,setRouteKey]=useState(()=>window.location.href);
 useEffect(()=>{let active=true;supabase.auth.getUser().then(({data})=>{if(active)setUserId(data.user?.id||'');}).catch(()=>{if(active)setUserId('');});const{data:listener}=supabase.auth.onAuthStateChange((_event,session)=>setUserId(session?.user?.id||''));const route=()=>setRouteKey(window.location.href);window.addEventListener('popstate',route);window.addEventListener('hashchange',route);return()=>{active=false;listener.subscription.unsubscribe();window.removeEventListener('popstate',route);window.removeEventListener('hashchange',route);};},[]);
 useEffect(()=>{setTerms(null);setTermsChecked(false);setConversations([]);setSafety({});setReviews([]);setError('');setStatus('');if(!userId)return;getMyTermsAcceptance().then(setTerms).catch(e=>setError(e instanceof Error?e.message:'Kullanım şartları durumu alınamadı.'));},[userId]);
 const productReference=useMemo(()=>{void routeKey;return productReferenceFromUrl();},[routeKey]);
 async function loadPanel(){setOpen(true);if(!userId)return;setError('');try{setBusy('load');const jobs:[Promise<any>,Promise<any>|null]=[listMyConversations(20,0),productReference?getProductDetail(productReference):null];const[conversationRows,product]=await Promise.all([jobs[0],jobs[1]??Promise.resolve(null)]);setConversations(conversationRows);if(product?.id){const data=await listProductReviews(product.id,20,0);setReviews(Array.isArray(data?.items)?data.items:[]);}else setReviews([]);}catch(e){setError(e instanceof Error?e.message:'Güvenlik merkezi yüklenemedi.');}finally{setBusy('');}}
 async function acceptTerms(){if(!termsChecked)return;try{setBusy('terms');setError('');const value=await acceptCurrentTerms();setTerms(value);setTermsChecked(false);setStatus('Kullanım Şartları kabulü kaydedildi. Yorum ve mesaj özellikleri açıldı.');}catch(e){setError(e instanceof Error?e.message:'Kullanım Şartları kabulü kaydedilemedi.');}finally{setBusy('');}}
 async function ensureSafety(id:string){if(safety[id])return safety[id];const value=await getConversationSafetyContext(id);setSafety(current=>({...current,[id]:value}));return value;}
 async function toggleBlock(conversation:ConversationSummary){try{setBusy(`block:${conversation.id}`);setError('');const current=await ensureSafety(conversation.id);if(!current.canBlock)throw new Error('Bu konuşmada engellenebilir bir müşteri/üretici bulunmuyor.');const next=await setConversationUserBlock(conversation.id,!current.blockedByMe);setSafety(state=>({...state,[conversation.id]:next}));setStatus(next.blockedByMe?`${next.counterpartName||'Kullanıcı'} engellendi. Yeni mesajlaşma durduruldu.`:`${next.counterpartName||'Kullanıcı'} için engel kaldırıldı.`);}catch(e){setError(e instanceof Error?e.message:'Engelleme işlemi tamamlanamadı.');}finally{setBusy('');}}
 async function reportChat(conversation:ConversationSummary){if(!window.confirm(`“${conversation.title}” konuşmasını moderasyon ekibine bildirmek istiyor musunuz?`))return;try{setBusy(`report:${conversation.id}`);setError('');await reportConversation(conversation.id,reason,details);setStatus('Konuşma bildirimi moderasyon kuyruğuna gönderildi.');}catch(e){setError(e instanceof Error?e.message:'Konuşma bildirilemedi.');}finally{setBusy('');}}
 async function reportReview(review:any){const id=safeText(review?.id,160);if(!id)return;if(!window.confirm('Bu müşteri yorumunu moderasyon ekibine bildirmek istiyor musunuz?'))return;try{setBusy(`review:${id}`);setError('');await reportPublishedReview(id,reason,details);setStatus('Yorum bildirimi moderasyon kuyruğuna gönderildi.');}catch(e){setError(e instanceof Error?e.message:'Yorum bildirilemedi.');}finally{setBusy('');}}
 if(!userId)return null;
 const accepted=terms?.accepted===true;
 return<>
  <button type="button" onClick={()=>void loadPanel()} className="fixed bottom-20 right-4 z-[70] min-h-11 rounded-full border border-brand-green bg-white px-4 text-sm font-bold text-brand-green shadow-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold dark:bg-gray-950 dark:text-brand-gold" aria-label="Güvenlik ve içerik bildirme merkezini aç"><ShieldCheck aria-hidden="true" className="mr-2 inline h-4 w-4"/>{accepted?'Güvenlik':'Şartlar & Güvenlik'}</button>
  {open?<div className="fixed inset-0 z-[90] flex items-end justify-center bg-black/50 p-3 sm:items-center" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false);}}><section role="dialog" aria-modal="true" aria-labelledby="store-safety-title" className="max-h-[88vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-5 shadow-2xl dark:bg-gray-950 sm:p-6">
    <div className="flex items-start justify-between gap-3"><div><h2 id="store-safety-title" className="text-xl font-bold">Güvenlik ve İçerik Merkezi</h2><p className="mt-1 text-sm text-gray-500">Kullanım Şartları, içerik bildirme ve kullanıcı engelleme işlemleri.</p></div><button type="button" onClick={()=>setOpen(false)} aria-label="Güvenlik merkezini kapat" className="min-h-11 rounded-xl border px-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><X aria-hidden="true" className="h-4 w-4"/></button></div>
    {error?<div role="alert" className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200">{error}</div>:null}{status?<div role="status" aria-live="polite" className="mt-4 rounded-xl border border-green-200 bg-green-50 p-3 text-sm text-green-800 dark:border-green-900/60 dark:bg-green-950/30 dark:text-green-200">{status}</div>:null}
    {!accepted?<section className="mt-5 rounded-2xl border border-amber-300 bg-amber-50 p-4 text-amber-950 dark:border-amber-800 dark:bg-amber-950/30 dark:text-amber-100"><h3 className="font-bold">Yorum ve mesaj özellikleri için Kullanım Şartları</h3><p className="mt-2 text-sm leading-6">Kullanıcı tarafından oluşturulan içeriklerde taciz, nefret, cinsel istismar, şiddet tehdidi, dolandırıcılık, spam, kişisel veri ihlali ve yasa dışı içerik yasaktır. İçerikler bildirilebilir ve kullanıcılar engellenebilir.</p><p className="mt-2 text-sm"><a href="/kullanim-sartlari" className="font-bold underline">Kullanım Şartları</a> · <a href="/gizlilik-politikasi" className="font-bold underline">Gizlilik Politikası</a></p><label className="mt-3 flex items-start gap-2 text-sm"><input type="checkbox" checked={termsChecked} onChange={event=>setTermsChecked(event.target.checked)} className="mt-1 h-4 w-4"/><span>Kullanım Şartlarını okudum ve kullanıcı içeriği kurallarını kabul ediyorum.</span></label><button type="button" onClick={()=>void acceptTerms()} disabled={!termsChecked||busy==='terms'} className="mt-3 min-h-11 rounded-xl bg-brand-green px-4 font-bold text-white disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">{busy==='terms'?'Kaydediliyor…':'Kabul et ve devam et'}</button></section>:<div className="mt-4 rounded-xl bg-green-50 p-3 text-sm text-green-800 dark:bg-green-950/30 dark:text-green-200">Kullanım Şartları sürümü {terms?.termsVersion} kabul edildi.</div>}
    <section className="mt-5"><h3 className="font-bold">Bildirim nedeni</h3><div className="mt-2 grid gap-2 sm:grid-cols-2"><select value={reason} onChange={event=>setReason(event.target.value as ReportReason)} className="min-h-11 rounded-xl border bg-transparent px-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">{Object.entries(reasonLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><input value={details} onChange={event=>setDetails(event.target.value.slice(0,1000))} maxLength={1000} aria-label="Bildirim açıklaması" className="min-h-11 rounded-xl border bg-transparent px-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold" placeholder="İsterseniz kısa açıklama ekleyin"/></div></section>
    {productReference?<section className="mt-6"><h3 className="font-bold">Bu üründeki yayınlanmış yorumlar</h3>{reviews.length?<div className="mt-3 space-y-2">{reviews.map((review,index)=>{const id=safeText(review?.id,160);return<article key={id||String(index)} className="rounded-xl border p-3"><div className="flex items-start justify-between gap-3"><div><strong>{safeText(review?.reviewerName,160)||'Müşteri'}</strong><p className="mt-1 line-clamp-2 text-sm text-gray-600 dark:text-gray-300">{safeText(review?.body,500)||'Yorum metni doğrulanamadı.'}</p></div><button type="button" disabled={!id||busy===`review:${id}`} onClick={()=>void reportReview(review)} className="min-h-11 shrink-0 rounded-xl border px-3 text-sm font-bold disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><Flag aria-hidden="true" className="mr-1 inline h-4 w-4"/>Bildir</button></div></article>;})}</div>:<p className="mt-2 text-sm text-gray-500">Bu ekranda bildirilebilir yayınlanmış yorum bulunmuyor.</p>}</section>:null}
    <section className="mt-6"><h3 className="font-bold">Mesajlaşma güvenliği</h3>{busy==='load'&&!conversations.length?<p role="status" className="mt-2 text-sm text-gray-500">Konuşmalar yükleniyor…</p>:conversations.length?<div className="mt-3 space-y-2">{conversations.map(conversation=>{const context=safety[conversation.id];return<article key={conversation.id} className="rounded-xl border p-3"><div className="font-semibold">{conversation.title}</div><p className="mt-1 line-clamp-1 text-sm text-gray-500">{conversation.lastMessage||'Mesaj özeti yok'}</p>{context?<p className="mt-2 text-xs text-gray-500">{context.counterpartName?`Karşı taraf: ${context.counterpartName}`:'Bu konuşmada engellenebilir bir kullanıcı yok.'}{context.blocksMe?' · Karşı taraf sizi engellemiş.':''}</p>:null}<div className="mt-2 flex flex-wrap gap-2"><button type="button" onClick={()=>void reportChat(conversation)} disabled={busy===`report:${conversation.id}`} className="min-h-11 rounded-xl border px-3 text-sm font-bold disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><Flag aria-hidden="true" className="mr-1 inline h-4 w-4"/>Konuşmayı bildir</button><button type="button" onClick={()=>void toggleBlock(conversation)} disabled={busy===`block:${conversation.id}`} className="min-h-11 rounded-xl border px-3 text-sm font-bold disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><Ban aria-hidden="true" className="mr-1 inline h-4 w-4"/>{context?.blockedByMe?'Engeli kaldır':'Kullanıcıyı engelle'}</button></div></article>;})}</div>:<p className="mt-2 text-sm text-gray-500">Henüz güvenlik işlemi yapılabilecek konuşma yok.</p>}</section>
  </section></div>:null}
 </>;
}
