import{supabase}from'../../lib/supabase';

export type StoreBrandingKind='logo'|'cover';
export type StoreBrandingSnapshot={producerId:string;displayName:string;storeKind:string;status:string;verified:boolean;logoPath:string;coverPath:string;canEdit:boolean;logoBinaryVerified:boolean;coverBinaryVerified:boolean};
export type StoreBrandingDimensions={width:number;height:number};
export type StoreBrandingValidation={dimensions:StoreBrandingDimensions;sizeBytes:number;mime:string};

export const STORE_BRANDING_SPECS={
 logo:{recommendedWidth:1024,recommendedHeight:1024,minWidth:512,minHeight:512,maxWidth:4096,maxHeight:4096,ratio:1,maxBytes:5*1024*1024,label:'Logo'},
 cover:{recommendedWidth:1500,recommendedHeight:600,minWidth:1200,minHeight:480,maxWidth:6000,maxHeight:2400,ratio:2.5,maxBytes:5*1024*1024,label:'Kapak'},
}as const;

const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const TYPES=new Set(['image/jpeg','image/png','image/webp']);
function record(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function text(value:unknown,label:string,max=300,optional=false){if(value==null&&optional)return'';if(typeof value!=='string')throw new Error(`${label} doğrulanamadı.`);const normalized=value.trim();if((!optional&&!normalized)||normalized.length>max||/[\u0000-\u001F\u007F]/.test(normalized))throw new Error(`${label} doğrulanamadı.`);return normalized;}
function bool(value:unknown,label:string){if(typeof value!=='boolean')throw new Error(`${label} doğrulanamadı.`);return value;}
function storagePath(value:unknown,label:string){const normalized=text(value,label,1200,true);if(!normalized)return'';if(normalized.startsWith('/')||/^[a-z][a-z0-9+.-]*:/i.test(normalized)||normalized.split('/').some(part=>!part||part==='.'||part==='..'))throw new Error(`${label} doğrulanamadı.`);return normalized;}
function normalizeSnapshot(value:unknown):StoreBrandingSnapshot{if(!record(value))throw new Error('Mağaza görsel paketi doğrulanamadı.');const producerId=text(value.producerId,'Mağaza kimliği',80);if(!UUID_RE.test(producerId))throw new Error('Mağaza kimliği doğrulanamadı.');return{producerId,displayName:text(value.displayName,'Mağaza adı',240),storeKind:text(value.storeKind,'Mağaza tipi',40),status:text(value.status,'Mağaza durumu',40),verified:bool(value.verified,'Mağaza doğrulaması'),logoPath:storagePath(value.logoPath,'Logo yolu'),coverPath:storagePath(value.coverPath,'Kapak yolu'),canEdit:bool(value.canEdit,'Görsel düzenleme yetkisi'),logoBinaryVerified:bool(value.logoBinaryVerified,'Logo binary doğrulaması'),coverBinaryVerified:bool(value.coverBinaryVerified,'Kapak binary doğrulaması')};}
function normalizeId(value:string){const normalized=String(value||'').trim().toLowerCase();if(!UUID_RE.test(normalized))throw new Error('Mağaza kimliği doğrulanamadı.');return normalized;}
function extension(mime:string){if(mime==='image/jpeg')return'jpg';if(mime==='image/png')return'png';if(mime==='image/webp')return'webp';throw new Error('Logo ve kapak yalnız JPEG, PNG veya WebP olabilir.');}
function profilePathOwnedBy(producerId:string,path:string){return new RegExp(`^${producerId}/profile/(logo|cover)-[0-9a-f-]{36}[.](jpg|jpeg|png|webp)$`,'i').test(path);}

export function storeBrandingAssetUrl(path:string){const normalized=storagePath(path,'Mağaza görseli');return normalized?supabase.storage.from('catalog-public').getPublicUrl(normalized).data.publicUrl:'';}

export async function getStoreBranding(producerId:string){const id=normalizeId(producerId);const{data,error}=await supabase.rpc('get_store_branding_editor_v1',{p_producer_id:id});if(error)throw error;return normalizeSnapshot(data);}

async function browserImageDimensions(file:File):Promise<StoreBrandingDimensions>{if(typeof createImageBitmap==='function'){const bitmap=await createImageBitmap(file);try{return{width:bitmap.width,height:bitmap.height};}finally{bitmap.close();}}const url=URL.createObjectURL(file);try{return await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve({width:image.naturalWidth,height:image.naturalHeight});image.onerror=()=>reject(new Error('Görsel ölçüleri okunamadı.'));image.src=url;});}finally{URL.revokeObjectURL(url);}}

export async function validateStoreBrandingFile(file:File,kind:StoreBrandingKind):Promise<StoreBrandingValidation>{if(!(file instanceof File))throw new Error('Görsel dosyası seçilmedi.');if(!TYPES.has(file.type))throw new Error('Logo ve kapak yalnız JPEG, PNG veya WebP olabilir.');const spec=STORE_BRANDING_SPECS[kind];if(file.size<1||file.size>spec.maxBytes)throw new Error('Logo ve kapak görselleri en fazla 5 MB olabilir.');let dimensions:StoreBrandingDimensions;try{dimensions=await browserImageDimensions(file);}catch{throw new Error('Görselin piksel ölçüleri okunamadı. JPEG, PNG veya WebP dosyası kullanın.');}const{width,height}=dimensions;if(!Number.isSafeInteger(width)||!Number.isSafeInteger(height)||width<1||height<1)throw new Error('Görsel ölçüleri doğrulanamadı.');if(kind==='logo'){if(width!==height||width<spec.minWidth||height<spec.minHeight||width>spec.maxWidth||height>spec.maxHeight)throw new Error(`Logo 1:1 kare olmalı; minimum ${spec.minWidth} × ${spec.minHeight} px, önerilen ${spec.recommendedWidth} × ${spec.recommendedHeight} px.`);}else{const ratio=width/height;if(width<spec.minWidth||height<spec.minHeight||width>spec.maxWidth||height>spec.maxHeight||Math.abs(ratio-spec.ratio)>0.025)throw new Error(`Kapak 5:2 oranında olmalı; minimum ${spec.minWidth} × ${spec.minHeight} px, önerilen ${spec.recommendedWidth} × ${spec.recommendedHeight} px.`);}return{dimensions,sizeBytes:file.size,mime:file.type};}

async function edgeErrorMessage(error:unknown,data:unknown){let code='';if(record(data)&&typeof data.error==='string')code=data.error;const context=(error as {context?:unknown}|null)?.context;if(!code&&typeof Response!=='undefined'&&context instanceof Response){try{const payload=await context.clone().json();if(record(payload)&&typeof payload.error==='string')code=payload.error;}catch{/* response body is optional */}}return storeBrandingError(code||String((error as {message?:unknown}|null)?.message||''));}

export async function uploadAndBindStoreBrandAsset(producerId:string,kind:StoreBrandingKind,file:File){const id=normalizeId(producerId),local=await validateStoreBrandingFile(file,kind),path=`${id}/profile/${kind}-${crypto.randomUUID()}.${extension(file.type)}`;let uploaded=false;try{const{error:uploadError}=await supabase.storage.from('catalog-public').upload(path,file,{contentType:file.type,cacheControl:'31536000',upsert:false});if(uploadError)throw uploadError;uploaded=true;const{data:verified,error:verifyError}=await supabase.functions.invoke('catalog-media-verify',{body:{path}});if(verifyError||!record(verified)||verified.ok!==true){throw new Error(await edgeErrorMessage(verifyError,verified));}if(verified.assetKind!==kind||verified.width!==local.dimensions.width||verified.height!==local.dimensions.height)throw new Error('Sunucu ile cihazdaki görsel ölçüsü doğrulaması eşleşmedi.');const{data:bound,error:bindError}=await supabase.rpc('set_store_branding_asset_v1',{p_producer_id:id,p_kind:kind,p_path:path});if(bindError)throw bindError;if(!record(bound)||bound.ok!==true||bound.path!==path)throw new Error('Mağaza görseli sunucuya bağlanamadı.');uploaded=false;const previousPath=storagePath(bound.previousPath,'Önceki mağaza görseli');if(previousPath&&previousPath!==path&&profilePathOwnedBy(id,previousPath)){await supabase.storage.from('catalog-public').remove([previousPath]).catch(()=>undefined);}return await getStoreBranding(id);}catch(error){if(uploaded)await supabase.storage.from('catalog-public').remove([path]).catch(()=>undefined);if(error instanceof Error&&error.message)throw error;throw new Error(storeBrandingError(error));}}

export function storeBrandingError(error:unknown){const message=String((error as {message?:unknown}|null)?.message??error??'').trim();const map:Array<[string,string]>=[['store_branding_size_invalid','Logo ve kapak görselleri en fazla 5 MB olabilir.'],['store_branding_type_invalid','Logo ve kapak yalnız JPEG, PNG veya WebP olabilir.'],['store_branding_logo_dimensions_invalid','Logo 1:1 kare ve minimum 512 × 512 px olmalıdır. Önerilen ölçü 1024 × 1024 px.'],['store_branding_cover_dimensions_invalid','Kapak 5:2 oranında ve minimum 1200 × 480 px olmalıdır. Önerilen ölçü 1500 × 600 px.'],['store_branding_dimensions_unreadable','Görselin piksel ölçüleri sunucuda doğrulanamadı.'],['store_branding_owner_required','Bu mağazanın görsellerini değiştirme yetkiniz yok.'],['store_branding_access_required','Bu mağazanın marka yönetimine erişim yetkiniz yok.'],['store_branding_edit_required','Bu mağazanın logo veya kapak görselini değiştirme yetkiniz yok.'],['store_branding_asset_not_verified','Görsel gerçek dosya ve Storage bütünlüğü doğrulamasından geçmedi.'],['permission_required:product.publish','Golden Oremar Resmi Mağazası görsellerini yalnız yetkili Super Admin değiştirebilir.']];for(const[key,value]of map)if(message.includes(key))return value;return message&&message.length<=300?message:'Mağaza görseli işlemi tamamlanamadı.';}
