import{userFacingError}from'../../lib/userFacingError';
import React,{useEffect,useMemo,useState}from'react';
import{ChevronDown,Search,X}from'lucide-react';
import{listPublicFaq,type PublicFaqItem}from'./faqApi';
import{NETWORK_RESTORED_EVENT}from'../resilience/useConnectivity';

function searchLocale(value:string){const normalized=String(value||'tr').trim().replace('_','-');return/^[A-Za-z]{2,3}(?:-[A-Za-z0-9]{2,8})?$/.test(normalized)?normalized:'tr';}

export default function FaqPanel({locale='tr'}:{locale?:string}){
 const[data,setData]=useState<{locale:string;fallbackUsed:boolean;items:PublicFaqItem[]}|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[query,setQuery]=useState('');const[category,setCategory]=useState('Tümü');
 async function load(silent=false){try{if(!silent)setLoading(true);setError('');const result=await listPublicFaq(locale);setData({locale:result.locale,fallbackUsed:result.fallbackUsed,items:result.items});}catch(e:any){setError(userFacingError(e,'Sık sorulan sorular yüklenemedi.'));if(!silent)setData(null);}finally{if(!silent)setLoading(false);}}
 useEffect(()=>{void load();},[locale]);
 useEffect(()=>{const restore=()=>void load(true);window.addEventListener(NETWORK_RESTORED_EVENT,restore);return()=>window.removeEventListener(NETWORK_RESTORED_EVENT,restore);},[locale]);
 const categories=useMemo(()=>['Tümü',...Array.from(new Set((data?.items||[]).map(item=>item.category).filter(Boolean)))],[data]);
 useEffect(()=>{if(!categories.includes(category))setCategory('Tümü');},[categories,category]);
 const filtered=useMemo(()=>{const activeLocale=searchLocale(data?.locale||locale);const q=query.trim().toLocaleLowerCase(activeLocale);return(data?.items||[]).filter(item=>(category==='Tümü'||item.category===category)&&(!q||`${item.question} ${item.answer} ${(item.tags||[]).join(' ')}`.toLocaleLowerCase(activeLocale).includes(q)));},[data,query,category,locale]);
 const focus='focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold';
 return<section aria-label="Sık sorulan sorular" className="space-y-3">
  {data?.fallbackUsed?<p role="status" className="rounded-xl bg-amber-50 p-3 text-xs text-amber-900 dark:bg-amber-950/30 dark:text-amber-100">Bu dilde yayınlanmış soru yok; Türkçe içerik gösteriliyor.</p>:null}
  {loading?<div role="status" aria-live="polite" className="space-y-2" aria-label="Sorular yükleniyor">{[0,1,2,3].map(index=><div key={index} className="h-14 animate-pulse rounded-2xl bg-brand-card ring-1 ring-brand-border"/>)}</div>:null}
  {error?<div><div role="alert" className="rounded-2xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950 dark:border-amber-900/60 dark:bg-amber-950/30 dark:text-amber-100">{error}</div><button type="button" onClick={()=>void load()} className={`mt-3 min-h-11 rounded-xl border-2 border-brand-border bg-brand-card px-4 font-bold ${focus}`}>Tekrar dene</button></div>:null}
  {!loading&&data?<>
   <label className="block" htmlFor="faq-search"><span className="sr-only">Sorularda ara</span><div className="relative"><Search aria-hidden="true" className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-brand-muted"/><input id="faq-search" type="search" value={query} maxLength={120} onChange={event=>setQuery(event.target.value.slice(0,120))} placeholder="Soru ara: iade, kargo, ödeme…" className="min-h-12 w-full rounded-2xl border-2 border-brand-border bg-brand-card pl-11 pr-12 text-brand-text placeholder:text-brand-muted focus:border-brand-gold focus:outline-none"/>{query?<button type="button" onClick={()=>setQuery('')} aria-label="Aramayı temizle" className={`absolute right-1 top-1/2 grid min-h-11 min-w-11 -translate-y-1/2 place-items-center rounded-xl ${focus}`}><X aria-hidden="true" className="h-4 w-4"/></button>:null}</div></label>
   <div className="-mx-1 flex gap-2 overflow-x-auto px-1 pb-1" role="group" aria-label="Soru kategorileri">{categories.map(item=><button key={item} type="button" aria-pressed={category===item} onClick={()=>setCategory(item)} className={`min-h-10 shrink-0 rounded-full border-2 px-4 text-sm font-bold transition-colors ${focus} ${category===item?'border-brand-green bg-brand-green text-brand-on-green':'border-brand-border bg-brand-card text-brand-text hover:border-brand-gold/40'}`}>{item}</button>)}</div>
   <p role="status" aria-live="polite" className="px-1 text-xs font-semibold text-brand-muted">{filtered.length} soru</p>
   {filtered.length?<div className="overflow-hidden rounded-2xl border-2 border-brand-border bg-brand-card">{filtered.map((item,index)=><details key={item.id} className={`group ${index?'border-t border-brand-border':''}`}><summary className={`flex min-h-14 cursor-pointer list-none items-center gap-3 px-4 py-3 text-left font-bold text-brand-text transition-colors hover:bg-brand-gold/5 [&::-webkit-details-marker]:hidden ${focus}`}><span className="min-w-0 flex-1">{item.question}</span><ChevronDown aria-hidden="true" className="h-5 w-5 shrink-0 text-brand-muted transition-transform duration-200 group-open:rotate-180"/></summary><div className="px-4 pb-4"><p className="whitespace-pre-wrap break-words text-sm leading-6 text-brand-text/85">{item.answer}</p><span className="mt-3 inline-block rounded-full bg-brand-green/10 px-2.5 py-1 text-xs font-semibold text-brand-green dark:text-brand-gold">{item.category}</span></div></details>)}</div>:<div role="status" aria-live="polite" className="rounded-2xl border-2 border-dashed border-brand-border p-4 text-sm text-brand-muted">Aramanızla eşleşen soru bulunamadı.{query||category!=='Tümü'?<button type="button" onClick={()=>{setQuery('');setCategory('Tümü');}} className={`mt-3 block min-h-11 rounded-xl border-2 border-brand-border bg-brand-card px-4 font-bold text-brand-text ${focus}`}>Filtreleri temizle</button>:null}</div>}
  </>:null}
 </section>;
}
