import React,{useEffect,useState}from'react';
import{BadgeCheck,CheckCircle2,Heart,RefreshCw}from'lucide-react';
import{catalogPublicUrl}from'./api';
import{listFavoriteProducts,removeFavoriteProduct,type FavoriteProductItem}from'./favoriteProductsApi';
import{productHandlingLabel,type ProductHandlingType}from'../catalog/productHandlingApi';
import{EmptyState,ErrorState,Money,Panel}from'./ui';

function handlingChip(type:ProductHandlingType|null){if(type==='fish')return'bg-sky-100 text-sky-800 dark:bg-sky-950/40 dark:text-sky-200';if(type==='red_meat')return'bg-rose-100 text-rose-800 dark:bg-rose-950/40 dark:text-rose-200';if(type==='poultry')return'bg-amber-100 text-amber-900 dark:bg-amber-950/40 dark:text-amber-200';if(type==='egg')return'bg-yellow-100 text-yellow-900 dark:bg-yellow-950/40 dark:text-yellow-200';if(type==='dairy')return'bg-cyan-100 text-cyan-900 dark:bg-cyan-950/40 dark:text-cyan-200';if(type==='produce')return'bg-emerald-100 text-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-200';if(type==='beverage')return'bg-indigo-100 text-indigo-900 dark:bg-indigo-950/40 dark:text-indigo-200';if(type==='non_food')return'bg-slate-100 text-slate-800 dark:bg-slate-800 dark:text-slate-200';return'bg-stone-100 text-stone-800 dark:bg-stone-800 dark:text-stone-200';}

export default function FavoritesPanel({onOpenProduct}:{onOpenProduct?:(slug:string)=>void}){
 const[items,setItems]=useState<FavoriteProductItem[]|null>(null);const[error,setError]=useState('');const[status,setStatus]=useState('');const[loading,setLoading]=useState(true);const[busyId,setBusyId]=useState<string|null>(null);
 async function load(silent=false){try{if(!silent)setLoading(true);setError('');setItems(await listFavoriteProducts());}catch(e:unknown){setError(e instanceof Error&&e.message?e.message:'Favoriler yüklenemedi.');}finally{if(!silent)setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function remove(item:FavoriteProductItem){if(busyId)return;try{setBusyId(item.productId);setError('');setStatus('');await removeFavoriteProduct(item.slug);setItems(current=>current?current.filter(row=>row.productId!==item.productId):current);setStatus(`✓ ${item.name} favorilerinizden çıkarıldı.`);}catch(e:unknown){setError(e instanceof Error&&e.message?e.message:'Ürün favorilerden çıkarılamadı.');}finally{setBusyId(null);}}
 if(loading)return<Panel title="Favorilerim" description="Beğendiğiniz ürünleri, üretici bilgileri ve güncel satış durumlarıyla tek yerde inceleyin."><div className="flex min-h-60 flex-col items-center justify-center gap-4 py-10"><div className="grid h-24 w-24 place-items-center rounded-3xl bg-gradient-to-br from-red-100 to-pink-100 dark:from-red-950/40 dark:to-pink-950/40"><Heart aria-hidden="true" className="h-12 w-12 text-red-500"/></div><div className="text-center"><div className="text-lg font-black text-brand-text">Favorileriniz yükleniyor</div><div className="mt-1 text-sm font-semibold text-brand-muted">Beğendiğiniz ürünler hazırlanıyor…</div></div></div></Panel>;
 if(!items)return<Panel title="Favorilerim" description="Kaydettiğiniz ürünleri güncel fiyat ve stok bilgileriyle yeniden inceleyin."><div className="rounded-2xl border-2 border-red-200 bg-red-50 p-4 font-semibold leading-relaxed text-red-800 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200"><p>⚠️ {error||'Favorilerinizi şu anda gösteremiyoruz.'}</p><button type="button" onClick={()=>void load()} className="mt-3 inline-flex min-h-11 items-center gap-2 rounded-xl border-2 border-red-300 bg-white px-4 font-bold transition-all hover:border-red-400 hover:bg-red-50 dark:bg-red-950/20 dark:hover:bg-red-900/30 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><RefreshCw aria-hidden="true" className="h-4 w-4"/>Yeniden dene</button></div></Panel>;
 return<Panel title="Favorilerim" description="Beğendiğiniz ürünleri, üretici bilgileri ve güncel satış durumlarıyla tek yerde inceleyin.">{error?<div className="mb-5 rounded-2xl border-2 border-red-200 bg-red-50 p-4 font-semibold leading-relaxed text-red-800 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200"><p>⚠️ {error}</p><button type="button" onClick={()=>void load()} className="mt-3 inline-flex min-h-11 items-center gap-2 rounded-xl border-2 border-red-300 bg-white px-4 font-bold transition-all hover:border-red-400 hover:bg-red-50 dark:bg-red-950/20 dark:hover:bg-red-900/30 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><RefreshCw aria-hidden="true" className="h-4 w-4"/>Yeniden dene</button></div>:null}{status?<div role="status" aria-live="polite" className="mb-5 rounded-2xl border-2 border-green-200 bg-green-50 p-3 text-sm font-bold text-green-800 dark:bg-green-950/30 dark:text-green-200">{status}</div>:null}<div className="sr-only" role="status" aria-live="polite">{busyId?'Favori işlemi yapılıyor.':''}</div>{!items.length?<div className="flex min-h-60 flex-col items-center justify-center gap-4 rounded-2xl border-2 border-dashed border-gray-200 py-10 dark:border-gray-800"><div className="grid h-20 w-20 place-items-center rounded-3xl bg-gradient-to-br from-gray-100 to-gray-200 dark:from-gray-800 dark:to-gray-900"><Heart aria-hidden="true" className="h-10 w-10 text-gray-400"/></div><div className="text-center"><div className="text-lg font-black text-brand-text">Favoriniz yok</div><div className="mt-2 max-w-sm text-sm leading-relaxed text-brand-muted">Beğendiğiniz ürünleri katalogdan veya ürün detayından kalp simgesine tıklayarak buraya ekleyebilirsiniz.</div></div></div>:<div className="grid gap-5 sm:grid-cols-2 sm:gap-6">{items.map(item=>{const busy=busyId===item.productId,saleReady=item.available&&Boolean(item.variant),official=item.producer.storeKind==='official',handlingLabel=productHandlingLabel(item.handlingProfile),tracked=item.stockMode==='tracked'||item.stockMode==='seasonal';return<article key={item.productId} aria-busy={busy} className={`overflow-hidden rounded-2xl border-2 shadow-sm transition-all hover:shadow-md dark:bg-gray-900 ${official?'border-rose-200 bg-white dark:border-rose-900/70':'border-gray-200 bg-white dark:border-gray-800'}`}>
  {item.imagePath?<button type="button" disabled={!onOpenProduct} onClick={()=>onOpenProduct?.(item.slug)} className="block w-full disabled:cursor-default"><img src={catalogPublicUrl(item.imagePath)} alt={`${item.name} görseli`} loading="lazy" decoding="async" onError={e=>{const img=e.currentTarget;if(!img.dataset.fallback){img.dataset.fallback='1';img.style.display='none';const fallback=img.nextElementSibling;if(fallback)fallback.classList.remove('hidden');}}} className="h-40 w-full object-cover"/><div className="hidden grid h-40 w-full place-items-center border-2 border-dashed border-gray-200 bg-gray-100 px-4 text-center text-sm font-semibold text-gray-500 dark:bg-gray-800"><Heart aria-hidden="true" className="mb-2 h-8 w-8 text-gray-300"/><div>Ürün görseli yüklenemedi</div></div></button>:<div role="img" aria-label={`${item.name} için doğrulanmış görsel henüz yayınlanmadı`} className="grid h-40 w-full place-items-center border-2 border-dashed border-gray-200 bg-gray-100 px-4 text-center text-sm font-semibold text-gray-500 dark:bg-gray-800">Doğrulanmış görsel henüz yayınlanmadı</div>}
  <div className="p-5"><div className="mb-3 flex flex-wrap items-center gap-2 text-xs font-bold"><span className={`rounded-full border-2 px-2.5 py-1 ${saleReady?'border-green-200 bg-green-50 text-green-800 dark:bg-green-950/40 dark:text-green-200':'border-amber-200 bg-amber-50 text-amber-900 dark:bg-amber-950/40 dark:text-amber-200'}`}>{saleReady?'Satışta':'Şu an satışta değil'}</span>{handlingLabel?<span className={`rounded-full border-2 px-2.5 py-1 ${handlingChip(item.handlingProfile.productType)}`}>{handlingLabel}{item.handlingProfile.requiresColdChain?' • Soğuk zincir':''}</span>:null}{item.producer.verified?<span className={`inline-flex items-center gap-1 rounded-full border-2 px-2.5 py-1 ${official?'border-rose-200 bg-rose-100 text-rose-800 dark:bg-rose-950/40 dark:text-rose-200':'border-blue-200 bg-blue-100 text-blue-800 dark:bg-blue-950/40 dark:text-blue-200'}`}><BadgeCheck aria-hidden="true" className="h-3.5 w-3.5"/>{item.producer.storeBadgeLabel}</span>:null}{item.producer.originVerified?<span className="inline-flex items-center gap-1 rounded-full border-2 border-brand-gold/30 bg-brand-gold/10 px-2.5 py-1 text-brand-gold"><CheckCircle2 aria-hidden="true" className="h-3.5 w-3.5"/>Menşe doğrulandı</span>:null}</div>
  <h3 className="line-clamp-2 text-lg font-black leading-snug">{item.name}</h3>{item.shortDescription?<p className="mt-2 line-clamp-2 text-sm leading-relaxed text-gray-500">{item.shortDescription}</p>:null}<p className="mt-3 text-sm font-bold text-gray-700 dark:text-gray-200">Üretici: {item.producer.name}</p>{item.origin?<p className="mt-1 text-xs leading-relaxed text-gray-500">Menşe: {item.origin}</p>:null}{tracked?<p className={`mt-3 text-xs font-black ${item.availableQuantity===0?'text-red-700 dark:text-red-300':'text-gray-500'}`}>{item.availableQuantity===0?'Stokta yok':item.availableQuantity!==null&&item.availableQuantity<=5?`${item.availableQuantity} adet mevcut`:'Stokta'}</p>:item.stockMode==='preorder'?<p className="mt-3 text-xs font-black text-brand-green">Ön siparişe açık</p>:null}
  {item.variant?<div className="mt-4 flex items-end gap-2"><div className="font-black text-brand-green dark:text-brand-gold"><Money minor={item.variant.priceMinor} currency={item.currency}/></div>{item.variant.compareAtPriceMinor!==null&&item.variant.compareAtPriceMinor>item.variant.priceMinor?<div className="text-sm font-bold text-gray-400 line-through"><Money minor={item.variant.compareAtPriceMinor} currency={item.currency}/></div>:null}</div>:<p className="mt-4 text-sm font-semibold leading-relaxed text-amber-700 dark:text-amber-300">Bu ürün için şu anda satın alınabilir bir seçenek yok.</p>}
  <div className="mt-5 grid grid-cols-[1fr_auto] gap-3"><button type="button" disabled={!onOpenProduct} onClick={()=>onOpenProduct?.(item.slug)} className="min-h-11 rounded-xl border-2 border-brand-green bg-brand-green px-3 font-bold text-brand-on-green shadow-sm transition-all hover:bg-green-700 disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">Ürünü aç</button><button type="button" disabled={busy} onClick={()=>void remove(item)} aria-label={`${item.name} ürününü favorilerden çıkar`} className="min-h-11 rounded-xl border-2 border-gray-200 bg-white px-3 font-bold transition-all hover:border-red-300 hover:bg-red-50 disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold dark:border-gray-700 dark:bg-gray-900">{busy?'Çıkarılıyor…':'Favoriden çıkar'}</button></div></div>
 </article>;})}</div>}</Panel>;
}
