import React,{useEffect,useMemo,useRef,useState}from'react';
import{ArrowLeft,FileText,Image as ImageIcon,Paperclip,RefreshCw,Send,X}from'lucide-react';
import{attachmentDisplayName,getConversationMessages,getMessageAttachmentUrl,listMyConversations,markConversationRead,removeUnusedMessageAttachments,sendConversationMessage,setConversationOpenState,uploadMessageAttachment}from'./messagesApi';
import{EmptyState,ErrorState,LoadingState,Panel}from'./ui';

type DraftFile={file:File;id:string};
const allowedAccept='image/jpeg,image/png,image/webp,image/avif,application/pdf';
const allowedTypes=new Set(['image/jpeg','image/png','image/webp','image/avif','application/pdf']);
const MESSAGE_PAGE_SIZE=60;
const CONVERSATION_PAGE_SIZE=30;

function normalizedId(value:unknown){return String(value||'').trim();}
function verifiedUnread(value:unknown){const parsed=Number(value);return Number.isSafeInteger(parsed)&&parsed>=0?parsed:null;}
function safeTime(value:unknown){const raw=String(value||'').trim();if(!raw)return Number.NEGATIVE_INFINITY;const time=new Date(raw).getTime();return Number.isFinite(time)?time:Number.NEGATIVE_INFINITY;}
function messageKey(message:any,index:number){const id=normalizedId(message?.id);return id?`id:${id}`:`fallback:${String(message?.createdAt||'')}|${String(message?.senderName||'')}|${index}`;}
function conversationKey(item:any,index:number){const id=normalizedId(item?.id);return id?`id:${id}`:`fallback:${String(item?.updatedAt||item?.lastMessageAt||'')}|${String(item?.title||item?.subject||'')}|${index}`;}
function draftId(){try{return crypto.randomUUID();}catch{return`file-${Date.now()}-${Math.random().toString(36).slice(2)}`;}}

export default function MessagesPanel({initialConversationId}:{initialConversationId?:string|null}){
 const initialId=normalizedId(initialConversationId);
 const[conversations,setConversations]=useState<any[]>([]);const[selectedId,setSelectedId]=useState(initialId);const[messages,setMessages]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[listMoreLoading,setListMoreLoading]=useState(false);const[hasMoreConversations,setHasMoreConversations]=useState(false);const[threadLoading,setThreadLoading]=useState(false);const[olderLoading,setOlderLoading]=useState(false);const[hasOlder,setHasOlder]=useState(false);const[error,setError]=useState('');const[body,setBody]=useState('');const[files,setFiles]=useState<DraftFile[]>([]);const[sending,setSending]=useState(false);const[status,setStatus]=useState('');const listTimer=useRef<number|null>(null);const threadTimer=useRef<number|null>(null);const endRef=useRef<HTMLDivElement>(null);const threadRef=useRef<HTMLDivElement>(null);const conversationLimitRef=useRef(CONVERSATION_PAGE_SIZE);
 const selected=useMemo(()=>conversations.find(item=>normalizedId(item?.id)===selectedId)||null,[conversations,selectedId]);
 async function loadList(silent=false,limit=conversationLimitRef.current){
  try{
   if(!silent){setLoading(true);setError('');}
   const requestLimit=Math.max(CONVERSATION_PAGE_SIZE,Math.min(300,Number.isSafeInteger(limit)?limit:CONVERSATION_PAGE_SIZE));
   const result=await listMyConversations(requestLimit,0);const rows=Array.isArray(result)?result:[];
   conversationLimitRef.current=requestLimit;setHasMoreConversations(rows.length===requestLimit);setConversations(rows);
   if(initialId&&rows.some((row:any)=>normalizedId(row?.id)===initialId))setSelectedId(current=>current||initialId);
  }catch(e:any){if(!silent)setError(e?.message||'Konuşmalar yüklenemedi.');}
  finally{if(!silent)setLoading(false);}
 }
 async function loadMoreConversations(){if(listMoreLoading||!hasMoreConversations)return;try{setListMoreLoading(true);setError('');const nextLimit=Math.min(300,conversationLimitRef.current+CONVERSATION_PAGE_SIZE);const result=await listMyConversations(nextLimit,0);const rows=Array.isArray(result)?result:[];conversationLimitRef.current=nextLimit;setHasMoreConversations(nextLimit<300&&rows.length===nextLimit);setConversations(rows);}catch(e:any){setError(e?.message||'Daha fazla konuşma yüklenemedi.');}finally{setListMoreLoading(false);}}
 async function loadThread(id:string,silent=false){
  const conversationId=normalizedId(id);if(!conversationId)return;
  try{
   if(!silent){setThreadLoading(true);setError('');}
   const result=await getConversationMessages(conversationId,MESSAGE_PAGE_SIZE,null);const rows=Array.isArray(result)?result:[];setHasOlder(rows.length===MESSAGE_PAGE_SIZE);
   setMessages(current=>{if(!silent)return rows;const unique=new Map<string,any>();current.forEach((message,index)=>unique.set(messageKey(message,index),message));rows.forEach((message,index)=>unique.set(messageKey(message,current.length+index),message));return Array.from(unique.values()).sort((a,b)=>safeTime(a?.createdAt)-safeTime(b?.createdAt));});
   try{await markConversationRead(conversationId);setConversations(current=>current.map(item=>normalizedId(item?.id)===conversationId?{...item,unreadCount:0}:item));}catch(e:any){if(!silent)setError(e?.message||'Mesajlar açıldı ancak okundu durumu güncellenemedi.');}
   if(!silent)window.setTimeout(()=>endRef.current?.scrollIntoView({block:'end'}),30);
  }catch(e:any){if(!silent)setError(e?.message||'Mesajlar yüklenemedi.');}
  finally{if(!silent)setThreadLoading(false);}
 }
 async function loadOlder(){if(!selectedId||olderLoading||!hasOlder||!messages.length)return;const before=String(messages[0]?.createdAt||'').trim();if(!before||!Number.isFinite(new Date(before).getTime())){setError('Eski mesaj sayfası için tarih sınırı doğrulanamadı.');return;}const container=threadRef.current;const previousHeight=container?.scrollHeight||0;try{setOlderLoading(true);setError('');const result=await getConversationMessages(selectedId,MESSAGE_PAGE_SIZE,before);const rows=Array.isArray(result)?result:[];setHasOlder(rows.length===MESSAGE_PAGE_SIZE);setMessages(current=>{const unique=new Map<string,any>();rows.forEach((message,index)=>unique.set(messageKey(message,index),message));current.forEach((message,index)=>unique.set(messageKey(message,rows.length+index),message));return Array.from(unique.values()).sort((a,b)=>safeTime(a?.createdAt)-safeTime(b?.createdAt));});window.requestAnimationFrame(()=>{if(container)container.scrollTop=Math.max(0,container.scrollHeight-previousHeight);});}catch(e:any){setError(e?.message||'Eski mesajlar yüklenemedi.');}finally{setOlderLoading(false);}}
 useEffect(()=>{void loadList();return()=>{if(listTimer.current)window.clearInterval(listTimer.current);if(threadTimer.current)window.clearInterval(threadTimer.current);};},[]);
 useEffect(()=>{if(listTimer.current)window.clearInterval(listTimer.current);listTimer.current=window.setInterval(()=>void loadList(true,conversationLimitRef.current),30000);return()=>{if(listTimer.current)window.clearInterval(listTimer.current);};},[]);
 useEffect(()=>{if(!selectedId){setMessages([]);setHasOlder(false);return;}void loadThread(selectedId);if(threadTimer.current)window.clearInterval(threadTimer.current);threadTimer.current=window.setInterval(()=>void loadThread(selectedId,true),15000);return()=>{if(threadTimer.current)window.clearInterval(threadTimer.current);};},[selectedId]);
 async function send(){if(!selectedId||sending)return;const trimmed=body.trim();if(!trimmed&&!files.length){setError('Mesaj veya ek dosya ekleyin.');return;}if(trimmed.length>5000){setError('Mesaj en fazla 5000 karakter olabilir.');return;}if(files.length>5){setError('Bir mesajda en fazla 5 ek dosya olabilir.');return;}const uploaded:string[]=[];try{setSending(true);setError('');setStatus(files.length?'Ek dosyalar hazırlanıyor…':'Mesaj hazırlanıyor…');for(const item of files){uploaded.push(await uploadMessageAttachment(selectedId,item.file));}const text=trimmed||'Ek dosya gönderildi.';const imageOnly=files.length>0&&files.every(item=>item.file.type.startsWith('image/'));setStatus('Mesaj gönderiliyor…');await sendConversationMessage({conversationId:selectedId,body:text,attachmentPaths:uploaded,messageType:files.length?(imageOnly?'image':'file'):'text'});setBody('');setFiles([]);setStatus('Mesaj gönderildi.');await Promise.all([loadThread(selectedId,true),loadList(true,conversationLimitRef.current)]);window.setTimeout(()=>endRef.current?.scrollIntoView({block:'end'}),30);}catch(e:any){if(uploaded.length)await removeUnusedMessageAttachments(uploaded).catch(()=>{});setError(e?.message||'Mesaj gönderilemedi.');setStatus('');}finally{setSending(false);}}
 async function toggleOpen(){const id=normalizedId(selected?.id);const currentStatus=String(selected?.status||'').trim();if(!id||!['open','closed'].includes(currentStatus))return;try{setError('');setStatus('Konuşma durumu güncelleniyor…');await setConversationOpenState(id,currentStatus==='closed');await loadList(true,conversationLimitRef.current);await loadThread(id,true);setStatus(currentStatus==='closed'?'Konuşma yeniden açıldı.':'Konuşma kapatıldı.');}catch(e:any){setError(e?.message||'Konuşma durumu değiştirilemedi.');setStatus('');}}
 function addFiles(fileList:FileList|null){if(!fileList)return;setError('');const incoming=Array.from(fileList);if(files.length+incoming.length>5){setError('Bir mesajda en fazla 5 ek dosya olabilir.');return;}for(const file of incoming){if(file.size<=0||file.size>20*1024*1024){setError('Her ek dosya boş olmamalı ve en fazla 20 MB olabilir.');return;}if(!allowedTypes.has(file.type)){setError('Ek dosya JPEG, PNG, WebP, AVIF veya PDF olmalıdır.');return;}}setFiles(current=>[...current,...incoming.map(file=>({file,id:draftId()}))]);}
 async function openAttachment(path:string){const normalized=String(path||'').trim();if(!normalized){setError('Ek dosya yolu doğrulanamadı.');return;}try{setError('');const url=await getMessageAttachmentUrl(normalized);window.open(url,'_blank','noopener,noreferrer');}catch(e:any){setError(e?.message||'Ek dosya açılamadı.');}}
 if(loading)return<LoadingState label="Konuşmalar yükleniyor"/>;
 const selectedStatus=String(selected?.status||'').trim();const selectedStatusKnown=['open','closed'].includes(selectedStatus);
 return<Panel title="Mesajlarım" description="Golden Oremar destek ve üretici konuşmalarınızı güvenli biçimde yönetin.">
  {error?<ErrorState message={error} onRetry={()=>selectedId?void loadThread(selectedId):void loadList()}/>:null}
  <div className="sr-only" role="status" aria-live="polite">{threadLoading?'Mesajlar yükleniyor.':olderLoading?'Eski mesajlar yükleniyor.':listMoreLoading?'Daha fazla konuşma yükleniyor.':sending?'Mesaj gönderiliyor.':status}</div>
  {!selectedId?<>
   <div className="mb-3 flex items-center justify-between gap-3"><div className="text-sm text-gray-500" aria-live="polite">{conversations.length} konuşma gösteriliyor</div><button type="button" onClick={()=>void loadList(false,conversationLimitRef.current)} disabled={listMoreLoading} className="min-h-11 rounded-xl border px-4 font-semibold disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><RefreshCw aria-hidden="true" className="mr-2 inline h-4 w-4"/>Yenile</button></div>
   {!conversations.length?<EmptyState title="Henüz konuşmanız yok" body="Destek veya üreticiyle başlatılan güvenli konuşmalar burada görünecek."/>:<><div className="space-y-2">{conversations.map((item:any,index:number)=>{const id=normalizedId(item?.id);const unread=verifiedUnread(item?.unreadCount);return <button type="button" key={conversationKey(item,index)} disabled={!id} onClick={()=>setSelectedId(id)} className={`min-h-16 w-full rounded-xl border p-4 text-left disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold ${unread!==null&&unread>0?'border-brand-gold/50 bg-brand-gold/5':''}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="font-bold">{String(item?.title||'').trim()||'Konuşma'}</div><div className="mt-1 truncate text-sm text-gray-500">{String(item?.subject||'').trim()||'Konu bilgisi yok'}</div><div className="mt-1 line-clamp-1 text-sm text-gray-600 dark:text-gray-300">{String(item?.lastMessage||'').trim()||'Henüz mesaj yok'}</div>{!id?<div className="mt-1 text-xs text-red-700 dark:text-red-300">Konuşma kimliği doğrulanamadı</div>:null}</div><div className="shrink-0 text-right">{unread===null?<span className="text-xs text-red-700 dark:text-red-300">Okunmamış sayısı doğrulanamadı</span>:unread>0?<span className="inline-grid min-h-6 min-w-6 place-items-center rounded-full bg-brand-gold px-1 text-xs font-bold text-white" aria-label={`${unread} okunmamış mesaj`}>{unread}</span>:null}<div className="mt-2 text-xs text-gray-400">{formatDate(item?.lastMessageAt||item?.updatedAt)}</div></div></div></button>;})}</div>{hasMoreConversations?<div className="mt-4 flex justify-center"><button type="button" disabled={listMoreLoading} onClick={()=>void loadMoreConversations()} className="min-h-11 rounded-xl border px-5 font-semibold disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">{listMoreLoading?'Konuşmalar yükleniyor…':'Daha fazla konuşma göster'}</button></div>:conversations.length>=CONVERSATION_PAGE_SIZE?<p className="mt-4 text-center text-xs text-gray-400">Yüklenebilen konuşmalar gösteriliyor.</p>:null}</>}
  </>:<div className="space-y-4">
   <div className="flex items-start justify-between gap-3"><button type="button" onClick={()=>{setSelectedId('');setBody('');setFiles([]);setStatus('');}} className="min-h-11 rounded-xl border px-4 font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><ArrowLeft aria-hidden="true" className="mr-2 inline h-4 w-4"/>Konuşmalar</button><button type="button" onClick={()=>void loadThread(selectedId)} disabled={threadLoading} className="min-h-11 rounded-xl border px-3 disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold" aria-label="Mesajları yenile"><RefreshCw aria-hidden="true" className="h-4 w-4"/></button></div>
   {!selected?<div role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900 dark:border-amber-900/60 dark:bg-amber-950/30 dark:text-amber-100">Bu konuşma mevcut listede doğrulanamadı. Yenileyin veya konuşma listesine dönün.</div>:<div className="rounded-xl border p-4"><div className="font-bold">{String(selected?.title||'').trim()||'Konuşma'}</div><div className="mt-1 text-sm text-gray-500">{String(selected?.subject||'').trim()||'Konu bilgisi yok'}</div><div className="mt-2 flex items-center justify-between gap-3"><span className={`text-xs font-semibold ${selectedStatus==='closed'?'text-gray-500':selectedStatus==='open'?'text-green-700':'text-red-700 dark:text-red-300'}`}>{selectedStatus==='closed'?'Kapalı':selectedStatus==='open'?'Açık':'Durum doğrulanamadı'}</span><button type="button" disabled={!selectedStatusKnown||sending} onClick={()=>void toggleOpen()} className="min-h-11 rounded-lg border px-3 text-sm font-semibold disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">{selectedStatus==='closed'?'Konuşmayı yeniden aç':'Konuşmayı kapat'}</button></div></div>}
   {threadLoading?<LoadingState label="Mesajlar yükleniyor"/>:<div ref={threadRef} className="max-h-[52vh] space-y-3 overflow-y-auto rounded-2xl border bg-gray-50 p-3 dark:bg-gray-950">{hasOlder?<div className="flex justify-center pb-1"><button type="button" disabled={olderLoading} onClick={()=>void loadOlder()} className="min-h-11 rounded-xl border bg-white px-4 text-sm font-semibold disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold dark:bg-gray-900">{olderLoading?'Eski mesajlar yükleniyor…':'Daha eski mesajları göster'}</button></div>:messages.length?<div className="text-center text-xs text-gray-400">Konuşmanın yüklenebilen başlangıcına ulaştınız.</div>:null}{messages.length?messages.map((message:any,index:number)=>{const sender=message?.isMine?'Siz':String(message?.senderName||'').trim()||'Gönderen doğrulanamadı';const attachmentPaths=Array.isArray(message?.attachmentPaths)?message.attachmentPaths.filter((path:any)=>String(path||'').trim()):[];return <article key={messageKey(message,index)} className={`max-w-[88%] rounded-2xl p-3 ${message?.isMine?'ml-auto bg-brand-green text-white':'mr-auto bg-white text-gray-900 dark:bg-gray-800 dark:text-white'}`}><div className="text-xs font-semibold opacity-75">{sender}</div><p className="mt-1 whitespace-pre-wrap break-words text-sm leading-6">{String(message?.body||'').trim()||'Mesaj içeriği doğrulanamadı'}</p>{attachmentPaths.length?<div className="mt-2 space-y-1">{attachmentPaths.map((path:any,pathIndex:number)=>{const normalized=String(path).trim();return <button type="button" key={`${normalized}-${pathIndex}`} onClick={()=>void openAttachment(normalized)} className={`flex min-h-11 w-full items-center gap-2 rounded-lg border px-3 text-left text-xs font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold ${message?.isMine?'border-white/30':'border-gray-200 dark:border-gray-700'}`}>{isImagePath(normalized)?<ImageIcon aria-hidden="true" className="h-4 w-4"/>:<FileText aria-hidden="true" className="h-4 w-4"/>}<span className="min-w-0 flex-1 truncate">{attachmentDisplayName(normalized)||`Ek ${pathIndex+1}`}</span></button>;})}</div>:null}<div className="mt-2 text-[11px] opacity-60">{formatDate(message?.createdAt)}</div></article>; }):<div className="p-6 text-center text-sm text-gray-500">Henüz mesaj yok.</div>}<div ref={endRef}/></div>}
   {selectedStatus==='closed'?<div role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900 dark:border-amber-900/60 dark:bg-amber-950/30 dark:text-amber-100">Bu konuşma kapalı. Yeni mesaj göndermek için yeniden açın.</div>:selectedStatus==='open'?<div className="rounded-2xl border p-4"><label className="block"><span className="text-sm font-semibold">Mesajınız</span><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={5000} rows={4} disabled={sending} className="mt-1 w-full rounded-xl border bg-transparent p-3 disabled:opacity-60" placeholder="Mesajınızı yazın…"/><span className="mt-1 block text-xs text-gray-500">{body.length}/5000</span></label><div className="mt-3 flex flex-wrap items-center gap-2"><label className={`inline-flex min-h-11 items-center rounded-xl border px-4 font-semibold focus-within:ring-2 focus-within:ring-brand-gold ${sending?'cursor-not-allowed opacity-50':'cursor-pointer'}`}><Paperclip aria-hidden="true" className="mr-2 h-4 w-4"/>Dosya ekle<input type="file" multiple accept={allowedAccept} disabled={sending} className="sr-only" onChange={e=>{addFiles(e.target.files);e.currentTarget.value='';}}/></label><span className="text-xs text-gray-500">En fazla 5 dosya • 20 MB/dosya</span></div>{files.length?<ul className="mt-3 space-y-2">{files.map(item=><li key={item.id} className="flex items-center justify-between gap-3 rounded-lg bg-gray-50 p-2 dark:bg-gray-800"><span className="min-w-0 truncate text-sm">{item.file.name}</span><button type="button" disabled={sending} onClick={()=>setFiles(current=>current.filter(file=>file.id!==item.id))} className="min-h-11 rounded-lg border px-3 disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold" aria-label={`${item.file.name} dosyasını kaldır`}><X aria-hidden="true" className="h-4 w-4"/></button></li>)}</ul>:null}<div aria-live="polite" className="mt-2 min-h-5 text-xs text-brand-green">{status}</div><button type="button" onClick={()=>void send()} disabled={sending||(!body.trim()&&!files.length)} className="mt-2 min-h-12 w-full rounded-xl bg-brand-green px-4 font-bold text-white disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><Send aria-hidden="true" className="mr-2 inline h-4 w-4"/>{sending?'Gönderiliyor…':'Mesajı gönder'}</button></div>:<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200">Konuşma durumu doğrulanamadığı için yeni mesaj gönderme ve durum değiştirme işlemleri güvenlik amacıyla kapatıldı.</div>}
  </div>}
 </Panel>;
}
function formatDate(value?:string|null){const raw=String(value||'').trim();if(!raw)return'Tarih doğrulanamadı';const date=new Date(raw);if(Number.isNaN(date.getTime()))return'Tarih doğrulanamadı';try{return new Intl.DateTimeFormat('tr-TR',{dateStyle:'short',timeStyle:'short'}).format(date);}catch{return'Tarih doğrulanamadı';}}
function isImagePath(path:string){return/\.(jpe?g|png|webp|avif)$/i.test(path.split('?')[0]);}
