import{ supabase }from'../../lib/supabase';

const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const conversationTypes=new Set<ConversationType>(['support','producer','order']);
const conversationStatuses=new Set<ConversationStatus>(['open','waiting_customer','waiting_support','closed']);
const messageTypes=new Set<MessageType>(['text','image','file','system']);
const sendableMessageTypes=new Set<SendableMessageType>(['text','image','file']);

type ConversationType='support'|'producer'|'order';
export type ConversationStatus='open'|'waiting_customer'|'waiting_support'|'closed';
export type MessageType='text'|'image'|'file'|'system';
type SendableMessageType='text'|'image'|'file';
export type ConversationSummary={id:string;type:ConversationType;orderId:string|null;producerId:string|null;productId:string|null;subject:string|null;status:ConversationStatus;updatedAt:string;lastMessageAt:string|null;title:string;lastMessage:string;unreadCount:number};
export type ConversationMessage={id:string;senderUserId:string;senderName:string;isMine:boolean;body:string;attachmentPaths:string[];messageType:MessageType;createdAt:string;editedAt:string|null;deletedAt:string|null};
export type ConversationStateResult={conversationId:string;status:'open'|'closed';closedAt:string|null};
export type SentMessageResult={id:string;conversationId:string;messageType:SendableMessageType;createdAt:string};
export type StartedProducerConversation={conversationId:string;messageId:string;status:'open';producerId:string;productId:string|null;orderId:string|null};
export type MyMessagePolicy={producerProtectionEnabled:boolean;allowAttachments:boolean;allowImages:boolean;allowPdf:boolean;maxAttachments:number;maxAttachmentMb:number};

const moderationMessages:Record<string,string>={email:'E-posta adresi',phone:'Telefon numarası',messaging_app:'WhatsApp, Telegram, Signal veya Viber bilgisi',external_link:'Dış bağlantı',social_handle:'Sosyal medya kullanıcı adı',bank_details:'Banka veya IBAN bilgisi',external_payment:'Platform dışı ödeme yöntemi',qr_code:'QR / karekod yönlendirmesi',custom_phrase:'Yasaklı ticaret ifadesi'};
function userFacingRpcError(error:unknown){const message=error instanceof Error?error.message:String((error as any)?.message??error??'');const match=message.match(/message_moderation_blocked:([a-z_]+)/i);if(match){const label=moderationMessages[match[1]]||'Platform dışı iletişim bilgisi';return new Error(`${label} mağaza mesajlarında paylaşılamaz. Lütfen görüşmeyi ve ticareti Golden Oremar içinde sürdürün.`);}if(message.includes('message_attachments_disabled'))return new Error('Mesaj eki gönderimi şu anda Super Admin politikası tarafından kapalı.');if(message.includes('message_attachment_limit_exceeded'))return new Error('Ek dosya sayısı mevcut mesaj güvenliği sınırını aşıyor.');if(message.includes('message_attachment_size_not_allowed'))return new Error('Ek dosyalardan biri mevcut boyut sınırını aşıyor.');if(message.includes('message_attachment_type_not_allowed'))return new Error('Bu dosya türüne mevcut mesaj güvenliği politikası izin vermiyor.');if(message.includes('message_attachment_conversation_mismatch'))return new Error('Ek dosya bu konuşmaya ait değil.');return error instanceof Error?error:new Error(message||'İşlem tamamlanamadı.');}
function unwrap<T>(data:T|null,error:unknown):T{if(error)throw userFacingRpcError(error);return data as T;}
function isRecord(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function boundedInt(value:number,fallback:number,min:number,max:number){const parsed=Number(value);return Number.isSafeInteger(parsed)?Math.min(max,Math.max(min,parsed)):fallback;}
function requiredUuid(value:unknown,label:string){const id=String(value??'').trim();if(!UUID_RE.test(id))throw new Error(`${label} kimliği geçersiz.`);return id;}
function optionalUuid(value:unknown,label:string){if(value==null||value==='')return null;return requiredUuid(value,label);}
function requiredText(value:unknown,label:string,max:number){const text=typeof value==='string'?value.trim():'';if(!text||text.length>max||/[\u0000-\u001f\u007f]/.test(text))throw new Error(`${label} doğrulanamadı.`);return text;}
function optionalText(value:unknown,label:string,max:number){if(value==null||value==='')return null;if(typeof value!=='string')throw new Error(`${label} doğrulanamadı.`);const text=value.trim();if(!text)return null;if(text.length>max||/[\u0000-\u001f\u007f]/.test(text))throw new Error(`${label} doğrulanamadı.`);return text;}
function textAllowEmpty(value:unknown,label:string,max:number){if(typeof value!=='string'||value.length>max||/[\u0000-\u001f\u007f]/.test(value))throw new Error(`${label} doğrulanamadı.`);return value;}
function safeInt(value:unknown,label:string,min=0,max=Number.MAX_SAFE_INTEGER){const parsed=typeof value==='number'?value:Number(value);if(!Number.isSafeInteger(parsed)||parsed<min||parsed>max)throw new Error(`${label} doğrulanamadı.`);return parsed;}
function booleanValue(value:unknown,label:string){if(typeof value!=='boolean')throw new Error(`${label} doğrulanamadı.`);return value;}
function dateTime(value:unknown,label:string,required=true){if(value==null||value===''){if(required)throw new Error(`${label} doğrulanamadı.`);return null;}if(typeof value!=='string')throw new Error(`${label} doğrulanamadı.`);const date=new Date(value);if(Number.isNaN(date.getTime()))throw new Error(`${label} doğrulanamadı.`);return date.toISOString();}
function enumValue<T extends string>(value:unknown,label:string,allowed:Set<T>){if(typeof value!=='string'||!allowed.has(value as T))throw new Error(`${label} doğrulanamadı.`);return value as T;}
function safeStoragePath(value:unknown){const path=String(value??'').trim().replace(/^\/+/, '');if(!path||path.length>500||/[\u0000-\u001f\\]/.test(path)||path.split('/').some(part=>!part||part==='.'||part==='..'))throw new Error('Ek dosya yolu geçersiz.');return path;}

function normalizeConversation(value:unknown,index:number):ConversationSummary{if(!isRecord(value))throw new Error(`${index+1}. konuşma doğrulanamadı.`);return{id:requiredUuid(value.id,`${index+1}. konuşma`),type:enumValue(value.type,`${index+1}. konuşma türü`,conversationTypes),orderId:optionalUuid(value.orderId,`${index+1}. sipariş`),producerId:optionalUuid(value.producerId,`${index+1}. üretici`),productId:optionalUuid(value.productId,`${index+1}. ürün`),subject:optionalText(value.subject,`${index+1}. konuşma konusu`,200),status:enumValue(value.status,`${index+1}. konuşma durumu`,conversationStatuses),updatedAt:dateTime(value.updatedAt,`${index+1}. konuşma güncelleme tarihi`) as string,lastMessageAt:dateTime(value.lastMessageAt,`${index+1}. son mesaj tarihi`,false),title:requiredText(value.title,`${index+1}. konuşma başlığı`,240),lastMessage:textAllowEmpty(value.lastMessage,`${index+1}. son mesaj`,180),unreadCount:safeInt(value.unreadCount,`${index+1}. okunmamış mesaj sayısı`)}};
function normalizeConversationList(value:unknown):ConversationSummary[]{if(!Array.isArray(value))throw new Error('Konuşma listesi sunucudan doğrulanamadı.');return value.map(normalizeConversation);}
function normalizeMessage(value:unknown,index:number):ConversationMessage{if(!isRecord(value)||!Array.isArray(value.attachmentPaths))throw new Error(`${index+1}. mesaj doğrulanamadı.`);const attachmentPaths=value.attachmentPaths.map(safeStoragePath);if(attachmentPaths.length>5||new Set(attachmentPaths).size!==attachmentPaths.length)throw new Error(`${index+1}. mesaj ekleri doğrulanamadı.`);const deletedAt=dateTime(value.deletedAt,`${index+1}. mesaj silinme tarihi`,false);if(deletedAt&&attachmentPaths.length)throw new Error(`${index+1}. silinmiş mesaj ekleri tutarsız.`);return{id:requiredUuid(value.id,`${index+1}. mesaj`),senderUserId:requiredUuid(value.senderUserId,`${index+1}. mesaj gönderen`),senderName:requiredText(value.senderName,`${index+1}. gönderen adı`,240),isMine:booleanValue(value.isMine,`${index+1}. mesaj sahipliği`),body:requiredText(value.body,`${index+1}. mesaj içeriği`,5000),attachmentPaths,messageType:enumValue(value.messageType,`${index+1}. mesaj türü`,messageTypes),createdAt:dateTime(value.createdAt,`${index+1}. mesaj tarihi`) as string,editedAt:dateTime(value.editedAt,`${index+1}. mesaj düzenleme tarihi`,false),deletedAt};}
function normalizeMessageList(value:unknown):ConversationMessage[]{if(!Array.isArray(value))throw new Error('Mesaj listesi sunucudan doğrulanamadı.');return value.map(normalizeMessage);}
function normalizeConversationState(value:unknown,conversationId:string,open:boolean):ConversationStateResult{if(!isRecord(value))throw new Error('Konuşma durum sonucu doğrulanamadı.');const returnedId=requiredUuid(value.conversationId,'Konuşma');if(returnedId!==conversationId)throw new Error('Konuşma durum sonucu başka kayda ait.');const expected=open?'open':'closed';if(value.status!==expected)throw new Error('Konuşma durum sonucu istenen durumla eşleşmiyor.');const closedAt=dateTime(value.closedAt,'Konuşma kapanış tarihi',false);if(open&&closedAt!==null)throw new Error('Açık konuşmada kapanış tarihi bulunamaz.');if(!open&&closedAt===null)throw new Error('Kapatılan konuşmanın kapanış tarihi doğrulanamadı.');return{conversationId:returnedId,status:expected,closedAt};}
function normalizeSentMessage(value:unknown,conversationId:string,messageType:SendableMessageType):SentMessageResult{if(!isRecord(value))throw new Error('Mesaj gönderim sonucu doğrulanamadı.');const returnedConversationId=requiredUuid(value.conversationId,'Konuşma');if(returnedConversationId!==conversationId||value.messageType!==messageType)throw new Error('Mesaj gönderim sonucu istekle eşleşmiyor.');return{id:requiredUuid(value.id,'Mesaj'),conversationId:returnedConversationId,messageType,createdAt:dateTime(value.createdAt,'Mesaj gönderim tarihi') as string};}
function normalizeStartedProducerConversation(value:unknown,expected:{producerId:string;productId:string|null;orderId:string|null}):StartedProducerConversation{if(!isRecord(value))throw new Error('Üretici soru konuşması sonucu doğrulanamadı.');const producerId=requiredUuid(value.producerId,'Üretici'),productId=optionalUuid(value.productId,'Ürün'),orderId=optionalUuid(value.orderId,'Sipariş');if(producerId!==expected.producerId||productId!==expected.productId||orderId!==expected.orderId||value.status!=='open')throw new Error('Üretici soru konuşması sonucu istek bağlamıyla eşleşmiyor.');return{conversationId:requiredUuid(value.conversationId,'Konuşma'),messageId:requiredUuid(value.messageId,'İlk mesaj'),status:'open',producerId,productId,orderId};}
function normalizePolicy(value:unknown):MyMessagePolicy{if(!isRecord(value))throw new Error('Mesaj politikası doğrulanamadı.');return{producerProtectionEnabled:booleanValue(value.producerProtectionEnabled,'Mağaza mesaj koruması'),allowAttachments:booleanValue(value.allowAttachments,'Dosya ekleme izni'),allowImages:booleanValue(value.allowImages,'Görsel ekleme izni'),allowPdf:booleanValue(value.allowPdf,'PDF ekleme izni'),maxAttachments:safeInt(value.maxAttachments,'Maksimum ek sayısı',0,5),maxAttachmentMb:safeInt(value.maxAttachmentMb,'Maksimum ek boyutu',1,20)}};
async function startProducerConversation(input:{producerId:string;productId:string|null;orderId:string|null;subject:string;message:string}):Promise<StartedProducerConversation>{const producerId=requiredUuid(input.producerId,'Üretici'),productId=input.productId==null?null:requiredUuid(input.productId,'Ürün'),orderId=input.orderId==null?null:requiredUuid(input.orderId,'Sipariş');if((productId?1:0)+(orderId?1:0)!==1)throw new Error('Üretici sorusu ürün veya sipariş bağlamından tam birini gerektirir.');const subject=requiredText(input.subject,'Soru konusu',200),message=requiredText(input.message,'Soru metni',5000);const{data,error}=await supabase.rpc('start_producer_conversation_v1',{p_producer_id:producerId,p_product_id:productId,p_order_id:orderId,p_subject:subject,p_initial_message:message});return normalizeStartedProducerConversation(unwrap<unknown>(data,error),{producerId,productId,orderId});}

export async function getMyMessagePolicy(){const{data,error}=await supabase.rpc('get_my_message_policy_v1');return normalizePolicy(unwrap<unknown>(data,error));}
export async function listMyConversations(limit=50,offset=0,scope:'all'|'producer'='all'):Promise<ConversationSummary[]>{const rpc=scope==='producer'?'list_my_producer_conversations_v1':'list_my_conversations_v1';const{data,error}=await supabase.rpc(rpc,{p_limit:boundedInt(limit,50,1,100),p_offset:boundedInt(offset,0,0,10000)});return normalizeConversationList(unwrap<unknown>(data,error));}
export async function getConversationMessages(conversationId:string,limit=100,before?:string|null):Promise<ConversationMessage[]>{const id=requiredUuid(conversationId,'Konuşma');const cursor=before?.trim()||null;if(cursor&&Number.isNaN(Date.parse(cursor)))throw new Error('Mesaj sayfalama tarihi geçersiz.');const{data,error}=await supabase.rpc('get_conversation_messages_v1',{p_conversation_id:id,p_limit:boundedInt(limit,100,1,100),p_before:cursor});return normalizeMessageList(unwrap<unknown>(data,error));}
export async function markConversationRead(conversationId:string){const id=requiredUuid(conversationId,'Konuşma');const{data,error}=await supabase.rpc('mark_conversation_read_v1',{p_conversation_id:id});return dateTime(unwrap<unknown>(data,error),'Konuşma okunma tarihi') as string;}
export async function setConversationOpenState(conversationId:string,open:boolean){const id=requiredUuid(conversationId,'Konuşma');const desired=open===true;const{data,error}=await supabase.rpc('set_conversation_open_state_v1',{p_conversation_id:id,p_open:desired});return normalizeConversationState(unwrap<unknown>(data,error),id,desired);}
export async function sendConversationMessage(input:{conversationId:string;body:string;attachmentPaths?:string[];messageType?:SendableMessageType}){const conversationId=requiredUuid(input.conversationId,'Konuşma');const body=String(input.body||'').trim();if(!body||body.length>5000)throw new Error('Mesaj 1 ile 5000 karakter arasında olmalıdır.');const rawAttachments=(Array.isArray(input.attachmentPaths)?input.attachmentPaths:[]).map(safeStoragePath);if(new Set(rawAttachments).size!==rawAttachments.length)throw new Error('Aynı ek dosya bir mesajda birden fazla kez kullanılamaz.');if(rawAttachments.length>5)throw new Error('Bir mesajda en fazla 5 ek dosya olabilir.');const messageType=input.messageType||'text';if(!sendableMessageTypes.has(messageType))throw new Error('Mesaj türü geçersiz.');if((messageType==='image'||messageType==='file')&&!rawAttachments.length)throw new Error('Dosyalı mesaj için en az bir ek dosya gerekir.');const{data,error}=await supabase.rpc('send_conversation_message_v1',{p_conversation_id:conversationId,p_body:body,p_attachment_paths:rawAttachments,p_message_type:messageType});return normalizeSentMessage(unwrap<unknown>(data,error),conversationId,messageType);}
export async function startProducerProductConversation(input:{producerId:string;productId:string;productName:string;message:string}){const productName=requiredText(input.productName,'Ürün adı',240);return startProducerConversation({producerId:input.producerId,productId:input.productId,orderId:null,subject:`Ürün hakkında: ${productName}`.slice(0,200),message:input.message});}
export async function startProducerOrderConversation(input:{producerId:string;orderId:string;orderNumber:string;message:string}){const orderNumber=requiredText(input.orderNumber,'Sipariş numarası',160);return startProducerConversation({producerId:input.producerId,productId:null,orderId:input.orderId,subject:`Sipariş hakkında: ${orderNumber}`.slice(0,200),message:input.message});}

const allowedMime=new Set(['image/jpeg','image/png','image/webp','image/avif','application/pdf']);
const maxBytes=20*1024*1024;
const extensionByMime:Record<string,string>={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/avif':'avif','application/pdf':'pdf'};
export async function uploadMessageAttachment(conversationId:string,file:File){const id=requiredUuid(conversationId,'Konuşma');if(!allowedMime.has(file.type))throw new Error('Ek dosya JPEG, PNG, WebP, AVIF veya PDF olmalıdır.');if(file.size<=0||file.size>maxBytes)throw new Error('Her ek dosya boş olmamalı ve en fazla 20 MB olabilir.');const{data:userData,error:userError}=await supabase.auth.getUser();if(userError)throw userFacingRpcError(userError);const userId=String(userData.user?.id||'').trim();if(!UUID_RE.test(userId))throw new Error('Oturum doğrulanamadı.');if(typeof globalThis.crypto?.randomUUID!=='function')throw new Error('Güvenli ek dosya kimliği üretilemedi.');const extension=extensionByMime[file.type];const path=`${userId}/${id}/${globalThis.crypto.randomUUID()}_attachment.${extension}`;const{error}=await supabase.storage.from('message-attachments').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(error)throw userFacingRpcError(error);return path;}
export async function removeUnusedMessageAttachments(paths:string[]){const unique=Array.isArray(paths)?[...new Set(paths.map(safeStoragePath))].slice(0,20):[];if(!unique.length)return;const{error}=await supabase.storage.from('message-attachments').remove(unique);if(error)throw userFacingRpcError(error);}
export async function getMessageAttachmentUrl(path:string,expiresIn=900){const normalized=safeStoragePath(path);const ttl=boundedInt(expiresIn,900,60,3600);const{data,error}=await supabase.storage.from('message-attachments').createSignedUrl(normalized,ttl);if(error)throw userFacingRpcError(error);const signedUrl=typeof data?.signedUrl==='string'?data.signedUrl.trim():'';if(!signedUrl)throw new Error('Ek dosya bağlantısı oluşturulamadı.');let parsed:URL;try{parsed=new URL(signedUrl);}catch{throw new Error('Ek dosya bağlantısı doğrulanamadı.');}if(parsed.protocol!=='https:')throw new Error('Ek dosya bağlantısı güvenli değil.');return parsed.toString();}
export function attachmentDisplayName(path:string){const normalized=safeStoragePath(path);const last=normalized.split('/').pop();if(!last)throw new Error('Ek dosya adı doğrulanamadı.');const index=last.indexOf('_');return index>=0?last.slice(index+1):last;}
