import React,{useEffect,useMemo,useRef,useState}from'react';
import{ArrowLeft,FileText,Image as ImageIcon,Paperclip,RefreshCw,Send,X}from'lucide-react';
import{attachmentDisplayName,getConversationMessages,getMessageAttachmentUrl,listMyConversations,markConversationRead,removeUnusedMessageAttachments,sendConversationMessage,setConversationOpenState,uploadMessageAttachment}from'./messagesApi';
import{EmptyState,ErrorState,LoadingState,Panel}from'./ui';

type DraftFile={file:File;id:string};
const allowedAccept='image/jpeg,image/png,image/webp,image/avif,application/pdf';

export default function MessagesPanel({initialConversationId}:{initialConversationId?:string|null}){
 const[conversations,setConversations]=useState<any[]>([]);const[selectedId,setSelectedId]=useState(initialConversationId||'');const[messages,setMessages]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[threadLoading,setThreadLoading]=useState(false);const[error,setError]=useState('');const[body,setBody]=useState('');const[files,setFiles]=useState<DraftFile[]>([]);const[sending,setSending]=useState(false);const[status,setStatus]=useState('');const listTimer=useRef<number|null>(null);const threadTimer=useRef<number|null>(null);const endRef=useRef<HTMLDivElement>(null);
 const selected=useMemo(()=>conversations.find(item=>item.id===selectedId)||null,[conversations,selectedId]);
 async function loadList(silent=false){try{if(!silent)setLoading(true);setError('');const rows=await listMyConversations();setConversations(rows);if(initialConversationId&&rows.some((row:any)=>row.id===initialConversationId))setSelectedId(current=>current||initialConversationId);}catch(e:any){if(!silent)setError(e?.message||'Konuşmalar yüklenemedi.');}finally{if(!silent)setLoading(false);}}
 async function loadThread(id:string,silent=false){if(!id)return;try{if(!silent)setThreadLoading(true);setError('');const rows=await getConversationMessages(id,100,null);setMessages(rows);await markConversationRead(id);setConversations(current=>current.map(item=>item.id===id?{...item,unreadCount:0}:item));if(!silent)setTimeout(()=>endRef.current?.scrollIntoView({block:'end'}),30);}catch(e:any){if(!silent)setError(e?.message||'Mesajlar yüklenemedi.');}finally{if(!silent)setThreadLoading(false);}}
 useEffect(()=>{void loadList();return()=>{if(listTimer.current)window.clearInterval(listTimer.current);if(threadTimer.current)window.clearInterval(threadTimer.current);};},[]);
 useEffect(()=>{if(listTimer.current)window.clearInterval(listTimer.current);listTimer.current=window.setInterval(()=>void loadList(true),30000);return()=>{if(listTimer.current)window.clearInterval(listTimer.current);};},[]);
 useEffect(()=>{if(!selectedId){setMessages([]);return;}void loadThread(selectedId);if(threadTimer.current)window.clearInterval(threadTimer.current);threadTimer.current=window.setInterval(()=>void loadThread(selectedId,true),15000);return()=>{if(threadTimer.current)window.clearInterval(threadTimer.current);};},[selectedId]);
 async function send(){if(!selectedId||sending)return;const trimmed=body.trim();if(!trimmed&&!files.length){setError('Mesaj veya ek dosya ekleyin.');return;}if(trimmed.length>5000){setError('Mesaj en fazla 5000 karakter olabilir.');return;}if(files.length>5){setError('Bir mesajda en fazla 5 ek dosya olabilir.');return;}const uploaded:string[]=[];try{setSending(true);setError('');setStatus('Ek dosyalar hazırlanıyor…');for(const item of files){uploaded.push(await uploadMessageAttachment(selectedId,item.file));}const text=trimmed||'Ek dosya gönderildi.';const imageOnly=files.length>0&&files.every(item=>item.file.type.startsWith('image/'));setStatus('Mesaj gönderiliyor…');await sendConversationMessage({conversationId:selectedId,body:text,attachmentPaths:uploaded,messageType:files.length?(imageOnly?'image':'file'):'text'});setBody('');setFiles([]);setStatus('Mesaj gönderildi.');await Promise.all([loadThread(selectedId),loadList(true)]);}catch(e:any){if(uploaded.length)await removeUnusedMessageAttachments(uploaded).catch(()=>{});setError(e?.message||'Mesaj gönderilemedi.');setStatus('');}finally{setSending(false);}}
 async function toggleOpen(){if(!selected)return;try{setError('');await setConversationOpenState(selected.id,selected.status==='closed');await loadList(true);await loadThread(selected.id,true);}catch(e:any){setError(e?.message||'Konuşma durumu değiştirilemedi.');}}
 function addFiles(fileList:FileList|null){if(!fileList)return;setError('');const incoming=Array.from(fileList);if(files.length+incoming.length>5){setError('Bir mesajda en fazla 5 ek dosya olabilir.');return;}for(const file of incoming){if(file.size<=0||file.size>20*1024*1024){setError('Her ek dosya en fazla 20 MB olabilir.');return;}if(!['image/jpeg','image/png','image/webp','image/avif','application/pdf'].includes(file.type)){setError('Ek dosya JPEG, PNG, WebP, AVIF veya PDF olmalıdır.');return;}}setFiles(current=>[...current,...incoming.map(file=>({file,id:crypto.randomUUID()}))]);}
 async function openAttachment(path:string){try{setError('');const url=await getMessageAttachmentUrl(path);window.open(url,'_blank','noopener,noreferrer');}catch(e:any){setError(e?.message||'Ek dosya açılamadı.');}}
 if(loading)return<LoadingState label="Konuşmalar yükleniyor"/>;
 return<Panel title="Mesajlarım" description="Golden Oremar destek ve üretici konuşmalarınızı güvenli biçimde yönetin.">
  {error?<ErrorState message={error} onRetry={()=>selectedId?loadThread(selectedId):loadList()}/>:null}
  {!selectedId?<>
   <div className="mb-3 flex items-center justify-between gap-3"><div className="text-sm text-gray-500">{conversations.length} konuşma</div><button onClick={()=>void loadList()} className="min-h-11 rounded-xl border px-4 font-semibold"><RefreshCw className="mr-2 inline h-4 w-4"/>Yenile</button></div>
   {!conversations.length?<EmptyState title="Henüz konuşmanız yok" body="Destek veya üreticiyle başlatılan güvenli konuşmalar burada görünecek."/>:<div className="space-y-2">{conversations.map((item:any)=><button key={item.id} onClick={()=>setSelectedId(item.id)} className={`min-h-16 w-full rounded-xl border p-4 text-left ${Number(item.unreadCount||0)>0?'border-brand-gold/50 bg-brand-gold/5':''}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="font-bold">{item.title||'Konuşma'}</div><div className="mt-1 truncate text-sm text-gray-500">{item.subject}</div><div className="mt-1 line-clamp-1 text-sm text-gray-600 dark:text-gray-300">{item.lastMessage||'Henüz mesaj yok'}</div></div><div className="shrink-0 text-right">{Number(item.unreadCount||0)>0?<span className="inline-grid min-h-6 min-w-6 place-items-center rounded-full bg-brand-gold px-1 text-xs font-bold text-white">{item.unreadCount}</span>:null}<div className="mt-2 text-xs text-gray-400">{formatDate(item.lastMessageAt||item.updatedAt)}</div></div></div></button>)}</div>}
  </>:<div className="space-y-4">
   <div className="flex items-start justify-between gap-3"><button onClick={()=>setSelectedId('')} className="min-h-11 rounded-xl border px-4 font-semibold"><ArrowLeft className="mr-2 inline h-4 w-4"/>Konuşmalar</button><button onClick={()=>void loadThread(selectedId)} className="min-h-11 rounded-xl border px-3" aria-label="Mesajları yenile"><RefreshCw className="h-4 w-4"/></button></div>
   <div className="rounded-xl border p-4"><div className="font-bold">{selected?.title||'Konuşma'}</div><div className="mt-1 text-sm text-gray-500">{selected?.subject}</div><div className="mt-2 flex items-center justify-between gap-3"><span className={`text-xs font-semibold ${selected?.status==='closed'?'text-gray-500':'text-green-700'}`}>{selected?.status==='closed'?'Kapalı':'Açık'}</span><button onClick={()=>void toggleOpen()} className="min-h-11 rounded-lg border px-3 text-sm font-semibold">{selected?.status==='closed'?'Konuşmayı yeniden aç':'Konuşmayı kapat'}</button></div></div>
   {threadLoading?<LoadingState label="Mesajlar yükleniyor"/>:<div className="max-h-[52vh] space-y-3 overflow-y-auto rounded-2xl border bg-gray-50 p-3 dark:bg-gray-950" aria-live="polite">{messages.length?messages.map((message:any)=><article key={message.id} className={`max-w-[88%] rounded-2xl p-3 ${message.isMine?'ml-auto bg-brand-green text-white':'mr-auto bg-white text-gray-900 dark:bg-gray-800 dark:text-white'}`}><div className="text-xs font-semibold opacity-75">{message.isMine?'Siz':message.senderName}</div><p className="mt-1 whitespace-pre-wrap break-words text-sm leading-6">{message.body}</p>{message.attachmentPaths?.length?<div className="mt-2 space-y-1">{message.attachmentPaths.map((path:string,index:number)=><button key={path} onClick={()=>void openAttachment(path)} className={`flex min-h-11 w-full items-center gap-2 rounded-lg border px-3 text-left text-xs font-semibold ${message.isMine?'border-white/30':'border-gray-200 dark:border-gray-700'}`}>{isImagePath(path)?<ImageIcon className="h-4 w-4"/>:<FileText className="h-4 w-4"/>}<span className="min-w-0 flex-1 truncate">{attachmentDisplayName(path)||`Ek ${index+1}`}</span></button>)}</div>:null}<div className="mt-2 text-[11px] opacity-60">{formatDate(message.createdAt)}</div></article>):<div className="p-6 text-center text-sm text-gray-500">Henüz mesaj yok.</div>}<div ref={endRef}/></div>}
   {selected?.status==='closed'?<div role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Bu konuşma kapalı. Yeni mesaj göndermek için yeniden açın.</div>:<div className="rounded-2xl border p-4"><label className="block"><span className="text-sm font-semibold">Mesajınız</span><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={5000} rows={4} className="mt-1 w-full rounded-xl border bg-transparent p-3" placeholder="Mesajınızı yazın…"/><span className="mt-1 block text-xs text-gray-500">{body.length}/5000</span></label><div className="mt-3 flex flex-wrap items-center gap-2"><label className="inline-flex min-h-11 cursor-pointer items-center rounded-xl border px-4 font-semibold"><Paperclip className="mr-2 h-4 w-4"/>Dosya ekle<input type="file" multiple accept={allowedAccept} className="sr-only" onChange={e=>{addFiles(e.target.files);e.currentTarget.value='';}}/></label><span className="text-xs text-gray-500">En fazla 5 dosya • 20 MB/dosya</span></div>{files.length?<ul className="mt-3 space-y-2">{files.map(item=><li key={item.id} className="flex items-center justify-between gap-3 rounded-lg bg-gray-50 p-2 dark:bg-gray-800"><span className="min-w-0 truncate text-sm">{item.file.name}</span><button onClick={()=>setFiles(current=>current.filter(file=>file.id!==item.id))} className="min-h-11 rounded-lg border px-3" aria-label={`${item.file.name} dosyasını kaldır`}><X className="h-4 w-4"/></button></li>)}</ul>:null}<div aria-live="polite" className="mt-2 min-h-5 text-xs text-brand-green">{status}</div><button onClick={()=>void send()} disabled={sending} className="mt-2 min-h-12 w-full rounded-xl bg-brand-green px-4 font-bold text-white disabled:opacity-50"><Send className="mr-2 inline h-4 w-4"/>{sending?'Gönderiliyor…':'Mesajı gönder'}</button></div>}
  </div>}
 </Panel>;
}
function formatDate(value?:string|null){if(!value)return'';try{return new Intl.DateTimeFormat('tr-TR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value));}catch{return value;}}
function isImagePath(path:string){return/\.(jpe?g|png|webp|avif)$/i.test(path);}
