import React,{useEffect,useState}from'react';
import{ExternalLink,RotateCcw}from'lucide-react';
import{cancelOrder,getOrderDetail,listOrders}from'./api';
import{EmptyState,ErrorState,LoadingState,Money,Panel}from'./ui';
import ReturnRequestDialog from'./ReturnRequestDialog';
import ReturnDetailDialog from'./ReturnDetailDialog';
import{useDialogA11y}from'./useDialogA11y';

const PAGE_SIZE=20;
const statusText:Record<string,string>={pending_payment:'Ödeme bekleniyor',confirmed:'Onaylandı',preparing:'Hazırlanıyor',partially_shipped:'Kısmen gönderildi',shipped:'Kargoda',delivered:'Teslim edildi',completed:'Tamamlandı',cancelled:'İptal edildi'};
const returnStatusText:Record<string,string>={requested:'Talep alındı',under_review:'İnceleniyor',approved:'Onaylandı',in_transit:'İade kargoda',received:'İade teslim alındı',rejected:'Reddedildi',refunded:'Geri ödeme yapıldı',closed:'Kapandı'};
const paymentText:Record<string,string>={pending:'Bekliyor',authorized:'Yetkilendirildi',captured:'Ödendi',partially_refunded:'Kısmi geri ödeme',refunded:'Geri ödendi',failed:'Başarısız'};
function verifiedCount(value:unknown){const parsed=Number(value);return Number.isSafeInteger(parsed)&&parsed>=0?parsed:null;}
function negativeMinor(value:unknown){const parsed=Number(value);return Number.isSafeInteger(parsed)?-parsed:Number.NaN;}
function orderKey(item:any,index:number){const id=String(item?.id||'').trim();return id?`id:${id}`:`fallback:${String(item?.orderNumber||'')}|${index}`;}

export default function OrdersPanel({initialOrderId}:{initialOrderId?:string|null}){
 const[page,setPage]=useState<any>(null);const[detail,setDetail]=useState<any>(null);const[error,setError]=useState('');const[listStatus,setListStatus]=useState('');const[loading,setLoading]=useState(true);const[loadingMore,setLoadingMore]=useState(false);const[openingId,setOpeningId]=useState<string|null>(null);const[detailError,setDetailError]=useState('');const[detailStatus,setDetailStatus]=useState('');const[returnOrderId,setReturnOrderId]=useState<string|null>(null);const[returnDetailId,setReturnDetailId]=useState<string|null>(null);const[cancelCandidate,setCancelCandidate]=useState<any>(null);const[cancelBusy,setCancelBusy]=useState(false);
 const nestedOpen=Boolean(returnOrderId||returnDetailId||cancelCandidate);
 const orderDialogRef=useDialogA11y(()=>setDetail(null),Boolean(detail)&&!nestedOpen);
 const cancelDialogRef=useDialogA11y(()=>{if(!cancelBusy)setCancelCandidate(null);},Boolean(cancelCandidate));

 async function load(reset=true){
  const currentItems=Array.isArray(page?.items)?page.items:[];const offset=reset?0:currentItems.length;
  try{
   if(reset)setLoading(true);else setLoadingMore(true);
   setError('');
   const next=await listOrders(PAGE_SIZE,offset);const nextItems=Array.isArray(next?.items)?next.items:[];
   setPage((previous:any)=>{
    if(reset||!previous)return{...next,items:nextItems};
    const previousItems=Array.isArray(previous?.items)?previous.items:[];const unique=new Map<string,any>();
    previousItems.forEach((item:any,index:number)=>unique.set(orderKey(item,index),item));
    nextItems.forEach((item:any,index:number)=>unique.set(orderKey(item,previousItems.length+index),item));
    return {...next,offset:0,items:Array.from(unique.values())};
   });
  }catch(e:any){setError(e?.message||'Siparişler yüklenemedi.');}
  finally{if(reset)setLoading(false);else setLoadingMore(false);}
 }
 useEffect(()=>{void load(true);},[]);
 useEffect(()=>{const id=String(initialOrderId||'').trim();if(id)void open(id);},[initialOrderId]);
 async function open(id:string){const normalized=String(id||'').trim();if(!normalized||openingId)return;try{setOpeningId(normalized);setError('');setListStatus('');setDetailError('');setDetailStatus('');setDetail(await getOrderDetail(normalized));}catch(e:any){setError(e?.message||'Sipariş detayı yüklenemedi.');}finally{setOpeningId(null);}}
 async function refreshDetail(id:string){try{setDetailError('');setDetailStatus('');setDetail(await getOrderDetail(id));await load(true);setDetailStatus('Sipariş detayı güncellendi.');}catch(e:any){setDetailError(e?.message||'Sipariş detayı yenilenemedi.');}}
 async function confirmCancel(){const id=String(cancelCandidate?.id||'').trim();if(!id||cancelBusy)return;try{setCancelBusy(true);setDetailError('');setDetailStatus('');await cancelOrder(id);setCancelCandidate(null);setDetail(null);await load(true);setListStatus('Sipariş iptal edildi.');}catch(e:any){setCancelCandidate(null);setDetailError(e?.message||'Sipariş iptal edilemedi.');}finally{setCancelBusy(false);}}
 if(loading)return<LoadingState label="Siparişler yükleniyor"/>;
 const items=Array.isArray(page?.items)?page.items:[];const total=verifiedCount(page?.total);const hasMore=total!==null&&items.length<total;
 const returns=Array.isArray(detail?.returns)?detail.returns:[];const activeReturn=returns.find((r:any)=>['requested','under_review','approved','in_transit','received'].includes(r?.status));
 return<Panel title="Siparişlerim" description="Sipariş, ödeme, kargo, iade ve geri ödeme durumlarını tek yerden izleyin.">
  {error?<ErrorState message={error} onRetry={()=>void load(true)}/>:null}
  {listStatus?<div role="status" aria-live="polite" className="mb-3 rounded-xl bg-green-50 p-3 text-sm text-green-800 dark:bg-green-950/30 dark:text-green-200">{listStatus}</div>:null}
  <div className="sr-only" aria-live="polite">{openingId?'Sipariş detayı yükleniyor.':loadingMore?'Daha fazla sipariş yükleniyor.':''}</div>
  {!items.length?<EmptyState title="Henüz sipariş yok" body="Sipariş verdiğinizde tüm durum geçmişi burada görünecek."/>:<>
   <div className="mb-3 text-sm text-gray-500">{items.length}{total!==null?` / ${total}`:''} sipariş gösteriliyor{total===null?' • Toplam sayı doğrulanamadı':''}</div>
   <div className="space-y-3">{items.map((o:any,index:number)=>{const id=String(o?.id||'').trim();const itemCount=verifiedCount(o?.itemCount);const orderNumber=String(o?.orderNumber||'').trim()||'Sipariş numarası doğrulanamadı';const status=String(o?.status||'').trim();return <button type="button" key={orderKey(o,index)} disabled={!id||Boolean(openingId)} aria-busy={Boolean(id)&&openingId===id} onClick={()=>void open(id)} className="min-h-14 w-full rounded-xl border border-gray-200 p-4 text-left disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold dark:border-gray-700"><div className="flex justify-between gap-3"><div><div className="font-bold">{orderNumber}{o?.gift?<span className="text-xs text-brand-gold"> • Hediye</span>:null}</div><div className="mt-1 text-sm text-gray-500">{openingId===id?'Detay yükleniyor…':`${statusText[status]||status||'Durum doğrulanamadı'} • ${itemCount===null?'Ürün sayısı doğrulanamadı':`${itemCount} ürün`}`}</div>{o?.trackingNumber?<div className="mt-1 text-xs text-gray-500">Takip: {o.trackingNumber}</div>:null}{!id?<div className="mt-1 text-xs text-red-700 dark:text-red-300">Sipariş kimliği doğrulanamadı</div>:null}</div><div className="font-bold"><Money minor={o?.totalMinor} currency={o?.currency}/></div></div></button>;})}</div>
   {hasMore?<div className="mt-5 flex justify-center"><button type="button" disabled={loadingMore} onClick={()=>void load(false)} className="min-h-11 rounded-xl border border-brand-green px-5 font-bold text-brand-green disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold dark:border-brand-gold dark:text-brand-gold">{loadingMore?'Yükleniyor…':'Daha fazla sipariş göster'}</button></div>:null}
  </>}

  {detail?<div role="dialog" aria-modal="true" aria-labelledby="order-detail-title" className="fixed inset-0 z-50 overflow-y-auto bg-black/60 p-4"><div ref={orderDialogRef} tabIndex={-1} className="mx-auto mt-6 max-w-2xl rounded-2xl bg-white p-5 outline-none dark:bg-gray-900">
   <div className="flex items-start justify-between gap-3"><div><h3 id="order-detail-title" className="text-xl font-bold">{String(detail?.orderNumber||'').trim()||'Sipariş detayı'}</h3><p className="text-sm text-gray-500">{statusText[String(detail?.status||'')]||String(detail?.status||'').trim()||'Durum doğrulanamadı'}</p><p className="mt-1 text-xs text-gray-500">Ödeme: {paymentText[String(detail?.paymentStatus||'')]||String(detail?.paymentStatus||'').trim()||'Durum doğrulanamadı'}</p></div><button type="button" onClick={()=>setDetail(null)} aria-label="Sipariş detayını kapat" className="min-h-11 rounded-lg border px-4 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">Kapat</button></div>
   {detailError?<div className="mt-4"><ErrorState message={detailError}/></div>:null}
   {detailStatus?<div role="status" aria-live="polite" className="mt-4 rounded-xl bg-green-50 p-3 text-sm text-green-800 dark:bg-green-950/30 dark:text-green-200">{detailStatus}</div>:null}

   <section className="mt-5" aria-labelledby="order-items-title"><h4 id="order-items-title" className="font-bold">Ürünler</h4><div className="mt-2 space-y-3">{Array.isArray(detail?.items)&&detail.items.length?detail.items.map((i:any,index:number)=><div key={String(i?.id||'').trim()||`item-${index}`} className="rounded-xl border p-3"><div className="font-semibold">{String(i?.productName||'').trim()||'Ürün bilgisi doğrulanamadı'}</div><div className="text-sm text-gray-500">{String(i?.variantName||'').trim()||'Standart'} • {verifiedCount(i?.quantity)===null?'Adet doğrulanamadı':`${verifiedCount(i?.quantity)} adet`}</div><div className="mt-1 font-bold"><Money minor={i?.lineTotalMinor} currency={detail?.currency}/></div></div>):<div className="rounded-xl border border-dashed p-4 text-sm text-gray-500">Ürün satırları doğrulanamadı.</div>}</div></section>

   {detail?.gift?<div className="mt-5 rounded-xl border border-brand-gold/30 bg-brand-gold/5 p-4"><div className="font-bold">Hediye bilgisi</div><p className="mt-1 text-sm">Alıcı: {String(detail.gift?.recipientName||'').trim()||'Alıcı bilgisi doğrulanamadı'}</p>{detail.gift?.message?<p className="mt-2 text-sm italic">“{detail.gift.message}”</p>:null}</div>:null}

   {Array.isArray(detail?.shipments)&&detail.shipments.length?<section className="mt-5" aria-labelledby="shipments-title"><h4 id="shipments-title" className="font-bold">Kargo</h4>{detail.shipments.map((s:any,index:number)=><div key={String(s?.id||'').trim()||`shipment-${index}`} className="mt-2 rounded-xl border p-3 text-sm"><div>{String(s?.carrier||'').trim()||'Kargo firması doğrulanamadı'} • {String(s?.status||'').trim()||'Durum doğrulanamadı'}</div>{s?.trackingNumber?<div className="mt-1">Takip: {s.trackingNumber}</div>:null}{safeUrl(s?.trackingUrl)?<a href={safeUrl(s.trackingUrl)} target="_blank" rel="noopener noreferrer" className="mt-2 inline-flex min-h-11 items-center font-semibold text-brand-green">Kargoyu takip et<ExternalLink aria-hidden="true" className="ml-2 h-4 w-4"/></a>:null}</div>)}</section>:null}

   {Array.isArray(detail?.statusHistory)&&detail.statusHistory.length?<section className="mt-5" aria-labelledby="history-title"><h4 id="history-title" className="font-bold">Sipariş geçmişi</h4><ol className="mt-2 space-y-2">{detail.statusHistory.map((h:any,index:number)=><li key={`${String(h?.at||'')}-${index}`} className="rounded-xl border p-3"><div className="text-sm font-semibold">{statusText[String(h?.to||'')]||String(h?.to||'').trim()||'Durum doğrulanamadı'}</div><div className="text-xs text-gray-500">{formatDate(h?.at)}</div>{h?.note?<div className="mt-1 text-sm">{h.note}</div>:null}</li>)}</ol></section>:null}

   {returns.length?<section className="mt-5" aria-labelledby="returns-title"><h4 id="returns-title" className="font-bold">İade talepleri</h4><div className="mt-2 space-y-2">{returns.map((r:any,index:number)=>{const returnId=String(r?.id||'').trim();return <button type="button" key={returnId||`return-${index}`} disabled={!returnId} onClick={()=>setReturnDetailId(returnId)} className="min-h-14 w-full rounded-xl border p-3 text-left disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><div className="flex justify-between gap-3"><div><div className="font-semibold">{String(r?.returnNumber||'').trim()||'İade numarası doğrulanamadı'}</div><div className="text-sm text-gray-500">{returnStatusText[String(r?.status||'')]||String(r?.status||'').trim()||'Durum doğrulanamadı'} • {formatDate(r?.requestedAt)}</div></div><span className="font-semibold text-brand-green">Detay</span></div>{r?.resolutionNote?<div className="mt-2 text-sm">{r.resolutionNote}</div>:null}</button>;})}</div></section>:null}

   {Array.isArray(detail?.refunds)&&detail.refunds.length?<section className="mt-5" aria-labelledby="refunds-title"><h4 id="refunds-title" className="font-bold">Geri ödemeler</h4><div className="mt-2 space-y-2">{detail.refunds.map((r:any,index:number)=><div key={String(r?.id||'').trim()||`refund-${index}`} className="rounded-xl border p-3"><div className="flex justify-between gap-3"><span className="font-semibold">{String(r?.status||'').trim()||'Durum doğrulanamadı'}</span><Money minor={r?.amountMinor} currency={r?.currency}/></div>{r?.processedAt?<div className="mt-1 text-xs text-gray-500">{formatDate(r.processedAt)}</div>:null}</div>)}</div></section>:null}

   <div className="mt-5 rounded-xl bg-gray-50 p-4 dark:bg-gray-800"><div className="flex justify-between"><span>Ara toplam</span><Money minor={detail?.subtotalMinor} currency={detail?.currency}/></div><div className="mt-1 flex justify-between"><span>İndirim</span><Money minor={negativeMinor(detail?.discountMinor)} currency={detail?.currency}/></div><div className="mt-1 flex justify-between"><span>Kargo</span><Money minor={detail?.shippingMinor} currency={detail?.currency}/></div><div className="mt-2 flex justify-between border-t pt-2 font-bold"><span>Toplam</span><Money minor={detail?.totalMinor} currency={detail?.currency}/></div></div>

   {detail?.status==='pending_payment'?<button type="button" disabled={!String(detail?.id||'').trim()} onClick={()=>{setDetailError('');setDetailStatus('');setCancelCandidate({id:detail.id,orderNumber:detail.orderNumber});}} className="mt-5 min-h-11 w-full rounded-xl border border-red-300 font-bold text-red-700 disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500 dark:text-red-300">Siparişi iptal et</button>:null}
   {['delivered','completed'].includes(detail?.status)?<div className="mt-4">{activeReturn?<div role="status" className="rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900 dark:bg-amber-950/20 dark:text-amber-100">Açık iade talebi: <button type="button" disabled={!String(activeReturn?.id||'').trim()} onClick={()=>setReturnDetailId(String(activeReturn.id))} className="min-h-11 font-bold underline">{String(activeReturn?.returnNumber||'').trim()||'İade'} - {returnStatusText[String(activeReturn?.status||'')]||String(activeReturn?.status||'').trim()||'Durum doğrulanamadı'}</button></div>:<button type="button" disabled={!String(detail?.id||'').trim()} onClick={()=>setReturnOrderId(String(detail.id))} className="min-h-12 w-full rounded-xl border border-brand-green font-bold text-brand-green disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><RotateCcw aria-hidden="true" className="mr-2 inline h-4 w-4"/>İade / sorun bildir</button>}</div>:null}
  </div></div>:null}

  {cancelCandidate?<div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/60 p-4"><div ref={cancelDialogRef} role="alertdialog" aria-modal="true" aria-labelledby="cancel-order-title" aria-describedby="cancel-order-description" tabIndex={-1} className="w-full max-w-md rounded-2xl bg-white p-5 text-brand-text shadow-xl outline-none dark:bg-gray-900"><h3 id="cancel-order-title" className="text-lg font-bold">Siparişi iptal etmek istiyor musunuz?</h3><p id="cancel-order-description" className="mt-2 text-sm text-gray-600 dark:text-gray-300">{String(cancelCandidate?.orderNumber||'').trim()||'Bu'} ödeme bekleyen sipariş iptal edilecek. İşlem yalnız backend izin veriyorsa tamamlanır ve geri alınamaz.</p><div aria-live="polite" className="sr-only">{cancelBusy?'Sipariş iptal ediliyor.':''}</div><div className="mt-5 grid grid-cols-2 gap-3"><button type="button" disabled={cancelBusy} onClick={()=>setCancelCandidate(null)} className="min-h-11 rounded-xl border font-semibold disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">Vazgeç</button><button type="button" disabled={cancelBusy} onClick={()=>void confirmCancel()} className="min-h-11 rounded-xl bg-red-700 font-bold text-white disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500">{cancelBusy?'İptal ediliyor…':'Siparişi İptal Et'}</button></div></div></div>:null}

  {returnOrderId?<ReturnRequestDialog orderId={returnOrderId} onClose={()=>setReturnOrderId(null)} onSubmitted={async()=>{const id=returnOrderId;setReturnOrderId(null);await refreshDetail(id);}}/>:null}
  {returnDetailId?<ReturnDetailDialog returnId={returnDetailId} onClose={()=>setReturnDetailId(null)}/>:null}
 </Panel>;
}
function safeUrl(value?:string|null){if(!value)return'';try{const url=new URL(value);return url.protocol==='https:'?url.toString():'';}catch{return'';}}
function formatDate(value?:string|null){const raw=String(value||'').trim();if(!raw)return'Tarih doğrulanamadı';const date=new Date(raw);if(Number.isNaN(date.getTime()))return'Tarih doğrulanamadı';try{return new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium',timeStyle:'short'}).format(date);}catch{return'Tarih doğrulanamadı';}}
