import React,{useEffect,useState}from'react';
import{MapPin,Upload}from'lucide-react';
import{catalogPublicUrl}from'./api';
import{Panel,ErrorState,LoadingState}from'./ui';
import{supabase}from'../../lib/supabase';

async function rpc(name:string,args:any={}){const{data,error}=await supabase.rpc(name,args);if(error)throw error;return data;}
async function uploadAsset(producerId:string,file:File,kind:'logo'|'cover'){
 const allowed=['image/jpeg','image/png','image/webp','image/avif'];if(!allowed.includes(file.type))throw new Error('Görsel JPEG, PNG, WebP veya AVIF olmalıdır.');
 if(file.size<=0||file.size>10*1024*1024)throw new Error('Görsel en fazla 10 MB olabilir.');
 const ext=file.type==='image/jpeg'?'jpg':file.type==='image/png'?'png':file.type==='image/avif'?'avif':'webp';
 const path=`${producerId}/profile/${kind}-${crypto.randomUUID()}.${ext}`;
 const{error}=await supabase.storage.from('catalog-public').upload(path,file,{contentType:file.type,upsert:false,cacheControl:'31536000'});if(error)throw error;return path;
}
export default function ProducerProfilePanel({onChanged}:{onChanged?:()=>void|Promise<void>}){
 const[profile,setProfile]=useState<any>(null);const[request,setRequest]=useState<any>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');
 const[form,setForm]=useState<any>({displayName:'',description:'',story:'',logoPath:'',coverPath:''});
 const[location,setLocation]=useState<any>({countryCode:'TR',province:'',district:'',village:'',villageIsCustom:false,reason:''});
 async function load(){try{setLoading(true);setError('');const[p,r]=await Promise.all([rpc('get_my_producer_profile_v1'),rpc('get_my_producer_location_change_v1')]);setProfile(p);setRequest(r);setForm({displayName:p.display_name||'',description:p.description||'',story:p.story||'',logoPath:p.logo_path||'',coverPath:p.cover_path||''});setLocation((v:any)=>({...v,countryCode:p.production_country_code||'TR',province:p.production_province||'',district:p.production_district||'',village:p.production_village||''}));}catch(e:any){setError(e?.message||'Üretici profili yüklenemedi.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function choose(file:File|undefined,kind:'logo'|'cover'){if(!file||!profile)return;let path='';try{setBusy(true);setError('');path=await uploadAsset(profile.id,file,kind);setForm((f:any)=>({...f,[kind==='logo'?'logoPath':'coverPath']:path}));}catch(e:any){if(path)await supabase.storage.from('catalog-public').remove([path]).catch(()=>{});setError(e?.message||'Görsel yüklenemedi.');}finally{setBusy(false);}}
 async function save(e:React.FormEvent){e.preventDefault();if(form.displayName.trim().length<2){setError('Üretici adı en az 2 karakter olmalıdır.');return;}try{setBusy(true);setError('');setMessage('');await rpc('update_my_producer_profile_v2',{p_display_name:form.displayName,p_description:form.description,p_story:form.story,p_logo_path:form.logoPath||null,p_cover_path:form.coverPath||null});setMessage('Mağaza profiliniz güncellendi.');await load();await onChanged?.();}catch(e:any){setError(e?.message||'Mağaza profili güncellenemedi.');}finally{setBusy(false);}}
 async function requestLocation(e:React.FormEvent){e.preventDefault();if(location.reason.trim().length<20){setError('Konum değişikliği nedenini en az 20 karakterle açıklayın.');return;}try{setBusy(true);setError('');setMessage('');await rpc('request_producer_location_change_v1',{p_country_code:location.countryCode,p_province:location.province,p_district:location.district,p_village:location.village,p_village_is_custom:!!location.villageIsCustom,p_latitude:null,p_longitude:null,p_reason:location.reason});setMessage('Köy/menşe değişikliği admin incelemesine gönderildi.');await load();}catch(e:any){setError(e?.message||'Konum değişikliği talebi gönderilemedi.');}finally{setBusy(false);}}
 if(loading)return<LoadingState label="Üretici profili yükleniyor"/>;
 if(!profile)return<ErrorState message={error||'Üretici profili bulunamadı.'} onRetry={load}/>;
 return<div className="space-y-5">{error?<ErrorState message={error}/>:null}{message?<div role="status" className="rounded-xl bg-green-50 p-3 text-sm text-green-800">{message}</div>:null}
 <Panel title="Mağaza Profilini Düzenle" description="Ad, açıklama, hikâye, logo ve kapak doğrudan güncellenebilir. Doğrulanmış köy/menşe ayrı incelemeye tabidir."><form onSubmit={save} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Asset label="Logo" path={form.logoPath} onFile={f=>choose(f,'logo')}/><Asset label="Kapak" path={form.coverPath} onFile={f=>choose(f,'cover')}/></div><label className="block"><span className="text-sm font-semibold">Mağaza/üretici adı</span><input value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})} className="mt-1 min-h-11 w-full rounded-xl border bg-transparent px-3"/></label><label className="block"><span className="text-sm font-semibold">Kısa açıklama</span><textarea maxLength={1200} rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="mt-1 w-full rounded-xl border bg-transparent p-3"/></label><label className="block"><span className="text-sm font-semibold">Üretici hikâyesi</span><textarea maxLength={5000} rows={6} value={form.story} onChange={e=>setForm({...form,story:e.target.value})} className="mt-1 w-full rounded-xl border bg-transparent p-3"/></label><button disabled={busy} className="min-h-11 w-full rounded-xl bg-brand-green font-bold text-white disabled:opacity-50">Mağaza profilini kaydet</button></form></Panel>
 <Panel title="Doğrulanmış Köy / Menşe" description="Bu bilgi müşteri güven rozetlerini etkilediği için satıcı tarafından doğrudan değiştirilemez."><div className="rounded-xl border p-4"><div className="font-bold"><MapPin className="mr-2 inline h-4 w-4"/>{profile.production_village||profile.production_location||'Yapılandırılmış köy kaydı yok'}</div>{profile.production_district||profile.production_province?<p className="mt-1 text-sm text-gray-500">{[profile.production_district,profile.production_province,profile.production_country_code].filter(Boolean).join(' / ')}</p>:null}</div>{request?.status==='pending'?<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Bekleyen konum değişikliği:</strong> {request.village}, {request.district}/{request.province}. Yönetim incelemesi bekleniyor.</div>:<form onSubmit={requestLocation} className="mt-4 space-y-3"><div className="grid gap-3 sm:grid-cols-2"><Field label="Ülke kodu"><input maxLength={2} value={location.countryCode} onChange={e=>setLocation({...location,countryCode:e.target.value.toUpperCase()})}/></Field><Field label="İl"><input value={location.province} onChange={e=>setLocation({...location,province:e.target.value})}/></Field><Field label="İlçe"><input value={location.district} onChange={e=>setLocation({...location,district:e.target.value})}/></Field><Field label="Köy / mezra"><input value={location.village} onChange={e=>setLocation({...location,village:e.target.value})}/></Field></div><label className="flex min-h-11 items-center gap-3 rounded-xl border p-3"><input type="checkbox" checked={location.villageIsCustom} onChange={e=>setLocation({...location,villageIsCustom:e.target.checked})} className="h-5 w-5"/><span>Köy/mezra adını listede olmadığı için manuel girdim</span></label><label className="block"><span className="text-sm font-semibold">Değişiklik nedeni</span><textarea rows={4} value={location.reason} onChange={e=>setLocation({...location,reason:e.target.value})} className="mt-1 w-full rounded-xl border bg-transparent p-3" placeholder="Taşınma, üretim yerinin değişmesi veya doğrulanmış kayıt düzeltmesi gibi nedeni açıklayın."/></label><button disabled={busy} className="min-h-11 w-full rounded-xl border border-brand-gold font-bold text-brand-gold disabled:opacity-50">Konum değişikliğini incelemeye gönder</button></form>}</Panel>
 </div>;
}
function Asset({label,path,onFile}:{label:string;path:string;onFile:(file?:File)=>void}){return<div className="rounded-xl border p-3"><div className="font-semibold">{label}</div>{path?<img src={catalogPublicUrl(path)} alt="" className="mt-2 h-32 w-full rounded-lg object-cover"/>:<div className="mt-2 grid h-24 place-items-center rounded-lg bg-gray-50 text-sm text-gray-400">Görsel yok</div>}<label className="mt-2 inline-flex min-h-11 cursor-pointer items-center rounded-lg border px-3 font-semibold"><Upload className="mr-2 h-4 w-4"/>Görsel seç<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" className="sr-only" onChange={e=>{onFile(e.target.files?.[0]);e.currentTarget.value='';}}/></label></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return<label className="block"><span className="text-sm font-semibold">{label}</span>{React.cloneElement(children as React.ReactElement<any>,{className:'mt-1 min-h-11 w-full rounded-xl border bg-transparent px-3'})}</label>}
