import React,{useEffect,useRef,useState}from'react';
import{FileText,Image as ImageIcon,Paperclip,Send,X}from'lucide-react';
import{getMyMessagePolicy,removeUnusedMessageAttachments,sendConversationMessage,startProducerOrderConversation,startProducerProductConversation,uploadMessageAttachment,type MyMessagePolicy,type StartedProducerConversation}from'./messagesApi';

type ProductContext={kind:'product';producerId:string;productId:string;productName:string};
type OrderContext={kind:'order';producerId:string;orderId:string;orderNumber:string;productName?:string|null};
type Props={context:ProductContext|OrderContext;onCancel:()=>void;onStarted:(result:StartedProducerConversation)=>void;className?:string};
type DraftFile={id:string;file:File};
let draftSequence=0;
function draftId(){if(typeof globalThis.crypto?.randomUUID==='function')return globalThis.crypto.randomUUID();draftSequence+=1;return`question-file-${Date.now()}-${draftSequence}`;}
function acceptedTypes(policy:MyMessagePolicy|null){const types:string[]=[];if(policy?.allowImages)types.push('image/jpeg','image/png','image/webp','image/avif');if(policy?.allowPdf)types.push('application/pdf');return types;}

export default function ProducerQuestionComposer({context,onCancel,onStarted,className=''}:Props){
 const[question,setQuestion]=useState('');const[files,setFiles]=useState<DraftFile[]>([]);const[policy,setPolicy]=useState<MyMessagePolicy|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[status,setStatus]=useState('');const[started,setStarted]=useState<StartedProducerConversation|null>(null);const inputRef=useRef<HTMLTextAreaElement>(null);
 useEffect(()=>{let active=true;window.setTimeout(()=>inputRef.current?.focus(),30);setQuestion('');setFiles([]);setError('');setStatus('');setStarted(null);setPolicy(null);getMyMessagePolicy().then(value=>{if(active)setPolicy(value);}).catch(()=>{if(active)setPolicy(null);});return()=>{active=false;};},[context.kind,context.producerId,context.kind==='product'?context.productId:context.orderId]);
 const title=context.kind==='product'?`${context.productName} hakkında soru sor`:`${context.orderNumber} siparişi hakkında soru sor`;
 const description=context.kind==='product'?'Sorunuz bu ürüne ve doğrulanmış üreticiye bağlanır. Yanıt Hesabım > Mesajlarım bölümüne düşer.':`Sorunuz bu siparişteki ilgili üreticiye bağlanır${context.productName?` - ${context.productName}`:''}. Yanıt Hesabım > Mesajlarım bölümüne düşer.`;
 const types=acceptedTypes(policy);const attachmentsReady=Boolean(policy?.allowAttachments&&policy.maxAttachments>0&&types.length);

 function addFiles(fileList:FileList|null){if(!fileList||busy||started)return;if(!policy){setError('Dosya ekleme bilgisi alınamadı. Sorunuzu metin olarak gönderebilirsiniz.');return;}if(!attachmentsReady){setError('Bu konuşmada dosya ekleme şu anda kullanılamıyor.');return;}setError('');const incoming=Array.from(fileList);if(files.length+incoming.length>policy.maxAttachments){setError(`Bir soruya en fazla ${policy.maxAttachments} dosya ekleyebilirsiniz.`);return;}for(const file of incoming){if(!types.includes(file.type)){setError('Bu dosya türü bu konuşmada kullanılamıyor.');return;}if(file.size<=0||file.size>policy.maxAttachmentMb*1024*1024){setError(`Her ek dosya boş olmamalı ve en fazla ${policy.maxAttachmentMb} MB olabilir.`);return;}}setFiles(current=>[...current,...incoming.map(file=>({id:draftId(),file}))]);}
 async function sendAttachments(result:StartedProducerConversation){if(!files.length)return true;const uploaded:string[]=[];try{setStatus('Ek dosyalar yükleniyor…');for(const item of files)uploaded.push(await uploadMessageAttachment(result.conversationId,item.file));const imageOnly=files.every(item=>item.file.type.startsWith('image/'));setStatus('Ek dosyalar mağazaya gönderiliyor…');await sendConversationMessage({conversationId:result.conversationId,body:'Soru ekleri',attachmentPaths:uploaded,messageType:imageOnly?'image':'file'});return true;}catch(e:unknown){if(uploaded.length)await removeUnusedMessageAttachments(uploaded).catch(()=>{});setStarted(result);setStatus('');setError('Sorunuz gönderildi ancak ek dosyalar gönderilemedi. Soruyu yeniden göndermeden ekleri tekrar deneyebilirsiniz.');return false;}}
 async function submit(){if(busy)return;if(started){try{setBusy(true);setError('');const ok=await sendAttachments(started);if(ok){const result=started;setQuestion('');setFiles([]);setStarted(null);setStatus('');onStarted(result);}}finally{setBusy(false);}return;}const message=question.trim();if(!message){setError('Sorunuzu yazın.');return;}if(message.length>5000){setError('Soru en fazla 5000 karakter olabilir.');return;}try{setBusy(true);setError('');setStatus('Soru gönderiliyor…');const result=context.kind==='product'?await startProducerProductConversation({producerId:context.producerId,productId:context.productId,productName:context.productName,message}):await startProducerOrderConversation({producerId:context.producerId,orderId:context.orderId,orderNumber:context.orderNumber,message});const ok=await sendAttachments(result);if(!ok)return;setQuestion('');setFiles([]);setStatus('');onStarted(result);}catch{setStatus('');setError('Sorunuz şu anda gönderilemedi. Lütfen yeniden deneyin.');}finally{setBusy(false);}}
 return<section aria-labelledby="producer-question-title" className={`rounded-2xl border border-brand-green/30 bg-brand-green/5 p-4 ${className}`}>
  <div className="flex items-start justify-between gap-3"><div><h3 id="producer-question-title" className="font-bold">{title}</h3><p className="mt-1 text-sm text-gray-500">{description}</p></div><button type="button" onClick={onCancel} disabled={busy} aria-label="Soru formunu kapat" className="min-h-11 rounded-lg border px-3 disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><X aria-hidden="true" className="h-4 w-4"/></button></div>
  {policy?.producerProtectionEnabled?<div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900 dark:border-amber-900/60 dark:bg-amber-950/30 dark:text-amber-100">Mağaza ile iletişim ve alışveriş Golden Oremar içinde tutulur. Platform dışına yönlendiren içerikler güvenlik kuralları gereği engellenebilir.</div>:null}
  {error?<div role="alert" className="mt-3 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200">{error}</div>:null}{status?<div role="status" aria-live="polite" className="mt-3 text-sm font-semibold text-brand-green dark:text-brand-gold">{status}</div>:null}
  <label className="mt-3 block"><span className="text-sm font-semibold">Sorunuz</span><textarea ref={inputRef} value={question} onChange={event=>setQuestion(event.target.value)} maxLength={5000} rows={4} disabled={busy||Boolean(started)} className="mt-1 w-full rounded-xl border bg-white p-3 disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold dark:bg-gray-900" placeholder="Ürün, teslimat, kullanım veya siparişiniz hakkında sorunuzu yazın."/><span className="mt-1 block text-xs text-gray-500">{question.length}/5000</span></label>
  <div className="mt-3"><label className={`inline-flex min-h-11 items-center rounded-xl border px-4 font-semibold focus-within:ring-2 focus-within:ring-brand-gold ${busy||started||!attachmentsReady?'cursor-not-allowed opacity-50':'cursor-pointer'}`}><Paperclip aria-hidden="true" className="mr-2 h-4 w-4"/>{attachmentsReady?'Görsel veya PDF ekle':'Dosya ekleme kapalı'}<input type="file" multiple accept={types.join(',')} disabled={busy||Boolean(started)||!attachmentsReady} className="sr-only" onChange={event=>{addFiles(event.target.files);event.currentTarget.value='';}}/></label>{policy?<span className="ml-2 text-xs text-gray-500">En fazla {policy.maxAttachments} dosya, {policy.maxAttachmentMb} MB/dosya</span>:<span className="ml-2 text-xs text-gray-500">Dosya ekleme bilgisi alınamadı</span>}</div>
  {files.length?<ul className="mt-3 space-y-2" aria-label="Soru ekleri">{files.map(item=><li key={item.id} className="flex items-center gap-3 rounded-xl border bg-white p-3 dark:bg-gray-900">{item.file.type.startsWith('image/')?<ImageIcon aria-hidden="true" className="h-4 w-4 shrink-0 text-brand-gold"/>:<FileText aria-hidden="true" className="h-4 w-4 shrink-0 text-brand-gold"/>}<span className="min-w-0 flex-1 truncate text-sm">{item.file.name}</span><button type="button" disabled={busy||Boolean(started)} onClick={()=>setFiles(current=>current.filter(file=>file.id!==item.id))} aria-label={`${item.file.name} ekini kaldır`} className="min-h-11 rounded-lg border px-3 disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><X aria-hidden="true" className="h-4 w-4"/></button></li>)}</ul>:null}
  <button type="button" onClick={()=>void submit()} disabled={busy||(!started&&!question.trim())} className="mt-3 min-h-12 w-full rounded-xl bg-brand-green px-4 font-bold text-white disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><Send aria-hidden="true" className="mr-2 inline h-4 w-4"/>{busy?(started?'Ekler yeniden gönderiliyor…':'Gönderiliyor…'):started?'Ekleri yeniden gönder':'Soruyu gönder'}</button>
 </section>;
}
