import React,{useEffect,useState}from'react';
import{ArrowLeft,ExternalLink,RefreshCw}from'lucide-react';
import{getMyReturnDetail,getReturnEvidenceSignedUrl}from'./returnsApi';
import{ErrorState,LoadingState,Money}from'./ui';
import{useDialogA11y}from'./useDialogA11y';

const statusLabels:Record<string,string>={requested:'Talep alındı',under_review:'İnceleniyor',approved:'Onaylandı',in_transit:'İade kargoda',received:'İade teslim alındı',rejected:'Reddedildi',refunded:'Geri ödeme yapıldı',closed:'Kapandı'};
const reasonLabels:Record<string,string>={damaged:'Ürün hasarlı geldi',wrong_item:'Yanlış ürün gönderildi',quality_issue:'Kalite / tazelik sorunu',missing_item:'Siparişte ürün eksik',changed_mind:'Fikrim değişti',delivery_issue:'Teslimat kaynaklı sorun',other:'Diğer'};
const refundStatusLabels:Record<string,string>={pending:'Bekliyor',processing:'İşleniyor',succeeded:'Tamamlandı',completed:'Tamamlandı',failed:'Başarısız',cancelled:'İptal edildi',refunded:'Geri ödendi'};
function verifiedPositiveCount(value:unknown){const parsed=Number(value);return Number.isSafeInteger(parsed)&&parsed>0?parsed:null;}
function normalizedId(value:unknown){return String(value||'').trim();}

export default function ReturnDetailDialog({returnId,onClose}:{returnId:string;onClose:()=>void}){
 const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[error,setError]=useState('');
 const dialogRef=useDialogA11y(onClose,!loading);const loadingDialogRef=useDialogA11y(onClose,loading);
 async function load(silent=false){try{if(silent)setRefreshing(true);else setLoading(true);setError('');const next=await getMyReturnDetail(returnId);setData(next&&typeof next==='object'&&!Array.isArray(next)?next:null);if(!next||typeof next!=='object'||Array.isArray(next))setError('İade detayı sunucudan doğrulanamadı.');}catch(e:any){setError(e?.message||'İade detayı yüklenemedi.');if(!silent)setData(null);}finally{if(silent)setRefreshing(false);else setLoading(false);}}
 useEffect(()=>{void load();},[returnId]);
 async function openEvidence(path:string){const normalized=String(path||'').trim();if(!normalized){setError('Kanıt dosyası yolu doğrulanamadı.');return;}try{setError('');const url=await getReturnEvidenceSignedUrl(normalized);window.open(url,'_blank','noopener,noreferrer');}catch(e:any){setError(e?.message||'Kanıt dosyası açılamadı.');}}
 if(loading)return<div role="dialog" aria-modal="true" aria-labelledby="return-detail-loading-title" className="fixed inset-0 z-[70] flex items-center justify-center bg-black/60 p-4"><div ref={loadingDialogRef} tabIndex={-1} className="w-full max-w-md rounded-2xl bg-white p-5 shadow-xl outline-none dark:bg-gray-900"><div className="flex items-start justify-between gap-3"><h3 id="return-detail-loading-title" className="text-lg font-bold">İade detayı</h3><button type="button" onClick={onClose} className="min-h-11 rounded-xl border px-4 font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">Geri</button></div><LoadingState label="İade detayı yükleniyor"/></div></div>;
 const items=Array.isArray(data?.items)?data.items:[];const refunds=Array.isArray(data?.refunds)?data.refunds:[];const status=String(data?.status||'').trim();const reason=String(data?.reasonCode||'').trim();
 return<div role="dialog" aria-modal="true" aria-labelledby="return-detail-title" className="fixed inset-0 z-[70] overflow-y-auto bg-black/60 p-4"><div ref={dialogRef} tabIndex={-1} aria-busy={refreshing} className="mx-auto mt-4 max-w-2xl rounded-2xl bg-white p-5 outline-none dark:bg-gray-900">
  <div className="flex items-start justify-between gap-3"><div><h3 id="return-detail-title" className="text-xl font-bold">{String(data?.returnNumber||'').trim()||'İade talebi'}</h3><p className={`mt-1 text-sm font-semibold ${statusLabels[status]?'text-brand-green':'text-red-700 dark:text-red-300'}`}>{statusLabels[status]||'İade durumu doğrulanamadı'}</p></div><div className="flex gap-2"><button type="button" disabled={refreshing} onClick={()=>void load(true)} className="grid min-h-11 min-w-11 place-items-center rounded-xl border px-3 disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold" aria-label="İade detayını yenile"><RefreshCw aria-hidden="true" className={`h-4 w-4 ${refreshing?'animate-spin':''}`}/></button><button type="button" onClick={onClose} disabled={refreshing} className="min-h-11 rounded-xl border px-4 font-semibold disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><ArrowLeft aria-hidden="true" className="mr-2 inline h-4 w-4"/>Geri</button></div></div>
  {error?<div className="mt-4"><ErrorState message={error} onRetry={refreshing?undefined:()=>void load(true)}/></div>:null}
  {data?<>
  <div className="mt-5 rounded-xl bg-gray-50 p-4 dark:bg-gray-800"><div className="text-sm text-gray-500">Neden</div><div className="font-semibold">{reasonLabels[reason]||'İade nedeni doğrulanamadı'}</div><p className="mt-2 whitespace-pre-wrap text-sm">{String(data?.customerMessage||'').trim()||'Müşteri açıklaması doğrulanamadı'}</p></div>
  {data?.reviewReason?<div className="mt-4 rounded-xl border border-red-200 p-4 dark:border-red-900"><div className="font-bold">İnceleme notu</div><p className="mt-1 text-sm">{data.reviewReason}</p></div>:null}
  {data?.resolutionNote?<div className="mt-4 rounded-xl border p-4"><div className="font-bold">Çözüm</div><p className="mt-1 text-sm">{data.resolutionNote}</p></div>:null}
  <div className="mt-5"><h4 className="font-bold">İade edilen ürünler</h4>{items.length?<div className="mt-2 space-y-3">{items.map((item:any,index:number)=>{const quantity=verifiedPositiveCount(item?.quantity);const productName=String(item?.productName||'').trim()||'Ürün bilgisi doğrulanamadı';const evidence=Array.isArray(item?.evidencePaths)?item.evidencePaths.map((path:any)=>String(path||'').trim()).filter(Boolean):[];return <article key={normalizedId(item?.id)||`return-item-${index}`} className="rounded-xl border p-4"><div className="font-semibold">{productName}</div><div className="text-sm text-gray-500">{String(item?.variantName||'').trim()||'Standart'} • {quantity===null?'Adet doğrulanamadı':`${quantity} adet`}</div>{item?.refundAmountMinor!=null?<div className="mt-2 font-bold"><Money minor={item.refundAmountMinor} currency={item?.currency}/></div>:null}{evidence.length?<div className="mt-3"><div className="text-sm font-semibold">Kanıt dosyaları</div><div className="mt-2 flex flex-wrap gap-2">{evidence.map((path:string,pathIndex:number)=><button type="button" key={`${path}-${pathIndex}`} onClick={()=>void openEvidence(path)} className="min-h-11 rounded-lg border px-3 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">Kanıt {pathIndex+1}<ExternalLink aria-hidden="true" className="ml-2 inline h-4 w-4"/></button>)}</div></div>:null}</article>;})}</div>:<div className="mt-2 rounded-xl border border-dashed p-4 text-sm text-gray-500">İade ürünleri doğrulanamadı veya bu kayıtta ürün satırı bulunmuyor.</div>}</div>
  {refunds.length?<div className="mt-5"><h4 className="font-bold">Geri ödeme</h4><div className="mt-2 space-y-2">{refunds.map((refund:any,index:number)=>{const refundStatus=String(refund?.status||'').trim();return <div key={normalizedId(refund?.id)||`refund-${index}`} className="rounded-xl border p-3"><div className="flex justify-between gap-3"><span className="font-semibold">{refundStatusLabels[refundStatus]||'Geri ödeme durumu doğrulanamadı'}</span><Money minor={refund?.amountMinor} currency={refund?.currency}/></div>{refund?.processedAt?<div className="mt-1 text-xs text-gray-500">{formatDate(refund.processedAt)}</div>:null}</div>;})}</div></div>:null}
  <div className="mt-5 text-xs text-gray-500">Talep: {formatDate(data?.requestedAt)}{data?.reviewedAt?` • İnceleme: ${formatDate(data.reviewedAt)}`:''}{data?.closedAt?` • Kapanış: ${formatDate(data.closedAt)}`:''}</div>
  </>:<div className="mt-5 rounded-xl border border-dashed p-4 text-sm text-gray-500">İade kaydı doğrulanamadı. Yeniden deneyin.</div>}
 </div></div>;
}
function formatDate(value?:string|null){const raw=String(value||'').trim();if(!raw)return'Tarih doğrulanamadı';const date=new Date(raw);if(Number.isNaN(date.getTime()))return'Tarih doğrulanamadı';try{return new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium',timeStyle:'short'}).format(date);}catch{return'Tarih doğrulanamadı';}}
