import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,FileImage,RefreshCw,Trash2,UploadCloud}from'lucide-react';
import{getOrderReturnOptions,removeReturnEvidence,requestCustomerReturnV3,uploadReturnEvidence}from'./returnsApi';
import{ErrorState,LoadingState,Money}from'./ui';
import{useDialogA11y}from'./useDialogA11y';

const reasonLabels:Record<string,string>={damaged:'Ürün hasarlı geldi',wrong_item:'Yanlış ürün gönderildi',quality_issue:'Kalite / tazelik sorunu',missing_item:'Siparişte ürün eksik',changed_mind:'Fikrim değişti',delivery_issue:'Teslimat kaynaklı sorun',other:'Diğer'};
const allowedTypes=['image/jpeg','image/png','image/webp','video/mp4'];
const maxFileSize=15*1024*1024;
type ItemState={selected:boolean;quantity:number;files:File[]};

export default function ReturnRequestDialog({orderId,onClose,onSubmitted}:{orderId:string;onClose:()=>void;onSubmitted:(result:any)=>void}){
 const dialogRef=useDialogA11y(onClose);
 const[options,setOptions]=useState<any>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[status,setStatus]=useState('');
 const[reason,setReason]=useState('');const[message,setMessage]=useState('');const[itemState,setItemState]=useState<Record<string,ItemState>>({});
 async function load(){try{setLoading(true);setError('');const data=await getOrderReturnOptions(orderId);setOptions(data);const next:Record<string,ItemState>={};(data?.items||[]).forEach((item:any)=>{next[item.orderItemId]={selected:false,quantity:Math.min(1,Number(item.remainingQuantity||0)),files:[]};});setItemState(next);}catch(e:any){setError(e?.message||'İade seçenekleri yüklenemedi.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[orderId]);
 const selectedItems=useMemo(()=>Object.entries(itemState).filter(([,v])=>v.selected),[itemState]);
 const totalFiles=useMemo(()=>Object.values(itemState).reduce((sum,v)=>sum+v.files.length,0),[itemState]);
 function patchItem(id:string,patch:Partial<ItemState>){setItemState(current=>({...current,[id]:{...current[id],...patch}}));}
 function addFiles(id:string,files:FileList|null){if(!files)return;setError('');const current=itemState[id]?.files||[];const incoming=Array.from(files);for(const file of incoming){if(!allowedTypes.includes(file.type)){setError('Kanıt dosyası JPEG, PNG, WebP veya MP4 olmalıdır.');return;}if(file.size<=0||file.size>maxFileSize){setError('Her kanıt dosyası en fazla 15 MB olabilir.');return;}}if(current.length+incoming.length>5){setError('Bir ürün için en fazla 5 kanıt dosyası ekleyebilirsiniz.');return;}if(totalFiles+incoming.length>15){setError('Bir iade talebinde toplam en fazla 15 kanıt dosyası olabilir.');return;}patchItem(id,{files:[...current,...incoming]});}
 function removeFile(id:string,index:number){patchItem(id,{files:(itemState[id]?.files||[]).filter((_,i)=>i!==index)});}
 async function submit(){if(!options?.canRequest){setError('Bu sipariş için şu anda yeni iade talebi oluşturulamıyor.');return;}if(!selectedItems.length){setError('İade etmek istediğiniz en az bir ürünü seçin.');return;}if(!reason){setError('İade nedenini seçin.');return;}const trimmed=message.trim();if(trimmed.length<10||trimmed.length>3000){setError('Açıklama 10 ile 3000 karakter arasında olmalıdır.');return;}const uploaded:string[]=[];try{setBusy(true);setError('');setStatus('Kanıt dosyaları hazırlanıyor…');const payload:any[]=[];for(const[orderItemId,state]of selectedItems){const item=(options.items||[]).find((x:any)=>x.orderItemId===orderItemId);const remaining=Number(item?.remainingQuantity||0);if(state.quantity<1||state.quantity>remaining)throw new Error(`${item?.productName||'Ürün'} için geçersiz iade adedi.`);const evidencePaths:string[]=[];for(const file of state.files){setStatus(`${file.name} yükleniyor…`);const path=await uploadReturnEvidence(orderId,file);uploaded.push(path);evidencePaths.push(path);}payload.push({orderItemId,quantity:state.quantity,evidencePaths});}setStatus('İade talebi oluşturuluyor…');const result=await requestCustomerReturnV3({orderId,items:payload,reasonCode:reason,message:trimmed});setStatus('İade talebiniz oluşturuldu.');onSubmitted(result);}catch(e:any){if(uploaded.length){await removeReturnEvidence(uploaded).catch(()=>{});}setError(e?.message||'İade talebi oluşturulamadı.');setStatus('');}finally{setBusy(false);}}
 if(loading)return<div role="dialog" aria-modal="true" aria-label="İade talebi"><LoadingState label="İade seçenekleri yükleniyor"/></div>;
 return<div role="dialog" aria-modal="true" aria-labelledby="return-title" className="fixed inset-0 z-[60] overflow-y-auto bg-black/60 p-4"><div ref={dialogRef} tabIndex={-1} className="mx-auto mt-4 max-w-2xl rounded-2xl bg-white p-5 shadow-xl outline-none dark:bg-gray-900">
  <div className="flex items-start justify-between gap-3"><div><h3 id="return-title" className="text-xl font-bold">İade talebi oluştur</h3><p className="mt-1 text-sm text-gray-500">{options?.orderNumber}</p></div><button onClick={onClose} disabled={busy} className="min-h-11 rounded-xl border px-4 font-semibold"><ArrowLeft className="mr-2 inline h-4 w-4"/>Geri</button></div>
  {error?<div className="mt-4"><ErrorState message={error} onRetry={load}/></div>:null}
  {!options?.eligibleStatus?<Notice>İade yalnız teslim edilmiş veya tamamlanmış siparişlerde açılabilir.</Notice>:null}{options?.activeReturnExists?<Notice>Bu sipariş için halen açık bir iade talebi var. Yeni talep, mevcut süreç kapanmadan oluşturulamaz.</Notice>:null}{options?.eligibleStatus&&!options?.activeReturnExists&&!options?.canRequest?<Notice>Bu siparişte iade edilebilir ürün adedi kalmamış.</Notice>:null}
  <fieldset className="mt-5 space-y-3" disabled={busy||!options?.canRequest}><legend className="mb-2 font-bold">İade edilecek ürünler</legend>{(options?.items||[]).map((item:any)=>{const state=itemState[item.orderItemId]||{selected:false,quantity:1,files:[]};const remaining=Number(item.remainingQuantity||0);return<div key={item.orderItemId} className={`rounded-xl border p-4 ${remaining<=0?'opacity-60':''}`}><label className="flex min-h-11 items-start gap-3"><input type="checkbox" className="mt-1 h-5 w-5" checked={state.selected} disabled={remaining<=0} onChange={e=>patchItem(item.orderItemId,{selected:e.target.checked})}/><span><span className="font-semibold">{item.productName}</span><span className="block text-sm text-gray-500">{item.variantName||'Standart'} • Satın alınan {item.purchasedQuantity} • Daha önce iade {item.returnedQuantity} • Kalan {remaining}</span><span className="mt-1 block text-sm font-semibold"><Money minor={item.lineTotalMinor} currency={item.currency}/></span></span></label>{state.selected&&remaining>0?<div className="mt-3 border-t pt-3"><label className="block"><span className="text-sm font-semibold">İade adedi</span><input type="number" min="1" max={remaining} value={state.quantity} onChange={e=>patchItem(item.orderItemId,{quantity:Number(e.target.value)})} className="mt-1 min-h-11 w-full rounded-xl border bg-transparent px-3"/></label><div className="mt-3"><label className="inline-flex min-h-11 cursor-pointer items-center rounded-xl border px-4 font-semibold"><UploadCloud className="mr-2 h-4 w-4"/>Kanıt fotoğrafı/video ekle<input type="file" className="sr-only" multiple accept="image/jpeg,image/png,image/webp,video/mp4" onChange={e=>{addFiles(item.orderItemId,e.target.files);e.currentTarget.value='';}}/></label><p className="mt-1 text-xs text-gray-500">İsteğe bağlı. Ürün başına en fazla 5 dosya; JPEG, PNG, WebP veya MP4; dosya başına 15 MB.</p></div>{state.files.length?<ul className="mt-3 space-y-2" aria-label={`${item.productName} kanıt dosyaları`}>{state.files.map((file,index)=><li key={`${file.name}-${index}`} className="flex items-center justify-between gap-3 rounded-lg bg-gray-50 p-2 dark:bg-gray-800"><span className="min-w-0 truncate text-sm"><FileImage className="mr-2 inline h-4 w-4"/>{file.name}</span><button type="button" onClick={()=>removeFile(item.orderItemId,index)} className="min-h-11 rounded-lg border px-3" aria-label={`${file.name} dosyasını kaldır`}><Trash2 className="h-4 w-4"/></button></li>)}</ul>:null}</div>:null}</div>})}</fieldset>
  <div className="mt-5"><label className="block"><span className="font-semibold">İade nedeni</span><select value={reason} disabled={busy||!options?.canRequest} onChange={e=>setReason(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border bg-transparent px-3"><option value="">Seçin</option>{(options?.reasonCodes||Object.keys(reasonLabels)).map((code:string)=><option key={code} value={code}>{reasonLabels[code]||code}</option>)}</select></label></div>
  <div className="mt-4"><label className="block"><span className="font-semibold">Sorunu açıklayın</span><textarea value={message} disabled={busy||!options?.canRequest} onChange={e=>setMessage(e.target.value)} maxLength={3000} rows={5} className="mt-1 w-full rounded-xl border bg-transparent p-3" placeholder="Üründe ne olduğunu ve nasıl teslim aldığınızı açıkça yazın."/><span className="mt-1 block text-xs text-gray-500">{message.trim().length}/3000 karakter • en az 10 karakter</span></label></div>
  <div aria-live="polite" className="mt-3 min-h-6 text-sm text-brand-green">{status}</div><button onClick={()=>void submit()} disabled={busy||!options?.canRequest} className="mt-2 min-h-12 w-full rounded-xl bg-brand-green px-4 font-bold text-white disabled:opacity-50">{busy?<><RefreshCw className="mr-2 inline h-4 w-4 animate-spin"/>Gönderiliyor…</>:'İade talebini gönder'}</button>
 </div></div>;
}
function Notice({children}:{children:React.ReactNode}){return<div role="status" className="mt-4 rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900 dark:bg-amber-950/20 dark:text-amber-100">{children}</div>;}
