import React,{useEffect,useState}from'react';
import{Star,Trash2}from'lucide-react';
import{supabase}from'../../lib/supabase';
import{catalogPublicUrl}from'./api';
import{EmptyState,ErrorState,LoadingState,Panel}from'./ui';
import{useDialogA11y}from'./useDialogA11y';

const reviewStatus:Record<string,string>={pending:'İncelemede',published:'Yayında',rejected:'Yayınlanmadı',withdrawn:'Geri çekildi'};
async function rpc(name:string,args:any={}){const{data,error}=await supabase.rpc(name,args);if(error)throw error;return data;}
async function uploadReviewMedia(userId:string,files:File[]){if(files.length>5)throw new Error('En fazla 5 yorum görseli yükleyebilirsiniz.');const uploaded:string[]=[];try{for(const file of files){if(!['image/jpeg','image/png','image/webp','image/avif'].includes(file.type))throw new Error('Yorum görseli JPEG, PNG, WebP veya AVIF olmalıdır.');if(file.size<=0||file.size>8*1024*1024)throw new Error('Her yorum görseli en fazla 8 MB olabilir.');const ext=file.type==='image/jpeg'?'jpg':file.type==='image/png'?'png':file.type==='image/avif'?'avif':'webp';const path=`${userId}/${crypto.randomUUID()}.${ext}`;const{error}=await supabase.storage.from('review-media').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;uploaded.push(path);}return uploaded;}catch(e){if(uploaded.length)await supabase.storage.from('review-media').remove(uploaded).catch(()=>{});throw e;}}
export default function ReviewsPanel({userId,onOpenProduct}:{userId:string;onOpenProduct?:(slug:string)=>void}){
 const[reviewable,setReviewable]=useState<any[]>([]);const[reviews,setReviews]=useState<any[]>([]);const[editing,setEditing]=useState<any|null>(null);const[files,setFiles]=useState<File[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');
 const editorRef=useDialogA11y(()=>{if(!busy){setEditing(null);setFiles([]);}},Boolean(editing));
 async function load(){try{setLoading(true);setError('');const[a,b]=await Promise.all([rpc('list_my_reviewable_order_items_v1'),rpc('list_my_reviews_v1')]);setReviewable(a||[]);setReviews(b||[]);}catch(e:any){setError(e?.message||'Yorumlar yüklenemedi.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(!editing)return;if(Number(editing.rating)<1||Number(editing.rating)>5){setError('1 ile 5 arasında puan seçin.');return;}if(editing.body.trim().length<10){setError('Yorum en az 10 karakter olmalıdır.');return;}let uploaded:string[]=[];try{setBusy(true);setError('');setMessage('');uploaded=files.length?await uploadReviewMedia(userId,files):[];const media=[...(editing.mediaPaths||[]),...uploaded].slice(0,5);if(editing.reviewId){await rpc('update_my_review_v1',{p_review_id:editing.reviewId,p_rating:Number(editing.rating),p_title:editing.title||null,p_body:editing.body,p_media_paths:media});setMessage('Yorumunuz güncellendi ve moderasyon durumuna göre yeniden yayınlanacaktır.');}else{await rpc('submit_verified_review_v1',{p_order_item_id:editing.orderItemId,p_rating:Number(editing.rating),p_title:editing.title||null,p_body:editing.body,p_media_paths:media});setMessage('Doğrulanmış satın alma yorumunuz incelemeye gönderildi.');}setEditing(null);setFiles([]);await load();}catch(e:any){if(uploaded.length)await supabase.storage.from('review-media').remove(uploaded).catch(()=>{});setError(e?.message||'Yorum gönderilemedi.');}finally{setBusy(false);}}
 async function withdraw(id:string){if(!window.confirm('Bu yorumu geri çekmek istediğinize emin misiniz?'))return;try{setBusy(true);setError('');setMessage('');await rpc('withdraw_my_review_v1',{p_review_id:id});setMessage('Yorumunuz geri çekildi.');await load();}catch(e:any){setError(e?.message||'Yorum geri çekilemedi.');}finally{setBusy(false);}}
 function startNew(item:any){setError('');setMessage('');setEditing({orderItemId:item.orderItemId,rating:5,title:'',body:'',mediaPaths:[]});setFiles([]);}
 function startEdit(review:any){setError('');setMessage('');setEditing({reviewId:review.id,rating:review.rating,title:review.title||'',body:review.body,mediaPaths:review.mediaPaths||[]});setFiles([]);}
 if(loading)return<LoadingState label="Yorumlar yükleniyor"/>;
 return<div className="space-y-5">{error?<ErrorState message={error} onRetry={()=>void load()}/>:null}{message?<div role="status" aria-live="polite" className="rounded-xl bg-green-50 p-3 text-green-800 dark:bg-green-950/30 dark:text-green-200">{message}</div>:null}
 <Panel title="Değerlendirilecek Ürünler" description="Yalnız teslim edilmiş gerçek sipariş ürünlerine doğrulanmış satın alma yorumu yazabilirsiniz.">{!reviewable.length?<EmptyState title="Yorum bekleyen ürün yok" body="Teslim edilen ve henüz yorumlamadığınız ürünler burada görünür."/>:<div className="space-y-3">{reviewable.map(item=><article key={item.orderItemId} className="flex gap-3 rounded-xl border p-3">{item.imagePath?<img src={catalogPublicUrl(item.imagePath)} alt="" loading="lazy" decoding="async" className="h-20 w-20 rounded-lg object-cover"/>:<div aria-hidden="true" className="h-20 w-20 shrink-0 rounded-lg bg-gray-100 dark:bg-gray-800"/>}<div className="min-w-0 flex-1"><div className="font-bold">{item.productName}</div><div className="text-sm text-gray-500">{item.producerName} • {item.orderNumber}</div><button type="button" onClick={()=>startNew(item)} className="mt-2 min-h-11 rounded-lg bg-brand-green px-4 font-bold text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">Yorum yap</button></div></article>)}</div>}</Panel>
 <Panel title="Yorumlarım" description={`${reviews.length} değerlendirme kaydı`}>{!reviews.length?<EmptyState title="Henüz yorumunuz yok" body="Gönderdiğiniz değerlendirmeler burada görünür."/>:<div className="space-y-3">{reviews.map(r=><article key={r.id} aria-busy={busy} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><div><button type="button" onClick={()=>onOpenProduct?.(r.productSlug)} className="min-h-11 text-left font-bold hover:underline focus-visible:rounded-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">{r.productName}</button><div className="mt-1 flex items-center gap-1" aria-label={`${r.rating} yıldız`}>{Array.from({length:5}).map((_,i)=><Star aria-hidden="true" key={i} className={`h-4 w-4 ${i<r.rating?'fill-brand-gold text-brand-gold':'text-gray-300'}`}/>)}</div></div><span className="h-fit rounded-full bg-gray-100 px-2.5 py-1 text-xs font-semibold text-gray-600 dark:bg-gray-800 dark:text-gray-300">{reviewStatus[r.status]||r.status}</span></div>{r.title?<h3 className="mt-3 font-semibold">{r.title}</h3>:null}<p className="mt-1 whitespace-pre-wrap text-sm text-gray-700 dark:text-gray-300">{r.body}</p>{Array.isArray(r.mediaPaths)&&r.mediaPaths.length?<div className="mt-2 text-xs text-gray-500">{r.mediaPaths.length} görsel eklendi</div>:null}{r.merchantReply?<div className="mt-3 rounded-lg bg-gray-50 p-3 text-sm dark:bg-gray-800"><strong>Üretici yanıtı:</strong> {r.merchantReply}</div>:null}<div className="mt-3 flex gap-2"><button type="button" disabled={busy||r.status==='withdrawn'} onClick={()=>startEdit(r)} className="min-h-11 rounded-lg border px-3 font-semibold disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">Düzenle</button><button type="button" disabled={busy||r.status==='withdrawn'} onClick={()=>void withdraw(r.id)} aria-label={`${r.productName} yorumunu geri çek`} className="min-h-11 min-w-11 rounded-lg border border-red-200 px-3 text-red-700 disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500"><Trash2 aria-hidden="true" className="mx-auto h-4 w-4"/></button></div></article>)}</div>}</Panel>
 {editing?<div className="fixed inset-0 z-[90] overflow-y-auto bg-black/60 p-4"><form ref={editorRef} tabIndex={-1} onSubmit={submit} role="dialog" aria-modal="true" aria-labelledby="review-editor-title" className="mx-auto mt-8 max-w-xl space-y-4 rounded-2xl bg-white p-5 outline-none dark:bg-gray-900"><h2 id="review-editor-title" className="text-xl font-bold">{editing.reviewId?'Yorumu düzenle':'Ürünü değerlendir'}</h2><fieldset><legend className="font-semibold">Puan</legend><div className="mt-2 flex gap-2">{[1,2,3,4,5].map(value=><button key={value} type="button" onClick={()=>setEditing({...editing,rating:value})} aria-label={`${value} yıldız`} aria-pressed={editing.rating===value} className="grid min-h-11 min-w-11 place-items-center rounded-lg border focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><Star aria-hidden="true" className={`h-5 w-5 ${value<=editing.rating?'fill-brand-gold text-brand-gold':'text-gray-300'}`}/></button>)}</div></fieldset><label className="block"><span className="text-sm font-semibold">Başlık (opsiyonel)</span><input maxLength={120} value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})} className="mt-1 min-h-11 w-full rounded-xl border bg-transparent px-3"/></label><label className="block"><span className="text-sm font-semibold">Yorumunuz</span><textarea minLength={10} maxLength={3000} rows={5} value={editing.body} onChange={e=>setEditing({...editing,body:e.target.value})} className="mt-1 w-full rounded-xl border bg-transparent p-3"/><span className="mt-1 block text-xs text-gray-500">{editing.body.length}/3000</span></label><label className="inline-flex min-h-11 cursor-pointer items-center rounded-xl border px-3 font-semibold focus-within:ring-2 focus-within:ring-brand-gold">Fotoğraf ekle<input type="file" multiple accept="image/jpeg,image/png,image/webp,image/avif" className="sr-only" onChange={e=>{setFiles(Array.from(e.target.files||[]).slice(0,Math.max(0,5-(editing.mediaPaths||[]).length)));e.currentTarget.value='';}}/></label><div className="text-sm text-gray-500">Mevcut: {(editing.mediaPaths||[]).length}, eklenecek: {files.length}, toplam en fazla 5 görsel</div><div className="flex gap-3"><button type="button" disabled={busy} onClick={()=>{setEditing(null);setFiles([]);}} className="min-h-11 flex-1 rounded-xl border font-semibold disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">Vazgeç</button><button type="submit" disabled={busy} className="min-h-11 flex-1 rounded-xl bg-brand-green font-bold text-white disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold">{busy?'Gönderiliyor…':'Yorumu Gönder'}</button></div></form></div>:null}
 </div>;
}
