import React,{useEffect,useState}from'react';
import{ArrowLeft,Bell,ChevronRight,KeyRound,Mail,Palette,ShieldCheck,Trash2,Volume2}from'lucide-react';
import{cancelAccountClosure,changeMyPassword,getMyNewsletterStatus,getNotificationPreferences,requestAccountClosure,signOutAllDevices,signOutOtherDevices,subscribeNewsletter,unsubscribeMyNewsletter,updateNotificationPreferences}from'./api';
import type{AccountClosureSummary,AccountProfile,NewsletterStatus,NewsletterSummary,NotificationPreferences}from'./types';
import{ErrorState,Panel}from'./ui';
import{useAccessibleDialog}from'../accessibility/useAccessibleDialog';
import PremiumPreferencesPanel from'./PremiumPreferencesPanel';
import type{AppTheme}from'../appearance/theme';
import{disableNativePushRegistration,enableNativePushRegistration,getNativePushPermission,isNativePushPlatform,isNativePushProviderConfigured}from'../notifications/nativePush';

const keys=[['orderPush','Sipariş durumları'],['paymentPush','Ödeme durumları'],['shipmentPush','Kargo ve teslimat'],['returnPush','İade ve geri ödeme'],['messagePush','Mesajlar'],['reviewPush','Yorumlar'],['producerPush','Satıcı/üretici işlemleri'],['systemPush','Sistem ve güvenlik'],['campaignPush','Kampanyalar']]as const;
const activeClosureStatuses=new Set(['requested','processing','ready_for_auth_deletion']);
type SettingsView='menu'|'theme'|'sound'|'password'|'notifications'|'newsletter'|'sessions'|'closure';
type SessionAction='others'|'all'|null;

function newsletterStatusLabel(status:NewsletterStatus|null){return status==='active'?'Aktif':status==='pending'?'E-posta onayı bekleniyor':status==='unsubscribed'?'Abonelik kapalı':status==='none'?'Abone değil':status==='bounced'?'E-posta teslimatı başarısız':status==='complained'?'Spam şikayeti nedeniyle kapalı':'Durum alınamadı';}
function permissionLabel(value:string){return value==='granted'?'İzin verildi':value==='denied'?'İzin reddedildi':value==='prompt'?'Henüz sorulmadı':value==='prompt-with-rationale'?'İzin onayı bekleniyor':'Durum alınamadı';}
function closureStatusLabel(value:AccountClosureSummary['status']){const labels:Record<AccountClosureSummary['status'],string>={requested:'Talep alındı',processing:'İşleniyor',ready_for_auth_deletion:'Hesap silme için son kontroller yapılıyor',cancelled:'İptal edildi',completed:'Tamamlandı',rejected:'Reddedildi'};return labels[value];}
function validEmail(value:unknown){const email=String(value||'').trim();return/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)?email:'';}

export default function SettingsPanel({closure,onChanged,profile,theme='light',onThemeChange}:{closure:AccountClosureSummary|null;onChanged:()=>Promise<void>|void;profile:AccountProfile;theme?:AppTheme;onThemeChange?:(theme:AppTheme)=>void}){
 const[view,setView]=useState<SettingsView>('menu');
 const[prefs,setPrefs]=useState<NotificationPreferences|null>(null),[prefsLoading,setPrefsLoading]=useState(true),[prefsBusy,setPrefsBusy]=useState(false),[prefsError,setPrefsError]=useState('');
 const[nativePushPermission,setNativePushPermission]=useState<string>('unknown');const nativePushPlatform=isNativePushPlatform();const nativePushConfigured=isNativePushProviderConfigured();
 const[currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[passwordBusy,setPasswordBusy]=useState(false),[passwordError,setPasswordError]=useState('');
 const[newsletter,setNewsletter]=useState<NewsletterSummary|null>(null),[newsletterLoading,setNewsletterLoading]=useState(true),[newsletterBusy,setNewsletterBusy]=useState(false),[newsletterError,setNewsletterError]=useState('');
 const[sessionBusy,setSessionBusy]=useState<SessionAction>(null),[sessionError,setSessionError]=useState(''),[sessionConfirmAction,setSessionConfirmAction]=useState<SessionAction>(null);
 const[reason,setReason]=useState(''),[closureBusy,setClosureBusy]=useState(false),[closureError,setClosureError]=useState(''),[closureConfirmOpen,setClosureConfirmOpen]=useState(false);
 const closureDialogRef=useAccessibleDialog<HTMLDivElement>(closureConfirmOpen,()=>{if(!closureBusy)setClosureConfirmOpen(false);});
 const sessionDialogRef=useAccessibleDialog<HTMLDivElement>(!!sessionConfirmAction,()=>{if(!sessionBusy)setSessionConfirmAction(null);});
 const passwordMismatch=confirmPassword.length>0&&newPassword!==confirmPassword;
 const accountEmail=validEmail(profile.email||newsletter?.email);const currentNewsletterStatus=newsletter?.status??null;

 async function loadPrefs(){try{setPrefsLoading(true);setPrefsError('');setPrefs(await getNotificationPreferences());}catch{setPrefs(null);setPrefsError('Bildirim ayarları şu anda yüklenemedi. Lütfen yeniden deneyin.');}finally{setPrefsLoading(false);}}
 async function loadNewsletter(){try{setNewsletterLoading(true);setNewsletterError('');setNewsletter(await getMyNewsletterStatus());}catch{setNewsletter(null);setNewsletterError('E-bülten durumu şu anda alınamadı. Lütfen yeniden deneyin.');}finally{setNewsletterLoading(false);}}
 useEffect(()=>{void loadPrefs();void loadNewsletter();if(nativePushPlatform)void getNativePushPermission().then(value=>setNativePushPermission(String(value))).catch(()=>setNativePushPermission('unknown'));},[]);

 async function savePrefs(){if(!prefs||prefsBusy)return;try{setPrefsBusy(true);setPrefsError('');if(nativePushPlatform&&prefs.pushEnabled){const registration=await enableNativePushRegistration();if(registration.status==='not-configured')throw new Error('NOT_READY');if(registration.status==='denied')throw new Error('DENIED');setNativePushPermission('granted');}if(nativePushPlatform&&!prefs.pushEnabled){await disableNativePushRegistration();setNativePushPermission(String(await getNativePushPermission()));}setPrefs(await updateNotificationPreferences(prefs));setView('menu');}catch(e:unknown){const code=e instanceof Error?e.message:'';setPrefsError(code==='DENIED'?'Cihaz bildirim izni verilmedi. Telefon ayarlarından bildirimlere izin verin.':code==='NOT_READY'?'Cihaz bildirimleri şu anda kullanıma hazır değil.':'Bildirim tercihleri şu anda kaydedilemedi. Lütfen yeniden deneyin.');}finally{setPrefsBusy(false);}}
 async function savePassword(e:React.FormEvent){e.preventDefault();if(passwordBusy)return;setPasswordError('');if(currentPassword.length<1||currentPassword.length>256){setPasswordError('Mevcut şifrenizi kontrol edin.');return;}if(newPassword.length<8||newPassword.length>72){setPasswordError('Yeni şifre 8-72 karakter arasında olmalıdır.');return;}if(newPassword!==confirmPassword){setPasswordError('Yeni şifreler eşleşmiyor.');return;}if(currentPassword===newPassword){setPasswordError('Yeni şifre mevcut şifrenizden farklı olmalıdır.');return;}try{setPasswordBusy(true);await changeMyPassword(currentPassword,newPassword);setCurrentPassword('');setNewPassword('');setConfirmPassword('');setView('menu');}catch{setPasswordError('Şifre şu anda güncellenemedi. Mevcut şifrenizi kontrol edip yeniden deneyin.');}finally{setPasswordBusy(false);}}
 async function startNewsletter(){if(newsletterBusy||!accountEmail)return;try{setNewsletterBusy(true);setNewsletterError('');await subscribeNewsletter(accountEmail,profile.locale);setNewsletter(await getMyNewsletterStatus());await onChanged();setView('menu');}catch{setNewsletterError('E-bülten aboneliği şu anda başlatılamadı. Hesap e-postanızı kontrol edip yeniden deneyin.');}finally{setNewsletterBusy(false);}}
 async function stopNewsletter(){if(newsletterBusy)return;try{setNewsletterBusy(true);setNewsletterError('');await unsubscribeMyNewsletter();setNewsletter(await getMyNewsletterStatus());await onChanged();setView('menu');}catch{setNewsletterError('E-bülten aboneliği şu anda kapatılamadı. Lütfen yeniden deneyin.');}finally{setNewsletterBusy(false);}}
 async function runSession(action:Exclude<SessionAction,null>){if(sessionBusy)return;setSessionError('');setSessionBusy(action);try{if(action==='others'){await signOutOtherDevices();setSessionConfirmAction(null);setView('menu');}else await signOutAllDevices();}catch{setSessionConfirmAction(null);setSessionError('Oturum işlemi şu anda tamamlanamadı. Lütfen yeniden deneyin.');}finally{setSessionBusy(null);}}
 async function confirmCloseAccount(){if(closureBusy)return;const normalizedReason=reason.trim();if(normalizedReason.length<5||normalizedReason.length>2000){setClosureConfirmOpen(false);setClosureError('Kapatma nedeni 5 ile 2000 karakter arasında olmalıdır.');return;}try{setClosureBusy(true);setClosureError('');await requestAccountClosure(normalizedReason);setReason('');setClosureConfirmOpen(false);await onChanged();setView('menu');}catch{setClosureConfirmOpen(false);setClosureError('Hesap kapatma talebi şu anda oluşturulamadı. Lütfen yeniden deneyin.');}finally{setClosureBusy(false);}}
 async function cancelClose(){if(closureBusy)return;try{setClosureBusy(true);setClosureError('');await cancelAccountClosure();await onChanged();setView('menu');}catch{setClosureError('Talep şu anda iptal edilemedi. Lütfen yeniden deneyin.');}finally{setClosureBusy(false);}}

 const closureStatus=closure?.status??null;const activeClosure=closureStatus?activeClosureStatuses.has(closureStatus):false;
 const menuItems:[SettingsView,string,string,React.ComponentType<{className?:string}>][]=[['theme','Tema','Marka görünümü ve kişisel renk tercihi',Palette],['sound','Bildirim Sesi','Golden Oremar premium ses imzası',Volume2],['notifications','Bildirim Tercihleri','Sipariş, ödeme, kargo, mesaj ve kampanyalar',Bell],['password','Şifre Değiştir','Parolanızı güvenli şekilde güncelleyin',KeyRound],['newsletter','E-bülten','Yeni ürün ve kampanya e-postaları',Mail],['sessions','Oturum ve Güvenlik','Diğer cihazlardaki oturumları yönetin',ShieldCheck],['closure','Hesap Kapatma','Hesap kapatma talebi ve durumu',Trash2]];
 if(view==='menu')return<section aria-labelledby="settings-title" className="space-y-3"><div className="mb-4"><h2 id="settings-title" data-account-panel-heading tabIndex={-1} className="text-2xl font-black outline-none">Ayarlar</h2><p className="mt-1 text-sm text-brand-muted">Her ayar ayrı ekranda açılır. Uzun ve karışık tek sayfa kullanılmaz.</p></div>{menuItems.map(([key,label,description,Icon])=><button key={key} type="button" onClick={()=>setView(key)} className="flex min-h-20 w-full items-center gap-3 rounded-2xl border border-brand-border bg-brand-card p-4 text-left shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-brand-green/10 text-brand-green"><Icon className="h-5 w-5" aria-hidden="true"/></span><span className="min-w-0 flex-1"><span className="block font-black text-brand-text">{label}</span><span className="mt-1 block text-sm text-brand-muted">{description}</span></span><ChevronRight className="h-5 w-5 shrink-0 text-brand-muted" aria-hidden="true"/></button>)}</section>;

 const back=<button type="button" onClick={()=>setView('menu')} className="mb-4 inline-flex min-h-11 items-center rounded-xl border border-brand-border bg-brand-card px-4 font-bold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold"><ArrowLeft aria-hidden="true" className="mr-2 h-4 w-4"/>Ayarlara dön</button>;
 return<div className="space-y-4">{back}
  {view==='theme'?<PremiumPreferencesPanel theme={theme} onThemeChange={onThemeChange} mode="theme" onSaved={()=>setView('menu')}/>:null}
  {view==='sound'?<PremiumPreferencesPanel theme={theme} onThemeChange={onThemeChange} mode="sound" onSaved={()=>setView('menu')}/>:null}
  {view==='password'?<Panel title="Şifre Değiştir" description="Mevcut şifrenizi girerek yeni şifrenizi güvenli şekilde oluşturun.">{passwordError?<ErrorState message={passwordError}/>:null}<form onSubmit={savePassword} className="space-y-3" aria-busy={passwordBusy}><label className="block"><span className="text-sm font-semibold">Mevcut şifre</span><input required maxLength={256} disabled={passwordBusy} type="password" autoComplete="current-password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border bg-transparent px-3"/></label><label className="block"><span className="text-sm font-semibold">Yeni şifre</span><input required minLength={8} maxLength={72} disabled={passwordBusy} type="password" autoComplete="new-password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border bg-transparent px-3"/></label><label className="block"><span className="text-sm font-semibold">Yeni şifre tekrar</span><input required minLength={8} maxLength={72} disabled={passwordBusy} type="password" autoComplete="new-password" aria-invalid={passwordMismatch||undefined} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border bg-transparent px-3"/>{passwordMismatch?<span className="mt-1 block text-xs font-semibold text-red-700">Yeni şifreler eşleşmiyor.</span>:null}</label><button disabled={passwordBusy||!currentPassword||newPassword.length<8||passwordMismatch||!confirmPassword||currentPassword===newPassword} className="min-h-11 w-full rounded-xl bg-brand-green font-bold text-brand-on-green disabled:opacity-50">{passwordBusy?'Şifre güncelleniyor…':'Kaydet'}</button></form></Panel>:null}
  {view==='notifications'?<Panel title="Bildirim Tercihleri" description="Sipariş, ödeme, mesaj ve kampanya bildirimlerini ayrı ayrı yönetin.">{prefsError?<ErrorState message={prefsError} onRetry={()=>void loadPrefs()}/>:null}{prefsLoading?<div role="status" className="text-sm text-brand-muted">Bildirim ayarları yükleniyor…</div>:prefs?<div className="space-y-2" aria-busy={prefsBusy}><label className="flex min-h-12 items-center justify-between gap-4 rounded-xl border border-brand-border p-3"><span className="font-bold">Push bildirimleri</span><input disabled={prefsBusy} type="checkbox" className="h-5 w-5" checked={prefs.pushEnabled} onChange={e=>setPrefs({...prefs,pushEnabled:e.target.checked})}/></label>{nativePushPlatform?<div className="rounded-xl border border-brand-border bg-brand-card p-3 text-sm text-brand-muted">{nativePushConfigured?`Cihaz bildirimleri hazır. Telefon izni: ${permissionLabel(nativePushPermission)}.`:'Cihaz bildirimleri bu sürümde henüz kullanıma hazır değil.'}</div>:null}{keys.map(([key,label])=><label key={key} className="flex min-h-12 items-center justify-between gap-4 rounded-xl border border-brand-border p-3"><span>{label}</span><input disabled={prefsBusy} type="checkbox" className="h-5 w-5" checked={prefs[key]} onChange={e=>setPrefs({...prefs,[key]:e.target.checked})}/></label>)}<button type="button" disabled={prefsBusy} onClick={()=>void savePrefs()} className="min-h-11 w-full rounded-xl bg-brand-green font-bold text-brand-on-green disabled:opacity-50">{prefsBusy?'Kaydediliyor…':'Kaydet'}</button></div>:null}</Panel>:null}
  {view==='newsletter'?<Panel title="E-bülten" description="Yeni ürün ve kampanya e-postaları için e-posta onaylı abonelik kullanılır.">{newsletterError?<ErrorState message={newsletterError} onRetry={()=>void loadNewsletter()}/>:null}{newsletterLoading?<div role="status" className="text-sm text-brand-muted">E-bülten durumu yükleniyor…</div>:newsletter?<div className="rounded-xl border border-brand-border p-4" aria-busy={newsletterBusy}><div className="text-sm text-brand-muted">E-posta</div><div className="mt-1 break-all font-semibold">{accountEmail||'Hesap e-postası bulunamadı'}</div><div className="mt-3 text-sm">Durum: <strong>{newsletterStatusLabel(currentNewsletterStatus)}</strong></div>{currentNewsletterStatus==='active'||currentNewsletterStatus==='pending'?<button type="button" disabled={newsletterBusy} onClick={()=>void stopNewsletter()} className="mt-4 min-h-11 w-full rounded-xl border border-red-300 font-bold text-red-700 disabled:opacity-50">{newsletterBusy?'İşleniyor…':'Aboneliği kapat'}</button>:<button type="button" disabled={newsletterBusy||!accountEmail} onClick={()=>void startNewsletter()} className="mt-4 min-h-11 w-full rounded-xl bg-brand-green font-bold text-brand-on-green disabled:opacity-50">{newsletterBusy?'İşleniyor…':'Abone ol'}</button>}</div>:null}</Panel>:null}
  {view==='sessions'?<Panel title="Oturum ve Güvenlik" description="Bu cihazdan çıkış Hesabım sayfasının altında bulunur. Buradan diğer cihazlardaki oturumları yönetebilirsiniz.">{sessionError?<ErrorState message={sessionError}/>:null}<div className="space-y-2"><button type="button" disabled={!!sessionBusy} onClick={()=>setSessionConfirmAction('others')} className="min-h-12 w-full rounded-xl border border-brand-border font-semibold">Diğer cihazlardaki oturumları kapat</button><button type="button" disabled={!!sessionBusy} onClick={()=>setSessionConfirmAction('all')} className="min-h-12 w-full rounded-xl border border-red-300 font-semibold text-red-700">Tüm cihazlardan çıkış yap</button></div></Panel>:null}
  {view==='closure'?<Panel title="Hesap Kapatma" description="Aktif sipariş veya iade varken kapatma engellenir. Yasal olarak korunması gereken kayıtlar gerekli süre boyunca saklanır.">{closureError?<ErrorState message={closureError}/>:null}{activeClosure&&closureStatus?<div className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950">Aktif hesap kapatma talebiniz var. Durum: <strong>{closureStatusLabel(closureStatus)}</strong>.<button type="button" disabled={closureBusy} onClick={()=>void cancelClose()} className="mt-3 min-h-11 w-full rounded-lg border border-amber-500 font-bold">{closureBusy?'İptal ediliyor…':'Talebi iptal et'}</button></div>:<div><label className="block"><span className="text-sm font-semibold">Kapatma nedeni</span><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={3} minLength={5} maxLength={2000} className="mt-1 w-full rounded-xl border bg-transparent p-3" placeholder="Neden hesabınızı kapatmak istediğinizi kısaca yazın."/></label><button type="button" onClick={()=>setClosureConfirmOpen(true)} disabled={closureBusy||reason.trim().length<5||reason.trim().length>2000} className="mt-3 min-h-11 w-full rounded-xl border border-red-300 font-bold text-red-700 disabled:opacity-50">Hesap kapatma talebi oluştur</button></div>}</Panel>:null}

  {sessionConfirmAction?<div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/60 p-4"><div ref={sessionDialogRef} role="alertdialog" aria-modal="true" aria-labelledby="session-confirm-title" tabIndex={-1} className="w-full max-w-md rounded-2xl bg-brand-card p-5 text-brand-text shadow-xl outline-none"><h3 id="session-confirm-title" className="text-lg font-bold">Oturumları kapatmayı onaylıyor musunuz?</h3><p className="mt-2 text-sm text-brand-muted">{sessionConfirmAction==='all'?'Hesap tüm cihazlardan çıkarılacak ve yeniden giriş yapmanız gerekecek.':'Bu cihaz açık kalırken diğer aktif oturumlar kapatılacak.'}</p><div className="mt-5 grid grid-cols-2 gap-3"><button type="button" disabled={!!sessionBusy} onClick={()=>setSessionConfirmAction(null)} className="min-h-11 rounded-xl border font-semibold">Vazgeç</button><button type="button" disabled={!!sessionBusy} onClick={()=>void runSession(sessionConfirmAction)} className="min-h-11 rounded-xl bg-red-700 font-bold text-white">{sessionBusy?'Kapatılıyor…':'Onayla'}</button></div></div></div>:null}
  {closureConfirmOpen?<div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/60 p-4"><div ref={closureDialogRef} role="alertdialog" aria-modal="true" aria-labelledby="closure-confirm-title" tabIndex={-1} className="w-full max-w-md rounded-2xl bg-brand-card p-5 text-brand-text shadow-xl outline-none"><h3 id="closure-confirm-title" className="text-lg font-bold">Hesap kapatma talebi oluşturulsun mu?</h3><p className="mt-2 text-sm text-brand-muted">Bu işlem hesabı anında silmez. Talebiniz gerekli güvenlik ve hesap kontrollerinden sonra işleme alınır.</p><div className="mt-5 grid grid-cols-2 gap-3"><button type="button" disabled={closureBusy} onClick={()=>setClosureConfirmOpen(false)} className="min-h-11 rounded-xl border font-semibold">Vazgeç</button><button type="button" disabled={closureBusy} onClick={()=>void confirmCloseAccount()} className="min-h-11 rounded-xl bg-red-700 font-bold text-white">{closureBusy?'Oluşturuluyor…':'Talebi Onayla'}</button></div></div></div>:null}
 </div>;
}
