import { supabase } from '../../lib/supabase';

export type NutritionDraft={servingSize:string;energyKcal:string;proteinG:string;carbohydrateG:string;sugarsG:string;fatG:string;saturatedFatG:string;fiberG:string;saltG:string};
export type ProductEditorialDraft={
 title:string;summary:string;
 productInfo:{ingredients:string[];nutrition:NutritionDraft;usageNotes:string[]};
 safety:{storage:string[];preparation:string[];warnings:string[];allergens:string[];allergenNote:string};
 recipe:{enabled:boolean;title:string;servings:string;prepMinutes:string;cookMinutes:string;ingredients:string[];steps:string[]};
};
export type ProductEditorialEditor={productId:string;productName:string;producerId:string;storeKind:'official'|'independent';canPublish:boolean;published:ProductEditorialDraft;draft:null|{id:string;status:'draft'|'review'|'rejected'|'approved';payload:ProductEditorialDraft;reviewNote:string;updatedAt:string};videoPath:string};

const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function record(value:unknown):value is Record<string,any>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function text(value:unknown,max:number,required=false){if(value==null&&!required)return'';const normalized=typeof value==='string'?value.trim():'';if((required&&!normalized)||normalized.length>max||/[\u0000-\u001F\u007F]/.test(normalized))throw new Error('Ürün bilgi alanı doğrulanamadı.');return normalized;}
function stringArray(value:unknown,maxItems:number,maxLen:number){if(value==null)return[];if(!Array.isArray(value)||value.length>maxItems)throw new Error('Ürün bilgi listesi doğrulanamadı.');return value.map(item=>text(item,maxLen,true));}
function numericText(value:unknown){if(value==null||value==='')return'';if(typeof value!=='number'&&typeof value!=='string')throw new Error('Besin değeri doğrulanamadı.');const normalized=String(value).trim();if(!/^\d+(?:[.,]\d+)?$/.test(normalized))throw new Error('Besin değeri doğrulanamadı.');return normalized.replace(',','.');}
function normalizePayload(value:unknown):ProductEditorialDraft{
 if(!record(value)||!record(value.productInfo)||!record(value.safety)||!record(value.recipe))throw new Error('Ürün sağlık ve tarif bilgileri doğrulanamadı.');
 const nutrition=record(value.productInfo.nutrition)?value.productInfo.nutrition:{};
 return{
  title:text(value.title,180,true),summary:text(value.summary,1000),
  productInfo:{ingredients:stringArray(value.productInfo.ingredients,80,300),usageNotes:stringArray(value.productInfo.usageNotes,30,500),nutrition:{servingSize:text(nutrition.servingSize,80),energyKcal:numericText(nutrition.energyKcal),proteinG:numericText(nutrition.proteinG),carbohydrateG:numericText(nutrition.carbohydrateG),sugarsG:numericText(nutrition.sugarsG),fatG:numericText(nutrition.fatG),saturatedFatG:numericText(nutrition.saturatedFatG),fiberG:numericText(nutrition.fiberG),saltG:numericText(nutrition.saltG)}},
  safety:{storage:stringArray(value.safety.storage,20,500),preparation:stringArray(value.safety.preparation,30,500),warnings:stringArray(value.safety.warnings,20,700),allergens:stringArray(value.safety.allergens,30,160),allergenNote:text(value.safety.allergenNote,1000)},
  recipe:{enabled:value.recipe.enabled===true,title:text(value.recipe.title,180),servings:numericText(value.recipe.servings),prepMinutes:numericText(value.recipe.prepMinutes),cookMinutes:numericText(value.recipe.cookMinutes),ingredients:stringArray(value.recipe.ingredients,60,300),steps:stringArray(value.recipe.steps,40,1000)}
 };
}
function payloadForRpc(input:ProductEditorialDraft){
 const numberOrUndefined=(value:string)=>{const raw=value.trim().replace(',','.');if(!raw)return undefined;const parsed=Number(raw);if(!Number.isFinite(parsed)||parsed<0)throw new Error('Sayısal ürün bilgisi geçersiz.');return parsed;};
 const nutrition=Object.fromEntries(Object.entries(input.productInfo.nutrition).flatMap(([key,value])=>key==='servingSize'?(value.trim()?[[key,value.trim()]]:[]):(value.trim()?[[key,numberOrUndefined(value)]]:[]));
 const servings=input.recipe.servings.trim()?Math.trunc(Number(input.recipe.servings)):undefined;const prep=input.recipe.prepMinutes.trim()?Math.trunc(Number(input.recipe.prepMinutes)):undefined;const cook=input.recipe.cookMinutes.trim()?Math.trunc(Number(input.recipe.cookMinutes)):undefined;
 return{title:input.title.trim(),summary:input.summary.trim(),productInfo:{ingredients:input.productInfo.ingredients.map(v=>v.trim()).filter(Boolean),nutrition,usageNotes:input.productInfo.usageNotes.map(v=>v.trim()).filter(Boolean)},safety:{storage:input.safety.storage.map(v=>v.trim()).filter(Boolean),preparation:input.safety.preparation.map(v=>v.trim()).filter(Boolean),warnings:input.safety.warnings.map(v=>v.trim()).filter(Boolean),allergens:input.safety.allergens.map(v=>v.trim()).filter(Boolean),allergenNote:input.safety.allergenNote.trim()},recipe:{enabled:input.recipe.enabled,title:input.recipe.title.trim(),...(servings!==undefined?{servings}:{}),...(prep!==undefined?{prepMinutes:prep}:{}),...(cook!==undefined?{cookMinutes:cook}:{}),ingredients:input.recipe.ingredients.map(v=>v.trim()).filter(Boolean),steps:input.recipe.steps.map(v=>v.trim()).filter(Boolean)}};
}
function normalizeEditor(value:unknown):ProductEditorialEditor{
 if(!record(value)||!UUID_RE.test(String(value.productId||''))||!UUID_RE.test(String(value.producerId||'')))throw new Error('Ürün bilgi editörü doğrulanamadı.');const storeKind=value.storeKind;if(storeKind!=='official'&&storeKind!=='independent')throw new Error('Mağaza türü doğrulanamadı.');if(typeof value.canPublish!=='boolean')throw new Error('Yayın yetkisi doğrulanamadı.');const published=normalizePayload(value.published);let draft:ProductEditorialEditor['draft']=null;if(value.draft!=null){if(!record(value.draft)||!UUID_RE.test(String(value.draft.id||''))||!['draft','review','rejected','approved'].includes(String(value.draft.status||'')))throw new Error('Ürün bilgi taslağı doğrulanamadı.');draft={id:String(value.draft.id),status:value.draft.status,payload:normalizePayload(value.draft.payload),reviewNote:text(value.draft.reviewNote,2000),updatedAt:text(value.draft.updatedAt,80,true)};}const videoPath=text(value.videoPath,1200);if(videoPath&&(/^[a-z][a-z0-9+.-]*:/i.test(videoPath)||videoPath.startsWith('/')))throw new Error('Ürün video yolu doğrulanamadı.');return{productId:String(value.productId),productName:text(value.productName,300,true),producerId:String(value.producerId),storeKind,canPublish:value.canPublish,published,draft,videoPath};
}
export function emptyEditorial(productName=''):ProductEditorialDraft{return{title:productName?`${productName} | Saklama ve Kullanım`:'Ürün bilgileri',summary:'',productInfo:{ingredients:[],nutrition:{servingSize:'',energyKcal:'',proteinG:'',carbohydrateG:'',sugarsG:'',fatG:'',saturatedFatG:'',fiberG:'',saltG:''},usageNotes:[]},safety:{storage:[],preparation:[],warnings:[],allergens:[],allergenNote:''},recipe:{enabled:false,title:'',servings:'',prepMinutes:'',cookMinutes:'',ingredients:[],steps:[]}};}
export async function getProductEditorialEditor(reference:string){const ref=text(reference,220,true);const{data,error}=await supabase.rpc('get_product_editorial_editor_v1',{p_reference:ref});if(error)throw error;return normalizeEditor(data);}
export async function saveProductEditorial(reference:string,payload:ProductEditorialDraft,action:'save'|'submit'|'publish',note:string|null=null){const ref=text(reference,220,true);const{data,error}=await supabase.rpc('save_product_editorial_v1',{p_reference:ref,p_payload:payloadForRpc(payload),p_action:action,p_note:note});if(error)throw error;if(!record(data)||!UUID_RE.test(String(data.id||''))||!UUID_RE.test(String(data.productId||'')))throw new Error('Ürün bilgi kayıt sonucu doğrulanamadı.');return data;}
export async function listPendingProductEditorialReviews(){const{data,error}=await supabase.rpc('admin_list_product_editorial_reviews_v1');if(error)throw error;if(!Array.isArray(data)||data.length>5000)throw new Error('Ürün bilgi onay listesi doğrulanamadı.');return data.map((row,index)=>{if(!record(row)||!UUID_RE.test(String(row.id||''))||!UUID_RE.test(String(row.productId||''))||!UUID_RE.test(String(row.producerId||'')))throw new Error(`${index+1}. ürün bilgi talebi doğrulanamadı.`);return{id:String(row.id),productId:String(row.productId),productName:text(row.productName,300,true),productSlug:text(row.productSlug,220,true),producerId:String(row.producerId),producerName:text(row.producerName,240,true),payload:normalizePayload(row.payload),submittedAt:text(row.submittedAt,80),updatedAt:text(row.updatedAt,80,true)};});}
export async function reviewProductEditorial(reference:string,payload:ProductEditorialDraft,approve:boolean,note:string){if(approve)return saveProductEditorial(reference,payload,'publish',null);const ref=text(reference,220,true);const reason=text(note,2000,true);if(reason.length<8)throw new Error('Red gerekçesi en az 8 karakter olmalıdır.');const{data,error}=await supabase.rpc('save_product_editorial_v1',{p_reference:ref,p_payload:{},p_action:'reject',p_note:reason});if(error)throw error;return data;}
