import React from'react';
import{BookOpen,ShieldCheck,Utensils}from'lucide-react';
import type{ProductEditorialDraft}from'./api';

type Props={value:ProductEditorialDraft;onChange:(next:ProductEditorialDraft)=>void;disabled?:boolean};
const input='min-h-11 w-full rounded-xl border border-gray-200 bg-transparent px-3 dark:border-gray-700';
const area='w-full rounded-xl border border-gray-200 bg-transparent p-3 dark:border-gray-700';
function lines(values:string[]){return values.join('\n');}
function split(value:string,max:number){return value.split('\n').map(row=>row.trim()).filter(Boolean).slice(0,max);}
export default function ProductCardDetailsFields({value,onChange,disabled=false}:Props){
 function root<K extends keyof ProductEditorialDraft>(key:K,next:ProductEditorialDraft[K]){onChange({...value,[key]:next});}
 function info(key:keyof ProductEditorialDraft['productInfo'],next:any){root('productInfo',{...value.productInfo,[key]:next});}
 function safety(key:keyof ProductEditorialDraft['safety'],next:any){root('safety',{...value.safety,[key]:next});}
 function recipe(key:keyof ProductEditorialDraft['recipe'],next:any){root('recipe',{...value.recipe,[key]:next});}
 function nutrition(key:keyof ProductEditorialDraft['productInfo']['nutrition'],next:string){info('nutrition',{...value.productInfo.nutrition,[key]:next});}
 return<fieldset disabled={disabled} className="space-y-5 disabled:opacity-60"><legend className="sr-only">Ürün kartı sağlık, içerik ve tarif bilgileri</legend>
  <div className="grid gap-4 md:grid-cols-2"><Field label="Bilgi başlığı"><input value={value.title} maxLength={180} onChange={e=>root('title',e.target.value)} className={input}/></Field><Field label="Sağlık ve kullanım özeti"><input value={value.summary} maxLength={1000} onChange={e=>root('summary',e.target.value)} className={input}/></Field></div>
  <div className="grid gap-5 xl:grid-cols-2">
   <section className="space-y-4 rounded-2xl border p-4"><h3 className="flex items-center gap-2 font-black"><BookOpen aria-hidden="true" className="h-5 w-5 text-brand-gold"/>İçerik ve besin bilgileri</h3><Field label="İçindekiler - her satıra bir içerik"><textarea rows={6} value={lines(value.productInfo.ingredients)} onChange={e=>info('ingredients',split(e.target.value,80))} className={area}/></Field><div className="grid gap-3 sm:grid-cols-3"><Small label="Porsiyon" value={value.productInfo.nutrition.servingSize} onChange={v=>nutrition('servingSize',v)}/><Small label="Enerji kcal" value={value.productInfo.nutrition.energyKcal} onChange={v=>nutrition('energyKcal',v)}/><Small label="Protein g" value={value.productInfo.nutrition.proteinG} onChange={v=>nutrition('proteinG',v)}/><Small label="Karbonhidrat g" value={value.productInfo.nutrition.carbohydrateG} onChange={v=>nutrition('carbohydrateG',v)}/><Small label="Şeker g" value={value.productInfo.nutrition.sugarsG} onChange={v=>nutrition('sugarsG',v)}/><Small label="Yağ g" value={value.productInfo.nutrition.fatG} onChange={v=>nutrition('fatG',v)}/><Small label="Doymuş yağ g" value={value.productInfo.nutrition.saturatedFatG} onChange={v=>nutrition('saturatedFatG',v)}/><Small label="Lif g" value={value.productInfo.nutrition.fiberG} onChange={v=>nutrition('fiberG',v)}/><Small label="Tuz g" value={value.productInfo.nutrition.saltG} onChange={v=>nutrition('saltG',v)}/></div><Field label="Kullanım notları - her satıra bir not"><textarea rows={4} value={lines(value.productInfo.usageNotes)} onChange={e=>info('usageNotes',split(e.target.value,30))} className={area}/></Field></section>
   <section className="space-y-4 rounded-2xl border p-4"><h3 className="flex items-center gap-2 font-black"><ShieldCheck aria-hidden="true" className="h-5 w-5 text-brand-green"/>Sağlık ve güvenlik bilgileri</h3><Field label="Saklama koşulları - her satıra bir madde"><textarea rows={5} value={lines(value.safety.storage)} onChange={e=>safety('storage',split(e.target.value,20))} className={area}/></Field><Field label="Hazırlama / güvenli kullanım"><textarea rows={5} value={lines(value.safety.preparation)} onChange={e=>safety('preparation',split(e.target.value,30))} className={area}/></Field><Field label="Uyarılar"><textarea rows={4} value={lines(value.safety.warnings)} onChange={e=>safety('warnings',split(e.target.value,20))} className={area}/></Field><Field label="Bilinen alerjenler"><textarea rows={3} value={lines(value.safety.allergens)} onChange={e=>safety('allergens',split(e.target.value,30))} className={area}/></Field><Field label="Alerjen / etiket notu"><textarea rows={3} maxLength={1000} value={value.safety.allergenNote} onChange={e=>safety('allergenNote',e.target.value)} className={area}/></Field></section>
  </div>
  <section className="rounded-2xl border p-4"><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={value.recipe.enabled} onChange={e=>recipe('enabled',e.target.checked)} className="h-5 w-5"/><span className="font-black"><Utensils aria-hidden="true" className="mr-2 inline h-5 w-5 text-brand-gold"/>Bu ürün kartında tarif göster</span></label>{value.recipe.enabled?<div className="mt-4 space-y-4"><div className="grid gap-3 sm:grid-cols-4"><Field label="Tarif adı"><input value={value.recipe.title} maxLength={180} onChange={e=>recipe('title',e.target.value)} className={input}/></Field><Small label="Porsiyon" value={value.recipe.servings} onChange={v=>recipe('servings',v)}/><Small label="Hazırlık dk" value={value.recipe.prepMinutes} onChange={v=>recipe('prepMinutes',v)}/><Small label="Pişirme dk" value={value.recipe.cookMinutes} onChange={v=>recipe('cookMinutes',v)}/></div><div className="grid gap-4 md:grid-cols-2"><Field label="Tarif malzemeleri"><textarea rows={6} value={lines(value.recipe.ingredients)} onChange={e=>recipe('ingredients',split(e.target.value,60))} className={area}/></Field><Field label="Tarif yapılışı - her satıra bir adım"><textarea rows={6} value={lines(value.recipe.steps)} onChange={e=>recipe('steps',split(e.target.value,40))} className={area}/></Field></div></div>:<p className="mt-2 text-sm text-gray-500">Tarif bu ürün için uygun değilse kapalı bırakabilirsiniz.</p>}</section>
  <p className="text-xs leading-5 text-gray-500">Bu alanlar ürün kartının kendi bilgileri olarak kaydedilir. Tıbbi tedavi iddiası yazmayın; ürünün gerçek içeriğini, etiketteki bilgileri ve güvenli kullanım kurallarını girin.</p>
 </fieldset>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return<label className="block"><span className="mb-1 block text-sm font-semibold">{label}</span>{children}</label>;}
function Small({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return<Field label={label}><input inputMode="decimal" value={value} onChange={e=>onChange(e.target.value)} className={input}/></Field>;}
