import React,{useEffect,useState}from'react';
import{BookOpen,ChevronRight,RefreshCw,Save,Send,ShieldCheck,Utensils}from'lucide-react';
import{emptyEditorial,getProductEditorialEditor,saveProductEditorial,type ProductEditorialDraft}from'./api';

type Props={reference:string;onChanged?:()=>void|Promise<void>;compact?:boolean};
function lines(value:string[]){return value.join('\n');}
function toLines(value:string,maxItems:number){return value.split('\n').map(v=>v.trim()).filter(Boolean).slice(0,maxItems);}
function messageOf(error:unknown){const message=String((error as any)?.message||'').trim();const map:Array<[string,string]>=[['recipe_content_incomplete','Tarifi açtıysanız tarif adı, malzemeler ve yapılış adımlarını tamamlayın.'],['invalid_product_editorial','Ürün bilgi alanlarından biri geçersiz.'],['product_access_denied','Bu ürünün sağlık ve tarif bilgilerini düzenleme yetkiniz yok.'],['admin_required','Bu bilgiyi doğrudan yayınlamak için Super Admin yetkisi gerekir.']];for(const[key,text]of map)if(message.includes(key))return text;return message||'Ürün bilgileri kaydedilemedi.';}

export default function ProductEditorialEditor({reference,onChanged,compact=false}:Props){
 const[editor,setEditor]=useState<any>(null);const[draft,setDraft]=useState<ProductEditorialDraft>(emptyEditorial());const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('');
 async function load(){try{setLoading(true);setError('');const next=await getProductEditorialEditor(reference);setEditor(next);setDraft(next.draft?.payload||next.published||emptyEditorial(next.productName));}catch(e){setError(messageOf(e));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[reference]);
 function patch<K extends keyof ProductEditorialDraft>(key:K,value:ProductEditorialDraft[K]){setDraft(current=>({...current,[key]:value}));}
 function patchInfo(key:keyof ProductEditorialDraft['productInfo'],value:any){patch('productInfo',{...draft.productInfo,[key]:value});}
 function patchSafety(key:keyof ProductEditorialDraft['safety'],value:any){patch('safety',{...draft.safety,[key]:value});}
 function patchRecipe(key:keyof ProductEditorialDraft['recipe'],value:any){patch('recipe',{...draft.recipe,[key]:value});}
 async function persist(action:'save'|'submit'|'publish'){if(busy)return;try{setBusy(action);setError('');setNotice('');await saveProductEditorial(reference,draft,action);setNotice(action==='publish'?'Sağlık, kullanım ve tarif bilgileri müşteriye yayınlandı.':action==='submit'?'Ürün bilgi değişiklikleri Super Admin incelemesine gönderildi.':'Ürün bilgi taslağı kaydedildi.');await load();await onChanged?.();}catch(e){setError(messageOf(e));}finally{setBusy('');}}
 if(loading)return<div role="status" className="rounded-2xl border p-5 text-sm text-gray-500">Ürün sağlık ve tarif bilgileri yükleniyor...</div>;
 if(!editor)return<div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error||'Ürün bilgi editörü yüklenemedi.'}</div>;
 const draftStatus=editor.draft?.status;const canPublish=editor.canPublish===true;
 return<section className={`space-y-5 rounded-3xl border bg-white dark:bg-gray-900 ${compact?'p-4':'p-5 sm:p-6'}`} aria-labelledby="product-editorial-heading">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><ShieldCheck aria-hidden="true" className="h-5 w-5 text-brand-green"/><h2 id="product-editorial-heading" className="text-xl font-black">Sağlık, kullanım ve tarif bilgileri</h2></div><p className="mt-1 max-w-3xl text-sm text-gray-500">Mevcut doğrulanmış bilgi korunur. Hastalık tedavisi veya kesin sağlık sonucu iddiası yazmayın; ürün etiketi, gerçek içerik ve güvenli kullanım bilgilerini girin.</p></div><button type="button" onClick={()=>void load()} disabled={Boolean(busy)} className="min-h-11 rounded-xl border px-3 font-semibold disabled:opacity-50"><RefreshCw aria-hidden="true" className="mr-2 inline h-4 w-4"/>Yenile</button></div>
  {draftStatus==='review'?<div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm text-blue-900">Bu bilgi değişikliği Super Admin incelemesinde. Yayındaki mevcut bilgi onay gelene kadar değişmez.</div>:null}{draftStatus==='rejected'?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-900"><strong>Düzeltme istendi.</strong>{editor.draft?.reviewNote?` ${editor.draft.reviewNote}`:''}</div>:null}
  {error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>:null}{notice?<div role="status" aria-live="polite" className="rounded-xl border border-green-200 bg-green-50 p-3 text-sm text-green-900">{notice}</div>:null}
  <div className="grid gap-4 lg:grid-cols-2"><Field label="Bilgi başlığı"><input value={draft.title} maxLength={180} onChange={e=>patch('title',e.target.value as any)} className="input"/></Field><Field label="Kısa özet"><input value={draft.summary} maxLength={1000} onChange={e=>patch('summary',e.target.value as any)} className="input"/></Field></div>
  <div className="grid gap-5 xl:grid-cols-2">
   <div className="space-y-4 rounded-2xl border p-4"><h3 className="flex items-center gap-2 font-black"><BookOpen aria-hidden="true" className="h-5 w-5 text-brand-gold"/>İçerik ve besin bilgisi</h3><Field label="İçindekiler - her satıra bir içerik"><textarea value={lines(draft.productInfo.ingredients)} onChange={e=>patchInfo('ingredients',toLines(e.target.value,80))} rows={6} className="textarea"/></Field><div className="grid gap-3 sm:grid-cols-3"><Small label="Porsiyon" value={draft.productInfo.nutrition.servingSize} onChange={v=>patchInfo('nutrition',{...draft.productInfo.nutrition,servingSize:v})}/><Small label="Enerji kcal" inputMode="decimal" value={draft.productInfo.nutrition.energyKcal} onChange={v=>patchInfo('nutrition',{...draft.productInfo.nutrition,energyKcal:v})}/><Small label="Protein g" inputMode="decimal" value={draft.productInfo.nutrition.proteinG} onChange={v=>patchInfo('nutrition',{...draft.productInfo.nutrition,proteinG:v})}/><Small label="Karbonhidrat g" inputMode="decimal" value={draft.productInfo.nutrition.carbohydrateG} onChange={v=>patchInfo('nutrition',{...draft.productInfo.nutrition,carbohydrateG:v})}/><Small label="Şeker g" inputMode="decimal" value={draft.productInfo.nutrition.sugarsG} onChange={v=>patchInfo('nutrition',{...draft.productInfo.nutrition,sugarsG:v})}/><Small label="Yağ g" inputMode="decimal" value={draft.productInfo.nutrition.fatG} onChange={v=>patchInfo('nutrition',{...draft.productInfo.nutrition,fatG:v})}/><Small label="Doymuş yağ g" inputMode="decimal" value={draft.productInfo.nutrition.saturatedFatG} onChange={v=>patchInfo('nutrition',{...draft.productInfo.nutrition,saturatedFatG:v})}/><Small label="Lif g" inputMode="decimal" value={draft.productInfo.nutrition.fiberG} onChange={v=>patchInfo('nutrition',{...draft.productInfo.nutrition,fiberG:v})}/><Small label="Tuz g" inputMode="decimal" value={draft.productInfo.nutrition.saltG} onChange={v=>patchInfo('nutrition',{...draft.productInfo.nutrition,saltG:v})}/></div><Field label="Kullanım notları - her satıra bir not"><textarea value={lines(draft.productInfo.usageNotes)} onChange={e=>patchInfo('usageNotes',toLines(e.target.value,30))} rows={4} className="textarea"/></Field></div>
   <div className="space-y-4 rounded-2xl border p-4"><h3 className="flex items-center gap-2 font-black"><ShieldCheck aria-hidden="true" className="h-5 w-5 text-brand-green"/>Gıda / ürün güvenliği</h3><Field label="Saklama - her satıra bir kural"><textarea value={lines(draft.safety.storage)} onChange={e=>patchSafety('storage',toLines(e.target.value,20))} rows={5} className="textarea"/></Field><Field label="Hazırlama / kullanım - her satıra bir adım"><textarea value={lines(draft.safety.preparation)} onChange={e=>patchSafety('preparation',toLines(e.target.value,30))} rows={5} className="textarea"/></Field><Field label="Uyarılar - her satıra bir uyarı"><textarea value={lines(draft.safety.warnings)} onChange={e=>patchSafety('warnings',toLines(e.target.value,20))} rows={4} className="textarea"/></Field><Field label="Bilinen alerjenler - her satıra bir alerjen"><textarea value={lines(draft.safety.allergens)} onChange={e=>patchSafety('allergens',toLines(e.target.value,30))} rows={3} className="textarea"/></Field><Field label="Alerjen / etiket notu"><textarea value={draft.safety.allergenNote} maxLength={1000} onChange={e=>patchSafety('allergenNote',e.target.value)} rows={3} className="textarea"/></Field></div>
  </div>
  <div className="rounded-2xl border p-4"><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={draft.recipe.enabled} onChange={e=>patchRecipe('enabled',e.target.checked)} className="h-5 w-5"/><span className="font-black"><Utensils aria-hidden="true" className="mr-2 inline h-5 w-5 text-brand-gold"/>Bu ürün için tarif yayınla</span></label>{draft.recipe.enabled?<div className="mt-4 space-y-4"><div className="grid gap-3 sm:grid-cols-4"><Field label="Tarif adı"><input value={draft.recipe.title} maxLength={180} onChange={e=>patchRecipe('title',e.target.value)} className="input"/></Field><Small label="Porsiyon" inputMode="numeric" value={draft.recipe.servings} onChange={v=>patchRecipe('servings',v)}/><Small label="Hazırlık dk" inputMode="numeric" value={draft.recipe.prepMinutes} onChange={v=>patchRecipe('prepMinutes',v)}/><Small label="Pişirme dk" inputMode="numeric" value={draft.recipe.cookMinutes} onChange={v=>patchRecipe('cookMinutes',v)}/></div><div className="grid gap-4 md:grid-cols-2"><Field label="Tarif malzemeleri - her satıra bir madde"><textarea value={lines(draft.recipe.ingredients)} onChange={e=>patchRecipe('ingredients',toLines(e.target.value,60))} rows={6} className="textarea"/></Field><Field label="Yapılış - her satıra bir adım"><textarea value={lines(draft.recipe.steps)} onChange={e=>patchRecipe('steps',toLines(e.target.value,40))} rows={6} className="textarea"/></Field></div></div>:<p className="mt-2 text-sm text-gray-500">Tarif zorunlu değildir. Uygun olmayan ürünlerde kapalı bırakın.</p>}</div>
  <div className="flex flex-col gap-2 sm:flex-row sm:justify-end"><button type="button" onClick={()=>void persist('save')} disabled={Boolean(busy)||draftStatus==='review'} className="min-h-11 rounded-xl border px-4 font-bold disabled:opacity-50"><Save aria-hidden="true" className="mr-2 inline h-4 w-4"/>{busy==='save'?'Kaydediliyor...':'Taslağı kaydet'}</button>{canPublish?<button type="button" onClick={()=>void persist('publish')} disabled={Boolean(busy)} className="min-h-11 rounded-xl bg-brand-green px-5 font-black text-white disabled:opacity-50">{busy==='publish'?'Yayınlanıyor...':'Müşteriye yayınla'}<ChevronRight aria-hidden="true" className="ml-2 inline h-4 w-4"/></button>:<button type="button" onClick={()=>void persist('submit')} disabled={Boolean(busy)||draftStatus==='review'} className="min-h-11 rounded-xl bg-blue-600 px-5 font-black text-white disabled:opacity-50"><Send aria-hidden="true" className="mr-2 inline h-4 w-4"/>{busy==='submit'?'Gönderiliyor...':'Super Admin incelemesine gönder'}</button>}</div>
 </section>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return<label className="block"><span className="mb-1 block text-sm font-semibold">{label}</span>{children}</label>;}
function Small({label,value,onChange,inputMode='text'}:{label:string;value:string;onChange:(value:string)=>void;inputMode?:React.HTMLAttributes<HTMLInputElement>['inputMode']}){return<Field label={label}><input inputMode={inputMode} value={value} onChange={e=>onChange(e.target.value)} className="input"/></Field>;}
