import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,BookOpen,RefreshCw,Search}from'lucide-react';
import{listMyProducerProducts}from'./api';
import ProductHealthEditorForm from'../content/ProductHealthEditorForm';
import{editorPayloadFromPublished,getSellerProductHealthEditor,productHealthErrorMessage,type SellerProductHealthEditor}from'../content/productHealthEditorApi';
import{EmptyState,ErrorState,LoadingState}from'../account/ui';

type ProductRow={id:string;name:string;slug:string;status:string};
export default function ProducerProductHealthManager({onBack}:{onBack:()=>void}){const[products,setProducts]=useState<ProductRow[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[query,setQuery]=useState('');const[selected,setSelected]=useState<ProductRow|null>(null);const[editor,setEditor]=useState<SellerProductHealthEditor|null>(null);const[editorLoading,setEditorLoading]=useState(false);
 async function load(){try{setLoading(true);setError('');const rows=await listMyProducerProducts();setProducts(rows.filter((row:any)=>row.status!=='archived').map((row:any)=>({id:String(row.id),name:String(row.name),slug:String(row.slug),status:String(row.status)})));}catch(err){setError(productHealthErrorMessage(err,'Ürünler yüklenemedi.'));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase('tr-TR');return q?products.filter(row=>`${row.name} ${row.slug}`.toLocaleLowerCase('tr-TR').includes(q)):products;},[products,query]);
 async function open(row:ProductRow){try{setSelected(row);setEditorLoading(true);setError('');setEditor(await getSellerProductHealthEditor(row.id));}catch(err){setSelected(null);setEditor(null);setError(productHealthErrorMessage(err,'Ürün bilgileri açılamadı.'));}finally{setEditorLoading(false);}}
 if(loading)return<LoadingState label="Ürün bilgileri yükleniyor"/>;if(selected&&editorLoading)return<LoadingState label="Ürün bilgi editörü yükleniyor"/>;if(selected&&editor){const initial=editor.pending?.payload||editorPayloadFromPublished(editor.published);return<ProductHealthEditorForm mode="seller" productId={editor.productId} productName={editor.productName} initial={initial} requestId={editor.pending?.requestId} onBack={()=>{setSelected(null);setEditor(null);}} onDone={async()=>setEditor(await getSellerProductHealthEditor(editor.productId))}/>;}
 return<div className="space-y-5"><header className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black">Ürün İçerik ve Sağlık Bilgileri</h2><p className="mt-1 max-w-3xl text-sm text-gray-500">İçindekiler, besin, alerjen, saklama, kullanım ve tarif bilgilerini yönetin. Gönderilen değişiklik mevcut müşteri yayınını bozmaz, Super Admin onayından sonra yayınlanır.</p></div><div className="flex gap-2"><button type="button" onClick={onBack} className="min-h-11 rounded-xl border px-4 font-semibold"><ArrowLeft aria-hidden="true" className="mr-2 inline h-4 w-4"/>Geri</button><button type="button" onClick={()=>void load()} className="min-h-11 rounded-xl border px-4 font-semibold"><RefreshCw aria-hidden="true" className="mr-2 inline h-4 w-4"/>Yenile</button></div></header>{error?<ErrorState message={error} onRetry={load}/>:null}<label className="relative block"><span className="sr-only">Ürün ara</span><Search aria-hidden="true" className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400"/><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ürün ara" className="min-h-11 w-full rounded-xl border pl-10 pr-3"/></label>{!filtered.length?<EmptyState title="Düzenlenebilir ürün yok" body="Ürün yönetiminde bir ürün oluşturduğunuzda burada görünecektir."/>:<div className="grid gap-3 sm:grid-cols-2">{filtered.map(row=><button type="button" key={row.id} onClick={()=>void open(row)} className="rounded-2xl border p-4 text-left hover:border-brand-green"><div className="flex items-start gap-3"><BookOpen aria-hidden="true" className="mt-0.5 h-5 w-5 shrink-0 text-brand-green"/><div><div className="font-black">{row.name}</div><div className="mt-1 text-xs text-gray-500">Ürün durumu: {row.status}</div><div className="mt-2 text-sm font-semibold text-brand-green">Bilgileri düzenle</div></div></div></button>)}</div>}</div>;}
