// Generated by scripts/product-photos/import.mjs. Representative photos shipped
// in public/product-photos; a real uploaded photo always takes precedence.
export const SHIPPED_PRODUCT_PHOTOS: readonly string[] = [
 "abidin-in-yayla-kuzusu-302",
 "amine-nin-cifte-sari-koy-yumurtasi-305",
 "ata-tohumu-dag-kekigi-suyu-distile-807",
 "avasin-cam-damacana-suyu-401",
 "avasin-deresi-canli-alabaligi-ozel-hasat-301",
 "avasin-mese-bali-103",
 "bercelan-yaylasi-bahar-cicek-bali-102",
 "buyuk-iskender-corek-otu-tohumu-705",
 "dag-cilegi-yabani-803",
 "daglica-karakovan-petek-bali-101",
 "eksi-karadut-suyu-804",
 "el-isciligi-mese-palamudu-ekmegi-505",
 "el-islemesi-tahta-kasik-ve-yayik-tokmagi-704",
 "fahrettin-in-sutten-kesilmis-oglagi-303",
 "gunes-sirri-guzu-yagi-ic-yag-701",
 "gunluk-taze-civik-sut-sagimdan-kapiya-204",
 "hakkari-dag-elmasi-801",
 "hakkari-dag-erigi-902",
 "hakkari-ham-propolisi-907",
 "hakkari-yayla-karpuzu-905",
 "hardaliye-geleneksel-805",
 "hatun-ana-nin-eksi-maya-gunesi-tarhana-501",
 "havahan-in-otlu-dag-peyniri-203",
 "sessiz-orman-kuzu-gobegi-mantari-601"
];
