// Generated by scripts/product-photos/import.mjs. Second (origin) photos shipped
// in public/product-photos/origin, shown as the second slide on the product page.
export const SHIPPED_ORIGIN_PHOTOS: readonly string[] = [];
