// Generated by scripts/product-photos/import.mjs. Representative photos shipped
// in public/product-photos; a real uploaded photo always takes precedence.
export const SHIPPED_PRODUCT_PHOTOS: readonly string[] = [];
