// Generated by scripts/product-photos/import.mjs. Representative photos shipped
// in public/product-photos; a real uploaded photo always takes precedence.
export const SHIPPED_PRODUCT_PHOTOS: readonly string[] = [
 "abidin-in-yayla-kuzusu-302",
 "ata-tohumu-dag-kekigi-suyu-distile-807",
 "avasin-cam-damacana-suyu-401",
 "avasin-mese-bali-103",
 "bercelan-yaylasi-bahar-cicek-bali-102",
 "hakkari-ham-propolisi-907",
 "sessiz-orman-kuzu-gobegi-mantari-601"
];
