-- Catalogue export for scripts/schema/build-baseline.mjs and compare-catalog.mjs.
-- Read-only. Returns one JSON document describing the application schemas.
-- On the live project run it in parts if a tool limits answer size: the
-- 'functions' key is the large one (about 1.5 MB).
with s as (select oid, nspname from pg_namespace where nspname in ('public','private','api_internal','api_public_bridge'))
select jsonb_build_object(
'schemas', (select jsonb_agg(jsonb_build_object('name',n.nspname,'acl',(select jsonb_agg(jsonb_build_object('grantee',coalesce(r.rolname,'PUBLIC'),'priv',a.privilege_type,'grantable',a.is_grantable)) from aclexplode(n.nspacl) a left join pg_roles r on r.oid=a.grantee),'comment',obj_description(n.oid,'pg_namespace'))) from pg_namespace n join s on s.oid=n.oid),
'sequences', (select jsonb_agg(jsonb_build_object('schema',s.nspname,'name',c.relname,'type',format_type(q.seqtypid,null),'start',q.seqstart,'inc',q.seqincrement,'min',q.seqmin,'max',q.seqmax,'cache',q.seqcache,'cycle',q.seqcycle,
   'owned',(select jsonb_build_object('table',tn.nspname||'.'||tc.relname,'col',a.attname,'identity',a.attidentity) from pg_depend d join pg_class tc on tc.oid=d.refobjid join pg_namespace tn on tn.oid=tc.relnamespace join pg_attribute a on a.attrelid=tc.oid and a.attnum=d.refobjsubid where d.objid=c.oid and d.deptype in ('a','i') limit 1),
   'acl',(select jsonb_agg(jsonb_build_object('grantee',coalesce(r.rolname,'PUBLIC'),'priv',a.privilege_type)) from aclexplode(c.relacl) a left join pg_roles r on r.oid=a.grantee))) from pg_class c join s on s.oid=c.relnamespace join pg_sequence q on q.seqrelid=c.oid),
'tables', (select jsonb_agg(jsonb_build_object('schema',s.nspname,'name',c.relname,'rls',c.relrowsecurity,'force',c.relforcerowsecurity,'replident',c.relreplident,'comment',obj_description(c.oid,'pg_class'),
   'columns',(select jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notnull',a.attnotnull,'default',pg_get_expr(ad.adbin,ad.adrelid),'identity',a.attidentity,'generated',a.attgenerated,'collation',case when a.attcollation<>t.typcollation and a.attcollation<>0 then (select collname from pg_collation where oid=a.attcollation) end,'comment',col_description(c.oid,a.attnum)) order by a.attnum) from pg_attribute a join pg_type t on t.oid=a.atttypid left join pg_attrdef ad on ad.adrelid=a.attrelid and ad.adnum=a.attnum where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped),
   'constraints',(select jsonb_agg(jsonb_build_object('name',k.conname,'type',k.contype,'def',pg_get_constraintdef(k.oid)) order by k.contype, k.conname) from pg_constraint k where k.conrelid=c.oid),
   'indexes',(select jsonb_agg(pg_get_indexdef(i.indexrelid) order by ic.relname) from pg_index i join pg_class ic on ic.oid=i.indexrelid where i.indrelid=c.oid and not exists(select 1 from pg_constraint k where k.conindid=i.indexrelid and k.conrelid=c.oid)),
   'triggers',(select jsonb_agg(jsonb_build_object('name',tg.tgname,'def',pg_get_triggerdef(tg.oid),'enabled',tg.tgenabled) order by tg.tgname) from pg_trigger tg where tg.tgrelid=c.oid and not tg.tgisinternal),
   'policies',(select jsonb_agg(jsonb_build_object('name',p.polname,'cmd',p.polcmd,'permissive',p.polpermissive,'roles',(select jsonb_agg(case when r=0 then 'public' else (select rolname from pg_roles where oid=r) end) from unnest(p.polroles) r),'using',pg_get_expr(p.polqual,p.polrelid),'check',pg_get_expr(p.polwithcheck,p.polrelid)) order by p.polname) from pg_policy p where p.polrelid=c.oid),
   'acl',(select jsonb_agg(jsonb_build_object('grantee',coalesce(r.rolname,'PUBLIC'),'priv',a.privilege_type)) from aclexplode(c.relacl) a left join pg_roles r on r.oid=a.grantee),
   'colacl',(select jsonb_agg(jsonb_build_object('col',at.attname,'grantee',coalesce(r.rolname,'PUBLIC'),'priv',a.privilege_type)) from pg_attribute at cross join aclexplode(at.attacl) a left join pg_roles r on r.oid=a.grantee where at.attrelid=c.oid and at.attacl is not null)
 ) order by s.nspname, c.relname) from pg_class c join s on s.oid=c.relnamespace where c.relkind in ('r','p')),
'views', (select jsonb_agg(jsonb_build_object('schema',s.nspname,'name',c.relname,'kind',c.relkind,'def',pg_get_viewdef(c.oid),'options',c.reloptions,'acl',(select jsonb_agg(jsonb_build_object('grantee',coalesce(r.rolname,'PUBLIC'),'priv',a.privilege_type)) from aclexplode(c.relacl) a left join pg_roles r on r.oid=a.grantee))) from pg_class c join s on s.oid=c.relnamespace where c.relkind in ('v','m')),
'defacl', (select jsonb_agg(jsonb_build_object('role',(select rolname from pg_roles where oid=d.defaclrole),'schema',(select nspname from pg_namespace where oid=d.defaclnamespace),'objtype',d.defaclobjtype,'acl',(select jsonb_agg(jsonb_build_object('grantee',coalesce(r.rolname,'PUBLIC'),'priv',a.privilege_type)) from aclexplode(d.defaclacl) a left join pg_roles r on r.oid=a.grantee))) from pg_default_acl d),
'evt', (select jsonb_agg(jsonb_build_object('name',e.evtname,'event',e.evtevent,'fn',p.oid::regprocedure::text,'tags',e.evttags,'enabled',e.evtenabled,'owner',(select rolname from pg_roles where oid=e.evtowner))) from pg_event_trigger e join pg_proc p on p.oid=e.evtfoid),
'functions', (select jsonb_agg(jsonb_build_object('sig',p.oid::regprocedure::text,'def',pg_get_functiondef(p.oid),'acl',(select jsonb_agg(jsonb_build_object('grantee',coalesce(r.rolname,'PUBLIC'),'priv',a.privilege_type)) from aclexplode(coalesce(p.proacl, acldefault('f',p.proowner))) a left join pg_roles r on r.oid=a.grantee),'comment',obj_description(p.oid,'pg_proc'),'owner',(select rolname from pg_roles where oid=p.proowner)) order by p.oid) from pg_proc p join s on s.oid=p.pronamespace where not exists(select 1 from pg_depend d where d.objid=p.oid and d.deptype='e'))
) as j;
