import {supabase} from'../lib/supabase';

export type FinanceTotals={order_count:number;gross_sales_minor:number;refund_minor:number;net_sales_minor:number;commission_minor:number;estimated_payout_minor:number;producer_gross_minor:number;paid_payout_minor:number;pending_payout_minor:number;captured_payment_minor:number;reconciliation_delta_minor:number;};
export type FinanceReportV2={currency:string;from:string;to:string;totals:FinanceTotals;daily_sales:Array<{date:string;order_count:number;gross_sales_minor:number;refund_minor:number;net_sales_minor:number}>;vendor_income:Array<{producer_id:string;vendor_name:string;order_count:number;gross_sales_minor:number;commission_minor:number;estimated_payout_minor:number}>;available_currencies:string[];};
export type AccountingPeriod={id:string;from:string;to:string;currency:string;status:'closed'|'archived';closedAt:string;archivedAt:string|null;cleanupCompletedAt:string|null;snapshot:FinanceReportV2;};
export type ClosePeriodResult={id:string;from:string;to:string;currency:string;archivedOrderCount:number;snapshot:FinanceReportV2;};
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function record(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function unwrap<T>(data:T|null,error:unknown):T{if(error)throw error;return data as T;}
function text(value:unknown,label:string,max:number){const next=typeof value==='string'?value.trim():'';if(!next||next.length>max||/[\u0000-\u001F\u007F]/.test(next))throw new Error(`${label} doğrulanamadı.`);return next;}
function dateOnly(value:unknown,label:string){const next=text(value,label,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(next))throw new Error(`${label} doğrulanamadı.`);return next;}
function dateTime(value:unknown,label:string,required=true){if(value==null||value===''){if(required)throw new Error(`${label} doğrulanamadı.`);return null;}const next=text(value,label,80);if(Number.isNaN(Date.parse(next)))throw new Error(`${label} doğrulanamadı.`);return next;}
function integer(value:unknown,label:string,min=Number.MIN_SAFE_INTEGER){if(typeof value!=='number'||!Number.isSafeInteger(value)||value<min)throw new Error(`${label} doğrulanamadı.`);return value;}
function nonnegative(value:unknown,label:string){return integer(value,label,0);}
function currency(value:unknown){const next=text(value,'Para birimi',3).toUpperCase();if(!/^[A-Z]{3}$/.test(next))throw new Error('Para birimi doğrulanamadı.');return next;}
function uuid(value:unknown,label:string){const next=text(value,label,36);if(!UUID_RE.test(next))throw new Error(`${label} doğrulanamadı.`);return next;}
function totals(value:unknown):FinanceTotals{if(!record(value))throw new Error('Finans toplamları doğrulanamadı.');const gross=nonnegative(value.gross_sales_minor,'Brüt satış'),refund=nonnegative(value.refund_minor,'İade'),net=integer(value.net_sales_minor,'Net satış');if(net!==gross-refund)throw new Error('Net satış hesabı tutarsız.');return{order_count:nonnegative(value.order_count,'Sipariş sayısı'),gross_sales_minor:gross,refund_minor:refund,net_sales_minor:net,commission_minor:integer(value.commission_minor,'Platform komisyonu'),estimated_payout_minor:integer(value.estimated_payout_minor,'Satıcı net hakedişi'),producer_gross_minor:integer(value.producer_gross_minor,'Satıcı brüt geliri'),paid_payout_minor:nonnegative(value.paid_payout_minor,'Ödenen hakediş'),pending_payout_minor:nonnegative(value.pending_payout_minor,'Bekleyen hakediş'),captured_payment_minor:nonnegative(value.captured_payment_minor,'Tahsil edilen ödeme'),reconciliation_delta_minor:integer(value.reconciliation_delta_minor,'Mutabakat farkı')};}
function report(value:unknown):FinanceReportV2{if(!record(value)||!Array.isArray(value.daily_sales)||!Array.isArray(value.vendor_income)||!Array.isArray(value.available_currencies))throw new Error('Finans raporu doğrulanamadı.');const reportCurrency=currency(value.currency),from=dateOnly(value.from,'Rapor başlangıcı'),to=dateOnly(value.to,'Rapor bitişi');const daily=value.daily_sales.map((row,index)=>{if(!record(row))throw new Error(`${index+1}. günlük finans kaydı doğrulanamadı.`);const gross=nonnegative(row.gross_sales_minor,'Günlük brüt satış'),refund=nonnegative(row.refund_minor,'Günlük iade'),net=integer(row.net_sales_minor,'Günlük net satış');if(net!==gross-refund)throw new Error('Günlük finans hesabı tutarsız.');return{date:dateOnly(row.date,'Finans günü'),order_count:nonnegative(row.order_count,'Günlük sipariş'),gross_sales_minor:gross,refund_minor:refund,net_sales_minor:net};});const vendors=value.vendor_income.map((row,index)=>{if(!record(row))throw new Error(`${index+1}. satıcı finans kaydı doğrulanamadı.`);return{producer_id:uuid(row.producer_id,'Satıcı kimliği'),vendor_name:text(row.vendor_name,'Satıcı adı',240),order_count:nonnegative(row.order_count,'Satıcı sipariş sayısı'),gross_sales_minor:integer(row.gross_sales_minor,'Satıcı brüt satış'),commission_minor:integer(row.commission_minor,'Satıcı komisyonu'),estimated_payout_minor:integer(row.estimated_payout_minor,'Satıcı net hakedişi')}});const availableCurrencies=[...new Set(value.available_currencies.map(currency))];if(!availableCurrencies.includes(reportCurrency))availableCurrencies.push(reportCurrency);return{currency:reportCurrency,from,to,totals:totals(value.totals),daily_sales:daily,vendor_income:vendors,available_currencies:availableCurrencies.sort()};}
export async function getFinanceReportV2(from:string,to:string,code:string){const{data,error}=await supabase.rpc('admin_finance_report_v2',{p_from:dateOnly(from,'Başlangıç'),p_to:dateOnly(to,'Bitiş'),p_currency:currency(code)});return report(unwrap<unknown>(data,error));}
export async function listAccountingPeriods():Promise<AccountingPeriod[]>{const{data,error}=await supabase.rpc('admin_list_accounting_periods_v1');const raw=unwrap<unknown>(data,error);if(!Array.isArray(raw)||raw.length>1000)throw new Error('Muhasebe dönemleri doğrulanamadı.');return raw.map((row,index)=>{if(!record(row))throw new Error(`${index+1}. muhasebe dönemi doğrulanamadı.`);const status=row.status;if(status!=='closed'&&status!=='archived')throw new Error('Muhasebe dönem durumu doğrulanamadı.');return{id:uuid(row.id,'Dönem kimliği'),from:dateOnly(row.from,'Dönem başlangıcı'),to:dateOnly(row.to,'Dönem bitişi'),currency:currency(row.currency),status,closedAt:dateTime(row.closedAt,'Dönem kapanış tarihi') as string,archivedAt:dateTime(row.archivedAt,'Arşiv tarihi',false),cleanupCompletedAt:dateTime(row.cleanupCompletedAt,'Temizlik tarihi',false),snapshot:report(row.snapshot)}});}
export async function closeAccountingPeriod(from:string,to:string,code:string):Promise<ClosePeriodResult>{const{data,error}=await supabase.rpc('super_admin_close_accounting_period_v1',{p_from:dateOnly(from,'Başlangıç'),p_to:dateOnly(to,'Bitiş'),p_currency:currency(code)});const raw=unwrap<unknown>(data,error);if(!record(raw))throw new Error('Dönem kapama sonucu doğrulanamadı.');return{id:uuid(raw.id,'Dönem kimliği'),from:dateOnly(raw.from,'Başlangıç'),to:dateOnly(raw.to,'Bitiş'),currency:currency(raw.currency),archivedOrderCount:nonnegative(raw.archivedOrderCount,'Arşivlenen sipariş sayısı'),snapshot:report(raw.snapshot)};}
export async function cleanupOperationalHistory(periodId:string){const id=uuid(periodId,'Dönem kimliği');const{data,error}=await supabase.rpc('super_admin_cleanup_operational_history_v1',{p_period_id:id});const raw=unwrap<unknown>(data,error);if(!record(raw)||uuid(raw.id,'Dönem kimliği')!==id||raw.financialRecordsPreserved!==true)throw new Error('Operasyonel geçmiş temizliği sonucu doğrulanamadı.');return{notificationsDeleted:nonnegative(raw.notificationsDeleted,'Silinen bildirim sayısı'),idempotencyDeleted:nonnegative(raw.idempotencyDeleted,'Silinen idempotency kaydı'),outboxDeleted:nonnegative(raw.outboxDeleted,'Silinen outbox kaydı'),errorDaysDeleted:nonnegative(raw.errorDaysDeleted,'Silinen hata günü')};}
export function accountingErrorMessage(error:unknown,fallback='Muhasebe işlemi tamamlanamadı.'){const message=String((error as{message?:unknown}|null)?.message||'').trim();const map:Array<[string,string]>=[['super_admin_required','Bu işlem yalnız Super Admin tarafından yapılabilir.'],['admin_required','Finans raporu için yönetici yetkisi gerekir.'],['invalid_finance_date_range','Rapor tarih aralığı geçersiz.'],['invalid_currency','Para birimi geçersiz.'],['accounting_period_overlap','Bu tarih aralığı aynı para biriminde daha önce kapatılmış bir dönemle çakışıyor.'],['open_orders_prevent_period_close','Bu dönemde tamamlanmamış sipariş var. Dönem kapatılamaz.'],['open_returns_prevent_period_close','Bu dönemde açık iade var. Dönem kapatılamaz.'],['accounting_period_not_found','Muhasebe dönemi bulunamadı.']];for(const[key,value]of map)if(message.includes(key))return value;return message||fallback;}
