import { supabase } from '../lib/supabase';

export type AccountAnonymizationResult={id:string;status:'anonymized';avatarPath:string|null;reviewMediaPaths:string[];ordersPreserved:number;paymentsPreserved:number;};
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function record(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function unwrap<T>(data:T|null,error:unknown):T{if(error)throw error;return data as T;}
function uuid(value:unknown,label:string){const next=typeof value==='string'?value.trim():'';if(!UUID_RE.test(next))throw new Error(`${label} doğrulanamadı.`);return next;}
function optionalPath(value:unknown,label:string){if(value==null||value==='')return null;if(typeof value!=='string')throw new Error(`${label} doğrulanamadı.`);const path=value.trim();if(!path||path.length>1200||/^[a-z][a-z0-9+.-]*:/i.test(path)||path.startsWith('/')||path.split('/').some(part=>!part||part==='.'||part==='..'))throw new Error(`${label} doğrulanamadı.`);return path;}
function paths(value:unknown,label:string){if(!Array.isArray(value)||value.length>1000)throw new Error(`${label} doğrulanamadı.`);return value.map((item,index)=>optionalPath(item,`${label} ${index+1}`)).filter((item):item is string=>Boolean(item));}
function integer(value:unknown,label:string){if(typeof value!=='number'||!Number.isSafeInteger(value)||value<0)throw new Error(`${label} doğrulanamadı.`);return value;}
export async function superAdminAnonymizeClosedUser(userId:string,reason:string):Promise<AccountAnonymizationResult>{const id=uuid(userId,'Kullanıcı kimliği');const clean=reason.trim();if(clean.length<8||clean.length>1000)throw new Error('Anonimleştirme gerekçesi 8 ile 1000 karakter arasında olmalıdır.');const{data,error}=await supabase.rpc('super_admin_anonymize_closed_user_v1',{p_user_id:id,p_reason:clean});const raw=unwrap<unknown>(data,error);if(!record(raw)||uuid(raw.id,'Kullanıcı kimliği')!==id||raw.status!=='anonymized')throw new Error('Anonimleştirme sonucu doğrulanamadı.');return{id,status:'anonymized',avatarPath:optionalPath(raw.avatarPath,'Avatar yolu'),reviewMediaPaths:paths(raw.reviewMediaPaths,'Yorum görselleri'),ordersPreserved:integer(raw.ordersPreserved,'Korunan sipariş sayısı'),paymentsPreserved:integer(raw.paymentsPreserved,'Korunan ödeme sayısı')};}
export async function cleanupAnonymizedUserMedia(result:AccountAnonymizationResult){const failures:string[]=[];if(result.avatarPath){const{error}=await supabase.storage.from('user-private').remove([result.avatarPath]);if(error)failures.push('avatar');}if(result.reviewMediaPaths.length){const{error}=await supabase.storage.from('review-media').remove(result.reviewMediaPaths);if(error)failures.push('yorum medyası');}return failures;}
export function accountErasureErrorMessage(error:unknown,fallback='Hesap anonimleştirme işlemi tamamlanamadı.'){const message=String((error as{message?:unknown}|null)?.message||'').trim();const map:Array<[string,string]>=[['super_admin_required','Bu işlem yalnız Super Admin tarafından yapılabilir.'],['cannot_anonymize_current_user','Kendi Super Admin hesabınızı anonimleştiremezsiniz.'],['account_must_be_closed_before_anonymization','Önce hesabı Kullanıcılar ekranından kalıcı olarak kapatmalısınız.'],['privileged_account_cannot_be_anonymized_here','Admin veya Super Admin hesabı bu akıştan anonimleştirilemez.'],['open_commerce_records_prevent_anonymization','Açık sipariş veya iade bulunduğu için kişisel veri temizliği henüz yapılamaz. Önce ticari süreçleri tamamlayın.'],['anonymization_reason_required','Anonimleştirme için açık bir gerekçe yazın.'],['user_not_found','Kullanıcı artık bulunamadı. Listeyi yenileyin.']];for(const[key,value]of map)if(message.includes(key))return value;return message||fallback;}
