import React,{useEffect,useState}from'react';
import{KeyRound,Loader2,Plus,RefreshCw,ShieldCheck,Trash2,X}from'lucide-react';
import{beginBackupStaffTotpEnrollment,cancelStaffTotpEnrollment,getAuthenticatorAssuranceLevel,listStaffTotpFactors,removeVerifiedStaffTotpFactor,verifyStaffTotpEnrollment,type StaffTotpEnrollment,type StaffTotpFactor}from'../features/auth/mfaApi';
import{useAuthorization}from'../features/auth/AuthorizationContext';

function safeError(error:unknown){const message=error instanceof Error?error.message:'';return message&&message.length<=500?message:'Authenticator güvenlik işlemi tamamlanamadı.';}
function shortId(value:string){return value.length>12?`${value.slice(0,6)}…${value.slice(-6)}`:value;}

export default function AdminMfaSecurity(){
 const{snapshot,refresh:refreshAuthorization}=useAuthorization();
 const[factors,setFactors]=useState<StaffTotpFactor[]>([]);
 const[aal,setAal]=useState<'aal1'|'aal2'>('aal1');
 const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState('');
 const[enrollment,setEnrollment]=useState<StaffTotpEnrollment|null>(null),[code,setCode]=useState('');
 const[removeTarget,setRemoveTarget]=useState<StaffTotpFactor|null>(null),[removeConfirm,setRemoveConfirm]=useState('');

 async function load(){setLoading(true);setError('');try{const[nextFactors,assurance]=await Promise.all([listStaffTotpFactors(),getAuthenticatorAssuranceLevel()]);setFactors(nextFactors.filter(item=>item.status==='verified'));setAal(assurance.currentLevel);}catch(next){setError(safeError(next));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 function show(message:string){setToast(message);window.setTimeout(()=>setToast(''),4000);}
 async function startBackup(){if(busy)return;setBusy(true);setError('');try{setEnrollment(await beginBackupStaffTotpEnrollment());setCode('');}catch(next){setError(safeError(next));}finally{setBusy(false);}}
 async function cancelBackup(){if(!enrollment||busy)return;setBusy(true);setError('');try{await cancelStaffTotpEnrollment(enrollment.factorId);setEnrollment(null);setCode('');}catch(next){setError(safeError(next));}finally{setBusy(false);}}
 async function verifyBackup(event:React.FormEvent){event.preventDefault();if(!enrollment||busy||!/^[0-9]{6}$/.test(code))return;setBusy(true);setError('');try{await verifyStaffTotpEnrollment(enrollment.factorId,code);setEnrollment(null);setCode('');await Promise.all([load(),refreshAuthorization()]);show('Yedek authenticator doğrulandı. Diğer oturumlar Supabase MFA politikası gereği kapatıldı.');}catch(next){setError(safeError(next));setCode('');}finally{setBusy(false);}}
 async function removeFactor(){if(!removeTarget||busy||removeConfirm!=='KALDIR')return;setBusy(true);setError('');try{await removeVerifiedStaffTotpFactor(removeTarget.id);setRemoveTarget(null);setRemoveConfirm('');await Promise.all([load(),refreshAuthorization()]);show('Authenticator kaydı güvenli şekilde kaldırıldı.');}catch(next){setError(safeError(next));}finally{setBusy(false);}}

 if(loading)return<div role="status" className="flex min-h-52 items-center justify-center gap-2 text-sm font-semibold text-gray-500"><Loader2 aria-hidden="true" className="h-5 w-5 animate-spin"/>Authenticator güvenliği doğrulanıyor…</div>;
 return<div className="space-y-6">
  <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-black text-gray-900 dark:text-white">Yönetim MFA ve Authenticator</h2><p className="mt-1 max-w-3xl text-sm text-gray-500 dark:text-gray-400">Personel yönetim capability'leri doğrulanmış TOTP ve AAL2 oturumuyla korunur. Supabase recovery code üretmediği için en az bir yedek authenticator önerilir.</p></div><button type="button" onClick={()=>void load()} disabled={busy} className="min-h-11 rounded-xl border border-gray-200 px-4 font-bold dark:border-gray-700"><RefreshCw aria-hidden="true" className="mr-2 inline h-4 w-4"/>Yenile</button></header>
  {error?<div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200">{error}</div>:null}
  {toast?<div role="status" className="rounded-2xl border border-green-200 bg-green-50 p-4 text-sm font-semibold text-green-800 dark:border-green-900/60 dark:bg-green-950/30 dark:text-green-200">{toast}</div>:null}
  <section className="grid gap-3 sm:grid-cols-3"><Metric label="Oturum güven seviyesi" value={aal.toUpperCase()}/><Metric label="Doğrulanmış TOTP" value={String(factors.length)}/><Metric label="Backend enforcement" value={snapshot?.mfaEnforcementActive?'Aktif':'Geçiş'}/></section>
  <section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><ShieldCheck aria-hidden="true" className="h-5 w-5 text-brand-green"/><h3 className="font-black">Doğrulanmış authenticator cihazları</h3></div><p className="mt-1 text-sm text-gray-500">Son faktör silinemez. Yedek faktörü farklı bir cihaz veya güvenli authenticator profili üzerinde tutun.</p></div>{!enrollment?<button type="button" onClick={()=>void startBackup()} disabled={busy||aal!=='aal2'||factors.length<1} className="min-h-11 shrink-0 rounded-xl bg-brand-green px-4 font-bold text-brand-on-green disabled:opacity-40"><Plus aria-hidden="true" className="mr-1 inline h-4 w-4"/>Yedek ekle</button>:null}</div><div className="mt-4 space-y-3">{factors.map((factor,index)=><article key={factor.id} className="flex flex-col gap-3 rounded-xl border border-gray-200 p-4 dark:border-gray-700 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="font-bold">{factor.friendlyName}</div><div className="mt-1 text-xs text-gray-500">Faktör {index+1} · {shortId(factor.id)} · doğrulanmış</div></div><button type="button" onClick={()=>{setRemoveTarget(factor);setRemoveConfirm('');setError('');}} disabled={busy||factors.length<=1} className="min-h-11 rounded-xl border border-red-200 px-4 font-bold text-red-700 disabled:opacity-35 dark:border-red-900/60 dark:text-red-300"><Trash2 aria-hidden="true" className="mr-1 inline h-4 w-4"/>Kaldır</button></article>)}{!factors.length?<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-semibold text-amber-900 dark:border-amber-900/60 dark:bg-amber-950/30 dark:text-amber-100">Doğrulanmış TOTP faktörü bulunamadı. Yönetim giriş kapısı ilk kurulumu tamamlamadan bu alanı açmamalıdır.</div>:null}</div></section>
  {enrollment?<section className="rounded-2xl border border-brand-gold/40 bg-white p-5 dark:bg-gray-800"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black">Yedek authenticator kurulumu</h3><p className="mt-1 text-sm text-gray-500">QR kodunu yedek cihazdaki authenticator ile tarayın ve oluşan 6 haneli kodu doğrulayın.</p></div><button type="button" onClick={()=>void cancelBackup()} disabled={busy} className="min-h-11 min-w-11 rounded-xl border" aria-label="Yedek kurulumu iptal et"><X aria-hidden="true" className="mx-auto h-5 w-5"/></button></div><div className="mt-4 grid gap-4 md:grid-cols-[280px_1fr]"><div className="rounded-2xl border bg-white p-3"><img src={enrollment.qrCode} alt="Yedek Golden Oremar TOTP authenticator QR kodu" className="mx-auto w-full max-w-[260px]"/></div><div><div className="text-xs font-black uppercase tracking-wider text-gray-500">Elle kurulum anahtarı</div><code className="mt-2 block break-all rounded-xl bg-black/5 p-3 text-sm font-bold dark:bg-white/5">{enrollment.secret}</code><form onSubmit={verifyBackup} className="mt-4 space-y-3"><label className="block"><span className="mb-1 block text-sm font-bold">6 haneli kod</span><input required inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" minLength={6} maxLength={6} value={code} onChange={event=>setCode(event.target.value.replace(/\D/g,'').slice(0,6))} disabled={busy} className="min-h-12 w-full rounded-xl border px-4 text-center text-xl font-black tracking-[0.3em]"/></label><button type="submit" disabled={busy||!/^[0-9]{6}$/.test(code)} className="min-h-12 w-full rounded-xl bg-brand-green font-black text-brand-on-green disabled:opacity-40">{busy?'Doğrulanıyor…':'Yedek faktörü doğrula'}</button></form></div></div></section>:null}
  {removeTarget?<div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/70 sm:items-center sm:p-4"><div role="alertdialog" aria-modal="true" aria-labelledby="remove-mfa-title" className="w-full max-w-lg rounded-t-3xl bg-white p-5 shadow-2xl dark:bg-gray-900 sm:rounded-3xl"><h3 id="remove-mfa-title" className="text-xl font-black">Authenticator kaydını kaldır</h3><p className="mt-2 text-sm text-gray-500">{removeTarget.friendlyName} kaldırılacak. Bu işlem yalnız başka doğrulanmış faktör kaldığında yapılabilir.</p><label className="mt-4 block"><span className="mb-1 block text-sm font-bold">Onay için KALDIR yazın</span><input value={removeConfirm} onChange={event=>setRemoveConfirm(event.target.value)} disabled={busy} autoComplete="off" className="min-h-11 w-full rounded-xl border px-3"/></label><div className="mt-4 grid grid-cols-2 gap-3"><button type="button" onClick={()=>{setRemoveTarget(null);setRemoveConfirm('');}} disabled={busy} className="min-h-11 rounded-xl border font-bold">Vazgeç</button><button type="button" onClick={()=>void removeFactor()} disabled={busy||removeConfirm!=='KALDIR'} className="min-h-11 rounded-xl bg-red-700 font-black text-white disabled:opacity-40">{busy?'Kaldırılıyor…':'Kalıcı kaldır'}</button></div></div></div>:null}
 </div>;
}
function Metric({label,value}:{label:string;value:string}){return<div className="rounded-2xl border border-gray-200 bg-white p-4 text-center dark:border-gray-700 dark:bg-gray-800"><div className="text-xl font-black"><KeyRound aria-hidden="true" className="mr-1 inline h-4 w-4 text-brand-green"/>{value}</div><div className="mt-1 text-xs font-semibold text-gray-500">{label}</div></div>;}
