import React,{useEffect,useMemo,useState}from'react';
import{CheckCircle2,PackageCheck,RefreshCw,Save,Search,Truck,XCircle}from'lucide-react';
import{listShippingWeightReadiness,shippingReadinessErrorMessage,updateVerifiedShippingWeight,type ShippingWeightRow}from'./shippingReadinessAdminApi';

function kg(value:number|null){return value==null?'-':`${(value/1000).toLocaleString('tr-TR',{maximumFractionDigits:3})} kg`;}
export function AdminShippingReadiness(){
 const[rows,setRows]=useState<ShippingWeightRow[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[search,setSearch]=useState(''),[view,setView]=useState<'missing'|'all'>('missing'),[editingId,setEditingId]=useState<string|null>(null),[weightInput,setWeightInput]=useState(''),[note,setNote]=useState(''),[saving,setSaving]=useState(false);
 async function load(initial=false){try{initial?setLoading(true):setRefreshing(true);setError('');setRows(await listShippingWeightReadiness());}catch(next){setError(shippingReadinessErrorMessage(next,'Kargo ağırlıkları yüklenemedi.'));}finally{setLoading(false);setRefreshing(false);}}
 useEffect(()=>{void load(true);},[]);
 const missingCount=rows.filter(row=>row.missingWeight).length;
 const filtered=useMemo(()=>{const q=search.trim().toLocaleLowerCase('tr-TR');return rows.filter(row=>(view==='all'||row.missingWeight)&&(!q||`${row.productName} ${row.variantName} ${row.sku||''} ${row.producerName}`.toLocaleLowerCase('tr-TR').includes(q)));},[rows,view,search]);
 function edit(row:ShippingWeightRow){setEditingId(row.variantId);setWeightInput(row.weightGrams!=null?String(row.weightGrams):'');setNote('');setError('');setStatus('');}
 async function save(row:ShippingWeightRow){if(saving)return;const weight=Number(weightInput);try{setSaving(true);setError('');setStatus('');const result=await updateVerifiedShippingWeight({row,weightGrams:weight,verificationNote:note});setRows(items=>items.map(item=>item.variantId===row.variantId?{...item,weightGrams:result.weightGrams,missingWeight:false,updatedAt:result.updatedAt}:item));setEditingId(null);setWeightInput('');setNote('');setStatus(`${row.productName} - ${row.variantName} için doğrulanmış kargo ağırlığı kaydedildi.`);}catch(next){setError(shippingReadinessErrorMessage(next));}finally{setSaving(false);}}
 if(loading)return<div role="status" className="flex min-h-64 items-center justify-center rounded-2xl border bg-white p-6 dark:bg-gray-800">Kargo hazırlığı denetleniyor...</div>;
 return<div className="space-y-6"><header className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-2"><Truck className="h-7 w-7 text-brand-green" aria-hidden="true"/><h2 className="text-2xl font-bold">Kargo Hazırlığı</h2></div><p className="mt-2 max-w-3xl text-sm text-gray-500">Yayındaki varyantların gerçek gönderi ağırlığını gram cinsinden doğrular. Ağırlık kargo fiyatını etkilediği için değişiklik doğrulama notuyla audit log'a yazılır ve eşzamanlı satıcı değişikliği varsa işlem reddedilir.</p></div><button type="button" onClick={()=>void load(false)} disabled={refreshing||saving} className="min-h-11 rounded-xl border bg-white px-4 font-semibold disabled:opacity-50 dark:bg-gray-800"><RefreshCw className={`mr-2 inline h-4 w-4 ${refreshing?'animate-spin':''}`} aria-hidden="true"/>Yenile</button></header>
 {error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{error}</div>:null}{status?<div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-800">{status}</div>:null}
 <section className="grid gap-3 sm:grid-cols-3"><button type="button" onClick={()=>setView('missing')} aria-pressed={view==='missing'} className={`rounded-2xl border p-4 text-left ${view==='missing'?'border-red-300 bg-red-50':'bg-white dark:bg-gray-800'}`}><XCircle className="h-5 w-5 text-red-600" aria-hidden="true"/><div className="mt-2 text-2xl font-bold">{missingCount}</div><div className="text-sm font-semibold">Ağırlığı eksik</div></button><button type="button" onClick={()=>setView('all')} aria-pressed={view==='all'} className={`rounded-2xl border p-4 text-left ${view==='all'?'border-brand-green/50 bg-green-50':'bg-white dark:bg-gray-800'}`}><PackageCheck className="h-5 w-5 text-brand-green" aria-hidden="true"/><div className="mt-2 text-2xl font-bold">{rows.length}</div><div className="text-sm font-semibold">Aktif varyant</div></button><div className="rounded-2xl border bg-white p-4 dark:bg-gray-800"><CheckCircle2 className="h-5 w-5 text-emerald-600" aria-hidden="true"/><div className="mt-2 text-2xl font-bold">{rows.length-missingCount}</div><div className="text-sm font-semibold">Ağırlığı hazır</div></div></section>
 <section className="rounded-2xl border bg-white dark:bg-gray-800"><div className="border-b p-4"><label className="relative block max-w-xl"><span className="sr-only">Ürün veya üretici ara</span><Search className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400" aria-hidden="true"/><input type="search" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Ürün, varyant, SKU veya üretici ara..." className="min-h-11 w-full rounded-xl border bg-gray-50 py-2 pl-10 pr-4 dark:bg-gray-900"/></label></div><div className="divide-y">{filtered.map(row=>{const editing=editingId===row.variantId;return<article key={row.variantId} className="p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-bold">{row.productName}</h3><p className="mt-1 text-sm text-gray-500">{row.variantName} · {row.sku||'SKU yok'} · {row.producerName}</p><p className="mt-2 text-sm"><strong>Mevcut ağırlık:</strong> {kg(row.weightGrams)} {row.missingWeight?<span className="ml-2 rounded-full bg-red-50 px-2 py-1 text-xs font-bold text-red-700">Eksik</span>:<span className="ml-2 rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700">Hazır</span>}</p></div>{!editing?<button type="button" onClick={()=>edit(row)} disabled={saving||editingId!==null} className="min-h-11 rounded-xl border px-4 font-semibold disabled:opacity-50">Doğrulanmış ağırlığı gir</button>:null}</div>{editing?<div className="mt-4 grid gap-3 rounded-2xl border bg-gray-50 p-4 dark:bg-gray-900 sm:grid-cols-2"><label><span className="text-sm font-bold">Ağırlık - gram</span><input type="number" min={1} max={100000000} step={1} value={weightInput} onChange={event=>setWeightInput(event.target.value)} inputMode="numeric" className="mt-2 min-h-11 w-full rounded-xl border px-3" placeholder="Örn. 850"/></label><label><span className="text-sm font-bold">Doğrulama kaynağı/notu</span><input value={note} onChange={event=>setNote(event.target.value)} minLength={10} maxLength={500} className="mt-2 min-h-11 w-full rounded-xl border px-3" placeholder="Üretici ambalaj ölçümü, tartım kaydı vb."/></label><div className="flex gap-2 sm:col-span-2"><button type="button" onClick={()=>{setEditingId(null);setWeightInput('');setNote('');}} disabled={saving} className="min-h-11 flex-1 rounded-xl border px-4 font-semibold disabled:opacity-50">Vazgeç</button><button type="button" onClick={()=>void save(row)} disabled={saving||!Number.isSafeInteger(Number(weightInput))||Number(weightInput)<1||note.trim().length<10} className="min-h-11 flex-1 rounded-xl bg-brand-green px-4 font-bold text-brand-on-green disabled:opacity-50"><Save className="mr-2 inline h-4 w-4" aria-hidden="true"/>{saving?'Kaydediliyor...':'Kaydet'}</button></div></div>:null}</article>;})}{filtered.length===0?<div className="p-10 text-center text-gray-500">Bu görünümde eşleşen varyant yok.</div>:null}</div></section>
 </div>;
}
