import React,{useEffect,useState}from'react';
import{AlertTriangle,BadgeCheck,Boxes,Check,CircleDollarSign,FileCheck2,Loader2,Package,RefreshCw,RotateCcw,ShoppingBag,Store,Users}from'lucide-react';
import{dashboardErrorMessage,formatMinor,getAdminOperationsOverview,type AdminOperationsOverview}from'./dashboardApi';

interface AdminDashboardProps{setActiveTab?:(tab:string)=>void;}
function StatCard({label,value,helper,icon}:{label:string;value:React.ReactNode;helper?:string;icon:React.ReactNode}){return <div className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800"><div className="flex items-start justify-between gap-3"><div><div className="text-sm font-medium text-gray-500 dark:text-gray-400">{label}</div><div className="mt-2 text-2xl font-bold text-gray-900 dark:text-white">{value}</div>{helper?<div className="mt-1 text-xs text-gray-500 dark:text-gray-400">{helper}</div>:null}</div><div className="rounded-xl bg-brand-green/10 p-2.5 text-brand-green">{icon}</div></div></div>;}

function AdminOverview({data,setActiveTab}:{data:AdminOperationsOverview;setActiveTab?:(tab:string)=>void}){
 const queueRows=[
  {key:'vendor-applications',label:'Satıcı başvuruları',value:data.counts.producer_applications,helper:'Gönderilen, incelenen veya ek bilgi bekleyen',icon:<Store className="h-5 w-5" aria-hidden="true"/>},
  {key:'product-approvals',label:'Ürün incelemeleri',value:data.counts.product_reviews,helper:'Yayın öncesi onay bekleyen ürünler',icon:<Package className="h-5 w-5" aria-hidden="true"/>},
  {key:'reviews',label:'Yorum moderasyonu',value:data.counts.review_moderation,helper:'Onay bekleyen müşteri yorumları',icon:<FileCheck2 className="h-5 w-5" aria-hidden="true"/>},
  {key:'orders',label:'Açık siparişler',value:data.counts.open_orders,helper:'Aktif sipariş yaşam döngüsündeki kayıtlar',icon:<ShoppingBag className="h-5 w-5" aria-hidden="true"/>},
 ];
 return <div className="space-y-6">
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard label="Aktif kullanıcı" value={data.counts.active_users.toLocaleString('tr-TR')} helper="Silinmemiş aktif hesaplar" icon={<Users className="h-5 w-5" aria-hidden="true"/>}/><StatCard label="Doğrulanmış üretici" value={data.counts.verified_producers.toLocaleString('tr-TR')} helper="Aktif ve kimliği doğrulanmış" icon={<BadgeCheck className="h-5 w-5" aria-hidden="true"/>}/><StatCard label="Yayındaki ürün" value={data.counts.published_products.toLocaleString('tr-TR')} helper="Aktif katalog ürünleri" icon={<Boxes className="h-5 w-5" aria-hidden="true"/>}/><StatCard label="İade talepleri" value={data.counts.return_requests.toLocaleString('tr-TR')} helper="Açık iade iş akışları" icon={<RotateCcw className="h-5 w-5" aria-hidden="true"/>}/></div>
  <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800" aria-labelledby="finance-summary-title"><div className="flex items-start justify-between gap-3"><div><h2 id="finance-summary-title" className="text-lg font-bold text-gray-900 dark:text-white">Tahsilat Özeti</h2><p className="mt-1 text-xs text-gray-500">Gerçek ödeme ve başarılı iade hareketlerinden hesaplanır.</p></div><CircleDollarSign className="h-5 w-5 text-gray-400" aria-hidden="true"/></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{data.finance_by_currency.map(row=><div key={row.currency} className="rounded-xl bg-gray-50 p-4 dark:bg-gray-900/60"><div className="text-xs font-semibold text-gray-500">{row.currency}</div><div className="mt-2 text-xl font-bold text-gray-900 dark:text-white">{formatMinor(row.net_collected_minor,row.currency)}</div><div className="mt-2 grid grid-cols-2 gap-2 text-xs"><div><span className="text-gray-500">Tahsil</span><div className="font-medium text-gray-800 dark:text-gray-200">{formatMinor(row.captured_minor,row.currency)}</div></div><div><span className="text-gray-500">İade</span><div className="font-medium text-gray-800 dark:text-gray-200">{formatMinor(row.refunded_minor,row.currency)}</div></div></div></div>)}{data.finance_by_currency.length===0?<div className="py-5 text-center text-sm text-gray-500 sm:col-span-2 xl:col-span-3">Henüz doğrulanmış ödeme hareketi yok.</div>:null}</div></section>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Operasyon kuyrukları">{queueRows.map(row=><button key={row.key} type="button" onClick={()=>setActiveTab?.(row.key)} className="min-h-32 rounded-2xl border border-gray-100 bg-white p-5 text-left shadow-sm transition hover:border-brand-green/40 hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-green dark:border-gray-700 dark:bg-gray-800"><div className="flex items-start justify-between gap-3"><div className="rounded-xl bg-brand-green/10 p-2.5 text-brand-green">{row.icon}</div><div className="text-2xl font-black text-gray-900 dark:text-white">{row.value}</div></div><div className="mt-4 font-semibold text-gray-900 dark:text-white">{row.label}</div><div className="mt-1 text-xs text-gray-500">{row.helper}</div></button>)}</section>
  <div className="grid gap-4 lg:grid-cols-2"><section className="overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm dark:border-gray-700 dark:bg-gray-800" aria-labelledby="recent-orders-title"><div className="border-b border-gray-100 p-5 dark:border-gray-700"><h2 id="recent-orders-title" className="font-bold text-gray-900 dark:text-white">Son Siparişler</h2><p className="mt-1 text-xs text-gray-500">En yeni gerçek siparişler.</p></div><div className="divide-y divide-gray-100 dark:divide-gray-700">{data.recent_orders.map(order=><button key={order.id} type="button" onClick={()=>setActiveTab?.('orders')} className="flex min-h-16 w-full items-center justify-between gap-3 p-4 text-left hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-brand-gold dark:hover:bg-gray-700/40"><div className="min-w-0"><div className="truncate font-semibold text-gray-900 dark:text-white">{order.order_number}</div><div className="mt-1 text-xs text-gray-500">{order.status} · {order.payment_status} · {order.fulfillment_status}</div></div><div className="shrink-0 text-right"><div className="font-semibold text-gray-900 dark:text-white">{formatMinor(order.total_minor,order.currency)}</div><div className="mt-1 text-xs text-gray-500">{new Date(order.created_at).toLocaleDateString('tr-TR')}</div></div></button>)}{data.recent_orders.length===0?<div className="p-8 text-center text-sm text-gray-500">Henüz sipariş yok.</div>:null}</div></section><section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800" aria-labelledby="admin-queue-title"><h2 id="admin-queue-title" className="font-bold text-gray-900 dark:text-white">Diğer Yönetim Kuyrukları</h2><div className="mt-4 grid grid-cols-2 gap-3"><QueueMetric label="Ürün değişiklik talepleri" value={data.counts.product_change_requests}/><QueueMetric label="Destek konuşmaları" value={data.counts.support_conversations}/><QueueMetric label="Hesap kapatma talepleri" value={data.counts.account_closures}/><QueueMetric label="İşlenen satıcı ödemeleri" value={data.counts.producer_payouts}/></div></section></div>
 </div>;
}
function QueueMetric({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-gray-50 p-4 dark:bg-gray-900/60"><div className="text-xs text-gray-500">{label}</div><div className="mt-1 text-2xl font-bold text-gray-900 dark:text-white">{value.toLocaleString('tr-TR')}</div></div>;}

export function AdminDashboard({setActiveTab}:AdminDashboardProps={}){
 const[data,setData]=useState<AdminOperationsOverview|null>(null);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[error,setError]=useState('');const[toast,setToast]=useState('');
 async function load(initial=false){try{if(initial)setLoading(true);else setRefreshing(true);setError('');const next=await getAdminOperationsOverview();setData(next);return true;}catch(err){setError(dashboardErrorMessage(err));return false;}finally{setLoading(false);setRefreshing(false);}}
 useEffect(()=>{void load(true);},[]);
 async function refresh(){const ok=await load(false);if(ok){setToast('Panel verileri yenilendi.');window.setTimeout(()=>setToast(''),2500);}}
 if(loading&&!data)return <div role="status" className="flex min-h-64 items-center justify-center gap-2 text-gray-500"><Loader2 className="h-5 w-5 animate-spin" aria-hidden="true"/>Canlı yönetim verileri yükleniyor...</div>;
 return <div className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold text-gray-900 dark:text-white">Yönetim Genel Bakış</h1><p className="mt-1 text-sm text-gray-500 dark:text-gray-400">Bu ekran yalnız sunucuda doğrulanan yönetim metriklerini gösterir.</p></div><button type="button" disabled={refreshing} onClick={()=>void refresh()} className="flex min-h-11 items-center justify-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2 font-semibold text-gray-700 hover:bg-gray-50 disabled:cursor-wait disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold dark:border-gray-700 dark:bg-gray-800 dark:text-gray-200"><RefreshCw className={`h-4 w-4 ${refreshing?'animate-spin':''}`} aria-hidden="true"/>{refreshing?'Yenileniyor…':'Yenile'}</button></header>{error?<div role="alert" className="flex items-start gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800 dark:border-red-900/50 dark:bg-red-950/30 dark:text-red-200"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0" aria-hidden="true"/><div><div>{error}</div>{!data?<button type="button" onClick={()=>void load(true)} className="mt-3 min-h-11 rounded-xl border border-red-300 px-4 font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500 dark:border-red-800">Tekrar dene</button>:null}</div></div>:null}{data?<AdminOverview data={data} setActiveTab={setActiveTab}/>:null}{toast?<div role="status" aria-live="polite" className="fixed bottom-4 right-4 z-[70] flex items-center gap-2 rounded-xl bg-gray-900 px-5 py-3 text-white shadow-2xl"><Check className="h-5 w-5 text-green-400" aria-hidden="true"/>{toast}</div>:null}</div>;
}
