import React,{useEffect,useState}from'react';
import{AlertTriangle,BadgeCheck,Boxes,Check,CircleDollarSign,Database,FileCheck2,FolderArchive,HardDrive,Image,Loader2,Package,RefreshCw,RotateCcw,ShoppingBag,Store,Tags,Users,WalletCards}from'lucide-react';
import{dashboardErrorMessage,formatMinor,getAdminOperationsOverview,type AdminOperationsOverview}from'./dashboardApi';

interface AdminDashboardProps{setActiveTab?:(tab:string)=>void;}
function StatCard({label,value,helper,icon,onClick}:{label:string;value:React.ReactNode;helper?:string;icon:React.ReactNode;onClick?:()=>void}){const body=<><div className="flex items-start justify-between gap-3"><div><div className="text-sm font-medium text-gray-500 dark:text-gray-400">{label}</div><div className="mt-2 text-2xl font-black tracking-tight text-gray-950 dark:text-white">{value}</div>{helper?<div className="mt-1 text-xs text-gray-500 dark:text-gray-400">{helper}</div>:null}</div><div className="rounded-xl bg-brand-green/10 p-2.5 text-brand-green">{icon}</div></div></>;return onClick?<button type="button" onClick={onClick} className="rounded-2xl border border-gray-100 bg-white p-5 text-left shadow-sm transition hover:border-brand-green/40 hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-green dark:border-gray-700 dark:bg-gray-800">{body}</button>:<div className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800">{body}</div>;}
function Mini({label,value}:{label:string;value:React.ReactNode}){return <div className="rounded-xl bg-gray-50 p-3 dark:bg-gray-900/60"><div className="text-xs text-gray-500">{label}</div><div className="mt-1 font-bold text-gray-950 dark:text-white">{value}</div></div>;}

function Overview({data,setActiveTab}:{data:AdminOperationsOverview;setActiveTab?:(tab:string)=>void}){
 const c=data.counts;
 const queueRows=[
  {key:'vendor-applications',label:'Satıcı başvuruları',value:c.producer_applications,helper:'İnceleme veya ek bilgi bekliyor',icon:<Store className="h-5 w-5" aria-hidden="true"/>},
  {key:'product-approvals',label:'Ürün incelemeleri',value:c.product_reviews,helper:'Yayın öncesi onay bekliyor',icon:<Package className="h-5 w-5" aria-hidden="true"/>},
  {key:'reviews',label:'Yorum moderasyonu',value:c.review_moderation,helper:'Müşteri yorumu incelemesi',icon:<FileCheck2 className="h-5 w-5" aria-hidden="true"/>},
  {key:'orders',label:'Havuz onayları',value:c.settlements_waiting,helper:'Tamamlanan sipariş, satıcı release bekliyor',icon:<WalletCards className="h-5 w-5" aria-hidden="true"/>},
 ];
 return <div className="space-y-6">
  <section aria-labelledby="ecosystem-title"><div className="mb-3 flex items-end justify-between gap-3"><div><h2 id="ecosystem-title" className="text-lg font-bold">Canlı Ekosistem</h2><p className="mt-1 text-xs text-gray-500">Sayaçların tamamı Supabase'deki gerçek kayıtlardan hesaplanır.</p></div><span className="text-xs text-gray-500">{new Date(data.generated_at).toLocaleString('tr-TR')}</span></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-4 xl:grid-cols-5"><StatCard label="Toplam üye" value={c.members_total.toLocaleString('tr-TR')} helper={`${c.members_active.toLocaleString('tr-TR')} aktif`} icon={<Users className="h-5 w-5" aria-hidden="true"/>}/><StatCard label="Aktif müşteri" value={c.customers_active.toLocaleString('tr-TR')} helper="Yetkili roller hariç aktif hesap" icon={<Users className="h-5 w-5" aria-hidden="true"/>}/><StatCard label="Üretici kaydı" value={c.producers_total.toLocaleString('tr-TR')} helper={`${c.verified_producers.toLocaleString('tr-TR')} doğrulanmış aktif`} icon={<BadgeCheck className="h-5 w-5" aria-hidden="true"/>}/><StatCard label="Kategori" value={c.categories_total.toLocaleString('tr-TR')} helper={`${c.categories_active.toLocaleString('tr-TR')} aktif`} icon={<Tags className="h-5 w-5" aria-hidden="true"/>}/><StatCard label="Ürün" value={c.products_total.toLocaleString('tr-TR')} helper={`${c.products_published.toLocaleString('tr-TR')} yayında`} icon={<Boxes className="h-5 w-5" aria-hidden="true"/>}/><StatCard label="Sipariş" value={c.orders_total.toLocaleString('tr-TR')} helper={`${c.open_orders.toLocaleString('tr-TR')} açık`} icon={<ShoppingBag className="h-5 w-5" aria-hidden="true"/>} onClick={()=>setActiveTab?.('orders')}/><StatCard label="Yetkili personel" value={c.staff_users.toLocaleString('tr-TR')} helper={`${c.producer_role_users.toLocaleString('tr-TR')} producer rolü`} icon={<Database className="h-5 w-5" aria-hidden="true"/>}/><StatCard label="Açık iade" value={c.return_requests.toLocaleString('tr-TR')} helper="Aktif iade yaşam döngüsü" icon={<RotateCcw className="h-5 w-5" aria-hidden="true"/>} onClick={()=>setActiveTab?.('returns')}/><StatCard label="Havuz onayı" value={c.settlements_waiting.toLocaleString('tr-TR')} helper="Super Admin release bekliyor" icon={<WalletCards className="h-5 w-5" aria-hidden="true"/>} onClick={()=>setActiveTab?.('orders')}/><StatCard label="Planlanan ödeme" value={c.producer_payouts.toLocaleString('tr-TR')} helper="Scheduled veya processing" icon={<CircleDollarSign className="h-5 w-5" aria-hidden="true"/>} onClick={()=>setActiveTab?.('finance')}/></div></section>

  <section className="grid gap-4 xl:grid-cols-[1.35fr_.65fr]">
   <div className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800" aria-labelledby="pool-title"><div className="flex items-start justify-between gap-3"><div><h2 id="pool-title" className="text-lg font-bold">Tahsilat ve Korumalı Hakediş Havuzu</h2><p className="mt-1 text-xs text-gray-500">Para birimleri karıştırılmaz. Tahsilat, iade, korumalı satıcı payı, serbest bırakılan hak ve ödenen payout ayrı hesaplanır.</p></div><WalletCards className="h-6 w-6 text-brand-green" aria-hidden="true"/></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{data.finance_by_currency.map(row=><article key={row.currency} className="rounded-2xl border border-gray-100 p-4 dark:border-gray-700"><div className="flex items-center justify-between"><span className="text-xs font-black tracking-widest text-gray-500">{row.currency}</span><span className="text-lg font-black">{formatMinor(row.net_collected_minor,row.currency)}</span></div><div className="mt-3 grid grid-cols-2 gap-2"><Mini label="Tahsil" value={formatMinor(row.captured_minor,row.currency)}/><Mini label="İade" value={formatMinor(row.refunded_minor,row.currency)}/><Mini label="Korumalı havuz" value={formatMinor(row.protected_pool_minor,row.currency)}/><Mini label="Sağlayıcı onaylı" value={formatMinor(row.approved_seller_minor,row.currency)}/><Mini label="Satıcı bekleyen" value={formatMinor(row.seller_pending_ledger_minor,row.currency)}/><Mini label="Satıcı kullanılabilir" value={formatMinor(row.seller_available_ledger_minor,row.currency)}/><div className="col-span-2"><Mini label="Satıcıya ödenen toplam" value={formatMinor(row.seller_paid_out_minor,row.currency)}/></div></div></article>)}{!data.finance_by_currency.length?<div className="py-10 text-center text-sm text-gray-500 lg:col-span-2">Henüz doğrulanmış ödeme hareketi yok. Sıfır tutar uydurulmaz.</div>:null}</div></div>
   <div className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800" aria-labelledby="storage-title"><div className="flex items-center justify-between"><div><h2 id="storage-title" className="text-lg font-bold">Dosya Varlıkları</h2><p className="mt-1 text-xs text-gray-500">Gerçek Storage object sayısı.</p></div><HardDrive className="h-6 w-6 text-brand-green" aria-hidden="true"/></div><div className="mt-4 space-y-3"><StorageRow label="Katalog görselleri / videoları" value={c.catalog_objects} icon={<Image className="h-5 w-5" aria-hidden="true"/>}/><StorageRow label="İçerik dosyaları" value={c.content_objects} icon={<FolderArchive className="h-5 w-5" aria-hidden="true"/>}/><StorageRow label="Özel ürün sertifikaları" value={c.certificate_objects} icon={<ShieldCheckIcon/>}/></div></div>
  </section>

  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Operasyon kuyrukları">{queueRows.map(row=><button key={row.key} type="button" onClick={()=>setActiveTab?.(row.key)} className="min-h-32 rounded-2xl border border-gray-100 bg-white p-5 text-left shadow-sm transition hover:border-brand-green/40 hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-green dark:border-gray-700 dark:bg-gray-800"><div className="flex items-start justify-between gap-3"><div className="rounded-xl bg-brand-green/10 p-2.5 text-brand-green">{row.icon}</div><div className="text-2xl font-black">{row.value.toLocaleString('tr-TR')}</div></div><div className="mt-4 font-semibold">{row.label}</div><div className="mt-1 text-xs text-gray-500">{row.helper}</div></button>)}</section>

  <div className="grid gap-4 lg:grid-cols-2"><section className="overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm dark:border-gray-700 dark:bg-gray-800"><div className="border-b p-5"><h2 className="font-bold">Son Siparişler</h2><p className="mt-1 text-xs text-gray-500">Arşivlenmemiş en yeni gerçek siparişler.</p></div><div className="divide-y">{data.recent_orders.map(order=><button key={order.id} type="button" onClick={()=>setActiveTab?.('orders')} className="flex min-h-16 w-full items-center justify-between gap-3 p-4 text-left hover:bg-gray-50 dark:hover:bg-gray-700/40"><div className="min-w-0"><div className="truncate font-semibold">{order.order_number}</div><div className="mt-1 text-xs text-gray-500">{order.status} · {order.payment_status} · {order.fulfillment_status}</div></div><div className="shrink-0 text-right"><div className="font-semibold">{formatMinor(order.total_minor,order.currency)}</div><div className="mt-1 text-xs text-gray-500">{new Date(order.created_at).toLocaleDateString('tr-TR')}</div></div></button>)}{!data.recent_orders.length?<div className="p-8 text-center text-sm text-gray-500">Henüz sipariş yok.</div>:null}</div></section><section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800"><h2 className="font-bold">Diğer Yönetim Kuyrukları</h2><div className="mt-4 grid grid-cols-2 gap-3"><Queue label="Ürün değişiklikleri" value={c.product_change_requests}/><Queue label="Destek konuşmaları" value={c.support_conversations}/><Queue label="Hesap kapatma" value={c.account_closures}/><Queue label="Satıcı başvuruları" value={c.producer_applications}/></div></section></div>
 </div>;
}
function StorageRow({label,value,icon}:{label:string;value:number;icon:React.ReactNode}){return <div className="flex items-center justify-between gap-3 rounded-xl bg-gray-50 p-4 dark:bg-gray-900/60"><div className="flex items-center gap-3 text-sm font-semibold"><span className="text-brand-green">{icon}</span>{label}</div><strong className="text-xl">{value.toLocaleString('tr-TR')}</strong></div>;}
function Queue({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-gray-50 p-4 dark:bg-gray-900/60"><div className="text-xs text-gray-500">{label}</div><div className="mt-1 text-2xl font-bold">{value.toLocaleString('tr-TR')}</div></div>;}
function ShieldCheckIcon(){return <BadgeCheck className="h-5 w-5" aria-hidden="true"/>;}

export function AdminDashboard({setActiveTab}:AdminDashboardProps={}){
 const[data,setData]=useState<AdminOperationsOverview|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState('');
 async function load(initial=false){try{if(initial)setLoading(true);else setRefreshing(true);setError('');setData(await getAdminOperationsOverview());return true;}catch(next){setError(dashboardErrorMessage(next));return false;}finally{setLoading(false);setRefreshing(false);}}
 useEffect(()=>{void load(true);},[]);
 async function refresh(){if(await load(false)){setToast('Canlı yönetim verileri yenilendi.');window.setTimeout(()=>setToast(''),2500);}}
 if(loading&&!data)return <div role="status" className="flex min-h-64 items-center justify-center gap-2 text-gray-500"><Loader2 className="h-5 w-5 animate-spin" aria-hidden="true"/>Canlı yönetim verileri yükleniyor...</div>;
 return <div className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-xs font-black uppercase tracking-[.2em] text-brand-green">Golden Oremar Control Center</div><h1 className="mt-1 text-3xl font-black tracking-tight">Canlı Yönetim Kokpiti</h1><p className="mt-1 text-sm text-gray-500">Katalog, kullanıcı, operasyon, Storage ve para akışının doğrulanmış tek görünümü.</p></div><button type="button" disabled={refreshing} onClick={()=>void refresh()} className="min-h-11 rounded-xl border px-4 font-semibold disabled:opacity-60"><RefreshCw className={`mr-2 inline h-4 w-4 ${refreshing?'animate-spin':''}`} aria-hidden="true"/>{refreshing?'Yenileniyor...':'Canlı veriyi yenile'}</button></header>{error?<div role="alert" className="flex items-start gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800 dark:border-red-900/50 dark:bg-red-950/30 dark:text-red-200"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0" aria-hidden="true"/><div>{error}{!data?<button type="button" onClick={()=>void load(true)} className="mt-3 block min-h-11 rounded-xl border px-4 font-semibold">Tekrar dene</button>:null}</div></div>:null}{data?<Overview data={data} setActiveTab={setActiveTab}/>:null}{toast?<div role="status" aria-live="polite" className="fixed bottom-4 right-4 z-[70] flex items-center gap-2 rounded-xl bg-gray-950 px-5 py-3 text-white shadow-2xl"><Check className="h-5 w-5 text-green-400" aria-hidden="true"/>{toast}</div>:null}</div>;
}
