import React,{useEffect,useMemo,useState}from'react';
import{BadgeCheck,Crown,Image as ImageIcon,Loader2,RefreshCw,Save,Sparkles,Store,Upload,Users}from'lucide-react';
import{listAdminStorefronts,storefrontAdminError,storefrontAssetUrl,updateStorefrontPresentation,uploadStorefrontAsset,type AdminStorefront,type StorefrontTheme,type StorefrontTier}from'./storefrontAdminApi';

type Draft={launchAudienceCount:string;launchAudienceLabel:string;tier:StorefrontTier;theme:StorefrontTheme;headline:string;subheadline:string};
const tierLabels:Record<StorefrontTier,string>={standard:'Standart',verified:'Doğrulanmış Premium',signature:'Signature'};
const themeLabels:Record<StorefrontTheme,string>={heritage:'Köy Mirası',emerald:'Zümrüt Prestige',midnight:'Gece Premium',ivory:'Fildişi Minimal'};
function draftOf(row:AdminStorefront):Draft{return{launchAudienceCount:String(row.launchAudienceCount),launchAudienceLabel:row.launchAudienceLabel,tier:row.tier,theme:row.theme,headline:row.headline,subheadline:row.subheadline};}
function formatCount(value:number){try{return new Intl.NumberFormat('tr-TR').format(value);}catch{return String(value);}}

export default function AdminStorefronts(){
 const[stores,setStores]=useState<AdminStorefront[]>([]);const[selectedId,setSelectedId]=useState('');const[draft,setDraft]=useState<Draft|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const selected=useMemo(()=>stores.find(row=>row.id===selectedId)||null,[stores,selectedId]);
 async function load(silent=false){if(!silent)setLoading(true);setError('');try{const rows=await listAdminStorefronts();setStores(rows);setSelectedId(previous=>rows.some(row=>row.id===previous)?previous:rows[0]?.id||'');}catch(next){setError(storefrontAdminError(next,'Mağaza vitrinleri yüklenemedi.'));}finally{if(!silent)setLoading(false);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{if(selected)setDraft(draftOf(selected));else setDraft(null);},[selected?.id,selected?.launchAudienceCount,selected?.launchAudienceLabel,selected?.tier,selected?.theme,selected?.headline,selected?.subheadline]);
 async function save(event:React.FormEvent){event.preventDefault();if(!selected||!draft||busy)return;const count=Number(draft.launchAudienceCount);if(!Number.isSafeInteger(count)||count<0||count>1_000_000_000){setError('Lansman topluluğu 0 ile 1 milyar arasında tam sayı olmalıdır.');return;}setBusy('save');setError('');setNotice('');try{await updateStorefrontPresentation({id:selected.id,launchAudienceCount:count,launchAudienceLabel:draft.launchAudienceLabel,tier:draft.tier,theme:draft.theme,headline:draft.headline,subheadline:draft.subheadline});setNotice('Mağaza vitrini güncellendi.');await load(true);}catch(next){setError(storefrontAdminError(next));}finally{setBusy('');}}
 async function upload(kind:'logo'|'cover',event:React.ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value='';if(!file||!selected||busy)return;setBusy(kind);setError('');setNotice('');try{await uploadStorefrontAsset(selected.id,kind,file,{logoPath:selected.logoPath,coverPath:selected.coverPath});setNotice(kind==='logo'?'Profil görseli güncellendi.':'Kapak görseli güncellendi.');await load(true);}catch(next){setError(storefrontAdminError(next,'Mağaza görseli yüklenemedi.'));}finally{setBusy('');}}
 if(loading)return<div role="status" className="flex min-h-56 items-center justify-center gap-2"><Loader2 aria-hidden="true" className="h-5 w-5 animate-spin"/>Mağaza vitrinleri yükleniyor...</div>;
 return<div className="space-y-6">
  <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><Sparkles aria-hidden="true" className="h-6 w-6 text-brand-gold"/><h1 className="text-2xl font-black">Premium Mağaza Vitrinleri</h1></div><p className="mt-2 max-w-3xl text-sm text-gray-500">Golden Oremar resmi mağazası ve doğrulanmış satıcı mağazalarının kapak, profil, premium tema ve sosyal kanıt sunumunu yönetin. Gerçek takipçi metriği yalnız gerçek takiplerden hesaplanır.</p></div><button type="button" onClick={()=>void load()} disabled={Boolean(busy)} className="min-h-11 rounded-xl border px-4 font-semibold disabled:opacity-50"><RefreshCw aria-hidden="true" className="mr-2 inline h-4 w-4"/>Yenile</button></header>
  {error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800 dark:border-red-900/50 dark:bg-red-950/30 dark:text-red-200">{error}</div>:null}{notice?<div role="status" aria-live="polite" className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900 dark:border-emerald-900/50 dark:bg-emerald-950/30 dark:text-emerald-100">{notice}</div>:null}
  <div className="grid gap-5 xl:grid-cols-[320px_minmax(0,1fr)]">
   <aside className="space-y-2" aria-label="Mağaza seçimi">{stores.map(store=><button key={store.id} type="button" onClick={()=>setSelectedId(store.id)} aria-current={selectedId===store.id?'true':undefined} className={`w-full rounded-2xl border p-4 text-left transition ${selectedId===store.id?'border-brand-gold bg-brand-gold/5 shadow-sm':'bg-white hover:border-gray-300 dark:bg-gray-800'}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="truncate font-bold">{store.name}</div><div className="mt-1 truncate text-xs text-gray-500">{store.location||'Konum girilmemiş'}</div></div>{store.storeKind==='official'?<span className="inline-flex shrink-0 items-center gap-1 rounded-full bg-emerald-100 px-2 py-1 text-[11px] font-bold text-emerald-800"><Crown aria-hidden="true" className="h-3.5 w-3.5"/>Resmi</span>:<span className="inline-flex shrink-0 items-center gap-1 rounded-full bg-blue-100 px-2 py-1 text-[11px] font-bold text-blue-800"><BadgeCheck aria-hidden="true" className="h-3.5 w-3.5"/>Satıcı</span>}</div><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><div className="rounded-lg bg-gray-50 p-2 dark:bg-gray-900"><div className="text-gray-500">Gerçek takipçi</div><div className="font-bold">{formatCount(store.realFollowerCount)}</div></div><div className="rounded-lg bg-gray-50 p-2 dark:bg-gray-900"><div className="text-gray-500">{store.launchAudienceLabel}</div><div className="font-bold">{formatCount(store.launchAudienceCount)}</div></div></div></button>)}{!stores.length?<div className="rounded-2xl border border-dashed p-6 text-sm text-gray-500">Yönetilebilir mağaza bulunamadı.</div>:null}</aside>
   {selected&&draft?<form onSubmit={save} className="space-y-6 rounded-3xl border bg-white p-5 shadow-sm dark:bg-gray-800 sm:p-6">
    <div className="overflow-hidden rounded-2xl border bg-gray-950"><div className="relative h-44 sm:h-56">{selected.coverPath?<img src={storefrontAssetUrl(selected.coverPath)} alt={`${selected.name} kapak önizlemesi`} className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center bg-gradient-to-br from-emerald-950 via-emerald-800 to-amber-600 text-white"><div className="text-center"><ImageIcon aria-hidden="true" className="mx-auto h-8 w-8"/><div className="mt-2 text-sm font-bold">Kapak görseli bekleniyor</div></div></div>}<div className="absolute inset-0 bg-gradient-to-t from-black/65 via-transparent to-transparent"/><div className="absolute bottom-4 left-4 right-4 flex items-end gap-3"><div className="grid h-20 w-20 shrink-0 place-items-center overflow-hidden rounded-full border-4 border-white bg-white shadow-xl">{selected.logoPath?<img src={storefrontAssetUrl(selected.logoPath)} alt={`${selected.name} profil önizlemesi`} className="h-full w-full object-cover"/>:<Store aria-hidden="true" className="h-8 w-8 text-brand-green"/>}</div><div className="min-w-0 pb-1 text-white"><div className="flex flex-wrap items-center gap-2"><div className="truncate text-xl font-black">{selected.name}</div>{selected.storeKind==='official'?<span className="rounded-full bg-emerald-500 px-2.5 py-1 text-[11px] font-black">RESMİ MAĞAZA</span>:<span className="rounded-full bg-blue-500 px-2.5 py-1 text-[11px] font-black">DOĞRULANMIŞ</span>}</div><div className="mt-1 text-xs text-white/80">{tierLabels[draft.tier]} · {themeLabels[draft.theme]}</div></div></div></div></div>
    <div className="grid gap-3 sm:grid-cols-2"><label className="min-h-11 cursor-pointer rounded-xl border p-3 text-center font-semibold"><Upload aria-hidden="true" className="mr-2 inline h-4 w-4"/>{busy==='logo'?'Yükleniyor...':'Profil görseli yükle'}<input type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" disabled={Boolean(busy)} onChange={event=>void upload('logo',event)}/></label><label className="min-h-11 cursor-pointer rounded-xl border p-3 text-center font-semibold"><Upload aria-hidden="true" className="mr-2 inline h-4 w-4"/>{busy==='cover'?'Yükleniyor...':'Kapak görseli yükle'}<input type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" disabled={Boolean(busy)} onChange={event=>void upload('cover',event)}/></label></div>
    <div className="grid gap-4 md:grid-cols-2"><label className="block"><span className="text-sm font-bold">Vitrin seviyesi</span><select value={draft.tier} onChange={e=>setDraft({...draft,tier:e.target.value as StorefrontTier})} className="mt-2 min-h-11 w-full rounded-xl border bg-transparent px-3"><option value="standard">Standart</option><option value="verified">Doğrulanmış Premium</option><option value="signature">Signature</option></select></label><label className="block"><span className="text-sm font-bold">Vitrin teması</span><select value={draft.theme} onChange={e=>setDraft({...draft,theme:e.target.value as StorefrontTheme})} className="mt-2 min-h-11 w-full rounded-xl border bg-transparent px-3"><option value="heritage">Köy Mirası</option><option value="emerald">Zümrüt Prestige</option><option value="midnight">Gece Premium</option><option value="ivory">Fildişi Minimal</option></select></label></div>
    <div className="grid gap-4 md:grid-cols-2"><label className="block"><span className="text-sm font-bold">Vitrin başlığı</span><input value={draft.headline} maxLength={140} onChange={e=>setDraft({...draft,headline:e.target.value})} className="mt-2 min-h-11 w-full rounded-xl border bg-transparent px-3" placeholder="Mağazanın güçlü kısa vaadi"/></label><label className="block"><span className="text-sm font-bold">Vitrin alt başlığı</span><textarea value={draft.subheadline} maxLength={320} onChange={e=>setDraft({...draft,subheadline:e.target.value})} className="mt-2 min-h-24 w-full rounded-xl border bg-transparent p-3" placeholder="Menşe, kalite ve mağaza hikâyesini kısa anlatın"/></label></div>
    <section className="rounded-2xl border border-emerald-200 bg-emerald-50/70 p-4 dark:border-emerald-900/50 dark:bg-emerald-950/20" aria-labelledby="social-proof-title"><div className="flex items-center gap-2"><Users aria-hidden="true" className="h-5 w-5 text-emerald-700"/><h2 id="social-proof-title" className="font-bold">Topluluk ve takip</h2></div><div className="mt-4 grid gap-4 md:grid-cols-2"><div className="rounded-xl border bg-white p-4 dark:bg-gray-900"><div className="text-xs font-bold uppercase tracking-wide text-gray-500">Gerçek takipçi</div><div className="mt-1 text-3xl font-black">{formatCount(selected.realFollowerCount)}</div><p className="mt-2 text-xs text-gray-500">Salt okunur. Kullanıcı Takip Et / Takibi Bırak işlemleriyle sunucuda gerçek zamanlı hesaplanır.</p></div><div className="rounded-xl border bg-white p-4 dark:bg-gray-900"><label className="block"><span className="text-xs font-bold uppercase tracking-wide text-gray-500">Lansman topluluğu</span><input inputMode="numeric" pattern="[0-9]*" value={draft.launchAudienceCount} onChange={e=>setDraft({...draft,launchAudienceCount:e.target.value.replace(/\D/g,'').slice(0,10)})} className="mt-2 min-h-11 w-full rounded-xl border bg-transparent px-3 text-xl font-black"/></label><label className="mt-3 block"><span className="text-xs font-bold uppercase tracking-wide text-gray-500">Public etiket</span><input value={draft.launchAudienceLabel} maxLength={60} onChange={e=>setDraft({...draft,launchAudienceLabel:e.target.value})} className="mt-2 min-h-11 w-full rounded-xl border bg-transparent px-3"/></label><p className="mt-2 text-xs text-gray-500">Bu değer takipçi sayısına eklenmez; mağazada ayrı ve açık etiketle gösterilir.</p></div></div></section>
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="text-xs text-gray-500">Logo: {selected.logoReady?'hazır':'eksik'} · Kapak: {selected.coverReady?'hazır':'eksik'} · Konum: {selected.location||'eksik'}</div><button type="submit" disabled={Boolean(busy)} className="min-h-11 rounded-xl bg-brand-green px-5 font-bold text-brand-on-green disabled:opacity-50"><Save aria-hidden="true" className="mr-2 inline h-4 w-4"/>{busy==='save'?'Kaydediliyor...':'Vitrini kaydet'}</button></div>
   </form>:<div className="rounded-3xl border border-dashed p-10 text-center text-gray-500">Düzenlemek için bir mağaza seçin.</div>}
  </div>
 </div>;
}
