import React,{useEffect,useMemo,useState}from'react';
import{BadgeCheck,Crown,Image as ImageIcon,Loader2,PackagePlus,RefreshCw,Save,Search,ShieldCheck,Store,Upload,X}from'lucide-react';
import{loadOfficialStoreProductManager,officialProductAssetUrl,officialProductError,saveOfficialStoreProduct,uploadOfficialProductImages,type OfficialSourceMode,type OfficialStoreProduct,type OrganicClaim}from'./officialStoreProductApi';

type Draft={reference:string|null;name:string;description:string;story:string;categoryId:string;price:string;originalPrice:string;stock:string;weight:string;unit:string;gallery:string[];active:boolean;sourceMode:OfficialSourceMode;sourceDisplayName:string;sourceProvince:string;sourceDistrict:string;sourceVillage:string;sourceLocality:string;originVerified:boolean;organicClaim:OrganicClaim};
const SOURCE_LABELS:Record<OfficialSourceMode,string>={platform_village_catalog:'Golden Oremar köy kataloğu',platform_direct:'Golden Oremar doğrudan üretimi/tedariği',village_partner:'Doğrulanmış köylü/üretici kaynağı'};
const ORGANIC_LABELS:Record<OrganicClaim,string>={producer_declared_organic:'Doğal/organik üretim beyanı',certification_in_progress:'Organik belgelendirme sürecinde',certified_organic:'Sertifikalı organik',not_claimed:'Organik iddiası yok'};
function emptyDraft(categoryId=''):Draft{return{reference:null,name:'',description:'',story:'',categoryId,price:'',originalPrice:'',stock:'',weight:'',unit:'adet',gallery:[],active:true,sourceMode:'platform_village_catalog',sourceDisplayName:'Golden Oremar Resmi Mağazası',sourceProvince:'Hakkâri',sourceDistrict:'Yüksekova',sourceVillage:'Yeşiltaş',sourceLocality:'Dağlıca',originVerified:true,organicClaim:'producer_declared_organic'};}
function draftFrom(row:OfficialStoreProduct):Draft{return{reference:row.id,name:row.name,description:row.description,story:row.story,categoryId:row.categoryId,price:String(row.price),originalPrice:String(row.originalPrice),stock:String(row.stock),weight:row.weight==null?'':String(row.weight),unit:row.unit,gallery:[...row.gallery],active:row.isActive,sourceMode:row.provenance?.sourceMode||'platform_village_catalog',sourceDisplayName:row.provenance?.sourceDisplayName||'Golden Oremar Resmi Mağazası',sourceProvince:row.provenance?.sourceProvince||'Hakkâri',sourceDistrict:row.provenance?.sourceDistrict||'Yüksekova',sourceVillage:row.provenance?.sourceVillage||'Yeşiltaş',sourceLocality:row.provenance?.sourceLocality||'Dağlıca',originVerified:row.provenance?.originVerified===true,organicClaim:row.provenance?.organicClaim||'producer_declared_organic'};}
function numberValue(value:string){const normalized=value.trim().replace(',','.');const parsed=Number(normalized);return Number.isFinite(parsed)?parsed:NaN;}

export default function AdminOfficialStoreProducts(){
 const[products,setProducts]=useState<OfficialStoreProduct[]>([]);const[categories,setCategories]=useState<any[]>([]);const[store,setStore]=useState<any>(null);const[draft,setDraft]=useState<Draft|null>(null);const[selected,setSelected]=useState('');const[query,setQuery]=useState('');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('');
 async function load(silent=false){if(!silent)setLoading(true);setError('');try{const result=await loadOfficialStoreProductManager();setProducts(result.products);setCategories(result.categories);setStore(result.officialStore);setSelected(previous=>result.products.some(row=>row.id===previous)?previous:'');if(!draft&&!selected)setDraft(emptyDraft(result.categories[0]?.id||''));}catch(next){setError(officialProductError(next,'Resmi mağaza ürünleri yüklenemedi.'));}finally{if(!silent)setLoading(false);}}
 useEffect(()=>{void load();},[]);
 const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase('tr-TR');return q?products.filter(row=>`${row.name} ${row.category} ${row.provenance?.sourceDisplayName||''} ${row.provenance?.originLabel||''}`.toLocaleLowerCase('tr-TR').includes(q)):products;},[products,query]);
 function newProduct(){setSelected('');setDraft(emptyDraft(categories[0]?.id||''));setError('');setNotice('');}
 function edit(row:OfficialStoreProduct){setSelected(row.id);setDraft(draftFrom(row));setError('');setNotice('');window.scrollTo({top:0,behavior:'smooth'});}
 function set<K extends keyof Draft>(key:K,value:Draft[K]){setDraft(current=>current?{...current,[key]:value}:current);}
 async function upload(event:React.ChangeEvent<HTMLInputElement>){const files=Array.from(event.target.files||[]);event.target.value='';if(!draft||!files.length||busy)return;if(draft.gallery.length+files.length>10){setError('Bir üründe en fazla 10 görsel kullanılabilir.');return;}setBusy('upload');setError('');setNotice('');try{const paths=await uploadOfficialProductImages(files);setDraft(current=>current?{...current,gallery:[...current.gallery,...paths].slice(0,10)}:current);setNotice(`${paths.length} gerçek ürün görseli Storage alanına yüklendi.`);}catch(next){setError(officialProductError(next,'Ürün görselleri yüklenemedi.'));}finally{setBusy('');}}
 function removeGallery(path:string){setDraft(current=>current?{...current,gallery:current.gallery.filter(item=>item!==path)}:current);}
 async function persist(publish:boolean){if(!draft||busy)return;setBusy(publish?'publish':'save');setError('');setNotice('');try{const price=numberValue(draft.price),originalPrice=draft.originalPrice.trim()?numberValue(draft.originalPrice):price,weight=numberValue(draft.weight),stock=Number(draft.stock);await saveOfficialStoreProduct({reference:draft.reference,name:draft.name,description:draft.description,story:draft.story,categoryId:draft.categoryId,price,originalPrice,stock,weight,unit:draft.unit,gallery:draft.gallery,active:draft.active,publish,sourceMode:draft.sourceMode,sourceDisplayName:draft.sourceDisplayName,sourceProvince:draft.sourceProvince,sourceDistrict:draft.sourceDistrict,sourceVillage:draft.sourceVillage,sourceLocality:draft.sourceLocality,originVerified:draft.originVerified,organicClaim:draft.organicClaim});setNotice(publish?'Ürün güvenlik kontrollerinden geçti ve Golden Oremar mağazasında yayınlandı.':'Ürün taslağı kaydedildi.');await load(true);setDraft(emptyDraft(categories[0]?.id||''));setSelected('');}catch(next){setError(officialProductError(next));}finally{setBusy('');}}
 if(loading)return<div role="status" className="flex min-h-56 items-center justify-center gap-2"><Loader2 aria-hidden="true" className="h-5 w-5 animate-spin"/>Resmi mağaza ürünleri yükleniyor...</div>;
 return<div className="space-y-6">
  <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2"><Crown aria-hidden="true" className="h-6 w-6 text-emerald-700"/><h1 className="text-2xl font-black">Golden Oremar Resmi Mağaza Ürünleri</h1></div><p className="mt-2 max-w-4xl text-sm text-gray-500">Kendi ürünlerinizi veya doğrulanmış köylü/üretici kaynağından temin ettiğiniz ürünleri resmi mağaza adına yönetin. Satıcı kimliği Golden Oremar olarak kalır; gerçek kaynak ve köy bilgisi ürün provenance kaydında ayrı korunur.</p>{store?<div className="mt-3 inline-flex items-center gap-2 rounded-full bg-emerald-100 px-3 py-1.5 text-xs font-bold text-emerald-900"><BadgeCheck aria-hidden="true" className="h-4 w-4"/>{store.name} · {store.location?.village||'Yeşiltaş'}, {store.location?.district||'Yüksekova'}</div>:null}</div><div className="flex gap-2"><button type="button" onClick={newProduct} className="min-h-11 rounded-xl bg-emerald-700 px-4 font-bold text-white"><PackagePlus aria-hidden="true" className="mr-2 inline h-4 w-4"/>Yeni ürün</button><button type="button" onClick={()=>void load()} disabled={Boolean(busy)} className="min-h-11 rounded-xl border px-4 font-semibold disabled:opacity-50"><RefreshCw aria-hidden="true" className="mr-2 inline h-4 w-4"/>Yenile</button></div></header>
  {error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800 dark:border-red-900/50 dark:bg-red-950/30 dark:text-red-200">{error}</div>:null}{notice?<div role="status" aria-live="polite" className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900 dark:border-emerald-900/50 dark:bg-emerald-950/30 dark:text-emerald-100">{notice}</div>:null}
  <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]">
   {draft?<form onSubmit={event=>{event.preventDefault();void persist(false);}} className="space-y-6 rounded-3xl border bg-white p-5 shadow-sm dark:bg-gray-800 sm:p-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">{draft.reference?'Ürünü düzenle':'Yeni resmi mağaza ürünü'}</h2><p className="mt-1 text-xs text-gray-500">Ürün yayınlanmadan önce fiyat, ağırlık, menşe ve gerçek Storage ana görseli sunucuda tekrar kontrol edilir.</p></div>{draft.reference?<button type="button" onClick={newProduct} className="min-h-11 rounded-xl border px-4 font-semibold">Düzenlemeyi kapat</button>:null}</div>
    <div className="grid gap-4 md:grid-cols-2"><Field label="Ürün adı"><input value={draft.name} maxLength={180} onChange={e=>set('name',e.target.value)} className="input" required/></Field><Field label="Kategori"><select value={draft.categoryId} onChange={e=>set('categoryId',e.target.value)} className="input" required><option value="">Kategori seçin</option>{categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></Field></div>
    <Field label="Ürün açıklaması"><textarea value={draft.description} maxLength={20000} onChange={e=>set('description',e.target.value)} className="min-h-28 w-full rounded-xl border bg-transparent p-3" required/><Help>{draft.description.length}/20000 · Yayın için en az 20 karakter</Help></Field>
    <Field label="Ürün hikâyesi"><textarea value={draft.story} maxLength={20000} onChange={e=>set('story',e.target.value)} className="min-h-28 w-full rounded-xl border bg-transparent p-3" required/><Help>Üretim, aile/köy hikâyesi, hasat veya hazırlama yöntemini gerçek bilgiyle anlatın.</Help></Field>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Fiyat (TL)"><input inputMode="decimal" value={draft.price} onChange={e=>set('price',e.target.value)} className="input" placeholder="299.90" required/></Field><Field label="Eski/karşılaştırma fiyatı"><input inputMode="decimal" value={draft.originalPrice} onChange={e=>set('originalPrice',e.target.value)} className="input" placeholder="Boşsa fiyatla aynı"/></Field><Field label="Stok"><input inputMode="numeric" value={draft.stock} onChange={e=>set('stock',e.target.value.replace(/\D/g,''))} className="input" required/></Field><Field label="Kargo ağırlığı (kg)"><input inputMode="decimal" value={draft.weight} onChange={e=>set('weight',e.target.value)} className="input" placeholder="1.25" required/></Field></div>
    <Field label="Satış birimi"><input value={draft.unit} maxLength={80} onChange={e=>set('unit',e.target.value)} className="input" placeholder="adet, kg, kavanoz, paket" required/></Field>
    <section className="rounded-2xl border p-4" aria-labelledby="official-product-media"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 id="official-product-media" className="font-black">Gerçek ürün görselleri</h3><p className="mt-1 text-xs text-gray-500">İlk görsel ana görsel olur. JPEG, PNG, WebP veya AVIF, görsel başına en fazla 10 MB.</p></div><label className="min-h-11 cursor-pointer rounded-xl border px-4 py-3 font-semibold"><Upload aria-hidden="true" className="mr-2 inline h-4 w-4"/>{busy==='upload'?'Yükleniyor...':'Görsel yükle'}<input type="file" multiple accept="image/jpeg,image/png,image/webp,image/avif" className="sr-only" disabled={Boolean(busy)} onChange={event=>void upload(event)}/></label></div>{draft.gallery.length?<div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{draft.gallery.map((path,index)=><div key={path} className="relative overflow-hidden rounded-xl border bg-gray-100"><img src={officialProductAssetUrl(path)} alt={`${draft.name||'Ürün'} görseli ${index+1}`} className="aspect-square w-full object-cover"/><div className="absolute left-2 top-2 rounded-full bg-black/65 px-2 py-1 text-[10px] font-bold text-white">{index===0?'ANA':index+1}</div><button type="button" onClick={()=>removeGallery(path)} className="absolute right-2 top-2 grid min-h-11 min-w-11 place-items-center rounded-full bg-white/95 shadow" aria-label={`${index+1}. görseli formdan kaldır`}><X aria-hidden="true" className="h-4 w-4"/></button></div>)}</div>:<div className="mt-4 grid min-h-28 place-items-center rounded-xl border border-dashed text-sm text-gray-500"><ImageIcon aria-hidden="true" className="mb-2 h-6 w-6"/>Henüz görsel yüklenmedi</div>}</section>
    <section className="rounded-2xl border border-emerald-200 bg-emerald-50/50 p-4 dark:border-emerald-900/50 dark:bg-emerald-950/20" aria-labelledby="origin-title"><div className="flex items-center gap-2"><ShieldCheck aria-hidden="true" className="h-5 w-5 text-emerald-700"/><h3 id="origin-title" className="font-black">Kaynak, köy ve ürün doğruluğu</h3></div><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Kaynak tipi"><select value={draft.sourceMode} onChange={e=>{const value=e.target.value as OfficialSourceMode;setDraft(current=>current?{...current,sourceMode:value,sourceDisplayName:value==='village_partner'?'': 'Golden Oremar Resmi Mağazası'}:current);}} className="input">{Object.entries(SOURCE_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label={draft.sourceMode==='village_partner'?'Köylü / üretici adı':'Kaynak adı'}><input value={draft.sourceDisplayName} maxLength={180} onChange={e=>set('sourceDisplayName',e.target.value)} className="input" required/></Field></div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="İl"><input value={draft.sourceProvince} maxLength={120} onChange={e=>set('sourceProvince',e.target.value)} className="input" required/></Field><Field label="İlçe"><input value={draft.sourceDistrict} maxLength={120} onChange={e=>set('sourceDistrict',e.target.value)} className="input" required/></Field><Field label="Köy"><input value={draft.sourceVillage} maxLength={120} onChange={e=>set('sourceVillage',e.target.value)} className="input" required/></Field><Field label="Yerel bölge / mezra"><input value={draft.sourceLocality} maxLength={160} onChange={e=>set('sourceLocality',e.target.value)} className="input" placeholder="Dağlıca"/></Field></div><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Organik beyanı"><select value={draft.organicClaim} onChange={e=>set('organicClaim',e.target.value as OrganicClaim)} className="input">{Object.entries(ORGANIC_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{draft.organicClaim==='certified_organic'?<Help>Sertifikalı organik seçilirse geçerli ürün sertifikası olmadan sunucu yayına izin vermez.</Help>:null}</Field><label className="flex min-h-12 items-start gap-3 rounded-xl border bg-white p-3 dark:bg-gray-900"><input type="checkbox" checked={draft.originVerified} onChange={e=>set('originVerified',e.target.checked)} className="mt-1 h-5 w-5"/><span><span className="block font-bold">Menşe bilgilerini doğruladım</span><span className="mt-1 block text-xs text-gray-500">Kaynağın gerçekten yukarıdaki üretici/köy bilgisine ait olduğunu belge, doğrudan tedarik veya Super Admin kontrolüyle doğrulayın.</span></span></label></div></section>
    <label className="flex min-h-12 items-center gap-3 rounded-xl border p-3"><input type="checkbox" checked={draft.active} onChange={e=>set('active',e.target.checked)} className="h-5 w-5"/><span><span className="font-bold">Ürün aktif</span><span className="ml-2 text-xs text-gray-500">Pasif ürün katalogda satın alınamaz.</span></span></label>
    <div className="grid gap-3 sm:grid-cols-2"><button type="submit" disabled={Boolean(busy)} className="min-h-12 rounded-xl border px-5 font-bold disabled:opacity-50"><Save aria-hidden="true" className="mr-2 inline h-4 w-4"/>{busy==='save'?'Kaydediliyor...':'Taslak kaydet'}</button><button type="button" onClick={()=>void persist(true)} disabled={Boolean(busy)} className="min-h-12 rounded-xl bg-emerald-700 px-5 font-black text-white disabled:opacity-50"><BadgeCheck aria-hidden="true" className="mr-2 inline h-4 w-4"/>{busy==='publish'?'Kontrol ediliyor...':'Kontrol et ve yayınla'}</button></div>
   </form>:null}
   <aside className="space-y-4"><label className="relative block"><span className="sr-only">Resmi mağaza ürünlerinde ara</span><Search aria-hidden="true" className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400"/><input type="search" value={query} maxLength={160} onChange={e=>setQuery(e.target.value)} placeholder="Ürün, kategori veya kaynak ara" className="min-h-11 w-full rounded-xl border bg-white py-2 pl-10 pr-3 dark:bg-gray-800"/></label><div className="rounded-2xl border bg-white p-3 dark:bg-gray-800"><div className="mb-3 flex items-center justify-between"><h2 className="font-black">Resmi mağaza kataloğu</h2><span className="rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-bold text-emerald-900">{filtered.length}</span></div><div className="max-h-[75dvh] space-y-2 overflow-y-auto pr-1">{filtered.map(row=><button type="button" key={row.id} onClick={()=>edit(row)} aria-current={selected===row.id?'true':undefined} className={`w-full rounded-xl border p-3 text-left ${selected===row.id?'border-emerald-600 bg-emerald-50 dark:bg-emerald-950/20':''}`}><div className="flex items-start gap-3">{row.image?<img src={officialProductAssetUrl(row.image)} alt="" className="h-14 w-14 rounded-lg object-cover"/>:<div className="grid h-14 w-14 shrink-0 place-items-center rounded-lg bg-gray-100 dark:bg-gray-900"><Store aria-hidden="true" className="h-5 w-5 text-gray-400"/></div>}<div className="min-w-0 flex-1"><div className="line-clamp-2 font-bold">{row.name}</div><div className="mt-1 text-xs text-gray-500">{row.category} · {row.status}</div><div className="mt-1 truncate text-xs text-gray-500">{row.provenance?.sourceDisplayName||'Kaynak bilgisi eksik'}</div></div></div></button>)}{!filtered.length?<div className="rounded-xl border border-dashed p-6 text-center text-sm text-gray-500">Eşleşen ürün yok.</div>:null}</div></div></aside>
  </div>
 </div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return<label className="block"><span className="text-sm font-bold">{label}</span><div className="mt-2">{children}</div></label>;}
function Help({children}:{children:React.ReactNode}){return<div className="mt-1.5 text-xs leading-5 text-gray-500">{children}</div>;}
