import React,{useEffect,useState}from'react';
import{Globe2,Plus,RefreshCw,Star,Trash2}from'lucide-react';
import{deleteReleaseOrigin,getReleaseOrigins,releaseSetupErrorMessage,saveReleaseOrigin,type ReleaseOrigin}from'./releaseSetupAdminApi';

export function AdminReleaseOrigins({onPrimaryChanged}:{onPrimaryChanged?:(origin:string)=>void}){
 const[items,setItems]=useState<ReleaseOrigin[]>([]),[newOrigin,setNewOrigin]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState(''),[status,setStatus]=useState('');
 async function load(){try{setLoading(true);setError('');const next=await getReleaseOrigins();setItems(next);const primary=next.find(item=>item.isPrimary);if(primary)onPrimaryChanged?.(primary.origin);}catch(next){setError(releaseSetupErrorMessage(next,'Domain/origin listesi yüklenemedi.'));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function add(){const origin=newOrigin.trim();if(!origin||busy)return;try{setBusy('add');setError('');setStatus('');const next=await saveReleaseOrigin(origin,false,true);setItems(next);setNewOrigin('');setStatus('Yeni HTTPS domain/origin Supabase veritabanına eklendi.');}catch(next){setError(releaseSetupErrorMessage(next,'Domain/origin eklenemedi.'));}finally{setBusy(null);}}
 async function makePrimary(item:ReleaseOrigin){if(item.isPrimary||busy)return;try{setBusy(item.id);setError('');setStatus('');const next=await saveReleaseOrigin(item.origin,true,true);setItems(next);const primary=next.find(value=>value.isPrimary);if(!primary||primary.origin!==item.origin)throw new Error('Birincil origin değişikliği doğrulanamadı.');onPrimaryChanged?.(primary.origin);setStatus(`${primary.origin} birincil public origin olarak kaydedildi.`);}catch(next){setError(releaseSetupErrorMessage(next,'Birincil domain değiştirilemedi.'));}finally{setBusy(null);}}
 async function remove(item:ReleaseOrigin){if(item.isPrimary||busy)return;try{setBusy(item.id);setError('');setStatus('');const next=await deleteReleaseOrigin(item.id);setItems(next);setStatus(`${item.origin} domain/origin kaydı silindi.`);}catch(next){setError(releaseSetupErrorMessage(next,'Domain/origin silinemedi.'));}finally{setBusy(null);}}
 return<section className="rounded-2xl border bg-white p-5 dark:bg-gray-800" aria-labelledby="release-origins-title">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><Globe2 className="h-5 w-5 text-brand-green" aria-hidden="true"/><h3 id="release-origins-title" className="font-bold">Domain ve HTTPS origin yönetimi</h3></div><p className="mt-1 text-sm text-gray-500">Yeni domain ekleyebilir, mevcut bir domaini birincil yapabilir veya kullanılmayan alias kaydını silebilirsiniz. Birincil değişiklik aynı transaction içinde Supabase release config’e yazılır.</p></div><button type="button" onClick={()=>void load()} disabled={loading||Boolean(busy)} className="min-h-11 rounded-xl border px-4 font-semibold disabled:opacity-50"><RefreshCw className={`mr-2 inline h-4 w-4 ${loading?'animate-spin':''}`} aria-hidden="true"/>Yenile</button></div>
  {error?<div role="alert" className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>:null}{status?<div role="status" className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{status}</div>:null}
  <div className="mt-5 flex flex-col gap-2 sm:flex-row"><label className="flex-1"><span className="sr-only">Yeni HTTPS domain veya origin</span><input type="url" value={newOrigin} onChange={event=>setNewOrigin(event.target.value)} placeholder="https://ornek-domain.com" maxLength={2048} className="min-h-11 w-full rounded-xl border px-3"/></label><button type="button" onClick={()=>void add()} disabled={Boolean(busy)||newOrigin.trim().length<8} className="min-h-11 rounded-xl bg-brand-green px-4 font-bold text-brand-on-green disabled:opacity-50"><Plus className="mr-2 inline h-4 w-4" aria-hidden="true"/>Yeni origin ekle</button></div>
  <div className="mt-5 space-y-3">{items.map(item=><div key={item.id} className="flex flex-col gap-3 rounded-xl border p-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="break-all font-mono text-sm font-bold">{item.origin}</span>{item.isPrimary?<span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700">Birincil</span>:<span className="rounded-full bg-gray-100 px-2 py-1 text-xs font-bold text-gray-700">Alias</span>}{item.isActive?<span className="text-xs text-emerald-700">Aktif</span>:<span className="text-xs text-gray-500">Pasif</span>}</div><p className="mt-1 text-xs text-gray-500">Son güncelleme: {new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(item.updatedAt))}</p></div><div className="flex flex-col gap-2 sm:flex-row">{!item.isPrimary?<button type="button" onClick={()=>void makePrimary(item)} disabled={Boolean(busy)} className="min-h-10 rounded-xl border px-3 text-sm font-bold disabled:opacity-50"><Star className="mr-1 inline h-4 w-4" aria-hidden="true"/>Birincil yap</button>:null}{!item.isPrimary?<button type="button" onClick={()=>void remove(item)} disabled={Boolean(busy)} className="min-h-10 rounded-xl border border-red-200 px-3 text-sm font-bold text-red-700 disabled:opacity-50"><Trash2 className="mr-1 inline h-4 w-4" aria-hidden="true"/>Sil</button>:null}</div></div>)}{!loading&&items.length===0?<div role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Aktif domain/origin kaydı bulunamadı.</div>:null}</div>
 </section>;
}
