import React,{useEffect,useState}from'react';
import{AlertTriangle,CheckCircle2,CreditCard,Link2,Loader2,RefreshCw,Save,ShieldCheck,XCircle}from'lucide-react';
import{getPaymentControl,paymentControlErrorMessage,updatePaymentControl,type PaymentControl}from'./paymentControlApi';
import{getPaymentRuntimeHealth,type PaymentRuntimeHealth}from'./paymentHealthApi';
function clone(value:PaymentControl):PaymentControl{return{...value};}
function Toggle({checked,onChange,label,description,disabled=false}:{checked:boolean;onChange:(next:boolean)=>void;label:string;description:string;disabled?:boolean}){return<label className={`flex min-h-16 items-start justify-between gap-4 rounded-2xl border p-4 ${disabled?'opacity-50':''}`}><span><span className="block font-bold">{label}</span><span className="mt-1 block text-sm text-gray-500">{description}</span></span><input type="checkbox" checked={checked} disabled={disabled} onChange={event=>onChange(event.target.checked)} className="mt-1 h-5 w-5"/></label>;}
function ReadyBadge({health}:{health:{enabled:boolean;ready:boolean}|undefined}){if(!health)return<span className="rounded-full bg-gray-100 px-2 py-1 text-xs font-bold text-gray-600">Kontrol edilmedi</span>;if(health.ready)return<span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700"><CheckCircle2 className="h-3.5 w-3.5" aria-hidden="true"/>Hazır</span>;if(health.enabled)return<span className="inline-flex items-center gap-1 rounded-full bg-amber-50 px-2 py-1 text-xs font-bold text-amber-800"><AlertTriangle className="h-3.5 w-3.5" aria-hidden="true"/>Eksik yapılandırma</span>;return<span className="inline-flex items-center gap-1 rounded-full bg-gray-100 px-2 py-1 text-xs font-bold text-gray-600"><XCircle className="h-3.5 w-3.5" aria-hidden="true"/>Kapalı</span>;}
export function AdminPaymentControls(){
 const[control,setControl]=useState<PaymentControl|null>(null),[health,setHealth]=useState<PaymentRuntimeHealth|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[healthLoading,setHealthLoading]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState('');
 async function refreshHealth(showError=true){setHealthLoading(true);try{setHealth(await getPaymentRuntimeHealth());}catch(next){setHealth(null);if(showError)setError(paymentControlErrorMessage(next,'Ödeme çalışma zamanı kontrol edilemedi.'));}finally{setHealthLoading(false);}}
 async function load(){setLoading(true);setError('');try{setControl(await getPaymentControl());await refreshHealth(false);}catch(next){setError(paymentControlErrorMessage(next,'Ödeme altyapısı yüklenemedi.'));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);function patch(mutator:(next:PaymentControl)=>void){if(!control)return;const next=clone(control);mutator(next);setControl(next);}
 async function save(){if(!control)return;setSaving(true);setError('');setToast('');try{const saved=await updatePaymentControl(control);setControl(saved);setToast('iyzico ödeme ayarları kaydedildi. Checkout yalnız açık ve hazır akışları gösterecek.');await refreshHealth(false);window.setTimeout(()=>setToast(''),4200);}catch(next){setError(paymentControlErrorMessage(next));}finally{setSaving(false);}}
 if(loading)return<div role="status" className="flex min-h-48 items-center justify-center gap-2 rounded-2xl border bg-white dark:bg-gray-800"><Loader2 className="h-5 w-5 animate-spin" aria-hidden="true"/>Ödeme altyapısı yükleniyor...</div>;if(!control)return<div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-5 text-red-800">{error||'Ödeme altyapısı bulunamadı.'}</div>;
 return<div className="space-y-6"><header className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><h2 className="text-2xl font-bold">Ödeme Altyapısı</h2><p className="mt-1 max-w-3xl text-sm text-gray-500">Golden Oremar tek sağlayıcı olarak iyzico kullanır. Müşteri ister tek seferlik iyzico ödeme formunu kullanır, ister açık onayla kartını kaydeder ve sonraki alışverişlerde seçer.</p></div><div className="flex gap-2"><button type="button" onClick={()=>void refreshHealth()} disabled={healthLoading} className="min-h-11 rounded-xl border px-4 font-semibold"><RefreshCw className={`mr-2 inline h-4 w-4 ${healthLoading?'animate-spin':''}`} aria-hidden="true"/>Sağlığı kontrol et</button><button type="button" onClick={()=>void save()} disabled={saving} className="min-h-11 rounded-xl bg-brand-green px-4 font-bold text-white disabled:opacity-50"><Save className="mr-2 inline h-4 w-4" aria-hidden="true"/>{saving?'Kaydediliyor...':'Kaydet'}</button></div></header>
 {error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{error}</div>:null}{toast?<div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-800">{toast}</div>:null}
 <section className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border bg-white p-5 dark:bg-gray-800"><ShieldCheck className="h-6 w-6 text-brand-green" aria-hidden="true"/><h3 className="mt-2 font-bold">iyzico anahtarları</h3><p className="mt-2 text-sm text-gray-500">{health?.runtime.iyzicoSecretsConfigured?'Sunucuda tanımlı':'Henüz eksik'}</p></div><div className="rounded-2xl border bg-white p-5 dark:bg-gray-800"><Link2 className="h-6 w-6 text-brand-green" aria-hidden="true"/><h3 className="mt-2 font-bold">Ödeme dönüş adresi</h3><p className="mt-2 text-sm text-gray-500">{health?.runtime.paymentReturnUrlConfigured?'Tanımlı':'Hosted ödeme için eksik'}</p></div><div className="rounded-2xl border bg-white p-5 dark:bg-gray-800"><CheckCircle2 className="h-6 w-6 text-brand-green" aria-hidden="true"/><h3 className="mt-2 font-bold">Tahsilat hazırlığı</h3><p className="mt-2 text-sm text-gray-500">{health?.runtime.livePaymentsEnabled?'Sağlayıcı anahtarları hazır':'Kapalı veya yapılandırma eksik'}</p></div></section>
 <section className="rounded-2xl border bg-white p-5 dark:bg-gray-800"><label className="block" htmlFor="iyzico-return-url"><span className="font-bold">Ödeme dönüş adresi</span><span className="mt-1 block text-sm text-gray-500">iyzico ödeme ekranından sonra müşterinin döneceği Golden Oremar web veya app-link adresi. Domain hazır olduğunda buradan değiştirilebilir.</span><input id="iyzico-return-url" value={control.returnUrl||''} onChange={e=>patch(next=>{next.returnUrl=e.target.value.trim()||null;})} maxLength={1000} placeholder="https://... veya goldenoremar://payment-return" className="mt-3 min-h-11 w-full rounded-xl border px-3"/></label></section>
 <section className="space-y-3 rounded-2xl border bg-white p-5 dark:bg-gray-800"><div className="flex items-center justify-between gap-3"><div><h3 className="text-lg font-bold">iyzico Checkout Form</h3><p className="text-sm text-gray-500">Kart kaydetmeden tek seferlik ödeme. Kart bilgisi iyzico ödeme ekranında girilir.</p></div><ReadyBadge health={health?.methods.hostedCheckout}/></div><Toggle checked={control.checkoutFormEnabled} onChange={value=>patch(next=>{next.checkoutFormEnabled=value;})} label="Tek seferlik iyzico ödemeyi aç" description="Müşteri kartını hesabına kaydetmeden ödeme yapabilir."/></section>
 <section className="space-y-3 rounded-2xl border bg-white p-5 dark:bg-gray-800"><div className="flex items-center justify-between gap-3"><div><h3 className="text-lg font-bold">Kayıtlı kart</h3><p className="text-sm text-gray-500">Kartın iyzico referansı kullanılır. Müşteri sonraki alışverişlerde kayıtlı kartını seçebilir.</p></div><ReadyBadge health={health?.methods.savedCardPayment}/></div><Toggle checked={control.liveCardPaymentsEnabled} onChange={value=>patch(next=>{next.liveCardPaymentsEnabled=value;if(!value)next.cardEnrollmentEnabled=false;})} label="Kayıtlı kartla ödemeyi aç" description="Daha önce iyzico üzerinde kaydedilmiş kart referanslarıyla tahsilat yapılabilir."/><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold">Kart kaydetme</p><ReadyBadge health={health?.methods.cardEnrollment}/></div><Toggle checked={control.cardEnrollmentEnabled} disabled={!control.liveCardPaymentsEnabled} onChange={value=>patch(next=>{next.cardEnrollmentEnabled=value;})} label="Müşteriye kartımı kaydet seçeneğini göster" description="Müşteri açıkça seçerse kart iyzico Card Storage üzerinde kaydedilir. İstemiyorsa kaydedilmez."/></section>
 <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-950"><h3 className="font-bold">Yayına alma kuralı</h3><p className="mt-1 text-sm">Şirket ve iyzico production bilgilerini bağladıktan sonra önce test siparişiyle tahsilat, komisyon bölüşümü, iade ve muhasebe kaydını doğrula. Sonra ilgili akışı buradan aç.</p></section></div>;
}
