import React,{useEffect,useMemo,useState}from'react';
import{AlertTriangle,Loader2,RefreshCw,Search,ShieldAlert,Trash2,X}from'lucide-react';
import{adminListPlatformUsers,type AdminPlatformUser}from'./userAdminApi';
import{accountErasureErrorMessage,cleanupAnonymizedUserMedia,superAdminAnonymizeClosedUser}from'./accountErasureApi';
import{useAccessibleDialog}from'../features/accessibility/useAccessibleDialog';

export function AdminAccountErasure(){
 const[users,setUsers]=useState<AdminPlatformUser[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState(''),[search,setSearch]=useState(''),[target,setTarget]=useState<AdminPlatformUser|null>(null),[reason,setReason]=useState(''),[confirm,setConfirm]=useState('');
 const dialogRef=useAccessibleDialog<HTMLDivElement>(Boolean(target),()=>{if(!busy)close();});
 async function load(silent=false){if(!silent)setLoading(true);setError('');try{setUsers(await adminListPlatformUsers());}catch(next){setError(accountErasureErrorMessage(next,'Kullanıcılar yüklenemedi.'));}finally{if(!silent)setLoading(false);}}
 useEffect(()=>{void load();},[]);
 function close(){setTarget(null);setReason('');setConfirm('');setError('');}
 function show(message:string){setToast(message);window.setTimeout(()=>setToast(''),5000);}
 const candidates=useMemo(()=>{const q=search.trim().toLocaleLowerCase('tr-TR');return users.filter(user=>user.status==='deleted'&&user.role!=='admin'&&user.role!=='super_admin'&&(!q||`${user.name} ${user.email} ${user.id}`.toLocaleLowerCase('tr-TR').includes(q)));},[users,search]);
 async function anonymize(event:React.FormEvent){event.preventDefault();if(!target||busy)return;if(confirm!=='ANONİMLEŞTİR'){setError('İşlemi doğrulamak için ANONİMLEŞTİR yazın.');return;}if(reason.trim().length<8){setError('Anonimleştirme gerekçesi en az 8 karakter olmalıdır.');return;}setBusy(true);setError('');try{const result=await superAdminAnonymizeClosedUser(target.id,reason);const mediaFailures=await cleanupAnonymizedUserMedia(result);show(`Hesap anonimleştirildi. ${result.ordersPreserved} sipariş ve ${result.paymentsPreserved} ödeme kaydı hukuki/muhasebe geçmişi için korundu.${mediaFailures.length?` Temizlenemeyen medya: ${mediaFailures.join(', ')}.`:''}`);close();await load(true);}catch(next){setError(accountErasureErrorMessage(next));}finally{setBusy(false);}}
 return<div className="space-y-6">
  <header><h2 className="text-2xl font-bold">Kalıcı Hesap Anonimleştirme</h2><p className="mt-1 max-w-4xl text-sm text-gray-500">Yalnız Super Admin içindir. Önce Kullanıcılar ekranından hesap kalıcı kapatılır. Daha sonra açık sipariş/iade yoksa gereksiz kişisel veriler silinir, Auth oturumları iptal edilir ve giriş kimliği anonimleştirilir. Finansal ve hukuki kayıtlar korunur.</p></header>
  <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-950 dark:border-red-900/50 dark:bg-red-950/20 dark:text-red-100"><ShieldAlert aria-hidden="true" className="mr-2 inline h-5 w-5"/><strong>Geri döndürülemez:</strong> Bu işlem hesabı tekrar kullanılabilir hale getirmek için tasarlanmamıştır. Aktif, engellenmiş veya açık ticari işlemi olan hesap burada görünmez.</div>
  {error&&!target?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{error}</div>:null}
  <div className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><span className="sr-only">Kapalı hesap ara</span><Search aria-hidden="true" className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400"/><input type="search" value={search} onChange={e=>setSearch(e.target.value)} maxLength={160} placeholder="Kapalı hesap adı, e-posta veya UUID ara..." className="min-h-11 w-full rounded-xl border bg-white pl-10 pr-4 dark:bg-gray-900"/></label><button type="button" onClick={()=>void load()} disabled={loading} className="min-h-11 rounded-xl border px-4"><RefreshCw aria-hidden="true" className={`mr-2 inline h-4 w-4 ${loading?'animate-spin':''}`}/>Yenile</button></div>
  {loading?<div role="status" className="flex min-h-40 items-center justify-center gap-2 rounded-2xl border"><Loader2 aria-hidden="true" className="h-5 w-5 animate-spin"/>Kapalı hesaplar yükleniyor...</div>:<section className="space-y-3" aria-label="Anonimleştirilebilir hesaplar">{candidates.map(user=><article key={user.id} className="rounded-2xl border bg-white p-4 dark:bg-gray-800"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><h3 className="font-bold">{user.name}</h3><p className="mt-1 break-all text-sm text-gray-500">{user.email||user.id}</p><p className="mt-1 text-xs text-gray-500">Rol: {user.role} · profil durumu: {user.profileStatus}</p></div><button type="button" onClick={()=>{setTarget(user);setReason('');setConfirm('');setError('');}} className="min-h-11 rounded-xl border border-red-300 px-4 font-bold text-red-700"><Trash2 aria-hidden="true" className="mr-1 inline h-4 w-4"/>Anonimleştir</button></div></article>)}{!candidates.length?<div className="rounded-2xl border p-8 text-center text-gray-500">Anonimleştirmeye hazır kapalı hesap yok.</div>:null}</section>}
  {target?<div className="fixed inset-0 z-[70] flex items-end justify-center bg-black/70 sm:items-center sm:p-4"><div ref={dialogRef} role="alertdialog" aria-modal="true" aria-labelledby="erase-account-title" tabIndex={-1} className="w-full max-w-xl rounded-t-3xl bg-white p-5 shadow-2xl outline-none dark:bg-gray-900 sm:rounded-3xl"><div className="flex items-start justify-between gap-3"><div><h3 id="erase-account-title" className="text-xl font-bold">Kapalı hesabı anonimleştir</h3><p className="mt-1 text-sm text-gray-500">{target.name} · {target.email}</p></div><button type="button" disabled={busy} onClick={close} className="min-h-11 min-w-11 rounded-xl" aria-label="Pencereyi kapat"><X aria-hidden="true" className="mx-auto h-5 w-5"/></button></div><form onSubmit={anonymize} className="mt-5 space-y-4"><label className="block"><span className="mb-1 block text-sm font-semibold">Anonimleştirme gerekçesi</span><textarea required minLength={8} maxLength={1000} rows={4} value={reason} onChange={e=>setReason(e.target.value)} className="w-full rounded-xl border p-3" placeholder="Kullanıcı talebi, güvenlik kararı, saklama süresi sonrası temizlik..."/></label><label className="block"><span className="mb-1 block text-sm font-semibold">Onay için ANONİMLEŞTİR yazın</span><input value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="off" className="min-h-11 w-full rounded-xl border px-3"/></label>{error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800"><AlertTriangle aria-hidden="true" className="mr-1 inline h-4 w-4"/>{error}</div>:null}<div className="grid grid-cols-2 gap-3"><button type="button" disabled={busy} onClick={close} className="min-h-11 rounded-xl border font-semibold">Vazgeç</button><button type="submit" disabled={busy||confirm!=='ANONİMLEŞTİR'||reason.trim().length<8} className="min-h-11 rounded-xl bg-red-800 font-bold text-white disabled:opacity-40">{busy?'Kontrol ediliyor…':'Kalıcı anonimleştir'}</button></div></form></div></div>:null}
  {toast?<div role="status" className="fixed bottom-4 right-4 z-[90] max-w-md rounded-xl bg-gray-950 px-5 py-3 text-white shadow-2xl">{toast}</div>:null}
 </div>;
}
