import React,{useEffect,useState}from'react';
import{Building2,Loader2,MessageCircle,Phone,Plus,RefreshCw,Save,Search,Trash2}from'lucide-react';
import{formatMoney}from'../features/cart/checkoutHelpers';
import{ORDER_REQUEST_STATUS_LABELS,formatIban,getOfflineOrderingSettings,isValidTurkishIban,listOrderRequests,orderRequestAdminError,saveOfflineOrderingSettings,updateOrderRequest,type AdminBankAccount,type OfflineOrderingSettings,type OrderRequest,type OrderRequestFilter,type OrderRequestStatus}from'./orderRequestAdminApi';

const FILTERS:Array<{value:OrderRequestFilter;label:string}>=[{value:'open',label:'Açık'},{value:'new',label:'Yeni'},{value:'confirmed',label:'Onaylandı'},{value:'paid',label:'Ödendi'},{value:'shipped',label:'Kargoda'},{value:'completed',label:'Tamamlandı'},{value:'cancelled',label:'İptal'},{value:'all',label:'Tümü'}];
const NEXT:Record<OrderRequestStatus,Array<{status:OrderRequestStatus;label:string}>>={
 new:[{status:'contacted',label:'İletişime geçildi'},{status:'confirmed',label:'Onayla (stoktan düş)'},{status:'cancelled',label:'İptal et'}],
 contacted:[{status:'confirmed',label:'Onayla (stoktan düş)'},{status:'cancelled',label:'İptal et'}],
 confirmed:[{status:'paid',label:'Ödeme alındı'},{status:'shipped',label:'Kargoya verildi'},{status:'cancelled',label:'İptal et (stok geri)'}],
 paid:[{status:'shipped',label:'Kargoya verildi'},{status:'cancelled',label:'İptal et (stok geri)'}],
 shipped:[{status:'completed',label:'Teslim edildi'}],
 completed:[],cancelled:[],
};
const EMPTY_ACCOUNT:AdminBankAccount={bankName:'',accountHolder:'',iban:'TR',branch:'',active:true};

function dateTime(value:string){const date=new Date(value);if(Number.isNaN(date.getTime()))return'';try{return new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium',timeStyle:'short'}).format(date);}catch{return date.toISOString();}}
function statusTone(status:OrderRequestStatus){return status==='new'?'border-amber-300 bg-amber-50 text-amber-900':status==='cancelled'?'border-gray-300 bg-gray-100 text-gray-700':status==='completed'?'border-blue-300 bg-blue-50 text-blue-800':'border-emerald-300 bg-emerald-50 text-emerald-800';}

export default function AdminOrderRequests(){
 const[settings,setSettings]=useState<OfflineOrderingSettings|null>(null);
 const[settingsError,setSettingsError]=useState('');
 const[settingsStatus,setSettingsStatus]=useState('');
 const[savingSettings,setSavingSettings]=useState(false);
 const[filter,setFilter]=useState<OrderRequestFilter>('open');
 const[query,setQuery]=useState('');
 const[items,setItems]=useState<OrderRequest[]>([]);
 const[counts,setCounts]=useState<Partial<Record<OrderRequestStatus,number>>>({});
 const[loading,setLoading]=useState(true);
 const[error,setError]=useState('');
 const[busyId,setBusyId]=useState('');
 const[notes,setNotes]=useState<Record<string,string>>({});

 async function loadSettings(){try{setSettingsError('');setSettings(await getOfflineOrderingSettings());}catch(err){setSettingsError(orderRequestAdminError(err));}}
 async function load(nextFilter=filter,nextQuery=query){try{setLoading(true);setError('');const result=await listOrderRequests({status:nextFilter,query:nextQuery});setItems(result.items);setCounts(result.counts);}catch(err){setError(orderRequestAdminError(err));}finally{setLoading(false);}}
 useEffect(()=>{void loadSettings();},[]);
 useEffect(()=>{void load(filter);// eslint-disable-next-line react-hooks/exhaustive-deps
 },[filter]);

 function patchSettings(patch:Partial<OfflineOrderingSettings>){setSettings(current=>current?{...current,...patch}:current);setSettingsStatus('');}
 function patchAccount(index:number,patch:Partial<AdminBankAccount>){setSettings(current=>current?{...current,bankAccounts:current.bankAccounts.map((account,i)=>i===index?{...account,...patch}:account)}:current);setSettingsStatus('');}
 async function persistSettings(){if(!settings||savingSettings)return;try{setSavingSettings(true);setSettingsError('');const next=await saveOfflineOrderingSettings(settings);setSettings(next);setSettingsStatus('Kaydedildi. Değişiklik mağazada birkaç dakika içinde görünür.');}catch(err){setSettingsError(orderRequestAdminError(err));}finally{setSavingSettings(false);}}
 async function move(request:OrderRequest,status:OrderRequestStatus){if(busyId)return;if(status==='cancelled'&&!window.confirm(`${request.reference} iptal edilsin mi?${request.stockCommitted?' Düşülen stok geri eklenecek.':''}`))return;try{setBusyId(request.id);setError('');await updateOrderRequest(request.id,status,notes[request.id]);await load();}catch(err){setError(orderRequestAdminError(err));}finally{setBusyId('');}}
 async function saveNote(request:OrderRequest){if(busyId)return;try{setBusyId(request.id);setError('');await updateOrderRequest(request.id,request.status,notes[request.id]);await load();}catch(err){setError(orderRequestAdminError(err));}finally{setBusyId('');}}

 const openCount=(counts.new||0)+(counts.contacted||0)+(counts.confirmed||0)+(counts.paid||0);
 return<div className="space-y-6">
  <header><h2 className="text-2xl font-black">Sipariş Talepleri</h2><p className="mt-1 max-w-3xl text-sm text-gray-500">Online ödeme açılana kadar müşteriler (üye olmayanlar dahil) WhatsApp veya Havale/EFT ile sipariş verir. Tutar, stok ve kargo sunucuda hesaplanır. Onayladığınızda stok düşer, iptal ederseniz geri eklenir.</p></header>

  <section className="rounded-2xl border bg-white p-4 dark:bg-gray-800" aria-labelledby="offline-channels-title">
   <h3 id="offline-channels-title" className="font-black">Sipariş kanalları</h3>
   {settingsError?<div role="alert" className="mt-3 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{settingsError}</div>:null}
   {!settings?<p role="status" className="mt-3 text-sm text-gray-500">{settingsError?'':'Yükleniyor…'}</p>:<div className="mt-3 space-y-4">
    <div className="flex flex-wrap gap-2 text-xs font-bold"><span className={`rounded-full border px-3 py-1 ${settings.publicWhatsappEnabled?'border-emerald-300 bg-emerald-50 text-emerald-800':'border-gray-300 bg-gray-100 text-gray-700'}`}>WhatsApp siparişi: {settings.publicWhatsappEnabled?'mağazada açık':'kapalı'}</span><span className={`rounded-full border px-3 py-1 ${settings.publicBankEnabled?'border-emerald-300 bg-emerald-50 text-emerald-800':'border-gray-300 bg-gray-100 text-gray-700'}`}>Havale/EFT: {settings.publicBankEnabled?'mağazada açık':settings.bankAccounts.length?'kapalı':'IBAN eklenince açılır'}</span></div>
    <fieldset disabled={!settings.canManage||savingSettings} className="grid gap-4 md:grid-cols-2">
     <label className="flex min-h-11 items-center gap-3 rounded-xl border p-3"><input type="checkbox" checked={settings.whatsappEnabled} onChange={event=>patchSettings({whatsappEnabled:event.target.checked})} className="h-5 w-5"/><span className="font-semibold">WhatsApp ile sipariş</span></label>
     <label className="flex min-h-11 items-center gap-3 rounded-xl border p-3"><input type="checkbox" checked={settings.bankTransferEnabled} onChange={event=>patchSettings({bankTransferEnabled:event.target.checked})} className="h-5 w-5"/><span className="font-semibold">Havale / EFT ile sipariş</span></label>
     <label className="block"><span className="text-sm font-bold">Sipariş WhatsApp numarası</span><input value={settings.whatsappNumber} onChange={event=>patchSettings({whatsappNumber:event.target.value.replace(/[^\d+\s]/g,'').slice(0,20)})} inputMode="tel" placeholder={settings.contactWhatsappNumber?`Boş bırakılırsa: ${settings.contactWhatsappNumber}`:'905xx xxx xx xx'} className="mt-1 min-h-11 w-full rounded-xl border px-3"/><span className="mt-1 block text-xs text-gray-500">Boş bırakılırsa İletişim ayarlarındaki WhatsApp numarası kullanılır.</span></label>
     <label className="block"><span className="text-sm font-bold">Havale ödeme süresi (saat)</span><input type="number" min={1} max={240} value={settings.paymentWindowHours} onChange={event=>patchSettings({paymentWindowHours:Math.max(1,Math.min(240,Number(event.target.value)||48))})} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label>
     <label className="block md:col-span-2"><span className="text-sm font-bold">Müşteriye kısa not (isteğe bağlı)</span><input value={settings.customerNote} onChange={event=>patchSettings({customerNote:event.target.value.slice(0,600)})} maxLength={600} placeholder="Örn. Siparişler hafta içi 24 saat içinde kargolanır." className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label>
    </fieldset>
    <div className="space-y-3"><div className="flex items-center justify-between gap-3"><h4 className="font-bold">Banka hesapları</h4>{settings.canManage&&settings.bankAccounts.length<5?<button type="button" onClick={()=>patchSettings({bankAccounts:[...settings.bankAccounts,{...EMPTY_ACCOUNT}]})} className="inline-flex min-h-11 items-center gap-2 rounded-xl border px-3 text-sm font-bold"><Plus aria-hidden="true" className="h-4 w-4"/>Hesap ekle</button>:null}</div>
     {!settings.bankAccounts.length?<p className="rounded-xl border border-dashed p-4 text-sm text-gray-500">Henüz banka hesabı yok. Havale/EFT seçeneği, en az bir geçerli IBAN eklendiğinde mağazada görünür.</p>:null}
     {settings.bankAccounts.map((account,index)=>{const ibanOk=isValidTurkishIban(account.iban);return<fieldset key={index} disabled={!settings.canManage||savingSettings} className="grid gap-3 rounded-xl border p-3 md:grid-cols-2"><legend className="px-1 text-sm font-bold"><Building2 aria-hidden="true" className="mr-1 inline h-4 w-4"/>{index+1}. hesap</legend>
      <label className="block"><span className="text-sm font-semibold">Banka</span><input value={account.bankName} onChange={event=>patchAccount(index,{bankName:event.target.value.slice(0,80)})} placeholder="Örn. Ziraat Bankası" className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label>
      <label className="block"><span className="text-sm font-semibold">Alıcı adı (hesap sahibi)</span><input value={account.accountHolder} onChange={event=>patchAccount(index,{accountHolder:event.target.value.slice(0,140)})} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label>
      <label className="block md:col-span-2"><span className="text-sm font-semibold">IBAN</span><input value={formatIban(account.iban)} onChange={event=>patchAccount(index,{iban:event.target.value.replace(/[^A-Za-z0-9]/g,'').toUpperCase().slice(0,26)})} inputMode="text" autoCapitalize="characters" spellCheck={false} aria-invalid={account.iban.length>4&&!ibanOk?true:undefined} className="mt-1 min-h-11 w-full rounded-xl border px-3 font-mono tracking-wide"/>{account.iban.length>4?<span className={`mt-1 block text-xs font-semibold ${ibanOk?'text-emerald-700':'text-red-700'}`}>{ibanOk?'IBAN doğrulandı.':'IBAN henüz geçerli değil (TR + 24 rakam).'}</span>:null}</label>
      <label className="block"><span className="text-sm font-semibold">Şube (isteğe bağlı)</span><input value={account.branch} onChange={event=>patchAccount(index,{branch:event.target.value.slice(0,80)})} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label>
      <div className="flex items-end justify-between gap-3"><label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={account.active} onChange={event=>patchAccount(index,{active:event.target.checked})} className="h-5 w-5"/><span className="text-sm font-semibold">Müşteriye göster</span></label><button type="button" onClick={()=>patchSettings({bankAccounts:settings.bankAccounts.filter((_,i)=>i!==index)})} aria-label={`${index+1}. hesabı kaldır`} className="min-h-11 min-w-11 rounded-xl border border-red-200 text-red-700"><Trash2 aria-hidden="true" className="mx-auto h-4 w-4"/></button></div>
     </fieldset>;})}
    </div>
    {settings.canManage?<div className="flex flex-wrap items-center gap-3"><button type="button" onClick={()=>void persistSettings()} disabled={savingSettings} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-brand-green px-5 font-black text-brand-on-green disabled:opacity-50">{savingSettings?<Loader2 aria-hidden="true" className="h-4 w-4 animate-spin"/>:<Save aria-hidden="true" className="h-4 w-4"/>}Kaydet</button>{settingsStatus?<span role="status" className="text-sm font-semibold text-emerald-700">{settingsStatus}</span>:null}</div>:<p className="text-sm text-gray-500">Ayarları değiştirmek için ödeme yönetimi yetkisi gerekir.</p>}
   </div>}
  </section>

  <section className="rounded-2xl border bg-white p-4 dark:bg-gray-800" aria-labelledby="order-requests-title">
   <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><h3 id="order-requests-title" className="font-black">Talepler <span className="ml-1 rounded-full bg-amber-100 px-2 py-0.5 text-sm text-amber-900">{openCount} açık</span></h3>
    <form onSubmit={event=>{event.preventDefault();void load(filter,query);}} className="flex gap-2"><label className="sr-only" htmlFor="order-request-search">Sipariş kodu, ad veya telefon</label><input id="order-request-search" value={query} onChange={event=>setQuery(event.target.value.slice(0,120))} placeholder="Kod, ad veya telefon" className="min-h-11 w-56 rounded-xl border px-3"/><button type="submit" className="min-h-11 min-w-11 rounded-xl border" aria-label="Ara"><Search aria-hidden="true" className="mx-auto h-4 w-4"/></button><button type="button" onClick={()=>void load()} className="min-h-11 min-w-11 rounded-xl border" aria-label="Yenile"><RefreshCw aria-hidden="true" className={`mx-auto h-4 w-4 ${loading?'animate-spin':''}`}/></button></form></div>
   <div className="mt-3 flex gap-2 overflow-x-auto pb-1" aria-label="Durum filtresi">{FILTERS.map(option=><button type="button" key={option.value} aria-pressed={filter===option.value} onClick={()=>setFilter(option.value)} className={`min-h-10 shrink-0 rounded-full border px-3 text-sm font-bold ${filter===option.value?'border-brand-green bg-brand-green text-brand-on-green':'bg-white dark:bg-gray-900'}`}>{option.label}{option.value!=='open'&&option.value!=='all'&&counts[option.value as OrderRequestStatus]?` (${counts[option.value as OrderRequestStatus]})`:''}</button>)}</div>
   {error?<div role="alert" className="mt-3 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>:null}
   {loading&&!items.length?<p role="status" className="mt-4 text-sm text-gray-500">Talepler yükleniyor…</p>:null}
   {!loading&&!items.length&&!error?<p className="mt-4 rounded-xl border border-dashed p-5 text-center text-sm text-gray-500">Bu durumda sipariş talebi yok.</p>:null}
   <div className="mt-4 space-y-3">{items.map(request=>{const waDigits=request.phone.replace(/\D/g,'');return<article key={request.id} className="rounded-xl border p-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-lg font-black tracking-wide">{request.reference}</span><span className={`rounded-full border px-2 py-0.5 text-xs font-black ${statusTone(request.status)}`}>{ORDER_REQUEST_STATUS_LABELS[request.status]}</span><span className="rounded-full border px-2 py-0.5 text-xs font-bold">{request.method==='whatsapp'?'WhatsApp':'Havale/EFT'}</span>{request.guest?<span className="rounded-full border px-2 py-0.5 text-xs font-bold">Misafir</span>:<span className="rounded-full border px-2 py-0.5 text-xs font-bold">Üye</span>}{request.stockCommitted?<span className="rounded-full border border-blue-200 px-2 py-0.5 text-xs font-bold text-blue-800">Stoktan düşüldü</span>:null}</div><p className="mt-1 text-xs text-gray-500">{dateTime(request.createdAt)}</p></div><strong className="text-lg">{formatMoney(request.totalMinor,request.currency)}</strong></div>
    <div className="mt-3 grid gap-3 text-sm md:grid-cols-2"><div><p className="font-bold">{request.customerName}</p><p className="mt-1 flex flex-wrap gap-2"><a href={`tel:${request.phone}`} className="inline-flex min-h-11 items-center gap-1 rounded-lg border px-3 font-semibold"><Phone aria-hidden="true" className="h-4 w-4"/>{request.phone}</a><a href={`https://wa.me/${waDigits}?text=${encodeURIComponent(`Merhaba ${request.customerName}, Golden Oremar ${request.reference} numaralı siparişiniz hakkında yazıyoruz.`)}`} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center gap-1 rounded-lg border px-3 font-semibold"><MessageCircle aria-hidden="true" className="h-4 w-4"/>WhatsApp</a></p>{request.email?<p className="mt-1 text-gray-600">{request.email}</p>:null}<p className="mt-2 text-gray-700 dark:text-gray-300">{request.addressLine}<br/>{request.district} / {request.province}</p>{request.customerNote?<p className="mt-2 rounded-lg bg-gray-50 p-2 dark:bg-gray-900">Not: {request.customerNote}</p>:null}</div>
     <div><ul className="space-y-1">{request.items.map((item,index)=><li key={`${item.slug}:${index}`} className="flex justify-between gap-3"><span>{item.quantity} x {item.productName} <span className="text-gray-500">({[item.variantName,item.options].filter(Boolean).join(', ')})</span></span><span className="whitespace-nowrap font-semibold">{formatMoney(item.lineTotalMinor,request.currency)}</span></li>)}</ul><p className="mt-2 flex justify-between border-t pt-2 text-gray-600"><span>Kargo</span><span>{request.shippingMinor===null?'Belirlenecek':request.shippingMinor===0?'Ücretsiz':formatMoney(request.shippingMinor,request.currency)}</span></p></div></div>
    <label className="mt-3 block"><span className="text-sm font-semibold">İç not (kargo takip no, görüşme notu)</span><textarea value={notes[request.id]??request.adminNote??''} onChange={event=>setNotes(current=>({...current,[request.id]:event.target.value.slice(0,2000)}))} rows={2} className="mt-1 w-full rounded-xl border p-2"/></label>
    <div className="mt-3 flex flex-wrap gap-2">{NEXT[request.status].map(action=><button type="button" key={action.status} disabled={busyId===request.id} onClick={()=>void move(request,action.status)} className={`min-h-11 rounded-xl px-4 text-sm font-black disabled:opacity-50 ${action.status==='cancelled'?'border border-red-300 text-red-700':'bg-brand-green text-brand-on-green'}`}>{busyId===request.id?<Loader2 aria-hidden="true" className="mr-1 inline h-4 w-4 animate-spin"/>:null}{action.label}</button>)}<button type="button" disabled={busyId===request.id} onClick={()=>void saveNote(request)} className="min-h-11 rounded-xl border px-4 text-sm font-bold">Notu kaydet</button></div>
   </article>;})}</div>
  </section>
 </div>;
}
