import React,{useEffect,useMemo,useState}from'react';
import{Banknote,CheckCircle2,Loader2,RefreshCw,Search,ShieldCheck,TriangleAlert,X}from'lucide-react';
import{formatPayoutMinor,producerPayoutAdminErrorMessage,superAdminListProducerPayouts,superAdminUpdateProducerPayout,type AdminProducerPayout,type AdminProducerPayoutStatus}from'./producerPayoutAdminApi';
import{useAccessibleDialog}from'../features/accessibility/useAccessibleDialog';
import{useAuthorization}from'../features/auth/AuthorizationContext';

const statusLabel:Record<AdminProducerPayoutStatus,string>={requested:'Talep edildi',scheduled:'Planlandı',processing:'Aktarım işleniyor',paid:'Ödendi',failed:'Başarısız',cancelled:'İptal edildi'};
const channelLabel={provider_marketplace:'iyzico pazaryeri',manual_bank_transfer:'Manuel banka transferi'}as const;
const statusClass:Record<AdminProducerPayoutStatus,string>={requested:'bg-amber-100 text-amber-900 dark:bg-amber-950/40 dark:text-amber-100',scheduled:'bg-blue-100 text-blue-900 dark:bg-blue-950/40 dark:text-blue-100',processing:'bg-violet-100 text-violet-900 dark:bg-violet-950/40 dark:text-violet-100',paid:'bg-green-100 text-green-900 dark:bg-green-950/40 dark:text-green-100',failed:'bg-red-100 text-red-900 dark:bg-red-950/40 dark:text-red-100',cancelled:'bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-200'};
type ActionStatus='processing'|'paid'|'failed'|'cancelled';
function formatDate(value:string|null){if(!value)return'Yok';const date=new Date(value);if(Number.isNaN(date.getTime()))return'Tarih doğrulanamadı';return new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium',timeStyle:'short'}).format(date);}
function formatIban(value:string|null){if(!value)return'IBAN kaydı bulunamadı';return value.replace(/(.{4})/g,'$1 ').trim();}

export function AdminProducerPayouts(){
 const{can}=useAuthorization();const canReview=can('payout.review');const canRelease=can('payout.release');
 const[rows,setRows]=useState<AdminProducerPayout[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[toast,setToast]=useState('');const[status,setStatus]=useState<'all'|AdminProducerPayoutStatus>('all');const[search,setSearch]=useState('');const[selected,setSelected]=useState<AdminProducerPayout|null>(null);const[action,setAction]=useState<ActionStatus|null>(null);const[reference,setReference]=useState('');const[note,setNote]=useState('');
 const closeAction=()=>{if(busy)return;setSelected(null);setAction(null);setReference('');setNote('');setError('');};const dialogRef=useAccessibleDialog<HTMLElement>(Boolean(selected&&action),closeAction);
 async function load(){try{setLoading(true);setError('');setRows(await superAdminListProducerPayouts(status,300,0));}catch(err){setError(producerPayoutAdminErrorMessage(err,'Satıcı ödeme kuyruğu yüklenemedi.'));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[status]);
 const filtered=useMemo(()=>{const q=search.trim().toLocaleLowerCase('tr-TR');if(!q)return rows;return rows.filter(row=>`${row.producerName} ${row.ownerEmail||''} ${row.destinationAccountHolder||''} ${row.destinationIban||''} ${row.orderNumber||''} ${row.providerReference||''}`.toLocaleLowerCase('tr-TR').includes(q));},[rows,search]);
 const totals=useMemo(()=>rows.reduce((acc,row)=>{const key=`${row.currency}:${row.status}`;acc.set(key,(acc.get(key)||0)+row.amountMinor);return acc;},new Map<string,number>()),[rows]);void totals;
 function openAction(row:AdminProducerPayout,next:ActionStatus){if(next==='paid'&&!canRelease)return;if(next!=='paid'&&!canReview)return;setSelected(row);setAction(next);setReference('');setNote(row.note||'');setError('');}
 function flash(message:string){setToast(message);window.setTimeout(()=>setToast(''),4000);}
 async function submit(event:React.FormEvent){event.preventDefault();if(!selected||!action||busy)return;if(action==='paid'&&!canRelease){setError('Bu işlemi yalnız payout.release capability sahibi kullanıcı tamamlayabilir.');return;}if(action!=='paid'&&!canReview){setError('Bu işlem için payout.review capability gerekir.');return;}try{setBusy(true);setError('');await superAdminUpdateProducerPayout({id:selected.id,status:action,reference:reference||null,note:note||null});flash(action==='paid'?'Ödeme gerçek transfer referansıyla ödendi olarak kaydedildi.':action==='processing'?'Çekim işleme alındı.':action==='failed'?'Ödeme başarısız olarak kaydedildi.':'Çekim iptal edildi.');closeAction();await load();}catch(err){setError(producerPayoutAdminErrorMessage(err));}finally{setBusy(false);}}
 return <div className="space-y-6">
  <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full bg-brand-green/10 px-3 py-1 text-xs font-bold text-brand-green"><ShieldCheck aria-hidden="true" className="h-4 w-4"/>{canRelease?'SUPER ADMIN':'PAYOUT REVIEW'}</div><h2 className="mt-3 text-2xl font-bold">Satıcı Ödeme ve IBAN Merkezi</h2><p className="mt-1 max-w-4xl text-sm text-gray-600 dark:text-gray-300">Satıcının tam ödeme hedefi, korumalı havuzdan çıkan iyzico aktarımı ve manuel banka çekimleri burada birlikte izlenir. İnceleme capability'si operasyonel durumları yönetir. Gerçek ödeme serbest bırakma yalnız payout.release capability'sine aittir.</p></div><button type="button" onClick={()=>void load()} disabled={loading||busy} className="min-h-11 rounded-xl border px-4 font-semibold disabled:opacity-50"><RefreshCw aria-hidden="true" className={`mr-2 inline h-4 w-4 ${loading?'animate-spin':''}`}/>Yenile</button></header>

  <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950 dark:border-amber-900/60 dark:bg-amber-950/25 dark:text-amber-100"><div className="flex gap-3"><TriangleAlert aria-hidden="true" className="mt-0.5 h-5 w-5 shrink-0"/><p><strong>Önemli:</strong> “Ödendi” aksiyonu yalnız payout.release capability'si olan Super Admin için görünür. Manuel kanalda önce gerçek banka transferi yapılır, sonra gerçek referans kaydedilir. Server her durumda capability kontrolünü yeniden yapar.</p></div></div>

  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary label="Bekleyen çekim" rows={rows.filter(row=>row.status==='requested')}/><Summary label="Aktarım işleniyor" rows={rows.filter(row=>row.status==='processing')}/><Summary label="Tamamlanan" rows={rows.filter(row=>row.status==='paid')}/><Summary label="Sorunlu" rows={rows.filter(row=>row.status==='failed')}/></section>

  <div className="grid gap-3 rounded-2xl border bg-white p-4 dark:bg-gray-900 md:grid-cols-[minmax(0,1fr)_220px]"><label className="relative"><span className="sr-only">Satıcı ödeme ara</span><Search aria-hidden="true" className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400"/><input type="search" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Satıcı, e-posta, IBAN, sipariş veya referans ara" className="min-h-11 w-full rounded-xl border bg-gray-50 py-2 pl-10 pr-4 dark:bg-gray-950"/></label><label><span className="sr-only">Ödeme durumu</span><select value={status} onChange={event=>setStatus(event.target.value as typeof status)} className="min-h-11 w-full rounded-xl border bg-gray-50 px-3 dark:bg-gray-950"><option value="all">Tüm durumlar</option><option value="requested">Talep edildi</option><option value="processing">Aktarım işleniyor</option><option value="paid">Ödendi</option><option value="failed">Başarısız</option><option value="cancelled">İptal edildi</option><option value="scheduled">Planlandı</option></select></label></div>

  {error&&!selected?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800 dark:border-red-900/50 dark:bg-red-950/30 dark:text-red-200">{error}</div>:null}
  {loading?<div role="status" className="flex min-h-48 items-center justify-center gap-2 rounded-2xl border"><Loader2 aria-hidden="true" className="h-5 w-5 animate-spin"/>Ödeme kayıtları yükleniyor...</div>:<div className="space-y-4">{filtered.map(row=><article key={row.id} className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-gray-900"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-bold">{row.producerName}</h3><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${statusClass[row.status]}`}>{statusLabel[row.status]}</span><span className="rounded-full border px-2.5 py-1 text-xs font-semibold">{channelLabel[row.channel]}</span></div><p className="mt-1 text-sm text-gray-500">{row.ownerEmail||'Satıcı e-postası yok'}{row.orderNumber?` · Sipariş ${row.orderNumber}`:''}</p></div><div className="text-left lg:text-right"><div className="text-xl font-black">{formatPayoutMinor(row.amountMinor,row.currency)}</div><div className="mt-1 text-xs text-gray-500">{formatDate(row.requestedAt||row.createdAt)}</div></div></div>
    <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Info label="Hesap sahibi" value={row.destinationAccountHolder||'Kayıt yok'}/><Info label="Tam IBAN" value={formatIban(row.destinationIban)} mono/><Info label="Sağlayıcı" value={row.provider||channelLabel[row.channel]}/><Info label="Transfer referansı" value={row.providerReference||'Henüz yok'} mono/></div>
    <div className="mt-3 grid gap-3 md:grid-cols-3"><Info label="Korumalı / bekleyen" value={formatPayoutMinor(row.balance.pendingMinor,row.currency)}/><Info label="Manuel çekilebilir" value={formatPayoutMinor(row.balance.availableToPayoutMinor,row.currency)}/><Info label="Toplam rezerve" value={formatPayoutMinor(row.balance.reservedPayoutMinor,row.currency)}/></div>
    {row.note?<div className="mt-3 rounded-xl bg-gray-50 p-3 text-sm dark:bg-gray-950/70"><strong>Not:</strong> {row.note}</div>:null}
    <div className="mt-4 flex flex-wrap gap-2 border-t pt-4">{canReview&&row.channel==='manual_bank_transfer'&&['requested','scheduled'].includes(row.status)?<button type="button" onClick={()=>openAction(row,'processing')} className="min-h-11 rounded-xl border border-violet-200 px-4 font-semibold text-violet-800 dark:text-violet-200">İşleme al</button>:null}{canRelease&&(row.status==='processing'||(row.channel==='manual_bank_transfer'&&['requested','scheduled'].includes(row.status)))?<button type="button" onClick={()=>openAction(row,'paid')} className="min-h-11 rounded-xl bg-brand-green px-4 font-bold text-brand-on-green"><CheckCircle2 aria-hidden="true" className="mr-2 inline h-4 w-4"/>Ödendi olarak kapat</button>:null}{canReview&&(row.status==='processing'||(row.channel==='manual_bank_transfer'&&['requested','scheduled'].includes(row.status)))?<button type="button" onClick={()=>openAction(row,'failed')} className="min-h-11 rounded-xl border border-red-200 px-4 font-semibold text-red-700">Başarısız</button>:null}{canReview&&row.channel==='manual_bank_transfer'&&['requested','scheduled','processing'].includes(row.status)?<button type="button" onClick={()=>openAction(row,'cancelled')} className="min-h-11 rounded-xl border px-4 font-semibold">İptal</button>:null}{['paid','failed','cancelled'].includes(row.status)?<span className="self-center text-sm text-gray-500">Sonuç: {formatDate(row.processedAt)}</span>:null}</div>
   </article>)}{!filtered.length?<div className="rounded-2xl border p-10 text-center text-gray-500">Filtrelerle eşleşen ödeme kaydı yok.</div>:null}</div>}

  {selected&&action?<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60 sm:items-center sm:p-4"><section ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="payout-action-title" tabIndex={-1} className="w-full max-w-xl rounded-t-3xl bg-white p-5 shadow-2xl outline-none dark:bg-gray-900 sm:rounded-2xl"><div className="flex items-start justify-between gap-3"><div><h3 id="payout-action-title" className="text-xl font-bold">{action==='paid'?'Ödemeyi tamamla':action==='processing'?'Ödemeyi işleme al':action==='failed'?'Ödemeyi başarısız kapat':'Çekimi iptal et'}</h3><p className="mt-1 text-sm text-gray-500">{selected.producerName} · {formatPayoutMinor(selected.amountMinor,selected.currency)}</p></div><button type="button" disabled={busy} onClick={closeAction} aria-label="İşlem penceresini kapat" className="min-h-11 min-w-11 rounded-xl"><X aria-hidden="true" className="mx-auto h-5 w-5"/></button></div>
   <div className="mt-4 rounded-xl border p-3 text-sm"><div className="font-semibold">{selected.destinationAccountHolder||'Hesap sahibi yok'}</div><div className="mt-1 break-all font-mono text-base font-bold">{formatIban(selected.destinationIban)}</div><div className="mt-1 text-xs text-gray-500">{channelLabel[selected.channel]}</div></div>
   {error?<div role="alert" className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800 dark:border-red-900/50 dark:bg-red-950/30 dark:text-red-200">{error}</div>:null}
   <form onSubmit={submit} className="mt-4 space-y-4">{action==='paid'?<label><span className="block text-sm font-semibold">Gerçek transfer referansı</span><input required minLength={4} maxLength={180} value={reference} onChange={event=>setReference(event.target.value)} placeholder={selected.channel==='provider_marketplace'?'iyzico mutabakat/transfer referansı':'Banka EFT/Havale referansı'} className="mt-1 min-h-11 w-full rounded-xl border px-3"/><span className="mt-1 block text-xs text-gray-500">Bu kayıt para göndermez. Önce gerçek transferin tamamlandığını doğrulayın.</span></label>:null}<label><span className="block text-sm font-semibold">Operasyon notu</span><textarea rows={4} maxLength={1000} required={action==='failed'||action==='cancelled'} minLength={action==='failed'||action==='cancelled'?10:undefined} value={note} onChange={event=>setNote(event.target.value)} className="mt-1 w-full rounded-xl border p-3" placeholder="Mutabakat, hata veya işlem açıklaması"/></label><div className="flex gap-3"><button type="button" disabled={busy} onClick={closeAction} className="min-h-11 flex-1 rounded-xl border">Vazgeç</button><button disabled={busy} className={`min-h-11 flex-1 rounded-xl font-bold text-white ${action==='failed'||action==='cancelled'?'bg-red-700':'bg-brand-green'}`}>{busy?<><Loader2 aria-hidden="true" className="mr-2 inline h-4 w-4 animate-spin"/>İşleniyor</>:action==='paid'?'Transferi kaydet':action==='processing'?'İşleme al':action==='failed'?'Başarısız kaydet':'İptal et'}</button></div></form>
  </section></div>:null}
  {toast?<div role="status" aria-live="polite" className="fixed bottom-4 right-4 z-[60] max-w-sm rounded-xl bg-gray-900 px-5 py-3 text-sm font-semibold text-white">{toast}</div>:null}
 </div>;
}

function Info({label,value,mono=false}:{label:string;value:string;mono?:boolean}){return<div className="rounded-xl bg-gray-50 p-3 dark:bg-gray-950/70"><div className="text-xs text-gray-500">{label}</div><div className={`mt-1 break-all font-semibold ${mono?'font-mono':''}`}>{value}</div></div>;}
function Summary({label,rows}:{label:string;rows:AdminProducerPayout[]}){const grouped=rows.reduce((map,row)=>map.set(row.currency,(map.get(row.currency)||0)+row.amountMinor),new Map<string,number>());return<div className="rounded-2xl border bg-white p-4 dark:bg-gray-900"><div className="flex items-center gap-2 text-sm font-semibold text-gray-500"><Banknote aria-hidden="true" className="h-4 w-4"/>{label}</div><div className="mt-2 text-2xl font-black">{rows.length}</div><div className="mt-2 space-y-1 text-xs text-gray-500">{Array.from(grouped.entries()).map(([currency,minor])=><div key={currency}>{formatPayoutMinor(minor,currency)}</div>)}{!rows.length?<div>0 kayıt</div>:null}</div></div>;}
