import React,{useEffect,useMemo,useState}from'react';
import{Check,CheckCircle,Eye,FileSearch,Loader2,MapPin,RefreshCw,Search,ShieldCheck,Store,X,XCircle}from'lucide-react';
import{adminGetProducerApplicationSensitive,adminListProducerApplications,adminReviewProducerApplication,adminSetProducerDocumentStatus,producerApplicationErrorMessage,type AdminProducerApplication,type ProducerApplicationDocument,type ProducerApplicationReviewStatus,type ProducerApplicationStatus,type ProducerDocumentReviewStatus,type ProducerDocumentVerificationStatus,type SensitiveProducerApplication}from'./producerApplicationAdminApi';
import{createProducerDocumentPreviewUrl}from'./producerDocumentApi';
import{useAccessibleDialog}from'../features/accessibility/useAccessibleDialog';
import{useCustomerSession}from'../features/auth/useCustomerSession';

type ReviewAction=ProducerApplicationReviewStatus;
const activityLabels:Record<string,string>={beekeeping:'Arıcılık',livestock:'Hayvancılık',dairy:'Süt üretimi',poultry:'Kümes hayvancılığı',field_farming:'Tarla tarımı',fruit_growing:'Meyvecilik',vegetable_growing:'Sebzecilik',wild_harvest:'Dağ ve doğa mahsulleri',fishing:'Balıkçılık',food_processing:'Geleneksel gıda işleme',beverage_production:'Yöresel içecek üretimi',natural_materials:'Doğal malzeme üretimi'};
const sourceLabels:Record<string,string>={own_production:'Kendi üretimi',family_production:'Aile üretimi',cooperative_production:'Kooperatif üretimi'};
function statusLabel(status:ProducerApplicationStatus){return({draft:'Taslak',submitted:'Gönderildi',under_review:'İnceleniyor',needs_information:'Ek bilgi gerekli',approved:'Onaylandı',rejected:'Reddedildi',withdrawn:'Geri çekildi'}as const)[status];}
function statusClass(status:ProducerApplicationStatus){if(status==='approved')return'bg-green-100 text-green-800 dark:bg-green-950/40 dark:text-green-200';if(status==='rejected'||status==='withdrawn')return'bg-red-100 text-red-800 dark:bg-red-950/40 dark:text-red-200';if(status==='needs_information')return'bg-orange-100 text-orange-800 dark:bg-orange-950/40 dark:text-orange-200';if(status==='under_review')return'bg-blue-100 text-blue-800 dark:bg-blue-950/40 dark:text-blue-200';if(status==='submitted')return'bg-yellow-100 text-yellow-800 dark:bg-yellow-950/40 dark:text-yellow-200';return'bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-200';}
function documentStatusClass(status:ProducerDocumentVerificationStatus){if(status==='verified')return'bg-green-100 text-green-800';if(status==='rejected')return'bg-red-100 text-red-800';if(status==='expired')return'bg-gray-200 text-gray-800';return'bg-yellow-100 text-yellow-800';}
function documentStatusLabel(status:ProducerDocumentVerificationStatus){return({pending:'Bekliyor',verified:'Doğrulandı',rejected:'Reddedildi',expired:'Süresi doldu'}as const)[status];}
function formatDate(value:string|null|undefined){if(!value)return'Bilinmiyor';const date=new Date(value);return Number.isNaN(date.getTime())?'Bilinmiyor':date.toLocaleString('tr-TR',{dateStyle:'medium',timeStyle:'short'});}
function structuredLocation(app:AdminProducerApplication){const parts=[app.production_village,app.production_district,app.production_province,app.production_country_code].filter(Boolean);return parts.length?parts.join(' / '):app.production_location||'Belirtilmemiş';}
function villageProvenance(app:AdminProducerApplication){if(!app.production_village)return'Köy adı girilmedi';return app.production_village_is_custom?'Satıcı köy adını elle girdi':'Köy adı yapılandırılmış listeden seçildi';}
function applicantDisplay(app:AdminProducerApplication){return app.legal_name||app.public_name||app.email||'Başvuru sahibi bilgisi eksik';}
function documentSizeLabel(size:number){return size<1024*1024?`${Math.ceil(size/1024)} KB`:`${(size/(1024*1024)).toLocaleString('tr-TR',{maximumFractionDigits:1})} MB`;}
function fullAddress(value:Record<string,unknown>|null|undefined){if(!value)return'Kayıt yok';const entries=Object.entries(value).filter(([,item])=>item!=null&&String(item).trim());return entries.length?entries.map(([key,item])=>`${key}: ${String(item)}`).join('\n'):'Kayıt yok';}

export function AdminVendorApplications(){
 const{currentUser}=useCustomerSession();const roles=Array.isArray(currentUser?.roles)?currentUser.roles.map(String):[];const isSuperAdmin=roles.includes('super_admin');
 const[applications,setApplications]=useState<AdminProducerApplication[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');const[error,setError]=useState('');const[toast,setToast]=useState('');const[searchTerm,setSearchTerm]=useState('');const[statusFilter,setStatusFilter]=useState<'all'|ProducerApplicationStatus>('submitted');const[selected,setSelected]=useState<AdminProducerApplication|null>(null);const[reviewAction,setReviewAction]=useState<ReviewAction|null>(null);const[reviewReason,setReviewReason]=useState('');const[commissionPercent,setCommissionPercent]=useState(10);const[sensitivePurpose,setSensitivePurpose]=useState('Satıcı ödeme ve KYC operasyon kontrolü');const[sensitive,setSensitive]=useState<SensitiveProducerApplication|null>(null);const[sensitiveLoading,setSensitiveLoading]=useState(false);
 const closeDetail=()=>{if(busy||sensitiveLoading||reviewAction)return;setSelected(null);setSensitive(null);setSensitivePurpose('Satıcı ödeme ve KYC operasyon kontrolü');setError('');};const closeReview=()=>{if(busy)return;setReviewAction(null);setReviewReason('');setError('');};
 const detailDialogRef=useAccessibleDialog<HTMLElement>(Boolean(selected),closeDetail);const reviewDialogRef=useAccessibleDialog<HTMLElement>(Boolean(reviewAction&&selected),closeReview);
 function showToast(message:string){setToast(message);window.setTimeout(()=>setToast(''),3000);}
 async function load(silent=false){if(!silent)setLoading(true);setError('');try{const rows=await adminListProducerApplications();setApplications(rows);setSelected(current=>current?rows.find(row=>row.id===current.id)||null:null);}catch(nextError){setError(producerApplicationErrorMessage(nextError,'Satıcı başvuruları yüklenemedi.'));}finally{if(!silent)setLoading(false);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{if(!isSuperAdmin){setSensitive(null);setSensitivePurpose('Satıcı ödeme ve KYC operasyon kontrolü');}},[isSuperAdmin]);
 const filtered=useMemo(()=>{const q=searchTerm.trim().toLocaleLowerCase('tr-TR');return applications.filter(app=>{if(statusFilter!=='all'&&app.status!==statusFilter)return false;if(!q)return true;const productText=app.planned_products.map(item=>`${item.name} ${item.category} ${sourceLabels[item.source_model]||item.source_model}`).join(' ');return`${app.brand_name} ${app.public_name} ${app.legal_name||''} ${app.email} ${structuredLocation(app)} ${app.activity_types.map(value=>activityLabels[value]||value).join(' ')} ${productText}`.toLocaleLowerCase('tr-TR').includes(q);});},[applications,searchTerm,statusFilter]);
 function openDetail(app:AdminProducerApplication){setSelected(app);setSensitive(null);setSensitivePurpose('Satıcı ödeme ve KYC operasyon kontrolü');setError('');}
 async function submitReview(event:React.FormEvent){event.preventDefault();if(!selected||!reviewAction||busy)return;setBusy(selected.id);setError('');try{await adminReviewProducerApplication({applicationId:selected.id,status:reviewAction,reason:reviewReason,commissionPercent});showToast(reviewAction==='approved'?'Başvuru onaylandı. Faaliyet ve kategori kapsamı üretici hesabına işlendi.':reviewAction==='rejected'?'Başvuru reddedildi.':reviewAction==='needs_information'?'Üreticiden ek bilgi istendi.':'Başvuru incelemeye alındı.');setReviewAction(null);await load(true);}catch(nextError){setError(producerApplicationErrorMessage(nextError));}finally{setBusy('');}}
 async function updateDocument(document:ProducerApplicationDocument,status:ProducerDocumentReviewStatus){if(busy)return;setBusy(document.id);setError('');try{await adminSetProducerDocumentStatus(document.id,status);showToast(`Belge ${documentStatusLabel(status).toLocaleLowerCase('tr-TR')} olarak işaretlendi.`);await load(true);}catch(nextError){setError(producerApplicationErrorMessage(nextError,'Belge durumu güncellenemedi.'));}finally{setBusy('');}}
 async function previewDocument(document:ProducerApplicationDocument){if(busy)return;setBusy(document.id);setError('');try{const url=await createProducerDocumentPreviewUrl(document.storage_path);window.open(url,'_blank','noopener,noreferrer');}catch(nextError){setError(producerApplicationErrorMessage(nextError,'Belge önizlemesi açılamadı.'));}finally{setBusy('');}}
 async function unlockSensitive(event:React.FormEvent){event.preventDefault();if(!isSuperAdmin||!selected||sensitiveLoading)return;setSensitiveLoading(true);setError('');try{setSensitive(await adminGetProducerApplicationSensitive(selected.id,sensitivePurpose));}catch(nextError){setError(producerApplicationErrorMessage(nextError,'Tam KYC bilgileri açılamadı.'));}finally{setSensitiveLoading(false);}}
 const canReview=selected&&!['approved','rejected','withdrawn'].includes(selected.status);
 return<div className="space-y-6">
  <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="text-2xl font-black">Satıcı Başvuruları</h2><p className="mt-1 max-w-3xl text-sm leading-relaxed text-gray-500 dark:text-gray-400">Üretici kimliği, gerçek üretim faaliyeti, köy/menşe, ürün sahipliği, kategori kapsamı ve belgeleri ayrı ayrı doğrulanır. Uygulama sahibi Super Admin gerektiğinde tam KYC ve ödeme kimliğini görebilir.</p></div><button type="button" onClick={()=>void load()} disabled={loading} className="flex min-h-11 items-center justify-center gap-2 rounded-xl border-2 border-gray-200 px-4 font-bold transition-all hover:border-brand-gold/30 hover:bg-brand-gold/5 disabled:cursor-not-allowed disabled:opacity-50 dark:border-gray-700"><RefreshCw aria-hidden="true" className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Yenile</button></header>
  {error&&!selected&&!reviewAction?<div role="alert" className="rounded-xl border-2 border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200">⚠ {error}</div>:null}
  <div className="grid gap-3 rounded-2xl border-2 border-gray-200 bg-white p-4 shadow-lg dark:border-gray-700 dark:bg-gray-800 md:grid-cols-[minmax(0,1fr)_220px]"><label className="relative"><span className="sr-only">Başvuru ara</span><Search aria-hidden="true" className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400"/><input type="search" value={searchTerm} onChange={event=>setSearchTerm(event.target.value)} placeholder="Üretici, köy, faaliyet veya ürün ara..." className="input pl-10"/></label><label><span className="sr-only">Başvuru durumu</span><select value={statusFilter} onChange={event=>setStatusFilter(event.target.value as typeof statusFilter)} className="input"><option value="all">Tüm başvurular</option><option value="draft">Taslaklar</option><option value="submitted">Gönderilenler</option><option value="under_review">İncelenenler</option><option value="needs_information">Ek bilgi bekleyen</option><option value="approved">Onaylananlar</option><option value="rejected">Reddedilenler</option><option value="withdrawn">Geri çekilenler</option></select></label></div>
  {loading?<div role="status" className="flex min-h-40 items-center justify-center gap-2 rounded-2xl border-2 border-gray-200 text-sm font-semibold text-gray-500 dark:border-gray-700"><Loader2 aria-hidden="true" className="h-5 w-5 animate-spin"/>Başvurular yükleniyor...</div>:<div className="grid gap-4 xl:grid-cols-2">{filtered.map(app=><article key={app.id} className="rounded-2xl border-2 border-gray-200 bg-white p-5 shadow-lg transition-all hover:border-brand-gold/30 dark:border-gray-700 dark:bg-gray-800"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 gap-3"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-brand-green/10 text-brand-green"><Store aria-hidden="true" className="h-6 w-6"/></span><div className="min-w-0"><h3 className="truncate font-black">{app.brand_name}</h3><p className="truncate text-sm text-gray-500 dark:text-gray-400">{applicantDisplay(app)}</p></div></div><span className={`shrink-0 rounded-full border-2 border-white px-2.5 py-1 text-xs font-bold dark:border-gray-800 ${statusClass(app.status)}`}>{statusLabel(app.status)}</span></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><Info label="Üretim yeri" value={structuredLocation(app)} icon={<MapPin aria-hidden="true" className="h-4 w-4"/>}/><Info label="Köy kayıt biçimi" value={villageProvenance(app)}/><Info label="Faaliyet" value={app.activity_types.map(value=>activityLabels[value]||value).join(', ')}/><Info label="Kategori kapsamı" value={app.product_categories.join(', ')}/><Info label="Planlanan ürün" value={`${app.planned_products.length} ürün`}/></div><div className="mt-5 flex items-center justify-between border-t-2 border-gray-100 pt-4 dark:border-gray-700"><span className="text-xs text-gray-500 dark:text-gray-400">{app.submitted_at?`Gönderim: ${formatDate(app.submitted_at)}`:`Oluşturma: ${formatDate(app.created_at)}`}</span><button type="button" onClick={()=>openDetail(app)} className="min-h-11 rounded-xl border-2 border-brand-green bg-brand-green px-4 font-bold text-brand-on-green shadow-lg transition-all hover:bg-green-700"><Eye aria-hidden="true" className="mr-2 inline h-4 w-4"/>İncele</button></div></article>)}{!filtered.length?<div className="xl:col-span-2 rounded-2xl border-2 border-gray-200 bg-gray-50 p-10 text-center text-sm font-semibold text-gray-500 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-400">Filtrelerle eşleşen başvuru yok.</div>:null}</div>}

  {selected?<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60 sm:items-center sm:p-4"><section ref={detailDialogRef} role="dialog" aria-modal="true" aria-labelledby="application-title" tabIndex={-1} className="max-h-[96dvh] w-full max-w-5xl overflow-y-auto rounded-t-3xl border-2 border-gray-200 bg-white p-5 shadow-2xl outline-none dark:border-gray-700 dark:bg-gray-800 sm:rounded-2xl sm:p-6"><div className="flex items-start justify-between gap-4"><div><h3 id="application-title" className="text-xl font-black">{selected.brand_name}</h3><p className="mt-1 text-sm leading-relaxed text-gray-500 dark:text-gray-400">{applicantDisplay(selected)} · {statusLabel(selected.status)}</p></div><button type="button" disabled={Boolean(busy)||sensitiveLoading||Boolean(reviewAction)} onClick={closeDetail} aria-label="Başvuru detayını kapat" className="min-h-11 min-w-11 rounded-xl transition-all hover:bg-gray-100 disabled:cursor-not-allowed disabled:opacity-50 dark:hover:bg-gray-700"><X aria-hidden="true" className="mx-auto h-5 w-5"/></button></div>{error&&!reviewAction?<div role="alert" className="mt-4 rounded-xl border-2 border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-800 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200">⚠ {error}</div>:null}
   <div className="mt-5 grid gap-4 lg:grid-cols-2"><section className="rounded-2xl border-2 border-gray-200 p-4 dark:border-gray-700"><h4 className="font-black">Üretici profili</h4><dl className="mt-3 space-y-3 text-sm"><Row label="Başvuru türü" value={`${selected.applicant_type} · ${selected.seller_classification}`}/><Row label="Köy / üretim yeri" value={structuredLocation(selected)}/><Row label="Köy kayıt biçimi" value={villageProvenance(selected)}/><Row label="Faaliyetler" value={selected.activity_types.map(value=>activityLabels[value]||value).join(', ')}/><Row label="Onay istenen kategoriler" value={selected.product_categories.join(', ')}/><Row label="Üretim kaynakları" value={selected.sourcing_models.map(value=>sourceLabels[value]||value).join(', ')}/><Row label="Üretim uygulamaları" value={selected.production_practice_notes||'Girilmedi'}/></dl></section><section className="rounded-2xl border-2 border-gray-200 p-4 dark:border-gray-700"><h4 className="font-black">Uygunluk ve KYC özeti</h4><dl className="mt-3 space-y-3 text-sm"><Row label="İletişim" value={`${selected.email||'E-posta yok'}${selected.phone?` · ${selected.phone}`:''}`}/><Row label="E-posta / telefon" value={`${selected.contact_email_verified_at?'E-posta doğrulandı':'E-posta doğrulanmadı'} · ${selected.phone_verified_at?'Telefon doğrulandı':'Telefon doğrulanmadı'}`}/><Row label="Gıda uygunluğu" value={selected.food_compliance_status}/><Row label="Organik iddia" value={`${selected.organic_claim_status}${selected.organic_certifier_name?` · ${selected.organic_certifier_name}`:''}`}/><Row label="Maskelenmiş kimlik / vergi" value={selected.identifier_masked||'Kayıt yok'}/><Row label="Maskelenmiş IBAN" value={selected.iban_masked||'Kayıt yok'}/></dl></section></div>
   <section className="mt-4 rounded-2xl border-2 border-gray-200 p-4 dark:border-gray-700"><h4 className="font-black">Planlanan kendi ürünleri</h4><p className="mt-1 text-xs leading-relaxed text-gray-500 dark:text-gray-400">Her ürün başvurudaki kategori kapsamına ve izin verilen üretim kaynağına bağlıdır.</p><div className="mt-3 grid gap-3 sm:grid-cols-2">{selected.planned_products.map((item,index)=><div key={`${item.name}-${index}`} className="rounded-xl border-2 border-gray-100 bg-gray-50 p-3 dark:border-gray-700 dark:bg-gray-900/60"><div className="font-bold">{item.name}</div><div className="mt-1 text-sm text-gray-500 dark:text-gray-400">{item.category} · {sourceLabels[item.source_model]||item.source_model}</div><div className="mt-1 text-xs text-gray-500 dark:text-gray-400">Tahmini {item.estimated_quantity} {item.unit}</div></div>)}</div></section>
   <section className="mt-4 rounded-2xl border-2 border-gray-200 p-4 dark:border-gray-700"><div className="flex items-center justify-between"><div><h4 className="font-black">Belgeler</h4><p className="mt-1 text-xs leading-relaxed text-gray-500 dark:text-gray-400">Belge doğrulaması ürün ve üretici onayından ayrıdır.</p></div><FileSearch aria-hidden="true" className="h-5 w-5 text-gray-400"/></div><div className="mt-3 space-y-2">{selected.documents.map(document=><div key={document.id} className="flex flex-col gap-3 rounded-xl border-2 border-gray-100 bg-gray-50 p-3 dark:border-gray-700 dark:bg-gray-900/60 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><span className="font-bold">{document.document_type}</span><span className={`ml-2 rounded-full border-2 border-white px-2 py-0.5 text-xs font-bold dark:border-gray-900 ${documentStatusClass(document.verification_status)}`}>{documentStatusLabel(document.verification_status)}</span><p className="mt-1 text-xs text-gray-500 dark:text-gray-400">{document.mime_type} · {documentSizeLabel(document.size_bytes)}</p></div><div className="flex flex-wrap gap-2"><button type="button" disabled={Boolean(busy)} onClick={()=>void previewDocument(document)} className="min-h-11 rounded-lg border-2 border-gray-200 px-3 text-sm font-bold transition-all hover:border-brand-gold/30 hover:bg-brand-gold/5 disabled:cursor-not-allowed disabled:opacity-40 dark:border-gray-700">Önizle</button><button type="button" disabled={Boolean(busy)||document.verification_status==='verified'} onClick={()=>void updateDocument(document,'verified')} className="min-h-11 rounded-lg border-2 border-green-200 px-3 text-sm font-bold text-green-700 transition-all hover:bg-green-50 disabled:cursor-not-allowed disabled:opacity-40">Doğrula</button><button type="button" disabled={Boolean(busy)||document.verification_status==='rejected'} onClick={()=>void updateDocument(document,'rejected')} className="min-h-11 rounded-lg border-2 border-red-200 px-3 text-sm font-bold text-red-700 transition-all hover:bg-red-50 disabled:cursor-not-allowed disabled:opacity-40">Reddet</button></div></div>)}{!selected.documents.length?<p className="py-4 text-center text-sm font-semibold text-gray-500 dark:text-gray-400">Belge yok.</p>:null}</div></section>
   {isSuperAdmin?<section className="mt-4 rounded-2xl border-2 border-amber-200 bg-amber-50 p-4 dark:border-amber-900/50 dark:bg-amber-950/20"><div className="flex gap-3"><ShieldCheck aria-hidden="true" className="h-5 w-5 shrink-0 text-amber-700"/><div className="min-w-0 flex-1"><h4 className="font-black">Super Admin tam KYC ve ödeme kimliği</h4><p className="mt-1 text-xs leading-relaxed">Uygulama sahibinin ödeme, doğrulama, mutabakat ve destek operasyonu için tam kimlik, vergi, iletişim ve IBAN kaydı açılır. Görüntüleme amacı denetim kaydına yazılır.</p>{!sensitive?<form onSubmit={unlockSensitive} className="mt-3 flex flex-col gap-2 sm:flex-row"><input required minLength={10} maxLength={200} value={sensitivePurpose} onChange={event=>setSensitivePurpose(event.target.value)} className="input flex-1" aria-label="KYC erişim amacı"/><button disabled={sensitiveLoading||sensitivePurpose.trim().length<10} className="min-h-11 rounded-xl border-2 border-amber-700 bg-amber-700 px-4 font-bold text-white shadow-lg transition-all hover:bg-amber-800 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">{sensitiveLoading?'Açılıyor...':'Tam KYC kaydını aç'}</button></form>:<div className="mt-4"><dl className="grid gap-3 text-sm sm:grid-cols-2"><Row label="Yasal ad" value={sensitive.legal_name||'Kayıt yok'}/><Row label="Kimlik no" value={sensitive.national_id||'Kayıt yok'}/><Row label="Vergi no" value={sensitive.tax_number||'Kayıt yok'}/><Row label="Vergi dairesi" value={sensitive.tax_office||'Kayıt yok'}/><Row label="MERSİS" value={sensitive.mersis_number||'Kayıt yok'}/><Row label="Vergi muafiyet no" value={sensitive.tax_exemption_number||'Kayıt yok'}/><Row label="Gıda kayıt no" value={sensitive.food_registration_number||'Kayıt yok'}/><Row label="Organik sertifika no" value={sensitive.organic_certificate_number||'Kayıt yok'}/><Row label="Banka hesap sahibi" value={sensitive.bank_account_holder||'Kayıt yok'}/><Row label="Tam IBAN" value={sensitive.iban||'Kayıt yok'}/><Row label="Telefon" value={sensitive.phone||'Kayıt yok'}/><Row label="İletişim e-postası" value={sensitive.contact_email||'Kayıt yok'}/><Row label="Rıza sürümü" value={sensitive.consent_version||'Kayıt yok'}/><Row label="Rıza tarihi" value={formatDate(sensitive.consented_at)}/><div className="sm:col-span-2"><dt className="text-xs text-gray-500 dark:text-gray-400">Tam adres kaydı</dt><dd className="mt-1 whitespace-pre-wrap break-words rounded-xl border-2 border-gray-200 bg-white p-3 font-medium dark:border-gray-700 dark:bg-gray-900/60">{fullAddress(sensitive.address)}</dd></div></dl><button type="button" onClick={()=>{setSensitive(null);setSensitivePurpose('Satıcı ödeme ve KYC operasyon kontrolü');}} className="mt-4 min-h-11 w-full rounded-xl border-2 border-gray-200 font-bold transition-all hover:border-brand-gold/30 hover:bg-brand-gold/5 dark:border-gray-700">Tam KYC görünümünü kapat</button></div>}</div></div></section>:null}
   {canReview?<div className="mt-5 grid gap-2 sm:grid-cols-4"><button type="button" onClick={()=>{setReviewAction('under_review');setReviewReason('');}} className="min-h-11 rounded-xl border-2 border-blue-200 font-bold text-blue-700 transition-all hover:bg-blue-50">İncelemeye al</button><button type="button" onClick={()=>{setReviewAction('needs_information');setReviewReason('');}} className="min-h-11 rounded-xl border-2 border-orange-200 font-bold text-orange-700 transition-all hover:bg-orange-50">Ek bilgi iste</button><button type="button" onClick={()=>{setReviewAction('rejected');setReviewReason('');}} className="min-h-11 rounded-xl border-2 border-red-200 font-bold text-red-700 transition-all hover:bg-red-50"><XCircle aria-hidden="true" className="mr-1 inline h-4 w-4"/>Reddet</button><button type="button" onClick={()=>{setReviewAction('approved');setReviewReason('');}} className="min-h-11 rounded-xl border-2 border-brand-green bg-brand-green font-bold text-brand-on-green shadow-lg transition-all hover:bg-green-700"><CheckCircle aria-hidden="true" className="mr-1 inline h-4 w-4"/>Onayla</button></div>:null}
  </section></div>:null}

  {reviewAction&&selected?<div className="fixed inset-0 z-[60] flex items-end justify-center bg-black/65 sm:items-center sm:p-4"><section ref={reviewDialogRef} role="dialog" aria-modal="true" aria-labelledby="review-title" tabIndex={-1} className="w-full max-w-lg rounded-t-3xl border-2 border-gray-200 bg-white p-5 shadow-2xl outline-none dark:border-gray-700 dark:bg-gray-800 sm:rounded-2xl"><h3 id="review-title" className="text-lg font-black">{reviewAction==='approved'?'Üreticiyi ve yetki kapsamını onayla':reviewAction==='rejected'?'Başvuruyu reddet':reviewAction==='needs_information'?'Ek bilgi iste':'İncelemeye al'}</h3><p className="mt-1 text-sm leading-relaxed text-gray-500 dark:text-gray-400">{reviewAction==='approved'?'Onaydan sonra faaliyet türleri ve seçilen kategoriler üretici hesabının satıcı yetki kapsamı olacaktır.':'İşlem sunucu denetim kaydıyla uygulanır.'}</p>{error?<div role="alert" className="mt-4 rounded-xl border-2 border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-800 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200">⚠ {error}</div>:null}<form onSubmit={submitReview} className="mt-4 space-y-4"><label><span className="block text-sm font-bold">Platform komisyonu (%)</span><input type="number" min="0" max="30" step="0.01" value={commissionPercent} onChange={event=>setCommissionPercent(Number(event.target.value))} className="input mt-1"/></label><label><span className="block text-sm font-bold">Gerekçe / inceleme notu</span><textarea required={reviewAction==='rejected'||reviewAction==='needs_information'} minLength={reviewAction==='rejected'||reviewAction==='needs_information'?10:undefined} maxLength={1000} rows={4} value={reviewReason} onChange={event=>setReviewReason(event.target.value)} className="input mt-1 p-3"/></label><div className="flex gap-3"><button type="button" disabled={Boolean(busy)} onClick={closeReview} className="min-h-11 flex-1 rounded-xl border-2 border-gray-200 font-bold transition-all hover:border-brand-gold/30 hover:bg-brand-gold/5 disabled:cursor-not-allowed disabled:opacity-50 dark:border-gray-700">Vazgeç</button><button disabled={Boolean(busy)} aria-busy={Boolean(busy)} className={`min-h-11 flex-1 rounded-xl border-2 font-bold text-white shadow-lg transition-all disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none ${reviewAction==='rejected'?'border-red-700 bg-red-700 hover:bg-red-800':'border-brand-green bg-brand-green hover:bg-green-700'}`}>{busy?<><Loader2 aria-hidden="true" className="mr-1 inline h-4 w-4 animate-spin"/>İşleniyor</>:reviewAction==='approved'?'Onayla':reviewAction==='rejected'?'Reddet':reviewAction==='needs_information'?'Ek bilgi iste':'İncelemeye al'}</button></div></form></section></div>:null}
  {toast?<div role="status" aria-live="polite" className="fixed right-4 z-[70] flex items-center gap-2 rounded-xl border-2 border-gray-900 bg-gray-900 px-5 py-3 font-bold text-white shadow-2xl" style={{bottom:'calc(1rem + env(safe-area-inset-bottom, 0px))'}}><Check aria-hidden="true" className="h-5 w-5 text-green-400"/>✓ {toast}</div>:null}
 </div>;
}

function Info({label,value,icon}:{label:string;value:string;icon?:React.ReactNode}){return<div className="rounded-xl border-2 border-gray-100 bg-gray-50 p-3 dark:border-gray-700 dark:bg-gray-900/60"><div className="text-xs font-bold text-gray-500 dark:text-gray-400">{label}</div><div className="mt-1 flex items-start gap-1.5 font-bold">{icon}{value||'Belirtilmemiş'}</div></div>;}
function Row({label,value}:{label:string;value:string}){return<div><dt className="text-xs font-bold text-gray-500 dark:text-gray-400">{label}</dt><dd className="mt-1 whitespace-pre-wrap break-words font-medium">{value}</dd></div>;}
