import React,{useEffect,useMemo,useState}from'react';
import{AlertTriangle,Bell,Building2,CheckCircle2,CreditCard,FileCheck2,Images,Mail,RefreshCw,Rocket,ShieldCheck,Smartphone,Store,Truck,XCircle}from'lucide-react';
import{getProductionReadiness,type ProductionReadiness}from'./productionReadinessAdminApi';

type Props={setActiveTab?:(tab:string)=>void};
type Row={id:string;label:string;ready:boolean;detail:string;actionTab?:string;actionLabel?:string;icon:React.ReactNode};
const legalLabels:Record<string,string>={about:'Hakkımızda',returns:'İade ve cayma',privacy:'Gizlilik',terms:'Kullanım şartları'};
function State({ready}:{ready:boolean}){return ready?<span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700"><CheckCircle2 className="h-3.5 w-3.5" aria-hidden="true"/>Hazır</span>:<span className="inline-flex items-center gap-1 rounded-full bg-red-50 px-2.5 py-1 text-xs font-bold text-red-700"><XCircle className="h-3.5 w-3.5" aria-hidden="true"/>Eksik</span>;}
function ReadinessRow({row,setActiveTab}:{row:Row;setActiveTab?:Props['setActiveTab']}){return<article className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-gray-800"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-start gap-3"><div className={`rounded-xl p-2.5 ${row.ready?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700'}`}>{row.icon}</div><div className="min-w-0"><h3 className="font-bold text-gray-900 dark:text-white">{row.label}</h3><p className="mt-1 text-sm text-gray-500">{row.detail}</p></div></div><State ready={row.ready}/></div>{!row.ready&&row.actionTab&&setActiveTab?<button type="button" onClick={()=>setActiveTab(row.actionTab!)} className="mt-4 min-h-11 w-full rounded-xl border px-4 font-semibold hover:bg-gray-50 dark:hover:bg-gray-700">{row.actionLabel||'İlgili bölümü aç'}</button>:null}</article>;}
export function AdminProductionReadiness({setActiveTab}:Props){
 const[data,setData]=useState<ProductionReadiness|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState('');
 async function load(initial=false){try{initial?setLoading(true):setRefreshing(true);setError('');setData(await getProductionReadiness());}catch(next){setError(next instanceof Error&&next.message?next.message:'Üretim hazırlığı denetlenemedi.');}finally{setLoading(false);setRefreshing(false);}}
 useEffect(()=>{void load(true);},[]);
 const rows=useMemo<Row[]>(()=>{if(!data)return[];const d=data.database,r=data.runtime,missingLegal=d.legalContent.missingSlugs.map(slug=>legalLabels[slug]||slug).join(', ');const experienceAssetsReady=d.assets.contentObjectCount>0&&d.assets.eventObjectCount>0;return[
  {id:'business',label:'İşletme ve destek kimliği',ready:d.businessIdentity.ready,detail:d.businessIdentity.ready?'Yasal unvan, destek e-postası ve telefon tanımlı.':`Yasal unvan: ${d.businessIdentity.legalNameConfigured?'var':'eksik'}, e-posta: ${d.businessIdentity.supportEmailConfigured?'var':'eksik'}, telefon: ${d.businessIdentity.supportPhoneConfigured?'var':'eksik'}.`,actionTab:'business-compliance',actionLabel:'İşletme kimliğini aç',icon:<Building2 className="h-5 w-5" aria-hidden="true"/>},
  {id:'catalog',label:'Gerçek ürün görselleri',ready:d.assets.catalogReady,detail:`${d.assets.publishedProductCount} yayındaki ürünün ${d.assets.publishedProductsWithRealPrimaryImage} tanesinde gerçek primary Storage görseli var. Eksik: ${d.assets.publishedProductsMissingRealPrimaryImage}.`,actionTab:'products',actionLabel:'Ürünleri aç',icon:<Images className="h-5 w-5" aria-hidden="true"/>},
  {id:'experience-assets',label:'İçerik ve etkinlik görselleri',ready:experienceAssetsReady,detail:`content-public: ${d.assets.contentObjectCount} obje, event-public: ${d.assets.eventObjectCount} obje.`,actionTab:'content',actionLabel:'İçerik kütüphanesini aç',icon:<Images className="h-5 w-5" aria-hidden="true"/>},
  {id:'legal',label:'Yasal içerikler',ready:d.legalContent.ready,detail:d.legalContent.ready?'Zorunlu Türkçe yasal belgeler yayınlanmış.':`Eksik yayınlar: ${missingLegal||'doğrulanamadı'}.`,actionTab:'business-compliance',actionLabel:'Yasal belgeleri aç',icon:<FileCheck2 className="h-5 w-5" aria-hidden="true"/>},
  {id:'shipping',label:'Kargo ağırlıkları',ready:d.shipping.ready,detail:`${d.shipping.activePublishedVariantCount} aktif yayındaki varyantın ${d.shipping.missingWeightVariantCount} tanesinde doğrulanmış ağırlık eksik.`,actionTab:'shipping-readiness',actionLabel:'Kargo hazırlığını aç',icon:<Truck className="h-5 w-5" aria-hidden="true"/>},
  {id:'producer-payments',label:'Üretici iyzico alt-üye hesapları',ready:d.producerPayments.ready,detail:`${d.producerPayments.activeVerifiedProducerCount} aktif doğrulanmış üreticiden ${d.producerPayments.readyProducerPaymentAccountCount} tanesi tahsilata hazır. Eksik: ${d.producerPayments.missingProducerPaymentAccountCount}.`,actionTab:'vendors',actionLabel:'Satıcıları aç',icon:<Store className="h-5 w-5" aria-hidden="true"/>},
  {id:'payment',label:'Uygulama içi canlı ödeme',ready:r.paymentReady,detail:`iyzico sunucu yapılandırması ${r.iyzicoConfigured?'hazır':'eksik'}; uygulama içi ödeme akışı ${d.paymentControl.atLeastOneCheckoutFlowEnabled?'açık':'kapalı'}.`,actionTab:'payment-controls',actionLabel:'Ödeme altyapısını aç',icon:<CreditCard className="h-5 w-5" aria-hidden="true"/>},
  {id:'email',label:'Ödeme makbuzu e-postası',ready:r.transactionalEmailConfigured,detail:r.transactionalEmailConfigured?'Resend ve doğrulanmış gönderici sunucuda hazır.':'Resend API anahtarı veya doğrulanmış gönderici adresi eksik.',actionTab:'transactional-emails',actionLabel:'Makbuz kuyruğunu aç',icon:<Mail className="h-5 w-5" aria-hidden="true"/>},
  {id:'android-push',label:'Android push bildirimleri',ready:r.fcmConfigured,detail:r.fcmConfigured?'FCM service account sunucu yapılandırması hazır.':'FCM project ID, service account e-postası veya private key eksik.',actionTab:'notifications',actionLabel:'Bildirim merkezini aç',icon:<Bell className="h-5 w-5" aria-hidden="true"/>},
  {id:'ios-push',label:'iOS push bildirimleri',ready:r.apnsConfigured,detail:r.apnsConfigured?'APNs production sunucu yapılandırması hazır.':'APNs team ID, key ID, private key veya bundle ID eksik.',actionTab:'notifications',actionLabel:'Bildirim merkezini aç',icon:<Smartphone className="h-5 w-5" aria-hidden="true"/>}
 ];},[data]);
 const readyCount=rows.filter(row=>row.ready).length;
 if(loading&&!data)return<div role="status" className="flex min-h-64 items-center justify-center rounded-2xl border bg-white p-6 dark:bg-gray-800">Üretim hazırlığı denetleniyor...</div>;
 return<div className="space-y-6"><header className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-2"><Rocket className="h-7 w-7 text-brand-green" aria-hidden="true"/><h2 className="text-2xl font-bold">Üretim Hazırlığı</h2></div><p className="mt-2 max-w-3xl text-sm text-gray-500">Bu ekran canlı veritabanı, Storage ve sunucu konfigürasyonunu denetler. Eksik işletme bilgisi, görsel, kargo ağırlığı, ödeme hesabı veya gizli anahtar hazırmış gibi gösterilmez.</p></div><button type="button" onClick={()=>void load(false)} disabled={refreshing} className="min-h-11 rounded-xl border bg-white px-4 font-semibold disabled:opacity-50 dark:bg-gray-800"><RefreshCw className={`mr-2 inline h-4 w-4 ${refreshing?'animate-spin':''}`} aria-hidden="true"/>Yeniden denetle</button></header>
 {error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{error}</div>:null}
 {data?<section className={`rounded-2xl border p-5 ${data.automatedReady?'border-emerald-200 bg-emerald-50':'border-amber-200 bg-amber-50'}`} aria-labelledby="automated-readiness-title"><div className="flex items-start gap-3">{data.automatedReady?<ShieldCheck className="mt-0.5 h-6 w-6 text-emerald-700" aria-hidden="true"/>:<AlertTriangle className="mt-0.5 h-6 w-6 text-amber-800" aria-hidden="true"/>}<div><h3 id="automated-readiness-title" className="font-bold">{data.automatedReady?'Otomatik üretim kontrolleri hazır':'Otomatik üretim kontrolleri henüz tamamlanmadı'}</h3><p className="mt-1 text-sm">{readyCount}/{rows.length} otomatik kontrol hazır. Son denetim: {new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(data.generatedAt))}.</p><p className="mt-2 text-xs">Bu durum mağaza imzalama ve harici sağlayıcı konsollarındaki manuel release kontrollerinin tamamlandığı anlamına gelmez.</p></div></div></section>:null}
 <section className="grid gap-4 xl:grid-cols-2">{rows.map(row=><ReadinessRow key={row.id} row={row} setActiveTab={setActiveTab}/>)}</section>
 {data?<section className="rounded-2xl border bg-white p-5 dark:bg-gray-800" aria-labelledby="manual-release-title"><h3 id="manual-release-title" className="font-bold">Manuel release kontrolleri</h3><p className="mt-1 text-sm text-gray-500">Bunlar Supabase sunucusundan güvenilir biçimde doğrulanamaz. Gerçek mağaza/sağlayıcı ekranlarında kontrol edilmeden “tamam” kabul edilmez.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{data.manualReleaseChecks.map(item=><div key={item.id} className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-amber-800" aria-hidden="true"/><div><div className="font-semibold">{item.label}</div><div className="mt-1 text-xs text-amber-900">Manuel doğrulama gerekli</div></div></div>)}</div></section>:null}
 </div>;
}
