import React,{useEffect,useMemo,useState}from'react';
import{Crown,FilePenLine,Headphones,Loader2,RefreshCw,Search,Shield,Store,UserCog,Users,Wrench}from'lucide-react';
import{ADMIN_PLATFORM_USER_ROLES,adminListPlatformUsers,adminSetPlatformUserRole,userAdminErrorMessage,type AdminPlatformUser,type AdminPlatformUserRole}from'./userAdminApi';

const ROLE_LABELS:Record<AdminPlatformUserRole,string>={customer:'Müşteri',producer:'Satıcı - Üretici',support:'Destek',content_editor:'İçerik Editörü',operations:'Operasyon',admin:'Admin - Yetkili Personel',super_admin:'Super Admin - Uygulama Sahibi'};
function roleLabel(role:AdminPlatformUserRole){return ROLE_LABELS[role];}
function displayName(user:AdminPlatformUser){return user.displayName||user.email||user.id;}
function roleIcon(role:AdminPlatformUserRole){if(role==='super_admin')return Crown;if(role==='admin')return UserCog;if(role==='operations')return Wrench;if(role==='content_editor')return FilePenLine;if(role==='support')return Headphones;if(role==='producer')return Store;return Users;}
export function AdminRoleGovernance(){
 const[users,setUsers]=useState<AdminPlatformUser[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[toast,setToast]=useState(''),[search,setSearch]=useState(''),[reason,setReason]=useState('');
 async function load(){setLoading(true);setError('');try{setUsers(await adminListPlatformUsers());}catch(next){setError(userAdminErrorMessage(next,'Yetki listesi yüklenemedi.'));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 const filtered=useMemo(()=>{const q=search.trim().toLocaleLowerCase('tr-TR');return users.filter(user=>user.status!=='deleted'&&(!q||`${displayName(user)} ${user.email||''} ${user.roles.map(roleLabel).join(' ')}`.toLocaleLowerCase('tr-TR').includes(q)));},[users,search]);
 const counts=useMemo(()=>({superAdmin:users.filter(u=>u.status==='active'&&u.roles.includes('super_admin')).length,admin:users.filter(u=>u.status==='active'&&u.roles.includes('admin')).length,producer:users.filter(u=>u.status==='active'&&u.roles.includes('producer')).length}),[users]);
 async function change(user:AdminPlatformUser,role:AdminPlatformUserRole){const clean=reason.trim();if(clean.length<8){setError('Rol değişikliği için en az 8 karakter gerekçe yazın.');return;}setBusy(user.id);setError('');try{await adminSetPlatformUserRole(user.id,role,clean);setToast(`${displayName(user)} için ana rol ${roleLabel(role)} olarak güncellendi.`);setReason('');await load();window.setTimeout(()=>setToast(''),3500);}catch(next){setError(userAdminErrorMessage(next));}finally{setBusy('');}}
 return<div className="space-y-6">
  <header><h2 className="text-2xl font-bold">Yetki ve Super Admin Yönetimi</h2><p className="mt-1 max-w-4xl text-sm text-gray-500">Canonical rol modeli yedi gerçek rol kullanır. Her hesap temel müşteri rolünü korur; seçilen ana rol sunucu tarafından doğrulanır ve yönetici seviyesindeki değişiklikler ayrıca korunur.</p></header>
  <div className="grid gap-3 lg:grid-cols-3"><Role icon={Crown} title="Super Admin - Sahip" body="Komisyon, kritik silme, hesap yaşam döngüsü, rol yönetimi ve sistem güvenliği."/><Role icon={Shield} title="Admin - Personel" body="Sipariş, iade, ürün moderasyonu, içerik ve günlük yönetim operasyonları."/><Role icon={Store} title="Satıcı - Üretici" body="Kendi ürün, stok, sipariş hazırlama, müşteri soruları ve finans operasyonları."/></div>
  <div className="grid grid-cols-3 gap-3"><Metric label="Super Admin" value={counts.superAdmin}/><Metric label="Admin" value={counts.admin}/><Metric label="Satıcı" value={counts.producer}/></div>
  <div className="rounded-2xl border bg-white p-4 dark:bg-gray-800"><label className="block"><span className="mb-1 block text-sm font-semibold">Rol değişikliği gerekçesi</span><textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={500} rows={3} className="w-full rounded-xl border p-3" placeholder="Örnek: Operasyon sorumluluğu ataması, destek görevi, içerik yetkisi veya görev değişikliği..."/></label><p className="mt-2 text-xs text-gray-500">Kendi yönetici rolünüzü bu ekrandan değiştiremezsiniz. Son aktif Super Admin kaldırılamaz. Yönetici hesapları ve yönetici rollerine atama yalnız Super Admin tarafından yapılır.</p></div>
  {error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{error}</div>:null}{toast?<div role="status" className="rounded-xl bg-green-50 p-4 text-green-800">{toast}</div>:null}
  <div className="flex gap-2"><label className="relative flex-1"><span className="sr-only">Kullanıcı ara</span><Search aria-hidden="true" className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400"/><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="İsim, e-posta veya rol ara..." className="min-h-11 w-full rounded-xl border pl-10 pr-3"/></label><button type="button" onClick={()=>void load()} disabled={loading} className="min-h-11 rounded-xl border px-4"><RefreshCw aria-hidden="true" className={`mr-1 inline h-4 w-4 ${loading?'animate-spin':''}`}/>Yenile</button></div>
  {loading?<div role="status" className="flex min-h-40 items-center justify-center gap-2 rounded-2xl border"><Loader2 aria-hidden="true" className="h-5 w-5 animate-spin"/>Yetkiler yükleniyor...</div>:<section className="space-y-3">{filtered.map(user=><article key={user.id} className="rounded-2xl border bg-white p-4 dark:bg-gray-800"><div className="flex flex-col gap-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><h3 className="font-bold">{displayName(user)}</h3><p className="mt-1 break-all text-sm text-gray-500">{user.email||user.id}</p><p className="mt-1 text-xs font-semibold">Ana rol: {roleLabel(user.primaryRole)}</p><p className="mt-1 text-xs text-gray-500">Aktif roller: {user.roles.map(roleLabel).join(' · ')}</p>{user.producerId?<p className="mt-1 text-xs text-gray-500">Bağlı üretici profili: {user.producerStatus||'Durum doğrulanamadı'}</p>:null}</div><span className="self-start rounded-full bg-gray-100 px-3 py-1 text-xs font-bold dark:bg-gray-700">{user.profileStatus}</span></div><div className="grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-7">{ADMIN_PLATFORM_USER_ROLES.map(role=>{const Icon=roleIcon(role);return<button key={role} type="button" disabled={busy===user.id||role===user.primaryRole||reason.trim().length<8} onClick={()=>void change(user,role)} className={`min-h-11 rounded-xl border px-3 text-xs font-bold disabled:opacity-35 ${role==='super_admin'?'border-amber-300 text-amber-800':''}`}><Icon aria-hidden="true" className="mr-1 inline h-4 w-4"/>{roleLabel(role)}</button>;})}</div></div></article>)}</section>}
 </div>;
}
function Role({icon:Icon,title,body}:{icon:React.ComponentType<{className?:string;'aria-hidden'?:boolean|string}>;title:string;body:string}){return<div className="rounded-2xl border bg-white p-4 dark:bg-gray-800"><Icon aria-hidden="true" className="h-5 w-5 text-brand-green"/><h3 className="mt-2 font-bold">{title}</h3><p className="mt-1 text-sm text-gray-500">{body}</p></div>;}
function Metric({label,value}:{label:string;value:number}){return<div className="rounded-2xl border bg-white p-4 text-center dark:bg-gray-800"><div className="text-2xl font-bold">{value}</div><div className="text-xs text-gray-500">{label}</div></div>;}
