import React,{useEffect,useMemo,useState}from'react';
import{Crown,Loader2,RefreshCw,Search,Shield,Store,UserCog,Users}from'lucide-react';
import{adminListPlatformUsers,adminSetPlatformUserRole,userAdminErrorMessage,type AdminPlatformUser,type AdminPlatformUserRole}from'./userAdminApi';

function roleLabel(role:AdminPlatformUserRole){return role==='super_admin'?'Super Admin - Uygulama Sahibi':role==='admin'?'Admin - Yetkili Personel':role==='vendor'?'Satıcı - Üretici Mağazası':'Müşteri';}
export function AdminRoleGovernance(){
 const[users,setUsers]=useState<AdminPlatformUser[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[toast,setToast]=useState(''),[search,setSearch]=useState(''),[reason,setReason]=useState('');
 async function load(){setLoading(true);setError('');try{setUsers(await adminListPlatformUsers());}catch(next){setError(userAdminErrorMessage(next,'Yetki listesi yüklenemedi.'));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 const filtered=useMemo(()=>{const q=search.trim().toLocaleLowerCase('tr-TR');return users.filter(user=>user.status!=='deleted'&&(!q||`${user.name} ${user.email} ${roleLabel(user.role)}`.toLocaleLowerCase('tr-TR').includes(q)));},[users,search]);
 const counts=useMemo(()=>({superAdmin:users.filter(u=>u.status==='active'&&u.role==='super_admin').length,admin:users.filter(u=>u.status==='active'&&u.role==='admin').length,vendor:users.filter(u=>u.status==='active'&&u.role==='vendor').length}),[users]);
 async function change(user:AdminPlatformUser,role:AdminPlatformUserRole){const clean=reason.trim();if(clean.length<8){setError('Rol değişikliği için en az 8 karakter gerekçe yazın.');return;}setBusy(user.id);setError('');try{await adminSetPlatformUserRole(user.id,role,clean);setToast(`${user.name} için rol ${roleLabel(role)} olarak güncellendi.`);setReason('');await load();window.setTimeout(()=>setToast(''),3500);}catch(next){setError(userAdminErrorMessage(next));}finally{setBusy('');}}
 return<div className="space-y-6">
  <header><h2 className="text-2xl font-bold">Yetki ve Super Admin Yönetimi</h2><p className="mt-1 max-w-4xl text-sm text-gray-500">Rol yapısı nettir: Super Admin uygulamanın sahibi ve en yüksek yetkidir. Admin senin atadığın personeldir. Satıcı ise yalnız kendi mağazasını ve satış operasyonunu yönetir.</p></header>
  <div className="grid gap-3 lg:grid-cols-3"><Role icon={Crown} title="Super Admin - Sahip" body="Komisyon, kritik silme, hesap kapatma/açma, muhasebe dönemi, Super Admin atama, hata günlükleri ve sistem güvenliği."/><Role icon={Shield} title="Admin - Personel" body="Sipariş, iade, ürün moderasyonu, içerik ve günlük operasyon. Sahip seviyesindeki kritik işlemler kapalıdır."/><Role icon={Store} title="Satıcı - Üretici" body="Ürün, stok, sipariş hazırlama, müşteri soruları, etkinlik başvurusu ve kendi finans özeti. Yönetim paneli değildir."/></div>
  <div className="grid grid-cols-3 gap-3"><Metric label="Super Admin" value={counts.superAdmin}/><Metric label="Admin" value={counts.admin}/><Metric label="Satıcı" value={counts.vendor}/></div>
  <div className="rounded-2xl border bg-white p-4 dark:bg-gray-800"><label className="block"><span className="mb-1 block text-sm font-semibold">Rol değişikliği gerekçesi</span><textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000} rows={3} className="w-full rounded-xl border p-3" placeholder="Örnek: Operasyon yöneticisi ataması, yetki devri, görev değişikliği..."/></label><p className="mt-2 text-xs text-gray-500">Sistemdeki son aktif Super Admin kaldırılamaz. Böylece sahip erişimini yanlışlıkla tamamen kaybetmezsiniz.</p></div>
  {error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{error}</div>:null}{toast?<div role="status" className="rounded-xl bg-green-50 p-4 text-green-800">{toast}</div>:null}
  <div className="flex gap-2"><label className="relative flex-1"><span className="sr-only">Kullanıcı ara</span><Search aria-hidden="true" className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400"/><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="İsim, e-posta veya rol ara..." className="min-h-11 w-full rounded-xl border pl-10 pr-3"/></label><button type="button" onClick={()=>void load()} disabled={loading} className="min-h-11 rounded-xl border px-4"><RefreshCw aria-hidden="true" className={`mr-1 inline h-4 w-4 ${loading?'animate-spin':''}`}/>Yenile</button></div>
  {loading?<div role="status" className="flex min-h-40 items-center justify-center gap-2 rounded-2xl border"><Loader2 aria-hidden="true" className="h-5 w-5 animate-spin"/>Yetkiler yükleniyor...</div>:<section className="space-y-3">{filtered.map(user=><article key={user.id} className="rounded-2xl border bg-white p-4 dark:bg-gray-800"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><h3 className="font-bold">{user.name}</h3><p className="mt-1 break-all text-sm text-gray-500">{user.email}</p><p className="mt-1 text-xs font-semibold">Mevcut rol: {roleLabel(user.role)}</p></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{(['user','vendor','admin','super_admin']as AdminPlatformUserRole[]).map(role=><button key={role} type="button" disabled={busy===user.id||role===user.role||reason.trim().length<8} onClick={()=>void change(user,role)} className={`min-h-11 rounded-xl border px-3 text-xs font-bold disabled:opacity-35 ${role==='super_admin'?'border-amber-300 text-amber-800':''}`}>{role==='user'?<Users aria-hidden="true" className="mr-1 inline h-4 w-4"/>:role==='vendor'?<Store aria-hidden="true" className="mr-1 inline h-4 w-4"/>:role==='admin'?<UserCog aria-hidden="true" className="mr-1 inline h-4 w-4"/>:<Crown aria-hidden="true" className="mr-1 inline h-4 w-4"/>}{role==='super_admin'?'Sahip':role==='admin'?'Admin':role==='vendor'?'Satıcı':'Müşteri'}</button>)}</div></div></article>)}</section>}
 </div>;
}
function Role({icon:Icon,title,body}:{icon:React.ComponentType<{className?:string;'aria-hidden'?:boolean|string}>;title:string;body:string}){return<div className="rounded-2xl border bg-white p-4 dark:bg-gray-800"><Icon aria-hidden="true" className="h-5 w-5 text-brand-green"/><h3 className="mt-2 font-bold">{title}</h3><p className="mt-1 text-sm text-gray-500">{body}</p></div>;}
function Metric({label,value}:{label:string;value:number}){return<div className="rounded-2xl border bg-white p-4 text-center dark:bg-gray-800"><div className="text-2xl font-bold">{value}</div><div className="text-xs text-gray-500">{label}</div></div>;}
