import React,{useEffect,useMemo,useState}from'react';
import{AlertTriangle,Archive,Image,Loader2,RefreshCw,Search,ShieldAlert,Trash2,X}from'lucide-react';
import{adminCatalogUrl,adminListProducts,type AdminProduct}from'./productAdminApi';
import{productRemovalErrorMessage,removeDeletedProductImages,superAdminRemoveProduct,type ProductRemovalResult}from'./productRemovalApi';
import{useAccessibleDialog}from'../features/accessibility/useAccessibleDialog';

export function AdminProductRemoval(){
 const[products,setProducts]=useState<AdminProduct[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState(''),[search,setSearch]=useState(''),[target,setTarget]=useState<AdminProduct|null>(null),[reason,setReason]=useState(''),[confirm,setConfirm]=useState('');
 const dialogRef=useAccessibleDialog<HTMLDivElement>(Boolean(target),()=>{if(!busy)close();});
 async function load(silent=false){if(!silent)setLoading(true);setError('');try{setProducts(await adminListProducts());}catch(next){setError(productRemovalErrorMessage(next,'Ürünler yüklenemedi.'));}finally{if(!silent)setLoading(false);}}
 useEffect(()=>{void load();},[]);
 function close(){setTarget(null);setReason('');setConfirm('');setError('');}
 function show(message:string){setToast(message);window.setTimeout(()=>setToast(''),4200);}
 const filtered=useMemo(()=>{const q=search.trim().toLocaleLowerCase('tr-TR');return products.filter(item=>!q||`${item.name} ${item.producer_name} ${item.slug} ${item.category_name||''}`.toLocaleLowerCase('tr-TR').includes(q));},[products,search]);
 async function remove(event:React.FormEvent){event.preventDefault();if(!target||busy)return;if(reason.trim().length<8){setError('Kaldırma gerekçesi en az 8 karakter olmalıdır.');return;}if(confirm!=='KALDIR'){setError('İşlemi doğrulamak için KALDIR yazın.');return;}setBusy(true);setError('');try{const result=await superAdminRemoveProduct(target.id,reason);let storageWarning='';if(result.mode==='permanently_deleted'&&result.imagePaths.length){try{await removeDeletedProductImages(result.imagePaths);}catch{storageWarning=' Ürün veritabanından kaldırıldı fakat bazı eski görsel dosyaları Storage temizleme kuyruğunda ayrıca kontrol edilmelidir.';}}show(removalMessage(result)+storageWarning);close();await load(true);}catch(next){setError(productRemovalErrorMessage(next));}finally{setBusy(false);}}
 return<div className="space-y-6">
  <header><h2 className="text-2xl font-bold">Güvenli Ürün Kaldırma</h2><p className="mt-1 max-w-4xl text-sm text-gray-500">Yalnız Super Admin içindir. Sipariş, yorum, lot veya değişiklik geçmişi bulunan ürün fiziksel olarak silinmez. Mağazadan kaldırılır, geçmiş kayıtları korunur. Hiç geçmişi olmayan ürün kalıcı olarak temizlenebilir.</p></header>
  <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950 dark:border-amber-900/50 dark:bg-amber-950/20 dark:text-amber-100"><ShieldAlert aria-hidden="true" className="mr-2 inline h-5 w-5"/><strong>Güvenlik kuralı:</strong> Bu ekran moderasyon reddi için kullanılmaz. Hatalı ürün önce Ürün Onayları bölümünden gerekçeyle reddedilir. Buradaki kaldırma, kataloğu tamamen kapatma veya kayıt silme işlemidir.</div>
  {error&&!target?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{error}</div>:null}
  <div className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><span className="sr-only">Ürün ara</span><Search aria-hidden="true" className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400"/><input type="search" value={search} onChange={e=>setSearch(e.target.value)} maxLength={160} placeholder="Ürün, üretici veya kategori ara..." className="min-h-11 w-full rounded-xl border bg-white pl-10 pr-4 dark:bg-gray-900"/></label><button type="button" onClick={()=>void load()} disabled={loading} className="min-h-11 rounded-xl border px-4"><RefreshCw aria-hidden="true" className={`mr-2 inline h-4 w-4 ${loading?'animate-spin':''}`}/>Yenile</button></div>
  {loading?<div role="status" className="flex min-h-40 items-center justify-center gap-2 rounded-2xl border"><Loader2 aria-hidden="true" className="h-5 w-5 animate-spin"/>Ürünler yükleniyor...</div>:<section className="space-y-3" aria-label="Kaldırılabilir ürünler">{filtered.map(item=><article key={item.id} className="rounded-2xl border bg-white p-4 dark:bg-gray-800"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3">{item.primary_image_path?<img src={adminCatalogUrl(item.primary_image_path)} alt="" className="h-14 w-14 shrink-0 rounded-xl object-cover"/>:<div className="grid h-14 w-14 shrink-0 place-items-center rounded-xl border"><Image aria-hidden="true" className="h-5 w-5 text-gray-400"/></div>}<div className="min-w-0"><h3 className="truncate font-bold">{item.name}</h3><p className="mt-1 text-sm text-gray-500">{item.producer_name} · {item.category_name||'Kategori yok'}</p><p className="mt-1 text-xs text-gray-500">Durum: {item.status} · {item.review_count} yorum · stok {item.available_quantity}</p></div></div><button type="button" onClick={()=>{setTarget(item);setReason('');setConfirm('');setError('');}} className="min-h-11 rounded-xl border border-red-300 px-4 font-bold text-red-700"><Trash2 aria-hidden="true" className="mr-1 inline h-4 w-4"/>Kaldır</button></div></article>)}{!filtered.length?<div className="rounded-2xl border p-8 text-center text-gray-500">Ürün bulunamadı.</div>:null}</section>}
  {target?<div className="fixed inset-0 z-[70] flex items-end justify-center bg-black/70 sm:items-center sm:p-4"><div ref={dialogRef} role="alertdialog" aria-modal="true" aria-labelledby="remove-product-title" tabIndex={-1} className="w-full max-w-xl rounded-t-3xl bg-white p-5 shadow-2xl outline-none dark:bg-gray-900 sm:rounded-3xl"><div className="flex items-start justify-between gap-3"><div><h3 id="remove-product-title" className="text-xl font-bold">Ürünü sistemden kaldır</h3><p className="mt-1 text-sm text-gray-500">{target.name} · {target.producer_name}</p></div><button type="button" disabled={busy} onClick={close} className="min-h-11 min-w-11 rounded-xl" aria-label="Pencereyi kapat"><X aria-hidden="true" className="mx-auto h-5 w-5"/></button></div><div className="mt-4 rounded-xl bg-gray-50 p-4 text-sm dark:bg-gray-800"><div className="flex gap-2"><Archive aria-hidden="true" className="mt-0.5 h-5 w-5 shrink-0"/><p>Sistem önce geçmiş bağımlılıklarını kontrol eder. Geçmiş varsa ürün sadece katalogdan kalıcı biçimde gizlenir. Geçmiş yoksa ürün kaydı fiziksel olarak silinebilir.</p></div></div><form onSubmit={remove} className="mt-5 space-y-4"><label className="block"><span className="mb-1 block text-sm font-semibold">Kaldırma gerekçesi</span><textarea required minLength={8} maxLength={1000} rows={4} value={reason} onChange={e=>setReason(e.target.value)} className="w-full rounded-xl border p-3" placeholder="Sahte ürün, hukuki talep, tekrar kayıt veya başka açık gerekçe..."/></label><label className="block"><span className="mb-1 block text-sm font-semibold">Onay için KALDIR yazın</span><input value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="off" className="min-h-11 w-full rounded-xl border px-3"/></label>{error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800"><AlertTriangle aria-hidden="true" className="mr-1 inline h-4 w-4"/>{error}</div>:null}<div className="grid grid-cols-2 gap-3"><button type="button" disabled={busy} onClick={close} className="min-h-11 rounded-xl border font-semibold">Vazgeç</button><button type="submit" disabled={busy||confirm!=='KALDIR'||reason.trim().length<8} className="min-h-11 rounded-xl bg-red-700 font-bold text-white disabled:opacity-40">{busy?'Kontrol ediliyor…':'Güvenli kaldır'}</button></div></form></div></div>:null}
  {toast?<div role="status" className="fixed bottom-4 right-4 z-[90] max-w-md rounded-xl bg-gray-950 px-5 py-3 text-white shadow-2xl">{toast}</div>:null}
 </div>;
}
function removalMessage(result:ProductRemovalResult){return result.mode==='permanently_deleted'?'Ürünün geçmiş bağı yoktu. Ürün kalıcı olarak kaldırıldı.':`Ürün mağazadan kaldırıldı. Geçmiş korundu: ${result.orderRefs} sipariş, ${result.reviewRefs} yorum, ${result.batchRefs} lot, ${result.changeRefs} değişiklik kaydı.`;}
