import React,{useEffect,useMemo,useState}from'react';
import{AlertTriangle,CheckCircle2,Clock3,Mail,RefreshCw,RotateCcw,Send,ShieldAlert}from'lucide-react';
import{listTransactionalEmailJobs,retryTransactionalEmailJob,type TransactionalEmailJob,type TransactionalEmailJobStatus}from'./transactionalEmailAdminApi';

const FILTERS:Array<{value:TransactionalEmailJobStatus|null;label:string}>=[{value:null,label:'Tümü'},{value:'pending',label:'Bekleyen'},{value:'processing',label:'İşleniyor'},{value:'failed',label:'Başarısız'},{value:'dead_letter',label:'Müdahale gerekli'},{value:'sent',label:'Gönderildi'}];
const statusLabel:Record<TransactionalEmailJobStatus,string>={pending:'Bekleyen',processing:'İşleniyor',failed:'Başarısız',sent:'Gönderildi',dead_letter:'Müdahale gerekli'};
const kindLabel:Record<TransactionalEmailJob['kind'],string>={order_payment_receipt:'Sipariş ödeme makbuzu',event_payment_receipt:'Etkinlik ödeme makbuzu'};
function date(value:string|null){if(!value)return'-';return new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));}
function StatusIcon({status}:{status:TransactionalEmailJobStatus}){if(status==='sent')return<CheckCircle2 className="h-5 w-5 text-emerald-600" aria-hidden="true"/>;if(status==='failed')return<AlertTriangle className="h-5 w-5 text-amber-600" aria-hidden="true"/>;if(status==='dead_letter')return<ShieldAlert className="h-5 w-5 text-red-600" aria-hidden="true"/>;if(status==='processing')return<Send className="h-5 w-5 text-blue-600" aria-hidden="true"/>;return<Clock3 className="h-5 w-5 text-gray-500" aria-hidden="true"/>;}
export function AdminTransactionalEmails(){
 const[items,setItems]=useState<TransactionalEmailJob[]>([]),[filter,setFilter]=useState<TransactionalEmailJobStatus|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[retryingId,setRetryingId]=useState<number|null>(null),[error,setError]=useState(''),[status,setStatus]=useState('');
 async function load(initial=false){try{initial?setLoading(true):setRefreshing(true);setError('');setItems(await listTransactionalEmailJobs(filter,100));}catch(next){setError(next instanceof Error&&next.message?next.message:'Makbuz e-posta kuyruğu yüklenemedi.');}finally{setLoading(false);setRefreshing(false);}}
 useEffect(()=>{void load(true);},[filter]);
 const counts=useMemo(()=>items.reduce((acc,item)=>{acc[item.status]=(acc[item.status]||0)+1;return acc;},{} as Record<TransactionalEmailJobStatus,number>),[items]);
 async function retry(job:TransactionalEmailJob){if(job.status!=='failed'&&job.status!=='dead_letter')return;try{setRetryingId(job.id);setError('');setStatus('');await retryTransactionalEmailJob(job.id);setStatus('Makbuz e-postası güvenli şekilde yeniden kuyruğa alındı.');await load(false);}catch(next){setError(next instanceof Error&&next.message?next.message:'E-posta işi yeniden kuyruğa alınamadı.');}finally{setRetryingId(null);}}
 if(loading)return<div role="status" className="flex min-h-56 items-center justify-center rounded-2xl border bg-white p-6 dark:bg-gray-800">Makbuz e-posta kuyruğu yükleniyor...</div>;
 return<div className="space-y-5"><header className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-2"><Mail className="h-6 w-6 text-brand-green" aria-hidden="true"/><h2 className="text-2xl font-bold">Makbuz E-posta Kuyruğu</h2></div><p className="mt-2 max-w-3xl text-sm text-gray-500">Ödeme kesinleştikten sonra oluşturulan sipariş ve etkinlik makbuzu e-postalarını izler. E-posta gönderimi ödeme sonucundan bağımsızdır; gönderim sorunu siparişi veya tahsilatı geri almaz.</p></div><button type="button" onClick={()=>void load(false)} disabled={refreshing||retryingId!==null} className="min-h-11 rounded-xl border bg-white px-4 font-semibold disabled:opacity-50 dark:bg-gray-800"><RefreshCw className={`mr-2 inline h-4 w-4 ${refreshing?'animate-spin':''}`} aria-hidden="true"/>Yenile</button></header>
 {error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>:null}{status?<div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{status}</div>:null}
 <section aria-label="E-posta kuyruğu filtreleri" className="flex gap-2 overflow-x-auto pb-1">{FILTERS.map(option=><button key={option.value||'all'} type="button" onClick={()=>setFilter(option.value)} aria-pressed={filter===option.value} className={`min-h-11 shrink-0 rounded-xl border px-4 text-sm font-semibold ${filter===option.value?'bg-brand-green text-brand-on-green':'bg-white dark:bg-gray-800'}`}>{option.label}{option.value&&counts[option.value]!=null?` (${counts[option.value]})`:''}</button>)}</section>
 {items.length===0?<div className="rounded-2xl border bg-white p-8 text-center dark:bg-gray-800"><Mail className="mx-auto h-10 w-10 text-gray-300" aria-hidden="true"/><h3 className="mt-3 font-bold">Bu durumda e-posta işi yok</h3><p className="mt-1 text-sm text-gray-500">Filtreye uyan makbuz e-postası bulunmuyor.</p></div>:<div className="grid gap-4 xl:grid-cols-2">{items.map(item=><article key={item.id} className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-gray-800"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-start gap-3"><StatusIcon status={item.status}/><div className="min-w-0"><h3 className="font-bold">{kindLabel[item.kind]}</h3><p className="mt-1 break-all text-xs text-gray-500">İşlem: {item.aggregateId}</p></div></div><span className="shrink-0 rounded-full bg-gray-100 px-2.5 py-1 text-xs font-bold text-gray-700 dark:bg-gray-700 dark:text-gray-200">{statusLabel[item.status]}</span></div><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-gray-500">Oluşturuldu</dt><dd className="font-semibold">{date(item.createdAt)}</dd></div><div><dt className="text-gray-500">Deneme</dt><dd className="font-semibold">{item.attempts}</dd></div><div><dt className="text-gray-500">Sonraki uygun zaman</dt><dd className="font-semibold">{date(item.availableAt)}</dd></div><div><dt className="text-gray-500">Gönderildi</dt><dd className="font-semibold">{date(item.sentAt)}</dd></div></dl>{item.lastError?<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950"><strong>Son hata:</strong> <span className="break-words">{item.lastError}</span></div>:null}{item.providerMessageId?<p className="mt-3 break-all text-xs text-gray-500">Sağlayıcı ileti kimliği: {item.providerMessageId}</p>:null}{item.status==='failed'||item.status==='dead_letter'?<button type="button" onClick={()=>void retry(item)} disabled={retryingId!==null||refreshing} aria-label={`${kindLabel[item.kind]} e-postasını yeniden kuyruğa al`} className="mt-4 min-h-11 w-full rounded-xl bg-brand-green px-4 font-bold text-brand-on-green disabled:opacity-50"><RotateCcw className={`mr-2 inline h-4 w-4 ${retryingId===item.id?'animate-spin':''}`} aria-hidden="true"/>{retryingId===item.id?'Yeniden kuyruğa alınıyor...':'Yeniden dene'}</button>:null}</article>)}</div>}
 </div>;
}
