import React,{useEffect,useMemo,useState}from'react';
import{AlertTriangle,Bell,Building2,CheckCircle2,CreditCard,FileCheck2,Images,Mail,RefreshCw,Rocket,ShieldCheck,Smartphone,Store,Truck,XCircle}from'lucide-react';
import{getProductionReadiness,type ProductionReadiness}from'./productionReadinessAdminApi';

type Props={setActiveTab?:(tab:string)=>void};
type RowStatus='ready'|'input_required'|'error';
type Row={id:string;label:string;status:RowStatus;detail:string;actionTab?:string;actionLabel?:string;icon:React.ReactNode};
const legalLabels:Record<string,string>={about:'Hakkımızda',returns:'İade ve cayma',privacy:'Gizlilik',terms:'Kullanım şartları'};
const businessMissingLabels:Record<string,string>={registered_legal_name:'kayıtlı ticari unvan',registered_address:'açık ticari/tebligat adresi',registered_country_code:'kayıtlı ülke',registered_identity_verification:'tescilli kimliğin belgeyle doğrulanması',support_email:'destek e-postası',support_phone:'destek telefonu',published_legal_documents:'yayınlanmış yasal belgeler',legal_documents_finalized:'yasal belgelerin nihai onayı'};
function State({status}:{status:RowStatus}){if(status==='ready')return<span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700"><CheckCircle2 className="h-3.5 w-3.5" aria-hidden="true"/>Hazır</span>;if(status==='input_required')return<span className="inline-flex items-center gap-1 rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-800"><AlertTriangle className="h-3.5 w-3.5" aria-hidden="true"/>Girdi gerekli</span>;return<span className="inline-flex items-center gap-1 rounded-full bg-red-50 px-2.5 py-1 text-xs font-bold text-red-700"><XCircle className="h-3.5 w-3.5" aria-hidden="true"/>Sistem hatası</span>;}
function ReadinessRow({row,setActiveTab}:{row:Row;setActiveTab?:Props['setActiveTab']}){const tone=row.status==='ready'?'bg-emerald-50 text-emerald-700':row.status==='input_required'?'bg-amber-50 text-amber-800':'bg-red-50 text-red-700';return<article className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-gray-800"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-start gap-3"><div className={`rounded-xl p-2.5 ${tone}`}>{row.icon}</div><div className="min-w-0"><h3 className="font-bold text-gray-900 dark:text-white">{row.label}</h3><p className="mt-1 text-sm text-gray-500">{row.detail}</p></div></div><State status={row.status}/></div>{row.status!=='ready'&&row.actionTab&&setActiveTab?<button type="button" onClick={()=>setActiveTab(row.actionTab!)} className="mt-4 min-h-11 w-full rounded-xl border px-4 font-semibold hover:bg-gray-50 dark:hover:bg-gray-700">{row.actionLabel||'İlgili bölümü aç'}</button>:null}</article>;}
export function AdminProductionReadiness({setActiveTab}:Props){
 const[data,setData]=useState<ProductionReadiness|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState('');
 async function load(initial=false){try{initial?setLoading(true):setRefreshing(true);setError('');setData(await getProductionReadiness());}catch(next){setError(next instanceof Error&&next.message?next.message:'Üretim hazırlığı denetlenemedi.');}finally{setLoading(false);setRefreshing(false);}}
 useEffect(()=>{void load(true);},[]);
 const rows=useMemo<Row[]>(()=>{if(!data)return[];const d=data.database,r=data.runtime,missingLegal=d.legalContent.missingSlugs.map(slug=>legalLabels[slug]||slug).join(', ');const missingBusiness=d.businessIdentity.missing.map(key=>businessMissingLabels[key]||key).join(', ');const experienceAssetsReady=d.assets.contentObjectCount>0&&d.assets.eventObjectCount>0;const shippingStatus=d.shipping.missingWeightVariantCount>0?'input_required':d.shipping.estimatedWeightVariantCount>0?'input_required':'ready';const shippingDetail=d.shipping.missingWeightVariantCount>0?`${d.shipping.activePublishedVariantCount} aktif varyantın ${d.shipping.missingWeightVariantCount} tanesinde paketli brüt gönderi ağırlığı eksik.`:d.shipping.estimatedWeightVariantCount>0?`${d.shipping.activePublishedVariantCount} aktif varyantın tamamında kargo hesabı için brüt ağırlık var. ${d.shipping.estimatedWeightVariantCount} değer ürün/ambalaj tipine göre tahmini, ${d.shipping.verifiedWeightVariantCount} değer gerçek tartım veya tedarikçi kaynağıyla doğrulanmış. Tahminler kargo hesabını çalıştırır ancak gerçek tartımla güncellenmelidir.`:`${d.shipping.activePublishedVariantCount} aktif varyantın tamamında paketli brüt gönderi ağırlığı fiziksel tartım veya tedarikçi kaynağıyla doğrulanmış.`;return[
  {id:'integrity',label:'Yazılım ve veritabanı bütünlüğü',status:d.integrity.ready?'ready':'error',detail:d.integrity.ready?'Kritik Super Admin bağımlılıkları sağlam. Eksik private/public runtime referansı yok.':`Eksik private referans: ${d.integrity.missingPrivateReferenceCount}, public referans: ${d.integrity.missingPublicReferenceCount}. Super Admin helper: ${d.integrity.superAdminHelperPresent?'var':'yok'}, audit ledger: ${d.integrity.adminAuditLedgerPresent?'var':'yok'}, readiness wrapper: ${d.integrity.readinessWrapperPresent?'var':'yok'}.`,icon:<ShieldCheck className="h-5 w-5" aria-hidden="true"/>},
  {id:'business',label:'Kayıtlı işletme ve yasal kimlik',status:d.businessIdentity.ready?'ready':'input_required',detail:d.businessIdentity.ready?'Kayıtlı ticari unvan, adres, ülke, destek kanalları ve yasal belge finalizasyonu tamam.':`Golden Oremar başlangıç kimliği doldurulmuş durumda. Production için kalan gerçek doğrulama: ${missingBusiness||'işletme kimliği doğrulanamadı'}.`,actionTab:'business-compliance',actionLabel:'İşletme kimliğini aç',icon:<Building2 className="h-5 w-5" aria-hidden="true"/>},
  {id:'catalog',label:'Gerçek ürün görselleri',status:d.assets.catalogReady?'ready':'input_required',detail:`${d.assets.publishedProductCount} yayındaki ürünün ${d.assets.publishedProductsWithRealPrimaryImage} tanesinde doğrulanmış primary Storage görseli var. Gerçek görsel bekleyen: ${d.assets.publishedProductsMissingRealPrimaryImage}.`,actionTab:'products',actionLabel:'Ürünleri aç',icon:<Images className="h-5 w-5" aria-hidden="true"/>},
  {id:'experience-assets',label:'İçerik ve etkinlik görselleri',status:experienceAssetsReady?'ready':'input_required',detail:`content-public: ${d.assets.contentObjectCount} obje, event-public: ${d.assets.eventObjectCount} obje. Yayınlanacak gerçek medya dosyaları gerektiğinde yüklenmeli.`,actionTab:'content',actionLabel:'İçerik kütüphanesini aç',icon:<Images className="h-5 w-5" aria-hidden="true"/>},
  {id:'legal',label:'Yasal içerikler',status:d.legalContent.ready?'ready':'input_required',detail:d.legalContent.ready?'Zorunlu Türkçe yasal belgeler yayınlanmış.':`Yayınlanması gereken belgeler: ${missingLegal||'doğrulanamadı'}.`,actionTab:'business-compliance',actionLabel:'Yasal belgeleri aç',icon:<FileCheck2 className="h-5 w-5" aria-hidden="true"/>},
  {id:'shipping',label:'Paketli kargo ağırlıkları',status:shippingStatus,detail:shippingDetail,actionTab:'shipping-readiness',actionLabel:'Kargo ağırlıklarını aç',icon:<Truck className="h-5 w-5" aria-hidden="true"/>},
  {id:'producer-payments',label:'Üretici iyzico alt-üye hesapları',status:d.producerPayments.ready?'ready':'input_required',detail:`${d.producerPayments.activeVerifiedProducerCount} aktif doğrulanmış üreticiden ${d.producerPayments.readyProducerPaymentAccountCount} tanesi sağlayıcı tarafında tahsilata hazır. Onboarding bekleyen: ${d.producerPayments.missingProducerPaymentAccountCount}.`,actionTab:'vendors',actionLabel:'Satıcıları aç',icon:<Store className="h-5 w-5" aria-hidden="true"/>},
  {id:'payment',label:'Uygulama içi canlı ödeme',status:r.paymentReady?'ready':'input_required',detail:`iyzico production yapılandırması ${r.iyzicoConfigured?'hazır':'girdi bekliyor'}; checkout akışı ${d.paymentControl.atLeastOneCheckoutFlowEnabled?'açık':'production bilgileri tamamlanana kadar kapalı'}.`,actionTab:'payment-controls',actionLabel:'Ödeme altyapısını aç',icon:<CreditCard className="h-5 w-5" aria-hidden="true"/>},
  {id:'email',label:'Ödeme makbuzu e-postası',status:r.transactionalEmailConfigured?'ready':'input_required',detail:r.transactionalEmailConfigured?'Resend ve doğrulanmış gönderici sunucuda hazır.':'Production e-posta anahtarı ve doğrulanmış gönderici girdisi gerekli.',actionTab:'transactional-emails',actionLabel:'Makbuz kuyruğunu aç',icon:<Mail className="h-5 w-5" aria-hidden="true"/>},
  {id:'android-push',label:'Android push bildirimleri',status:r.fcmConfigured?'ready':'input_required',detail:r.fcmConfigured?'FCM service account sunucu yapılandırması hazır.':'Production FCM proje ve service-account bilgileri gerekli.',actionTab:'notifications',actionLabel:'Bildirim merkezini aç',icon:<Bell className="h-5 w-5" aria-hidden="true"/>},
  {id:'ios-push',label:'iOS push bildirimleri',status:r.apnsConfigured?'ready':'input_required',detail:r.apnsConfigured?'APNs production sunucu yapılandırması hazır.':'Production APNs team, key, private key ve bundle bilgileri gerekli.',actionTab:'notifications',actionLabel:'Bildirim merkezini aç',icon:<Smartphone className="h-5 w-5" aria-hidden="true"/>}
 ];},[data]);
 const readyCount=rows.filter(row=>row.status==='ready').length,inputCount=rows.filter(row=>row.status==='input_required').length,errorCount=rows.filter(row=>row.status==='error').length;
 if(loading&&!data)return<div role="status" className="flex min-h-64 items-center justify-center rounded-2xl border bg-white p-6 dark:bg-gray-800">Üretim hazırlığı denetleniyor...</div>;
 const summaryTone=!data?.softwareIntegrityReady?'border-red-200 bg-red-50':data.automatedReady?'border-emerald-200 bg-emerald-50':'border-amber-200 bg-amber-50';
 return<div className="space-y-6"><header className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-2"><Rocket className="h-7 w-7 text-brand-green" aria-hidden="true"/><h2 className="text-2xl font-bold">Üretim Hazırlığı</h2></div><p className="mt-2 max-w-3xl text-sm text-gray-500">Bu ekran gerçek sistem hatalarını üretim için henüz sağlanmamış dış girdilerden ayırır. Kırmızı yalnız yazılım veya veritabanı bütünlüğü bozulduğunda kullanılır. Şirket doğrulaması, gerçek medya, fiziksel ağırlık doğrulaması veya sağlayıcı anahtarı gibi girdiler sarı gösterilir.</p></div><button type="button" onClick={()=>void load(false)} disabled={refreshing} className="min-h-11 rounded-xl border bg-white px-4 font-semibold disabled:opacity-50 dark:bg-gray-800"><RefreshCw className={`mr-2 inline h-4 w-4 ${refreshing?'animate-spin':''}`} aria-hidden="true"/>Yeniden denetle</button></header>
 {error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{error}</div>:null}
 {data?<section className={`rounded-2xl border p-5 ${summaryTone}`} aria-labelledby="automated-readiness-title"><div className="flex items-start gap-3">{!data.softwareIntegrityReady?<XCircle className="mt-0.5 h-6 w-6 text-red-700" aria-hidden="true"/>:data.automatedReady?<ShieldCheck className="mt-0.5 h-6 w-6 text-emerald-700" aria-hidden="true"/>:<AlertTriangle className="mt-0.5 h-6 w-6 text-amber-800" aria-hidden="true"/>}<div><h3 id="automated-readiness-title" className="font-bold">{!data.softwareIntegrityReady?'Yazılım bütünlüğünde hata var':data.automatedReady?'Yazılım ve otomatik üretim girdileri hazır':'Yazılım bütünlüğü hazır, gerçek üretim girdileri bekleniyor'}</h3><p className="mt-1 text-sm">Hazır: {readyCount}. Girdi gerekli: {inputCount}. Sistem hatası: {errorCount}. Son denetim: {new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(data.generatedAt))}.</p><p className="mt-2 text-xs">Sarı maddeler uygulamanın bozuk olduğu anlamına gelmez. Taslak şirket kimliği ve tahmini paket ağırlıkları uygulamanın boş kalmasını önler; gerçek belge veya ölçüm geldiğinde Super Admin üzerinden doğrulanmış değerle değiştirilir.</p></div></div></section>:null}
 <section className="grid gap-4 xl:grid-cols-2">{rows.map(row=><ReadinessRow key={row.id} row={row} setActiveTab={setActiveTab}/>)}</section>
 {data?<section className="rounded-2xl border bg-white p-5 dark:bg-gray-800" aria-labelledby="manual-release-title"><h3 id="manual-release-title" className="font-bold">Manuel release kontrolleri</h3><p className="mt-1 text-sm text-gray-500">Bunlar Supabase sunucusundan güvenilir biçimde doğrulanamaz. Gerçek mağaza veya sağlayıcı ekranlarında kontrol edilmeden tamam kabul edilmez.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{data.manualReleaseChecks.map(item=><div key={item.id} className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-amber-800" aria-hidden="true"/><div><div className="font-semibold">{item.label}</div><div className="mt-1 text-xs text-amber-900">Manuel doğrulama gerekli</div></div></div>)}</div></section>:null}
 </div>;
}
