import { supabase } from '../lib/supabase';

export type BusinessIdentity={legalName:string|null;supportEmail:string|null;supportPhone:string|null;updatedAt:string;};
export type LegalSlug='about'|'returns'|'privacy'|'terms';
export type LegalLocale='tr'|'en'|'de'|'fr'|'ku'|'ar';
export type LegalStatus='draft'|'published';
export type LegalDocument={id:string;slug:LegalSlug;locale:LegalLocale;title:string;summary:string;markdown:string;status:LegalStatus;publishedAt:string|null;updatedAt:string;};
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const SLUGS=new Set<LegalSlug>(['about','returns','privacy','terms']);
const LOCALES=new Set<LegalLocale>(['tr','en','de','fr','ku','ar']);
const STATUSES=new Set<LegalStatus>(['draft','published']);
function rec(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function text(value:unknown,label:string,max:number,nullable=false){if(value==null&&nullable)return null;if(typeof value!=='string')throw new Error(`${label} doğrulanamadı.`);const next=value.trim();if(!next&&nullable)return null;if(next.length>max||/[\u0000-\u001F\u007F]/.test(next))throw new Error(`${label} doğrulanamadı.`);return next;}
function requiredText(value:unknown,label:string,max:number){const next=text(value,label,max,false) as string;if(!next)throw new Error(`${label} doğrulanamadı.`);return next;}
function iso(value:unknown,label:string,nullable=false){if(value==null&&nullable)return null;const next=requiredText(value,label,80);if(Number.isNaN(Date.parse(next)))throw new Error(`${label} doğrulanamadı.`);return next;}
function uuid(value:unknown,label:string){const id=requiredText(value,label,36);if(!UUID_RE.test(id))throw new Error(`${label} doğrulanamadı.`);return id;}
function legalSlug(value:unknown){const slug=requiredText(value,'Belge türü',20) as LegalSlug;if(!SLUGS.has(slug))throw new Error('Yasal belge türü doğrulanamadı.');return slug;}
function legalLocale(value:unknown){const locale=requiredText(value,'Belge dili',8) as LegalLocale;if(!LOCALES.has(locale))throw new Error('Yasal belge dili doğrulanamadı.');return locale;}
function legalStatus(value:unknown){const status=requiredText(value,'Belge durumu',20) as LegalStatus;if(!STATUSES.has(status))throw new Error('Yasal belge durumu doğrulanamadı.');return status;}
function normalizeBusiness(value:unknown):BusinessIdentity{if(!rec(value))throw new Error('İşletme kimliği yanıtı doğrulanamadı.');const email=text(value.supportEmail,'Destek e-postası',254,true) as string|null;if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error('Destek e-postası doğrulanamadı.');return{legalName:text(value.legalName,'Yasal unvan',240,true) as string|null,supportEmail:email,supportPhone:text(value.supportPhone,'Destek telefonu',40,true) as string|null,updatedAt:iso(value.updatedAt,'İşletme bilgisi tarihi') as string};}
function normalizeDocument(value:unknown,index=0):LegalDocument{if(!rec(value))throw new Error(`${index+1}. yasal belge doğrulanamadı.`);return{id:uuid(value.id,'Belge kimliği'),slug:legalSlug(value.slug),locale:legalLocale(value.locale),title:requiredText(value.title,'Belge başlığı',240),summary:text(value.summary,'Belge özeti',2000,false) as string,markdown:text(value.markdown,'Belge metni',200000,false) as string,status:legalStatus(value.status),publishedAt:iso(value.publishedAt,'Yayın tarihi',true) as string|null,updatedAt:iso(value.updatedAt,'Belge güncelleme tarihi') as string};}
export async function getBusinessIdentity(){const{data,error}=await supabase.rpc('super_admin_get_business_identity_v1');if(error)throw error;return normalizeBusiness(data);}
export async function updateBusinessIdentity(input:{legalName:string;supportEmail:string;supportPhone:string}){const legalName=input.legalName.trim(),supportEmail=input.supportEmail.trim().toLowerCase(),supportPhone=input.supportPhone.trim();if(legalName.length<2||legalName.length>240)throw new Error('Resmi işletme unvanı 2 ile 240 karakter arasında olmalıdır.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(supportEmail))throw new Error('Geçerli bir destek e-postası yazın.');const digits=supportPhone.replace(/\D/g,'');if(!/^[+()0-9 .\-]+$/.test(supportPhone)||digits.length<10||digits.length>15)throw new Error('Destek telefonu 10 ile 15 rakam içermelidir.');const{data,error}=await supabase.rpc('super_admin_update_business_identity_v1',{p_legal_name:legalName,p_support_email:supportEmail,p_support_phone:supportPhone});if(error)throw error;return normalizeBusiness(data);}
export async function listLegalDocuments():Promise<LegalDocument[]>{const{data,error}=await supabase.rpc('super_admin_list_legal_documents_v1');if(error)throw error;if(!rec(data)||data.ok!==true||!Array.isArray(data.items))throw new Error('Yasal belge listesi doğrulanamadı.');return data.items.map(normalizeDocument);}
export async function saveLegalDocument(input:{slug:LegalSlug;locale:LegalLocale;title:string;summary:string;markdown:string;status:LegalStatus}){if(!SLUGS.has(input.slug)||!LOCALES.has(input.locale)||!STATUSES.has(input.status))throw new Error('Yasal belge seçimi geçersiz.');const title=input.title.trim(),summary=input.summary.trim(),markdown=input.markdown.trim();if(title.length<2||title.length>240)throw new Error('Belge başlığı 2 ile 240 karakter arasında olmalıdır.');if(summary.length>2000||markdown.length>200000)throw new Error('Yasal belge metni izin verilen sınırı aşıyor.');if(input.status==='published'&&markdown.length<100)throw new Error('Yasal belge yayınlanmadan önce en az 100 karakter gerçek içerik girilmelidir.');const{data,error}=await supabase.rpc('super_admin_upsert_legal_document_v1',{p_slug:input.slug,p_locale:input.locale,p_title:title,p_summary:summary,p_markdown:markdown,p_status:input.status});if(error)throw error;const result=normalizeDocument(data);if(result.slug!==input.slug||result.locale!==input.locale||result.status!==input.status)throw new Error('Yasal belge kayıt sonucu istekle eşleşmiyor.');return result;}
export function businessComplianceErrorMessage(error:unknown,fallback='İşletme/yasal işlem tamamlanamadı.'){const raw=error instanceof Error?error.message:String((error as{message?:unknown})?.message||'');const map:Array<[string,string]>=[['super_admin_required','Bu bölümü yalnız Super Admin yönetebilir.'],['invalid_legal_name','Resmi işletme unvanını kontrol edin.'],['invalid_support_email','Destek e-postasını kontrol edin.'],['invalid_support_phone','Destek telefonunu kontrol edin.'],['legal_document_too_short_to_publish','Belge yayınlanmadan önce en az 100 karakter gerçek içerik yazılmalıdır.'],['invalid_legal_slug','Yasal belge türü geçersiz.'],['invalid_legal_locale','Yasal belge dili geçersiz.']];for(const[key,message]of map)if(raw.includes(key))return message;return raw&&raw.length<=320?raw:fallback;}
