import { supabase } from '../lib/supabase';

export type CheckoutLegalReadiness={ready:boolean;missing:string[];registeredLegalName:string|null;registeredAddress:string|null;countryCode:string|null;legalDocumentsFinalized:boolean;publishedLegalDocumentCount:number;};
export type BusinessIdentity={brandLegalName:string|null;registeredLegalName:string|null;registeredAddress:string|null;taxOffice:string|null;taxNumber:string|null;mersisNumber:string|null;tradeRegistryNumber:string|null;countryCode:string|null;legalDocumentsFinalized:boolean;supportEmail:string|null;supportPhone:string|null;checkoutLegalReadiness:CheckoutLegalReadiness;updatedAt:string;};
export type LegalSlug='about'|'returns'|'privacy'|'terms';
export type LegalLocale='tr'|'en'|'de'|'fr'|'ku'|'ar';
export type LegalStatus='draft'|'published';
export type LegalDocument={id:string;slug:LegalSlug;locale:LegalLocale;title:string;summary:string;markdown:string;status:LegalStatus;publishedAt:string|null;updatedAt:string;};
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const SLUGS=new Set<LegalSlug>(['about','returns','privacy','terms']);
const LOCALES=new Set<LegalLocale>(['tr','en','de','fr','ku','ar']);
const STATUSES=new Set<LegalStatus>(['draft','published']);
function rec(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function text(value:unknown,label:string,max:number,nullable=false){if(value==null&&nullable)return null;if(typeof value!=='string')throw new Error(`${label} doğrulanamadı.`);const next=value.trim();if(!next&&nullable)return null;if(next.length>max||/[\u0000-\u001F\u007F]/.test(next))throw new Error(`${label} doğrulanamadı.`);return next;}
function requiredText(value:unknown,label:string,max:number){const next=text(value,label,max,false) as string;if(!next)throw new Error(`${label} doğrulanamadı.`);return next;}
function iso(value:unknown,label:string,nullable=false){if(value==null&&nullable)return null;const next=requiredText(value,label,80);if(Number.isNaN(Date.parse(next)))throw new Error(`${label} doğrulanamadı.`);return next;}
function uuid(value:unknown,label:string){const id=requiredText(value,label,36);if(!UUID_RE.test(id))throw new Error(`${label} doğrulanamadı.`);return id;}
function bool(value:unknown,label:string){if(typeof value!=='boolean')throw new Error(`${label} doğrulanamadı.`);return value;}
function integer(value:unknown,label:string,min=0,max=1000000){if(typeof value!=='number'||!Number.isSafeInteger(value)||value<min||value>max)throw new Error(`${label} doğrulanamadı.`);return value;}
function optionalCountry(value:unknown){const next=text(value,'Kayıtlı ülke kodu',2,true) as string|null;if(!next)return null;const upper=next.toUpperCase();if(!/^[A-Z]{2}$/.test(upper))throw new Error('Kayıtlı ülke kodu doğrulanamadı.');return upper;}
function legalSlug(value:unknown){const slug=requiredText(value,'Belge türü',20) as LegalSlug;if(!SLUGS.has(slug))throw new Error('Yasal belge türü doğrulanamadı.');return slug;}
function legalLocale(value:unknown){const locale=requiredText(value,'Belge dili',8) as LegalLocale;if(!LOCALES.has(locale))throw new Error('Yasal belge dili doğrulanamadı.');return locale;}
function legalStatus(value:unknown){const status=requiredText(value,'Belge durumu',20) as LegalStatus;if(!STATUSES.has(status))throw new Error('Yasal belge durumu doğrulanamadı.');return status;}
function normalizeReadiness(value:unknown):CheckoutLegalReadiness{if(!rec(value)||!Array.isArray(value.missing))throw new Error('Checkout yasal hazırlık durumu doğrulanamadı.');const missing=value.missing.map((item,index)=>requiredText(item,`${index+1}. eksik yasal alan`,120));return{ready:bool(value.ready,'Checkout yasal hazırlık durumu'),missing,registeredLegalName:text(value.registeredLegalName,'Tescilli unvan',240,true) as string|null,registeredAddress:text(value.registeredAddress,'Tescilli adres',1000,true) as string|null,countryCode:optionalCountry(value.countryCode),legalDocumentsFinalized:bool(value.legalDocumentsFinalized,'Yasal metin son onayı'),publishedLegalDocumentCount:integer(value.publishedLegalDocumentCount,'Yayınlanmış yasal belge sayısı',0,20)};}
function normalizeBusiness(value:unknown):BusinessIdentity{if(!rec(value))throw new Error('İşletme kimliği yanıtı doğrulanamadı.');const email=text(value.supportEmail,'Destek e-postası',254,true) as string|null;if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error('Destek e-postası doğrulanamadı.');return{brandLegalName:text(value.brandLegalName,'Marka işletme adı',240,true) as string|null,registeredLegalName:text(value.registeredLegalName,'Tescilli ticari unvan',240,true) as string|null,registeredAddress:text(value.registeredAddress,'Tescilli adres',1000,true) as string|null,taxOffice:text(value.taxOffice,'Vergi dairesi',160,true) as string|null,taxNumber:text(value.taxNumber,'Vergi numarası',11,true) as string|null,mersisNumber:text(value.mersisNumber,'MERSİS numarası',16,true) as string|null,tradeRegistryNumber:text(value.tradeRegistryNumber,'Ticaret sicil numarası',120,true) as string|null,countryCode:optionalCountry(value.countryCode),legalDocumentsFinalized:bool(value.legalDocumentsFinalized,'Yasal metin son onayı'),supportEmail:email,supportPhone:text(value.supportPhone,'Destek telefonu',40,true) as string|null,checkoutLegalReadiness:normalizeReadiness(value.checkoutLegalReadiness),updatedAt:iso(value.updatedAt,'İşletme bilgisi tarihi') as string};}
function normalizeDocument(value:unknown,index=0):LegalDocument{if(!rec(value))throw new Error(`${index+1}. yasal belge doğrulanamadı.`);return{id:uuid(value.id,'Belge kimliği'),slug:legalSlug(value.slug),locale:legalLocale(value.locale),title:requiredText(value.title,'Belge başlığı',240),summary:text(value.summary,'Belge özeti',2000,false) as string,markdown:text(value.markdown,'Belge metni',200000,false) as string,status:legalStatus(value.status),publishedAt:iso(value.publishedAt,'Yayın tarihi',true) as string|null,updatedAt:iso(value.updatedAt,'Belge güncelleme tarihi') as string};}
export async function getBusinessIdentity(){const{data,error}=await supabase.rpc('super_admin_get_business_identity_v2');if(error)throw error;return normalizeBusiness(data);}
export async function updateBusinessIdentity(input:{registeredLegalName:string;registeredAddress:string;taxOffice:string;taxNumber:string;mersisNumber:string;tradeRegistryNumber:string;countryCode:string;supportEmail:string;supportPhone:string;legalDocumentsFinalized:boolean}){const registeredLegalName=input.registeredLegalName.trim(),registeredAddress=input.registeredAddress.trim(),taxOffice=input.taxOffice.trim(),taxNumber=input.taxNumber.replace(/\D/g,''),mersisNumber=input.mersisNumber.replace(/\D/g,''),tradeRegistryNumber=input.tradeRegistryNumber.trim(),countryCode=input.countryCode.trim().toUpperCase(),supportEmail=input.supportEmail.trim().toLowerCase(),supportPhone=input.supportPhone.trim();if(registeredLegalName&&registeredLegalName.length<2)throw new Error('Tescilli ticari unvan en az 2 karakter olmalıdır.');if(registeredLegalName.length>240)throw new Error('Tescilli ticari unvan en fazla 240 karakter olabilir.');if(registeredAddress&&registeredAddress.length<10)throw new Error('Tescilli açık adres en az 10 karakter olmalıdır.');if(registeredAddress.length>1000)throw new Error('Tescilli açık adres en fazla 1000 karakter olabilir.');if(taxOffice.length>160)throw new Error('Vergi dairesi en fazla 160 karakter olabilir.');if(taxNumber&&![10,11].includes(taxNumber.length))throw new Error('Vergi numarası 10 veya 11 rakam olmalıdır.');if(mersisNumber&&mersisNumber.length!==16)throw new Error('MERSİS numarası 16 rakam olmalıdır.');if(tradeRegistryNumber.length>120)throw new Error('Ticaret sicil numarası en fazla 120 karakter olabilir.');if(countryCode&&!/^[A-Z]{2}$/.test(countryCode))throw new Error('Kayıtlı ülke kodu iki harfli ISO kodu olmalıdır.');if(input.legalDocumentsFinalized&&(!registeredLegalName||!registeredAddress||!countryCode))throw new Error('Yasal metinleri sonlandırmadan önce tescilli unvan, açık adres ve ülke kodunu girin.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(supportEmail))throw new Error('Geçerli bir destek e-postası yazın.');const digits=supportPhone.replace(/\D/g,'');if(!/^[+()0-9 .\-]+$/.test(supportPhone)||digits.length<10||digits.length>15)throw new Error('Destek telefonu 10 ile 15 rakam içermelidir.');const{data,error}=await supabase.rpc('super_admin_update_business_identity_v2',{p_registered_legal_name:registeredLegalName||null,p_registered_address:registeredAddress||null,p_tax_office:taxOffice||null,p_tax_number:taxNumber||null,p_mersis_number:mersisNumber||null,p_trade_registry_number:tradeRegistryNumber||null,p_country_code:countryCode||null,p_support_email:supportEmail,p_support_phone:supportPhone,p_legal_documents_finalized:input.legalDocumentsFinalized});if(error)throw error;return normalizeBusiness(data);}
export async function listLegalDocuments():Promise<LegalDocument[]>{const{data,error}=await supabase.rpc('super_admin_list_legal_documents_v1');if(error)throw error;if(!rec(data)||data.ok!==true||!Array.isArray(data.items))throw new Error('Yasal belge listesi doğrulanamadı.');return data.items.map(normalizeDocument);}
export async function saveLegalDocument(input:{slug:LegalSlug;locale:LegalLocale;title:string;summary:string;markdown:string;status:LegalStatus}){if(!SLUGS.has(input.slug)||!LOCALES.has(input.locale)||!STATUSES.has(input.status))throw new Error('Yasal belge seçimi geçersiz.');const title=input.title.trim(),summary=input.summary.trim(),markdown=input.markdown.trim();if(title.length<2||title.length>240)throw new Error('Belge başlığı 2 ile 240 karakter arasında olmalıdır.');if(summary.length>2000||markdown.length>200000)throw new Error('Yasal belge metni izin verilen sınırı aşıyor.');if(input.status==='published'&&markdown.length<100)throw new Error('Yasal belge yayınlanmadan önce en az 100 karakter gerçek içerik girilmelidir.');const{data,error}=await supabase.rpc('super_admin_upsert_legal_document_v1',{p_slug:input.slug,p_locale:input.locale,p_title:title,p_summary:summary,p_markdown:markdown,p_status:input.status});if(error)throw error;const result=normalizeDocument(data);if(result.slug!==input.slug||result.locale!==input.locale||result.status!==input.status)throw new Error('Yasal belge kayıt sonucu istekle eşleşmiyor.');return result;}
export function businessComplianceErrorMessage(error:unknown,fallback='İşletme/yasal işlem tamamlanamadı.'){const raw=error instanceof Error?error.message:String((error as{message?:unknown})?.message||'');const map:Array<[string,string]>=[['super_admin_required','Bu bölümü yalnız Super Admin yönetebilir.'],['invalid_registered_legal_name','Tescilli ticari unvanı kontrol edin.'],['invalid_registered_address','Tescilli açık adresi kontrol edin.'],['invalid_tax_office','Vergi dairesini kontrol edin.'],['invalid_tax_number','Vergi numarasını kontrol edin.'],['invalid_mersis_number','MERSİS numarasını kontrol edin.'],['invalid_trade_registry_number','Ticaret sicil numarasını kontrol edin.'],['invalid_registered_country_code','Kayıtlı ülke kodunu kontrol edin.'],['registered_identity_required_before_legal_finalization','Yasal metinlerin son onayından önce tescilli unvan, açık adres ve ülke kodu gereklidir.'],['commercial_legal_readiness_required','Ticari checkout için tescilli işletme kimliği ve yasal metin son onayı tamamlanmalıdır.'],['invalid_support_email','Destek e-postasını kontrol edin.'],['invalid_support_phone','Destek telefonunu kontrol edin.'],['legal_document_too_short_to_publish','Belge yayınlanmadan önce en az 100 karakter gerçek içerik yazılmalıdır.'],['invalid_legal_slug','Yasal belge türü geçersiz.'],['invalid_legal_locale','Yasal belge dili geçersiz.']];for(const[key,message]of map)if(raw.includes(key))return message;return raw&&raw.length<=320?raw:fallback;}
