import{adminGetBrandConfiguration}from'./contentAdminApi';
import{supabase}from'../lib/supabase';

export type EventSpotlightPlacement='after_hero'|'after_categories'|'before_products';
export type EventSpotlightSettings={enabled:boolean;title:string;subtitle:string;maxItems:number;featuredEventReference:string|null;showCountdown:boolean;showCapacity:boolean;showShare:boolean;showAllLink:boolean;placement:EventSpotlightPlacement;updatedAt?:string};
const PLACEMENTS=new Set<EventSpotlightPlacement>(['after_hero','after_categories','before_products']);
function isRecord(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function bool(value:unknown,label:string){if(typeof value!=='boolean')throw new Error(`${label} doğrulanamadı.`);return value;}
function text(value:unknown,label:string,max:number,required=true){if(typeof value!=='string')throw new Error(`${label} doğrulanamadı.`);const normalized=value.trim();if((required&&!normalized)||normalized.length>max||/[\u0000-\u001F\u007F]/.test(normalized))throw new Error(`${label} doğrulanamadı.`);return normalized;}
function normalize(value:unknown):EventSpotlightSettings{if(!isRecord(value))throw new Error('Etkinlik vitrini ayarları doğrulanamadı.');const maxItems=Number(value.maxItems);if(!Number.isSafeInteger(maxItems)||maxItems<1||maxItems>6)throw new Error('Etkinlik vitrini kart sayısı doğrulanamadı.');const placement=text(value.placement,'Etkinlik vitrini konumu',40)as EventSpotlightPlacement;if(!PLACEMENTS.has(placement))throw new Error('Etkinlik vitrini konumu doğrulanamadı.');const featured=value.featuredEventReference==null||value.featuredEventReference===''?null:text(value.featuredEventReference,'Öne çıkan etkinlik referansı',220);const updated=value.updatedAt==null?undefined:text(value.updatedAt,'Etkinlik vitrini güncelleme zamanı',80);if(updated&&Number.isNaN(Date.parse(updated)))throw new Error('Etkinlik vitrini güncelleme zamanı doğrulanamadı.');return{enabled:bool(value.enabled,'Etkinlik vitrini görünürlüğü'),title:text(value.title,'Etkinlik vitrini başlığı',120),subtitle:text(value.subtitle,'Etkinlik vitrini açıklaması',300,false),maxItems,featuredEventReference:featured,showCountdown:bool(value.showCountdown,'Geri sayım ayarı'),showCapacity:bool(value.showCapacity,'Kontenjan ayarı'),showShare:bool(value.showShare,'Paylaşım ayarı'),showAllLink:bool(value.showAllLink,'Tüm etkinlikler bağlantısı'),placement,updatedAt:updated};}
export async function adminGetEventSpotlight():Promise<EventSpotlightSettings>{const config=await adminGetBrandConfiguration();return normalize(config.publicConfig.eventSpotlight);}
export async function adminUpdateEventSpotlight(input:EventSpotlightSettings):Promise<EventSpotlightSettings>{const payload=normalize(input);const{updatedAt:_,...body}=payload;const{data,error}=await supabase.rpc('admin_update_event_spotlight_v1',{p_payload:body});if(error)throw error;return normalize(data);}
export function eventSpotlightError(error:unknown){const message=String((error as{message?:unknown}|null)?.message||'').trim();if(message.includes('super_admin_required'))return'Bu ayar yalnız Super Admin tarafından değiştirilebilir.';if(message.includes('featured_event_not_found'))return'Öne çıkarılacak etkinlik artık bulunamadı. Etkinlik listesini yenileyin.';if(message.includes('invalid_event_spotlight'))return'Etkinlik vitrini ayarlarından biri geçersiz.';if(message.includes('unsupported_event_spotlight_setting'))return'Desteklenmeyen etkinlik vitrini ayarı gönderildi.';return message&&message.length<=260?message:'Etkinlik vitrini ayarları kaydedilemedi.';}
