import { supabase } from '../lib/supabase';

export type OfficialSourceMode='platform_village_catalog'|'platform_direct'|'village_partner';
export type OrganicClaim='producer_declared_organic'|'certification_in_progress'|'certified_organic'|'not_claimed';
export type OfficialStoreProduct={
 id:string;databaseId:string;name:string;description:string;story:string;category:string;categoryId:string;price:number;originalPrice:number;stock:number;image:string;gallery:string[];unit:string;weight:number|null;isApproved:boolean;isActive:boolean;status:string;storeKind:string;
 provenance:{sellerModel:string;sourceMode:OfficialSourceMode;sourceDisplayName:string;sourceCountryCode:string;sourceProvince:string;sourceDistrict:string;sourceVillage:string;sourceLocality:string;originLabel:string;originVerified:boolean;organicClaim:OrganicClaim}|null;
};
export type OfficialStoreCategory={id:string;databaseId:string;name:string;active:boolean;sortOrder:number};

const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const SOURCE_MODES=new Set<OfficialSourceMode>(['platform_village_catalog','platform_direct','village_partner']);
const ORGANIC_CLAIMS=new Set<OrganicClaim>(['producer_declared_organic','certification_in_progress','certified_organic','not_claimed']);
function unwrap<T>(data:T|null,error:unknown):T{if(error)throw error;return data as T;}
function record(value:unknown):value is Record<string,any>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function text(value:unknown,label:string,max:number,required=true){const normalized=typeof value==='string'?value.trim():'';if((required&&!normalized)||normalized.length>max||/[\u0000-\u001F\u007F]/.test(normalized))throw new Error(`${label} doğrulanamadı.`);return normalized;}
function safeNumber(value:unknown,label:string,min=0,max=1_000_000_000){if(typeof value!=='number'||!Number.isFinite(value)||value<min||value>max)throw new Error(`${label} doğrulanamadı.`);return value;}
function integer(value:unknown,label:string,min=0,max=1_000_000_000){if(typeof value!=='number'||!Number.isSafeInteger(value)||value<min||value>max)throw new Error(`${label} doğrulanamadı.`);return value;}
function bool(value:unknown,label:string){if(typeof value!=='boolean')throw new Error(`${label} doğrulanamadı.`);return value;}
function path(value:unknown){if(value==null||value==='')return'';const raw=text(value,'Görsel yolu',1200);if(/^[a-z][a-z0-9+.-]*:/i.test(raw)||raw.startsWith('/')||raw.split('/').some(part=>!part||part==='.'||part==='..'))throw new Error('Görsel yolu doğrulanamadı.');return raw;}
function provenance(value:unknown){if(value==null)return null;if(!record(value))throw new Error('Ürün kaynak bilgisi doğrulanamadı.');const sourceMode=text(value.sourceMode,'Kaynak tipi',40) as OfficialSourceMode;if(!SOURCE_MODES.has(sourceMode))throw new Error('Kaynak tipi doğrulanamadı.');const organicClaim=text(value.organicClaim,'Organik beyanı',60) as OrganicClaim;if(!ORGANIC_CLAIMS.has(organicClaim))throw new Error('Organik beyanı doğrulanamadı.');return{sellerModel:text(value.sellerModel,'Satıcı modeli',60),sourceMode,sourceDisplayName:text(value.sourceDisplayName,'Kaynak adı',180),sourceCountryCode:text(value.sourceCountryCode,'Kaynak ülke kodu',2),sourceProvince:text(value.sourceProvince,'Kaynak il',120),sourceDistrict:text(value.sourceDistrict,'Kaynak ilçe',120),sourceVillage:text(value.sourceVillage,'Kaynak köy',120),sourceLocality:text(value.sourceLocality,'Kaynak yerel detay',160,false),originLabel:text(value.originLabel,'Menşe etiketi',500),originVerified:bool(value.originVerified,'Menşe doğrulaması'),organicClaim};}
function normalizeProduct(value:unknown,index:number):OfficialStoreProduct{if(!record(value))throw new Error(`${index+1}. resmi mağaza ürünü doğrulanamadı.`);if(value.storeKind!=='official')throw new Error(`${index+1}. ürün resmi mağazaya ait değil.`);const gallery=Array.isArray(value.gallery)?value.gallery.map(path):[];return{id:text(value.id,'Ürün referansı',160),databaseId:text(value.databaseId,'Ürün kimliği',160),name:text(value.name,'Ürün adı',300),description:text(value.description,'Açıklama',20000,false),story:text(value.story,'Hikâye',20000,false),category:text(value.category,'Kategori adı',240),categoryId:text(value.categoryId,'Kategori kimliği',220),price:safeNumber(value.price,'Fiyat'),originalPrice:safeNumber(value.originalPrice,'Karşılaştırma fiyatı'),stock:integer(value.stock,'Stok'),image:path(value.image),gallery,unit:text(value.unit,'Birim',120),weight:value.weight==null?null:safeNumber(value.weight,'Ağırlık',0.001,10000),isApproved:bool(value.is_approved,'Yayın durumu'),isActive:bool(value.is_active,'Aktiflik'),status:text(value.status,'Ürün durumu',40),storeKind:'official',provenance:provenance(value.provenance)};}
function normalizeCategory(value:unknown,index:number):OfficialStoreCategory{if(!record(value))throw new Error(`${index+1}. kategori doğrulanamadı.`);return{id:text(value.id,'Kategori bağlantısı',220),databaseId:text(value.databaseId,'Kategori kimliği',160),name:text(value.name,'Kategori adı',240),active:bool(value.is_active,'Kategori aktiflik durumu'),sortOrder:integer(value.sortOrder,'Kategori sırası',0,100000)};}

export async function loadOfficialStoreProductManager(){const{data,error}=await supabase.rpc('management_catalog_snapshot_v1');const raw=unwrap<unknown>(data,error);if(!record(raw)||raw.role!=='admin'||!Array.isArray(raw.products)||!Array.isArray(raw.categories)||!Array.isArray(raw.stores))throw new Error('Resmi mağaza yönetim paketi doğrulanamadı.');const stores=raw.stores.filter((store:any)=>record(store)&&store.storeKind==='official');if(stores.length!==1)throw new Error('Golden Oremar resmi mağaza kaydı tekil olarak doğrulanamadı.');const officialId=text(stores[0].id,'Resmi mağaza kimliği',160);if(!UUID_RE.test(officialId))throw new Error('Resmi mağaza kimliği doğrulanamadı.');const products=raw.products.filter((row:any)=>record(row)&&row.storeKind==='official').map(normalizeProduct);const categories=raw.categories.map(normalizeCategory).filter(row=>row.active).sort((a,b)=>a.sortOrder-b.sortOrder||a.name.localeCompare(b.name,'tr'));return{officialStore:{id:officialId,name:text(stores[0].name,'Resmi mağaza adı',240),location:record(stores[0].location)?stores[0].location:null},products,categories};}

export async function saveOfficialStoreProduct(input:{reference:string|null;name:string;description:string;story:string;categoryId:string;price:number;originalPrice:number;stock:number;weight:number;unit:string;gallery:string[];active:boolean;publish:boolean;sourceMode:OfficialSourceMode;sourceDisplayName:string;sourceProvince:string;sourceDistrict:string;sourceVillage:string;sourceLocality:string;originVerified:boolean;organicClaim:OrganicClaim}){
 const name=text(input.name,'Ürün adı',180);const description=text(input.description,'Ürün açıklaması',20000);const story=text(input.story,'Ürün hikâyesi',20000);if(description.length<20)throw new Error('Ürün açıklaması en az 20 karakter olmalıdır.');if(story.length<20)throw new Error('Ürün hikâyesi en az 20 karakter olmalıdır.');const categoryId=text(input.categoryId,'Kategori',220);const unit=text(input.unit,'Satış birimi',80);if(!Number.isFinite(input.price)||input.price<=0||input.price>1_000_000)throw new Error('Ürün fiyatı geçersiz.');if(!Number.isFinite(input.originalPrice)||input.originalPrice<input.price||input.originalPrice>1_000_000)throw new Error('Karşılaştırma fiyatı ürün fiyatından düşük olamaz.');if(!Number.isSafeInteger(input.stock)||input.stock<0||input.stock>100_000_000)throw new Error('Stok miktarı geçersiz.');if(!Number.isFinite(input.weight)||input.weight<=0||input.weight>10000)throw new Error('Kargo ağırlığı kilogram olarak sıfırdan büyük olmalıdır.');if(!SOURCE_MODES.has(input.sourceMode))throw new Error('Kaynak tipi geçersiz.');if(!ORGANIC_CLAIMS.has(input.organicClaim))throw new Error('Organik beyanı geçersiz.');const sourceDisplayName=text(input.sourceDisplayName,'Kaynak üretici/mağaza adı',180);const sourceProvince=text(input.sourceProvince,'Kaynak il',120);const sourceDistrict=text(input.sourceDistrict,'Kaynak ilçe',120);const sourceVillage=text(input.sourceVillage,'Kaynak köy',120);const sourceLocality=text(input.sourceLocality,'Kaynak yerel detay',160,false);if(input.sourceMode==='village_partner'&&!sourceDisplayName)throw new Error('Köylü/üretici kaynak adı zorunludur.');const gallery=[...new Set(input.gallery.map(path).filter(Boolean))].slice(0,10);if(input.publish&&!gallery.length)throw new Error('Ürünü yayınlamak için en az bir gerçek Storage görseli gerekir.');const payload={name,description,story,categoryId,price:input.price,originalPrice:input.originalPrice,stock:input.stock,weight:input.weight,unit,gallery,image:gallery[0]||'',is_active:input.active,is_approved:input.publish,sourceMode:input.sourceMode,sourceDisplayName,sourceCountryCode:'TR',sourceProvince,sourceDistrict,sourceVillage,sourceLocality,originVerified:input.originVerified,organicClaim:input.organicClaim};const{data,error}=await supabase.rpc('management_upsert_product_v1',{p_reference:input.reference?.trim()||null,p_payload:payload});const result=unwrap<unknown>(data,error);if(!record(result)||!result.databaseId||!result.status)throw new Error('Ürün kayıt sonucu doğrulanamadı.');return result;}

const IMAGE_TYPES=new Set(['image/jpeg','image/png','image/webp','image/avif']);
function ext(type:string){return type==='image/jpeg'?'jpg':type==='image/png'?'png':type==='image/avif'?'avif':'webp';}
export async function uploadOfficialProductImages(files:File[]){if(!Array.isArray(files)||files.length<1||files.length>10)throw new Error('Bir seferde 1 ile 10 görsel yükleyebilirsiniz.');const{data:userData,error:userError}=await supabase.auth.getUser();if(userError)throw userError;const userId=userData.user?.id;if(!userId||!UUID_RE.test(userId))throw new Error('Super Admin oturumu doğrulanamadı.');const uploaded:string[]=[];try{for(const file of files){if(!(file instanceof File)||!IMAGE_TYPES.has(file.type))throw new Error('Ürün görselleri JPEG, PNG, WebP veya AVIF olmalıdır.');if(file.size<=0||file.size>10*1024*1024)throw new Error('Her ürün görseli en fazla 10 MB olabilir.');const storagePath=`admin/${userId}/official-products/${crypto.randomUUID()}.${ext(file.type)}`;const{error}=await supabase.storage.from('catalog-public').upload(storagePath,file,{contentType:file.type,upsert:false,cacheControl:'31536000'});if(error)throw error;uploaded.push(storagePath);}return uploaded;}catch(error){if(uploaded.length)await supabase.storage.from('catalog-public').remove(uploaded).catch(()=>undefined);throw error;}}
export async function removeOfficialProductImages(paths:string[]){const normalized=paths.map(path).filter(Boolean);if(!normalized.length)return;if(normalized.length>10)throw new Error('Silinecek görsel sayısı doğrulanamadı.');const{error}=await supabase.storage.from('catalog-public').remove(normalized);if(error)throw error;}
export function officialProductAssetUrl(storagePath:string){const normalized=path(storagePath);return normalized?supabase.storage.from('catalog-public').getPublicUrl(normalized).data.publicUrl:'';}
export function officialProductError(error:unknown,fallback='Resmi mağaza ürün işlemi tamamlanamadı.'){const message=String((error as any)?.message||'').trim();if(!message)return fallback;const map:Array<[string,string]>=[['official_store_not_ready','Golden Oremar resmi mağazası satışa hazır değil.'],['stored_primary_product_image_required','Yayın için gerçek Storage ana görseli zorunludur.'],['active_priced_variant_required','Yayın için aktif ve pozitif fiyatlı ürün seçeneği gerekir.'],['verified_product_origin_required','Ürünün menşei doğrulanmadan yayınlanamaz.'],['valid_product_organic_certificate_required','Sertifikalı organik seçeneği için geçerli ürün sertifikası yüklenmelidir.'],['product_content_incomplete','Ürün açıklaması ve hikâyesi yayın için yetersiz.'],['existing_product_seller_cannot_be_changed','Yayındaki ürünün mağaza sahibi bu ekrandan değiştirilemez.'],['complete_product_source_location_required','Ürünün il, ilçe ve köy kaynak bilgileri eksiksiz olmalıdır.']];for(const[key,value]of map)if(message.includes(key))return value;return message.length<=300?message:fallback;}
