import{ supabase }from'../lib/supabase';

export type AdminProductCertification={id:string;certificateType:string;issuer:string;certificateNumber:string;issuedAt:string;expiresAt:string|null;status:'valid'|'revoked'|'expired';documentPath:string;reviewedAt:string;reviewNote:string};
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const DOCUMENT_TYPES=new Set(['application/pdf','image/jpeg','image/png','image/webp']);
function record(value:unknown):value is Record<string,any>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function text(value:unknown,label:string,max:number,required=true){const normalized=typeof value==='string'?value.trim():'';if((required&&!normalized)||normalized.length>max||/[\u0000-\u001F\u007F]/.test(normalized))throw new Error(`${label} doğrulanamadı.`);return normalized;}
function path(value:unknown){const normalized=text(value,'Sertifika belge yolu',1200);if(/^[a-z][a-z0-9+.-]*:/i.test(normalized)||normalized.startsWith('/')||normalized.split('/').some(part=>!part||part==='.'||part==='..'))throw new Error('Sertifika belge yolu doğrulanamadı.');return normalized;}
function date(value:unknown,label:string,required=true){const normalized=text(value,label,20,required);if(!normalized)return'';if(!/^\d{4}-\d{2}-\d{2}$/.test(normalized)||Number.isNaN(Date.parse(`${normalized}T00:00:00Z`)))throw new Error(`${label} doğrulanamadı.`);return normalized;}
function normalize(value:unknown,index:number):AdminProductCertification{if(!record(value)||!UUID_RE.test(String(value.id||'')))throw new Error(`${index+1}. ürün sertifikası doğrulanamadı.`);const status=text(value.status,'Sertifika durumu',20) as AdminProductCertification['status'];if(!['valid','revoked','expired'].includes(status))throw new Error('Sertifika durumu doğrulanamadı.');return{id:String(value.id),certificateType:text(value.certificateType,'Sertifika tipi',80),issuer:text(value.issuer,'Sertifika kuruluşu',180),certificateNumber:text(value.certificateNumber,'Sertifika numarası',120),issuedAt:date(value.issuedAt,'Düzenlenme tarihi'),expiresAt:value.expiresAt?date(value.expiresAt,'Geçerlilik tarihi'):null,status,documentPath:value.documentPath?path(value.documentPath):'',reviewedAt:text(value.reviewedAt,'İnceleme tarihi',80,false),reviewNote:text(value.reviewNote,'İnceleme notu',2000,false)};}
export async function listOfficialProductCertifications(productId:string){if(!UUID_RE.test(productId))throw new Error('Ürün kimliği doğrulanamadı.');const{data,error}=await supabase.rpc('admin_get_product_certifications_v1',{p_product_id:productId});if(error)throw error;if(!Array.isArray(data)||data.length>100)throw new Error('Ürün sertifikaları doğrulanamadı.');return data.map(normalize);}
export async function uploadOfficialProductCertificate(file:File){if(!(file instanceof File)||!DOCUMENT_TYPES.has(file.type))throw new Error('Sertifika belgesi PDF, JPEG, PNG veya WebP olmalıdır.');if(file.size<=0||file.size>20*1024*1024)throw new Error('Sertifika belgesi en fazla 20 MB olabilir.');const{data,error}=await supabase.auth.getUser();if(error)throw error;const userId=data.user?.id;if(!userId||!UUID_RE.test(userId))throw new Error('Super Admin oturumu doğrulanamadı.');const ext=file.type==='application/pdf'?'pdf':file.type==='image/jpeg'?'jpg':file.type==='image/png'?'png':'webp';const storagePath=`admin/${userId}/organic/${crypto.randomUUID()}.${ext}`;const{error:uploadError}=await supabase.storage.from('product-certificates').upload(storagePath,file,{contentType:file.type,upsert:false,cacheControl:'3600'});if(uploadError)throw uploadError;return storagePath;}
export async function removeUnlinkedOfficialProductCertificate(pathValue:string){const normalized=path(pathValue);const{error}=await supabase.storage.from('product-certificates').remove([normalized]);if(error)throw error;}
export async function recordOfficialProductOrganicCertificate(input:{productId:string;issuer:string;certificateNumber:string;issuedAt:string;expiresAt:string;documentPath:string;reviewConfirmed:boolean;reviewNote:string}){if(!UUID_RE.test(input.productId))throw new Error('Ürün kimliği doğrulanamadı.');const issuer=text(input.issuer,'Sertifika kuruluşu',180),certificateNumber=text(input.certificateNumber,'Sertifika numarası',120),issuedAt=date(input.issuedAt,'Düzenlenme tarihi'),expiresAt=date(input.expiresAt,'Geçerlilik tarihi'),documentPath=path(input.documentPath),reviewNote=text(input.reviewNote,'İnceleme notu',2000,false);if(!input.reviewConfirmed)throw new Error('Belgeyi gerçekten kontrol ettiğinizi onaylayın.');const{data,error}=await supabase.rpc('admin_record_product_organic_certificate_v1',{p_product_id:input.productId,p_issuer:issuer,p_certificate_number:certificateNumber,p_issued_at:issuedAt,p_expires_at:expiresAt,p_document_path:documentPath,p_review_confirmed:true,p_review_note:reviewNote||null});if(error)throw error;if(!record(data)||!UUID_RE.test(String(data.id||''))||data.status!=='valid')throw new Error('Sertifika doğrulama sonucu doğrulanamadı.');return data;}
export async function revokeOfficialProductCertification(certificationId:string,reason:string){if(!UUID_RE.test(certificationId))throw new Error('Sertifika kimliği doğrulanamadı.');const normalizedReason=text(reason,'İptal gerekçesi',2000);if(normalizedReason.length<8)throw new Error('İptal gerekçesi en az 8 karakter olmalıdır.');const{data,error}=await supabase.rpc('admin_revoke_product_certification_v1',{p_certification_id:certificationId,p_reason:normalizedReason});if(error)throw error;if(!record(data)||data.status!=='revoked')throw new Error('Sertifika iptal sonucu doğrulanamadı.');return data;}
export async function createOfficialProductCertificateDocumentUrl(documentPath:string){const normalized=path(documentPath);const{data,error}=await supabase.storage.from('product-certificates').createSignedUrl(normalized,300);if(error)throw error;const url=String(data?.signedUrl||'').trim();if(!/^https:\/\//i.test(url)||url.length>4000)throw new Error('Sertifika belge görüntüsü oluşturulamadı.');return url;}
