import { supabase } from '../lib/supabase';

export type ProductRemovalMode='archived_preserving_history'|'permanently_deleted';
export type ProductRemovalResult={id:string;mode:ProductRemovalMode;imagePaths:string[];orderRefs:number;reviewRefs:number;batchRefs:number;changeRefs:number;};
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function record(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function unwrap<T>(data:T|null,error:unknown):T{if(error)throw error;return data as T;}
function integer(value:unknown,label:string){if(typeof value!=='number'||!Number.isSafeInteger(value)||value<0)throw new Error(`${label} doğrulanamadı.`);return value;}
function uuid(value:unknown,label:string){const text=typeof value==='string'?value.trim():'';if(!UUID_RE.test(text))throw new Error(`${label} doğrulanamadı.`);return text;}
function imagePaths(value:unknown){if(!Array.isArray(value)||value.length>1000)throw new Error('Ürün görsel temizleme listesi doğrulanamadı.');return value.map((item,index)=>{const path=typeof item==='string'?item.trim():'';if(!path||path.length>1200||/^[a-z][a-z0-9+.-]*:/i.test(path)||path.startsWith('/')||path.split('/').some(part=>!part||part==='.'||part==='..'))throw new Error(`${index+1}. ürün görsel yolu doğrulanamadı.`);return path;});}
export async function superAdminRemoveProduct(productId:string,reason:string):Promise<ProductRemovalResult>{const id=uuid(productId,'Ürün kimliği');const clean=reason.trim();if(clean.length<8||clean.length>1000)throw new Error('Ürün kaldırma gerekçesi 8 ile 1000 karakter arasında olmalıdır.');const{data,error}=await supabase.rpc('super_admin_remove_product_v1',{p_product_id:id,p_reason:clean});const raw=unwrap<unknown>(data,error);if(!record(raw)||uuid(raw.id,'Ürün kimliği')!==id)throw new Error('Ürün kaldırma sonucu doğrulanamadı.');const mode=raw.mode;if(mode!=='archived_preserving_history'&&mode!=='permanently_deleted')throw new Error('Ürün kaldırma biçimi doğrulanamadı.');const result={id,mode,imagePaths:imagePaths(raw.imagePaths),orderRefs:integer(raw.orderRefs,'Sipariş referans sayısı'),reviewRefs:integer(raw.reviewRefs,'Yorum referans sayısı'),batchRefs:integer(raw.batchRefs,'Lot referans sayısı'),changeRefs:integer(raw.changeRefs,'Değişiklik referans sayısı')};if(mode==='permanently_deleted'&&(result.orderRefs||result.reviewRefs||result.batchRefs||result.changeRefs))throw new Error('Kalıcı silme sonucu geçmiş referanslarıyla tutarsız.');if(mode==='archived_preserving_history'&&result.imagePaths.length)throw new Error('Geçmiş korumalı kaldırmada görseller fiziksel temizlemeye gönderilemez.');return result;}
export async function removeDeletedProductImages(paths:string[]){if(!paths.length)return;const{error}=await supabase.storage.from('catalog-public').remove(paths);if(error)throw error;}
export function productRemovalErrorMessage(error:unknown,fallback='Ürün kaldırma işlemi tamamlanamadı.'){const message=String((error as{message?:unknown}|null)?.message||'').trim();const map:Array<[string,string]>=[['super_admin_required','Bu işlem yalnız Super Admin tarafından yapılabilir.'],['product_not_found','Ürün artık bulunamadı. Listeyi yenileyin.'],['product_removal_reason_required','Ürün kaldırma için açık bir gerekçe yazmalısınız.']];for(const[key,value]of map)if(message.includes(key))return value;return message||fallback;}
