import{supabase}from'../lib/supabase';

export type AdminOptionChoice={value:string;label:string;description:string};
export type AdminOptionGroup={key:string;label:string;help:string;required:boolean;choices:AdminOptionChoice[];visibleWhen:{key:string;equals:string}|null};
export type AdminCommerceProfile={optionSchema:AdminOptionGroup[];seasonalityMode:'year_round'|'seasonal'|'made_to_order';seasonStartMonth:number|null;seasonEndMonth:number|null;preorderEnabled:boolean;preparationDaysMin:number|null;preparationDaysMax:number|null;customerSeasonNote:string;researchBasis:string;researchSourceLabel:string;};
export type AdminSalesWindow={seasonYear:number;opensAt:string;closesAt:string;fulfillmentStartsAt:string;fulfillmentEndsAt:string;status:'scheduled'|'open'|'closed'|'paused';confirmed:boolean;publicNote:string;internalNote:string;};
export type AdminPriceVariant={id:string;sku:string;name:string;priceMinor:number;compareAtPriceMinor:number|null;weightGrams:number;default:boolean;active:boolean;updatedAt:string};
export type CommerceProductOption={id:string;name:string;slug:string;category:string};

function record(value:unknown):value is Record<string,any>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function text(value:unknown,max=1000){return typeof value==='string'?value.trim().slice(0,max):'';}
function integer(value:unknown,min:number,max:number){return typeof value==='number'&&Number.isSafeInteger(value)&&value>=min&&value<=max?value:null;}
function uuid(value:unknown){const v=text(value,80);return/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v)?v:'';}
function dateInput(value:unknown){const raw=text(value,80);if(!raw||Number.isNaN(Date.parse(raw)))return'';const d=new Date(raw);const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16);}

function normalizeChoice(value:unknown,index:number):AdminOptionChoice{if(!record(value))throw new Error(`${index+1}. seçenek doğrulanamadı.`);const choiceValue=text(value.value,60),label=text(value.label,100);if(!/^[A-Za-z0-9][A-Za-z0-9_-]{0,59}$/.test(choiceValue)||!label)throw new Error(`${index+1}. seçenek kimliği veya adı geçersiz.`);return{value:choiceValue,label,description:text(value.description,240)};}
function normalizeGroup(value:unknown,index:number):AdminOptionGroup{if(!record(value))throw new Error(`${index+1}. seçenek grubu doğrulanamadı.`);const key=text(value.key,40),label=text(value.label,100);if(!/^[A-Za-z][A-Za-z0-9_]{0,39}$/.test(key)||!label)throw new Error(`${index+1}. seçenek grubu anahtarı veya adı geçersiz.`);if(!Array.isArray(value.choices)||!value.choices.length||value.choices.length>12)throw new Error(`${label} için 1-12 seçenek gerekir.`);const visible=record(value.visibleWhen)?{key:text(value.visibleWhen.key,40),equals:text(value.visibleWhen.equals,60)}:null;return{key,label,help:text(value.help,240),required:value.required===true,choices:value.choices.map(normalizeChoice),visibleWhen:visible?.key&&visible.equals?visible:null};}
function normalizeProfile(value:unknown):AdminCommerceProfile{const p=record(value)?value:{};const mode=['year_round','seasonal','made_to_order'].includes(text(p.seasonalityMode,40))?text(p.seasonalityMode,40)as AdminCommerceProfile['seasonalityMode']:'year_round';const schema=Array.isArray(p.optionSchema)?p.optionSchema.map(normalizeGroup):[];return{optionSchema:schema,seasonalityMode:mode,seasonStartMonth:integer(p.seasonStartMonth,1,12),seasonEndMonth:integer(p.seasonEndMonth,1,12),preorderEnabled:p.preorderEnabled===true,preparationDaysMin:integer(p.preparationDaysMin,0,365),preparationDaysMax:integer(p.preparationDaysMax,0,365),customerSeasonNote:text(p.customerSeasonNote,1200),researchBasis:text(p.researchBasis,2000),researchSourceLabel:text(p.researchSourceLabel,500)};}
function normalizeWindow(value:unknown):AdminSalesWindow{const w=record(value)?value:{};const status=['scheduled','open','closed','paused'].includes(text(w.status,40))?text(w.status,40)as AdminSalesWindow['status']:'scheduled';return{seasonYear:integer(w.seasonYear,2020,2200)??new Date().getFullYear(),opensAt:dateInput(w.opensAt),closesAt:dateInput(w.closesAt),fulfillmentStartsAt:dateInput(w.fulfillmentStartsAt),fulfillmentEndsAt:dateInput(w.fulfillmentEndsAt),status,confirmed:w.confirmed===true,publicNote:text(w.publicNote,1000),internalNote:text(w.internalNote,2000)};}
function normalizeVariant(value:unknown,index:number):AdminPriceVariant{if(!record(value))throw new Error(`${index+1}. fiyat varyantı doğrulanamadı.`);const id=uuid(value.id),sku=text(value.sku,80).toUpperCase(),name=text(value.name,120),price=integer(value.priceMinor,0,1_000_000_000),compare=value.compareAtPriceMinor===null||value.compareAtPriceMinor===undefined?null:integer(value.compareAtPriceMinor,0,1_000_000_000),weight=integer(value.weightGrams,1,1_000_000);if(!/^[A-Z0-9][A-Z0-9._-]{2,79}$/.test(sku)||!name||price===null||weight===null||compare!==null&&compare<price)throw new Error(`${index+1}. fiyat varyantı geçersiz.`);return{id,sku,name,priceMinor:price,compareAtPriceMinor:compare,weightGrams:weight,default:value.default===true,active:value.active!==false,updatedAt:text(value.updatedAt,80)};}
function normalizeVariants(value:unknown):AdminPriceVariant[]{if(!Array.isArray(value)||value.length<1||value.length>12)throw new Error('Ürün için 1-12 fiyat varyantı gerekir.');const rows=value.map(normalizeVariant);if(new Set(rows.map(row=>row.sku)).size!==rows.length)throw new Error('Varyant SKU değerleri benzersiz olmalıdır.');if(rows.filter(row=>row.active&&row.default).length!==1)throw new Error('Tam olarak bir aktif varsayılan fiyat varyantı gerekir.');return rows;}

export async function listCommerceProducts():Promise<CommerceProductOption[]>{const{data,error}=await supabase.rpc('management_catalog_snapshot_v1');if(error)throw error;if(!record(data)||!Array.isArray(data.products))throw new Error('Ürün listesi alınamadı.');return data.products.flatMap((raw:any)=>{if(!record(raw))return[];const id=uuid(raw.databaseId||raw.id),name=text(raw.name,300),slug=text(raw.slug,220);if(!id||!name||!slug)return[];return[{id,name,slug,category:text(raw.category,200)||text(raw.categoryName,200)||'Kategori'}];}).sort((a,b)=>a.name.localeCompare(b.name,'tr'));}

export async function loadProductCommerceEditor(productId:string){if(!uuid(productId))throw new Error('Ürün kimliği geçersiz.');const{data,error}=await supabase.rpc('management_product_commerce_editor_v1',{p_product_id:productId});if(error)throw error;if(!record(data)||!record(data.product))throw new Error('Ürün seçenekleri yüklenemedi.');const variants=Array.isArray(data.variants)?data.variants.map(normalizeVariant):[];if(!variants.length)throw new Error('Ürünün fiyat varyantı bulunamadı.');return{product:{id:uuid(data.product.id),name:text(data.product.name,300),slug:text(data.product.slug,220),stockMode:text(data.product.stockMode,80),status:text(data.product.status,40)},profile:normalizeProfile(data.profile),variants,canManageLivePricing:data.canManageLivePricing===true,windows:Array.isArray(data.windows)?data.windows.map(normalizeWindow):[],canConfirmWindow:data.canConfirmWindow===true};}

export async function saveProductCommerceProfile(productId:string,profile:AdminCommerceProfile){if(!uuid(productId))throw new Error('Ürün kimliği geçersiz.');const normalized=normalizeProfile(profile);if(normalized.preparationDaysMin!==null&&normalized.preparationDaysMax!==null&&normalized.preparationDaysMax<normalized.preparationDaysMin)throw new Error('Azami hazırlık süresi asgari süreden kısa olamaz.');const{data,error}=await supabase.rpc('management_save_product_commerce_profile_v1',{p_product_id:productId,p_profile:{optionSchema:normalized.optionSchema.map(group=>({key:group.key,label:group.label,help:group.help||undefined,required:group.required,choices:group.choices.map(choice=>({value:choice.value,label:choice.label,description:choice.description||undefined})),visibleWhen:group.visibleWhen||undefined})),seasonalityMode:normalized.seasonalityMode,seasonStartMonth:normalized.seasonStartMonth,seasonEndMonth:normalized.seasonEndMonth,preorderEnabled:normalized.preorderEnabled,preparationDaysMin:normalized.preparationDaysMin,preparationDaysMax:normalized.preparationDaysMax,customerSeasonNote:normalized.customerSeasonNote,researchBasis:normalized.researchBasis,researchSourceLabel:normalized.researchSourceLabel}});if(error)throw error;return data;}

export async function saveProductPriceVariants(productId:string,variants:AdminPriceVariant[]){if(!uuid(productId))throw new Error('Ürün kimliği geçersiz.');const normalized=normalizeVariants(variants);for(const row of normalized)if(row.id&&!row.updatedAt)throw new Error(`${row.name} için güncelleme sürümü eksik.`);const{data,error}=await supabase.rpc('management_save_product_price_variants_v1',{p_product_id:productId,p_variants:normalized.map(row=>({id:row.id||undefined,sku:row.sku,name:row.name,priceMinor:row.priceMinor,compareAtPriceMinor:row.compareAtPriceMinor,weightGrams:row.weightGrams,default:row.default,active:row.active,updatedAt:row.updatedAt||undefined}))});if(error)throw error;if(!Array.isArray(data))throw new Error('Fiyat varyantları kaydedildi ancak sunucu yanıtı doğrulanamadı.');return data.map(normalizeVariant);}

export async function saveProductSalesWindow(productId:string,window:AdminSalesWindow){if(!uuid(productId))throw new Error('Ürün kimliği geçersiz.');const normalized=normalizeWindow(window);for(const[key,value]of Object.entries({opensAt:normalized.opensAt,closesAt:normalized.closesAt,fulfillmentStartsAt:normalized.fulfillmentStartsAt,fulfillmentEndsAt:normalized.fulfillmentEndsAt}))if(value&&Number.isNaN(Date.parse(value)))throw new Error(`${key} tarihi geçersiz.`);const{data,error}=await supabase.rpc('management_save_product_sales_window_v1',{p_product_id:productId,p_window:{seasonYear:normalized.seasonYear,opensAt:normalized.opensAt?new Date(normalized.opensAt).toISOString():null,closesAt:normalized.closesAt?new Date(normalized.closesAt).toISOString():null,fulfillmentStartsAt:normalized.fulfillmentStartsAt?new Date(normalized.fulfillmentStartsAt).toISOString():null,fulfillmentEndsAt:normalized.fulfillmentEndsAt?new Date(normalized.fulfillmentEndsAt).toISOString():null,status:normalized.status,confirmed:normalized.confirmed,publicNote:normalized.publicNote,internalNote:normalized.internalNote}});if(error)throw error;return data;}

export function emptyOptionGroup(index:number):AdminOptionGroup{return{key:`option${index+1}`,label:'Yeni seçenek grubu',help:'',required:true,choices:[{value:'standard',label:'Standart',description:''},{value:'alternative',label:'Alternatif',description:''}],visibleWhen:null};}
export function emptySalesWindow():AdminSalesWindow{return{seasonYear:new Date().getFullYear()+1,opensAt:'',closesAt:'',fulfillmentStartsAt:'',fulfillmentEndsAt:'',status:'scheduled',confirmed:false,publicNote:'',internalNote:''};}
export function emptyPriceVariant(seed?:AdminPriceVariant):AdminPriceVariant{return{id:'',sku:`GO-${crypto.randomUUID().slice(0,8).toUpperCase()}`,name:'Yeni paket',priceMinor:seed?.priceMinor??0,compareAtPriceMinor:null,weightGrams:seed?.weightGrams??1000,default:false,active:true,updatedAt:''};}