import { supabase } from '../lib/supabase';

export type AdminProducerPayoutStatus = 'requested' | 'scheduled' | 'processing' | 'paid' | 'failed' | 'cancelled';
export type AdminProducerPayoutChannel = 'provider_marketplace' | 'manual_bank_transfer';
export type AdminProducerPayoutBalance = { pendingMinor:number; availableLedgerMinor:number; reservedPayoutMinor:number; paidPayoutMinor:number; providerTransferProcessingMinor:number; manualWithdrawalPendingMinor:number; availableToPayoutMinor:number; lifetimeNetMinor:number };
export type AdminProducerPayout = {
  id:string; producerId:string; producerName:string; ownerUserId:string|null; ownerEmail:string|null; currency:string; amountMinor:number; status:AdminProducerPayoutStatus; channel:AdminProducerPayoutChannel; requestSource:string; sourceOrderId:string|null; orderNumber:string|null;
  provider:string|null; providerReference:string|null; note:string|null; destinationAccountHolder:string|null; destinationIban:string|null; destinationIbanMasked:string|null; requestedAt:string|null; scheduledAt:string|null; providerSettlementReleasedAt:string|null; processedAt:string|null; createdAt:string; balance:AdminProducerPayoutBalance;
};

const STATUSES = new Set<AdminProducerPayoutStatus>(['requested','scheduled','processing','paid','failed','cancelled']);
const CHANNELS = new Set<AdminProducerPayoutChannel>(['provider_marketplace','manual_bank_transfer']);
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function rec(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function text(value:unknown,label:string,max=500,required=true){if(value==null||value===''){if(required)throw new Error(`${label} doğrulanamadı.`);return null;}if(typeof value!=='string')throw new Error(`${label} doğrulanamadı.`);const out=value.trim();if((required&&!out)||out.length>max||/[\u0000-\u001F\u007F]/.test(out))throw new Error(`${label} doğrulanamadı.`);return out||null;}
function uuid(value:unknown,label:string,required=true){const out=text(value,label,36,required);if(out==null)return null;if(!UUID_RE.test(out))throw new Error(`${label} doğrulanamadı.`);return out;}
function integer(value:unknown,label:string,min=0){if(typeof value!=='number'||!Number.isSafeInteger(value)||value<min)throw new Error(`${label} doğrulanamadı.`);return value;}
function dateTime(value:unknown,label:string,required=false){const out=text(value,label,80,required);if(out==null)return null;if(Number.isNaN(Date.parse(out)))throw new Error(`${label} doğrulanamadı.`);return out;}
function code(value:unknown){const out=(text(value,'Para birimi',3,true) as string).toUpperCase();if(!/^[A-Z]{3}$/.test(out))throw new Error('Para birimi doğrulanamadı.');return out;}
function balance(value:unknown):AdminProducerPayoutBalance{if(!rec(value))throw new Error('Satıcı bakiyesi doğrulanamadı.');const pendingMinor=integer(value.pendingMinor,'Bekleyen bakiye'),availableLedgerMinor=integer(value.availableLedgerMinor,'Serbest bırakılan bakiye'),reservedPayoutMinor=integer(value.reservedPayoutMinor,'Rezerve ödeme'),paidPayoutMinor=integer(value.paidPayoutMinor,'Ödenen bakiye'),providerTransferProcessingMinor=integer(value.providerTransferProcessingMinor??0,'iyzico aktarımı'),manualWithdrawalPendingMinor=integer(value.manualWithdrawalPendingMinor??0,'Banka çekimi'),availableToPayoutMinor=integer(value.availableToPayoutMinor,'Manuel çekilebilir bakiye'),lifetimeNetMinor=integer(value.lifetimeNetMinor,'Toplam net');if(lifetimeNetMinor!==pendingMinor+availableLedgerMinor)throw new Error('Satıcı bakiye toplamı tutarsız.');return{pendingMinor,availableLedgerMinor,reservedPayoutMinor,paidPayoutMinor,providerTransferProcessingMinor,manualWithdrawalPendingMinor,availableToPayoutMinor,lifetimeNetMinor};}
function normalize(value:unknown,index:number):AdminProducerPayout{if(!rec(value))throw new Error(`${index+1}. ödeme kaydı doğrulanamadı.`);const status=text(value.status,'Ödeme durumu',30,true) as AdminProducerPayoutStatus,channel=text(value.channel,'Ödeme kanalı',40,true) as AdminProducerPayoutChannel;if(!STATUSES.has(status)||!CHANNELS.has(channel))throw new Error(`${index+1}. ödeme durumu doğrulanamadı.`);const destinationIban=text(value.destinationIban,'IBAN',34,false);if(destinationIban&& !/^TR[0-9]{24}$/.test(destinationIban.replace(/\s+/g,'').toUpperCase()))throw new Error(`${index+1}. ödeme IBAN'ı doğrulanamadı.`);return{id:uuid(value.id,'Ödeme kimliği') as string,producerId:uuid(value.producerId,'Satıcı kimliği') as string,producerName:text(value.producerName,'Satıcı adı',240,true) as string,ownerUserId:uuid(value.ownerUserId,'Hesap kimliği',false),ownerEmail:text(value.ownerEmail,'E-posta',320,false),currency:code(value.currency),amountMinor:integer(value.amountMinor,'Ödeme tutarı',1),status,channel,requestSource:text(value.requestSource,'Talep kaynağı',60,true) as string,sourceOrderId:uuid(value.sourceOrderId,'Sipariş kimliği',false),orderNumber:text(value.orderNumber,'Sipariş numarası',160,false),provider:text(value.provider,'Sağlayıcı',80,false),providerReference:text(value.providerReference,'Transfer referansı',255,false),note:text(value.note,'Ödeme notu',1000,false),destinationAccountHolder:text(value.destinationAccountHolder,'Hesap sahibi',300,false),destinationIban:destinationIban?destinationIban.replace(/\s+/g,'').toUpperCase():null,destinationIbanMasked:text(value.destinationIbanMasked,'Maskelenmiş IBAN',80,false),requestedAt:dateTime(value.requestedAt,'Talep tarihi'),scheduledAt:dateTime(value.scheduledAt,'Planlama tarihi'),providerSettlementReleasedAt:dateTime(value.providerSettlementReleasedAt,'Sağlayıcı serbest bırakma tarihi'),processedAt:dateTime(value.processedAt,'Sonuç tarihi'),createdAt:dateTime(value.createdAt,'Oluşturma tarihi',true) as string,balance:balance(value.balance)};}

export async function superAdminListProducerPayouts(status:'all'|AdminProducerPayoutStatus='all',limit=200,offset=0){if(!Number.isSafeInteger(limit)||limit<1||limit>500||!Number.isSafeInteger(offset)||offset<0)throw new Error('Ödeme sayfalaması geçersiz.');const{data,error}=await supabase.rpc('super_admin_list_producer_payouts_v2',{p_status:status==='all'?null:status,p_limit:limit,p_offset:offset});if(error)throw error;if(!Array.isArray(data)||data.length>limit)throw new Error('Ödeme kuyruğu doğrulanamadı.');return data.map(normalize);}
export async function superAdminUpdateProducerPayout(input:{id:string;status:'processing'|'paid'|'failed'|'cancelled';reference?:string|null;note?:string|null}){const id=uuid(input.id,'Ödeme kimliği') as string;if(!['processing','paid','failed','cancelled'].includes(input.status))throw new Error('Ödeme durumu geçersiz.');const reference=text(input.reference,'Transfer referansı',180,false),note=text(input.note,'Ödeme notu',1000,false);if(input.status==='paid'&&(!reference||reference.length<4))throw new Error('Ödendi kaydı için banka/sağlayıcı transfer referansı gerekir.');const{data,error}=await supabase.rpc('super_admin_update_producer_payout_v2',{p_payout_id:id,p_status:input.status,p_reference:reference,p_note:note});if(error)throw error;if(!rec(data)||uuid(data.id,'Ödeme kimliği')!==id||data.status!==input.status)throw new Error('Ödeme güncelleme sonucu doğrulanamadı.');return true;}
export function producerPayoutAdminErrorMessage(error:unknown,fallback='Satıcı ödeme işlemi tamamlanamadı.'){const message=String((error as{message?:unknown}|null)?.message||'').trim();const map:Array<[string,string]>=[['super_admin_required','Bu ekran ve ödeme işlemleri yalnız Super Admin içindir.'],['payout_not_found','Ödeme kaydı artık bulunamadı. Listeyi yenileyin.'],['invalid_payout_transition','Seçilen durum geçişi bu ödeme için geçerli değil.'],['payout_payment_reference_required','Ödendi olarak kapatmak için gerçek banka veya iyzico transfer referansı girin.'],['invalid_payout_status','Ödeme durumu geçersiz.'],['producer_bank_identity_incomplete','Satıcının ödeme IBAN veya hesap sahibi bilgisi eksik.']];for(const[key,label]of map)if(message.includes(key))return label;return message&&message.length<=300?message:fallback;}
export function formatPayoutMinor(value:number,currency:string){try{return new Intl.NumberFormat('tr-TR',{style:'currency',currency,maximumFractionDigits:2}).format(value/100);}catch{return`${(value/100).toFixed(2)} ${currency}`;}}
