import React,{useEffect,useState}from'react';
import{AlertTriangle,CheckCircle2,ImageOff,RefreshCw,ShieldCheck}from'lucide-react';
import{getSuperAdminProductPublishReadiness,publishReadinessErrorMessage,type PublishReadinessSnapshot,type PublishReadinessState}from'./productPublishReadinessApi';

type Props={onOpenProduct:(productId:string)=>void;};
const STATES:Array<{value:PublishReadinessState;label:string}>=[{value:'all',label:'Tümü'},{value:'published',label:'Published'},{value:'ready',label:'Ready to Publish'},{value:'missing_media',label:'Gerçek görsel eksik'},{value:'data_missing',label:'Zorunlu veri eksik'},{value:'media_blocked',label:'Media blocked'},{value:'owner_required',label:'Owner approval required'}];

export default function ProductPublishReadinessPanel({onOpenProduct}:Props){
 const[snapshot,setSnapshot]=useState<PublishReadinessSnapshot|null>(null);
 const[state,setState]=useState<PublishReadinessState>('all');
 const[loading,setLoading]=useState(true);
 const[error,setError]=useState('');
 async function load(nextState=state){try{setLoading(true);setError('');setSnapshot(await getSuperAdminProductPublishReadiness({state:nextState,limit:100,offset:0}));}catch(err){setError(publishReadinessErrorMessage(err));}finally{setLoading(false);}}
 useEffect(()=>{void load(state);},[state]);
 const summary=snapshot?.summary;
 return<section className="rounded-2xl border bg-white p-4 dark:bg-gray-800" aria-labelledby="publish-readiness-title">
  <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-2"><ShieldCheck aria-hidden="true" className="h-5 w-5 text-brand-green"/><h3 id="publish-readiness-title" className="font-black">Ürün yayın hazırlığı</h3></div><p className="mt-1 max-w-3xl text-sm text-gray-500">Bu görünüm yeni lifecycle state üretmez. Mevcut ürün, gerçek Storage medya ve zorunlu yayın gate'lerinden anlık olarak hesaplanır. Yayın kararı yine Super Admin owner komutunda kalır.</p></div><button type="button" onClick={()=>void load()} disabled={loading} className="min-h-11 rounded-xl border px-4 font-bold disabled:opacity-60"><RefreshCw aria-hidden="true" className={`mr-2 inline h-4 w-4 ${loading?'animate-spin':''}`}/>Yenile</button></div>
  {error?<div role="alert" className="mt-3 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>:null}
  {summary?<div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-7"><Metric label="Toplam ürün" value={summary.total}/><Metric label="Published" value={summary.published}/><Metric label="Ready to Publish" value={summary.readyToPublish}/><Metric label="Gerçek görsel eksik" value={summary.missingRealMedia}/><Metric label="Zorunlu veri eksik" value={summary.mandatoryDataMissing}/><Metric label="Media blocked" value={summary.mediaBlocked}/><Metric label="Owner approval required" value={summary.ownerApprovalRequired}/></div>:null}
  <div className="mt-4 flex gap-2 overflow-x-auto pb-1" aria-label="Yayın hazırlığı filtreleri">{STATES.map(option=><button type="button" key={option.value} onClick={()=>setState(option.value)} aria-pressed={state===option.value} className={`min-h-10 shrink-0 rounded-full border px-3 text-sm font-bold ${state===option.value?'border-brand-green bg-brand-green text-brand-on-green':'bg-white dark:bg-gray-900'}`}>{option.label}</button>)}</div>
  {loading&&!snapshot?<div role="status" className="mt-4 rounded-xl border p-5 text-center text-sm text-gray-500">Ürün yayın hazırlığı hesaplanıyor...</div>:null}
  {!loading&&snapshot&&!snapshot.items.length?<div className="mt-4 rounded-xl border border-dashed p-5 text-center text-sm text-gray-500">Bu durumda ürün yok.</div>:null}
  {snapshot?.items.length?<div className="mt-4 space-y-2">{snapshot.items.map(item=><article key={item.productId} className="rounded-xl border p-3"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-black">{item.name}</span>{item.readyToPublish?<Status tone="ready" label="READY TO PUBLISH"/>:item.published?<Status tone="published" label="PUBLISHED"/>:item.missingRealMedia?<Status tone="blocked" label="GERÇEK GÖRSEL BEKLİYOR"/>:<Status tone="blocked" label="ONAY / TAMAMLAMA BEKLİYOR"/>}</div><div className="mt-1 text-xs text-gray-500">{item.producerName||'Üretici bilgisi yok'} · {item.status}</div>{item.reasons.length?<ul className="mt-2 space-y-1 text-sm">{item.reasons.map(reason=><li key={reason.code} className="flex items-start gap-2"><AlertTriangle aria-hidden="true" className="mt-0.5 h-4 w-4 shrink-0 text-amber-600"/><span>{reason.label}</span></li>)}</ul>:<div className="mt-2 flex items-center gap-2 text-sm font-semibold text-brand-green"><CheckCircle2 aria-hidden="true" className="h-4 w-4"/>Zorunlu yayın gate'leri hazır.</div>}</div><button type="button" onClick={()=>onOpenProduct(item.productId)} className="min-h-11 shrink-0 rounded-xl border border-brand-green px-4 font-bold text-brand-green">Ürünü incele</button></div></article>)}</div>:null}
  {snapshot&&snapshot.filteredTotal>snapshot.items.length?<p className="mt-3 text-xs text-gray-500">İlk {snapshot.items.length} kayıt gösteriliyor. Toplam eşleşme: {snapshot.filteredTotal}.</p>:null}
 </section>;
}
function Metric({label,value}:{label:string;value:number}){return<div className="rounded-xl border p-3"><div className="text-xs font-semibold text-gray-500">{label}</div><div className="mt-1 text-2xl font-black tabular-nums">{value}</div></div>;}
function Status({label,tone}:{label:string;tone:'ready'|'published'|'blocked'}){const classes=tone==='ready'?'border-emerald-300 bg-emerald-50 text-emerald-800':tone==='published'?'border-blue-300 bg-blue-50 text-blue-800':'border-amber-300 bg-amber-50 text-amber-900';return<span className={`rounded-full border px-2 py-0.5 text-[11px] font-black ${classes}`}>{tone==='blocked'?<ImageOff aria-hidden="true" className="mr-1 inline h-3 w-3"/>:null}{label}</span>;}
