import { supabase } from '../lib/supabase';

export type ShippingWeightSource='unknown'|'estimated'|'measured'|'supplier';
export type ShippingWeightRow={variantId:string;productId:string;productName:string;variantName:string;sku:string|null;producerId:string;producerName:string;weightGrams:number|null;weightSource:ShippingWeightSource;weightNote:string|null;verifiedAt:string|null;missingWeight:boolean;estimatedWeight:boolean;verifiedWeight:boolean;updatedAt:string;};
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const WEIGHT_SOURCES=new Set<ShippingWeightSource>(['unknown','estimated','measured','supplier']);
function rec(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function text(value:unknown,label:string,max:number,nullable=false){if(value==null&&nullable)return null;if(typeof value!=='string')throw new Error(`${label} doğrulanamadı.`);const next=value.trim();if(!next&&nullable)return null;if(!next||next.length>max||/[\u0000-\u001F\u007F]/.test(next))throw new Error(`${label} doğrulanamadı.`);return next;}
function uuid(value:unknown,label:string){const id=text(value,label,36,false) as string;if(!UUID_RE.test(id))throw new Error(`${label} doğrulanamadı.`);return id;}
function integer(value:unknown,label:string,nullable=false){if(value==null&&nullable)return null;if(typeof value!=='number'||!Number.isSafeInteger(value)||value<0)throw new Error(`${label} doğrulanamadı.`);return value;}
function iso(value:unknown,label:string,nullable=false){if(value==null&&nullable)return null;const next=text(value,label,80,false) as string;if(Number.isNaN(Date.parse(next)))throw new Error(`${label} doğrulanamadı.`);return next;}
function weightSource(value:unknown):ShippingWeightSource{const source=text(value,'Kargo ağırlığı kaynağı',30,false) as ShippingWeightSource;if(!WEIGHT_SOURCES.has(source))throw new Error('Kargo ağırlığı kaynağı doğrulanamadı.');return source;}
function normalize(value:unknown,index=0):ShippingWeightRow{if(!rec(value))throw new Error(`${index+1}. kargo ağırlık kaydı doğrulanamadı.`);const weight=integer(value.weightGrams,'Kargo ağırlığı',true) as number|null,source=weightSource(value.weightSource);if(typeof value.missingWeight!=='boolean'||typeof value.estimatedWeight!=='boolean'||typeof value.verifiedWeight!=='boolean')throw new Error('Kargo ağırlık durumları doğrulanamadı.');const hasWeight=weight!=null&&weight>0,expectedMissing=!hasWeight,expectedEstimated=hasWeight&&source==='estimated',expectedVerified=hasWeight&&(source==='measured'||source==='supplier');if(value.missingWeight!==expectedMissing||value.estimatedWeight!==expectedEstimated||value.verifiedWeight!==expectedVerified)throw new Error('Kargo ağırlık durumu kendi içinde tutarsız.');if(hasWeight&&source==='unknown')throw new Error('Kargo ağırlığı kaynağı eksik.');if(!hasWeight&&source!=='unknown')throw new Error('Eksik kargo ağırlığı için kaynak durumu tutarsız.');const verifiedAt=iso(value.verifiedAt,'Ağırlık doğrulama zamanı',true) as string|null;if(expectedVerified&&!verifiedAt)throw new Error('Doğrulanmış ağırlığın doğrulama zamanı eksik.');if(expectedEstimated&&verifiedAt)throw new Error('Tahmini ağırlık doğrulanmış gibi işaretlenemez.');return{variantId:uuid(value.variantId,'Varyant kimliği'),productId:uuid(value.productId,'Ürün kimliği'),productName:text(value.productName,'Ürün adı',300,false) as string,variantName:text(value.variantName,'Varyant adı',240,false) as string,sku:text(value.sku,'SKU',120,true) as string|null,producerId:uuid(value.producerId,'Üretici kimliği'),producerName:text(value.producerName,'Üretici adı',240,false) as string,weightGrams:weight,weightSource:source,weightNote:text(value.weightNote,'Ağırlık kaynağı notu',500,true) as string|null,verifiedAt,missingWeight:value.missingWeight,estimatedWeight:value.estimatedWeight,verifiedWeight:value.verifiedWeight,updatedAt:iso(value.updatedAt,'Varyant güncelleme zamanı') as string};}
export async function listShippingWeightReadiness():Promise<ShippingWeightRow[]>{const{data,error}=await supabase.rpc('super_admin_list_shipping_weight_readiness_v1');if(error)throw error;if(!rec(data)||data.ok!==true||!Array.isArray(data.items))throw new Error('Kargo hazırlığı yanıtı doğrulanamadı.');return data.items.map(normalize);}
export async function updateVerifiedShippingWeight(input:{row:ShippingWeightRow;weightGrams:number;verificationNote:string}){if(!Number.isSafeInteger(input.weightGrams)||input.weightGrams<1||input.weightGrams>100000000)throw new Error('Doğrulanmış kargo ağırlığı 1 ile 100.000.000 gram arasında olmalıdır.');const note=input.verificationNote.trim();if(note.length<10||note.length>500)throw new Error('Ağırlığın hangi kaynaktan doğrulandığını 10 ile 500 karakter arasında yazın.');const{data,error}=await supabase.rpc('super_admin_update_variant_shipping_weight_v1',{p_variant_id:input.row.variantId,p_weight_grams:input.weightGrams,p_expected_updated_at:input.row.updatedAt,p_verification_note:note});if(error)throw error;if(!rec(data)||data.ok!==true||uuid(data.variantId,'Varyant kimliği')!==input.row.variantId)throw new Error('Kargo ağırlığı güncelleme sonucu doğrulanamadı.');const weight=integer(data.weightGrams,'Kargo ağırlığı') as number,updatedAt=iso(data.updatedAt,'Güncelleme zamanı') as string,source=weightSource(data.weightSource),verifiedAt=iso(data.verifiedAt,'Ağırlık doğrulama zamanı') as string;if(weight!==input.weightGrams||source!=='measured')throw new Error('Kargo ağırlığı sunucu sonucuyla eşleşmiyor.');return{weightGrams:weight,weightSource:source,verifiedAt,weightNote:note,updatedAt};}
export function shippingReadinessErrorMessage(error:unknown,fallback='Kargo hazırlığı işlemi tamamlanamadı.'){const raw=error instanceof Error?error.message:String((error as{message?:unknown})?.message||'');const map:Array<[string,string]>=[['super_admin_required','Kargo ağırlıklarını yalnız Super Admin yönetebilir.'],['shipping_weight_conflict','Bu varyant siz ekranı açtıktan sonra değişmiş. Güncel veriyi yeniden yükleyip tekrar deneyin.'],['shipping_weight_verification_note_required','Gerçek tartımın veya tedarikçi bilgisinin kaynağını açıklayan not gereklidir.'],['invalid_shipping_weight','Kargo ağırlığını gram cinsinden kontrol edin.']];for(const[key,message]of map)if(raw.includes(key))return message;return raw&&raw.length<=320?raw:fallback;}
