import{supabase}from'../lib/supabase';

export type StoreFollowSimulationStore={producerId:string;name:string;storeKind:'official'|'independent';verified:boolean;realFollowerCount:number;simulatedFollowers:number;updatedAt:string|null};
export type StoreFollowSimulationSnapshot={poolCapacity:number;allocated:number;available:number;publicMetricsIsolation:true;stores:StoreFollowSimulationStore[]};
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function record(value:unknown):value is Record<string,any>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function integer(value:unknown,label:string,max=10000){if(typeof value!=='number'||!Number.isSafeInteger(value)||value<0||value>max)throw new Error(`${label} doğrulanamadı.`);return value;}
function text(value:unknown,label:string,max:number){if(typeof value!=='string')throw new Error(`${label} doğrulanamadı.`);const normalized=value.trim();if(!normalized||normalized.length>max||/[\u0000-\u001F\u007F]/.test(normalized))throw new Error(`${label} doğrulanamadı.`);return normalized;}
function normalizeStore(value:unknown,index:number):StoreFollowSimulationStore{if(!record(value))throw new Error(`${index+1}. mağaza simülasyon kaydı doğrulanamadı.`);const producerId=text(value.producerId,'Mağaza kimliği',80);if(!UUID_RE.test(producerId))throw new Error(`${index+1}. mağaza kimliği doğrulanamadı.`);const storeKind=value.storeKind;if(storeKind!=='official'&&storeKind!=='independent')throw new Error(`${index+1}. mağaza türü doğrulanamadı.`);if(value.verified!==true)throw new Error(`${index+1}. mağaza doğrulama durumu geçersiz.`);const updatedAt=value.updatedAt==null?null:text(value.updatedAt,'Güncelleme zamanı',80);if(updatedAt&&Number.isNaN(Date.parse(updatedAt)))throw new Error(`${index+1}. güncelleme zamanı doğrulanamadı.`);return{producerId,name:text(value.name,'Mağaza adı',240),storeKind,verified:true,realFollowerCount:integer(value.realFollowerCount,'Gerçek takipçi sayısı',Number.MAX_SAFE_INTEGER),simulatedFollowers:integer(value.simulatedFollowers,'Simülasyon takipçisi'),updatedAt};}
function normalize(value:unknown):StoreFollowSimulationSnapshot{if(!record(value)||!Array.isArray(value.stores))throw new Error('Takip simülasyon havuzu doğrulanamadı.');const poolCapacity=integer(value.poolCapacity,'Havuz kapasitesi');const allocated=integer(value.allocated,'Ayrılmış simülasyon miktarı');const available=integer(value.available,'Kullanılabilir simülasyon miktarı');if(poolCapacity!==10000||allocated+available!==poolCapacity||value.publicMetricsIsolation!==true)throw new Error('Takip simülasyon güvenlik sınırı doğrulanamadı.');const stores=value.stores.map(normalizeStore);return{poolCapacity,allocated,available,publicMetricsIsolation:true,stores};}
export async function getStoreFollowSimulation():Promise<StoreFollowSimulationSnapshot>{const{data,error}=await supabase.rpc('get_store_follow_simulation_v1');if(error)throw error;return normalize(data);}
export async function setStoreFollowSimulation(producerId:string,simulatedFollowers:number):Promise<StoreFollowSimulationSnapshot>{const id=String(producerId||'').trim();if(!UUID_RE.test(id))throw new Error('Mağaza kimliği doğrulanamadı.');if(!Number.isSafeInteger(simulatedFollowers)||simulatedFollowers<0||simulatedFollowers>10000)throw new Error('Simülasyon takipçisi 0 ile 10.000 arasında olmalıdır.');const{data,error}=await supabase.rpc('admin_set_store_follow_simulation_v1',{p_producer_id:id,p_simulated_followers:simulatedFollowers});if(error)throw error;return normalize(data);}
export function storeFollowSimulationError(error:unknown){const message=String((error as{message?:unknown}|null)?.message||'').trim();if(message.includes('super_admin_required'))return'Bu alan yalnız Super Admin tarafından kullanılabilir.';if(message.includes('simulation_pool_capacity_exceeded'))return'Toplam simülasyon havuzu 10.000 sınırını aşamaz.';if(message.includes('invalid_simulation_allocation'))return'Simülasyon miktarı 0 ile 10.000 arasında olmalıdır.';if(message.includes('producer_not_available'))return'Mağaza aktif ve doğrulanmış olmadığı için simülasyon atanamaz.';return message&&message.length<=260?message:'Takip simülasyonu işlemi tamamlanamadı.';}
