import React,{useEffect,useMemo,useState}from'react';
import{AlertTriangle,CheckCircle2,Loader2,RefreshCw,ShieldCheck}from'lucide-react';
import{useAccessibleDialog}from'../features/accessibility/useAccessibleDialog';
import{supabase}from'../lib/supabase';

type ReadinessReason={code:string;label:string};
type ReadinessItem={productId:string;name:string;status:string;readyToPublish:boolean;reasons:ReadinessReason[]};
type ReadinessSnapshot={summary:{total:number;published:number;readyToPublish:number;missingRealMedia:number;mandatoryDataMissing:number;mediaBlocked:number;ownerApprovalRequired:number};items:ReadinessItem[]};
type BulkItemResult={productId:string;name:string;ok:boolean;approved:boolean;error?:string};
type BulkResult={requestedCount:number;successCount:number;failureCount:number;approved:boolean;results:BulkItemResult[]};
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function record(value:unknown):value is Record<string,any>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function integer(value:unknown,label:string){const number=typeof value==='string'&&/^\d+$/.test(value)?Number(value):value;if(typeof number!=='number'||!Number.isSafeInteger(number)||number<0)throw new Error(`${label} doğrulanamadı.`);return number;}
function text(value:unknown,label:string,max=400){if(typeof value!=='string')throw new Error(`${label} doğrulanamadı.`);const result=value.trim();if(!result||result.length>max||/[\u0000-\u001F\u007F]/.test(result))throw new Error(`${label} doğrulanamadı.`);return result;}
function normalizeReadiness(value:unknown):ReadinessSnapshot{if(!record(value)||!record(value.summary)||!Array.isArray(value.items)||value.items.length>500)throw new Error('Ürün yayın hazırlığı doğrulanamadı.');const summary={total:integer(value.summary.total,'Toplam ürün'),published:integer(value.summary.published,'Yayındaki ürün'),readyToPublish:integer(value.summary.readyToPublish,'Yayına hazır ürün'),missingRealMedia:integer(value.summary.missingRealMedia,'Görsel bekleyen ürün'),mandatoryDataMissing:integer(value.summary.mandatoryDataMissing,'Veri eksiği'),mediaBlocked:integer(value.summary.mediaBlocked,'Medya engeli'),ownerApprovalRequired:integer(value.summary.ownerApprovalRequired,'Sahip onayı')};const items=value.items.map((item:unknown,index:number)=>{if(!record(item))throw new Error(`${index+1}. yayın hazırlık kaydı doğrulanamadı.`);const productId=text(item.productId,'Ürün kimliği',36);if(!UUID_RE.test(productId))throw new Error('Ürün kimliği doğrulanamadı.');if(typeof item.readyToPublish!=='boolean'||!Array.isArray(item.reasons)||item.reasons.length>30)throw new Error('Ürün yayın hazırlık durumu doğrulanamadı.');const reasons=item.reasons.map((reason:unknown)=>{if(!record(reason))throw new Error('Yayın hazırlık gerekçesi doğrulanamadı.');return{code:text(reason.code,'Gerekçe kodu',120),label:text(reason.label,'Gerekçe',500)};});return{productId,name:text(item.name,'Ürün adı',300),status:text(item.status,'Ürün durumu',40),readyToPublish:item.readyToPublish,reasons};});if(summary.readyToPublish>summary.total||summary.published>summary.total)throw new Error('Ürün yayın hazırlık özeti tutarsız.');return{summary,items};}
function normalizeBulk(value:unknown):BulkResult{if(!record(value)||!Array.isArray(value.results)||value.results.length>500)throw new Error('Toplu yayın sonucu doğrulanamadı.');const result={requestedCount:integer(value.requestedCount,'İstenen ürün'),successCount:integer(value.successCount,'Başarılı ürün'),failureCount:integer(value.failureCount,'Başarısız ürün'),approved:value.approved===true,results:value.results.map((item:unknown,index:number)=>{if(!record(item))throw new Error(`${index+1}. toplu yayın sonucu doğrulanamadı.`);const productId=text(item.productId,'Ürün kimliği',36);if(!UUID_RE.test(productId)||typeof item.ok!=='boolean'||typeof item.approved!=='boolean')throw new Error('Toplu yayın ürün sonucu doğrulanamadı.');return{productId,name:text(item.name,'Ürün adı',300),ok:item.ok,approved:item.approved,error:typeof item.error==='string'?item.error.slice(0,500):undefined};})};if(result.successCount+result.failureCount!==result.requestedCount||result.results.length!==result.requestedCount)throw new Error('Toplu yayın sonuç sayıları tutarsız.');return result;}

export default function SuperAdminBulkProductRelease({onReleased}:{onReleased:()=>Promise<void>|void}){
 const[authorized,setAuthorized]=useState(false);const[loading,setLoading]=useState(true);const[snapshot,setSnapshot]=useState<ReadinessSnapshot|null>(null);const[error,setError]=useState('');const[dialogOpen,setDialogOpen]=useState(false);const[confirmation,setConfirmation]=useState('');const[busy,setBusy]=useState(false);const[result,setResult]=useState<BulkResult|null>(null);
 const dialogRef=useAccessibleDialog<HTMLDivElement>(dialogOpen,()=>{if(!busy){setDialogOpen(false);setConfirmation('');}});
 const ready=useMemo(()=>snapshot?.items.filter(item=>item.readyToPublish&&item.status==='review')||[],[snapshot]);const expectedPhrase=`YAYINLA ${ready.length}`;
 async function load(){setLoading(true);setError('');try{const[publish,health]=await Promise.all([supabase.rpc('authorization_has_permission_v1',{p_permission_key:'product.publish'}),supabase.rpc('authorization_has_permission_v1',{p_permission_key:'product.health_manage'})]);if(publish.error)throw publish.error;if(health.error)throw health.error;const allowed=publish.data===true&&health.data===true;setAuthorized(allowed);if(!allowed){setSnapshot(null);return;}const{data,error:readinessError}=await supabase.rpc('super_admin_product_publish_readiness_v1',{p_query:null,p_state:'all',p_limit:200,p_offset:0});if(readinessError)throw readinessError;setSnapshot(normalizeReadiness(data));}catch(nextError:any){setError(String(nextError?.message||'Ürün yayın hazırlığı yüklenemedi.'));setSnapshot(null);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function release(){if(busy||confirmation.trim()!==expectedPhrase||ready.length<1)return;setBusy(true);setError('');setResult(null);try{const ids=ready.map(item=>item.productId);if(ids.length>500)throw new Error('Tek işlemde en fazla 500 ürün yayınlanabilir.');const{data,error:bulkError}=await supabase.rpc('super_admin_bulk_review_products_v1',{p_product_ids:ids,p_approve:true,p_reason:'Super Admin toplu final yayın onayı. Yayın hazırlığı ve sahip onayı birlikte doğrulandı.'});if(bulkError)throw bulkError;const next=normalizeBulk(data);setResult(next);setDialogOpen(false);setConfirmation('');await load();await onReleased();}catch(nextError:any){setError(String(nextError?.message||'Toplu ürün yayını tamamlanamadı.'));}finally{setBusy(false);}}
 if(loading)return<div role="status" className="flex min-h-16 items-center gap-2 rounded-2xl border border-dashed px-4 text-sm text-gray-500"><Loader2 aria-hidden="true" className="h-4 w-4 animate-spin"/>Super Admin yayın hazırlığı doğrulanıyor…</div>;
 if(!authorized)return null;
 return <section className="rounded-2xl border border-brand-gold/30 bg-brand-gold/5 p-4" aria-labelledby="bulk-release-title">
  <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><ShieldCheck aria-hidden="true" className="h-5 w-5 text-brand-gold"/><h3 id="bulk-release-title" className="font-bold">Super Admin final yayın kontrolü</h3></div><p className="mt-1 max-w-3xl text-sm text-gray-600 dark:text-gray-300">Yalnız hazırlık kontrollerinin tamamı geçen ve halen inceleme durumunda olan ürünler toplu final onaya dahil edilir. İşlem ürün başına audit kaydı ve yayın kapılarını korur.</p></div><div className="flex flex-wrap items-center gap-2"><button type="button" onClick={()=>void load()} disabled={loading||busy} className="inline-flex min-h-11 items-center gap-2 rounded-xl border px-3 font-semibold disabled:opacity-50"><RefreshCw aria-hidden="true" className="h-4 w-4"/>Yenile</button><button type="button" onClick={()=>{setResult(null);setDialogOpen(true);}} disabled={!ready.length||busy} className="min-h-11 rounded-xl bg-brand-green px-4 font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">{ready.length?`${ready.length} hazır ürünü final onaya aç`:'Yayına hazır ürün yok'}</button></div></div>
  {snapshot?<div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label="Toplam" value={snapshot.summary.total}/><Metric label="Yayına hazır" value={ready.length}/><Metric label="Yayında" value={snapshot.summary.published}/><Metric label="Sahip onayı bekleyen" value={snapshot.summary.ownerApprovalRequired}/></div>:null}
  {error?<div role="alert" className="mt-3 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800 dark:border-red-900 dark:bg-red-950/30 dark:text-red-200">{error}</div>:null}
  {result?<div role="status" className={`mt-3 rounded-xl border p-3 text-sm ${result.failureCount?'border-amber-300 bg-amber-50 text-amber-950 dark:bg-amber-950/20 dark:text-amber-100':'border-green-300 bg-green-50 text-green-900 dark:bg-green-950/20 dark:text-green-100'}`}><div className="flex items-center gap-2 font-bold"><CheckCircle2 aria-hidden="true" className="h-4 w-4"/>{result.successCount} ürün yayınlandı{result.failureCount?`, ${result.failureCount} ürün güvenli şekilde yayınlanmadı.`:'.'}</div>{result.failureCount?<ul className="mt-2 list-disc pl-5">{result.results.filter(item=>!item.ok).slice(0,10).map(item=><li key={item.productId}>{item.name}: {item.error||'Yayın kapısı işlemi reddetti.'}</li>)}</ul>:null}</div>:null}
  {dialogOpen?<div className="fixed inset-0 z-[150] flex items-center justify-center bg-black/70 p-4"><div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="bulk-confirm-title" tabIndex={-1} className="w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl outline-none dark:bg-gray-900"><div className="flex items-center gap-2 text-amber-700 dark:text-amber-300"><AlertTriangle aria-hidden="true" className="h-6 w-6"/><h3 id="bulk-confirm-title" className="text-xl font-bold">Toplu final yayın onayı</h3></div><p className="mt-3 text-sm leading-6 text-gray-600 dark:text-gray-300"><strong>{ready.length}</strong> ürün müşteri kataloğunda yayınlanmak üzere Super Admin final onayına gönderilecek. Her ürün backend tarafından yeniden doğrulanır. Herhangi bir ürün yayın koşulunu artık karşılamıyorsa o ürün fail-closed kalır.</p><div className="mt-4 max-h-36 overflow-y-auto rounded-xl bg-gray-50 p-3 text-xs dark:bg-gray-800">{ready.slice(0,50).map(item=><div key={item.productId} className="truncate">{item.name}</div>)}</div><label className="mt-4 block"><span className="text-sm font-semibold">Onaylamak için <code>{expectedPhrase}</code> yazın</span><input autoFocus value={confirmation} onChange={event=>setConfirmation(event.target.value.slice(0,40))} className="mt-2 min-h-11 w-full rounded-xl border bg-transparent px-3"/></label><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>{setDialogOpen(false);setConfirmation('');}} disabled={busy} className="min-h-11 rounded-xl border px-4 font-semibold">İptal</button><button type="button" onClick={()=>void release()} disabled={busy||confirmation.trim()!==expectedPhrase} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-brand-green px-4 font-bold text-white disabled:opacity-50">{busy?<Loader2 aria-hidden="true" className="h-4 w-4 animate-spin"/>:null}Final onayı uygula</button></div></div></div>:null}
 </section>;
}
function Metric({label,value}:{label:string;value:number}){return<div className="rounded-xl border bg-white/70 p-3 dark:bg-gray-900/60"><div className="text-xs text-gray-500">{label}</div><div className="mt-1 text-xl font-bold">{value}</div></div>;}
