import { supabase } from '../lib/supabase';

export type SystemErrorRow={id:string;day:string;fingerprint:string;severity:'warning'|'error'|'fatal';source:string;message:string;stack:string|null;route:string|null;count:number;firstSeenAt:string;lastSeenAt:string;};
const SEVERITIES=new Set(['warning','error','fatal']);
function record(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function text(value:unknown,label:string,max:number,required=true){if(value==null||value===''){if(required)throw new Error(`${label} doğrulanamadı.`);return null;}if(typeof value!=='string')throw new Error(`${label} doğrulanamadı.`);const next=value.trim();if((required&&!next)||next.length>max||/[\u0000-\u001F\u007F]/.test(next))throw new Error(`${label} doğrulanamadı.`);return next||null;}
function date(value:unknown,label:string,dayOnly=false){const next=text(value,label,80,true) as string;if(dayOnly){if(!/^\d{4}-\d{2}-\d{2}$/.test(next))throw new Error(`${label} doğrulanamadı.`);}else if(Number.isNaN(Date.parse(next)))throw new Error(`${label} doğrulanamadı.`);return next;}
function integer(value:unknown,label:string,min=0){if(typeof value!=='number'||!Number.isSafeInteger(value)||value<min)throw new Error(`${label} doğrulanamadı.`);return value;}
function unwrap<T>(data:T|null,error:unknown):T{if(error)throw error;return data as T;}
function normalize(value:unknown,index:number):SystemErrorRow{if(!record(value))throw new Error(`${index+1}. hata kaydı doğrulanamadı.`);const severity=text(value.severity,'Hata seviyesi',20,true) as SystemErrorRow['severity'];if(!SEVERITIES.has(severity))throw new Error('Hata seviyesi doğrulanamadı.');return{id:text(value.id,'Hata kimliği',80,true) as string,day:date(value.day,'Hata günü',true),fingerprint:text(value.fingerprint,'Hata parmak izi',64,true) as string,severity,source:text(value.source,'Hata kaynağı',80,true) as string,message:text(value.message,'Hata mesajı',2000,true) as string,stack:text(value.stack,'Hata yığını',12000,false),route:text(value.route,'Hata rotası',500,false),count:integer(value.count,'Tekrar sayısı',1),firstSeenAt:date(value.firstSeenAt,'İlk görülme'),lastSeenAt:date(value.lastSeenAt,'Son görülme')};}
export async function listSystemErrors(from:string,to:string){date(from,'Başlangıç',true);date(to,'Bitiş',true);const{data,error}=await supabase.rpc('admin_list_system_errors_v1',{p_from:from,p_to:to});const raw=unwrap<unknown>(data,error);if(!Array.isArray(raw)||raw.length>10000)throw new Error('Sistem hata listesi doğrulanamadı.');return raw.map(normalize);}
export async function reportClientError(input:{source:string;message:string;stack?:string|null;route?:string|null;severity?:'warning'|'error'|'fatal';metadata?:Record<string,unknown>}){const source=text(input.source,'Hata kaynağı',80,true) as string;const message=text(input.message,'Hata mesajı',2000,true) as string;const stack=text(input.stack,'Hata yığını',12000,false);const route=text(input.route,'Hata rotası',500,false);const severity=input.severity||'error';if(!SEVERITIES.has(severity))throw new Error('Hata seviyesi doğrulanamadı.');const metadata=input.metadata&&record(input.metadata)?input.metadata:{};const{data,error}=await supabase.rpc('report_client_error_v1',{p_source:source,p_message:message,p_stack:stack,p_route:route,p_severity:severity,p_metadata:metadata});if(error)throw error;return data===true;}
export function systemErrorMessage(error:unknown,fallback='Sistem hata kayıtları yüklenemedi.'){const message=String((error as{message?:unknown}|null)?.message||'').trim();if(message.includes('super_admin_required'))return'Bu ekran yalnız Super Admin tarafından görüntülenebilir.';if(message.includes('invalid_error_date_range'))return'Hata raporu en fazla 90 günlük aralıkta görüntülenebilir.';return message||fallback;}
