import { supabase } from '../lib/supabase';

export type TransactionalEmailJobStatus='pending'|'processing'|'failed'|'sent'|'dead_letter';
export type TransactionalEmailJobKind='order_payment_receipt'|'event_payment_receipt';
export type TransactionalEmailJob={id:number;kind:TransactionalEmailJobKind;aggregateId:string;status:TransactionalEmailJobStatus;attempts:number;availableAt:string;providerMessageId:string|null;lastError:string|null;createdAt:string;sentAt:string|null;};
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const STATUSES=new Set<TransactionalEmailJobStatus>(['pending','processing','failed','sent','dead_letter']);
const KINDS=new Set<TransactionalEmailJobKind>(['order_payment_receipt','event_payment_receipt']);
function rec(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function text(value:unknown,label:string,max:number,nullable=false){if(value==null&&nullable)return null;if(typeof value!=='string')throw new Error(`${label} doğrulanamadı.`);const next=value.trim();if(!next||next.length>max||/[\u0000-\u001F\u007F]/.test(next))throw new Error(`${label} doğrulanamadı.`);return next;}
function integer(value:unknown,label:string,min=0){if(typeof value!=='number'||!Number.isSafeInteger(value)||value<min)throw new Error(`${label} doğrulanamadı.`);return value;}
function iso(value:unknown,label:string,nullable=false){if(value==null&&nullable)return null;const next=text(value,label,80,false) as string;if(Number.isNaN(Date.parse(next)))throw new Error(`${label} doğrulanamadı.`);return next;}
function normalizeJob(value:unknown):TransactionalEmailJob{if(!rec(value))throw new Error('E-posta kuyruk kaydı doğrulanamadı.');const kind=text(value.kind,'E-posta türü',80) as TransactionalEmailJobKind,status=text(value.status,'E-posta durumu',40) as TransactionalEmailJobStatus,aggregateId=text(value.aggregateId,'İşlem kimliği',80) as string;if(!KINDS.has(kind)||!STATUSES.has(status)||!UUID_RE.test(aggregateId))throw new Error('E-posta kuyruk kaydı sözleşmeye uymuyor.');return{id:integer(value.id,'Kuyruk kimliği',1),kind,aggregateId,status,attempts:integer(value.attempts,'Deneme sayısı'),availableAt:iso(value.availableAt,'Uygunluk zamanı') as string,providerMessageId:text(value.providerMessageId,'Sağlayıcı ileti kimliği',240,true) as string|null,lastError:text(value.lastError,'Son hata',500,true) as string|null,createdAt:iso(value.createdAt,'Oluşturulma zamanı') as string,sentAt:iso(value.sentAt,'Gönderilme zamanı',true) as string|null};}
export async function listTransactionalEmailJobs(status:TransactionalEmailJobStatus|null=null,limit=100):Promise<TransactionalEmailJob[]>{if(status&&!STATUSES.has(status))throw new Error('E-posta kuyruk filtresi geçersiz.');if(!Number.isSafeInteger(limit)||limit<1||limit>200)throw new Error('E-posta kuyruk liste limiti geçersiz.');const{data,error}=await supabase.rpc('super_admin_list_transactional_email_jobs_v1',{p_status:status,p_limit:limit});if(error)throw error;if(!rec(data)||data.ok!==true||!Array.isArray(data.items))throw new Error('E-posta kuyruğu yanıtı doğrulanamadı.');return data.items.map(normalizeJob);}
export async function retryTransactionalEmailJob(jobId:number){if(!Number.isSafeInteger(jobId)||jobId<1)throw new Error('E-posta kuyruk kimliği geçersiz.');const{data,error}=await supabase.rpc('super_admin_retry_transactional_email_job_v1',{p_job_id:jobId});if(error)throw error;if(data!==true)throw new Error('Bu e-posta işi yeniden kuyruğa alınamadı.');return true;}
