-- Schema drift closure, tables batch 2: private-schema customer and brand
-- records (account closure requests, brand secrets, contact messages, content
-- favourites, newsletter subscriptions, order gifts).
--
-- DDL generated by the database from its own catalogs via
-- scripts/generate-schema-ddl.sql, then md5-verified against that generated
-- text. Foreign keys are emitted after all CREATE TABLE statements so the file
-- is order-independent.
--
-- Applying is a no-op against the live project.

CREATE TABLE IF NOT EXISTS private.account_closure_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'requested'::text,
  reason text,
  admin_note text,
  requested_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  processed_at timestamp with time zone,
  processed_by uuid,
  CONSTRAINT account_closure_requests_pkey PRIMARY KEY (id),
  CONSTRAINT account_closure_requests_admin_note_check CHECK (((admin_note IS NULL) OR (char_length(admin_note) <= 4000))),
  CONSTRAINT account_closure_requests_reason_check CHECK (((reason IS NULL) OR (char_length(reason) <= 2000))),
  CONSTRAINT account_closure_requests_status_check CHECK ((status = ANY (ARRAY['requested'::text, 'processing'::text, 'ready_for_auth_deletion'::text, 'completed'::text, 'cancelled'::text, 'rejected'::text])))
);
ALTER TABLE private.account_closure_requests ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.brand_secrets (
  brand_slug text NOT NULL,
  legal_address jsonb NOT NULL DEFAULT '{}'::jsonb,
  tax_office text,
  tax_number text,
  operational_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT brand_secrets_pkey PRIMARY KEY (brand_slug),
  CONSTRAINT brand_secrets_legal_address_check CHECK ((jsonb_typeof(legal_address) = 'object'::text)),
  CONSTRAINT brand_secrets_operational_config_check CHECK ((jsonb_typeof(operational_config) = 'object'::text))
);
ALTER TABLE private.brand_secrets ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.brand_secrets FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.contact_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  subject text NOT NULL,
  message text NOT NULL,
  locale text NOT NULL DEFAULT 'tr'::text,
  source text NOT NULL DEFAULT 'web'::text,
  status text NOT NULL DEFAULT 'new'::text,
  assigned_to uuid,
  ip_hash text,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT contact_messages_pkey PRIMARY KEY (id),
  CONSTRAINT contact_messages_status_check CHECK ((status = ANY (ARRAY['new'::text, 'assigned'::text, 'in_progress'::text, 'resolved'::text, 'spam'::text])))
);
ALTER TABLE private.contact_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.contact_messages FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.content_favorites (
  user_id uuid NOT NULL,
  content_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT content_favorites_pkey PRIMARY KEY (user_id, content_id)
);
ALTER TABLE private.content_favorites ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.newsletter_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email_normalized text NOT NULL,
  user_id uuid,
  locale text NOT NULL DEFAULT 'tr'::text,
  status text NOT NULL DEFAULT 'pending'::text,
  consent_version text NOT NULL,
  consented_at timestamp with time zone NOT NULL,
  confirmed_at timestamp with time zone,
  unsubscribed_at timestamp with time zone,
  confirmation_token_hash text,
  unsubscribe_token_hash text,
  source text NOT NULL DEFAULT 'web'::text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT newsletter_subscriptions_email_normalized_key UNIQUE (email_normalized),
  CONSTRAINT newsletter_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT newsletter_subscriptions_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'active'::text, 'unsubscribed'::text, 'bounced'::text, 'complained'::text])))
);
ALTER TABLE private.newsletter_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.newsletter_subscriptions FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.order_gifts (
  order_id uuid NOT NULL,
  user_id uuid NOT NULL,
  recipient_name text NOT NULL,
  recipient_phone text,
  recipient_email text,
  gift_message text,
  sender_name text,
  hide_price boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  occasion text NOT NULL DEFAULT 'just_because'::text,
  presentation_style text NOT NULL DEFAULT 'oremar_gold'::text,
  card_title text,
  CONSTRAINT order_gifts_pkey PRIMARY KEY (order_id),
  CONSTRAINT order_gifts_card_title_check CHECK (((card_title IS NULL) OR (((char_length(btrim(card_title)) >= 2) AND (char_length(btrim(card_title)) <= 100)) AND (card_title !~ '[[:cntrl:]]'::text)))),
  CONSTRAINT order_gifts_occasion_check CHECK ((occasion = ANY (ARRAY['just_because'::text, 'birthday'::text, 'love'::text, 'thank_you'::text, 'celebration'::text, 'get_well'::text, 'new_home'::text, 'new_baby'::text]))),
  CONSTRAINT order_gifts_presentation_style_check CHECK ((presentation_style = ANY (ARRAY['oremar_gold'::text, 'mountain_warmth'::text, 'minimal_elegance'::text])))
);
ALTER TABLE private.order_gifts ENABLE ROW LEVEL SECURITY;

-- foreign keys (added after all tables exist)

ALTER TABLE private.account_closure_requests ADD CONSTRAINT account_closure_requests_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE private.account_closure_requests ADD CONSTRAINT account_closure_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE RESTRICT;
ALTER TABLE private.brand_secrets ADD CONSTRAINT brand_secrets_brand_slug_fkey FOREIGN KEY (brand_slug) REFERENCES brand_settings(slug) ON DELETE CASCADE;
ALTER TABLE private.contact_messages ADD CONSTRAINT contact_messages_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE private.contact_messages ADD CONSTRAINT contact_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE private.content_favorites ADD CONSTRAINT content_favorites_content_id_fkey FOREIGN KEY (content_id) REFERENCES content_entries(id) ON DELETE CASCADE;
ALTER TABLE private.content_favorites ADD CONSTRAINT content_favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE private.newsletter_subscriptions ADD CONSTRAINT newsletter_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE private.order_gifts ADD CONSTRAINT order_gifts_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
ALTER TABLE private.order_gifts ADD CONSTRAINT order_gifts_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
