-- Schema drift closure, RLS policies part 3: public schema, tables o-z
-- (45 policies). This completes the policy layer.
--
-- Policy DDL generated by the database from pg_policy, md5-verified against
-- that generated text (19a7b8377a2183aec51f0d137a5bb4c5). DROP POLICY IF
-- EXISTS guards are added for replayability and excluded from verification.
--
-- This batch carries the catalogue visibility chain, which is the single most
-- important rule in the storefront and is repeated consistently across
-- products, variants, inventory and images: a row is visible to anon only
-- when the product is published, active and not soft-deleted AND its producer
-- is active, verified and not soft-deleted. Suspending a producer therefore
-- removes their entire catalogue from public view in one step, with no
-- cascade update and no risk of an orphaned product staying visible.
--
-- Producer self-service is deliberately narrow. A producer may insert, update
-- or delete their own variants and images only while the product sits in
-- draft, review or rejected. Once it is published those paths close, which is
-- what forces edits through the change-request queue rather than letting a
-- published listing be altered silently.
--
-- reviews_insert_verified_purchase is worth reading closely: it requires the
-- review to belong to the caller, to start as pending, to be flagged as a
-- verified purchase, and to reference an order item the caller actually
-- bought on an order that reached delivered or completed. Combined with the
-- UNIQUE constraint on reviews.order_item_id, fake reviews are structurally
-- impossible rather than merely discouraged. reviews_authenticated_update
-- then only permits edits while the review is still pending, so a published
-- review cannot be rewritten after the fact.
--
-- Traceability follows the same discipline: batch rows, batch events and
-- certification links are public only once the batch is released, the parent
-- product is published and the producer is verified, and private batch events
-- stay invisible to anon entirely.
--
-- Applying is a no-op against the live project.

DROP POLICY IF EXISTS orders_authenticated_read ON public.orders;
CREATE POLICY orders_authenticated_read ON public.orders
  FOR SELECT
  TO authenticated
  USING (((user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT private.is_admin() AS is_admin)));

DROP POLICY IF EXISTS payment_records_read_own ON public.payment_records;
CREATE POLICY payment_records_read_own ON public.payment_records
  FOR SELECT
  TO authenticated
  USING ((user_id = ( SELECT auth.uid() AS uid)));

DROP POLICY IF EXISTS producer_applications_read_own ON public.producer_applications;
CREATE POLICY producer_applications_read_own ON public.producer_applications
  FOR SELECT
  TO authenticated
  USING ((applicant_user_id = ( SELECT auth.uid() AS uid)));

DROP POLICY IF EXISTS producer_location_change_select_own_v1 ON public.producer_location_change_requests;
CREATE POLICY producer_location_change_select_own_v1 ON public.producer_location_change_requests
  FOR SELECT
  TO authenticated
  USING (((requested_by = ( SELECT auth.uid() AS uid)) OR ( SELECT private.is_admin() AS is_admin)));

DROP POLICY IF EXISTS producers_authenticated_read ON public.producers;
CREATE POLICY producers_authenticated_read ON public.producers
  FOR SELECT
  TO authenticated
  USING ((((status = 'active'::text) AND (is_verified = true) AND (deleted_at IS NULL)) OR (owner_user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT private.is_admin() AS is_admin)));

DROP POLICY IF EXISTS producers_public_read ON public.producers;
CREATE POLICY producers_public_read ON public.producers
  FOR SELECT
  TO anon
  USING (((status = 'active'::text) AND (is_verified = true) AND (deleted_at IS NULL)));

DROP POLICY IF EXISTS product_availability_subscriptions_deny_direct ON public.product_availability_subscriptions;
CREATE POLICY product_availability_subscriptions_deny_direct ON public.product_availability_subscriptions
  FOR ALL
  TO PUBLIC
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS product_batch_certifications_authenticated_read ON public.product_batch_certifications;
CREATE POLICY product_batch_certifications_authenticated_read ON public.product_batch_certifications
  FOR SELECT
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM (product_batches batch
     LEFT JOIN producers producer ON ((producer.id = batch.producer_id)))
  WHERE ((batch.id = product_batch_certifications.batch_id) AND ((batch.status = 'released'::text) OR (producer.owner_user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT private.is_admin() AS is_admin))))));

DROP POLICY IF EXISTS product_batch_certifications_public_read ON public.product_batch_certifications;
CREATE POLICY product_batch_certifications_public_read ON public.product_batch_certifications
  FOR SELECT
  TO anon
  USING ((EXISTS ( SELECT 1
   FROM (product_batches batch
     JOIN product_certifications certification ON ((certification.id = product_batch_certifications.certification_id)))
  WHERE ((batch.id = product_batch_certifications.batch_id) AND (batch.status = 'released'::text) AND (certification.product_id = batch.product_id) AND (certification.status = 'valid'::text) AND ((certification.expires_at IS NULL) OR (certification.expires_at >= CURRENT_DATE))))));

DROP POLICY IF EXISTS product_batch_events_authenticated_read ON public.product_batch_events;
CREATE POLICY product_batch_events_authenticated_read ON public.product_batch_events
  FOR SELECT
  TO authenticated
  USING ((((visibility = 'public'::text) AND (EXISTS ( SELECT 1
   FROM product_batches batch
  WHERE ((batch.id = product_batch_events.batch_id) AND (batch.status = 'released'::text))))) OR (EXISTS ( SELECT 1
   FROM (product_batches batch
     JOIN producers producer ON ((producer.id = batch.producer_id)))
  WHERE ((batch.id = product_batch_events.batch_id) AND (producer.owner_user_id = ( SELECT auth.uid() AS uid))))) OR ( SELECT private.is_admin() AS is_admin)));

DROP POLICY IF EXISTS product_batch_events_public_read ON public.product_batch_events;
CREATE POLICY product_batch_events_public_read ON public.product_batch_events
  FOR SELECT
  TO anon
  USING (((visibility = 'public'::text) AND (EXISTS ( SELECT 1
   FROM product_batches batch
  WHERE ((batch.id = product_batch_events.batch_id) AND (batch.status = 'released'::text))))));

DROP POLICY IF EXISTS product_batches_authenticated_read ON public.product_batches;
CREATE POLICY product_batches_authenticated_read ON public.product_batches
  FOR SELECT
  TO authenticated
  USING (((status = 'released'::text) OR (EXISTS ( SELECT 1
   FROM producers producer
  WHERE ((producer.id = product_batches.producer_id) AND (producer.owner_user_id = ( SELECT auth.uid() AS uid))))) OR ( SELECT private.is_admin() AS is_admin)));

DROP POLICY IF EXISTS product_batches_public_read ON public.product_batches;
CREATE POLICY product_batches_public_read ON public.product_batches
  FOR SELECT
  TO anon
  USING (((status = 'released'::text) AND (EXISTS ( SELECT 1
   FROM (products product
     JOIN producers producer ON ((producer.id = product.producer_id)))
  WHERE ((product.id = product_batches.product_id) AND (product.status = 'published'::text) AND (product.is_active = true) AND (product.deleted_at IS NULL) AND (producer.id = product_batches.producer_id) AND (producer.status = 'active'::text) AND (producer.is_verified = true) AND (producer.deleted_at IS NULL))))));

DROP POLICY IF EXISTS product_certifications_public_read ON public.product_certifications;
CREATE POLICY product_certifications_public_read ON public.product_certifications
  FOR SELECT
  TO anon, authenticated
  USING (((status = 'valid'::text) AND (EXISTS ( SELECT 1
   FROM products p
  WHERE ((p.id = product_certifications.product_id) AND (p.status = 'published'::text) AND (p.is_active = true) AND (p.deleted_at IS NULL))))));

DROP POLICY IF EXISTS product_change_requests_authenticated_read ON public.product_change_requests;
CREATE POLICY product_change_requests_authenticated_read ON public.product_change_requests
  FOR SELECT
  TO authenticated
  USING ((( SELECT private.is_admin() AS is_admin) OR (EXISTS ( SELECT 1
   FROM producers producer
  WHERE ((producer.id = product_change_requests.producer_id) AND (producer.owner_user_id = ( SELECT auth.uid() AS uid)))))));

DROP POLICY IF EXISTS product_commerce_profiles_deny_direct ON public.product_commerce_profiles;
CREATE POLICY product_commerce_profiles_deny_direct ON public.product_commerce_profiles
  FOR ALL
  TO PUBLIC
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS product_images_authenticated_read ON public.product_images;
CREATE POLICY product_images_authenticated_read ON public.product_images
  FOR SELECT
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM (products product
     JOIN producers producer ON ((producer.id = product.producer_id)))
  WHERE ((product.id = product_images.product_id) AND (((product.status = 'published'::text) AND (product.is_active = true) AND (product.deleted_at IS NULL) AND (producer.status = 'active'::text) AND (producer.is_verified = true) AND (producer.deleted_at IS NULL)) OR (producer.owner_user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT private.is_admin() AS is_admin))))));

DROP POLICY IF EXISTS product_images_delete_own_producer ON public.product_images;
CREATE POLICY product_images_delete_own_producer ON public.product_images
  FOR DELETE
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM (products product
     JOIN producers producer ON ((producer.id = product.producer_id)))
  WHERE ((product.id = product_images.product_id) AND (product.status = ANY (ARRAY['draft'::text, 'review'::text, 'rejected'::text])) AND (producer.owner_user_id = ( SELECT auth.uid() AS uid))))));

DROP POLICY IF EXISTS product_images_insert_own_producer ON public.product_images;
CREATE POLICY product_images_insert_own_producer ON public.product_images
  FOR INSERT
  TO authenticated
  WITH CHECK ((EXISTS ( SELECT 1
   FROM (products product
     JOIN producers producer ON ((producer.id = product.producer_id)))
  WHERE ((product.id = product_images.product_id) AND (product.status = ANY (ARRAY['draft'::text, 'review'::text, 'rejected'::text])) AND (producer.owner_user_id = ( SELECT auth.uid() AS uid))))));

DROP POLICY IF EXISTS product_images_public_read ON public.product_images;
CREATE POLICY product_images_public_read ON public.product_images
  FOR SELECT
  TO anon
  USING ((EXISTS ( SELECT 1
   FROM (products product
     JOIN producers producer ON ((producer.id = product.producer_id)))
  WHERE ((product.id = product_images.product_id) AND (product.status = 'published'::text) AND (product.is_active = true) AND (product.deleted_at IS NULL) AND (producer.status = 'active'::text) AND (producer.is_verified = true) AND (producer.deleted_at IS NULL)))));

DROP POLICY IF EXISTS product_images_update_own_producer ON public.product_images;
CREATE POLICY product_images_update_own_producer ON public.product_images
  FOR UPDATE
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM (products product
     JOIN producers producer ON ((producer.id = product.producer_id)))
  WHERE ((product.id = product_images.product_id) AND (product.status = ANY (ARRAY['draft'::text, 'review'::text, 'rejected'::text])) AND (producer.owner_user_id = ( SELECT auth.uid() AS uid))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM (products product
     JOIN producers producer ON ((producer.id = product.producer_id)))
  WHERE ((product.id = product_images.product_id) AND (product.status = ANY (ARRAY['draft'::text, 'review'::text, 'rejected'::text])) AND (producer.owner_user_id = ( SELECT auth.uid() AS uid))))));

DROP POLICY IF EXISTS product_inventory_authenticated_read ON public.product_inventory;
CREATE POLICY product_inventory_authenticated_read ON public.product_inventory
  FOR SELECT
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM ((product_variants variant
     JOIN products product ON ((product.id = variant.product_id)))
     JOIN producers producer ON ((producer.id = product.producer_id)))
  WHERE ((variant.id = product_inventory.variant_id) AND (((variant.is_active = true) AND (product.status = 'published'::text) AND (product.is_active = true) AND (product.deleted_at IS NULL) AND (producer.status = 'active'::text) AND (producer.is_verified = true) AND (producer.deleted_at IS NULL)) OR (producer.owner_user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT private.is_admin() AS is_admin))))));

DROP POLICY IF EXISTS product_inventory_public_read ON public.product_inventory;
CREATE POLICY product_inventory_public_read ON public.product_inventory
  FOR SELECT
  TO anon
  USING ((EXISTS ( SELECT 1
   FROM ((product_variants variant
     JOIN products product ON ((product.id = variant.product_id)))
     JOIN producers producer ON ((producer.id = product.producer_id)))
  WHERE ((variant.id = product_inventory.variant_id) AND (variant.is_active = true) AND (product.status = 'published'::text) AND (product.is_active = true) AND (product.deleted_at IS NULL) AND (producer.status = 'active'::text) AND (producer.is_verified = true) AND (producer.deleted_at IS NULL)))));

DROP POLICY IF EXISTS product_provenance_public_read ON public.product_provenance;
CREATE POLICY product_provenance_public_read ON public.product_provenance
  FOR SELECT
  TO anon, authenticated
  USING ((EXISTS ( SELECT 1
   FROM products p
  WHERE ((p.id = product_provenance.product_id) AND (p.status = 'published'::text) AND (p.is_active = true) AND (p.deleted_at IS NULL)))));

DROP POLICY IF EXISTS product_sales_windows_deny_direct ON public.product_sales_windows;
CREATE POLICY product_sales_windows_deny_direct ON public.product_sales_windows
  FOR ALL
  TO PUBLIC
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS product_variants_authenticated_read ON public.product_variants;
CREATE POLICY product_variants_authenticated_read ON public.product_variants
  FOR SELECT
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM (products product
     JOIN producers producer ON ((producer.id = product.producer_id)))
  WHERE ((product.id = product_variants.product_id) AND (((product.status = 'published'::text) AND (product.is_active = true) AND (product.deleted_at IS NULL) AND (product_variants.is_active = true) AND (producer.status = 'active'::text) AND (producer.is_verified = true) AND (producer.deleted_at IS NULL)) OR (producer.owner_user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT private.is_admin() AS is_admin))))));

DROP POLICY IF EXISTS product_variants_delete_own_producer ON public.product_variants;
CREATE POLICY product_variants_delete_own_producer ON public.product_variants
  FOR DELETE
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM (products product
     JOIN producers producer ON ((producer.id = product.producer_id)))
  WHERE ((product.id = product_variants.product_id) AND (product.status = ANY (ARRAY['draft'::text, 'review'::text, 'rejected'::text])) AND (producer.owner_user_id = ( SELECT auth.uid() AS uid))))));

DROP POLICY IF EXISTS product_variants_insert_own_producer ON public.product_variants;
CREATE POLICY product_variants_insert_own_producer ON public.product_variants
  FOR INSERT
  TO authenticated
  WITH CHECK ((EXISTS ( SELECT 1
   FROM (products product
     JOIN producers producer ON ((producer.id = product.producer_id)))
  WHERE ((product.id = product_variants.product_id) AND (product.status = ANY (ARRAY['draft'::text, 'review'::text, 'rejected'::text])) AND (producer.owner_user_id = ( SELECT auth.uid() AS uid))))));

DROP POLICY IF EXISTS product_variants_public_read ON public.product_variants;
CREATE POLICY product_variants_public_read ON public.product_variants
  FOR SELECT
  TO anon
  USING (((is_active = true) AND (EXISTS ( SELECT 1
   FROM (products product
     JOIN producers producer ON ((producer.id = product.producer_id)))
  WHERE ((product.id = product_variants.product_id) AND (product.status = 'published'::text) AND (product.is_active = true) AND (product.deleted_at IS NULL) AND (producer.status = 'active'::text) AND (producer.is_verified = true) AND (producer.deleted_at IS NULL))))));

DROP POLICY IF EXISTS product_variants_update_own_producer ON public.product_variants;
CREATE POLICY product_variants_update_own_producer ON public.product_variants
  FOR UPDATE
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM (products product
     JOIN producers producer ON ((producer.id = product.producer_id)))
  WHERE ((product.id = product_variants.product_id) AND (product.status = ANY (ARRAY['draft'::text, 'review'::text, 'rejected'::text])) AND (producer.owner_user_id = ( SELECT auth.uid() AS uid))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM (products product
     JOIN producers producer ON ((producer.id = product.producer_id)))
  WHERE ((product.id = product_variants.product_id) AND (product.status = ANY (ARRAY['draft'::text, 'review'::text, 'rejected'::text])) AND (producer.owner_user_id = ( SELECT auth.uid() AS uid))))));

DROP POLICY IF EXISTS products_authenticated_read ON public.products;
CREATE POLICY products_authenticated_read ON public.products
  FOR SELECT
  TO authenticated
  USING ((((status = 'published'::text) AND (is_active = true) AND (deleted_at IS NULL) AND (EXISTS ( SELECT 1
   FROM producers producer
  WHERE ((producer.id = products.producer_id) AND (producer.status = 'active'::text) AND (producer.is_verified = true) AND (producer.deleted_at IS NULL))))) OR (EXISTS ( SELECT 1
   FROM producers producer
  WHERE ((producer.id = products.producer_id) AND (producer.owner_user_id = ( SELECT auth.uid() AS uid))))) OR ( SELECT private.is_admin() AS is_admin)));

DROP POLICY IF EXISTS products_public_read ON public.products;
CREATE POLICY products_public_read ON public.products
  FOR SELECT
  TO anon
  USING (((status = 'published'::text) AND (is_active = true) AND (deleted_at IS NULL) AND (EXISTS ( SELECT 1
   FROM producers producer
  WHERE ((producer.id = products.producer_id) AND (producer.status = 'active'::text) AND (producer.is_verified = true) AND (producer.deleted_at IS NULL))))));

DROP POLICY IF EXISTS profiles_authenticated_read ON public.profiles;
CREATE POLICY profiles_authenticated_read ON public.profiles
  FOR SELECT
  TO authenticated
  USING (((id = ( SELECT auth.uid() AS uid)) OR ( SELECT private.is_admin() AS is_admin)));

DROP POLICY IF EXISTS profiles_update_own ON public.profiles;
CREATE POLICY profiles_update_own ON public.profiles
  FOR UPDATE
  TO authenticated
  USING (((id = ( SELECT auth.uid() AS uid)) AND (status = 'active'::text) AND (deleted_at IS NULL)))
  WITH CHECK (((id = ( SELECT auth.uid() AS uid)) AND (status = 'active'::text) AND (deleted_at IS NULL)));

DROP POLICY IF EXISTS refunds_authenticated_read ON public.refunds;
CREATE POLICY refunds_authenticated_read ON public.refunds
  FOR SELECT
  TO authenticated
  USING (((EXISTS ( SELECT 1
   FROM orders customer_order
  WHERE ((customer_order.id = refunds.order_id) AND (customer_order.user_id = ( SELECT auth.uid() AS uid))))) OR ( SELECT private.is_admin() AS is_admin)));

DROP POLICY IF EXISTS return_items_read_own ON public.return_items;
CREATE POLICY return_items_read_own ON public.return_items
  FOR SELECT
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM return_requests customer_return
  WHERE ((customer_return.id = return_items.return_id) AND (customer_return.user_id = ( SELECT auth.uid() AS uid))))));

DROP POLICY IF EXISTS return_requests_read_own ON public.return_requests;
CREATE POLICY return_requests_read_own ON public.return_requests
  FOR SELECT
  TO authenticated
  USING ((user_id = ( SELECT auth.uid() AS uid)));

DROP POLICY IF EXISTS reviews_authenticated_read ON public.reviews;
CREATE POLICY reviews_authenticated_read ON public.reviews
  FOR SELECT
  TO authenticated
  USING (((status = 'published'::text) OR (user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT private.is_admin() AS is_admin)));

DROP POLICY IF EXISTS reviews_authenticated_update ON public.reviews;
CREATE POLICY reviews_authenticated_update ON public.reviews
  FOR UPDATE
  TO authenticated
  USING ((((user_id = ( SELECT auth.uid() AS uid)) AND (status = 'pending'::text)) OR ( SELECT private.is_admin() AS is_admin)))
  WITH CHECK ((((user_id = ( SELECT auth.uid() AS uid)) AND (status = 'pending'::text)) OR ( SELECT private.is_admin() AS is_admin)));

DROP POLICY IF EXISTS reviews_insert_verified_purchase ON public.reviews;
CREATE POLICY reviews_insert_verified_purchase ON public.reviews
  FOR INSERT
  TO authenticated
  WITH CHECK (((user_id = ( SELECT auth.uid() AS uid)) AND (status = 'pending'::text) AND (is_verified_purchase = true) AND (EXISTS ( SELECT 1
   FROM (order_items purchased_item
     JOIN orders customer_order ON ((customer_order.id = purchased_item.order_id)))
  WHERE ((purchased_item.id = reviews.order_item_id) AND (purchased_item.product_id = reviews.product_id) AND (customer_order.user_id = ( SELECT auth.uid() AS uid)) AND (customer_order.status = ANY (ARRAY['delivered'::text, 'completed'::text])))))));

DROP POLICY IF EXISTS reviews_public_read ON public.reviews;
CREATE POLICY reviews_public_read ON public.reviews
  FOR SELECT
  TO anon
  USING ((status = 'published'::text));

DROP POLICY IF EXISTS shipment_items_read_own ON public.shipment_items;
CREATE POLICY shipment_items_read_own ON public.shipment_items
  FOR SELECT
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM (shipments shipment
     JOIN orders customer_order ON ((customer_order.id = shipment.order_id)))
  WHERE ((shipment.id = shipment_items.shipment_id) AND (customer_order.user_id = ( SELECT auth.uid() AS uid))))));

DROP POLICY IF EXISTS shipments_read_own ON public.shipments;
CREATE POLICY shipments_read_own ON public.shipments
  FOR SELECT
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM orders customer_order
  WHERE ((customer_order.id = shipments.order_id) AND (customer_order.user_id = ( SELECT auth.uid() AS uid))))));

DROP POLICY IF EXISTS shipping_zone_countries_public_read ON public.shipping_zone_countries;
CREATE POLICY shipping_zone_countries_public_read ON public.shipping_zone_countries
  FOR SELECT
  TO anon, authenticated
  USING ((EXISTS ( SELECT 1
   FROM shipping_zones zone
  WHERE ((zone.id = shipping_zone_countries.zone_id) AND (zone.is_active = true)))));

DROP POLICY IF EXISTS shipping_zones_public_read ON public.shipping_zones;
CREATE POLICY shipping_zones_public_read ON public.shipping_zones
  FOR SELECT
  TO anon, authenticated
  USING ((is_active = true));
