-- Schema drift closure, tables batch 14: messaging, notifications and brand
-- settings (conversations, participants, messages, notifications,
-- brand_settings).
--
-- DDL generated by the database from its own catalogs via
-- scripts/generate-schema-ddl.sql, then md5-verified against that generated
-- text. Checked for constraint triggers: none in this batch. Foreign keys are
-- emitted after all CREATE TABLE statements so the file is order-independent.
--
-- Applying is a no-op against the live project.

CREATE TABLE IF NOT EXISTS public.brand_settings (
  slug text NOT NULL,
  brand_name text NOT NULL,
  legal_name text,
  default_currency text NOT NULL DEFAULT 'TRY'::text,
  default_locale text NOT NULL DEFAULT 'tr'::text,
  supported_locales text[] NOT NULL DEFAULT ARRAY['tr'::text, 'en'::text, 'de'::text, 'fr'::text, 'ku'::text, 'ar'::text],
  support_email text,
  support_phone text,
  order_prefix text NOT NULL DEFAULT 'GO'::text,
  maintenance_mode boolean NOT NULL DEFAULT false,
  public_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT brand_settings_pkey PRIMARY KEY (slug),
  CONSTRAINT brand_settings_default_currency_check CHECK ((default_currency ~ '^[A-Z]{3}$'::text)),
  CONSTRAINT brand_settings_default_locale_check CHECK ((default_locale = ANY (ARRAY['tr'::text, 'en'::text, 'de'::text, 'fr'::text, 'ku'::text, 'ar'::text]))),
  CONSTRAINT brand_settings_order_prefix_check CHECK ((order_prefix ~ '^[A-Z0-9]{2,8}$'::text)),
  CONSTRAINT brand_settings_public_config_check CHECK ((jsonb_typeof(public_config) = 'object'::text))
);
ALTER TABLE public.brand_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brand_settings FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.conversation_participants (
  conversation_id uuid NOT NULL,
  user_id uuid NOT NULL,
  participant_role text NOT NULL,
  last_read_at timestamp with time zone,
  joined_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT conversation_participants_pkey PRIMARY KEY (conversation_id, user_id),
  CONSTRAINT conversation_participants_participant_role_check CHECK ((participant_role = ANY (ARRAY['customer'::text, 'producer'::text, 'support'::text, 'admin'::text])))
);
ALTER TABLE public.conversation_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_participants FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_type text NOT NULL DEFAULT 'support'::text,
  order_id uuid,
  subject text,
  status text NOT NULL DEFAULT 'open'::text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  producer_id uuid,
  product_id uuid,
  context_key text,
  last_message_at timestamp with time zone,
  closed_at timestamp with time zone,
  closed_by uuid,
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_context_key_length_check CHECK (((context_key IS NULL) OR (char_length(context_key) <= 300))),
  CONSTRAINT conversations_conversation_type_check CHECK ((conversation_type = ANY (ARRAY['support'::text, 'producer'::text, 'order'::text]))),
  CONSTRAINT conversations_status_check CHECK ((status = ANY (ARRAY['open'::text, 'waiting_customer'::text, 'waiting_support'::text, 'closed'::text]))),
  CONSTRAINT conversations_subject_length_check CHECK (((subject IS NULL) OR (char_length(subject) <= 200)))
);
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  sender_user_id uuid NOT NULL,
  body text NOT NULL,
  attachment_paths text[] NOT NULL DEFAULT '{}'::text[],
  message_type text NOT NULL DEFAULT 'text'::text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  edited_at timestamp with time zone,
  deleted_at timestamp with time zone,
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_attachment_count_check CHECK ((COALESCE(array_length(attachment_paths, 1), 0) <= 5)),
  CONSTRAINT messages_body_check CHECK (((char_length(body) >= 1) AND (char_length(body) <= 5000))),
  CONSTRAINT messages_message_type_check CHECK ((message_type = ANY (ARRAY['text'::text, 'image'::text, 'file'::text, 'system'::text])))
);
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type text NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  action_url text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  expires_at timestamp with time zone,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_metadata_check CHECK ((jsonb_typeof(metadata) = 'object'::text)),
  CONSTRAINT notifications_type_check CHECK ((type = ANY (ARRAY['order'::text, 'payment'::text, 'shipment'::text, 'return'::text, 'campaign'::text, 'system'::text, 'producer'::text, 'message'::text, 'review'::text])))
);
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications FORCE ROW LEVEL SECURITY;

-- foreign keys (added after all tables exist)

ALTER TABLE public.conversation_participants ADD CONSTRAINT conversation_participants_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE;
ALTER TABLE public.conversation_participants ADD CONSTRAINT conversation_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.conversations ADD CONSTRAINT conversations_closed_by_fkey FOREIGN KEY (closed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.conversations ADD CONSTRAINT conversations_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.conversations ADD CONSTRAINT conversations_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL;
ALTER TABLE public.conversations ADD CONSTRAINT conversations_producer_id_fkey FOREIGN KEY (producer_id) REFERENCES producers(id) ON DELETE SET NULL;
ALTER TABLE public.conversations ADD CONSTRAINT conversations_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.messages ADD CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE;
ALTER TABLE public.messages ADD CONSTRAINT messages_sender_user_id_fkey FOREIGN KEY (sender_user_id) REFERENCES profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
