-- Schema drift closure, tables batch 11: producers, applications and
-- moderation (producers, producer applications, location change requests,
-- product change requests, reviews).
--
-- DDL generated by the database from its own catalogs via
-- scripts/generate-schema-ddl.sql, then md5-verified against that generated
-- text. Checked for constraint triggers: none in this batch. Foreign keys are
-- emitted after all CREATE TABLE statements so the file is order-independent.
--
-- Applying is a no-op against the live project.

CREATE TABLE IF NOT EXISTS public.producer_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  applicant_user_id uuid NOT NULL,
  brand_name text NOT NULL,
  public_name text NOT NULL,
  description text NOT NULL DEFAULT ''::text,
  production_location text NOT NULL,
  product_categories text[] NOT NULL DEFAULT '{}'::text[],
  status text NOT NULL DEFAULT 'draft'::text,
  submitted_at timestamp with time zone,
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  rejection_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  applicant_type text NOT NULL DEFAULT 'individual'::text,
  seller_classification text NOT NULL DEFAULT 'individual_non_merchant'::text,
  food_compliance_status text NOT NULL DEFAULT 'pending'::text,
  fulfillment_methods text[] NOT NULL DEFAULT ARRAY['cargo'::text],
  average_dispatch_days integer NOT NULL DEFAULT 3,
  cold_chain_capable boolean NOT NULL DEFAULT false,
  planned_products jsonb NOT NULL DEFAULT '[]'::jsonb,
  sourcing_models text[] NOT NULL DEFAULT ARRAY['own_production'::text],
  organic_claim_status text NOT NULL DEFAULT 'not_certified_no_claim'::text,
  organic_certifier_name text,
  organic_certificate_expires_on date,
  village_product_commitment boolean NOT NULL DEFAULT false,
  traceability_commitment boolean NOT NULL DEFAULT false,
  product_truth_commitment boolean NOT NULL DEFAULT false,
  production_practice_notes text NOT NULL DEFAULT ''::text,
  production_country_code text NOT NULL DEFAULT 'TR'::text,
  production_province text,
  production_district text,
  production_village text,
  production_village_is_custom boolean NOT NULL DEFAULT false,
  production_latitude numeric(9,6),
  production_longitude numeric(9,6),
  activity_types text[] NOT NULL DEFAULT '{}'::text[],
  CONSTRAINT producer_applications_pkey PRIMARY KEY (id),
  CONSTRAINT producer_applications_activity_types_check CHECK ((activity_types <@ ARRAY['beekeeping'::text, 'livestock'::text, 'dairy'::text, 'poultry'::text, 'field_farming'::text, 'fruit_growing'::text, 'vegetable_growing'::text, 'wild_harvest'::text, 'fishing'::text, 'food_processing'::text, 'beverage_production'::text, 'natural_materials'::text])),
  CONSTRAINT producer_applications_applicant_type_check CHECK ((applicant_type = ANY (ARRAY['individual'::text, 'business'::text]))),
  CONSTRAINT producer_applications_check CHECK ((((status = 'submitted'::text) AND (submitted_at IS NOT NULL)) OR (status <> 'submitted'::text))),
  CONSTRAINT producer_applications_coordinates_pair_check CHECK (((production_latitude IS NULL) = (production_longitude IS NULL))),
  CONSTRAINT producer_applications_country_code_check CHECK ((production_country_code ~ '^[A-Z]{2}$'::text)),
  CONSTRAINT producer_applications_dispatch_days_check CHECK (((average_dispatch_days >= 1) AND (average_dispatch_days <= 30))),
  CONSTRAINT producer_applications_food_compliance_status_check CHECK ((food_compliance_status = ANY (ARRAY['registered'::text, 'approved_facility'::text, 'primary_production_review'::text, 'pending'::text]))),
  CONSTRAINT producer_applications_fulfillment_methods_check CHECK ((((cardinality(fulfillment_methods) >= 1) AND (cardinality(fulfillment_methods) <= 3)) AND (fulfillment_methods <@ ARRAY['cargo'::text, 'local_delivery'::text, 'pickup'::text]))),
  CONSTRAINT producer_applications_latitude_check CHECK (((production_latitude IS NULL) OR ((production_latitude >= ('-90'::integer)::numeric) AND (production_latitude <= (90)::numeric)))),
  CONSTRAINT producer_applications_longitude_check CHECK (((production_longitude IS NULL) OR ((production_longitude >= ('-180'::integer)::numeric) AND (production_longitude <= (180)::numeric)))),
  CONSTRAINT producer_applications_organic_claim_status_check CHECK ((organic_claim_status = ANY (ARRAY['certified'::text, 'certification_in_progress'::text, 'not_certified_no_claim'::text]))),
  CONSTRAINT producer_applications_planned_products_check CHECK (((jsonb_typeof(planned_products) = 'array'::text) AND (jsonb_array_length(planned_products) <= 30))),
  CONSTRAINT producer_applications_seller_classification_check CHECK ((seller_classification = ANY (ARRAY['individual_non_merchant'::text, 'tax_exempt_artisan'::text, 'artisan'::text, 'sole_proprietor'::text, 'company'::text, 'cooperative'::text]))),
  CONSTRAINT producer_applications_sourcing_models_check CHECK ((((cardinality(sourcing_models) >= 1) AND (cardinality(sourcing_models) <= 5)) AND (sourcing_models <@ ARRAY['own_production'::text, 'family_production'::text, 'cooperative_production'::text, 'partner_farm'::text, 'authorized_local_supplier'::text]))),
  CONSTRAINT producer_applications_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'submitted'::text, 'under_review'::text, 'needs_information'::text, 'approved'::text, 'rejected'::text, 'withdrawn'::text])))
);
ALTER TABLE public.producer_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.producer_applications FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.producer_location_change_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  producer_id uuid NOT NULL,
  requested_by uuid NOT NULL,
  country_code text NOT NULL DEFAULT 'TR'::text,
  province text NOT NULL,
  district text NOT NULL,
  village text NOT NULL,
  village_is_custom boolean NOT NULL DEFAULT false,
  latitude numeric(9,6),
  longitude numeric(9,6),
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  review_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT producer_location_change_requests_pkey PRIMARY KEY (id),
  CONSTRAINT producer_location_change_requests_check CHECK (((latitude IS NULL) = (longitude IS NULL))),
  CONSTRAINT producer_location_change_requests_country_code_check CHECK ((country_code ~ '^[A-Z]{2}$'::text)),
  CONSTRAINT producer_location_change_requests_district_check CHECK (((char_length(btrim(district)) >= 2) AND (char_length(btrim(district)) <= 100))),
  CONSTRAINT producer_location_change_requests_latitude_check CHECK (((latitude IS NULL) OR ((latitude >= ('-90'::integer)::numeric) AND (latitude <= (90)::numeric)))),
  CONSTRAINT producer_location_change_requests_longitude_check CHECK (((longitude IS NULL) OR ((longitude >= ('-180'::integer)::numeric) AND (longitude <= (180)::numeric)))),
  CONSTRAINT producer_location_change_requests_province_check CHECK (((char_length(btrim(province)) >= 2) AND (char_length(btrim(province)) <= 100))),
  CONSTRAINT producer_location_change_requests_reason_check CHECK (((char_length(btrim(reason)) >= 20) AND (char_length(btrim(reason)) <= 2000))),
  CONSTRAINT producer_location_change_requests_review_reason_check CHECK (((review_reason IS NULL) OR (char_length(review_reason) <= 2000))),
  CONSTRAINT producer_location_change_requests_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'withdrawn'::text]))),
  CONSTRAINT producer_location_change_requests_village_check CHECK (((char_length(btrim(village)) >= 2) AND (char_length(btrim(village)) <= 160)))
);
ALTER TABLE public.producer_location_change_requests ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.producers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_user_id uuid,
  application_id uuid,
  slug text NOT NULL,
  display_name text NOT NULL,
  description text NOT NULL DEFAULT ''::text,
  story text NOT NULL DEFAULT ''::text,
  production_location text NOT NULL,
  latitude numeric(9,6),
  longitude numeric(9,6),
  logo_path text,
  cover_path text,
  translations jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'pending'::text,
  is_verified boolean NOT NULL DEFAULT false,
  commission_basis_points integer NOT NULL DEFAULT 0,
  rating_average numeric(3,2) NOT NULL DEFAULT 0,
  rating_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  deleted_at timestamp with time zone,
  producer_type text NOT NULL DEFAULT 'individual'::text,
  verified_at timestamp with time zone,
  verification_due_at timestamp with time zone,
  production_country_code text NOT NULL DEFAULT 'TR'::text,
  production_province text,
  production_district text,
  production_village text,
  production_village_is_custom boolean NOT NULL DEFAULT false,
  production_latitude numeric(9,6),
  production_longitude numeric(9,6),
  origin_verified boolean NOT NULL DEFAULT false,
  origin_verified_at timestamp with time zone,
  origin_verification_basis text,
  activity_types text[] NOT NULL DEFAULT '{}'::text[],
  approved_category_slugs text[] NOT NULL DEFAULT '{}'::text[],
  trust_badge_status text NOT NULL DEFAULT 'none'::text,
  trust_badge_granted_at timestamp with time zone,
  trust_badge_review_due_at timestamp with time zone,
  trust_badge_revoked_at timestamp with time zone,
  trust_badge_reason text,
  store_kind text NOT NULL DEFAULT 'independent'::text,
  storefront_tier text NOT NULL DEFAULT 'standard'::text,
  storefront_theme text NOT NULL DEFAULT 'heritage'::text,
  storefront_headline text,
  storefront_subheadline text,
  launch_audience_count bigint NOT NULL DEFAULT 0,
  launch_audience_label text NOT NULL DEFAULT 'Lansman topluluğu'::text,
  storefront_status text NOT NULL DEFAULT 'draft'::text,
  storefront_published_at timestamp with time zone,
  storefront_published_by uuid,
  storefront_contact_email text,
  storefront_contact_phone text,
  storefront_website_url text,
  storefront_address_line1 text,
  storefront_address_line2 text,
  storefront_postal_code text,
  storefront_city text,
  storefront_region text,
  storefront_country_code text,
  storefront_address_visibility text NOT NULL DEFAULT 'city_region'::text,
  storefront_business_name text,
  storefront_business_identity_type text,
  storefront_business_reference text,
  storefront_business_verified_at timestamp with time zone,
  storefront_setup_version smallint NOT NULL DEFAULT 1,
  store_number text NOT NULL,
  CONSTRAINT producers_application_id_key UNIQUE (application_id),
  CONSTRAINT producers_owner_user_id_key UNIQUE (owner_user_id),
  CONSTRAINT producers_slug_key UNIQUE (slug),
  CONSTRAINT producers_pkey PRIMARY KEY (id),
  CONSTRAINT producers_activity_types_check CHECK ((activity_types <@ ARRAY['beekeeping'::text, 'livestock'::text, 'dairy'::text, 'poultry'::text, 'field_farming'::text, 'fruit_growing'::text, 'vegetable_growing'::text, 'wild_harvest'::text, 'fishing'::text, 'food_processing'::text, 'beverage_production'::text, 'natural_materials'::text])),
  CONSTRAINT producers_commission_basis_points_check CHECK (((commission_basis_points >= 0) AND (commission_basis_points <= 10000))),
  CONSTRAINT producers_coordinates_pair_check CHECK (((production_latitude IS NULL) = (production_longitude IS NULL))),
  CONSTRAINT producers_country_code_check CHECK ((production_country_code ~ '^[A-Z]{2}$'::text)),
  CONSTRAINT producers_latitude_check CHECK (((production_latitude IS NULL) OR ((production_latitude >= ('-90'::integer)::numeric) AND (production_latitude <= (90)::numeric)))),
  CONSTRAINT producers_launch_audience_count_check CHECK (((launch_audience_count >= 0) AND (launch_audience_count <= 1000000000))),
  CONSTRAINT producers_launch_audience_label_check CHECK (((char_length(launch_audience_label) >= 2) AND (char_length(launch_audience_label) <= 60))),
  CONSTRAINT producers_longitude_check CHECK (((production_longitude IS NULL) OR ((production_longitude >= ('-180'::integer)::numeric) AND (production_longitude <= (180)::numeric)))),
  CONSTRAINT producers_official_store_shape_check CHECK (((store_kind <> 'official'::text) OR ((producer_type = 'brand'::text) AND (owner_user_id IS NULL) AND (application_id IS NULL)))),
  CONSTRAINT producers_origin_verification_basis_check CHECK (((origin_verification_basis IS NULL) OR (origin_verification_basis = ANY (ARRAY['application_review'::text, 'admin_confirmed_legacy_location'::text, 'admin_manual_verification'::text])))),
  CONSTRAINT producers_owner_required_for_individual_check CHECK (((producer_type <> 'individual'::text) OR (owner_user_id IS NOT NULL))),
  CONSTRAINT producers_producer_type_check CHECK ((producer_type = ANY (ARRAY['brand'::text, 'collective'::text, 'individual'::text]))),
  CONSTRAINT producers_rating_average_check CHECK (((rating_average >= (0)::numeric) AND (rating_average <= (5)::numeric))),
  CONSTRAINT producers_rating_count_check CHECK ((rating_count >= 0)),
  CONSTRAINT producers_slug_check CHECK ((slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'::text)),
  CONSTRAINT producers_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'active'::text, 'suspended'::text, 'rejected'::text, 'closed'::text]))),
  CONSTRAINT producers_store_kind_check CHECK ((store_kind = ANY (ARRAY['official'::text, 'independent'::text]))),
  CONSTRAINT producers_store_number_check CHECK ((store_number ~ '^GO-STORE-[0-9]{8}$'::text)),
  CONSTRAINT producers_storefront_address_visibility_check CHECK ((storefront_address_visibility = ANY (ARRAY['hidden'::text, 'city_region'::text, 'full'::text]))),
  CONSTRAINT producers_storefront_country_code_check CHECK (((storefront_country_code IS NULL) OR (storefront_country_code ~ '^[A-Z]{2}$'::text))),
  CONSTRAINT producers_storefront_headline_check CHECK (((storefront_headline IS NULL) OR ((char_length(storefront_headline) >= 2) AND (char_length(storefront_headline) <= 140)))),
  CONSTRAINT producers_storefront_setup_version_check CHECK (((storefront_setup_version >= 1) AND (storefront_setup_version <= 100))),
  CONSTRAINT producers_storefront_status_check CHECK ((storefront_status = ANY (ARRAY['draft'::text, 'published'::text]))),
  CONSTRAINT producers_storefront_subheadline_check CHECK (((storefront_subheadline IS NULL) OR ((char_length(storefront_subheadline) >= 2) AND (char_length(storefront_subheadline) <= 320)))),
  CONSTRAINT producers_storefront_theme_check CHECK ((storefront_theme = ANY (ARRAY['heritage'::text, 'emerald'::text, 'midnight'::text, 'ivory'::text]))),
  CONSTRAINT producers_storefront_tier_check CHECK ((storefront_tier = ANY (ARRAY['standard'::text, 'verified'::text, 'signature'::text]))),
  CONSTRAINT producers_translations_check CHECK ((jsonb_typeof(translations) = 'object'::text)),
  CONSTRAINT producers_trust_badge_reason_length_check CHECK (((trust_badge_reason IS NULL) OR (char_length(trust_badge_reason) <= 1000))),
  CONSTRAINT producers_trust_badge_status_check CHECK ((trust_badge_status = ANY (ARRAY['none'::text, 'active'::text, 'revoked'::text]))),
  CONSTRAINT producers_verification_window_check CHECK (((verification_due_at IS NULL) OR (verified_at IS NULL) OR (verification_due_at > verified_at)))
);
ALTER TABLE public.producers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.producers FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.product_change_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  producer_id uuid NOT NULL,
  requested_by uuid NOT NULL,
  proposed_payload jsonb NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  review_reason text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT product_change_requests_pkey PRIMARY KEY (id),
  CONSTRAINT product_change_requests_proposed_payload_check CHECK ((jsonb_typeof(proposed_payload) = 'object'::text)),
  CONSTRAINT product_change_requests_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'withdrawn'::text])))
);
ALTER TABLE public.product_change_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_change_requests FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  order_item_id uuid NOT NULL,
  rating smallint NOT NULL,
  title text,
  body text NOT NULL,
  media_paths text[] NOT NULL DEFAULT '{}'::text[],
  status text NOT NULL DEFAULT 'pending'::text,
  is_verified_purchase boolean NOT NULL DEFAULT true,
  merchant_reply text,
  merchant_replied_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  moderated_by uuid,
  moderated_at timestamp with time zone,
  moderation_reason text,
  merchant_reply_by uuid,
  edited_at timestamp with time zone,
  CONSTRAINT reviews_order_item_id_key UNIQUE (order_item_id),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_body_length_check CHECK (((char_length(body) >= 10) AND (char_length(body) <= 3000))),
  CONSTRAINT reviews_media_count_check CHECK ((COALESCE(array_length(media_paths, 1), 0) <= 5)),
  CONSTRAINT reviews_merchant_reply_length_check CHECK (((merchant_reply IS NULL) OR (char_length(merchant_reply) <= 2000))),
  CONSTRAINT reviews_moderation_reason_length_check CHECK (((moderation_reason IS NULL) OR (char_length(moderation_reason) <= 2000))),
  CONSTRAINT reviews_rating_check CHECK (((rating >= 1) AND (rating <= 5))),
  CONSTRAINT reviews_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'published'::text, 'rejected'::text, 'hidden'::text, 'withdrawn'::text]))),
  CONSTRAINT reviews_title_length_check CHECK (((title IS NULL) OR (char_length(title) <= 120)))
);
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews FORCE ROW LEVEL SECURITY;

-- foreign keys (added after all tables exist)

ALTER TABLE public.producer_applications ADD CONSTRAINT producer_applications_applicant_user_id_fkey FOREIGN KEY (applicant_user_id) REFERENCES profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.producer_applications ADD CONSTRAINT producer_applications_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.producer_location_change_requests ADD CONSTRAINT producer_location_change_requests_producer_id_fkey FOREIGN KEY (producer_id) REFERENCES producers(id) ON DELETE CASCADE;
ALTER TABLE public.producer_location_change_requests ADD CONSTRAINT producer_location_change_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES auth.users(id) ON DELETE RESTRICT;
ALTER TABLE public.producer_location_change_requests ADD CONSTRAINT producer_location_change_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.producers ADD CONSTRAINT producers_application_id_fkey FOREIGN KEY (application_id) REFERENCES producer_applications(id) ON DELETE SET NULL;
ALTER TABLE public.producers ADD CONSTRAINT producers_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.product_change_requests ADD CONSTRAINT product_change_requests_producer_id_fkey FOREIGN KEY (producer_id) REFERENCES producers(id) ON DELETE RESTRICT;
ALTER TABLE public.product_change_requests ADD CONSTRAINT product_change_requests_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT;
ALTER TABLE public.product_change_requests ADD CONSTRAINT product_change_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.product_change_requests ADD CONSTRAINT product_change_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.reviews ADD CONSTRAINT reviews_merchant_reply_by_fkey FOREIGN KEY (merchant_reply_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.reviews ADD CONSTRAINT reviews_moderated_by_fkey FOREIGN KEY (moderated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.reviews ADD CONSTRAINT reviews_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE RESTRICT;
ALTER TABLE public.reviews ADD CONSTRAINT reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.reviews ADD CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE RESTRICT;
