-- Schema drift closure, tables batch 13: shipping and returns
-- (shipping zones, zone country mapping, shipments, shipment items,
-- return requests, return items).
--
-- DDL generated by the database from its own catalogs via
-- scripts/generate-schema-ddl.sql, then md5-verified against that generated
-- text. Checked for constraint triggers: none in this batch. Foreign keys are
-- emitted after all CREATE TABLE statements so the file is order-independent.
--
-- Applying is a no-op against the live project.

CREATE TABLE IF NOT EXISTS public.return_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  return_id uuid NOT NULL,
  order_item_id uuid NOT NULL,
  quantity integer NOT NULL,
  condition text,
  evidence_paths text[] NOT NULL DEFAULT '{}'::text[],
  refund_amount_minor bigint,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT return_items_return_id_order_item_id_key UNIQUE (return_id, order_item_id),
  CONSTRAINT return_items_pkey PRIMARY KEY (id),
  CONSTRAINT return_items_condition_check CHECK (((condition IS NULL) OR (condition = ANY (ARRAY['unopened'::text, 'opened'::text, 'damaged'::text, 'spoiled'::text, 'other'::text])))),
  CONSTRAINT return_items_quantity_check CHECK ((quantity > 0)),
  CONSTRAINT return_items_refund_amount_minor_check CHECK (((refund_amount_minor IS NULL) OR (refund_amount_minor >= 0)))
);
ALTER TABLE public.return_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.return_items FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.return_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  return_number text NOT NULL,
  order_id uuid NOT NULL,
  user_id uuid NOT NULL,
  reason_code text NOT NULL,
  customer_message text NOT NULL,
  status text NOT NULL DEFAULT 'requested'::text,
  resolution text,
  requested_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  review_reason text,
  restock_approved boolean,
  received_at timestamp with time zone,
  closed_at timestamp with time zone,
  resolution_note text,
  CONSTRAINT return_requests_return_number_key UNIQUE (return_number),
  CONSTRAINT return_requests_pkey PRIMARY KEY (id),
  CONSTRAINT return_requests_reason_code_check CHECK ((reason_code = ANY (ARRAY['damaged'::text, 'wrong_item'::text, 'quality_issue'::text, 'missing_item'::text, 'changed_mind'::text, 'delivery_issue'::text, 'other'::text]))),
  CONSTRAINT return_requests_resolution_check CHECK (((resolution IS NULL) OR (resolution = ANY (ARRAY['refund'::text, 'replacement'::text, 'partial_refund'::text, 'store_credit'::text, 'none'::text])))),
  CONSTRAINT return_requests_resolution_note_length_check CHECK (((resolution_note IS NULL) OR (char_length(resolution_note) <= 3000))),
  CONSTRAINT return_requests_review_reason_length_check CHECK (((review_reason IS NULL) OR (char_length(review_reason) <= 3000))),
  CONSTRAINT return_requests_status_check CHECK ((status = ANY (ARRAY['requested'::text, 'under_review'::text, 'approved'::text, 'rejected'::text, 'in_transit'::text, 'received'::text, 'refunded'::text, 'closed'::text])))
);
ALTER TABLE public.return_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.return_requests FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.shipment_items (
  shipment_id uuid NOT NULL,
  order_item_id uuid NOT NULL,
  quantity integer NOT NULL,
  CONSTRAINT shipment_items_pkey PRIMARY KEY (shipment_id, order_item_id),
  CONSTRAINT shipment_items_quantity_check CHECK ((quantity > 0))
);
ALTER TABLE public.shipment_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipment_items FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.shipments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  carrier text,
  tracking_number text,
  tracking_url text,
  status text NOT NULL DEFAULT 'pending'::text,
  shipped_at timestamp with time zone,
  delivered_at timestamp with time zone,
  estimated_delivery_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT shipments_carrier_tracking_number_key UNIQUE (carrier, tracking_number),
  CONSTRAINT shipments_pkey PRIMARY KEY (id),
  CONSTRAINT shipments_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'label_created'::text, 'picked_up'::text, 'in_transit'::text, 'out_for_delivery'::text, 'delivered'::text, 'exception'::text, 'returned'::text])))
);
ALTER TABLE public.shipments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipments FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.shipping_zone_countries (
  zone_id uuid NOT NULL,
  country_code text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT shipping_zone_countries_pkey PRIMARY KEY (zone_id, country_code),
  CONSTRAINT shipping_zone_countries_code_check CHECK ((country_code ~ '^[A-Z]{2}$'::text))
);
ALTER TABLE public.shipping_zone_countries ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.shipping_zones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL,
  name text NOT NULL,
  currency text NOT NULL DEFAULT 'TRY'::text,
  is_active boolean NOT NULL DEFAULT false,
  is_rest_of_world boolean NOT NULL DEFAULT false,
  requires_manual_quote boolean NOT NULL DEFAULT false,
  base_fee_minor bigint,
  per_kg_fee_minor bigint,
  free_shipping_threshold_minor bigint,
  max_weight_grams integer,
  min_delivery_days integer,
  max_delivery_days integer,
  public_note text NOT NULL DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  supports_cold_chain boolean NOT NULL DEFAULT false,
  requires_product_export_approval boolean NOT NULL DEFAULT false,
  CONSTRAINT shipping_zones_code_key UNIQUE (code),
  CONSTRAINT shipping_zones_pkey PRIMARY KEY (id),
  CONSTRAINT shipping_zones_base_fee_check CHECK (((base_fee_minor IS NULL) OR (base_fee_minor >= 0))),
  CONSTRAINT shipping_zones_code_check CHECK ((code ~ '^[A-Z0-9_-]{2,40}$'::text)),
  CONSTRAINT shipping_zones_currency_check CHECK ((currency ~ '^[A-Z]{3}$'::text)),
  CONSTRAINT shipping_zones_delivery_days_check CHECK ((((min_delivery_days IS NULL) OR (min_delivery_days > 0)) AND ((max_delivery_days IS NULL) OR (max_delivery_days > 0)) AND ((min_delivery_days IS NULL) OR (max_delivery_days IS NULL) OR (max_delivery_days >= min_delivery_days)))),
  CONSTRAINT shipping_zones_free_threshold_check CHECK (((free_shipping_threshold_minor IS NULL) OR (free_shipping_threshold_minor >= 0))),
  CONSTRAINT shipping_zones_max_weight_check CHECK (((max_weight_grams IS NULL) OR (max_weight_grams > 0))),
  CONSTRAINT shipping_zones_per_kg_fee_check CHECK (((per_kg_fee_minor IS NULL) OR (per_kg_fee_minor >= 0))),
  CONSTRAINT shipping_zones_public_note_length_check CHECK ((char_length(public_note) <= 1000))
);
ALTER TABLE public.shipping_zones ENABLE ROW LEVEL SECURITY;

-- foreign keys (added after all tables exist)

ALTER TABLE public.return_items ADD CONSTRAINT return_items_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE RESTRICT;
ALTER TABLE public.return_items ADD CONSTRAINT return_items_return_id_fkey FOREIGN KEY (return_id) REFERENCES return_requests(id) ON DELETE CASCADE;
ALTER TABLE public.return_requests ADD CONSTRAINT return_requests_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT;
ALTER TABLE public.return_requests ADD CONSTRAINT return_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.return_requests ADD CONSTRAINT return_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.shipment_items ADD CONSTRAINT shipment_items_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE RESTRICT;
ALTER TABLE public.shipment_items ADD CONSTRAINT shipment_items_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES shipments(id) ON DELETE CASCADE;
ALTER TABLE public.shipments ADD CONSTRAINT shipments_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT;
ALTER TABLE public.shipping_zone_countries ADD CONSTRAINT shipping_zone_countries_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES shipping_zones(id) ON DELETE CASCADE;
