-- Schema drift closure, tables batch 7: the remaining private-schema tables
-- (event reservation finance, inventory movements, product export country
-- rules, promotion redemptions, review helpful votes).
--
-- This completes the private schema. DDL generated by the database from its
-- own catalogs via scripts/generate-schema-ddl.sql, then md5-verified against
-- that generated text. Foreign keys are emitted after all CREATE TABLE
-- statements so the file is order-independent.
--
-- Applying is a no-op against the live project.

CREATE TABLE IF NOT EXISTS private.event_reservation_finance (
  reservation_id uuid NOT NULL,
  event_id uuid NOT NULL,
  user_id uuid NOT NULL,
  producer_id uuid,
  ticket_price_minor bigint NOT NULL,
  guest_count integer NOT NULL,
  total_minor bigint NOT NULL,
  currency text NOT NULL,
  commission_basis_points_snapshot integer NOT NULL,
  platform_fee_minor bigint NOT NULL,
  producer_net_minor bigint NOT NULL,
  payment_status text NOT NULL,
  payment_expires_at timestamp with time zone,
  paid_at timestamp with time zone,
  provider text,
  provider_reference text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  refund_reference text,
  refund_transaction_id text,
  refunded_at timestamp with time zone,
  refund_attempt_count integer NOT NULL DEFAULT 0,
  last_refund_error text,
  last_refund_attempt_at timestamp with time zone,
  CONSTRAINT event_reservation_finance_pkey PRIMARY KEY (reservation_id),
  CONSTRAINT event_reservation_finance_commission_basis_points_snapsho_check CHECK (((commission_basis_points_snapshot >= 0) AND (commission_basis_points_snapshot <= 10000))),
  CONSTRAINT event_reservation_finance_currency_check CHECK ((currency ~ '^[A-Z]{3}$'::text)),
  CONSTRAINT event_reservation_finance_guest_count_check CHECK (((guest_count >= 1) AND (guest_count <= 20))),
  CONSTRAINT event_reservation_finance_paid_consistency CHECK ((((payment_status = 'paid'::text) AND (paid_at IS NOT NULL)) OR (payment_status <> 'paid'::text))),
  CONSTRAINT event_reservation_finance_payment_status_check CHECK ((payment_status = ANY (ARRAY['not_required'::text, 'pending'::text, 'authorized'::text, 'paid'::text, 'failed'::text, 'expired'::text, 'refund_required'::text, 'refunded'::text]))),
  CONSTRAINT event_reservation_finance_platform_fee_minor_check CHECK ((platform_fee_minor >= 0)),
  CONSTRAINT event_reservation_finance_producer_net_minor_check CHECK ((producer_net_minor >= 0)),
  CONSTRAINT event_reservation_finance_refund_attempt_count_check CHECK ((refund_attempt_count >= 0)),
  CONSTRAINT event_reservation_finance_refund_consistency CHECK ((((payment_status = 'refunded'::text) AND (refunded_at IS NOT NULL) AND (refund_transaction_id IS NOT NULL)) OR (payment_status <> 'refunded'::text))),
  CONSTRAINT event_reservation_finance_split_check CHECK (((platform_fee_minor + producer_net_minor) = total_minor)),
  CONSTRAINT event_reservation_finance_ticket_price_minor_check CHECK ((ticket_price_minor >= 0)),
  CONSTRAINT event_reservation_finance_total_check CHECK ((total_minor = (ticket_price_minor * guest_count))),
  CONSTRAINT event_reservation_finance_total_minor_check CHECK ((total_minor >= 0))
);
ALTER TABLE private.event_reservation_finance ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.inventory_movements (
  id bigint GENERATED ALWAYS AS IDENTITY,
  variant_id uuid NOT NULL,
  movement_type text NOT NULL,
  quantity_delta integer NOT NULL,
  reference_type text,
  reference_id uuid,
  reason text,
  idempotency_key text,
  actor_user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT inventory_movements_idempotency_key_key UNIQUE (idempotency_key),
  CONSTRAINT inventory_movements_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_movements_movement_type_check CHECK ((movement_type = ANY (ARRAY['opening'::text, 'purchase'::text, 'reservation'::text, 'release'::text, 'sale'::text, 'return'::text, 'adjustment'::text, 'damage'::text]))),
  CONSTRAINT inventory_movements_quantity_delta_check CHECK ((quantity_delta <> 0))
);
ALTER TABLE private.inventory_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.inventory_movements FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.product_export_country_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid,
  category_id uuid,
  country_code text NOT NULL,
  decision text NOT NULL,
  public_note text NOT NULL DEFAULT ''::text,
  internal_note text NOT NULL DEFAULT ''::text,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT product_export_country_rules_pkey PRIMARY KEY (id),
  CONSTRAINT product_export_country_rules_check CHECK (((((product_id IS NOT NULL))::integer + ((category_id IS NOT NULL))::integer) = 1)),
  CONSTRAINT product_export_country_rules_country_code_check CHECK ((country_code ~ '^[A-Z]{2}$'::text)),
  CONSTRAINT product_export_country_rules_decision_check CHECK ((decision = ANY (ARRAY['allowed'::text, 'manual_review'::text, 'restricted'::text, 'prohibited'::text]))),
  CONSTRAINT product_export_country_rules_internal_note_check CHECK ((char_length(internal_note) <= 2000)),
  CONSTRAINT product_export_country_rules_public_note_check CHECK ((char_length(public_note) <= 500))
);
ALTER TABLE private.product_export_country_rules ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.promotion_redemptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid NOT NULL,
  coupon_id uuid,
  user_id uuid NOT NULL,
  order_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'reserved'::text,
  product_discount_minor bigint NOT NULL DEFAULT 0,
  shipping_discount_minor bigint NOT NULL DEFAULT 0,
  total_discount_minor bigint NOT NULL,
  reserved_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  expires_at timestamp with time zone,
  consumed_at timestamp with time zone,
  released_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT promotion_redemptions_order_id_key UNIQUE (order_id),
  CONSTRAINT promotion_redemptions_pkey PRIMARY KEY (id),
  CONSTRAINT promotion_redemptions_check CHECK ((total_discount_minor = (product_discount_minor + shipping_discount_minor))),
  CONSTRAINT promotion_redemptions_product_discount_minor_check CHECK ((product_discount_minor >= 0)),
  CONSTRAINT promotion_redemptions_shipping_discount_minor_check CHECK ((shipping_discount_minor >= 0)),
  CONSTRAINT promotion_redemptions_status_check CHECK ((status = ANY (ARRAY['reserved'::text, 'consumed'::text, 'released'::text]))),
  CONSTRAINT promotion_redemptions_total_discount_minor_check CHECK ((total_discount_minor >= 0))
);
ALTER TABLE private.promotion_redemptions ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.review_helpful_votes (
  review_id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT review_helpful_votes_pkey PRIMARY KEY (review_id, user_id)
);
ALTER TABLE private.review_helpful_votes ENABLE ROW LEVEL SECURITY;

-- foreign keys (added after all tables exist)

ALTER TABLE private.event_reservation_finance ADD CONSTRAINT event_reservation_finance_event_id_fkey FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE RESTRICT;
ALTER TABLE private.event_reservation_finance ADD CONSTRAINT event_reservation_finance_producer_id_fkey FOREIGN KEY (producer_id) REFERENCES producers(id) ON DELETE RESTRICT;
ALTER TABLE private.event_reservation_finance ADD CONSTRAINT event_reservation_finance_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES event_reservations(id) ON DELETE RESTRICT;
ALTER TABLE private.event_reservation_finance ADD CONSTRAINT event_reservation_finance_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE RESTRICT;
ALTER TABLE private.inventory_movements ADD CONSTRAINT inventory_movements_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE private.inventory_movements ADD CONSTRAINT inventory_movements_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE RESTRICT;
ALTER TABLE private.product_export_country_rules ADD CONSTRAINT product_export_country_rules_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE;
ALTER TABLE private.product_export_country_rules ADD CONSTRAINT product_export_country_rules_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE private.product_export_country_rules ADD CONSTRAINT product_export_country_rules_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE private.product_export_country_rules ADD CONSTRAINT product_export_country_rules_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE private.promotion_redemptions ADD CONSTRAINT promotion_redemptions_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE RESTRICT;
ALTER TABLE private.promotion_redemptions ADD CONSTRAINT promotion_redemptions_coupon_id_fkey FOREIGN KEY (coupon_id) REFERENCES coupons(id) ON DELETE RESTRICT;
ALTER TABLE private.promotion_redemptions ADD CONSTRAINT promotion_redemptions_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT;
ALTER TABLE private.promotion_redemptions ADD CONSTRAINT promotion_redemptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE RESTRICT;
ALTER TABLE private.review_helpful_votes ADD CONSTRAINT review_helpful_votes_review_id_fkey FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE;
ALTER TABLE private.review_helpful_votes ADD CONSTRAINT review_helpful_votes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
