-- Product info cleanup v1: internal compliance notes in features/tags are replaced by
-- customer-facing, generically true wording. No prices, stock, weights, certificates or nutrition values.
update public.products set features = '["Bahar çiçeklerinden elde edilen bal","Kristalleşme doğal bir süreçtir; bozulma belirtisi değildir","Kristalleşen bal ılık su banyosunda yavaşça akışkanlaşır"]'::jsonb where id = 'aaabee02-be61-45ca-9007-bba163cf77c0'::uuid and legacy_id = '102';
update public.products set features = '["Koyu renkli, meşe ve orman florası karakteri","Hasat bölgesi ve üretici bilgisi ürün kaydında yer alır"]'::jsonb, tags = array['Koyu Renk', 'Meşe Balı']::text[] where id = 'c17f9a67-5560-449c-a8f2-a372f1625f88'::uuid and legacy_id = '103';
update public.products set features = '["Sütten kesilmiş oğlak eti","Kesim ve parçalama seçeneği siparişte belirlenir","Soğuk zincirde saklanmalı, iyice pişirilerek tüketilmelidir"]'::jsonb where id = 'b40c1609-2274-4dc8-9716-377a0f027dfa'::uuid and legacy_id = '303';
update public.products set features = '["Cam damacanada sunulan kaynak suyu","19 litrelik cam damacana","Çay, kahve ve yemek yapımına uygundur"]'::jsonb, tags = array['19L Cam', 'Kaynak Suyu']::text[] where id = 'dc2c2378-ad63-4bbe-9eab-882165939e54'::uuid and legacy_id = '401';
update public.products set features = '["Geleneksel ısı tutma ve pres taşı","Isınma süresi kullanım koşullarına göre değişir","Tıbbi amaçla sunulmaz; ısıtıldığında beze sarılarak kullanılmalıdır"]'::jsonb where id = 'b510b051-a5d7-47cd-9795-878573dd27f8'::uuid and legacy_id = '402';
update public.products set features = '["Geleneksel yöntemle hazırlanan ekşi mayalı tarhana","Buğday unu ve süt içerir","Serin ve kuru bir yerde, ambalajı kapalı saklanmalıdır"]'::jsonb, tags = array['Geleneksel Tarhana', 'Ekşi Mayalı']::text[] where id = '611e8fdc-6775-4312-9c6e-3c3769ebc731'::uuid and legacy_id = '501';
update public.products set features = '["Geleneksel dut hasadı ve kurutma","Çerez olarak veya tariflerde kullanılabilir","Serin ve kuru bir yerde, ağzı kapalı saklanmalıdır"]'::jsonb where id = 'e9941a2c-b441-496c-ae09-6564cba5d3a4'::uuid and legacy_id = '502';
update public.products set features = '["Odun ateşinde geleneksel yöntemle kaynatılır","Kahvaltıda tahinle veya tatlılarda kullanılabilir","Serin bir yerde, kapağı kapalı saklanmalıdır"]'::jsonb, tags = array['Geleneksel Pekmez', 'Odun Ateşi']::text[] where id = '9fa01408-b682-4600-a19b-dc7126519c1e'::uuid and legacy_id = '503';
update public.products set features = '["Tandır ve odun isi aromalı kuru üzüm","Çerez olarak veya pilav, hoşaf ve keklerde kullanılabilir","Serin, kuru ve kokusuz bir yerde saklanmalıdır"]'::jsonb where id = '1b401442-df5f-4b88-a578-100e7bcf9242'::uuid and legacy_id = '506';
update public.products set features = '["Serin ortamda kurutulmuş dağ kekiği","Baharat, demleme veya marinasyon için uygundur","Aroması güçlüdür; az miktarla başlanmalıdır"]'::jsonb where id = 'adfee0a8-15f5-4253-9881-870e89536a2a'::uuid and legacy_id = '507';
update public.products set features = '["Yabani doğa hasadı","Mevsimsel ve sınırlı hasat","Çiğ tüketilmez; iyice pişirilmelidir"]'::jsonb, tags = array['Mevsimsel Hasat', 'Yabani Mantar']::text[] where id = '787138cf-3248-48e1-a48f-da6ef43aacba'::uuid and legacy_id = '601';
update public.products set features = '["Yabani kızılcıktan geleneksel şurup","Suyla seyreltilerek içilir","Hediyelik cam şişe seti"]'::jsonb, tags = array['Kızılcık Şurubu', 'Cam Şişe']::text[] where id = '1780065a-28ac-4261-a2ef-13c39d299195'::uuid and legacy_id = '602';
update public.products set features = '["Kristal kaya tuzu","Blok veya öğütmelik seçenekleri ürün varyantına göre sunulur","Turşu, salamura ve sofra kullanımına uygundur"]'::jsonb, tags = array['Kristal Tuz', 'Rafine Edilmemiş']::text[] where id = '060ab141-6901-4364-9bac-8d47382ab9aa'::uuid and legacy_id = '603';
update public.products set features = '["Mevsimlik hasat iç yağ","Kavurma ve sıcak yemekler için hayvansal yağ","Buzdolabında saklanmalıdır"]'::jsonb where id = 'd810734a-c147-4fa5-a7b6-7182ff5c8ed1'::uuid and legacy_id = '701';
update public.products set features = '["Geleneksel kurutulmuş yoğurt (kurut)","Süt ve tuz içerir","Sulandırılarak mantı, erişte ve çorbalarda kullanılır"]'::jsonb where id = '61bdf13e-fb75-4033-b584-3dc43de678d1'::uuid and legacy_id = '703';
update public.products set features = '["El işçiliği ahşap kaşık ve yayık tokmağı","Üretici beyanına göre vernik veya sanayi boyası kullanılmamıştır","Elde yıkanmalı, bulaşık makinesine konulmamalıdır"]'::jsonb where id = 'feb5bc4c-e9f6-4d79-bbc9-e1afe4b9af2d'::uuid and legacy_id = '704';
update public.products set tags = array['Karadut Suyu', 'Şeker İlavesiz']::text[] where id = '56a24565-7268-49db-9715-2ba08035d265'::uuid and legacy_id = '804';
update public.products set features = '["Dağ kekiğinin damıtılmasıyla elde edilen aromatik su","Suyla seyreltilerek, birkaç damla kullanılır","Tıbbi veya antiseptik bir ürün olarak sunulmaz"]'::jsonb, tags = array['Distile Ürün', 'Dağ Kekiği']::text[] where id = 'ae324353-9844-4b34-a71e-491942b4182d'::uuid and legacy_id = '807';
