-- Schema drift closure, tables batch 4: payment core (saved payment methods,
-- payment intents, provider webhook events, per-item marketplace splits,
-- provider customer references).
--
-- DDL generated by the database from its own catalogs via
-- scripts/generate-schema-ddl.sql, then md5-verified against that generated
-- text. Foreign keys are emitted after all CREATE TABLE statements so the file
-- is order-independent.
--
-- Applying is a no-op against the live project.

CREATE TABLE IF NOT EXISTS private.customer_payment_methods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  provider text NOT NULL,
  provider_payment_method_ref text NOT NULL,
  brand text NOT NULL,
  last4 text NOT NULL,
  exp_month smallint,
  exp_year smallint,
  billing_name text,
  is_default boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'active'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  nickname text,
  billing_country_code text,
  billing_postal_code text,
  storage_consent_version text,
  storage_consented_at timestamp with time zone,
  storage_consent_source text,
  CONSTRAINT customer_payment_methods_user_id_provider_provider_payment__key UNIQUE (user_id, provider, provider_payment_method_ref),
  CONSTRAINT customer_payment_methods_pkey PRIMARY KEY (id),
  CONSTRAINT customer_payment_methods_billing_country_check CHECK (((billing_country_code IS NULL) OR (billing_country_code ~ '^[A-Z]{2}$'::text))),
  CONSTRAINT customer_payment_methods_billing_name_check CHECK (((billing_name IS NULL) OR (((char_length(btrim(billing_name)) >= 2) AND (char_length(btrim(billing_name)) <= 120)) AND (billing_name !~ '[[:cntrl:]]'::text)))),
  CONSTRAINT customer_payment_methods_billing_postal_check CHECK (((billing_postal_code IS NULL) OR (((char_length(btrim(billing_postal_code)) >= 1) AND (char_length(btrim(billing_postal_code)) <= 30)) AND (billing_postal_code !~ '[[:cntrl:]]'::text)))),
  CONSTRAINT customer_payment_methods_brand_check CHECK ((((char_length(brand) >= 1) AND (char_length(brand) <= 40)) AND (brand !~ '[[:cntrl:]]'::text))),
  CONSTRAINT customer_payment_methods_exp_month_check CHECK (((exp_month IS NULL) OR ((exp_month >= 1) AND (exp_month <= 12)))),
  CONSTRAINT customer_payment_methods_exp_year_check CHECK (((exp_year IS NULL) OR ((exp_year >= 2024) AND (exp_year <= 2200)))),
  CONSTRAINT customer_payment_methods_last4_check CHECK ((last4 ~ '^[0-9]{4}$'::text)),
  CONSTRAINT customer_payment_methods_nickname_check CHECK (((nickname IS NULL) OR (((char_length(btrim(nickname)) >= 1) AND (char_length(btrim(nickname)) <= 40)) AND (nickname !~ '[[:cntrl:]]'::text)))),
  CONSTRAINT customer_payment_methods_provider_check CHECK ((provider ~ '^[a-z0-9_-]{2,40}$'::text)),
  CONSTRAINT customer_payment_methods_provider_ref_check CHECK ((((char_length(provider_payment_method_ref) >= 3) AND (char_length(provider_payment_method_ref) <= 255)) AND (provider_payment_method_ref !~ '[[:cntrl:][:space:]]'::text))),
  CONSTRAINT customer_payment_methods_status_check CHECK ((status = ANY (ARRAY['active'::text, 'expired'::text, 'removed'::text]))),
  CONSTRAINT customer_payment_methods_storage_consent_consistency CHECK ((((storage_consent_version IS NULL) AND (storage_consented_at IS NULL) AND (storage_consent_source IS NULL)) OR ((storage_consent_version IS NOT NULL) AND (storage_consented_at IS NOT NULL) AND (storage_consent_source IS NOT NULL))))
);
ALTER TABLE private.customer_payment_methods ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.payment_events (
  id bigint GENERATED ALWAYS AS IDENTITY,
  provider text NOT NULL,
  provider_event_id text NOT NULL,
  payment_id uuid,
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  signature_verified boolean NOT NULL DEFAULT false,
  processing_status text NOT NULL DEFAULT 'pending'::text,
  processing_error text,
  received_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  processed_at timestamp with time zone,
  CONSTRAINT payment_events_provider_provider_event_id_key UNIQUE (provider, provider_event_id),
  CONSTRAINT payment_events_pkey PRIMARY KEY (id),
  CONSTRAINT payment_events_payload_check CHECK ((jsonb_typeof(payload) = 'object'::text)),
  CONSTRAINT payment_events_processing_status_check CHECK ((processing_status = ANY (ARRAY['pending'::text, 'processed'::text, 'ignored'::text, 'failed'::text])))
);
ALTER TABLE private.payment_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.payment_events FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.payment_intents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  order_id uuid,
  payment_method_id uuid,
  provider text NOT NULL,
  idempotency_key text NOT NULL,
  amount_minor bigint NOT NULL,
  currency text NOT NULL,
  status text NOT NULL DEFAULT 'created'::text,
  provider_reference text,
  attempt_count integer NOT NULL DEFAULT 0,
  failure_code text,
  failure_message text,
  provider_result jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  completed_at timestamp with time zone,
  subject_type text NOT NULL DEFAULT 'order'::text,
  subject_id uuid NOT NULL,
  payment_flow text NOT NULL DEFAULT 'saved_card'::text,
  provider_session_token text,
  client_ip inet,
  CONSTRAINT payment_intents_user_id_idempotency_key_key UNIQUE (user_id, idempotency_key),
  CONSTRAINT payment_intents_pkey PRIMARY KEY (id),
  CONSTRAINT payment_intents_amount_minor_check CHECK ((amount_minor > 0)),
  CONSTRAINT payment_intents_attempt_count_check CHECK ((attempt_count >= 0)),
  CONSTRAINT payment_intents_currency_check CHECK ((currency ~ '^[A-Z]{3}$'::text)),
  CONSTRAINT payment_intents_method_flow_check CHECK ((((payment_flow = 'saved_card'::text) AND (payment_method_id IS NOT NULL)) OR (payment_flow <> 'saved_card'::text))),
  CONSTRAINT payment_intents_payment_flow_check CHECK ((payment_flow = ANY (ARRAY['saved_card'::text, 'checkout_form'::text]))),
  CONSTRAINT payment_intents_provider_result_check CHECK ((jsonb_typeof(provider_result) = 'object'::text)),
  CONSTRAINT payment_intents_status_check CHECK ((status = ANY (ARRAY['created'::text, 'processing'::text, 'authorized'::text, 'captured'::text, 'failed'::text, 'cancelled'::text]))),
  CONSTRAINT payment_intents_subject_consistency_check CHECK ((((subject_type = 'order'::text) AND (order_id IS NOT NULL) AND (subject_id = order_id)) OR ((subject_type = 'event_reservation'::text) AND (order_id IS NULL)))),
  CONSTRAINT payment_intents_subject_type_check CHECK ((subject_type = ANY (ARRAY['order'::text, 'event_reservation'::text])))
);
ALTER TABLE private.payment_intents ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.payment_item_splits (
  id bigint GENERATED ALWAYS AS IDENTITY,
  payment_id uuid NOT NULL,
  order_id uuid,
  order_item_id uuid,
  producer_id uuid NOT NULL,
  provider_payment_transaction_id text NOT NULL,
  item_price_minor bigint NOT NULL,
  provider_paid_price_minor bigint,
  submerchant_price_minor bigint NOT NULL,
  transaction_status integer,
  approval_status text NOT NULL DEFAULT 'pending'::text,
  provider_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  event_reservation_id uuid,
  approved_at timestamp with time zone,
  approved_by uuid,
  approval_provider_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  approval_error text,
  CONSTRAINT payment_item_splits_payment_id_order_item_id_key UNIQUE (payment_id, order_item_id),
  CONSTRAINT payment_item_splits_provider_payment_transaction_id_key UNIQUE (provider_payment_transaction_id),
  CONSTRAINT payment_item_splits_pkey PRIMARY KEY (id),
  CONSTRAINT payment_item_splits_approval_error_length_check CHECK (((approval_error IS NULL) OR (char_length(approval_error) <= 500))),
  CONSTRAINT payment_item_splits_approval_provider_snapshot_check CHECK ((jsonb_typeof(approval_provider_snapshot) = 'object'::text)),
  CONSTRAINT payment_item_splits_approval_status_check CHECK ((approval_status = ANY (ARRAY['pending'::text, 'approved'::text, 'disapproved'::text]))),
  CONSTRAINT payment_item_splits_item_price_minor_check CHECK ((item_price_minor >= 0)),
  CONSTRAINT payment_item_splits_provider_paid_price_minor_check CHECK (((provider_paid_price_minor IS NULL) OR (provider_paid_price_minor >= 0))),
  CONSTRAINT payment_item_splits_provider_snapshot_check CHECK ((jsonb_typeof(provider_snapshot) = 'object'::text)),
  CONSTRAINT payment_item_splits_subject_consistency CHECK ((((order_id IS NOT NULL) AND (order_item_id IS NOT NULL) AND (event_reservation_id IS NULL)) OR ((order_id IS NULL) AND (order_item_id IS NULL) AND (event_reservation_id IS NOT NULL)))),
  CONSTRAINT payment_item_splits_submerchant_price_minor_check CHECK ((submerchant_price_minor >= 0))
);
ALTER TABLE private.payment_item_splits ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.payment_provider_customers (
  user_id uuid NOT NULL,
  provider text NOT NULL,
  provider_customer_ref text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT payment_provider_customers_provider_provider_customer_ref_key UNIQUE (provider, provider_customer_ref),
  CONSTRAINT payment_provider_customers_pkey PRIMARY KEY (user_id, provider),
  CONSTRAINT payment_provider_customers_provider_check CHECK ((provider ~ '^[a-z0-9_-]{2,40}$'::text)),
  CONSTRAINT payment_provider_customers_ref_check CHECK ((((char_length(provider_customer_ref) >= 3) AND (char_length(provider_customer_ref) <= 255)) AND (provider_customer_ref !~ '[[:cntrl:][:space:]]'::text)))
);
ALTER TABLE private.payment_provider_customers ENABLE ROW LEVEL SECURITY;

-- foreign keys (added after all tables exist)

ALTER TABLE private.customer_payment_methods ADD CONSTRAINT customer_payment_methods_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE private.payment_events ADD CONSTRAINT payment_events_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES payment_records(id) ON DELETE SET NULL;
ALTER TABLE private.payment_intents ADD CONSTRAINT payment_intents_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT;
ALTER TABLE private.payment_intents ADD CONSTRAINT payment_intents_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES private.customer_payment_methods(id) ON DELETE RESTRICT;
ALTER TABLE private.payment_intents ADD CONSTRAINT payment_intents_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE RESTRICT;
ALTER TABLE private.payment_item_splits ADD CONSTRAINT payment_item_splits_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE private.payment_item_splits ADD CONSTRAINT payment_item_splits_event_reservation_id_fkey FOREIGN KEY (event_reservation_id) REFERENCES event_reservations(id) ON DELETE RESTRICT;
ALTER TABLE private.payment_item_splits ADD CONSTRAINT payment_item_splits_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT;
ALTER TABLE private.payment_item_splits ADD CONSTRAINT payment_item_splits_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE RESTRICT;
ALTER TABLE private.payment_item_splits ADD CONSTRAINT payment_item_splits_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES payment_records(id) ON DELETE RESTRICT;
ALTER TABLE private.payment_item_splits ADD CONSTRAINT payment_item_splits_producer_id_fkey FOREIGN KEY (producer_id) REFERENCES producers(id) ON DELETE RESTRICT;
ALTER TABLE private.payment_provider_customers ADD CONSTRAINT payment_provider_customers_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
