-- Schema drift closure, tables batch 5: producer finance and platform
-- accounting (ledger entries, payouts, provider submerchant accounts,
-- settlement releases, accounting periods, platform expenses).
--
-- DDL generated by the database from its own catalogs via
-- scripts/generate-schema-ddl.sql, then md5-verified against that generated
-- text. Foreign keys are emitted after all CREATE TABLE statements so the file
-- is order-independent.
--
-- Applying is a no-op against the live project.

CREATE TABLE IF NOT EXISTS private.accounting_periods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  period_from date NOT NULL,
  period_to date NOT NULL,
  currency text NOT NULL,
  status text NOT NULL DEFAULT 'closed'::text,
  snapshot jsonb NOT NULL,
  closed_by uuid,
  closed_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  archived_at timestamp with time zone,
  cleanup_completed_at timestamp with time zone,
  CONSTRAINT accounting_periods_period_from_period_to_currency_key UNIQUE (period_from, period_to, currency),
  CONSTRAINT accounting_periods_pkey PRIMARY KEY (id),
  CONSTRAINT accounting_periods_check CHECK ((period_to >= period_from)),
  CONSTRAINT accounting_periods_currency_check CHECK ((currency ~ '^[A-Z]{3}$'::text)),
  CONSTRAINT accounting_periods_snapshot_check CHECK ((jsonb_typeof(snapshot) = 'object'::text)),
  CONSTRAINT accounting_periods_status_check CHECK ((status = ANY (ARRAY['closed'::text, 'archived'::text])))
);
ALTER TABLE private.accounting_periods ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.order_settlement_releases (
  order_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  requested_by uuid,
  requested_at timestamp with time zone,
  released_by uuid,
  released_at timestamp with time zone,
  provider text,
  last_error text,
  provider_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT order_settlement_releases_pkey PRIMARY KEY (order_id),
  CONSTRAINT order_settlement_releases_last_error_check CHECK (((last_error IS NULL) OR (char_length(last_error) <= 500))),
  CONSTRAINT order_settlement_releases_provider_snapshot_check CHECK ((jsonb_typeof(provider_snapshot) = 'object'::text)),
  CONSTRAINT order_settlement_releases_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'released'::text, 'failed'::text, 'blocked'::text])))
);
ALTER TABLE private.order_settlement_releases ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.platform_expenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  spent_on date NOT NULL,
  category text NOT NULL,
  description text NOT NULL,
  amount_minor bigint NOT NULL,
  currency text NOT NULL,
  external_reference text,
  receipt_path text,
  status text NOT NULL DEFAULT 'posted'::text,
  void_reason text,
  created_by uuid,
  voided_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  voided_at timestamp with time zone,
  CONSTRAINT platform_expenses_pkey PRIMARY KEY (id),
  CONSTRAINT platform_expenses_amount_minor_check CHECK ((amount_minor > 0)),
  CONSTRAINT platform_expenses_category_check CHECK ((category = ANY (ARRAY['payment_fee'::text, 'shipping_subsidy'::text, 'marketing'::text, 'software'::text, 'staff'::text, 'tax_accounting'::text, 'refund_loss'::text, 'bank_fee'::text, 'legal'::text, 'other'::text]))),
  CONSTRAINT platform_expenses_check CHECK ((((status = 'posted'::text) AND (void_reason IS NULL) AND (voided_at IS NULL)) OR ((status = 'void'::text) AND ((char_length(COALESCE(void_reason, ''::text)) >= 8) AND (char_length(COALESCE(void_reason, ''::text)) <= 1000)) AND (voided_at IS NOT NULL)))),
  CONSTRAINT platform_expenses_currency_check CHECK ((currency ~ '^[A-Z]{3}$'::text)),
  CONSTRAINT platform_expenses_description_check CHECK (((char_length(description) >= 3) AND (char_length(description) <= 1000))),
  CONSTRAINT platform_expenses_status_check CHECK ((status = ANY (ARRAY['posted'::text, 'void'::text])))
);
ALTER TABLE private.platform_expenses ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.producer_ledger_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  producer_id uuid NOT NULL,
  order_id uuid,
  order_item_id uuid,
  return_id uuid,
  refund_id uuid,
  entry_type text NOT NULL,
  currency text NOT NULL,
  merchandise_minor bigint NOT NULL,
  tax_minor bigint NOT NULL DEFAULT 0,
  producer_gross_minor bigint NOT NULL,
  platform_fee_minor bigint NOT NULL,
  producer_net_minor bigint NOT NULL,
  commission_basis_points integer NOT NULL,
  availability_status text NOT NULL DEFAULT 'pending'::text,
  available_at timestamp with time zone,
  source_key text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  event_reservation_id uuid,
  CONSTRAINT producer_ledger_entries_source_key_key UNIQUE (source_key),
  CONSTRAINT producer_ledger_entries_pkey PRIMARY KEY (id),
  CONSTRAINT producer_ledger_entries_availability_status_check CHECK ((availability_status = ANY (ARRAY['pending'::text, 'available'::text]))),
  CONSTRAINT producer_ledger_entries_check CHECK ((producer_gross_minor = (merchandise_minor + tax_minor))),
  CONSTRAINT producer_ledger_entries_check1 CHECK ((producer_net_minor = (producer_gross_minor - platform_fee_minor))),
  CONSTRAINT producer_ledger_entries_commission_basis_points_check CHECK (((commission_basis_points >= 0) AND (commission_basis_points <= 10000))),
  CONSTRAINT producer_ledger_entries_currency_check CHECK ((currency ~ '^[A-Z]{3}$'::text)),
  CONSTRAINT producer_ledger_entries_entry_type_check CHECK ((entry_type = ANY (ARRAY['sale'::text, 'refund'::text, 'adjustment'::text]))),
  CONSTRAINT producer_ledger_entries_metadata_check CHECK ((jsonb_typeof(metadata) = 'object'::text))
);
ALTER TABLE private.producer_ledger_entries ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.producer_payment_accounts (
  producer_id uuid NOT NULL,
  provider text NOT NULL DEFAULT 'iyzico'::text,
  provider_submerchant_type text,
  submerchant_external_id text NOT NULL,
  submerchant_key text,
  status text NOT NULL DEFAULT 'pending_configuration'::text,
  last_error text,
  provider_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  onboarded_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT producer_payment_accounts_provider_submerchant_external_id_key UNIQUE (provider, submerchant_external_id),
  CONSTRAINT producer_payment_accounts_pkey PRIMARY KEY (producer_id),
  CONSTRAINT producer_payment_accounts_provider_snapshot_check CHECK ((jsonb_typeof(provider_snapshot) = 'object'::text)),
  CONSTRAINT producer_payment_accounts_provider_submerchant_type_check CHECK ((provider_submerchant_type = ANY (ARRAY['PERSONAL'::text, 'PRIVATE_COMPANY'::text, 'LIMITED_OR_JOINT_STOCK_COMPANY'::text]))),
  CONSTRAINT producer_payment_accounts_status_check CHECK ((status = ANY (ARRAY['pending_configuration'::text, 'onboarding'::text, 'ready'::text, 'suspended'::text, 'error'::text])))
);
ALTER TABLE private.producer_payment_accounts ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.producer_payouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  producer_id uuid NOT NULL,
  currency text NOT NULL,
  amount_minor bigint NOT NULL,
  status text NOT NULL DEFAULT 'scheduled'::text,
  provider text,
  provider_reference text,
  note text,
  created_by uuid,
  processed_by uuid,
  scheduled_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  processed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  channel text NOT NULL DEFAULT 'manual_bank_transfer'::text,
  request_source text NOT NULL DEFAULT 'legacy_admin'::text,
  source_order_id uuid,
  requested_at timestamp with time zone,
  destination_application_id uuid,
  destination_account_holder text,
  destination_iban_ciphertext text,
  destination_iban_masked text,
  provider_settlement_released_at timestamp with time zone,
  CONSTRAINT producer_payouts_pkey PRIMARY KEY (id),
  CONSTRAINT producer_payouts_amount_minor_check CHECK ((amount_minor > 0)),
  CONSTRAINT producer_payouts_channel_check CHECK ((channel = ANY (ARRAY['provider_marketplace'::text, 'manual_bank_transfer'::text]))),
  CONSTRAINT producer_payouts_currency_check CHECK ((currency ~ '^[A-Z]{3}$'::text)),
  CONSTRAINT producer_payouts_destination_holder_length_check CHECK (((destination_account_holder IS NULL) OR (char_length(destination_account_holder) <= 300))),
  CONSTRAINT producer_payouts_destination_mask_length_check CHECK (((destination_iban_masked IS NULL) OR (char_length(destination_iban_masked) <= 80))),
  CONSTRAINT producer_payouts_request_source_check CHECK ((request_source = ANY (ARRAY['producer'::text, 'super_admin'::text, 'super_admin_settlement'::text, 'legacy_admin'::text]))),
  CONSTRAINT producer_payouts_status_check CHECK ((status = ANY (ARRAY['requested'::text, 'scheduled'::text, 'processing'::text, 'paid'::text, 'failed'::text, 'cancelled'::text])))
);
ALTER TABLE private.producer_payouts ENABLE ROW LEVEL SECURITY;

-- foreign keys (added after all tables exist)

ALTER TABLE private.accounting_periods ADD CONSTRAINT accounting_periods_closed_by_fkey FOREIGN KEY (closed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE private.order_settlement_releases ADD CONSTRAINT order_settlement_releases_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT;
ALTER TABLE private.order_settlement_releases ADD CONSTRAINT order_settlement_releases_released_by_fkey FOREIGN KEY (released_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE private.order_settlement_releases ADD CONSTRAINT order_settlement_releases_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE private.platform_expenses ADD CONSTRAINT platform_expenses_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE private.platform_expenses ADD CONSTRAINT platform_expenses_voided_by_fkey FOREIGN KEY (voided_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE private.producer_ledger_entries ADD CONSTRAINT producer_ledger_entries_event_reservation_id_fkey FOREIGN KEY (event_reservation_id) REFERENCES event_reservations(id) ON DELETE RESTRICT;
ALTER TABLE private.producer_ledger_entries ADD CONSTRAINT producer_ledger_entries_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT;
ALTER TABLE private.producer_ledger_entries ADD CONSTRAINT producer_ledger_entries_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE RESTRICT;
ALTER TABLE private.producer_ledger_entries ADD CONSTRAINT producer_ledger_entries_producer_id_fkey FOREIGN KEY (producer_id) REFERENCES producers(id) ON DELETE RESTRICT;
ALTER TABLE private.producer_ledger_entries ADD CONSTRAINT producer_ledger_entries_refund_id_fkey FOREIGN KEY (refund_id) REFERENCES refunds(id) ON DELETE SET NULL;
ALTER TABLE private.producer_ledger_entries ADD CONSTRAINT producer_ledger_entries_return_id_fkey FOREIGN KEY (return_id) REFERENCES return_requests(id) ON DELETE SET NULL;
ALTER TABLE private.producer_payment_accounts ADD CONSTRAINT producer_payment_accounts_producer_id_fkey FOREIGN KEY (producer_id) REFERENCES producers(id) ON DELETE RESTRICT;
ALTER TABLE private.producer_payouts ADD CONSTRAINT producer_payouts_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE private.producer_payouts ADD CONSTRAINT producer_payouts_destination_application_id_fkey FOREIGN KEY (destination_application_id) REFERENCES producer_applications(id) ON DELETE SET NULL;
ALTER TABLE private.producer_payouts ADD CONSTRAINT producer_payouts_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE private.producer_payouts ADD CONSTRAINT producer_payouts_producer_id_fkey FOREIGN KEY (producer_id) REFERENCES producers(id) ON DELETE RESTRICT;
ALTER TABLE private.producer_payouts ADD CONSTRAINT producer_payouts_source_order_id_fkey FOREIGN KEY (source_order_id) REFERENCES orders(id) ON DELETE RESTRICT;
