-- Schema drift closure, tables batch 9: the product catalogue
-- (categories, products, variants, inventory, images).
--
-- DDL generated by the database from its own catalogs via
-- scripts/generate-schema-ddl.sql, then md5-verified against that generated
-- text. Foreign keys are emitted after all CREATE TABLE statements so the file
-- is order-independent.
--
-- Generator fix prompted by this batch: products and product_images are the
-- only two tables carrying constraint triggers (pg_constraint.contype = 't').
-- pg_get_constraintdef renders those as the bare fragment
-- "TRIGGER DEFERRABLE INITIALLY DEFERRED", which is not valid inside CREATE
-- TABLE. Emitting it would have produced a file whose md5 matched the
-- generator output perfectly and still failed on execution - md5 proves
-- faithful copying, not syntactic validity. The generator now selects only
-- primary key, unique, check and exclusion constraints inline, and the two
-- constraint triggers are emitted separately at the end via
-- CREATE CONSTRAINT TRIGGER. Batches 1 to 8 were re-checked against
-- pg_constraint and contain no constraint triggers.
--
-- Applying is a no-op against the live project.

CREATE TABLE IF NOT EXISTS public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  parent_id uuid,
  slug text NOT NULL,
  name text NOT NULL,
  description text NOT NULL DEFAULT ''::text,
  icon text,
  image_path text,
  translations jsonb NOT NULL DEFAULT '{}'::jsonb,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  seo jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT categories_slug_key UNIQUE (slug),
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_image_path_not_absolute_url CHECK (((image_path IS NULL) OR (image_path !~* '^[a-z][a-z0-9+.-]*:'::text))),
  CONSTRAINT categories_seo_check CHECK ((jsonb_typeof(seo) = 'object'::text)),
  CONSTRAINT categories_slug_check CHECK ((slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'::text)),
  CONSTRAINT categories_sort_order_check CHECK ((sort_order >= 0)),
  CONSTRAINT categories_translations_check CHECK ((jsonb_typeof(translations) = 'object'::text))
);
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.product_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  storage_path text NOT NULL,
  alt_text text NOT NULL,
  width integer,
  height integer,
  sort_order integer NOT NULL DEFAULT 0,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT product_images_product_id_storage_path_key UNIQUE (product_id, storage_path),
  CONSTRAINT product_images_pkey PRIMARY KEY (id),
  CONSTRAINT product_images_height_check CHECK (((height IS NULL) OR (height > 0))),
  CONSTRAINT product_images_sort_order_check CHECK ((sort_order >= 0)),
  CONSTRAINT product_images_width_check CHECK (((width IS NULL) OR (width > 0)))
);
ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.product_inventory (
  variant_id uuid NOT NULL,
  available_quantity integer NOT NULL DEFAULT 0,
  reserved_quantity integer NOT NULL DEFAULT 0,
  reorder_level integer NOT NULL DEFAULT 0,
  version bigint NOT NULL DEFAULT 1,
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT product_inventory_pkey PRIMARY KEY (variant_id),
  CONSTRAINT product_inventory_available_quantity_check CHECK ((available_quantity >= 0)),
  CONSTRAINT product_inventory_check CHECK ((reserved_quantity <= available_quantity)),
  CONSTRAINT product_inventory_reorder_level_check CHECK ((reorder_level >= 0)),
  CONSTRAINT product_inventory_reserved_quantity_check CHECK ((reserved_quantity >= 0)),
  CONSTRAINT product_inventory_version_check CHECK ((version > 0))
);
ALTER TABLE public.product_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_inventory FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.product_variants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  sku text NOT NULL,
  name text NOT NULL,
  option_values jsonb NOT NULL DEFAULT '{}'::jsonb,
  price_minor bigint NOT NULL,
  compare_at_price_minor bigint,
  weight_grams integer,
  barcode text,
  is_default boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  shipping_weight_source text NOT NULL DEFAULT 'unknown'::text,
  shipping_weight_note text,
  shipping_weight_verified_at timestamp with time zone,
  CONSTRAINT product_variants_sku_key UNIQUE (sku),
  CONSTRAINT product_variants_pkey PRIMARY KEY (id),
  CONSTRAINT product_variants_check CHECK (((compare_at_price_minor IS NULL) OR (compare_at_price_minor >= price_minor))),
  CONSTRAINT product_variants_option_values_check CHECK ((jsonb_typeof(option_values) = 'object'::text)),
  CONSTRAINT product_variants_price_minor_check CHECK ((price_minor >= 0)),
  CONSTRAINT product_variants_shipping_weight_source_check CHECK ((shipping_weight_source = ANY (ARRAY['unknown'::text, 'estimated'::text, 'measured'::text, 'supplier'::text]))),
  CONSTRAINT product_variants_weight_grams_check CHECK (((weight_grams IS NULL) OR (weight_grams > 0)))
);
ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variants FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  legacy_source text,
  legacy_id text,
  producer_id uuid NOT NULL,
  category_id uuid NOT NULL,
  slug text NOT NULL,
  name text NOT NULL,
  short_description text NOT NULL DEFAULT ''::text,
  description text NOT NULL DEFAULT ''::text,
  story text NOT NULL DEFAULT ''::text,
  origin text,
  unit_label text NOT NULL,
  base_price_minor bigint NOT NULL,
  compare_at_price_minor bigint,
  currency text NOT NULL DEFAULT 'TRY'::text,
  tax_rate_basis_points integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'draft'::text,
  stock_mode text NOT NULL DEFAULT 'tracked'::text,
  preorder_lead_days integer,
  tags text[] NOT NULL DEFAULT '{}'::text[],
  features jsonb NOT NULL DEFAULT '[]'::jsonb,
  specifications jsonb NOT NULL DEFAULT '{}'::jsonb,
  translations jsonb NOT NULL DEFAULT '{}'::jsonb,
  seo jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_featured boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  published_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  deleted_at timestamp with time zone,
  export_status text NOT NULL DEFAULT 'not_configured'::text,
  country_of_origin_code text,
  customs_hs_code text,
  customs_description text,
  is_perishable boolean NOT NULL DEFAULT false,
  requires_cold_chain boolean NOT NULL DEFAULT false,
  shelf_life_days integer,
  search_text text NOT NULL DEFAULT ''::text,
  CONSTRAINT products_legacy_source_legacy_id_key UNIQUE (legacy_source, legacy_id),
  CONSTRAINT products_slug_key UNIQUE (slug),
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_base_price_minor_check CHECK ((base_price_minor >= 0)),
  CONSTRAINT products_check CHECK (((compare_at_price_minor IS NULL) OR (compare_at_price_minor >= base_price_minor))),
  CONSTRAINT products_check1 CHECK ((((status = 'published'::text) AND (published_at IS NOT NULL)) OR (status <> 'published'::text))),
  CONSTRAINT products_country_of_origin_check CHECK (((country_of_origin_code IS NULL) OR (country_of_origin_code ~ '^[A-Z]{2}$'::text))),
  CONSTRAINT products_currency_check CHECK ((currency ~ '^[A-Z]{3}$'::text)),
  CONSTRAINT products_customs_description_check CHECK (((customs_description IS NULL) OR (char_length(customs_description) <= 500))),
  CONSTRAINT products_customs_hs_code_check CHECK (((customs_hs_code IS NULL) OR (((char_length(customs_hs_code) >= 4) AND (char_length(customs_hs_code) <= 16)) AND (customs_hs_code ~ '^[0-9.]+$'::text)))),
  CONSTRAINT products_export_status_check CHECK ((export_status = ANY (ARRAY['not_configured'::text, 'domestic_only'::text, 'manual_review'::text, 'eligible'::text]))),
  CONSTRAINT products_features_check CHECK ((jsonb_typeof(features) = 'array'::text)),
  CONSTRAINT products_preorder_lead_days_check CHECK (((preorder_lead_days IS NULL) OR ((preorder_lead_days >= 0) AND (preorder_lead_days <= 365)))),
  CONSTRAINT products_seo_check CHECK ((jsonb_typeof(seo) = 'object'::text)),
  CONSTRAINT products_shelf_life_days_check CHECK (((shelf_life_days IS NULL) OR ((shelf_life_days >= 1) AND (shelf_life_days <= 3650)))),
  CONSTRAINT products_slug_check CHECK ((slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'::text)),
  CONSTRAINT products_specifications_check CHECK ((jsonb_typeof(specifications) = 'object'::text)),
  CONSTRAINT products_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'review'::text, 'published'::text, 'rejected'::text, 'archived'::text]))),
  CONSTRAINT products_stock_mode_check CHECK ((stock_mode = ANY (ARRAY['tracked'::text, 'preorder'::text, 'unlimited'::text, 'seasonal'::text]))),
  CONSTRAINT products_tax_rate_basis_points_check CHECK (((tax_rate_basis_points >= 0) AND (tax_rate_basis_points <= 10000))),
  CONSTRAINT products_translations_check CHECK ((jsonb_typeof(translations) = 'object'::text))
);
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products FORCE ROW LEVEL SECURITY;

-- foreign keys (added after all tables exist)

ALTER TABLE public.categories ADD CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE RESTRICT;
ALTER TABLE public.product_images ADD CONSTRAINT product_images_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.product_inventory ADD CONSTRAINT product_inventory_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE CASCADE;
ALTER TABLE public.product_variants ADD CONSTRAINT product_variants_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.products ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT;
ALTER TABLE public.products ADD CONSTRAINT products_producer_id_fkey FOREIGN KEY (producer_id) REFERENCES producers(id) ON DELETE RESTRICT;

-- constraint triggers (cannot be expressed inside CREATE TABLE; emitted from
-- pg_get_triggerdef). Both are deferred to transaction commit, which is what
-- lets a product and its images be written in one transaction and validated
-- together at the end rather than mid-write.

DROP TRIGGER IF EXISTS product_media_integrity_images_v1 ON public.product_images;
CREATE CONSTRAINT TRIGGER product_media_integrity_images_v1 AFTER INSERT OR DELETE OR UPDATE ON public.product_images DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION private.enforce_product_image_parent_media_integrity_v1();

DROP TRIGGER IF EXISTS product_media_integrity_product_v1 ON public.products;
CREATE CONSTRAINT TRIGGER product_media_integrity_product_v1 AFTER INSERT OR UPDATE ON public.products DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION private.enforce_product_publish_media_integrity_v1();
