-- Schema drift closure, tables batch 3: notification delivery and alert
-- subscriptions (push tokens, push delivery queue, per-user notification
-- preferences, stock alert subscriptions, archived content snapshots).
--
-- DDL generated by the database from its own catalogs via
-- scripts/generate-schema-ddl.sql, then md5-verified against that generated
-- text. Foreign keys are emitted after all CREATE TABLE statements so the file
-- is order-independent.
--
-- Applying is a no-op against the live project.

CREATE TABLE IF NOT EXISTS private.content_entry_public_archives (
  content_entry_id uuid NOT NULL,
  migration_key text NOT NULL,
  archived_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  summary text NOT NULL,
  body_markdown text NOT NULL,
  body_html_sanitized text NOT NULL,
  tags text[] NOT NULL DEFAULT ARRAY[]::text[],
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT content_entry_public_archives_pkey PRIMARY KEY (content_entry_id, migration_key)
);
ALTER TABLE private.content_entry_public_archives ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.device_push_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  token_hash text NOT NULL,
  token_ciphertext bytea NOT NULL,
  provider text NOT NULL,
  platform text NOT NULL,
  environment text NOT NULL DEFAULT 'production'::text,
  last_seen_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  disabled_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT device_push_tokens_token_hash_key UNIQUE (token_hash),
  CONSTRAINT device_push_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT device_push_tokens_environment_check CHECK ((environment = ANY (ARRAY['development'::text, 'production'::text]))),
  CONSTRAINT device_push_tokens_platform_check CHECK ((platform = ANY (ARRAY['android'::text, 'ios'::text]))),
  CONSTRAINT device_push_tokens_provider_check CHECK ((provider = ANY (ARRAY['fcm'::text, 'apns'::text])))
);
ALTER TABLE private.device_push_tokens ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.push_deliveries (
  id bigint GENERATED ALWAYS AS IDENTITY,
  notification_id uuid NOT NULL,
  user_id uuid NOT NULL,
  device_token_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  attempts integer NOT NULL DEFAULT 0,
  available_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  locked_at timestamp with time zone,
  locked_by text,
  sent_at timestamp with time zone,
  last_error text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT push_deliveries_notification_id_device_token_id_key UNIQUE (notification_id, device_token_id),
  CONSTRAINT push_deliveries_pkey PRIMARY KEY (id),
  CONSTRAINT push_deliveries_attempts_check CHECK (((attempts >= 0) AND (attempts <= 20))),
  CONSTRAINT push_deliveries_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'sent'::text, 'failed'::text, 'cancelled'::text])))
);
ALTER TABLE private.push_deliveries ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.stock_alert_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  variant_id uuid NOT NULL,
  user_id uuid,
  email_normalized text,
  status text NOT NULL DEFAULT 'active'::text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  notified_at timestamp with time zone,
  locale text NOT NULL DEFAULT 'tr'::text,
  unsubscribe_token_hash text,
  CONSTRAINT stock_alert_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT stock_alert_subscriptions_check CHECK (((user_id IS NOT NULL) OR (email_normalized IS NOT NULL))),
  CONSTRAINT stock_alert_subscriptions_locale_check CHECK ((locale = ANY (ARRAY['tr'::text, 'en'::text, 'de'::text, 'fr'::text, 'ku'::text, 'ar'::text]))),
  CONSTRAINT stock_alert_subscriptions_status_check CHECK ((status = ANY (ARRAY['active'::text, 'notified'::text, 'cancelled'::text])))
);
ALTER TABLE private.stock_alert_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.stock_alert_subscriptions FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.user_notification_preferences (
  user_id uuid NOT NULL,
  push_enabled boolean NOT NULL DEFAULT true,
  order_push boolean NOT NULL DEFAULT true,
  payment_push boolean NOT NULL DEFAULT true,
  shipment_push boolean NOT NULL DEFAULT true,
  return_push boolean NOT NULL DEFAULT true,
  message_push boolean NOT NULL DEFAULT true,
  review_push boolean NOT NULL DEFAULT true,
  producer_push boolean NOT NULL DEFAULT true,
  system_push boolean NOT NULL DEFAULT true,
  campaign_push boolean NOT NULL DEFAULT false,
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT user_notification_preferences_pkey PRIMARY KEY (user_id)
);
ALTER TABLE private.user_notification_preferences ENABLE ROW LEVEL SECURITY;

-- foreign keys (added after all tables exist)

ALTER TABLE private.content_entry_public_archives ADD CONSTRAINT content_entry_public_archives_content_entry_id_fkey FOREIGN KEY (content_entry_id) REFERENCES content_entries(id) ON DELETE CASCADE;
ALTER TABLE private.device_push_tokens ADD CONSTRAINT device_push_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE private.push_deliveries ADD CONSTRAINT push_deliveries_device_token_id_fkey FOREIGN KEY (device_token_id) REFERENCES private.device_push_tokens(id) ON DELETE CASCADE;
ALTER TABLE private.push_deliveries ADD CONSTRAINT push_deliveries_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES notifications(id) ON DELETE CASCADE;
ALTER TABLE private.push_deliveries ADD CONSTRAINT push_deliveries_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE private.stock_alert_subscriptions ADD CONSTRAINT stock_alert_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE private.stock_alert_subscriptions ADD CONSTRAINT stock_alert_subscriptions_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE CASCADE;
ALTER TABLE private.user_notification_preferences ADD CONSTRAINT user_notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
