-- Schema drift closure, tables batch 1: private-schema infrastructure tables
-- (audit log, idempotency keys, outbox events, legacy migration bookkeeping,
-- sensitive access log, submission rate-limit attempts).
--
-- DDL below was generated by the database itself from its own catalogs, not
-- hand-written, and the file is md5-verified against that generated text.
-- The generator lives at scripts/generate-schema-ddl.sql so this is
-- reproducible rather than a one-off transcription.
--
-- Foreign keys are emitted separately, after all CREATE TABLE statements, so
-- the file is order-independent and can be replayed against an empty database
-- without dependency failures.
--
-- Applying is a no-op against the live project: every statement is
-- CREATE TABLE IF NOT EXISTS, and the ALTER statements restate settings that
-- are already in effect.

CREATE TABLE IF NOT EXISTS private.audit_log (
  id bigint GENERATED ALWAYS AS IDENTITY,
  table_schema text NOT NULL,
  table_name text NOT NULL,
  record_id text,
  action text NOT NULL,
  actor_user_id uuid,
  actor_role text,
  old_data jsonb,
  new_data jsonb,
  request_id text,
  ip_address inet,
  occurred_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  transaction_id bigint NOT NULL DEFAULT txid_current(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_action_check CHECK ((action = ANY (ARRAY['INSERT'::text, 'UPDATE'::text, 'DELETE'::text])))
);
ALTER TABLE private.audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.audit_log FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.idempotency_keys (
  key text NOT NULL,
  scope text NOT NULL,
  user_id uuid,
  request_hash text NOT NULL,
  response_status integer,
  response_body jsonb,
  locked_at timestamp with time zone,
  completed_at timestamp with time zone,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT idempotency_keys_pkey PRIMARY KEY (key)
);
ALTER TABLE private.idempotency_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.idempotency_keys FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.legacy_records (
  source_system text NOT NULL,
  entity_type text NOT NULL,
  source_id text NOT NULL,
  payload jsonb NOT NULL,
  payload_sha256 text NOT NULL,
  migration_status text NOT NULL DEFAULT 'pending'::text,
  target_table text,
  target_id uuid,
  migration_error text,
  imported_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  migrated_at timestamp with time zone,
  CONSTRAINT legacy_records_pkey PRIMARY KEY (source_system, entity_type, source_id),
  CONSTRAINT legacy_records_migration_status_check CHECK ((migration_status = ANY (ARRAY['pending'::text, 'migrated'::text, 'skipped'::text, 'failed'::text]))),
  CONSTRAINT legacy_records_payload_check CHECK ((jsonb_typeof(payload) = ANY (ARRAY['object'::text, 'array'::text])))
);
ALTER TABLE private.legacy_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.legacy_records FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.migration_id_map (
  source_system text NOT NULL,
  entity_type text NOT NULL,
  source_id text NOT NULL,
  target_id uuid NOT NULL,
  source_hash text,
  migrated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT migration_id_map_entity_type_target_id_key UNIQUE (entity_type, target_id),
  CONSTRAINT migration_id_map_pkey PRIMARY KEY (source_system, entity_type, source_id)
);
ALTER TABLE private.migration_id_map ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.migration_id_map FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.outbox_events (
  id bigint GENERATED ALWAYS AS IDENTITY,
  aggregate_type text NOT NULL,
  aggregate_id uuid,
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  attempts integer NOT NULL DEFAULT 0,
  available_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  locked_at timestamp with time zone,
  locked_by text,
  processed_at timestamp with time zone,
  last_error text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT outbox_events_pkey PRIMARY KEY (id),
  CONSTRAINT outbox_events_attempts_check CHECK ((attempts >= 0)),
  CONSTRAINT outbox_events_payload_check CHECK ((jsonb_typeof(payload) = 'object'::text)),
  CONSTRAINT outbox_events_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'processed'::text, 'failed'::text, 'dead_letter'::text])))
);
ALTER TABLE private.outbox_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.outbox_events FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.sensitive_access_log (
  id bigint GENERATED ALWAYS AS IDENTITY,
  actor_user_id uuid NOT NULL,
  resource_type text NOT NULL,
  resource_id uuid NOT NULL,
  purpose text NOT NULL,
  occurred_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT sensitive_access_log_pkey PRIMARY KEY (id)
);
ALTER TABLE private.sensitive_access_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.sensitive_access_log FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.submission_attempts (
  id bigint GENERATED ALWAYS AS IDENTITY,
  scope text NOT NULL,
  ip_hash text NOT NULL,
  request_hash text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT submission_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT submission_attempts_ip_hash_check CHECK ((ip_hash ~ '^[a-f0-9]{64}$'::text)),
  CONSTRAINT submission_attempts_request_hash_check CHECK ((request_hash ~ '^[a-f0-9]{64}$'::text)),
  CONSTRAINT submission_attempts_scope_check CHECK ((scope = ANY (ARRAY['contact'::text, 'event_reservation'::text])))
);
ALTER TABLE private.submission_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.submission_attempts FORCE ROW LEVEL SECURITY;

-- foreign keys (added after all tables exist)

ALTER TABLE private.idempotency_keys ADD CONSTRAINT idempotency_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE private.sensitive_access_log ADD CONSTRAINT sensitive_access_log_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES auth.users(id) ON DELETE RESTRICT;
