-- Schema drift closure, tables batch 8: public-schema customer core
-- (profiles, addresses, favourites, carts, cart items).
--
-- DDL generated by the database from its own catalogs via
-- scripts/generate-schema-ddl.sql, then md5-verified against that generated
-- text. Foreign keys are emitted after all CREATE TABLE statements so the file
-- is order-independent.
--
-- Applying is a no-op against the live project.

CREATE TABLE IF NOT EXISTS public.addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  label text NOT NULL,
  recipient_name text NOT NULL,
  phone text NOT NULL,
  country_code text NOT NULL DEFAULT 'TR'::text,
  province text NOT NULL,
  district text NOT NULL,
  neighborhood text,
  address_line text NOT NULL,
  postal_code text,
  delivery_notes text,
  is_default boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  deleted_at timestamp with time zone,
  CONSTRAINT addresses_pkey PRIMARY KEY (id),
  CONSTRAINT addresses_country_code_check CHECK ((country_code ~ '^[A-Z]{2}$'::text))
);
ALTER TABLE public.addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.addresses FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.cart_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cart_id uuid NOT NULL,
  variant_id uuid NOT NULL,
  quantity integer NOT NULL,
  selected_options jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT cart_items_cart_id_variant_id_selected_options_key UNIQUE (cart_id, variant_id, selected_options),
  CONSTRAINT cart_items_pkey PRIMARY KEY (id),
  CONSTRAINT cart_items_quantity_check CHECK (((quantity >= 1) AND (quantity <= 99))),
  CONSTRAINT cart_items_selected_options_check CHECK ((jsonb_typeof(selected_options) = 'object'::text))
);
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.carts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'active'::text,
  currency text NOT NULL DEFAULT 'TRY'::text,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT carts_pkey PRIMARY KEY (id),
  CONSTRAINT carts_currency_check CHECK ((currency ~ '^[A-Z]{3}$'::text)),
  CONSTRAINT carts_status_check CHECK ((status = ANY (ARRAY['active'::text, 'converted'::text, 'abandoned'::text])))
);
ALTER TABLE public.carts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carts FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.favorites (
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT favorites_pkey PRIMARY KEY (user_id, product_id)
);
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.favorites FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid NOT NULL,
  display_name text NOT NULL DEFAULT ''::text,
  avatar_path text,
  locale text NOT NULL DEFAULT 'tr'::text,
  phone text,
  status text NOT NULL DEFAULT 'active'::text,
  marketing_consent boolean NOT NULL DEFAULT false,
  marketing_consent_at timestamp with time zone,
  last_seen_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  deleted_at timestamp with time zone,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_check CHECK (((marketing_consent = false) OR (marketing_consent_at IS NOT NULL))),
  CONSTRAINT profiles_locale_check CHECK ((locale = ANY (ARRAY['tr'::text, 'en'::text, 'de'::text, 'fr'::text, 'ku'::text, 'ar'::text]))),
  CONSTRAINT profiles_status_check CHECK ((status = ANY (ARRAY['active'::text, 'restricted'::text, 'blocked'::text, 'deleted'::text])))
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles FORCE ROW LEVEL SECURITY;

-- foreign keys (added after all tables exist)

ALTER TABLE public.addresses ADD CONSTRAINT addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.cart_items ADD CONSTRAINT cart_items_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES carts(id) ON DELETE CASCADE;
ALTER TABLE public.cart_items ADD CONSTRAINT cart_items_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE CASCADE;
ALTER TABLE public.carts ADD CONSTRAINT carts_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.favorites ADD CONSTRAINT favorites_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.favorites ADD CONSTRAINT favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
