-- Schema drift closure, RLS policies part 1: the private schema (26 policies).
--
-- Policy DDL generated by the database from pg_policy via
-- scripts/generate-schema-ddl.sql, then md5-verified against that generated
-- text.
--
-- What this layer expresses: with two exceptions, every private-schema policy
-- is a deny. The private schema is reached only through SECURITY DEFINER
-- functions owned by postgres, which are exempt from RLS, and through
-- service_role, which carries rolbypassrls. Client roles are told "no" at the
-- table level so that a future accidental GRANT cannot turn into a data leak.
--
-- The distinction between the two deny styles is deliberate and worth keeping:
-- RESTRICTIVE policies (audit_log, brand_secrets, producer_application_kyc,
-- producer_documents, payment_events, idempotency_keys and others) cannot be
-- widened by adding a permissive policy later. Someone adding a well-meaning
-- "allow the owner to read their own row" policy to one of those tables would
-- still be denied, because a restrictive policy is ANDed with everything else.
-- On the most sensitive tables - KYC ciphertext, brand secrets, the audit
-- trail - that is the correct posture.
--
-- The one genuine grant here is user_roles_read_own, which lets a signed-in
-- user read their own unexpired roles and nothing else. It exists because the
-- client needs to know what the current user may do; it is scoped to
-- auth.uid() and filters expired grants.
--
-- Applying is a no-op against the live project: these policies already exist.
-- DROP POLICY IF EXISTS precedes each CREATE so the file is replayable.

DROP POLICY IF EXISTS admin_audit_logs_no_direct_client_access ON private.admin_audit_logs;
CREATE POLICY admin_audit_logs_no_direct_client_access ON private.admin_audit_logs
  FOR ALL
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS audit_log_deny_client_access ON private.audit_log;
CREATE POLICY audit_log_deny_client_access ON private.audit_log
  AS RESTRICTIVE
  FOR ALL
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS brand_secrets_deny_client_access ON private.brand_secrets;
CREATE POLICY brand_secrets_deny_client_access ON private.brand_secrets
  AS RESTRICTIVE
  FOR ALL
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS contact_messages_deny_client_access ON private.contact_messages;
CREATE POLICY contact_messages_deny_client_access ON private.contact_messages
  AS RESTRICTIVE
  FOR ALL
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS content_entry_public_archives_deny_all ON private.content_entry_public_archives;
CREATE POLICY content_entry_public_archives_deny_all ON private.content_entry_public_archives
  FOR ALL
  TO PUBLIC
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS content_favorites_deny_all_v1 ON private.content_favorites;
CREATE POLICY content_favorites_deny_all_v1 ON private.content_favorites
  FOR ALL
  TO PUBLIC
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS idempotency_keys_deny_client_access ON private.idempotency_keys;
CREATE POLICY idempotency_keys_deny_client_access ON private.idempotency_keys
  AS RESTRICTIVE
  FOR ALL
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS inventory_movements_deny_client_access ON private.inventory_movements;
CREATE POLICY inventory_movements_deny_client_access ON private.inventory_movements
  AS RESTRICTIVE
  FOR ALL
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS legacy_records_deny_client_access ON private.legacy_records;
CREATE POLICY legacy_records_deny_client_access ON private.legacy_records
  AS RESTRICTIVE
  FOR ALL
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS migration_id_map_deny_client_access ON private.migration_id_map;
CREATE POLICY migration_id_map_deny_client_access ON private.migration_id_map
  AS RESTRICTIVE
  FOR ALL
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS newsletter_subscriptions_deny_client_access ON private.newsletter_subscriptions;
CREATE POLICY newsletter_subscriptions_deny_client_access ON private.newsletter_subscriptions
  AS RESTRICTIVE
  FOR ALL
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS order_gifts_deny_all ON private.order_gifts;
CREATE POLICY order_gifts_deny_all ON private.order_gifts
  FOR ALL
  TO PUBLIC
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS outbox_events_deny_client_access ON private.outbox_events;
CREATE POLICY outbox_events_deny_client_access ON private.outbox_events
  AS RESTRICTIVE
  FOR ALL
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS payment_events_deny_client_access ON private.payment_events;
CREATE POLICY payment_events_deny_client_access ON private.payment_events
  AS RESTRICTIVE
  FOR ALL
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS producer_application_kyc_deny_client_access ON private.producer_application_kyc;
CREATE POLICY producer_application_kyc_deny_client_access ON private.producer_application_kyc
  AS RESTRICTIVE
  FOR ALL
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS producer_documents_deny_client_access ON private.producer_documents;
CREATE POLICY producer_documents_deny_client_access ON private.producer_documents
  AS RESTRICTIVE
  FOR ALL
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS producer_follows_deny_all ON private.producer_follows;
CREATE POLICY producer_follows_deny_all ON private.producer_follows
  FOR ALL
  TO PUBLIC
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS product_public_content_archives_deny_all ON private.product_public_content_archives;
CREATE POLICY product_public_content_archives_deny_all ON private.product_public_content_archives
  FOR ALL
  TO PUBLIC
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS sensitive_access_log_no_direct_access ON private.sensitive_access_log;
CREATE POLICY sensitive_access_log_no_direct_access ON private.sensitive_access_log
  FOR ALL
  TO PUBLIC
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS stock_alert_subscriptions_deny_client_access ON private.stock_alert_subscriptions;
CREATE POLICY stock_alert_subscriptions_deny_client_access ON private.stock_alert_subscriptions
  AS RESTRICTIVE
  FOR ALL
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS submission_attempts_deny_direct_access ON private.submission_attempts;
CREATE POLICY submission_attempts_deny_direct_access ON private.submission_attempts
  FOR ALL
  TO PUBLIC
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS transactional_email_jobs_deny_direct_authenticated ON private.transactional_email_jobs;
CREATE POLICY transactional_email_jobs_deny_direct_authenticated ON private.transactional_email_jobs
  FOR ALL
  TO authenticated
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS user_blocks_deny_direct_access ON private.user_blocks;
CREATE POLICY user_blocks_deny_direct_access ON private.user_blocks
  FOR ALL
  TO PUBLIC
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS user_content_reports_deny_direct_access ON private.user_content_reports;
CREATE POLICY user_content_reports_deny_direct_access ON private.user_content_reports
  FOR ALL
  TO PUBLIC
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS user_roles_read_own ON private.user_roles;
CREATE POLICY user_roles_read_own ON private.user_roles
  FOR SELECT
  TO authenticated
  USING (((user_id = ( SELECT auth.uid() AS uid)) AND ((expires_at IS NULL) OR (expires_at > timezone('utc'::text, now())))));

DROP POLICY IF EXISTS user_terms_acceptances_deny_direct_access ON private.user_terms_acceptances;
CREATE POLICY user_terms_acceptances_deny_direct_access ON private.user_terms_acceptances
  FOR ALL
  TO PUBLIC
  USING (false)
  WITH CHECK (false);
