-- Schema drift closure, tables batch 12: campaigns, coupons and order
-- promotions (campaigns, coupons, campaign targeting joins, order promotions).
--
-- DDL generated by the database from its own catalogs via
-- scripts/generate-schema-ddl.sql, then md5-verified against that generated
-- text. Checked for constraint triggers: none in this batch. Foreign keys are
-- emitted after all CREATE TABLE statements so the file is order-independent.
--
-- Applying is a no-op against the live project.

CREATE TABLE IF NOT EXISTS public.campaign_categories (
  campaign_id uuid NOT NULL,
  category_id uuid NOT NULL,
  CONSTRAINT campaign_categories_pkey PRIMARY KEY (campaign_id, category_id)
);
ALTER TABLE public.campaign_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_categories FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.campaign_products (
  campaign_id uuid NOT NULL,
  product_id uuid NOT NULL,
  CONSTRAINT campaign_products_pkey PRIMARY KEY (campaign_id, product_id)
);
ALTER TABLE public.campaign_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_products FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL,
  title text NOT NULL,
  description text NOT NULL DEFAULT ''::text,
  banner_path text,
  discount_type text NOT NULL,
  discount_value integer NOT NULL DEFAULT 0,
  currency text,
  minimum_order_minor bigint NOT NULL DEFAULT 0,
  usage_limit integer,
  per_user_limit integer NOT NULL DEFAULT 1,
  starts_at timestamp with time zone NOT NULL,
  ends_at timestamp with time zone NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text,
  translations jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  target_scope text NOT NULL DEFAULT 'all'::text,
  activation_mode text NOT NULL DEFAULT 'automatic'::text,
  priority integer NOT NULL DEFAULT 0,
  max_discount_minor bigint,
  CONSTRAINT campaigns_slug_key UNIQUE (slug),
  CONSTRAINT campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT campaigns_activation_mode_check CHECK ((activation_mode = ANY (ARRAY['automatic'::text, 'coupon'::text]))),
  CONSTRAINT campaigns_check CHECK ((ends_at > starts_at)),
  CONSTRAINT campaigns_check1 CHECK ((((discount_type = 'percentage'::text) AND ((discount_value >= 1) AND (discount_value <= 10000))) OR ((discount_type = 'fixed'::text) AND (discount_value > 0) AND (currency IS NOT NULL)) OR ((discount_type = 'free_shipping'::text) AND (discount_value = 0)))),
  CONSTRAINT campaigns_currency_check CHECK (((currency IS NULL) OR (currency ~ '^[A-Z]{3}$'::text))),
  CONSTRAINT campaigns_discount_type_check CHECK ((discount_type = ANY (ARRAY['percentage'::text, 'fixed'::text, 'free_shipping'::text]))),
  CONSTRAINT campaigns_discount_value_check CHECK ((discount_value >= 0)),
  CONSTRAINT campaigns_max_discount_minor_check CHECK (((max_discount_minor IS NULL) OR (max_discount_minor > 0))),
  CONSTRAINT campaigns_minimum_order_minor_check CHECK ((minimum_order_minor >= 0)),
  CONSTRAINT campaigns_per_user_limit_check CHECK ((per_user_limit > 0)),
  CONSTRAINT campaigns_priority_check CHECK (((priority >= '-1000'::integer) AND (priority <= 1000))),
  CONSTRAINT campaigns_slug_check CHECK ((slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'::text)),
  CONSTRAINT campaigns_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'scheduled'::text, 'active'::text, 'paused'::text, 'ended'::text]))),
  CONSTRAINT campaigns_target_scope_check CHECK ((target_scope = ANY (ARRAY['all'::text, 'products'::text, 'categories'::text]))),
  CONSTRAINT campaigns_translations_check CHECK ((jsonb_typeof(translations) = 'object'::text)),
  CONSTRAINT campaigns_usage_limit_check CHECK (((usage_limit IS NULL) OR (usage_limit > 0)))
);
ALTER TABLE public.campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaigns FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.coupons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid NOT NULL,
  code_hash text NOT NULL,
  display_hint text,
  status text NOT NULL DEFAULT 'active'::text,
  starts_at timestamp with time zone,
  ends_at timestamp with time zone,
  usage_limit integer,
  per_user_limit integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT coupons_code_hash_key UNIQUE (code_hash),
  CONSTRAINT coupons_pkey PRIMARY KEY (id),
  CONSTRAINT coupons_check CHECK (((ends_at IS NULL) OR (starts_at IS NULL) OR (ends_at > starts_at))),
  CONSTRAINT coupons_per_user_limit_check CHECK ((per_user_limit > 0)),
  CONSTRAINT coupons_status_check CHECK ((status = ANY (ARRAY['active'::text, 'disabled'::text, 'expired'::text]))),
  CONSTRAINT coupons_usage_limit_check CHECK (((usage_limit IS NULL) OR (usage_limit > 0)))
);
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.order_promotions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  campaign_id uuid NOT NULL,
  coupon_id uuid,
  product_discount_minor bigint NOT NULL DEFAULT 0,
  shipping_discount_minor bigint NOT NULL DEFAULT 0,
  total_discount_minor bigint NOT NULL,
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT order_promotions_order_id_key UNIQUE (order_id),
  CONSTRAINT order_promotions_pkey PRIMARY KEY (id),
  CONSTRAINT order_promotions_check CHECK ((total_discount_minor = (product_discount_minor + shipping_discount_minor))),
  CONSTRAINT order_promotions_product_discount_minor_check CHECK ((product_discount_minor >= 0)),
  CONSTRAINT order_promotions_shipping_discount_minor_check CHECK ((shipping_discount_minor >= 0)),
  CONSTRAINT order_promotions_snapshot_check CHECK ((jsonb_typeof(snapshot) = 'object'::text)),
  CONSTRAINT order_promotions_total_discount_minor_check CHECK ((total_discount_minor >= 0))
);
ALTER TABLE public.order_promotions ENABLE ROW LEVEL SECURITY;

-- foreign keys (added after all tables exist)

ALTER TABLE public.campaign_categories ADD CONSTRAINT campaign_categories_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_categories ADD CONSTRAINT campaign_categories_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_products ADD CONSTRAINT campaign_products_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_products ADD CONSTRAINT campaign_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.coupons ADD CONSTRAINT coupons_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.order_promotions ADD CONSTRAINT order_promotions_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE RESTRICT;
ALTER TABLE public.order_promotions ADD CONSTRAINT order_promotions_coupon_id_fkey FOREIGN KEY (coupon_id) REFERENCES coupons(id) ON DELETE SET NULL;
ALTER TABLE public.order_promotions ADD CONSTRAINT order_promotions_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT;
