-- Schema drift closure, tables batch 10: orders and payment records
-- (orders, order items, order status history, payment records, refunds).
--
-- DDL generated by the database from its own catalogs via
-- scripts/generate-schema-ddl.sql, then md5-verified against that generated
-- text. Checked for constraint triggers: none in this batch. Foreign keys are
-- emitted after all CREATE TABLE statements so the file is order-independent.
--
-- Applying is a no-op against the live project.

CREATE TABLE IF NOT EXISTS public.order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  product_id uuid,
  variant_id uuid,
  producer_id uuid,
  product_name text NOT NULL,
  variant_name text,
  sku text,
  image_path text,
  quantity integer NOT NULL,
  unit_price_minor bigint NOT NULL,
  discount_minor bigint NOT NULL DEFAULT 0,
  tax_minor bigint NOT NULL DEFAULT 0,
  line_total_minor bigint NOT NULL,
  fulfillment_status text NOT NULL DEFAULT 'unfulfilled'::text,
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  commission_basis_points_snapshot integer NOT NULL DEFAULT 0,
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_check CHECK ((line_total_minor = (((unit_price_minor * quantity) - discount_minor) + tax_minor))),
  CONSTRAINT order_items_commission_snapshot_check CHECK (((commission_basis_points_snapshot >= 0) AND (commission_basis_points_snapshot <= 10000))),
  CONSTRAINT order_items_discount_minor_check CHECK ((discount_minor >= 0)),
  CONSTRAINT order_items_fulfillment_status_check CHECK ((fulfillment_status = ANY (ARRAY['unfulfilled'::text, 'processing'::text, 'fulfilled'::text, 'returned'::text, 'cancelled'::text]))),
  CONSTRAINT order_items_line_total_minor_check CHECK ((line_total_minor >= 0)),
  CONSTRAINT order_items_quantity_check CHECK ((quantity > 0)),
  CONSTRAINT order_items_snapshot_check CHECK ((jsonb_typeof(snapshot) = 'object'::text)),
  CONSTRAINT order_items_tax_minor_check CHECK ((tax_minor >= 0)),
  CONSTRAINT order_items_unit_price_minor_check CHECK ((unit_price_minor >= 0))
);
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.order_status_history (
  id bigint GENERATED ALWAYS AS IDENTITY,
  order_id uuid NOT NULL,
  from_status text,
  to_status text NOT NULL,
  note text,
  visible_to_customer boolean NOT NULL DEFAULT true,
  actor_user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT order_status_history_pkey PRIMARY KEY (id)
);
ALTER TABLE public.order_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_status_history FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  legacy_source text,
  legacy_id text,
  order_number text NOT NULL,
  user_id uuid NOT NULL,
  cart_id uuid,
  status text NOT NULL DEFAULT 'pending_payment'::text,
  payment_status text NOT NULL DEFAULT 'unpaid'::text,
  fulfillment_status text NOT NULL DEFAULT 'unfulfilled'::text,
  currency text NOT NULL DEFAULT 'TRY'::text,
  subtotal_minor bigint NOT NULL,
  discount_minor bigint NOT NULL DEFAULT 0,
  tax_minor bigint NOT NULL DEFAULT 0,
  shipping_minor bigint NOT NULL DEFAULT 0,
  total_minor bigint NOT NULL,
  shipping_address jsonb NOT NULL,
  billing_address jsonb,
  customer_note text,
  internal_note text,
  placed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  checkout_idempotency_key text,
  reservation_expires_at timestamp with time zone,
  accounting_archived_at timestamp with time zone,
  accounting_period_id uuid,
  CONSTRAINT orders_legacy_source_legacy_id_key UNIQUE (legacy_source, legacy_id),
  CONSTRAINT orders_order_number_key UNIQUE (order_number),
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_billing_address_check CHECK (((billing_address IS NULL) OR (jsonb_typeof(billing_address) = 'object'::text))),
  CONSTRAINT orders_check CHECK ((total_minor = (((subtotal_minor - discount_minor) + tax_minor) + shipping_minor))),
  CONSTRAINT orders_check1 CHECK ((discount_minor <= ((subtotal_minor + tax_minor) + shipping_minor))),
  CONSTRAINT orders_currency_check CHECK ((currency ~ '^[A-Z]{3}$'::text)),
  CONSTRAINT orders_discount_minor_check CHECK ((discount_minor >= 0)),
  CONSTRAINT orders_fulfillment_status_check CHECK ((fulfillment_status = ANY (ARRAY['unfulfilled'::text, 'processing'::text, 'partially_fulfilled'::text, 'fulfilled'::text, 'returned'::text]))),
  CONSTRAINT orders_payment_status_check CHECK ((payment_status = ANY (ARRAY['unpaid'::text, 'authorized'::text, 'partially_paid'::text, 'paid'::text, 'partially_refunded'::text, 'refunded'::text, 'failed'::text, 'disputed'::text]))),
  CONSTRAINT orders_reservation_expiry_check CHECK (((reservation_expires_at IS NULL) OR (reservation_expires_at > created_at))),
  CONSTRAINT orders_shipping_address_check CHECK ((jsonb_typeof(shipping_address) = 'object'::text)),
  CONSTRAINT orders_shipping_minor_check CHECK ((shipping_minor >= 0)),
  CONSTRAINT orders_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'pending_payment'::text, 'confirmed'::text, 'preparing'::text, 'partially_shipped'::text, 'shipped'::text, 'delivered'::text, 'completed'::text, 'cancelled'::text, 'refunded'::text]))),
  CONSTRAINT orders_subtotal_minor_check CHECK ((subtotal_minor >= 0)),
  CONSTRAINT orders_tax_minor_check CHECK ((tax_minor >= 0)),
  CONSTRAINT orders_total_minor_check CHECK ((total_minor >= 0))
);
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.payment_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  user_id uuid NOT NULL,
  provider text NOT NULL,
  provider_reference text,
  payment_method_type text NOT NULL,
  amount_minor bigint NOT NULL,
  currency text NOT NULL,
  status text NOT NULL DEFAULT 'created'::text,
  failure_code text,
  failure_message text,
  authorized_at timestamp with time zone,
  captured_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  subject_type text NOT NULL,
  subject_id uuid NOT NULL,
  CONSTRAINT payment_records_provider_provider_reference_key UNIQUE (provider, provider_reference),
  CONSTRAINT payment_records_pkey PRIMARY KEY (id),
  CONSTRAINT payment_records_amount_minor_check CHECK ((amount_minor > 0)),
  CONSTRAINT payment_records_currency_check CHECK ((currency ~ '^[A-Z]{3}$'::text)),
  CONSTRAINT payment_records_payment_method_type_check CHECK ((payment_method_type = ANY (ARRAY['card'::text, 'bank_transfer'::text, 'cash_on_delivery'::text, 'wallet'::text, 'other'::text]))),
  CONSTRAINT payment_records_status_check CHECK ((status = ANY (ARRAY['created'::text, 'pending'::text, 'authorized'::text, 'captured'::text, 'failed'::text, 'cancelled'::text, 'partially_refunded'::text, 'refunded'::text, 'disputed'::text]))),
  CONSTRAINT payment_records_subject_consistency_check CHECK ((((subject_type = 'order'::text) AND (order_id IS NOT NULL) AND (subject_id = order_id)) OR ((subject_type = 'event_reservation'::text) AND (order_id IS NULL)))),
  CONSTRAINT payment_records_subject_type_check CHECK ((subject_type = ANY (ARRAY['order'::text, 'event_reservation'::text])))
);
ALTER TABLE public.payment_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_records FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.refunds (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  return_id uuid,
  payment_id uuid,
  amount_minor bigint NOT NULL,
  currency text NOT NULL,
  reason text NOT NULL,
  provider_reference text,
  status text NOT NULL DEFAULT 'pending'::text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  provider text,
  processed_at timestamp with time zone,
  failure_code text,
  failure_message text,
  CONSTRAINT refunds_pkey PRIMARY KEY (id),
  CONSTRAINT refunds_amount_minor_check CHECK ((amount_minor > 0)),
  CONSTRAINT refunds_currency_check CHECK ((currency ~ '^[A-Z]{3}$'::text)),
  CONSTRAINT refunds_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'succeeded'::text, 'failed'::text, 'cancelled'::text])))
);
ALTER TABLE public.refunds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.refunds FORCE ROW LEVEL SECURITY;

-- foreign keys (added after all tables exist)

ALTER TABLE public.order_items ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT;
ALTER TABLE public.order_items ADD CONSTRAINT order_items_producer_id_fkey FOREIGN KEY (producer_id) REFERENCES producers(id) ON DELETE SET NULL;
ALTER TABLE public.order_items ADD CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.order_items ADD CONSTRAINT order_items_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE SET NULL;
ALTER TABLE public.order_status_history ADD CONSTRAINT order_status_history_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.order_status_history ADD CONSTRAINT order_status_history_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
ALTER TABLE public.orders ADD CONSTRAINT orders_accounting_period_id_fkey FOREIGN KEY (accounting_period_id) REFERENCES private.accounting_periods(id) ON DELETE SET NULL;
ALTER TABLE public.orders ADD CONSTRAINT orders_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES carts(id) ON DELETE SET NULL;
ALTER TABLE public.orders ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.payment_records ADD CONSTRAINT payment_records_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT;
ALTER TABLE public.payment_records ADD CONSTRAINT payment_records_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.refunds ADD CONSTRAINT refunds_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT;
ALTER TABLE public.refunds ADD CONSTRAINT refunds_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES payment_records(id) ON DELETE SET NULL;
ALTER TABLE public.refunds ADD CONSTRAINT refunds_return_id_fkey FOREIGN KEY (return_id) REFERENCES return_requests(id) ON DELETE SET NULL;
