-- Schema drift closure, tables batch 6: identity, KYC and authorisation
-- (producer application KYC, verification documents, trust badge history,
-- producer follows, permission catalogue, role-permission grants, user roles).
--
-- DDL generated by the database from its own catalogs via
-- scripts/generate-schema-ddl.sql, then md5-verified against that generated
-- text. Foreign keys are emitted after all CREATE TABLE statements so the file
-- is order-independent.
--
-- Applying is a no-op against the live project.

CREATE TABLE IF NOT EXISTS private.permissions (
  permission_key text NOT NULL,
  domain text NOT NULL,
  description text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT permissions_pkey PRIMARY KEY (permission_key),
  CONSTRAINT permissions_description_length_check CHECK (((char_length(description) >= 3) AND (char_length(description) <= 300))),
  CONSTRAINT permissions_domain_format_check CHECK ((domain ~ '^[a-z][a-z0-9_]*$'::text)),
  CONSTRAINT permissions_domain_matches_key_check CHECK ((domain = split_part(permission_key, '.'::text, 1))),
  CONSTRAINT permissions_key_format_check CHECK ((permission_key ~ '^[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*$'::text))
);
ALTER TABLE private.permissions ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.producer_application_kyc (
  application_id uuid NOT NULL,
  legal_name text NOT NULL,
  national_id_ciphertext text,
  tax_office text,
  tax_number_ciphertext text,
  iban_ciphertext text,
  bank_account_holder text,
  phone text NOT NULL,
  address jsonb NOT NULL,
  consent_version text NOT NULL,
  consented_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  contact_email text,
  mersis_number_ciphertext text,
  tax_exemption_number_ciphertext text,
  food_registration_number_ciphertext text,
  contact_email_verified_at timestamp with time zone,
  phone_verified_at timestamp with time zone,
  phone_verified_by uuid,
  organic_certificate_number_ciphertext text,
  CONSTRAINT producer_application_kyc_pkey PRIMARY KEY (application_id),
  CONSTRAINT producer_application_kyc_address_check CHECK ((jsonb_typeof(address) = 'object'::text))
);
ALTER TABLE private.producer_application_kyc ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.producer_application_kyc FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.producer_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL,
  document_type text NOT NULL,
  storage_path text NOT NULL,
  mime_type text NOT NULL,
  size_bytes bigint NOT NULL,
  checksum_sha256 text,
  verification_status text NOT NULL DEFAULT 'pending'::text,
  verified_by uuid,
  verified_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT producer_documents_application_id_document_type_storage_pat_key UNIQUE (application_id, document_type, storage_path),
  CONSTRAINT producer_documents_pkey PRIMARY KEY (id),
  CONSTRAINT producer_documents_document_type_check CHECK ((document_type = ANY (ARRAY['identity'::text, 'cks'::text, 'organic_certificate'::text, 'business_registration'::text, 'tax_certificate'::text, 'bank_proof'::text, 'food_business_registration'::text, 'food_business_approval'::text, 'tax_exemption_certificate'::text, 'mersis_record'::text, 'cooperative_registration'::text, 'residence_proof'::text, 'other'::text]))),
  CONSTRAINT producer_documents_size_bytes_check CHECK (((size_bytes > 0) AND (size_bytes <= 20971520))),
  CONSTRAINT producer_documents_verification_status_check CHECK ((verification_status = ANY (ARRAY['pending'::text, 'verified'::text, 'rejected'::text, 'expired'::text])))
);
ALTER TABLE private.producer_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.producer_documents FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.producer_follows (
  user_id uuid NOT NULL,
  producer_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT producer_follows_pkey PRIMARY KEY (user_id, producer_id)
);
ALTER TABLE private.producer_follows ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.producer_trust_badge_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  producer_id uuid NOT NULL,
  actor_user_id uuid,
  action text NOT NULL,
  reason text NOT NULL,
  review_due_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT producer_trust_badge_events_pkey PRIMARY KEY (id),
  CONSTRAINT producer_trust_badge_events_action_check CHECK ((action = ANY (ARRAY['granted'::text, 'revoked'::text, 'auto_revoked'::text]))),
  CONSTRAINT producer_trust_badge_events_reason_check CHECK (((char_length(reason) >= 10) AND (char_length(reason) <= 1000)))
);
ALTER TABLE private.producer_trust_badge_events ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.role_permissions (
  role text NOT NULL,
  permission_key text NOT NULL,
  granted_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  granted_by uuid,
  CONSTRAINT role_permissions_pkey PRIMARY KEY (role, permission_key),
  CONSTRAINT role_permissions_role_check CHECK ((role = ANY (ARRAY['customer'::text, 'producer'::text, 'support'::text, 'content_editor'::text, 'operations'::text, 'moderator'::text, 'admin'::text, 'super_admin'::text])))
);
ALTER TABLE private.role_permissions ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS private.user_roles (
  user_id uuid NOT NULL,
  role text NOT NULL,
  granted_by uuid,
  granted_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  expires_at timestamp with time zone,
  CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role),
  CONSTRAINT user_roles_check CHECK (((expires_at IS NULL) OR (expires_at > granted_at))),
  CONSTRAINT user_roles_role_check CHECK ((role = ANY (ARRAY['customer'::text, 'producer'::text, 'support'::text, 'content_editor'::text, 'operations'::text, 'moderator'::text, 'admin'::text, 'super_admin'::text])))
);
ALTER TABLE private.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.user_roles FORCE ROW LEVEL SECURITY;

-- foreign keys (added after all tables exist)

ALTER TABLE private.producer_application_kyc ADD CONSTRAINT producer_application_kyc_application_id_fkey FOREIGN KEY (application_id) REFERENCES producer_applications(id) ON DELETE CASCADE;
ALTER TABLE private.producer_application_kyc ADD CONSTRAINT producer_application_kyc_phone_verified_by_fkey FOREIGN KEY (phone_verified_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE private.producer_documents ADD CONSTRAINT producer_documents_application_id_fkey FOREIGN KEY (application_id) REFERENCES producer_applications(id) ON DELETE CASCADE;
ALTER TABLE private.producer_documents ADD CONSTRAINT producer_documents_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE private.producer_follows ADD CONSTRAINT producer_follows_producer_id_fkey FOREIGN KEY (producer_id) REFERENCES producers(id) ON DELETE CASCADE;
ALTER TABLE private.producer_follows ADD CONSTRAINT producer_follows_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE private.producer_trust_badge_events ADD CONSTRAINT producer_trust_badge_events_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE private.producer_trust_badge_events ADD CONSTRAINT producer_trust_badge_events_producer_id_fkey FOREIGN KEY (producer_id) REFERENCES producers(id) ON DELETE CASCADE;
ALTER TABLE private.role_permissions ADD CONSTRAINT role_permissions_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE private.role_permissions ADD CONSTRAINT role_permissions_permission_key_fkey FOREIGN KEY (permission_key) REFERENCES private.permissions(permission_key) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE private.user_roles ADD CONSTRAINT user_roles_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE private.user_roles ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
