-- Schema drift closure, RLS policies part 2: public schema, tables a-o
-- (35 policies).
--
-- Policy DDL generated by the database from pg_policy, then md5-verified
-- against that generated text (184dc9b63dbc29a1ded0ae7127c8f57f). The
-- DROP POLICY IF EXISTS guards below are added for replayability and are not
-- part of the generated output; verification compares CREATE statements only.
--
-- This is where the storefront's actual access model lives. Three patterns
-- recur:
--
--   own-row access - addresses, carts, cart_items, favorites, notifications,
--   conversation_participants, event_reservations. Each is scoped to
--   auth.uid(). cart_items reaches through to carts and additionally requires
--   the cart to still be active, so items cannot be added to a converted or
--   abandoned cart.
--
--   time-bounded public read - campaigns and their targeting joins are visible
--   to anon only while status is active and now() falls inside the campaign
--   window. An expired or paused campaign disappears from the public API
--   automatically, with no scheduled job involved.
--
--   participant-scoped messaging - conversations and messages are readable
--   only by a row in conversation_participants. messages_insert_participant
--   additionally pins sender_user_id to the caller and restricts message_type
--   to text/image/file, so a client cannot forge a message from someone else
--   or inject a 'system' message.
--
-- Two deliberate denials worth noting: coupons carries a RESTRICTIVE deny, so
-- coupon rows - even the hashes - are unreachable from any client, and
-- order_status_history is filtered on visible_to_customer, so internal
-- operational notes never reach the customer timeline.
--
-- Applying is a no-op against the live project.

DROP POLICY IF EXISTS addresses_manage_own ON public.addresses;
CREATE POLICY addresses_manage_own ON public.addresses
  FOR ALL
  TO authenticated
  USING ((user_id = ( SELECT auth.uid() AS uid)))
  WITH CHECK ((user_id = ( SELECT auth.uid() AS uid)));

DROP POLICY IF EXISTS brand_settings_public_read ON public.brand_settings;
CREATE POLICY brand_settings_public_read ON public.brand_settings
  FOR SELECT
  TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS campaign_categories_admin_delete ON public.campaign_categories;
CREATE POLICY campaign_categories_admin_delete ON public.campaign_categories
  FOR DELETE
  TO authenticated
  USING (( SELECT private.is_admin() AS is_admin));

DROP POLICY IF EXISTS campaign_categories_admin_insert ON public.campaign_categories;
CREATE POLICY campaign_categories_admin_insert ON public.campaign_categories
  FOR INSERT
  TO authenticated
  WITH CHECK (( SELECT private.is_admin() AS is_admin));

DROP POLICY IF EXISTS campaign_categories_admin_update ON public.campaign_categories;
CREATE POLICY campaign_categories_admin_update ON public.campaign_categories
  FOR UPDATE
  TO authenticated
  USING (( SELECT private.is_admin() AS is_admin))
  WITH CHECK (( SELECT private.is_admin() AS is_admin));

DROP POLICY IF EXISTS campaign_categories_authenticated_read ON public.campaign_categories;
CREATE POLICY campaign_categories_authenticated_read ON public.campaign_categories
  FOR SELECT
  TO authenticated
  USING (((EXISTS ( SELECT 1
   FROM campaigns campaign
  WHERE ((campaign.id = campaign_categories.campaign_id) AND (campaign.status = 'active'::text) AND ((timezone('utc'::text, now()) >= campaign.starts_at) AND (timezone('utc'::text, now()) <= campaign.ends_at))))) OR ( SELECT private.is_admin() AS is_admin)));

DROP POLICY IF EXISTS campaign_categories_public_read ON public.campaign_categories;
CREATE POLICY campaign_categories_public_read ON public.campaign_categories
  FOR SELECT
  TO anon
  USING ((EXISTS ( SELECT 1
   FROM campaigns campaign
  WHERE ((campaign.id = campaign_categories.campaign_id) AND (campaign.status = 'active'::text) AND ((timezone('utc'::text, now()) >= campaign.starts_at) AND (timezone('utc'::text, now()) <= campaign.ends_at))))));

DROP POLICY IF EXISTS campaign_products_admin_delete ON public.campaign_products;
CREATE POLICY campaign_products_admin_delete ON public.campaign_products
  FOR DELETE
  TO authenticated
  USING (( SELECT private.is_admin() AS is_admin));

DROP POLICY IF EXISTS campaign_products_admin_insert ON public.campaign_products;
CREATE POLICY campaign_products_admin_insert ON public.campaign_products
  FOR INSERT
  TO authenticated
  WITH CHECK (( SELECT private.is_admin() AS is_admin));

DROP POLICY IF EXISTS campaign_products_admin_update ON public.campaign_products;
CREATE POLICY campaign_products_admin_update ON public.campaign_products
  FOR UPDATE
  TO authenticated
  USING (( SELECT private.is_admin() AS is_admin))
  WITH CHECK (( SELECT private.is_admin() AS is_admin));

DROP POLICY IF EXISTS campaign_products_authenticated_read ON public.campaign_products;
CREATE POLICY campaign_products_authenticated_read ON public.campaign_products
  FOR SELECT
  TO authenticated
  USING (((EXISTS ( SELECT 1
   FROM campaigns campaign
  WHERE ((campaign.id = campaign_products.campaign_id) AND (campaign.status = 'active'::text) AND ((timezone('utc'::text, now()) >= campaign.starts_at) AND (timezone('utc'::text, now()) <= campaign.ends_at))))) OR ( SELECT private.is_admin() AS is_admin)));

DROP POLICY IF EXISTS campaign_products_public_read ON public.campaign_products;
CREATE POLICY campaign_products_public_read ON public.campaign_products
  FOR SELECT
  TO anon
  USING ((EXISTS ( SELECT 1
   FROM campaigns campaign
  WHERE ((campaign.id = campaign_products.campaign_id) AND (campaign.status = 'active'::text) AND ((timezone('utc'::text, now()) >= campaign.starts_at) AND (timezone('utc'::text, now()) <= campaign.ends_at))))));

DROP POLICY IF EXISTS campaigns_admin_insert ON public.campaigns;
CREATE POLICY campaigns_admin_insert ON public.campaigns
  FOR INSERT
  TO authenticated
  WITH CHECK (( SELECT private.is_admin() AS is_admin));

DROP POLICY IF EXISTS campaigns_admin_update ON public.campaigns;
CREATE POLICY campaigns_admin_update ON public.campaigns
  FOR UPDATE
  TO authenticated
  USING (( SELECT private.is_admin() AS is_admin))
  WITH CHECK (( SELECT private.is_admin() AS is_admin));

DROP POLICY IF EXISTS campaigns_authenticated_read ON public.campaigns;
CREATE POLICY campaigns_authenticated_read ON public.campaigns
  FOR SELECT
  TO authenticated
  USING ((((status = 'active'::text) AND ((timezone('utc'::text, now()) >= starts_at) AND (timezone('utc'::text, now()) <= ends_at))) OR ( SELECT private.is_admin() AS is_admin)));

DROP POLICY IF EXISTS campaigns_public_read ON public.campaigns;
CREATE POLICY campaigns_public_read ON public.campaigns
  FOR SELECT
  TO anon
  USING (((status = 'active'::text) AND ((timezone('utc'::text, now()) >= starts_at) AND (timezone('utc'::text, now()) <= ends_at))));

DROP POLICY IF EXISTS cart_items_manage_own ON public.cart_items;
CREATE POLICY cart_items_manage_own ON public.cart_items
  FOR ALL
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM carts cart
  WHERE ((cart.id = cart_items.cart_id) AND (cart.user_id = ( SELECT auth.uid() AS uid)) AND (cart.status = 'active'::text)))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM carts cart
  WHERE ((cart.id = cart_items.cart_id) AND (cart.user_id = ( SELECT auth.uid() AS uid)) AND (cart.status = 'active'::text)))));

DROP POLICY IF EXISTS carts_manage_own ON public.carts;
CREATE POLICY carts_manage_own ON public.carts
  FOR ALL
  TO authenticated
  USING ((user_id = ( SELECT auth.uid() AS uid)))
  WITH CHECK ((user_id = ( SELECT auth.uid() AS uid)));

DROP POLICY IF EXISTS categories_public_read ON public.categories;
CREATE POLICY categories_public_read ON public.categories
  FOR SELECT
  TO anon, authenticated
  USING ((is_active = true));

DROP POLICY IF EXISTS content_entries_public_read ON public.content_entries;
CREATE POLICY content_entries_public_read ON public.content_entries
  FOR SELECT
  TO anon, authenticated
  USING (((status = 'published'::text) AND (published_at <= timezone('utc'::text, now())) AND (deleted_at IS NULL)));

DROP POLICY IF EXISTS conversation_participants_read_own ON public.conversation_participants;
CREATE POLICY conversation_participants_read_own ON public.conversation_participants
  FOR SELECT
  TO authenticated
  USING ((user_id = ( SELECT auth.uid() AS uid)));

DROP POLICY IF EXISTS conversation_participants_update_own ON public.conversation_participants;
CREATE POLICY conversation_participants_update_own ON public.conversation_participants
  FOR UPDATE
  TO authenticated
  USING ((user_id = ( SELECT auth.uid() AS uid)))
  WITH CHECK ((user_id = ( SELECT auth.uid() AS uid)));

DROP POLICY IF EXISTS conversations_read_participant ON public.conversations;
CREATE POLICY conversations_read_participant ON public.conversations
  FOR SELECT
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM conversation_participants participant
  WHERE ((participant.conversation_id = conversations.id) AND (participant.user_id = ( SELECT auth.uid() AS uid))))));

DROP POLICY IF EXISTS coupons_deny_client_access ON public.coupons;
CREATE POLICY coupons_deny_client_access ON public.coupons
  AS RESTRICTIVE
  FOR ALL
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS event_reservations_read_own ON public.event_reservations;
CREATE POLICY event_reservations_read_own ON public.event_reservations
  FOR SELECT
  TO authenticated
  USING ((user_id = ( SELECT auth.uid() AS uid)));

DROP POLICY IF EXISTS events_public_read ON public.events;
CREATE POLICY events_public_read ON public.events
  FOR SELECT
  TO anon, authenticated
  USING ((status = ANY (ARRAY['published'::text, 'sold_out'::text, 'completed'::text])));

DROP POLICY IF EXISTS favorites_manage_own ON public.favorites;
CREATE POLICY favorites_manage_own ON public.favorites
  FOR ALL
  TO authenticated
  USING ((user_id = ( SELECT auth.uid() AS uid)))
  WITH CHECK ((user_id = ( SELECT auth.uid() AS uid)));

DROP POLICY IF EXISTS messages_insert_participant ON public.messages;
CREATE POLICY messages_insert_participant ON public.messages
  FOR INSERT
  TO authenticated
  WITH CHECK (((sender_user_id = ( SELECT auth.uid() AS uid)) AND (message_type = ANY (ARRAY['text'::text, 'image'::text, 'file'::text])) AND (EXISTS ( SELECT 1
   FROM conversation_participants participant
  WHERE ((participant.conversation_id = messages.conversation_id) AND (participant.user_id = ( SELECT auth.uid() AS uid)))))));

DROP POLICY IF EXISTS messages_read_participant ON public.messages;
CREATE POLICY messages_read_participant ON public.messages
  FOR SELECT
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM conversation_participants participant
  WHERE ((participant.conversation_id = messages.conversation_id) AND (participant.user_id = ( SELECT auth.uid() AS uid))))));

DROP POLICY IF EXISTS notifications_read_own ON public.notifications;
CREATE POLICY notifications_read_own ON public.notifications
  FOR SELECT
  TO authenticated
  USING ((user_id = ( SELECT auth.uid() AS uid)));

DROP POLICY IF EXISTS notifications_update_own ON public.notifications;
CREATE POLICY notifications_update_own ON public.notifications
  FOR UPDATE
  TO authenticated
  USING ((user_id = ( SELECT auth.uid() AS uid)))
  WITH CHECK ((user_id = ( SELECT auth.uid() AS uid)));

DROP POLICY IF EXISTS order_item_preparation_events_deny_direct ON public.order_item_preparation_events;
CREATE POLICY order_item_preparation_events_deny_direct ON public.order_item_preparation_events
  FOR ALL
  TO PUBLIC
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS order_items_authenticated_read ON public.order_items;
CREATE POLICY order_items_authenticated_read ON public.order_items
  FOR SELECT
  TO authenticated
  USING (((EXISTS ( SELECT 1
   FROM orders customer_order
  WHERE ((customer_order.id = order_items.order_id) AND (customer_order.user_id = ( SELECT auth.uid() AS uid))))) OR ( SELECT private.is_admin() AS is_admin)));

DROP POLICY IF EXISTS order_promotions_customer_read ON public.order_promotions;
CREATE POLICY order_promotions_customer_read ON public.order_promotions
  FOR SELECT
  TO authenticated
  USING (((EXISTS ( SELECT 1
   FROM orders customer_order
  WHERE ((customer_order.id = order_promotions.order_id) AND (customer_order.user_id = ( SELECT auth.uid() AS uid))))) OR ( SELECT private.is_admin() AS is_admin)));

DROP POLICY IF EXISTS order_status_history_read_own ON public.order_status_history;
CREATE POLICY order_status_history_read_own ON public.order_status_history
  FOR SELECT
  TO authenticated
  USING (((visible_to_customer = true) AND (EXISTS ( SELECT 1
   FROM orders customer_order
  WHERE ((customer_order.id = order_status_history.order_id) AND (customer_order.user_id = ( SELECT auth.uid() AS uid)))))));
