create table if not exists private.transactional_email_jobs (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('order_payment_receipt','event_payment_receipt')),
  aggregate_id uuid not null,
  user_id uuid not null,
  payload jsonb not null check (jsonb_typeof(payload)='object'),
  status text not null default 'pending' check (status in ('pending','processing','failed','sent','dead_letter')),
  attempts integer not null default 0 check (attempts between 0 and 100),
  available_at timestamptz not null default timezone('utc',now()),
  locked_at timestamptz,
  locked_by text,
  provider_message_id text,
  last_error text,
  created_at timestamptz not null default timezone('utc',now()),
  sent_at timestamptz,
  unique(kind,aggregate_id)
);

alter table private.transactional_email_jobs enable row level security;
revoke all on table private.transactional_email_jobs from public,anon,authenticated;
revoke all on sequence private.transactional_email_jobs_id_seq from public,anon,authenticated;
create index if not exists transactional_email_jobs_queue_idx on private.transactional_email_jobs(available_at,id) where status in ('pending','failed','processing');
create index if not exists transactional_email_jobs_user_idx on private.transactional_email_jobs(user_id,created_at desc);

create or replace function private.build_order_payment_receipt_payload_v1(p_order_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path to ''
as $function$
declare
  o public.orders%rowtype;
  recipient_email text;
  recipient_name text;
  recipient_locale text;
  payment_provider text;
  payment_method text;
  paid_at timestamptz;
  items jsonb;
begin
  select * into o from public.orders where id=p_order_id;
  if o.id is null then raise exception 'order_not_found' using errcode='P0002'; end if;
  if o.payment_status<>'paid' then raise exception 'order_not_paid' using errcode='55000'; end if;

  select lower(btrim(coalesce(u.email,''))),nullif(btrim(coalesce(p.display_name,'')),''),coalesce(nullif(btrim(p.locale),''),'tr')
  into recipient_email,recipient_name,recipient_locale
  from auth.users u left join public.profiles p on p.id=u.id
  where u.id=o.user_id;

  select pr.provider,pr.payment_method_type,coalesce(pr.captured_at,pr.updated_at)
  into payment_provider,payment_method,paid_at
  from public.payment_records pr
  where pr.order_id=o.id and pr.status='captured'
  order by pr.captured_at desc nulls last,pr.updated_at desc
  limit 1;

  select coalesce(jsonb_agg(jsonb_build_object(
    'name',oi.product_name,
    'variant',nullif(btrim(coalesce(oi.variant_name,'')),''),
    'quantity',oi.quantity,
    'lineTotalMinor',oi.line_total_minor
  ) order by oi.created_at,oi.id),'[]'::jsonb)
  into items
  from public.order_items oi where oi.order_id=o.id;

  return jsonb_build_object(
    'schemaVersion',1,
    'documentKind','payment_receipt',
    'legalInvoice',false,
    'recipientEmail',recipient_email,
    'recipientName',recipient_name,
    'locale',recipient_locale,
    'orderId',o.id,
    'orderNumber',o.order_number,
    'currency',o.currency,
    'subtotalMinor',o.subtotal_minor,
    'discountMinor',o.discount_minor,
    'taxMinor',o.tax_minor,
    'shippingMinor',o.shipping_minor,
    'totalMinor',o.total_minor,
    'placedAt',o.placed_at,
    'paidAt',paid_at,
    'paymentProvider',payment_provider,
    'paymentMethod',payment_method,
    'items',items
  );
end;
$function$;

create or replace function private.build_event_payment_receipt_payload_v1(p_reservation_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path to ''
as $function$
declare
  f private.event_reservation_finance%rowtype;
  r public.event_reservations%rowtype;
  event_title text;
  recipient_email text;
  recipient_name text;
  recipient_locale text;
begin
  select * into f from private.event_reservation_finance where reservation_id=p_reservation_id;
  if f.reservation_id is null then raise exception 'event_finance_not_found' using errcode='P0002'; end if;
  if f.payment_status<>'paid' then raise exception 'event_payment_not_paid' using errcode='55000'; end if;
  select * into r from public.event_reservations where id=p_reservation_id;
  if r.id is null then raise exception 'event_reservation_not_found' using errcode='P0002'; end if;
  select e.title into event_title from public.events e where e.id=r.event_id;
  select lower(btrim(coalesce(u.email,''))),coalesce(nullif(btrim(coalesce(p.display_name,'')),''),nullif(btrim(coalesce(r.guest_name,'')),'')),coalesce(nullif(btrim(p.locale),''),'tr')
  into recipient_email,recipient_name,recipient_locale
  from auth.users u left join public.profiles p on p.id=u.id
  where u.id=f.user_id;

  return jsonb_build_object(
    'schemaVersion',1,
    'documentKind','event_payment_receipt',
    'legalInvoice',false,
    'recipientEmail',recipient_email,
    'recipientName',recipient_name,
    'locale',recipient_locale,
    'reservationId',r.id,
    'reservationCode',r.reservation_code,
    'eventId',r.event_id,
    'eventTitle',event_title,
    'guestCount',f.guest_count,
    'ticketPriceMinor',f.ticket_price_minor,
    'totalMinor',f.total_minor,
    'currency',f.currency,
    'paidAt',f.paid_at,
    'paymentProvider',f.provider
  );
end;
$function$;

create or replace function private.enqueue_order_payment_receipt_email_v1()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
begin
  if new.payment_status='paid' and (tg_op='INSERT' or old.payment_status is distinct from new.payment_status) then
    insert into private.transactional_email_jobs(kind,aggregate_id,user_id,payload)
    values('order_payment_receipt',new.id,new.user_id,private.build_order_payment_receipt_payload_v1(new.id))
    on conflict(kind,aggregate_id) do nothing;
  end if;
  return new;
end;
$function$;

drop trigger if exists orders_enqueue_payment_receipt_email on public.orders;
create trigger orders_enqueue_payment_receipt_email
after insert or update on public.orders
for each row execute function private.enqueue_order_payment_receipt_email_v1();

create or replace function private.enqueue_event_payment_receipt_email_v1()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
begin
  if new.payment_status='paid' and (tg_op='INSERT' or old.payment_status is distinct from new.payment_status) then
    insert into private.transactional_email_jobs(kind,aggregate_id,user_id,payload)
    values('event_payment_receipt',new.reservation_id,new.user_id,private.build_event_payment_receipt_payload_v1(new.reservation_id))
    on conflict(kind,aggregate_id) do nothing;
  end if;
  return new;
end;
$function$;

drop trigger if exists event_finance_enqueue_payment_receipt_email on private.event_reservation_finance;
create trigger event_finance_enqueue_payment_receipt_email
after insert or update on private.event_reservation_finance
for each row execute function private.enqueue_event_payment_receipt_email_v1();

do $block$
begin
  if not exists(select 1 from vault.secrets where name='golden_oremar_transactional_email_worker') then
    perform vault.create_secret(encode(extensions.gen_random_bytes(32),'hex'),'golden_oremar_transactional_email_worker','Internal token for Golden Oremar transactional email cron worker');
  end if;
  if not exists(select 1 from vault.secrets where name='golden_oremar_project_url') then
    perform vault.create_secret('https://rmfcziawxjgcnxexbrvw.supabase.co','golden_oremar_project_url','Golden Oremar Supabase project URL for internal cron calls');
  end if;
end;
$block$;

create or replace function public.service_validate_transactional_email_worker_v1(p_secret text)
returns boolean
language sql
stable
security definer
set search_path to ''
as $function$
  select coalesce(char_length(p_secret) between 32 and 256,false)
    and exists(select 1 from vault.decrypted_secrets s where s.name='golden_oremar_transactional_email_worker' and s.decrypted_secret=p_secret);
$function$;

create or replace function public.service_claim_transactional_email_jobs_v1(p_worker_id text,p_limit integer default 10)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $function$
declare result jsonb;
begin
  if char_length(btrim(coalesce(p_worker_id,''))) not between 8 and 120 then raise exception 'invalid_worker_id' using errcode='22023'; end if;
  if p_limit not between 1 and 25 then raise exception 'invalid_claim_limit' using errcode='22023'; end if;
  with picked as (
    select j.id
    from private.transactional_email_jobs j
    where j.attempts<8 and j.available_at<=timezone('utc',now())
      and (j.status in ('pending','failed') or (j.status='processing' and j.locked_at<timezone('utc',now())-interval '15 minutes'))
    order by j.available_at,j.id
    for update skip locked
    limit p_limit
  ), claimed as (
    update private.transactional_email_jobs j
    set status='processing',attempts=j.attempts+1,locked_at=timezone('utc',now()),locked_by=btrim(p_worker_id),last_error=null
    where j.id in (select id from picked)
    returning j.id,j.kind,j.aggregate_id,j.payload,j.attempts
  )
  select coalesce(jsonb_agg(jsonb_build_object('id',id,'kind',kind,'aggregateId',aggregate_id,'payload',payload,'attempt',attempts) order by id),'[]'::jsonb)
  into result from claimed;
  return jsonb_build_object('ok',true,'jobs',result);
end;
$function$;

create or replace function public.service_complete_transactional_email_job_v1(p_job_id bigint,p_worker_id text,p_provider_message_id text)
returns boolean
language plpgsql
security definer
set search_path to ''
as $function$
begin
  update private.transactional_email_jobs
  set status='sent',provider_message_id=left(btrim(coalesce(p_provider_message_id,'')),240),sent_at=timezone('utc',now()),locked_at=null,locked_by=null,last_error=null
  where id=p_job_id and status='processing' and locked_by=btrim(coalesce(p_worker_id,''));
  return found;
end;
$function$;

create or replace function public.service_fail_transactional_email_job_v1(p_job_id bigint,p_worker_id text,p_error text,p_retryable boolean default true)
returns boolean
language plpgsql
security definer
set search_path to ''
as $function$
begin
  update private.transactional_email_jobs
  set status=case when coalesce(p_retryable,false) and attempts<8 then 'failed' else 'dead_letter' end,
      available_at=case
        when not coalesce(p_retryable,false) or attempts>=8 then available_at
        when attempts<=1 then timezone('utc',now())+interval '1 minute'
        when attempts=2 then timezone('utc',now())+interval '2 minutes'
        when attempts=3 then timezone('utc',now())+interval '5 minutes'
        when attempts=4 then timezone('utc',now())+interval '15 minutes'
        when attempts=5 then timezone('utc',now())+interval '30 minutes'
        when attempts=6 then timezone('utc',now())+interval '1 hour'
        else timezone('utc',now())+interval '6 hours'
      end,
      last_error=left(btrim(coalesce(p_error,'transactional_email_failed')),500),locked_at=null,locked_by=null
  where id=p_job_id and status='processing' and locked_by=btrim(coalesce(p_worker_id,''));
  return found;
end;
$function$;

create or replace function public.super_admin_list_transactional_email_jobs_v1(p_status text default null,p_limit integer default 50)
returns jsonb
language plpgsql
stable
security definer
set search_path to ''
as $function$
declare normalized text:=nullif(lower(btrim(coalesce(p_status,''))),'' ); result jsonb;
begin
  if auth.uid() is null or not coalesce(private.is_super_admin(),false) then raise exception 'super_admin_required' using errcode='42501'; end if;
  if normalized is not null and normalized not in ('pending','processing','failed','sent','dead_letter') then raise exception 'invalid_email_job_status' using errcode='22023'; end if;
  if p_limit not between 1 and 200 then raise exception 'invalid_limit' using errcode='22023'; end if;
  select coalesce(jsonb_agg(jsonb_build_object('id',j.id,'kind',j.kind,'aggregateId',j.aggregate_id,'status',j.status,'attempts',j.attempts,'availableAt',j.available_at,'providerMessageId',j.provider_message_id,'lastError',j.last_error,'createdAt',j.created_at,'sentAt',j.sent_at) order by j.created_at desc,j.id desc),'[]'::jsonb)
  into result from (select * from private.transactional_email_jobs where normalized is null or status=normalized order by created_at desc,id desc limit p_limit) j;
  return jsonb_build_object('ok',true,'items',result);
end;
$function$;

create or replace function public.super_admin_retry_transactional_email_job_v1(p_job_id bigint)
returns boolean
language plpgsql
security definer
set search_path to ''
as $function$
begin
  if auth.uid() is null or not coalesce(private.is_super_admin(),false) then raise exception 'super_admin_required' using errcode='42501'; end if;
  update private.transactional_email_jobs
  set status='pending',attempts=0,available_at=timezone('utc',now()),locked_at=null,locked_by=null,last_error=null
  where id=p_job_id and status in ('failed','dead_letter');
  return found;
end;
$function$;

revoke all on function public.service_validate_transactional_email_worker_v1(text) from public,anon,authenticated;
revoke all on function public.service_claim_transactional_email_jobs_v1(text,integer) from public,anon,authenticated;
revoke all on function public.service_complete_transactional_email_job_v1(bigint,text,text) from public,anon,authenticated;
revoke all on function public.service_fail_transactional_email_job_v1(bigint,text,text,boolean) from public,anon,authenticated;
grant execute on function public.service_validate_transactional_email_worker_v1(text) to service_role;
grant execute on function public.service_claim_transactional_email_jobs_v1(text,integer) to service_role;
grant execute on function public.service_complete_transactional_email_job_v1(bigint,text,text) to service_role;
grant execute on function public.service_fail_transactional_email_job_v1(bigint,text,text,boolean) to service_role;
revoke all on function public.super_admin_list_transactional_email_jobs_v1(text,integer) from public,anon;
revoke all on function public.super_admin_retry_transactional_email_job_v1(bigint) from public,anon;
grant execute on function public.super_admin_list_transactional_email_jobs_v1(text,integer) to authenticated;
grant execute on function public.super_admin_retry_transactional_email_job_v1(bigint) to authenticated;
