import { supabase } from '../../lib/supabase';

export type ProducerPaymentAccountStatus='pending_configuration'|'onboarding'|'ready'|'suspended'|'failed';
export type ProducerSubmerchantType='PERSONAL'|'PRIVATE_COMPANY'|'LIMITED_OR_JOINT_STOCK_COMPANY';
export type ProducerPaymentKycSource='approved_application'|'legacy_payment_profile'|'missing';
export type ProducerPaymentOnboarding={
 producerId:string;
 producerName:string;
 producerStatus:'active'|'suspended';
 producerVerified:true;
 applicationLinked:boolean;
 kycSource:ProducerPaymentKycSource;
 legacyKycEditable:boolean;
 kyc:{legalNamePresent:boolean;nationalIdPresent:boolean;taxNumberPresent:boolean;taxOfficePresent:boolean;ibanPresent:boolean;bankAccountHolderPresent:boolean;phonePresent:boolean;contactEmailPresent:boolean;addressPresent:boolean;consentPresent:boolean;updatedAt:string|null;};
 paymentAccount:{provider:'iyzico';providerSubmerchantType:ProducerSubmerchantType|null;status:ProducerPaymentAccountStatus;typeConfigured:boolean;ready:boolean;kycCompleteForConfiguredType:boolean;};
};
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const ACCOUNT_STATUSES=new Set<ProducerPaymentAccountStatus>(['pending_configuration','onboarding','ready','suspended','failed']);
const TYPES=new Set<ProducerSubmerchantType>(['PERSONAL','PRIVATE_COMPANY','LIMITED_OR_JOINT_STOCK_COMPANY']);
const SOURCES=new Set<ProducerPaymentKycSource>(['approved_application','legacy_payment_profile','missing']);
function rec(v:unknown):v is Record<string,unknown>{return Boolean(v)&&typeof v==='object'&&!Array.isArray(v);}
function text(v:unknown,label:string,max=240){if(typeof v!=='string')throw new Error(`${label} doğrulanamadı.`);const n=v.trim();if(!n||n.length>max||/[\u0000-\u001F\u007F]/.test(n))throw new Error(`${label} doğrulanamadı.`);return n;}
function bool(v:unknown,label:string){if(typeof v!=='boolean')throw new Error(`${label} doğrulanamadı.`);return v;}
function uuid(v:unknown,label:string){const n=text(v,label,36);if(!UUID_RE.test(n))throw new Error(`${label} doğrulanamadı.`);return n;}
function iso(v:unknown,label:string){if(v==null)return null;const n=text(v,label,80);if(Number.isNaN(Date.parse(n)))throw new Error(`${label} doğrulanamadı.`);return n;}
function normalize(value:unknown):ProducerPaymentOnboarding{if(!rec(value)||!rec(value.kyc)||!rec(value.paymentAccount))throw new Error('Satıcı ödeme hazırlığı yanıtı doğrulanamadı.');const source=text(value.kycSource,'KYC kaynağı',40) as ProducerPaymentKycSource,status=text(value.paymentAccount.status,'Ödeme hesabı durumu',40) as ProducerPaymentAccountStatus,producerStatus=text(value.producerStatus,'Satıcı durumu',30);if(!SOURCES.has(source)||!ACCOUNT_STATUSES.has(status)||!['active','suspended'].includes(producerStatus)||value.producerVerified!==true||value.paymentAccount.provider!=='iyzico')throw new Error('Satıcı ödeme hazırlığı sözleşmeye uymuyor.');let providerSubmerchantType:ProducerSubmerchantType|null=null;if(value.paymentAccount.providerSubmerchantType!=null){providerSubmerchantType=text(value.paymentAccount.providerSubmerchantType,'iyzico alt-üye türü',60) as ProducerSubmerchantType;if(!TYPES.has(providerSubmerchantType))throw new Error('iyzico alt-üye türü doğrulanamadı.');}const k=value.kyc,p=value.paymentAccount;return{producerId:uuid(value.producerId,'Satıcı kimliği'),producerName:text(value.producerName,'Satıcı adı',240),producerStatus:producerStatus as 'active'|'suspended',producerVerified:true,applicationLinked:bool(value.applicationLinked,'Başvuru bağlantısı'),kycSource:source,legacyKycEditable:bool(value.legacyKycEditable,'KYC düzenleme yetkisi'),kyc:{legalNamePresent:bool(k.legalNamePresent,'Yasal ad'),nationalIdPresent:bool(k.nationalIdPresent,'T.C. kimlik'),taxNumberPresent:bool(k.taxNumberPresent,'Vergi numarası'),taxOfficePresent:bool(k.taxOfficePresent,'Vergi dairesi'),ibanPresent:bool(k.ibanPresent,'IBAN'),bankAccountHolderPresent:bool(k.bankAccountHolderPresent,'Hesap sahibi'),phonePresent:bool(k.phonePresent,'Telefon'),contactEmailPresent:bool(k.contactEmailPresent,'E-posta'),addressPresent:bool(k.addressPresent,'Adres'),consentPresent:bool(k.consentPresent,'Ödeme KYC onayı'),updatedAt:iso(k.updatedAt,'KYC güncelleme zamanı')},paymentAccount:{provider:'iyzico',providerSubmerchantType,status,typeConfigured:bool(p.typeConfigured,'Alt-üye türü durumu'),ready:bool(p.ready,'Ödeme hesabı hazırlığı'),kycCompleteForConfiguredType:bool(p.kycCompleteForConfiguredType,'KYC tür uyumu')}};}
export async function getMyProducerPaymentOnboarding(){const{data,error}=await supabase.rpc('get_my_producer_payment_onboarding_v1');if(error)throw error;return normalize(data);}
export async function saveMyProducerPaymentKyc(input:{legalName:string;nationalId:string;taxNumber:string;taxOffice:string;iban:string;bankAccountHolder:string;phone:string;contactEmail:string;addressLine:string;district:string;province:string;postalCode:string;consent:true}){const legalName=input.legalName.trim(),nationalId=input.nationalId.replace(/\D/g,''),taxNumber=input.taxNumber.replace(/\D/g,''),taxOffice=input.taxOffice.trim(),iban=input.iban.replace(/\s+/g,'').toUpperCase(),bankAccountHolder=input.bankAccountHolder.trim(),phone=input.phone.trim(),contactEmail=input.contactEmail.trim().toLowerCase(),addressLine=input.addressLine.trim(),district=input.district.trim(),province=input.province.trim(),postalCode=input.postalCode.trim();if(legalName.length<2||legalName.length>240)throw new Error('Resmi ad/unvan 2 ile 240 karakter arasında olmalıdır.');if(!nationalId&&!taxNumber)throw new Error('T.C. kimlik numarası veya vergi numarasından en az birini girin.');if(nationalId&&nationalId.length!==11)throw new Error('T.C. kimlik numarası 11 rakam olmalıdır.');if(taxNumber&&taxNumber.length!==10)throw new Error('Vergi numarası 10 rakam olmalıdır.');if(taxOffice&&taxOffice.length<2)throw new Error('Vergi dairesi en az 2 karakter olmalıdır.');if(!/^TR[0-9]{24}$/.test(iban))throw new Error('Türkiye IBAN bilgisi TR ile başlayan 26 karakter olmalıdır.');if(bankAccountHolder.length<2)throw new Error('Banka hesap sahibinin adını yazın.');if(phone.replace(/\D/g,'').length<10)throw new Error('Türkiye telefon numarasını kontrol edin.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(contactEmail))throw new Error('Geçerli bir iletişim e-postası yazın.');if(addressLine.length<10||district.length<2||province.length<2)throw new Error('Ödeme KYC adresini eksiksiz yazın.');if(postalCode.length>20)throw new Error('Posta kodu en fazla 20 karakter olabilir.');if(input.consent!==true)throw new Error('Ödeme KYC kullanım onayı gereklidir.');const{data,error}=await supabase.rpc('save_my_producer_payment_kyc_v1',{p_legal_name:legalName,p_national_id:nationalId,p_tax_number:taxNumber,p_tax_office:taxOffice,p_iban:iban,p_bank_account_holder:bankAccountHolder,p_phone:phone,p_contact_email:contactEmail,p_address_line:addressLine,p_district:district,p_province:province,p_postal_code:postalCode,p_consent_version:'producer-payment-kyc-v1'});if(error)throw error;return normalize(data);}
export function producerPaymentErrorMessage(error:unknown,fallback='Ödeme hazırlığı işlemi tamamlanamadı.'){const raw=error instanceof Error?error.message:String((error as{message?:unknown})?.message||'');const map:Array<[string,string]>=[['approved_application_kyc_is_canonical','Ödeme kimliği mevcut onaylı satıcı başvurunuzdan yönetiliyor. Ayrı KYC kaydı oluşturulamaz.'],['producer_payment_account_already_ready','iyzico satıcı ödeme hesabınız zaten hazır. Hassas bilgiler bu formdan değiştirilemez.'],['invalid_turkish_identity','T.C. kimlik numarasını kontrol edin.'],['invalid_tax_number','Vergi numarası 10 rakam olmalıdır.'],['invalid_tr_iban','IBAN doğrulanamadı. Türkiye IBAN bilgisini kontrol edin.'],['invalid_tr_phone','Türkiye telefon numarasını kontrol edin.'],['payment_kyc_consent_required','Ödeme KYC bilgilerinin iyzico alt-üye işyeri kurulumu için kullanılmasına onay vermelisiniz.'],['active_verified_producer_required','Bu işlem yalnız aktif ve doğrulanmış satıcı hesabında kullanılabilir.']];for(const[key,message]of map)if(raw.includes(key))return message;return raw&&raw.length<=320?raw:fallback;}
