import React,{useEffect,useState}from'react';
import{CreditCard,ShieldCheck,X}from'lucide-react';
import{useAccessibleDialog}from'../accessibility/useAccessibleDialog';
import{enrollMyPaymentMethod,type PaymentReadiness,type SavedPaymentMethod}from'./api';
type Props={open:boolean;readiness:PaymentReadiness|null;onClose:()=>void;onSaved:(method:SavedPaymentMethod)=>void|Promise<void>;};
function formatCardInput(value:string){const digits=value.replace(/\D/g,'').slice(0,19);return digits.replace(/(.{4})/g,'$1 ').trim();}function currentYear(){return new Date().getUTCFullYear();}
export default function PaymentMethodEnrollmentDialog({open,readiness,onClose,onSaved}:Props){
 const[cardNumber,setCardNumber]=useState(''),[cardHolder,setCardHolder]=useState(''),[expMonth,setExpMonth]=useState(''),[expYear,setExpYear]=useState(''),[nickname,setNickname]=useState(''),[country,setCountry]=useState(''),[postal,setPostal]=useState(''),[makeDefault,setMakeDefault]=useState(false),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const dialogRef=useAccessibleDialog<HTMLFormElement>(open,()=>{if(!busy)onClose();});const ready=readiness?.cardEnrollmentEnabled===true&&readiness?.savedPaymentMethodsSupported===true&&readiness?.provider==='iyzico';
 useEffect(()=>{if(!open)return;setCardNumber('');setCardHolder('');setExpMonth('');setExpYear('');setNickname('');setCountry('');setPostal('');setMakeDefault(false);setConsent(false);setError('');},[open]);
 async function submit(event:React.FormEvent){event.preventDefault();if(busy)return;if(!ready){setError('Kart kaydetme şu anda kullanıma hazır değil.');return;}if(!consent){setError('Kartınızı kaydetmek için onay kutusunu işaretleyin.');return;}const digits=cardNumber.replace(/\D/g,''),holder=cardHolder.trim(),month=Number(expMonth),year=Number(expYear),alias=nickname.trim(),normalizedCountry=country.trim().toUpperCase(),normalizedPostal=postal.trim();if(digits.length<12||digits.length>19){setError('Kart numarası 12 ile 19 rakam arasında olmalıdır.');return;}if(holder.length<2||holder.length>120){setError('Kart sahibi adı 2 ile 120 karakter arasında olmalıdır.');return;}if(!Number.isSafeInteger(month)||month<1||month>12){setError('Son kullanma ayını kontrol edin.');return;}if(!Number.isSafeInteger(year)||year<currentYear()||year>2200){setError('Son kullanma yılını kontrol edin.');return;}if(alias.length>40){setError('Kart rumuzu en fazla 40 karakter olabilir.');return;}if(normalizedCountry&&!/^[A-Z]{2}$/.test(normalizedCountry)){setError('Fatura ülke kodunu iki harfle girin. Örneğin Türkiye için TR.');return;}if(normalizedPostal.length>30){setError('Fatura posta kodu en fazla 30 karakter olabilir.');return;}try{setBusy(true);setError('');const method=await enrollMyPaymentMethod({cardNumber:digits,cardHolderName:holder,expMonth:month,expYear:year,nickname:alias||null,billingCountryCode:normalizedCountry||null,billingPostalCode:normalizedPostal||null,makeDefault,consentToSaveCard:true});await onSaved(method);onClose();}catch{setError('Kart şu anda kaydedilemedi. Bilgilerinizi kontrol edip yeniden deneyin.');}finally{setBusy(false);}}
 if(!open)return null;return<div className="fixed inset-0 z-[110] overflow-y-auto bg-black/70 p-4" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)onClose();}}><form ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="payment-enrollment-title" aria-describedby="payment-enrollment-description" tabIndex={-1} onSubmit={submit} className="mx-auto my-8 w-full max-w-lg rounded-3xl bg-white p-5 text-brand-text shadow-2xl outline-none dark:bg-gray-900">
  <div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-brand-green dark:text-brand-gold"><CreditCard aria-hidden="true" className="h-5 w-5"/><span className="text-xs font-bold uppercase tracking-[0.14em]">Kayıtlı kart</span></div><h2 id="payment-enrollment-title" className="mt-1 text-xl font-bold">Kartımı kaydet</h2><p id="payment-enrollment-description" className="mt-1 text-sm text-gray-500">Bu kartı sonraki alışverişlerde seçebilmek için güvenli şekilde kaydedebilirsiniz.</p></div><button type="button" disabled={busy} onClick={onClose} aria-label="Kart ekleme penceresini kapat" className="grid min-h-11 min-w-11 place-items-center rounded-xl border disabled:opacity-50"><X aria-hidden="true" className="h-5 w-5"/></button></div>
  {error?<div role="alert" className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>:null}
  <div className={`mt-4 rounded-xl border p-3 text-sm ${ready?'border-green-200 bg-green-50 text-green-900':'border-amber-200 bg-amber-50 text-amber-900'}`}>{ready?'Kart kaydetme kullanıma hazır.':'Kart kaydetme şu anda kullanıma hazır değil.'}</div>
  <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2"><span className="text-sm font-semibold">Kart numarası</span><input value={formatCardInput(cardNumber)} onChange={e=>setCardNumber(e.target.value.replace(/\D/g,'').slice(0,19))} inputMode="numeric" autoComplete="cc-number" required disabled={busy||!ready} className="mt-1 min-h-12 w-full rounded-xl border px-3"/></label><label className="sm:col-span-2"><span className="text-sm font-semibold">Kart üzerindeki ad soyad</span><input value={cardHolder} onChange={e=>setCardHolder(e.target.value.slice(0,120))} autoComplete="cc-name" required disabled={busy||!ready} className="mt-1 min-h-12 w-full rounded-xl border px-3"/></label><label><span className="text-sm font-semibold">Ay</span><input value={expMonth} onChange={e=>setExpMonth(e.target.value.replace(/\D/g,'').slice(0,2))} inputMode="numeric" autoComplete="cc-exp-month" placeholder="MM" required disabled={busy||!ready} className="mt-1 min-h-12 w-full rounded-xl border px-3"/></label><label><span className="text-sm font-semibold">Yıl</span><input value={expYear} onChange={e=>setExpYear(e.target.value.replace(/\D/g,'').slice(0,4))} inputMode="numeric" autoComplete="cc-exp-year" placeholder="YYYY" required disabled={busy||!ready} className="mt-1 min-h-12 w-full rounded-xl border px-3"/></label><label className="sm:col-span-2"><span className="text-sm font-semibold">Kart rumuzu <span className="font-normal text-gray-500">(opsiyonel)</span></span><input value={nickname} onChange={e=>setNickname(e.target.value.slice(0,40))} maxLength={40} disabled={busy||!ready} placeholder="Örn. Günlük kartım" className="mt-1 min-h-12 w-full rounded-xl border px-3"/></label><label><span className="text-sm font-semibold">Fatura ülke kodu</span><input value={country} onChange={e=>setCountry(e.target.value.replace(/[^a-z]/gi,'').toUpperCase().slice(0,2))} maxLength={2} disabled={busy||!ready} placeholder="TR" className="mt-1 min-h-12 w-full rounded-xl border px-3"/></label><label><span className="text-sm font-semibold">Fatura posta kodu</span><input value={postal} onChange={e=>setPostal(e.target.value.slice(0,30))} maxLength={30} disabled={busy||!ready} className="mt-1 min-h-12 w-full rounded-xl border px-3"/></label></div>
  <label className="mt-4 flex min-h-12 items-start gap-3 rounded-2xl border border-brand-green/30 bg-brand-green/5 p-3"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} disabled={busy||!ready} className="mt-1 h-5 w-5"/><span><span className="block font-semibold">Kartımın sonraki alışverişler için kaydedilmesini onaylıyorum.</span><span className="mt-1 block text-xs text-gray-500">Bu onay isteğe bağlıdır. Tek seferlik ödeme için kart kaydetmeniz gerekmez.</span></span></label>
  <label className="mt-3 flex min-h-11 items-center gap-3"><input type="checkbox" checked={makeDefault} onChange={e=>setMakeDefault(e.target.checked)} disabled={busy||!ready} className="h-5 w-5"/><span className="text-sm font-semibold">Varsayılan ödeme yöntemim yap</span></label>
  <div className="mt-4 flex gap-2 rounded-xl bg-gray-50 p-3 text-xs text-gray-600"><ShieldCheck aria-hidden="true" className="mt-0.5 h-4 w-4 shrink-0 text-brand-green"/><p>Kart kaydetme onayınız güvenli şekilde kayıt altına alınır. Kartı daha sonra hesabınızdan kaldırabilirsiniz.</p></div>
  <div className="mt-5 grid grid-cols-2 gap-3"><button type="button" disabled={busy} onClick={onClose} className="min-h-12 rounded-xl border font-semibold">Vazgeç</button><button type="submit" disabled={busy||!ready||!consent} className="min-h-12 rounded-xl bg-brand-green px-4 font-bold text-white disabled:opacity-50">{busy?'Kaydediliyor…':'Kartımı Kaydet'}</button></div>
 </form></div>;
}
